import type { GameJson, ItemBitflag } from "$lib/types";

import {
  abilities,
  abilityCategories,
  characters,
  charactersOrder,
  gameSongs,
  inventory,
  items,
  profiCardCharacters,
  songs,
} from "./utils/resource";

const template: GameJson = {
  validator: {
    fileNames: ["savedata.bk"],
    regions: {
      europe_usa_japan: true,
    },
    text: "Drag 'n' drop here or click to add a save file.",
    hint: 'Works with "savedata.bk" files.',
    error: "Not a valid save file.",
  },
  items: [
    {
      length: 0x3a48,
      type: "container",
      instanceType: "tabs",
      instances: 2,
      enumeration: "Slot %d",
      disableSubinstanceIf: {
        offset: 0x8,
        type: "variable",
        dataType: "uint8",
        operator: "=",
        value: 0x0,
      },
      items: [
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Profile Name",
                              offset: 0x12,
                              length: 0xc,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint16",
                              endCode: 0x0,
                              test: true,
                            },
                            {
                              name: "Rhythmia",
                              offset: 0x2c,
                              type: "variable",
                              dataType: "uint32",
                              max: 999999,
                            },
                            {
                              name: "Playtime",
                              type: "group",
                              mode: "time",
                              items: [
                                {
                                  offset: 0x38,
                                  type: "variable",
                                  dataType: "uint32",
                                  operations: [
                                    {
                                      convert: {
                                        from: "seconds",
                                        to: "hours",
                                      },
                                    },
                                  ],
                                  max: 999,
                                },
                                {
                                  offset: 0x38,
                                  type: "variable",
                                  dataType: "uint32",
                                  operations: [
                                    {
                                      convert: {
                                        from: "seconds",
                                        to: "minutes",
                                      },
                                    },
                                  ],
                                  leadingZeros: 1,
                                  max: 59,
                                },
                                {
                                  offset: 0x38,
                                  type: "variable",
                                  dataType: "uint32",
                                  operations: [
                                    {
                                      convert: {
                                        from: "seconds",
                                        to: "seconds",
                                      },
                                    },
                                  ],
                                  leadingZeros: 1,
                                  max: 59,
                                },
                              ],
                            },
                            {
                              name: "Trophies",
                              offset: 0x3962,
                              type: "variable",
                              dataType: "uint8",
                              disabled: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Equipped Item",
                              offset: 0xd18,
                              type: "variable",
                              dataType: "uint32",
                              resource: "items",
                              autocomplete: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Formation",
                      flex: true,
                      items: [
                        {
                          name: "Character 1",
                          offset: 0xc98,
                          type: "variable",
                          dataType: "uint16",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          name: "Character 2",
                          offset: 0xc9a,
                          type: "variable",
                          dataType: "uint16",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          name: "Character 3",
                          offset: 0xc9c,
                          type: "variable",
                          dataType: "uint16",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          name: "Character 4",
                          offset: 0xc9e,
                          type: "variable",
                          dataType: "uint16",
                          resource: "characters",
                          autocomplete: true,
                        },
                      ],
                    },
                    {
                      name: "Unlocked Modes",
                      flex: true,
                      items: [
                        {
                          type: "bitflags",
                          flags: [
                            { offset: 0x9c, bit: 0, label: "Versus Mode" },
                            { offset: 0xa5, bit: 0, label: "Online Battle" },
                            { offset: 0xa6, bit: 0, label: "Local Battle", separator: true },
                            { offset: 0x9d, bit: 0, label: "Quest Medleys" },
                            { offset: 0xb5, bit: 0, label: "Medium Quest" },
                            { offset: 0xb6, bit: 0, label: "Long Quest" },
                            { offset: 0xb7, bit: 0, label: "Inherited Quest", separator: true },
                            { offset: 0x9e, bit: 0, label: "StreetPass", separator: true },
                            { offset: 0x9f, bit: 0, label: "Museum" },
                            { offset: 0xae, bit: 0, label: "Collection" },
                            { offset: 0xaf, bit: 0, label: "Music Player" },
                            { offset: 0xb0, bit: 0, label: "Theatre", separator: true },
                            { offset: 0xa0, bit: 0, label: "Settings" },
                            { offset: 0xa8, bit: 0, label: "Sound Settings" },
                            { offset: 0xaa, bit: 0, label: "Enter Passwords" },
                            { offset: 0xac, bit: 0, label: "Staff Credits", separator: true },
                            { offset: 0xb1, bit: 0, label: "Edit Party" },
                            { offset: 0xb2, bit: 0, label: "CollectaCard Crystarium" },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Unlocked Characters",
                      flex: true,
                      items: [...Array(4).keys()].map((index) => ({
                        type: "bitflags",
                        flags: Object.entries(characters)
                          .sort(
                            ([indexA], [indexB]) =>
                              charactersOrder.indexOf(parseInt(indexA)) -
                              charactersOrder.indexOf(parseInt(indexB)),
                          )
                          .slice(index * 18, (index + 1) * 18)
                          .map(([index, character]) => ({
                            offset: 0xd1c + parseInt(index) * 0x8e,
                            bit: 1,
                            label: character,
                          })),
                      })),
                    },
                  ],
                },
              ],
            },
            {
              name: "Party",
              items: [
                {
                  length: 0x8e,
                  type: "container",
                  instanceType: "tabs",
                  instances: 65,
                  resource: "characters",
                  resourceOrder: true,
                  vertical: true,
                  items: [
                    {
                      type: "tabs",
                      items: [
                        {
                          name: "Status",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Resets",
                                  offset: 0xd21,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 99,
                                },
                                {
                                  name: "Level",
                                  offset: 0xd20,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 99,
                                },
                                {
                                  name: "Experience",
                                  offset: 0xd1e,
                                  type: "variable",
                                  dataType: "uint16",
                                },
                                {
                                  name: "Play Count",
                                  offset: 0xda6,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                              ],
                            },
                            {
                              name: "Bonus",
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "HP",
                                  offset: 0xd22,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                                {
                                  name: "CP",
                                  offset: 0xd24,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 99,
                                },
                                {
                                  name: "Strength",
                                  offset: 0xd26,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                                {
                                  name: "Agility",
                                  offset: 0xd28,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                                {
                                  name: "Magic",
                                  offset: 0xd2a,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                                {
                                  name: "Luck",
                                  offset: 0xd2c,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                                {
                                  name: "Stamina",
                                  offset: 0xd2e,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                                {
                                  name: "Spirit",
                                  offset: 0xd30,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                              ],
                            },
                            {
                              type: "bitflags",
                              hidden: true,
                              flags: [
                                { offset: 0xd1c, bit: 0, label: "???" },
                                { offset: 0xd1c, bit: 1, label: "Unlocked" },
                                { offset: 0xd1c, bit: 2, label: "New" },
                                { offset: 0xd1c, bit: 3, label: "???" },
                                { offset: 0xd1c, bit: 4, label: "???" },
                                { offset: 0xd1c, bit: 5, label: "???" },
                                { offset: 0xd1c, bit: 6, label: "???" },
                                { offset: 0xd1c, bit: 7, label: "???" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Abilities",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Ability 1",
                                  offset: 0xd74,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "abilities",
                                  autocomplete: true,
                                },
                                {
                                  name: "Ability 2",
                                  offset: 0xd76,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "abilities",
                                  autocomplete: true,
                                },
                                {
                                  name: "Ability 3",
                                  offset: 0xd78,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "abilities",
                                  autocomplete: true,
                                },
                                {
                                  name: "Ability 4",
                                  offset: 0xd7a,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "abilities",
                                  autocomplete: true,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: abilityCategories.map((category) => ({
                                name: category.name,
                                type: "bitflags",
                                flags: category.abilities.map(
                                  (ability, index) => ({
                                    offset:
                                      0xd32 + Math.floor(ability.index / 8),
                                    bit: ability.index % 8,
                                    label: ability.name,
                                    separator:
                                      (category.abilities[index + 1] && Boolean(ability.name.match(/ga$|Lv3/))) ||
                                      Boolean(category.abilities[index + 1]?.name.match(/Lv1/)),
                                  }),
                                ),
                              })),
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Inventory",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: inventory.map((type) => ({
                    name: type.name,
                    flex: true,
                    items: type.items.map((item) => ({
                      id: "quantity",
                      name: item.name,
                      offset: 0xca0 + item.index,
                      type: "variable",
                      dataType: "uint8",
                      binary: { bitStart: 0, bitLength: 7 },
                      max: 99,
                    })),
                  })),
                },
              ],
            },
            {
              name: "Playable Songs",
              flex: true,
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: gameSongs.map((game) => ({
                    name: game.name,
                    items: [
                      {
                        id: "hiddenEvents",
                        type: "bitflags",
                        flags: game.songs.reduce(
                          (songs: ItemBitflag[], song) => {
                            songs.push(
                              { offset: 0x312a + song.index * 3, bit: 1, label: song.name },
                              { offset: 0x312b + song.index * 3, bit: 1, label: song.name, hidden: true },
                              { offset: 0x312c + song.index * 3, bit: 1, label: song.name, hidden: true },
                            );
                            return songs;
                          },
                          [],
                        ),
                      },
                    ],
                  })),
                },
              ],
            },
            {
              name: "Museum",
              items: [
                {
                  type: "tabs",
                  items: [
                    {
                      name: "Records",
                      items: [
                        {
                          type: "tabs",
                          vertical: true,
                          items: [
                            {
                              name: "Total Counts",
                              flex: true,
                              items: [
                                {
                                  name: "Songs played",
                                  offset: 0x3738,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Enemies defeated",
                                  offset: 0x373c,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Distance traveled",
                                  offset: 0x3740,
                                  type: "variable",
                                  dataType: "uint64",
                                  max: 99999999999,
                                },
                                {
                                  name: "Chained triggers",
                                  offset: 0x3748,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                                {
                                  name: "Critical triggers",
                                  offset: 0x374c,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                                {
                                  name: "ProfiCards received",
                                  offset: 0x3750,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 9999,
                                },
                                {
                                  name: "StreetPasses",
                                  offset: 0x3754,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                              ],
                            },
                            {
                              name: "Music Stages",
                              flex: true,
                              items: [
                                {
                                  name: "Total songs cleared",
                                  offset: 0x3780,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Basic Scores cleared",
                                  offset: 0x3784,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Expert Scores cleared",
                                  offset: 0x3788,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Ultimate Scores cleared",
                                  offset: 0x378c,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Perfect Chains achieved",
                                  offset: 0x3790,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Daily Specials cleared",
                                  offset: 0x3794,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Crowns received",
                                  offset: 0x3798,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 9999,
                                },
                                {
                                  name: "SSS ranks received",
                                  offset: 0x379c,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 9999,
                                },
                              ],
                            },
                            {
                              name: "Quest Medleys",
                              flex: true,
                              items: [
                                {
                                  name: "Short Quests cleared",
                                  offset: 0x37b8,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                                {
                                  name: "Medium Quests cleared",
                                  offset: 0x37ba,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                                {
                                  name: "Long Quests cleared",
                                  offset: 0x37bc,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                                {
                                  name: "Inherited Quests cleared",
                                  offset: 0x37be,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                                {
                                  name: "Bosses conquered",
                                  offset: 0x37c0,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                                {
                                  name: "Stages cleared",
                                  offset: 0x37c4,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                                {
                                  name: "Key used",
                                  offset: 0x37c8,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                              ],
                            },
                            {
                              name: "Versus Mode",
                              items: [
                                {
                                  name: "Online Battle Rating",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Rating",
                                      offset: 0x56,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Wins",
                                      offset: 0x37e6,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Losses",
                                      offset: 0x37e8,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Ties",
                                      offset: 0x37ea,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                  ],
                                },
                                {
                                  name: "Local Battle Rating",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Rating",
                                      offset: 0x54,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Wins",
                                      offset: 0x37ee,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Losses",
                                      offset: 0x37f0,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Ties",
                                      offset: 0x37f2,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                  ],
                                },
                                {
                                  name: "Highest Rank",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Rank",
                                      offset: 0x37fa,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "ranks",
                                    },
                                    {
                                      name: "Place",
                                      offset: 0x37fc,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 99,
                                    },
                                  ],
                                },
                                {
                                  name: "Online Scores played",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Basic Score",
                                      offset: 0x37fe,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 9999,
                                    },
                                    {
                                      name: "Expert Score",
                                      offset: 0x3800,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Ultimate Score",
                                      offset: 0x3802,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Ultimate No EX Burst",
                                      offset: 0x3804,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                  ],
                                },
                                {
                                  name: "Local Scores played",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Basic Score",
                                      offset: 0x3806,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 9999,
                                    },
                                    {
                                      name: "Expert Score",
                                      offset: 0x3808,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Ultimate Score",
                                      offset: 0x380a,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "Ultimate No EX Burst",
                                      offset: 0x380c,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "AI Battle victories",
                                      offset: 0x37f6,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                    {
                                      name: "EX Bursts used",
                                      offset: 0x3810,
                                      type: "variable",
                                      dataType: "uint32",
                                      max: 999999,
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              name: "Battle Party",
                              flex: true,
                              items: [
                                {
                                  name: "Levels reset",
                                  offset: 0x3820,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999,
                                },
                                {
                                  name: "CollectaCards obtained",
                                  offset: 0x3824,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                                {
                                  name: "Parameter boosts performed",
                                  offset: 0x3828,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Critical boosts achieved",
                                  offset: 0x382c,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                                {
                                  name: "Items used",
                                  offset: 0x3830,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                                {
                                  name: "Abilities triggered",
                                  offset: 0x3834,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                                {
                                  name: "Fat Chocobo encounters",
                                  offset: 0x3838,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 99999,
                                },
                                {
                                  name: "Treasure chests earned",
                                  offset: 0x383c,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999999,
                                },
                              ],
                            },
                            {
                              name: "Top Songs Played",
                              items: [
                                {
                                  length: 0x8,
                                  type: "container",
                                  instanceType: "section",
                                  instances: 8,
                                  enumeration: "%o Place",
                                  vertical: true,
                                  flex: true,
                                  items: [
                                    {
                                      name: "Song",
                                      offset: 0x3854,
                                      type: "variable",
                                      dataType: "uint32",
                                      resource: "songs",
                                      size: "lg",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Difficulty",
                                      offset: 0x3858,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "difficulties",
                                    },
                                    {
                                      name: "Play Count",
                                      offset: 0x385a,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              name: "Top Characters Used",
                              items: [
                                {
                                  length: 0x8,
                                  type: "container",
                                  instanceType: "section",
                                  instances: 8,
                                  enumeration: "%o Place",
                                  vertical: true,
                                  flex: true,
                                  items: [
                                    {
                                      name: "Character",
                                      offset: 0x38dc,
                                      type: "variable",
                                      dataType: "uint32",
                                      resource: "recordCharacters",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Play Count",
                                      offset: 0x38e2,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 9999,
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              name: "Trophies",
                              items: [
                                {
                                  name: "Chapter 1",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3955, bit: 0, label: "(Maybe with a Perfect Chain...)" },
                                        { offset: 0x3955, bit: 1, label: "(Maybe with an All Critical...)" },
                                        { offset: 0x3955, bit: 2, label: "(If you clear songs with Stylus style...)" },
                                        { offset: 0x3955, bit: 3, label: "(If you clear songs with Button style...)" },
                                        { offset: 0x3955, bit: 4, label: "(Clear songs one-handed and...)" },
                                        { offset: 0x3955, bit: 5, label: "(If you clear songs with Hybrid style...)" },
                                        { offset: 0x3955, bit: 6, label: "(If you can call upon that summon...)" },
                                        { offset: 0x3955, bit: 7, label: "(Maybe if you use StreetPass...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-0",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3948, bit: 0, label: "Achieved first Perfect Chain!" },
                                        { offset: 0x3948, bit: 1, label: "Achieved first All Critical!" },
                                        { offset: 0x3948, bit: 2, label: "Cleared score using Stylus style!" },
                                        { offset: 0x3948, bit: 3, label: "Cleared score using Button style!" },
                                        { offset: 0x3948, bit: 4, label: "Cleared score using One-Handed style!" },
                                        { offset: 0x3948, bit: 5, label: "Cleared score using Hybrid style!" },
                                        { offset: 0x3948, bit: 6, label: "Summoned the Knights of the Round!" },
                                        { offset: 0x3948, bit: 7, label: "Successfully shared ProfiCards!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 2",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3956, bit: 0, label: "(If you defeat the AI in Versus Mode...)" },
                                        { offset: 0x3956, bit: 1, label: "(If you win in an Online Battle...)" },
                                        { offset: 0x3956, bit: 2, label: "(If you win in a Local Battle...)" },
                                        { offset: 0x3956, bit: 3, label: "(If you collect the same kind of shards...)" },
                                        { offset: 0x3956, bit: 4, label: "(If you reset a Lv99 character...)" },
                                        { offset: 0x3956, bit: 5, label: "(With that powerful being at your side...)" },
                                        { offset: 0x3956, bit: 6, label: "(If you keep on summoning)" },
                                        { offset: 0x3956, bit: 7, label: "(If you ride all the chocobos)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-1",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3949, bit: 0, label: "Defeated AI in Versus Mode!" },
                                        { offset: 0x3949, bit: 1, label: "Defeated first online opponent!" },
                                        { offset: 0x3949, bit: 2, label: "Defeated first Local Play opponent!" },
                                        { offset: 0x3949, bit: 3, label: "Collected all shards for a Crystal!" },
                                        { offset: 0x3949, bit: 4, label: "Reset a member's level for the first time!" },
                                        { offset: 0x3949, bit: 5, label: "Unlocked Chaos as team member!" },
                                        { offset: 0x3949, bit: 6, label: "Summonded all of the summons!" },
                                        { offset: 0x3949, bit: 7, label: "Rode on all of the chocobos!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 3",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3957, bit: 0, label: "(If you ride on all of the vehicles...)" },
                                        { offset: 0x3957, bit: 1, label: "(If you see all the Extended Versions...)" },
                                        { offset: 0x3957, bit: 2, label: "(If you player every last song...)" },
                                        { offset: 0x3957, bit: 3, label: "(If you clear every last song...)" },
                                        { offset: 0x3957, bit: 4, label: "(If you defeat every kind of enemy...)" },
                                        { offset: 0x3957, bit: 5, label: "(If you play the game a lot...)" },
                                        { offset: 0x3957, bit: 6, label: "(If you earn a lot of Rhythmia...)" },
                                        { offset: 0x3957, bit: 7, label: "(If you use that summon over and over...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-2",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x394a, bit: 0, label: "Rode on all of the vehicles!" },
                                        { offset: 0x394a, bit: 1, label: "Watched all Extended Versions!" },
                                        { offset: 0x394a, bit: 2, label: "Played every last song!" },
                                        { offset: 0x394a, bit: 3, label: "Cleared every last song!" },
                                        { offset: 0x394a, bit: 4, label: "Defeated every kind of enemy!" },
                                        { offset: 0x394a, bit: 5, label: "Played for more than 100 hours!" },
                                        { offset: 0x394a, bit: 6, label: "Obtained 99,999 Rhythmia!" },
                                        { offset: 0x394a, bit: 7, label: "Summoned Knights of the Round 10 times!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 4",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3958, bit: 0, label: "(If you ride a lot of chocobos...)" },
                                        { offset: 0x3958, bit: 1, label: "(If you meet a lot of moogles...)" },
                                        { offset: 0x3958, bit: 2, label: "(If you meet Fat Chocobo a ton...)" },
                                        { offset: 0x3958, bit: 3, label: "(If you love these Extended Versions...)" },
                                        { offset: 0x3958, bit: 4, label: "(If you keep playing Music Stages...)" },
                                        { offset: 0x3958, bit: 5, label: "(If you play more Music Stages...)" },
                                        { offset: 0x3958, bit: 6, label: "(If you play event more Music Stages...)" },
                                        { offset: 0x3958, bit: 7, label: "(Use lots of abilities and...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-3",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x394b, bit: 0, label: "Rode chocobos 100 times!" },
                                        { offset: 0x394b, bit: 1, label: "Encountered moogles 100 times!" },
                                        { offset: 0x394b, bit: 2, label: "Met Fat Chocobo 100 times!" },
                                        { offset: 0x394b, bit: 3, label: "Watched Extended Versions 50 times!" },
                                        { offset: 0x394b, bit: 4, label: "Played Music Stages 100 times!" },
                                        { offset: 0x394b, bit: 5, label: "Played Music Stages 300 times!" },
                                        { offset: 0x394b, bit: 6, label: "Played Music Stages 500 times!" },
                                        { offset: 0x394b, bit: 7, label: "Activated abilities 500 times!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 5",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3959, bit: 0, label: "(Use a crazy number of abilities!)" },
                                        { offset: 0x3959, bit: 1, label: "(Use a lot of items and then...)" },
                                        { offset: 0x3959, bit: 2, label: "(Use all the items you can find!)" },
                                        { offset: 0x3959, bit: 3, label: "(Keep beating enemies and...)" },
                                        { offset: 0x3959, bit: 4, label: "(Go on, keep beating enemies...)" },
                                        { offset: 0x3959, bit: 5, label: "(Go wild beating enemies!)" },
                                        { offset: 0x3959, bit: 6, label: "(Use amny CollectaCards for boosts and...)" },
                                        { offset: 0x3959, bit: 7, label: "(Keep using the CollectaCard Crystarium...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-4",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x394c, bit: 0, label: "Activated abilities 1,000 times!" },
                                        { offset: 0x394c, bit: 1, label: "Used 50 items in Music Stages!" },
                                        { offset: 0x394c, bit: 2, label: "Used 100 items in Music Stages!" },
                                        { offset: 0x394c, bit: 3, label: "Faces 100 enemies in battles!" },
                                        { offset: 0x394c, bit: 4, label: "Faces 500 enemies in battles!" },
                                        { offset: 0x394c, bit: 5, label: "Faces 1,000 enemies in battles!" },
                                        { offset: 0x394c, bit: 6, label: "Used 10 CollectaCards for boosts!" },
                                        { offset: 0x394c, bit: 7, label: "Used 100 CollectaCards for boosts!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 6",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x395a, bit: 0, label: "(Keep on using the CollectaCard Crystarium...)" },
                                        { offset: 0x395a, bit: 1, label: "(Want to collect ProfiCards?)" },
                                        { offset: 0x395a, bit: 2, label: "(Feel like more ProfiCards?)" },
                                        { offset: 0x395a, bit: 3, label: "(Feel like a heap of ProfiCards?)" },
                                        { offset: 0x395a, bit: 4, label: "(Level up some characters to Lv99 and...)" },
                                        { offset: 0x395a, bit: 5, label: "(Level up many characters to Lv99 and...)" },
                                        { offset: 0x395a, bit: 6, label: "(Level up lots of characters to Lv99 and...)" },
                                        { offset: 0x395a, bit: 7, label: "(Reset members' levels many times and...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-5",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x394d, bit: 0, label: "Used 300 CollectaCards for boosts!" },
                                        { offset: 0x394d, bit: 1, label: "Obtained 15 different ProfiCards!" },
                                        { offset: 0x394d, bit: 2, label: "Obtained 50 different ProfiCards!" },
                                        { offset: 0x394d, bit: 3, label: "Obtained 99 different ProfiCards!" },
                                        { offset: 0x394d, bit: 4, label: "Four characters reached Lv99!" },
                                        { offset: 0x394d, bit: 5, label: "Sixteen characters reached Lv99!" },
                                        { offset: 0x394d, bit: 6, label: "Thirty-two characters reached Lv99!" },
                                        { offset: 0x394d, bit: 7, label: "Reset members' levels 4 times!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 7",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x395b, bit: 0, label: "(Reset members' levels more times and...)" },
                                        { offset: 0x395b, bit: 1, label: "(Reset members' levels even more times and...)" },
                                        { offset: 0x395b, bit: 2, label: "(If you win many Online Battles...)" },
                                        { offset: 0x395b, bit: 3, label: "(If you win more Online Battles...)" },
                                        { offset: 0x395b, bit: 4, label: "(If you win many more Online Battles...)" },
                                        { offset: 0x395b, bit: 5, label: "(Fill up those Critical Charts and...)" },
                                        { offset: 0x395b, bit: 6, label: "(Fill up more Critical Charts and...)" },
                                        { offset: 0x395b, bit: 7, label: "(Rack up those points...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-6",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x394e, bit: 0, label: "Reset members' levels 8 times!" },
                                        { offset: 0x394e, bit: 1, label: "Reset members' levels 12 times!" },
                                        { offset: 0x394e, bit: 2, label: "Won 10 Online Battles!" },
                                        { offset: 0x394e, bit: 3, label: "Won 30 Online Battles!" },
                                        { offset: 0x394e, bit: 4, label: "Won 50 Online Battles!" },
                                        { offset: 0x394e, bit: 5, label: "Filled 10 whole Critical Charts!" },
                                        { offset: 0x394e, bit: 6, label: "Filled 30 whole Critical Charts!" },
                                        { offset: 0x394e, bit: 7, label: "Received one billion points!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 8",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x395c, bit: 0, label: "(Can't have too many points...)" },
                                        { offset: 0x395c, bit: 1, label: "(Is there a limit on points? Want to know?)" },
                                        { offset: 0x395c, bit: 2, label: "(Clear some Short Quest Medleys and...)" },
                                        { offset: 0x395c, bit: 3, label: "(Clear more Short Quest Medleys and...)" },
                                        { offset: 0x395c, bit: 4, label: "(Clear lots of Short Quest Medleys and...)" },
                                        { offset: 0x395c, bit: 5, label: "(Clear some Medium Quest Medleys and...)" },
                                        { offset: 0x395c, bit: 6, label: "(Clear more Medium Quest Medleys and...)" },
                                        { offset: 0x395c, bit: 7, label: "(Clear lots of Medium Quest Medleys and...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-7",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x394f, bit: 0, label: "Received three billion points!" },
                                        { offset: 0x394f, bit: 1, label: "Received five billion points!" },
                                        { offset: 0x394f, bit: 2, label: "Cleared 10 Short Quest Medleys!" },
                                        { offset: 0x394f, bit: 3, label: "Cleared 30 Short Quest Medleys!" },
                                        { offset: 0x394f, bit: 4, label: "Cleared 50 Short Quest Medleys!" },
                                        { offset: 0x394f, bit: 5, label: "Cleared 5 Medium Quest Medleys!" },
                                        { offset: 0x394f, bit: 6, label: "Cleared 15 Medium Quest Medleys!" },
                                        { offset: 0x394f, bit: 7, label: "Cleared 30 Medium Quest Medleys!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 9",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x395d, bit: 0, label: "(Clear some Long Quest Medleys and...)" },
                                        { offset: 0x395d, bit: 1, label: "(Clear more Long Quest Medleys and...)" },
                                        { offset: 0x395d, bit: 2, label: "(Clear lots of Long Quest Medleys and...)" },
                                        { offset: 0x395d, bit: 3, label: "(Clear Inherited Quest Medleys and...)" },
                                        { offset: 0x395d, bit: 4, label: "(Clear more Inherited Quest Medleys and...)" },
                                        { offset: 0x395d, bit: 5, label: "(Clear lots of Inherited Quest Medleys and...)" },
                                        { offset: 0x395d, bit: 6, label: "(If you clear every Basic Score...)" },
                                        { offset: 0x395d, bit: 7, label: "(If you clear every Expert Score...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-8",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3950, bit: 0, label: "Cleared 5 Long Quest Medleys!" },
                                        { offset: 0x3950, bit: 1, label: "Cleared 15 Long Quest Medleys!" },
                                        { offset: 0x3950, bit: 2, label: "Cleared 30 Long Quest Medleys!" },
                                        { offset: 0x3950, bit: 3, label: "Cleared 5 Inherited Quest Medleys!" },
                                        { offset: 0x3950, bit: 4, label: "Cleared 15 Inherited Quest Medleys!" },
                                        { offset: 0x3950, bit: 5, label: "Cleared 30 Inherited Quest Medleys!" },
                                        { offset: 0x3950, bit: 6, label: "Cleared every Basic Score!" },
                                        { offset: 0x3950, bit: 7, label: "Cleared every Expert Score!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 10",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x395e, bit: 0, label: "(If you clear every Ultimate Score...)" },
                                        { offset: 0x395e, bit: 1, label: "(Perfect Chain all Basic Scores and...)" },
                                        { offset: 0x395e, bit: 2, label: "(Perfect Chain all Expert Scores and...)" },
                                        { offset: 0x395e, bit: 3, label: "(Perfect Chain all Ultimate Scores and...)" },
                                        { offset: 0x395e, bit: 4, label: "(Collect all Normal-class CollectaCards...)" },
                                        { offset: 0x395e, bit: 5, label: "(Collect all Rare-class CollectaCards...)" },
                                        { offset: 0x395e, bit: 6, label: "(Collect all Premium-class CollectaCards...)" },
                                        { offset: 0x395e, bit: 7, label: "(Unlock and use all of the characters to...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-9",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3951, bit: 0, label: "Cleared every Ultimate Score!" },
                                        { offset: 0x3951, bit: 1, label: "Perfect Chained all Basic Scores!" },
                                        { offset: 0x3951, bit: 2, label: "Perfect Chained all Expert Scores!" },
                                        { offset: 0x3951, bit: 3, label: "Perfect Chained all Ultimate Scores!" },
                                        { offset: 0x3951, bit: 4, label: "Collected all Normal-class CollectaCards!" },
                                        { offset: 0x3951, bit: 5, label: "Collected all Rare-class CollectaCards!" },
                                        { offset: 0x3951, bit: 6, label: "Collected all Premium-class CollectaCards!" },
                                        { offset: 0x3951, bit: 7, label: "Obtained all playable characters!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 11",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x395f, bit: 0, label: "(Level everyone up to Lv 99 and then...)" },
                                        { offset: 0x395f, bit: 1, label: "(If you fill all Critical Charts...)" },
                                        { offset: 0x395f, bit: 2, label: "(If you collect all of the chimes...)" },
                                        { offset: 0x395f, bit: 3, label: "(If you master the Bronze Class...)" },
                                        { offset: 0x395f, bit: 4, label: "(If you master the Silver Class...)" },
                                        { offset: 0x395f, bit: 5, label: "(If you master the Gold Class...)" },
                                        { offset: 0x395f, bit: 6, label: "(If you master the Platinum Class...)" },
                                        { offset: 0x395f, bit: 7, label: "(If you can critical all 8 card boosts...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-10",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3952, bit: 0, label: "All characters reached Lv99!" },
                                        { offset: 0x3952, bit: 1, label: "Perfectly filled all Critical Charts!" },
                                        { offset: 0x3952, bit: 2, label: "Collected all possible chime variations!" },
                                        { offset: 0x3952, bit: 3, label: "Mastered the Bronze Class!" },
                                        { offset: 0x3952, bit: 4, label: "Mastered the Silver Class!" },
                                        { offset: 0x3952, bit: 5, label: "Mastered the Gold Class!" },
                                        { offset: 0x3952, bit: 6, label: "Mastered the Platinum Class!" },
                                        { offset: 0x3952, bit: 7, label: "Critical boosts on all 8 cards!" },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  name: "Chapter 12",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Hints",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3960, bit: 0, label: "(Cut down many enemies in one BMS and...)" },
                                        { offset: 0x3960, bit: 1, label: "(Cover 10,000m in one FMS and...)" },
                                        { offset: 0x3960, bit: 2, label: "(Use lots of abilities in one song and...)" },
                                        { offset: 0x3960, bit: 3, label: "(Use lots of EX Bursts in one song and...)" },
                                        { offset: 0x3960, bit: 4, label: "(If you defeat many enemies in a quest...)" },
                                        { offset: 0x3960, bit: 5, label: "(If you cover a great distance in a quest...)" },
                                        { offset: 0x3960, bit: 6, label: "(Restore a lot of HP during a quest and...)" },
                                        { offset: 0x3960, bit: 7, label: "(Face that fearsome Quest Medley foe and...)" },
                                      ],
                                    },
                                    {
                                      id: "trophies-11",
                                      name: "Obtained",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x3953, bit: 0, label: "Beat 7 or more enemies in one BMS!" },
                                        { offset: 0x3953, bit: 1, label: "Covered 10,000m or more in a single song!" },
                                        { offset: 0x3953, bit: 2, label: "Activated 10 or more abilities in one song!" },
                                        { offset: 0x3953, bit: 3, label: "Triggered 10 or more EX Bursts in one song!" },
                                        { offset: 0x3953, bit: 4, label: "Defeated 50 or more enemies in a quest!" },
                                        { offset: 0x3953, bit: 5, label: "Covered over 50,000m during a quest!" },
                                        { offset: 0x3953, bit: 6, label: "Restored 500% of max HP during one quest!" },
                                        { offset: 0x3953, bit: 7, label: "Beat Feral Chaos during a Quest Medley!" },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Collection",
                      items: [
                        {
                          length: 0x3,
                          type: "container",
                          instanceType: "tabs",
                          instances: 162,
                          resource: "cards",
                          vertical: true,
                          items: [
                            {
                              name: "Normal",
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Status",
                                  offset: 0x3497,
                                  type: "variable",
                                  dataType: "bit",
                                  bit: 7,
                                  resource: "booleanAcquired",
                                },
                                {
                                  id: "quantity",
                                  name: "Quantity",
                                  offset: 0x3497,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: { bitStart: 0, bitLength: 7 },
                                  max: 99,
                                },
                              ],
                            },
                            {
                              name: "Rare",
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Status",
                                  offset: 0x3498,
                                  type: "variable",
                                  dataType: "bit",
                                  bit: 7,
                                  resource: "booleanAcquired",
                                },
                                {
                                  id: "quantity",
                                  name: "Quantity",
                                  offset: 0x3498,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: { bitStart: 0, bitLength: 7 },
                                  max: 99,
                                },
                              ],
                            },
                            {
                              name: "Premium",
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Status",
                                  offset: 0x3499,
                                  type: "variable",
                                  dataType: "bit",
                                  bit: 7,
                                  resource: "booleanAcquired",
                                },
                                {
                                  id: "quantity",
                                  name: "Quantity",
                                  offset: 0x3499,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: { bitStart: 0, bitLength: 7 },
                                  max: 99,
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Theatre",
                      items: [
                        {
                          name: "Movies",
                          type: "bitflags",
                          flags: [
                            { offset: 0x348d, bit: 0, label: "???", hidden: true },
                            { offset: 0x348d, bit: 1, label: "Movie from FINAL FANTASY XIV" },
                            { offset: 0x348d, bit: 2, label: "Movie from FINAL FANTASY TACTICS" },
                            { offset: 0x348d, bit: 3, label: "Movie from FINAL FANTASY X-2" },
                            { offset: 0x348d, bit: 4, label: "Movie from FINAL FANTASY CRYSTAL CHRONICLES" },
                            { offset: 0x348d, bit: 5, label: "Movie from FINAL FANTASY VII: Advent Children" },
                            { offset: 0x348d, bit: 6, label: "Movie from CRISIS CORE -FINAL FANTASY VII-" },
                            { offset: 0x348d, bit: 7, label: "Movie from DISSIDIA 012[duodecim] FINAL FANTASY" },
                            { offset: 0x348e, bit: 0, label: "Movie from FINAL FANTASY TYPE-0" },
                            { offset: 0x348e, bit: 1, label: "Movie from FINAL FANTASY XIII-2" },
                            { offset: 0x348e, bit: 2, label: "Movie from LIGHTNING RETURNS: FINAL FANTASY XIII" },
                            { offset: 0x348e, bit: 3, label: "Movie from FINAL FANTASY I-XIV" },
                            { offset: 0x348e, bit: 4, label: "???", hidden: true },
                            { offset: 0x348e, bit: 5, label: "???", hidden: true },
                            { offset: 0x348e, bit: 6, label: "???", hidden: true },
                            { offset: 0x348e, bit: 7, label: "???", hidden: true },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Music Player",
                      items: [
                        {
                          type: "tabs",
                          vertical: true,
                          items: gameSongs.map((game) => ({
                            name: game.name,
                            items: [
                              {
                                name: "Songs",
                                type: "bitflags",
                                flags: game.songs.map((song) => ({
                                  offset: 0x33ca + Math.floor(song.index / 8),
                                  bit: song.index % 8,
                                  label: song.name,
                                })),
                              },
                            ],
                          })),
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    abilities: {
      ...abilities,
      0xffff: "-",
    },
    booleanAcquired: {
      0x0: "-",
      0x1: "Acquired",
    },
    booleanUnlocked: {
      0x0: "-",
      0x1: "Unlocked",
    },
    cards: {
      0x0: "#001 Warrior of Light",
      0x1: "#002 Princess Sarah",
      0x2: "#003 Firion",
      0x3: "#004 Minwu",
      0x4: "#005 Onion Knight",
      0x5: "#006 Cid",
      0x6: "#007 Cecil",
      0x7: "#008 Rydia",
      0x8: "#009 Kain",
      0x9: "#010 Edge",
      0xa: "#011 Bartz",
      0xb: "#012 Faris",
      0xc: "#013 Lenna",
      0xd: "#014 Galuf",
      0xe: "#015 Terra",
      0xf: "#016 Locke",
      0x10: "#017 Celes",
      0x11: "#018 Edgar",
      0x12: "#019 Cloud",
      0x13: "#020 Aerith",
      0x14: "#021 Tifa",
      0x15: "#022 Barret",
      0x16: "#023 Sephiroth",
      0x17: "#024 Squall",
      0x18: "#025 Seifer",
      0x19: "#026 Rinoa",
      0x1a: "#027 Laguna",
      0x1b: "#028 Zidane",
      0x1c: "#029 Vivi",
      0x1d: "#030 Garnet",
      0x1e: "#031 Eiko",
      0x1f: "#032 Tidus",
      0x20: "#033 Yuna",
      0x21: "#034 Auron",
      0x22: "#035 Jecht",
      0x23: "#036 Shantotto",
      0x24: "#037 Prishe",
      0x25: "#038 Aphmau",
      0x26: "#039 Lilisette",
      0x27: "#040 Vaan",
      0x28: "#041 Ashe",
      0x29: "#042 Balthier",
      0x2a: "#043 Fran",
      0x2b: "#044 Lightning",
      0x2c: "#045 Snow",
      0x2d: "#046 Hope",
      0x2e: "#047 Vanille",
      0x2f: "#048 Y'shtola",
      0x30: "#049 Benjamin",
      0x31: "#050 Ramza",
      0x32: "#051 Agrias",
      0x33: "#052 Yuna #2",
      0x34: "#053 Rikku",
      0x35: "#054 Paine",
      0x36: "#055 Ciaran",
      0x37: "#056 Tifa #2",
      0x38: "#057 Zack",
      0x39: "#058 Cosmos",
      0x3a: "#059 Chaos",
      0x3b: "#060 Ace",
      0x3c: "#061 Machina",
      0x3d: "#062 Rem",
      0x3e: "#063 Serah",
      0x3f: "#064 Noel",
      0x40: "#065 Lightning #2",
      0x41: "#066 Chocobo",
      0x42: "#067 Fat Chocobo",
      0x43: "#068 Moogle",
      0x44: "#069 Curtain Call Heroes",
      0x45: "#070 Chocobo",
      0x46: "#071 Shiva",
      0x47: "#072 Ramuh",
      0x48: "#073 Ifrit",
      0x49: "#074 Odin",
      0x4a: "#075 Bahamut",
      0x4b: "#076 Knights of the Round",
      0x4c: "#077 Lich",
      0x4d: "#078 Chaos",
      0x4e: "#079 Captain",
      0x4f: "#080 Black Knight",
      0x50: "#081 Emperor",
      0x51: "#082 Hein",
      0x52: "#083 Xande",
      0x53: "#084 Cloud of Darkness",
      0x54: "#085 Scarmiglione",
      0x55: "#086 Cagnazzo",
      0x56: "#087 Barbariccia",
      0x57: "#088 Rubicante",
      0x58: "#089 Golbez",
      0x59: "#090 Zeromus",
      0x5a: "#091 Objet d'Art",
      0x5b: "#092 Enkidu",
      0x5c: "#093 Gilgamesh",
      0x5d: "#094 Omega",
      0x5e: "#095 Shinryu",
      0x5f: "#096 Exdeath",
      0x60: "#097 Magitek Armor",
      0x61: "#098 Ultros",
      0x62: "#099 Typhon",
      0x63: "#100 Deathgaze",
      0x64: "#101 Kefka Palazzo",
      0x65: "#102 Kefka",
      0x66: "#103 Reno",
      0x67: "#104 Ultimate Weapon",
      0x68: "#105 Diamond Weapon",
      0x69: "#106 Jenova - SYNTHESIS",
      0x6a: "#107 Safer - Sephiroth",
      0x6b: "#108 Esthar Soldier",
      0x6c: "#109 Gesper",
      0x6d: "#110 PuPu",
      0x6e: "#111 Tonberry King",
      0x6f: "#112 Gigantuar",
      0x70: "#113 Edea",
      0x71: "#114 Ultimecia",
      0x72: "#115 Black Waltz No. 3",
      0x73: "#116 Ozma",
      0x74: "#117 Trance Kuja",
      0x75: "#118 Necron",
      0x76: "#119 Anima",
      0x77: "#120 Seymour Natus",
      0x78: "#121 Braska's Final Aeon",
      0x79: "#122 Gigas",
      0x7a: "#123 Goobbue",
      0x7b: "#124 The Shadow Lord",
      0x7c: "#125 Eald'narche",
      0x7d: "#126 Bangaa Thief",
      0x7e: "#127 Mandragoras",
      0x7f: "#128 Gabranth",
      0x80: "#129 The Undying",
      0x81: "#130 Yiazmat",
      0x82: "#131 PSICOM Enforcer",
      0x83: "#132 Manasvin Warmech",
      0x84: "#133 Orphan",
      0x85: "#134 Ultima, the High Sera",
      0x86: "#135 Bahamut SIN",
      0x87: "#136 Manikin",
      0x88: "#137 Feral Chaos",
      0x89: "#138 Colossus",
      0x8a: "#139 Atlas",
      0x8b: "#140 Goblin",
      0x8c: "#141 Green Dragon",
      0x8d: "#142 Iron Giant",
      0x8e: "#143 Ahriman",
      0x8f: "#144 Sand Worm",
      0x90: "#145 Zu",
      0x91: "#146 Magic Pot",
      0x92: "#147 Lamia",
      0x93: "#148 Tonberry",
      0x94: "#149 Mover",
      0x95: "#150 Cactuar",
      0x96: "#151 Hill Gigas",
      0x97: "#152 Coeurl",
      0x98: "#153 Sahagin",
      0x99: "#154 Adamantoise",
      0x9a: "#155 Bomb",
      0x9b: "#156 King Bomb",
      0x9c: "#157 Malboro",
      0x9d: "#158 Great Malboro",
      0x9e: "#159 Flan",
      0x9f: "#160 Jumbo Flan",
      0xa0: "#161 Behemoth",
      0xa1: "#162 King Behemoth",
    },
    characters,
    difficulties: {
      0x0: "Basic Score",
      0x1: "Expert Score",
      0x2: "Ultimate Score",
    },
    items: {
      ...items,
      0xffffffff: "-",
    },
    profiCardCharacters,
    ranks: {
      0x0: "Bronze",
      0x1: "Silver",
      0x2: "Gold",
      0x3: "Platinum",
    },
    recordCharacters: {
      ...characters,
      0xffffffff: "-",
    },
    songs: {
      ...songs,
      0xffffffff: "-",
    },
  },
  resourcesGroups: {
    abilities: [
      {
        name: abilityCategories[0].name,
        options: abilityCategories[0].abilities.map((ability) => ability.index),
      },
      {
        name: abilityCategories[1].name,
        options: abilityCategories[1].abilities.map((ability) => ability.index),
      },
    ],
    items: [
      {
        name: inventory[0].name,
        options: inventory[0].items.map((item) => item.index),
      },
      {
        name: inventory[4].name,
        options: inventory[4].items.map((item) => item.index),
      },
    ],
    songs: gameSongs.map((game) => ({
      name: game.name,
      options: game.songs.map((song) => song.index),
    })),
  },
  resourcesOrder: {
    abilities: [0xffff],
    characters: charactersOrder,
    items: [0xffffffff],
    recordCharacters: [0xffffffff],
    songs: [0xffffffff],
  },
};

export default template;
