import type { GameJson } from "$lib/types";

import { enemies } from "./utils/resource";

const template: GameJson = {
  validator: {
    regions: {
      europe: {
        0x0: [
          0x43, 0x41, 0x53, 0x54, 0x4c, 0x45, 0x56, 0x41, 0x4e, 0x49, 0x41,
          0x32, 0x2d, 0x30, 0x31, 0x30,
        ], // "CASTLEVANIA2-010"
      },
      usa: {
        0x0: [
          0x43, 0x41, 0x53, 0x54, 0x4c, 0x45, 0x56, 0x41, 0x4e, 0x49, 0x41,
          0x32, 0x2d, 0x30, 0x31, 0x30,
        ], // "CASTLEVANIA2-010"
      },
      japan: {
        0x0: [
          0x43, 0x41, 0x53, 0x54, 0x4c, 0x45, 0x56, 0x41, 0x4e, 0x49, 0x41,
          0x32, 0x2d, 0x30, 0x31, 0x30,
        ], // "CASTLEVANIA2-010"
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    hint: "Compatible with Castlevania Advance Collection.",
    error: "Not a valid save file.",
  },
  items: [
    {
      length: 0x8f8,
      type: "container",
      instanceType: "tabs",
      instances: 3,
      enumeration: "Slot %d",
      disableSubinstanceIf: {
        offset: 0x2d,
        type: "variable",
        dataType: "uint8",
        operator: "=",
        value: 0x0,
      },
      prependSubinstance: [
        {
          name: "General",
          items: [
            {
              id: "language",
              name: "Language",
              offset: 0x1afc,
              type: "variable",
              dataType: "uint8",
              resource: "languages",
              test: true,
            },
            {
              name: "Unlocked Modes",
              type: "bitflags",
              flags: [
                { offset: 0x1af8, bit: 0, label: "Hard Mode" },
                { offset: 0x1af8, bit: 0, label: "Boss Rush" },
                { offset: 0x1af8, bit: 0, label: "Sound Test", separator: true },
                { offset: 0x1af8, bit: 1, label: "Julius Mode" },
                { offset: 0x1af8, bit: 1, label: "No Use Mode" },
                { offset: 0x1af8, bit: 1, label: "No Soul Mode" },
              ],
            },
          ],
        },
      ],
      items: [
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Filename",
                              offset: 0x1a0,
                              length: 0x8,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              resource: "letters",
                              test: true,
                            },
                            {
                              name: "Difficulty",
                              offset: 0x1ad,
                              type: "variable",
                              dataType: "bit",
                              bit: 4,
                              resource: "difficulties",
                            },
                            {
                              name: "Progression",
                              offset: 0x1ad,
                              type: "variable",
                              dataType: "bit",
                              bit: 0,
                              resource: "progressions",
                            },
                            {
                              name: "Handicaps",
                              offset: 0x452,
                              type: "variable",
                              dataType: "uint8",
                              binary: { bitStart: 4, bitLength: 2 },
                              resource: "handicaps",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Playtime",
                              type: "group",
                              mode: "time",
                              items: [
                                {
                                  offset: 0x1b8,
                                  type: "variable",
                                  dataType: "uint32",
                                  operations: [
                                    { "/": 60 },
                                    {
                                      convert: { from: "seconds", to: "hours" },
                                    },
                                  ],
                                  max: 99,
                                },
                                {
                                  offset: 0x1b8,
                                  type: "variable",
                                  dataType: "uint32",
                                  operations: [
                                    { "/": 60 },
                                    {
                                      convert: {
                                        from: "seconds",
                                        to: "minutes",
                                      },
                                    },
                                  ],
                                  leadingZeros: 1,
                                  max: 59,
                                },
                                {
                                  offset: 0x1b8,
                                  type: "variable",
                                  dataType: "uint32",
                                  operations: [
                                    { "/": 60 },
                                    {
                                      convert: {
                                        from: "seconds",
                                        to: "seconds",
                                      },
                                    },
                                  ],
                                  leadingZeros: 1,
                                  max: 59,
                                },
                              ],
                            },
                            {
                              name: "Location",
                              offset: 0x1aa,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "locations",
                              size: "lg",
                              autocomplete: true,
                            },
                            {
                              id: "gold",
                              name: "Gold",
                              offset: 0x44,
                              type: "variable",
                              dataType: "uint32",
                              max: 999999,
                            },
                            {
                              name: "Gold (Save Preview)",
                              offset: 0x1b4,
                              type: "variable",
                              dataType: "uint32",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Is Copy",
                              offset: 0x1ae,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Position X",
                              offset: 0x444,
                              type: "variable",
                              dataType: "uint16",
                              hidden: true,
                            },
                            {
                              name: "Position Y",
                              offset: 0x446,
                              type: "variable",
                              dataType: "uint16",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Warp Rooms",
                      items: [
                        {
                          type: "bitflags",
                          flags: [
                            { offset: 0x484, bit: 0, label: "Castle Corridor" },
                            { offset: 0x484, bit: 1, label: "Dance Hall" },
                            { offset: 0x484, bit: 2, label: "Inner Quarters" },
                            { offset: 0x484, bit: 3, label: "Top Floor" },
                            { offset: 0x484, bit: 4, label: "Clock Tower" },
                            { offset: 0x484, bit: 5, label: "Chapel" },
                            { offset: 0x484, bit: 6, label: "Underground Reservoir" },
                            { offset: 0x484, bit: 7, label: "The Arena" },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Status",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Character",
                              offset: 0x1a,
                              type: "variable",
                              dataType: "uint8",
                              resource: "characters",
                              disabled: true,
                            },
                            {
                              id: "level",
                              name: "Level",
                              offset: 0x2d,
                              type: "variable",
                              dataType: "uint8",
                              min: 1,
                              max: 99,
                            },
                            {
                              name: "Level (Save Preview)",
                              offset: 0x1ac,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Experience",
                              offset: 0x40,
                              type: "variable",
                              dataType: "uint32",
                              max: 99999999,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "HP",
                              type: "group",
                              mode: "fraction",
                              items: [
                                {
                                  offset: 0x2e,
                                  type: "variable",
                                  dataType: "uint16",
                                  min: 1,
                                  max: 9999,
                                },
                                {
                                  offset: 0x32,
                                  type: "variable",
                                  dataType: "uint16",
                                  min: 1,
                                  max: 9999,
                                },
                              ],
                            },
                            {
                              name: "MP",
                              type: "group",
                              mode: "fraction",
                              items: [
                                {
                                  offset: 0x30,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                                {
                                  offset: 0x34,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                              ],
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Strength",
                              offset: 0x36,
                              type: "variable",
                              dataType: "uint16",
                              min: 1,
                              max: 999,
                            },
                            {
                              name: "Constitution",
                              offset: 0x38,
                              type: "variable",
                              dataType: "uint16",
                              min: 1,
                              max: 999,
                            },
                            {
                              name: "Intelligence",
                              offset: 0x3a,
                              type: "variable",
                              dataType: "uint16",
                              min: 1,
                              max: 999,
                            },
                            {
                              name: "Luck",
                              offset: 0x3c,
                              type: "variable",
                              dataType: "uint16",
                              min: 1,
                              max: 999,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Equipped Souls",
                      flex: true,
                      items: [
                        {
                          name: "Bullet Soul",
                          offset: 0x1d,
                          type: "variable",
                          dataType: "uint8",
                          resource: "bulletSouls",
                          autocomplete: true,
                        },
                        {
                          name: "Guardian Soul",
                          offset: 0x1e,
                          type: "variable",
                          dataType: "uint8",
                          resource: "guardianSouls",
                          autocomplete: true,
                        },
                        {
                          name: "Enchanted Soul",
                          offset: 0x1f,
                          type: "variable",
                          dataType: "uint8",
                          resource: "enchantedSouls",
                          autocomplete: true,
                        },
                      ],
                    },
                    {
                      name: "Equipped Gears",
                      flex: true,
                      items: [
                        {
                          name: "Hand",
                          offset: 0x1c,
                          type: "variable",
                          dataType: "uint8",
                          resource: "hand",
                          autocomplete: true,
                        },
                        {
                          name: "Body",
                          offset: 0x20,
                          type: "variable",
                          dataType: "uint8",
                          resource: "body",
                          autocomplete: true,
                        },
                        {
                          name: "Accessory",
                          offset: 0x21,
                          type: "variable",
                          dataType: "uint8",
                          resource: "accessories",
                          autocomplete: true,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Souls",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Bullet Souls",
                      flex: true,
                      items: [
                        {
                          name: "Killer Mantle",
                          offset: 0xea,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Disc Armor",
                          offset: 0xde,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Mudman",
                          offset: 0xda,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Killer Doll",
                          offset: 0xe9,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Winged Skeleton",
                          offset: 0xd0,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Bat",
                          offset: 0xd0,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Skeleton",
                          offset: 0xd1,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Merman",
                          offset: 0xd1,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Axe Armor",
                          offset: 0xd2,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Skull Archer",
                          offset: 0xd2,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Killer Fish",
                          offset: 0xd3,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Blue Crow",
                          offset: 0xd3,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Zombie Solider",
                          offset: 0xd4,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Ghost",
                          offset: 0xd4,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Siren",
                          offset: 0xd5,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Tiny Devil",
                          offset: 0xd5,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Durga",
                          offset: 0xd6,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Rock Armor",
                          offset: 0xd6,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Student Witch",
                          offset: 0xd7,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Arachne",
                          offset: 0xd7,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Fleaman",
                          offset: 0xd8,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Evil Butcher",
                          offset: 0xd8,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Waiter Skeleton",
                          offset: 0xd9,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Altair",
                          offset: 0xd9,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Cockatrice",
                          offset: 0xda,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Werewolf",
                          offset: 0xdb,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Harpy",
                          offset: 0xdb,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Une",
                          offset: 0xdc,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Needles",
                          offset: 0xdc,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Man-Eater",
                          offset: 0xdd,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Ukoback",
                          offset: 0xdd,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Fish Head",
                          offset: 0xde,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Nightmare",
                          offset: 0xdf,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Slime",
                          offset: 0xdf,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Dryad",
                          offset: 0xe0,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Ripper",
                          offset: 0xe0,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Werejaguar",
                          offset: 0xe1,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Weretiger",
                          offset: 0xe1,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Biphron",
                          offset: 0xe2,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Mandragora",
                          offset: 0xe2,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Beam Skeleton",
                          offset: 0xe3,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Skull Millione",
                          offset: 0xe3,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Giant Skeleton",
                          offset: 0xe4,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Gladiator",
                          offset: 0xe4,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Demon Lord",
                          offset: 0xe5,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Flame Demon",
                          offset: 0xe5,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Lightning Doll",
                          offset: 0xe6,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Valkyrie",
                          offset: 0xe6,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Bomber Armor",
                          offset: 0xe7,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Red Minotaur",
                          offset: 0xe7,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Legion",
                          offset: 0xe8,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Balore",
                          offset: 0xe8,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Nemesis",
                          offset: 0xe9,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Kyoma Demon",
                          offset: 0xea,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Chronomage",
                          offset: 0xeb,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                      ],
                    },
                    {
                      name: "Guardian Souls",
                      flex: true,
                      items: [
                        {
                          name: "Devil",
                          offset: 0x110,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Alastor",
                          offset: 0x113,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Great Armor",
                          offset: 0x10b,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Giant Bat",
                          offset: 0x108,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Flying Armor",
                          offset: 0x108,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Black Panther",
                          offset: 0x109,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Buer",
                          offset: 0x109,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Witch",
                          offset: 0x10a,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Giant Ghost",
                          offset: 0x10a,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Final Guard",
                          offset: 0x10b,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Catoblepas",
                          offset: 0x10c,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Bone Pillar",
                          offset: 0x10c,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Cagnazzo",
                          offset: 0x10d,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Big Golem",
                          offset: 0x10d,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Shadow Knight",
                          offset: 0x10e,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Creaking Skull",
                          offset: 0x10e,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Medusa Head",
                          offset: 0x10f,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Persephone",
                          offset: 0x10f,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Alura Une",
                          offset: 0x110,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Manticore",
                          offset: 0x111,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Curly",
                          offset: 0x111,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Sky Fish",
                          offset: 0x112,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Imp",
                          offset: 0x112,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Death",
                          offset: 0x113,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                      ],
                    },
                    {
                      name: "Enchanted Souls",
                      flex: true,
                      items: [
                        {
                          name: "Gremlin",
                          offset: 0x133,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Skula",
                          offset: 0x122,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Dead Crusader",
                          offset: 0x130,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Undine",
                          offset: 0x122,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Zombie Officer",
                          offset: 0x123,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Iron Golem",
                          offset: 0x123,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Dead Warrior",
                          offset: 0x124,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Peeping Eye",
                          offset: 0x124,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Succubus",
                          offset: 0x125,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Flesh Golem",
                          offset: 0x125,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Tsuchinoko",
                          offset: 0x126,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Giant Worm",
                          offset: 0x126,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Wooden Golem",
                          offset: 0x127,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Zombie",
                          offset: 0x127,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Lubicant",
                          offset: 0x128,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Headhunter",
                          offset: 0x128,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Basilisk",
                          offset: 0x129,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Erinys",
                          offset: 0x129,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Mimic",
                          offset: 0x12a,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Arc Demon",
                          offset: 0x12a,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Poison Worm",
                          offset: 0x12b,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Ectoplasm",
                          offset: 0x12b,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Gargoyle",
                          offset: 0x12c,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Skeleton Knight",
                          offset: 0x12c,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Minotaur",
                          offset: 0x12d,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Golem",
                          offset: 0x12d,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Triton",
                          offset: 0x12e,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "White Dragon",
                          offset: 0x12e,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Quezcoatl",
                          offset: 0x12f,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Gorgon",
                          offset: 0x12f,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Red Crow",
                          offset: 0x130,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Lilith",
                          offset: 0x131,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Bael",
                          offset: 0x131,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                        {
                          name: "Stolas",
                          offset: 0x132,
                          type: "variable",
                          dataType: "lower4",
                          max: 15,
                        },
                        {
                          name: "Ghost Dancer",
                          offset: 0x132,
                          type: "variable",
                          dataType: "upper4",
                          max: 15,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Inventory",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Weapons",
                      flex: true,
                      items: [
                        {
                          name: "Knife",
                          offset: 0x68,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Baselard",
                          offset: 0x69,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Combat Knife",
                          offset: 0x6a,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Short Sword",
                          offset: 0x6b,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Bastard Sword",
                          offset: 0x6c,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Whip Sword",
                          offset: 0x6d,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Gladius",
                          offset: 0x6e,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Gram",
                          offset: 0x6f,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Milican's Sword",
                          offset: 0x70,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Hrunting",
                          offset: 0x71,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Mystletain",
                          offset: 0x72,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Rahab's Sword",
                          offset: 0x73,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Durandal",
                          offset: 0x74,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Laevatain",
                          offset: 0x75,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Burtgang",
                          offset: 0x76,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Kaladbolg",
                          offset: 0x77,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Vjaya",
                          offset: 0x78,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Balmung",
                          offset: 0x79,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Broadsword",
                          offset: 0x7a,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Scimitar",
                          offset: 0x7b,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Claymore",
                          offset: 0x7c,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Great Sword",
                          offset: 0x7d,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Joyeuse",
                          offset: 0x7e,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Dainslef",
                          offset: 0x7f,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Ascalon",
                          offset: 0x80,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Claimh Solais",
                          offset: 0x81,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Final Sword",
                          offset: 0x82,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Bamboo Sword",
                          offset: 0x83,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Katana",
                          offset: 0x84,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Osafune",
                          offset: 0x85,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Onikiri",
                          offset: 0x86,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Kunitsuna",
                          offset: 0x87,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Yasutsuna",
                          offset: 0x88,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Muramasa",
                          offset: 0x89,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Hammer",
                          offset: 0x8a,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Warhammer",
                          offset: 0x8b,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Excalibur",
                          offset: 0x8c,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Tallhammer",
                          offset: 0x8d,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Battle Axe",
                          offset: 0x8e,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Death's Sickle",
                          offset: 0x8f,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Rapier",
                          offset: 0x90,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Estoc",
                          offset: 0x91,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Cutall",
                          offset: 0x92,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Spear",
                          offset: 0x93,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Trident",
                          offset: 0x94,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Lance",
                          offset: 0x95,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Partizan",
                          offset: 0x96,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Gabolg",
                          offset: 0x97,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Gungner",
                          offset: 0x98,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Ronginus' Spear",
                          offset: 0x99,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Cestus",
                          offset: 0x9a,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Kaiser Knuckle",
                          offset: 0x9b,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Mach Punch",
                          offset: 0x9c,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Whip Knuckle",
                          offset: 0x9d,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Poison Fist",
                          offset: 0x9e,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Handgun",
                          offset: 0x9f,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Silver Gun",
                          offset: 0xa0,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Positron Rifle",
                          offset: 0xa1,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Valmanway",
                          offset: 0xa2,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                      ],
                    },
                    {
                      name: "Armors",
                      flex: true,
                      items: [
                        {
                          name: "Casual Clothes",
                          offset: 0xa3,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Cloth Tunic",
                          offset: 0xa4,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Gym Clothes",
                          offset: 0xa5,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "War Fatigues",
                          offset: 0xa6,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Ninja Suit",
                          offset: 0xa7,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Soldier Uniform",
                          offset: 0xa8,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Pitch Black Suit",
                          offset: 0xa9,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Olrox's Suit",
                          offset: 0xaa,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Dracula's Tunic",
                          offset: 0xab,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Leather Plate",
                          offset: 0xac,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Copper Plate",
                          offset: 0xad,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Iron Plate",
                          offset: 0xae,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Steel Plate",
                          offset: 0xaf,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Silver Plate",
                          offset: 0xb0,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Gold Plate",
                          offset: 0xb1,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Eversing",
                          offset: 0xb2,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Samurai Armor",
                          offset: 0xb3,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Silk Robe",
                          offset: 0xb4,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Elfin Robe",
                          offset: 0xb5,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Death's Robe",
                          offset: 0xb6,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Demon's Mail",
                          offset: 0xb7,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Armor of Fire",
                          offset: 0xb8,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Armor of Water",
                          offset: 0xb9,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Blocking Mail",
                          offset: 0xba,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Army Jacket",
                          offset: 0xbb,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                      ],
                    },
                    {
                      name: "Accessories",
                      flex: true,
                      items: [
                        {
                          name: "Cape",
                          offset: 0xbc,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Crimson Cloak",
                          offset: 0xbd,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Black Cloak",
                          offset: 0xbe,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Pendant",
                          offset: 0xbf,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Heart Pendant",
                          offset: 0xc0,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Scarf",
                          offset: 0xc1,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Red Scarf",
                          offset: 0xc2,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Ancient Belt",
                          offset: 0xc3,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Black Belt",
                          offset: 0xc4,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Skull Necklace",
                          offset: 0xc5,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Flame Necklace",
                          offset: 0xc6,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Satan's Ring",
                          offset: 0xc7,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Tear of Blood",
                          offset: 0xc8,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Lucky Charm",
                          offset: 0xc9,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Rare Ring",
                          offset: 0xca,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Soul Eater Ring",
                          offset: 0xcb,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Rune Ring",
                          offset: 0xcc,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Sherman Ring",
                          offset: 0xcd,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Gold Ring",
                          offset: 0xce,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Chaos Ring",
                          offset: 0xcf,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                      ],
                    },
                    {
                      name: "Items",
                      flex: true,
                      items: [
                        {
                          name: "Potion",
                          offset: 0x48,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "High Potion",
                          offset: 0x49,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Super Potion",
                          offset: 0x4a,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Meat Strip",
                          offset: 0x4b,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Tasty Meat",
                          offset: 0x4c,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Mind Up",
                          offset: 0x4d,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "High Mind Up",
                          offset: 0x4e,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Mana Prism",
                          offset: 0x4f,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Anti-Venom",
                          offset: 0x50,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Uncurse Potion",
                          offset: 0x51,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Potato Pancake",
                          offset: 0x52,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Beef Curry",
                          offset: 0x53,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Ramen",
                          offset: 0x54,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Cream Soda",
                          offset: 0x55,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Cream Puff",
                          offset: 0x56,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Milk",
                          offset: 0x57,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Coffee",
                          offset: 0x58,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Tea",
                          offset: 0x59,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Pudding",
                          offset: 0x5a,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Strawberry",
                          offset: 0x5b,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Melon",
                          offset: 0x5c,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Grapes",
                          offset: 0x5d,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Persimmon",
                          offset: 0x5e,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Rotten Meat",
                          offset: 0x5f,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Spoiled Milk",
                          offset: 0x60,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Skeleteon Key",
                          offset: 0x61,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Ancient Book 1",
                          offset: 0x62,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Ancient Book 2",
                          offset: 0x63,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "Ancient Book 3",
                          offset: 0x64,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "CASTLE MAP 1",
                          offset: 0x65,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "CASTLE MAP 2",
                          offset: 0x66,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                        {
                          name: "CASTLE MAP 3",
                          offset: 0x67,
                          type: "variable",
                          dataType: "uint8",
                          max: 9,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Abilities",
              flex: true,
              items: [
                {
                  id: "abilities",
                  name: "Abilities",
                  type: "bitflags",
                  flags: [
                    { offset: 0x146, bit: 0, label: "Grave Keeper" },
                    { offset: 0x146, bit: 4, label: "Skeleton Blaze" },
                    { offset: 0x147, bit: 0, label: "Malphas" },
                    { offset: 0x147, bit: 4, label: "Kicker Skeleton" },
                    { offset: 0x148, bit: 0, label: "Hippogryph" },
                    { offset: 0x148, bit: 4, label: "Galamoth" },
                  ],
                },
                {
                  name: "Equipped Abilities",
                  type: "bitflags",
                  flags: [
                    { offset: 0x14a, bit: 0, label: "Grave Keeper" },
                    { offset: 0x14a, bit: 1, label: "Skeleton Blaze" },
                    { offset: 0x14a, bit: 2, label: "Malphas" },
                    { offset: 0x14a, bit: 3, label: "Kicker Skeleton" },
                    { offset: 0x14a, bit: 4, label: "Hippogryph" },
                    { offset: 0x14a, bit: 5, label: "Galamoth" },
                  ],
                },
              ],
            },
            {
              name: "Bestiary",
              flex: true,
              items: [
                {
                  name: "Entries",
                  type: "bitflags",
                  flags: enemies.map((enemy) => ({
                    offset: 0x154 + Math.floor(enemy.index / 8),
                    bit: enemy.index % 8,
                    label: enemy.name,
                    separator: (enemy.index + 1) % 10 === 0,
                  })),
                },
                {
                  name: "Drops",
                  type: "bitflags",
                  flags: enemies.map((enemy) => ({
                    offset: 0x164 + Math.floor(enemy.index / 8),
                    bit: enemy.index % 8,
                    label: enemy.name,
                    separator: (enemy.index + 1) % 10 === 0,
                    disabled: !enemy.drops[0],
                  })),
                },
                {
                  name: "Rare Drops",
                  type: "bitflags",
                  flags: enemies.map((enemy) => ({
                    offset: 0x174 + Math.floor(enemy.index / 8),
                    bit: enemy.index % 8,
                    label: enemy.name,
                    separator: (enemy.index + 1) % 10 === 0,
                    disabled: !enemy.drops[1],
                  })),
                },
              ],
            },
            {
              name: "Events",
              planned: true,
              items: [
                {
                  name: "Locations Visited",
                  offset: 0x489,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
              ],
            },
            {
              name: "Config",
              flex: true,
              items: [
                {
                  name: "Button Attack",
                  offset: 0x14c,
                  type: "variable",
                  dataType: "uint16",
                  resource: "buttons",
                },
                {
                  name: "Button Jump",
                  offset: 0x14e,
                  type: "variable",
                  dataType: "uint16",
                  resource: "buttons",
                },
                {
                  name: "Button Guardian",
                  offset: 0x150,
                  type: "variable",
                  dataType: "uint16",
                  resource: "buttons",
                },
                {
                  name: "Button Ability",
                  offset: 0x152,
                  type: "variable",
                  dataType: "uint16",
                  resource: "buttons",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    accessories: {
      0x19: "Cape",
      0x1a: "Crimson Cloak",
      0x1b: "Black Cloak",
      0x1c: "Pendant",
      0x1d: "Heart Pendant",
      0x1e: "Scarf",
      0x1f: "Red Scarf",
      0x20: "Ancient Belt",
      0x21: "Black Belt",
      0x22: "Skull Necklace",
      0x23: "Flame Necklace",
      0x24: "Satan's Ring",
      0x25: "Tear of Blood",
      0x26: "Lucky Charm",
      0x27: "Rare Ring",
      0x28: "Soul Eater Ring",
      0x29: "Rune Ring",
      0x2a: "Sherman Ring",
      0x2b: "Gold Ring",
      0x2c: "Chaos Ring",
      0xff: "-",
    },
    body: {
      0x0: "Casual Clothes",
      0x1: "Cloth Tunic",
      0x2: "Gym Clothes",
      0x3: "War Fatigues",
      0x4: "Ninja Suit",
      0x5: "Soldier Uniform",
      0x6: "Pitch Black Suit",
      0x7: "Olrox's Suit",
      0x8: "Dracula's Tunic",
      0x9: "Leather Plate",
      0xa: "Copper Plate",
      0xb: "Iron Plate",
      0xc: "Steel Plate",
      0xd: "Silver Plate",
      0xe: "Gold Plate",
      0xf: "Eversing",
      0x10: "Samurai Armor",
      0x11: "Silk Robe",
      0x12: "Elfin Robe",
      0x13: "Death's Robe",
      0x14: "Demon's Mail",
      0x15: "Armor of Fire",
      0x16: "Armor of Water",
      0x17: "Blocking Mail",
      0x18: "Army Jacket",
      0xff: "-",
    },
    bulletSouls: {
      0x0: "-",
      0x1: "Winged Skeleton",
      0x2: "Bat",
      0x3: "Skeleton",
      0x4: "Merman",
      0x5: "Axe Armor",
      0x6: "Skull Archer",
      0x7: "Killer Fish",
      0x8: "Blue Crow",
      0x9: "Zombie Solider",
      0xa: "Ghost",
      0xb: "Siren",
      0xc: "Tiny Devil",
      0xd: "Durga",
      0xe: "Rock Armor",
      0xf: "Student Witch",
      0x10: "Arachne",
      0x11: "Fleaman",
      0x12: "Evil Butcher",
      0x13: "Waiter Skeleton",
      0x14: "Altair",
      0x15: "Mudman",
      0x16: "Cockatrice",
      0x17: "Werewolf",
      0x18: "Harpy",
      0x19: "Une",
      0x1a: "Needles",
      0x1b: "Man-Eater",
      0x1c: "Ukoback",
      0x1d: "Fish Head",
      0x1e: "Disc Armor",
      0x1f: "Nightmare",
      0x20: "Slime",
      0x21: "Dryad",
      0x22: "Ripper",
      0x23: "Werejaguar",
      0x24: "Weretiger",
      0x25: "Biphron",
      0x26: "Mandragora",
      0x27: "Beam Skeleton",
      0x28: "Skull Millione",
      0x29: "Giant Skeleton",
      0x2a: "Gladiator",
      0x2b: "Demon Lord",
      0x2c: "Flame Demon",
      0x2d: "Lightning Doll",
      0x2e: "Valkyrie",
      0x2f: "Bomber Armor",
      0x30: "Red Minotaur",
      0x31: "Legion",
      0x32: "Balore",
      0x33: "Killer Doll",
      0x34: "Nemesis",
      0x35: "Killer Mantle",
      0x36: "Kyoma Demon",
      0x37: "Chronomage",
    },
    buttons: {
      0x1: "A",
      0x2: "B",
      0x100: "L",
      0x200: "R",
    },
    characters: {
      0x0: "Soma",
      0x1: "Julius",
    },
    difficulties: {
      0x0: "Normal",
      0x1: "Hard",
    },
    enchantedSouls: {
      0x0: "-",
      0x1: "Undine",
      0x2: "Skula",
      0x3: "Zombie Officer",
      0x4: "Iron Golem",
      0x5: "Dead Warrior",
      0x6: "Peeping Eye",
      0x7: "Succubus",
      0x8: "Flesh Golem",
      0x9: "Tsuchinoko",
      0xa: "Giant Worm",
      0xb: "Wooden Golem",
      0xc: "Zombie",
      0xd: "Lubicant",
      0xe: "Headhunter",
      0xf: "Basilisk",
      0x10: "Erinys",
      0x11: "Mimic",
      0x12: "Arc Demon",
      0x13: "Poison Worm",
      0x14: "Ectoplasm",
      0x15: "Gargoyle",
      0x16: "Skeleton Knight",
      0x17: "Minotaur",
      0x18: "Golem",
      0x19: "Triton",
      0x1a: "White Dragon",
      0x1b: "Quezcoatl",
      0x1c: "Gorgon",
      0x1d: "Dead Crusader",
      0x1e: "Red Crow",
      0x1f: "Lilith",
      0x20: "Bael",
      0x21: "Stolas",
      0x22: "Ghost Dancer",
      0x23: "Gremlin",
    },
    guardianSouls: {
      0x0: "-",
      0x1: "Giant Bat",
      0x2: "Flying Armor",
      0x3: "Black Panther",
      0x4: "Buer",
      0x5: "Witch",
      0x6: "Giant Ghost",
      0x7: "Final Guard",
      0x8: "Great Armor",
      0x9: "Catoblepas",
      0xa: "Bone Pillar",
      0xb: "Cagnazzo",
      0xc: "Big Golem",
      0xd: "Shadow Knight",
      0xe: "Creaking Skull",
      0xf: "Medusa Head",
      0x10: "Persephone",
      0x11: "Alura Une",
      0x12: "Devil",
      0x13: "Manticore",
      0x14: "Curly",
      0x15: "Sky Fish",
      0x16: "Imp",
      0x17: "Alastor",
      0x18: "Death",
    },
    hand: {
      0x0: "Knife",
      0x1: "Baselard",
      0x2: "Combat Knife",
      0x3: "Short Sword",
      0x4: "Bastard Sword",
      0x5: "Whip Sword",
      0x6: "Gladius",
      0x7: "Gram",
      0x8: "Milican's Sword",
      0x9: "Hrunting",
      0xa: "Mystletain",
      0xb: "Rahab's Sword",
      0xc: "Durandal",
      0xd: "Laevatain",
      0xe: "Burtgang",
      0xf: "Kaladbolg",
      0x10: "Vjaya",
      0x11: "Balmung",
      0x12: "Broadsword",
      0x13: "Scimitar",
      0x14: "Claymore",
      0x15: "Great Sword",
      0x16: "Joyeuse",
      0x17: "Dainslef",
      0x18: "Ascalon",
      0x19: "Claimh Solais",
      0x1a: "Final Sword",
      0x1b: "Bamboo Sword",
      0x1c: "Katana",
      0x1d: "Osafune",
      0x1e: "Onikiri",
      0x1f: "Kunitsuna",
      0x20: "Yasutsuna",
      0x21: "Muramasa",
      0x22: "Hammer",
      0x23: "Warhammer",
      0x24: "Excalibur",
      0x25: "Tallhammer",
      0x26: "Battle Axe",
      0x27: "Death's Sickle",
      0x28: "Rapier",
      0x29: "Estoc",
      0x2a: "Cutall",
      0x2b: "Spear",
      0x2c: "Trident",
      0x2d: "Lance",
      0x2e: "Partizan",
      0x2f: "Gabolg",
      0x30: "Gungner",
      0x31: "Ronginus' Spear",
      0x32: "Cestus",
      0x33: "Kaiser Knuckle",
      0x34: "Mach Punch",
      0x35: "Whip Knuckle",
      0x36: "Poison Fist",
      0x37: "Handgun",
      0x38: "Silver Gun",
      0x39: "Positron Rifle",
      0x3a: "Valmanway",
      0xff: "-",
    },
    handicaps: {
      0x0: "-",
      0x1: "No Use",
      0x2: "No Soul",
      0x3: "No Use + No Soul",
    },
    languages: [
      // Europe
      {
        0x0: "-",
        0x1: "English",
        0x2: "French",
        0x3: "German",
      },
      // USA
      {
        0x1: "English",
      },
      // Japan
      {
        0x0: "Japanese",
      },
    ],
    letters: {
      0x0: " ",
      0x2: "A",
      0x3: "B",
      0x4: "C",
      0x5: "D",
      0x6: "E",
      0x7: "F",
      0x8: "G",
      0x9: "H",
      0xa: "I",
      0xb: "J",
      0xc: "K",
      0xd: "L",
      0xe: "M",
      0xf: "N",
      0x10: "O",
      0x11: "P",
      0x12: "Q",
      0x13: "R",
      0x14: "S",
      0x15: "T",
      0x16: "U",
      0x17: "V",
      0x18: "W",
      0x19: "X",
      0x1a: "Y",
      0x1b: "Z",
      0x1c: "@",
      0x1d: ".",
      0x1e: "-",
      0x1f: "'",
      0x20: "!",
      0x21: "☠",
      0x22: "†",
      0x23: " ",
    },
    locations: {
      0xe: "Castle Corridor (after Creaking Skull)",
      0x1f: "Castle Corridor (near Chapel)",
      0x24: "Castle Corridor",
      0x10e: "Chapel",
      0x20c: "Study",
      0x315: "Dance Hall",
      0x316: "Dance Hall (near big Golem)",
      0x414: "Inner Quarters",
      0x50b: "Floating Garden (near Julius)",
      0x50c: "Floating Garden",
      0x60f: "Clock Tower",
      0x61f: "Clock Tower (near Death)",
      0x727: "Underground Reservoir (West)",
      0x729: "Underground Cemetery",
      0x730: "Underground Reservoir (East)",
      0x815: "The Arena",
      0x916: "Top Floor",
      0xb01: "Chaotic Realm (part 2)",
      0xb12: "Chaotic Realm (part 3)",
      0xb1e: "Chaotic Realm (part 1)",
    },
    progressions: {
      0x0: "-",
      0x1: "Game Complete",
    },
  },
  resourcesLabels: {
    locations: {
      0xe: "Castle Corridor",
      0x10e: "Chapel",
      0x20c: "Study",
      0x315: "Dance Hall",
      0x414: "Inner Quarters",
      0x50b: "Floating Garden",
      0x60f: "Clock Tower",
      0x727: "Undergrounds",
      0x815: "The Arena",
      0x916: "Top Floor",
      0xb01: "Chaotic Realm",
    },
  },
  resourcesOrder: {
    accessories: [0xff],
    body: [0xff],
    hand: [0xff],
    locations: [
      0x24, 0xe, 0x1f, 0x10e, 0x20c, 0x315, 0x316, 0x414, 0x50c, 0x50b, 0x60f,
      0x61f, 0x727, 0x730, 0x729, 0x815, 0x916, 0xb1e, 0xb01, 0xb12,
    ],
  },
};

export default template;
