export const enemies = [
  { index: 0x0, name: "001 Zombie", drops: [true, false] },
  { index: 0x1, name: "002 Bat", drops: [false, false] },
  { index: 0x2, name: "003 Ghost", drops: [false, false] },
  { index: 0x3, name: "004 Skeleton", drops: [false, false] },
  { index: 0x4, name: "005 Ouija Table", drops: [false, false] },
  { index: 0x5, name: "006 Peeping Eye", drops: [false, false] },
  { index: 0x6, name: "007 Axe Armor", drops: [true, true] },
  { index: 0x7, name: "008 Skull Archer", drops: [false, false] },
  { index: 0x8, name: "009 Warg", drops: [false, false] },
  { index: 0x9, name: "010 Spin Devil", drops: [false, false] },
  { index: 0xa, name: "011 Armor Knight", drops: [true, false] },
  { index: 0xb, name: "012 Student Witch", drops: [true, false] },
  { index: 0xc, name: "013 Slaughterer", drops: [true, true] },
  { index: 0xd, name: "014 Bomber Armor", drops: [true, false] },
  { index: 0xe, name: "015 Golem", drops: [false, false] },
  { index: 0xf, name: "016 Slime", drops: [false, false] },
  { index: 0x10, name: "017 Une", drops: [false, false] },
  { index: 0x11, name: "018 Skeleton Ape", drops: [false, false] },
  { index: 0x12, name: "019 Manticore", drops: [true, false] },
  { index: 0x13, name: "020 Mollusca", drops: [true, false] },
  { index: 0x14, name: "021 Rycuda", drops: [true, false] },
  { index: 0x15, name: "022 Mandragora", drops: [false, false] },
  { index: 0x16, name: "023 Yorick", drops: [false, false] },
  { index: 0x17, name: "024 Skeleton Farmer", drops: [false, false] },
  { index: 0x18, name: "025 The Creature", drops: [true, false] },
  { index: 0x19, name: "026 Catoblepas", drops: [true, true] },
  { index: 0x1a, name: "027 Ghoul", drops: [true, true] },
  { index: 0x1b, name: "028 Corpseweed", drops: [false, false] },
  { index: 0x1c, name: "029 Yeti", drops: [false, false] },
  { index: 0x1d, name: "030 Tombstone", drops: [false, false] },
  { index: 0x1e, name: "031 Ghost Dancer", drops: [true, false] },
  { index: 0x1f, name: "032 Flying Humanoid", drops: [false, false] },
  { index: 0x20, name: "033 Mini Devil", drops: [false, false] },
  { index: 0x21, name: "034 Quetzalcoatl", drops: [true, true] },
  { index: 0x22, name: "035 Treant", drops: [false, false] },
  { index: 0x23, name: "036 Amalaric Sniper", drops: [true, true] },
  { index: 0x24, name: "037 Valkyrie", drops: [true, true] },
  { index: 0x25, name: "038 Great Armor", drops: [true, false] },
  { index: 0x26, name: "039 Killer Doll", drops: [false, false] },
  { index: 0x27, name: "040 Waiter Skeleton", drops: [true, true] },
  { index: 0x28, name: "041 Persephone", drops: [true, true] },
  { index: 0x29, name: "042 Witch", drops: [true, true] },
  { index: 0x2a, name: "043 Buer", drops: [false, false] },
  { index: 0x2b, name: "044 Lilith", drops: [true, false] },
  { index: 0x2c, name: "045 Killer Clown", drops: [true, true] },
  { index: 0x2d, name: "046 Skelerang", drops: [true, false] },
  { index: 0x2e, name: "047 Fleaman", drops: [true, false] },
  { index: 0x2f, name: "048 Devil", drops: [true, true] },
  { index: 0x30, name: "049 Guillotiner", drops: [false, false] },
  { index: 0x31, name: "050 Draghignazzo", drops: [true, false] },
  { index: 0x32, name: "051 Needles", drops: [true, false] },
  { index: 0x33, name: "052 Hell Boar", drops: [true, true] },
  { index: 0x34, name: "053 Bone Pillar", drops: [false, false] },
  { index: 0x35, name: "054 White Dragon", drops: [false, false] },
  { index: 0x36, name: "055 Wakwak Tree", drops: [true, false] },
  { index: 0x37, name: "056 Imp", drops: [false, false] },
  { index: 0x38, name: "057 Harpy", drops: [false, false] },
  { index: 0x39, name: "058 Barbaricca", drops: [true, false] },
  { index: 0x3a, name: "059 Malachi", drops: [true, false] },
  { index: 0x3b, name: "060 Cave Troll", drops: [true, false] },
  { index: 0x3c, name: "061 Larva", drops: [false, false] },
  { index: 0x3d, name: "062 Heart Eater", drops: [true, true] },
  { index: 0x3e, name: "063 Merman", drops: [false, false] },
  { index: 0x3f, name: "064 Fish Head", drops: [false, false] },
  { index: 0x40, name: "065 Medusa Head", drops: [false, false] },
  { index: 0x41, name: "066 Ukoback", drops: [false, false] },
  { index: 0x42, name: "067 Killer Fish", drops: [true, true] },
  { index: 0x43, name: "068 Mimic", drops: [false, false] },
  { index: 0x44, name: "069 Dead Pirate", drops: [true, true] },
  { index: 0x45, name: "070 Frozen Shade", drops: [true, true] },
  { index: 0x46, name: "071 Homunculus", drops: [false, false] },
  { index: 0x47, name: "072 Disc Armor", drops: [true, false] },
  { index: 0x48, name: "073 Decarabia", drops: [true, false] },
  { index: 0x49, name: "074 Dead Mate", drops: [true, true] },
  { index: 0x4a, name: "075 Bugbear", drops: [false, false] },
  { index: 0x4b, name: "076 Procel", drops: [false, false] },
  { index: 0x4c, name: "077 Bone Ark", drops: [false, false] },
  { index: 0x4d, name: "078 Gorgon", drops: [true, true] },
  { index: 0x4e, name: "079 Alura Une", drops: [true, false] },
  { index: 0x4f, name: "080 Great Axe Armor", drops: [true, true] },
  { index: 0x50, name: "081 Mothman", drops: [false, false] },
  { index: 0x51, name: "082 Mushussu", drops: [true, false] },
  { index: 0x52, name: "083 Dead Crusader", drops: [true, true] },
  { index: 0x53, name: "084 Dead Warrior", drops: [true, true] },
  { index: 0x54, name: "085 Erinys", drops: [true, true] },
  { index: 0x55, name: "086 Succubus", drops: [true, true] },
  { index: 0x56, name: "087 Ripper", drops: [true, true] },
  { index: 0x57, name: "088 Black Panther", drops: [false, false] },
  { index: 0x58, name: "089 Mud Demon", drops: [false, false] },
  { index: 0x59, name: "090 Giant Slug", drops: [false, false] },
  { index: 0x5a, name: "091 Werewolf", drops: [true, true] },
  { index: 0x5b, name: "092 Flame Demon", drops: [true, true] },
  { index: 0x5c, name: "093 Tanjelly", drops: [false, false] },
  { index: 0x5d, name: "094 Arc Demon", drops: [true, true] },
  { index: 0x5e, name: "095 Gaibon", drops: [false, false] },
  { index: 0x5f, name: "096 Slogra", drops: [false, false] },
  { index: 0x60, name: "097 Stolas", drops: [true, false] },
  { index: 0x61, name: "098 Final Guard", drops: [true, true] },
  { index: 0x62, name: "099 Malacoda", drops: [true, false] },
  { index: 0x63, name: "100 Alastor", drops: [false, false] },
  { index: 0x64, name: "101 Iron Golem", drops: [false, false] },
  { index: 0x65, name: "102 Flying Armor", drops: [false, false] },
  { index: 0x66, name: "103 Balore", drops: [false, false] },
  { index: 0x67, name: "104 Malphas", drops: [false, false] },
  { index: 0x68, name: "105 Dmitrii", drops: [false, false] },
  { index: 0x69, name: "106 Dario", drops: [false, false] },
  { index: 0x6a, name: "107 Puppet Master", drops: [false, false] },
  { index: 0x6b, name: "108 Rahab", drops: [false, false] },
  { index: 0x6c, name: "109 Gergoth", drops: [false, false] },
  { index: 0x6d, name: "110 Zephyr", drops: [false, false] },
  { index: 0x6e, name: "111 Bat Company", drops: [false, false] },
  { index: 0x6f, name: "112 Paranoia", drops: [false, false] },
  { index: 0x70, name: "113 Aguni", drops: [false, false] },
  { index: 0x71, name: "114 Death", drops: [false, false] },
  { index: 0x72, name: "115 Abaddon", drops: [false, false] },
  { index: 0x73, name: "116 Menace", drops: [false, false] },
];
