import type { GameJson } from "$lib/types";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa_japan: {
        0x0: [0x44, 0x52, 0x41, 0x43, 0x55, 0x4c, 0x41, 0x20, 0x41, 0x47, 0x42], // "DRACULA AGB"
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      length: 0x3d0,
      type: "container",
      instanceType: "tabs",
      instances: 8,
      enumeration: "Slot %d",
      disableSubinstanceIf: {
        offset: 0x10,
        type: "variable",
        dataType: "uint8",
        value: 0x0,
      },
      prependSubinstance: [
        {
          name: "General",
          items: [
            {
              name: "Unlocked Modes",
              type: "bitflags",
              flags: [
                { offset: 0xb, bit: 2, label: "Magician Mode Unlocked" },
                { offset: 0xb, bit: 3, label: "Fighter Mode Unlocked" },
                { offset: 0xb, bit: 1, label: "Shooter Mode Unlocked" },
                { offset: 0xb, bit: 4, label: "Thief Mode Unlocked" },
                { offset: 0xb, bit: 5, label: "All modes completed" },
              ],
            },
          ],
        },
      ],
      items: [
        {
          name: "Checksum",
          offset: 0x19,
          type: "checksum",
          dataType: "uint8",
          control: {
            offsetStart: 0x10,
            offsetEnd: 0x3e0,
          },
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              flex: true,
              items: [
                {
                  name: "Filename",
                  offset: 0x11,
                  length: 0x8,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  resource: "letters",
                  test: true,
                },
                {
                  name: "Play Time",
                  type: "group",
                  mode: "time",
                  items: [
                    {
                      offset: 0xa0,
                      type: "variable",
                      dataType: "uint32",
                      operations: [
                        { "/": 60 },
                        { convert: { from: "seconds", to: "hours" } },
                      ],
                      max: 99,
                    },
                    {
                      offset: 0xa0,
                      type: "variable",
                      dataType: "uint32",
                      operations: [
                        { "/": 60 },
                        { convert: { from: "seconds", to: "minutes" } },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      offset: 0xa0,
                      type: "variable",
                      dataType: "uint32",
                      operations: [
                        { "/": 60 },
                        { convert: { from: "seconds", to: "seconds" } },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                  ],
                },
                {
                  name: "Mode",
                  offset: 0x9c,
                  type: "variable",
                  dataType: "uint16",
                  resource: "modes",
                },
                {
                  name: "Location",
                  offset: 0xa4,
                  type: "variable",
                  dataType: "uint16",
                  bigEndian: true,
                  resource: "locations",
                  size: "lg",
                  autocomplete: true,
                },
                {
                  name: "Map Discovery Rate",
                  offset: 0xbc,
                  type: "variable",
                  dataType: "uint16",
                  operations: [{ "/": 9.8 }, { round: 2 }],
                  suffix: "%",
                  disabled: true,
                },
              ],
            },
            {
              name: "Status",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Level",
                              offset: 0x30c,
                              type: "variable",
                              dataType: "uint8",
                              min: 1,
                              max: 99,
                            },
                            {
                              name: "Experience",
                              offset: 0x310,
                              type: "variable",
                              dataType: "uint32",
                              max: 99999999,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "HP",
                              offset: 0x2d6,
                              type: "variable",
                              dataType: "uint16",
                              min: 1,
                              max: 9999,
                            },
                            {
                              name: "MP",
                              offset: 0x2de,
                              type: "variable",
                              dataType: "uint16",
                              max: 9999,
                            },
                            {
                              name: "Hearts",
                              offset: 0x2e4,
                              type: "variable",
                              dataType: "uint16",
                              max: 999,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Subweapon",
                              offset: 0x2e8,
                              type: "variable",
                              dataType: "uint8",
                              resource: "subweapons",
                              autocomplete: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Stats Bonus",
                      flex: true,
                      items: [
                        {
                          name: "HP +10",
                          offset: 0x3d5,
                          type: "variable",
                          dataType: "uint8",
                        },
                        {
                          name: "MP +10",
                          offset: 0x3d6,
                          type: "variable",
                          dataType: "uint8",
                        },
                        {
                          name: "Hearts +6",
                          offset: 0x3d4,
                          type: "variable",
                          dataType: "uint8",
                        },
                      ],
                    },
                    {
                      name: "Equipped DSS",
                      flex: true,
                      items: [
                        {
                          name: "DSS Action",
                          offset: 0x315,
                          type: "variable",
                          dataType: "uint8",
                          resource: "dssAction",
                          autocomplete: true,
                        },
                        {
                          name: "DSS Attribute",
                          offset: 0x314,
                          type: "variable",
                          dataType: "uint8",
                          resource: "dssAttribute",
                          autocomplete: true,
                        },
                      ],
                    },
                    {
                      name: "Equipped Items",
                      flex: true,
                      items: [
                        {
                          name: "Body",
                          offset: 0x316,
                          type: "variable",
                          dataType: "uint8",
                          resource: "equipments",
                          autocomplete: true,
                        },
                        {
                          name: "Arm Right",
                          offset: 0x317,
                          type: "variable",
                          dataType: "uint8",
                          resource: "equipments",
                          autocomplete: true,
                        },
                        {
                          name: "Arm Left",
                          offset: 0x318,
                          type: "variable",
                          dataType: "uint8",
                          resource: "equipments",
                          autocomplete: true,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "DSS",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "DSS Action",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Mercury",
                              offset: 0x326,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus",
                              offset: 0x327,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter",
                              offset: 0x328,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars",
                              offset: 0x329,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana",
                              offset: 0x32a,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo",
                              offset: 0x32b,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune",
                              offset: 0x32c,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturn",
                              offset: 0x32d,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus",
                              offset: 0x32e,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto",
                              offset: 0x32f,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "DSS Attribute",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Salamander",
                              offset: 0x31c,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Serpent",
                              offset: 0x31d,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mandragora",
                              offset: 0x31e,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Golem",
                              offset: 0x31f,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Cockatrice",
                              offset: 0x320,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Manticore",
                              offset: 0x321,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Griffin",
                              offset: 0x322,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Thunder Bird",
                              offset: 0x323,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Unicorn",
                              offset: 0x324,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Black Dog",
                              offset: 0x325,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "DSS Combinations",
                      flex: true,
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Mercury / Salamander",
                              offset: 0x330,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mercury / Serpent",
                              offset: 0x331,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mercury / Mandragora",
                              offset: 0x332,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mercury / Golem",
                              offset: 0x333,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mercury / Cockatrice",
                              offset: 0x334,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mercury / Manticore",
                              offset: 0x335,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mercury / Griffin",
                              offset: 0x336,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mercury / Thunder Bird",
                              offset: 0x337,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mercury / Unicorn",
                              offset: 0x338,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mercury / Black Dog",
                              offset: 0x339,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Venus / Salamander",
                              offset: 0x33a,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus / Serpent",
                              offset: 0x33b,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus / Mandragora",
                              offset: 0x33c,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus / Golem",
                              offset: 0x33d,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus / Cockatrice",
                              offset: 0x33e,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus / Manticore",
                              offset: 0x33f,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus / Griffin",
                              offset: 0x340,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus / Thunder Bird",
                              offset: 0x341,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus / Unicorn",
                              offset: 0x342,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Venus / Black Dog",
                              offset: 0x343,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Jupiter / Salamander",
                              offset: 0x344,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter / Serpent",
                              offset: 0x345,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter / Mandragora",
                              offset: 0x346,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter / Golem",
                              offset: 0x347,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter / Cockatrice",
                              offset: 0x348,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter / Manticore",
                              offset: 0x349,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter / Griffin",
                              offset: 0x34a,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter / Thunder Bird",
                              offset: 0x34b,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter / Unicorn",
                              offset: 0x34c,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Jupiter / Black Dog",
                              offset: 0x34d,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Mars / Salamander",
                              offset: 0x34e,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars / Serpent",
                              offset: 0x34f,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars / Mandragora",
                              offset: 0x350,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars / Golem",
                              offset: 0x351,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars / Cockatrice",
                              offset: 0x352,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars / Manticore",
                              offset: 0x353,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars / Griffin",
                              offset: 0x354,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars / Thunder Bird",
                              offset: 0x355,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars / Unicorn",
                              offset: 0x356,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Mars / Black Dog",
                              offset: 0x357,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Diana / Salamander",
                              offset: 0x358,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana / Serpent",
                              offset: 0x359,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana / Mandragora",
                              offset: 0x35a,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana / Golem",
                              offset: 0x35b,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana / Cockatrice",
                              offset: 0x35c,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana / Manticore",
                              offset: 0x35d,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana / Griffin",
                              offset: 0x35e,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana / Thunder Bird",
                              offset: 0x35f,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana / Unicorn",
                              offset: 0x360,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Diana / Black Dog",
                              offset: 0x361,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Apollo / Salamander",
                              offset: 0x362,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo / Serpent",
                              offset: 0x363,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo / Mandragora",
                              offset: 0x364,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo / Golem",
                              offset: 0x365,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo / Cockatrice",
                              offset: 0x366,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo / Manticore",
                              offset: 0x367,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo / Griffin",
                              offset: 0x368,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo / Thunder Bird",
                              offset: 0x369,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo / Unicorn",
                              offset: 0x36a,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Apollo / Black Dog",
                              offset: 0x36b,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Neptune / Salamander",
                              offset: 0x36c,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune / Serpent",
                              offset: 0x36d,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune / Mandragora",
                              offset: 0x36e,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune / Golem",
                              offset: 0x36f,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune / Cockatrice",
                              offset: 0x370,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune / Manticore",
                              offset: 0x371,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune / Griffin",
                              offset: 0x372,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune / Thunder Bird",
                              offset: 0x373,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune / Unicorn",
                              offset: 0x374,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Neptune / Black Dog",
                              offset: 0x375,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Saturne / Salamander",
                              offset: 0x376,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturne / Serpent",
                              offset: 0x377,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturne / Mandragora",
                              offset: 0x378,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturne / Golem",
                              offset: 0x379,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturne / Cockatrice",
                              offset: 0x37a,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturne / Manticore",
                              offset: 0x37b,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturne / Griffin",
                              offset: 0x37c,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturne / Thunder Bird",
                              offset: 0x37d,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturne / Unicorn",
                              offset: 0x37e,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Saturne / Black Dog",
                              offset: 0x37f,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Uranus / Salamander",
                              offset: 0x380,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus / Serpent",
                              offset: 0x381,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus / Mandragora",
                              offset: 0x382,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus / Golem",
                              offset: 0x383,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus / Cockatrice",
                              offset: 0x384,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus / Manticore",
                              offset: 0x385,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus / Griffin",
                              offset: 0x386,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus / Thunder Bird",
                              offset: 0x387,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus / Unicorn",
                              offset: 0x388,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Uranus / Black Dog",
                              offset: 0x389,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Pluto / Salamander",
                              offset: 0x38a,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto / Serpent",
                              offset: 0x38b,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto / Mandragora",
                              offset: 0x38c,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto / Golem",
                              offset: 0x38d,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto / Cockatrice",
                              offset: 0x38e,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto / Manticore",
                              offset: 0x38f,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto / Griffin",
                              offset: 0x390,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto / Thunder Bird",
                              offset: 0x391,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto / Unicorn",
                              offset: 0x392,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Pluto / Black Dog",
                              offset: 0x393,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Inventory",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Equipment",
                      flex: true,
                      items: [
                        {
                          name: "Leather Armor",
                          offset: 0x395,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Bronze Armor",
                          offset: 0x396,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Gold Armor",
                          offset: 0x397,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Chain Mail",
                          offset: 0x398,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Steel Armor",
                          offset: 0x399,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Platinum Armor",
                          offset: 0x39a,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Diamond Armor",
                          offset: 0x39b,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Mirror Armor",
                          offset: 0x39c,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Needle Armor",
                          offset: 0x39d,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Dark Armor",
                          offset: 0x39e,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Shining Armor",
                          offset: 0x39f,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Cotton Robe",
                          offset: 0x3a0,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Silk Robe",
                          offset: 0x3a1,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Rainbow Robe",
                          offset: 0x3a2,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Magic Robe",
                          offset: 0x3a3,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Sage Robe",
                          offset: 0x3a4,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Cotton Clothes",
                          offset: 0x3a5,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Prison Garb",
                          offset: 0x3a6,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Stylish Suit",
                          offset: 0x3a7,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Night Suit",
                          offset: 0x3a8,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Ninja Garb",
                          offset: 0x3a9,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Soldier Fatigues",
                          offset: 0x3aa,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Double Grips",
                          offset: 0x3ab,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Star Bracelet",
                          offset: 0x3ac,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Strength Ring",
                          offset: 0x3ad,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Hard Ring",
                          offset: 0x3ae,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Intelligence Ring",
                          offset: 0x3af,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Luck Ring",
                          offset: 0x3b0,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Cursed Ring",
                          offset: 0x3b1,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Strength Armband",
                          offset: 0x3b2,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Defense Armband",
                          offset: 0x3b3,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Sage Armband",
                          offset: 0x3b4,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Gambler Armband",
                          offset: 0x3b5,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Wrist Band",
                          offset: 0x3b6,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Gauntlet",
                          offset: 0x3b7,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Arm Guard",
                          offset: 0x3b8,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Magic Gauntlet",
                          offset: 0x3b9,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Miracle Armband",
                          offset: 0x3ba,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Toy Ring",
                          offset: 0x3bb,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Bear Ring",
                          offset: 0x3bc,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                      ],
                    },
                    {
                      name: "Items",
                      flex: true,
                      items: [
                        {
                          name: "Potion",
                          offset: 0x3bd,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Meat",
                          offset: 0x3be,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Spiced Meat",
                          offset: 0x3bf,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Potion High",
                          offset: 0x3c0,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Potion Ex",
                          offset: 0x3c1,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Antidote",
                          offset: 0x3c2,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Cure Curse",
                          offset: 0x3c3,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Mind Restore",
                          offset: 0x3c4,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Mind High",
                          offset: 0x3c5,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Mind Ex",
                          offset: 0x3c6,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Heart",
                          offset: 0x3c7,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Heart High",
                          offset: 0x3c8,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Heart Ex",
                          offset: 0x3c9,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Heart Mega",
                          offset: 0x3ca,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                      ],
                    },
                    {
                      name: "Magic Items",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Dash Boots",
                              offset: 0x3d7,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Double",
                              offset: 0x3d8,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Tackle",
                              offset: 0x3d9,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Kick Boots",
                              offset: 0x3da,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Heavy Ring",
                              offset: 0x3db,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Cleansing",
                              offset: 0x3dc,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Roc Wing",
                              offset: 0x3dd,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Last Key",
                              offset: 0x3de,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Events",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "bitflags",
                          flags: [
                            { offset: 0x32, bit: 1, label: "DSS Tutorial read" },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Sealed Room",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xab, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x22, bit: 1, label: "Camilla resurect Dracula in Room 0" },
                                { offset: 0x22, bit: 3, label: "Destructed floor in Room 0" },
                                { offset: 0x33, bit: 4, label: "Dracula 2nd defeated in Room 2", separator: true },
                                { offset: 0x22, bit: 5, label: "Potion HP in Room 4", separator: true },
                                { offset: 0x1c, bit: 2, label: "Wall destroyed in Room 0" },
                                { offset: 0x1c, bit: 3, label: "Wall destroyed in Room 4" },
                                { offset: 0x1c, bit: 4, label: "Wall destroyed in Room 16" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Catacomb",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xac, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x31, bit: 0, label: "Dash Boots in Room 7" },
                                { offset: 0x32, bit: 3, label: "Cerberus defeated in Room 5" },
                                { offset: 0x31, bit: 1, label: "Double in Room 22", separator: true },
                                { offset: 0x22, bit: 6, label: "Potion HP in Room 0" },
                                { offset: 0x23, bit: 6, label: "Potion HP in Room 10" },
                                { offset: 0x24, bit: 0, label: "Potion HP in Room 18" },
                                { offset: 0x23, bit: 3, label: "Potion HP in Room 20" },
                                { offset: 0x24, bit: 4, label: "Potion HP in Room 23" },
                                { offset: 0x24, bit: 3, label: "Potion MP in Room 0" },
                                { offset: 0x23, bit: 7, label: "Potion MP in Room 4" },
                                { offset: 0x24, bit: 1, label: "Potion MP in Room 14" },
                                { offset: 0x23, bit: 0, label: "Potion MP in Room 15" },
                                { offset: 0x23, bit: 4, label: "Potion MP in Room 21" },
                                { offset: 0x23, bit: 1, label: "Potion MP in Room 24" },
                                { offset: 0x22, bit: 7, label: "Potion Hearts in Room 2" },
                                { offset: 0x24, bit: 2, label: "Potion Hearts in Room 19" },
                                { offset: 0x23, bit: 2, label: "Potion Hearts in Room 20" },
                                { offset: 0x23, bit: 5, label: "Potion Hearts in Room 21", separator: true },
                                { offset: 0x1c, bit: 5, label: "Wall destroyed in Room 6" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Abyss Stairway",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xad, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x21, bit: 2, label: "Green Statues destroyed", separator: true },
                                { offset: 0x24, bit: 6, label: "Potion HP in Room 1" },
                                { offset: 0x24, bit: 5, label: "Potion HP in Room 4" },
                                { offset: 0x24, bit: 7, label: "Potion MP in Room 7" },
                                { offset: 0x25, bit: 0, label: "Potion Hearts in Room 6", separator: true },
                                { offset: 0x1c, bit: 7, label: "Wall destroyed in Room 0" },
                                { offset: 0x1c, bit: 6, label: "Wall destroyed in Room 3" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Audience Room",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xae, bit: 0, label: "Location discovered" },
                                { offset: 0xa6, bit: 0, label: "Warp Room 1 activated" },
                                { offset: 0xa7, bit: 0, label: "Warp Room 2 activated", separator: true },
                                { offset: 0x21, bit: 1, label: "Blue Door destroyed in Room 1" },
                                { offset: 0x32, bit: 4, label: "Necromancer defeated in Room 11" },
                                { offset: 0x31, bit: 2, label: "Tackle in Room 8", separator: true },
                                { offset: 0x25, bit: 2, label: "Potion HP in Room 7" },
                                { offset: 0x25, bit: 1, label: "Potion HP in Room 10" },
                                { offset: 0x26, bit: 5, label: "Potion HP in Room 24" },
                                { offset: 0x25, bit: 3, label: "Potion MP in Room 9" },
                                { offset: 0x25, bit: 6, label: "Potion MP in Room 15" },
                                { offset: 0x26, bit: 2, label: "Potion MP in Room 18" },
                                { offset: 0x25, bit: 5, label: "Potion MP in Room 19" },
                                { offset: 0x26, bit: 4, label: "Potion MP in Room 23" },
                                { offset: 0x26, bit: 1, label: "Potion Hearts in Room 6" },
                                { offset: 0x25, bit: 4, label: "Potion Hearts in Room 19" },
                                { offset: 0x25, bit: 7, label: "Potion Hearts in Room 21" },
                                { offset: 0x26, bit: 0, label: "Potion Hearts in Room 21" },
                                { offset: 0x26, bit: 3, label: "Potion Hearts in Room 22", separator: true },
                                { offset: 0x1d, bit: 1, label: "Wall destroyed in Room 1" },
                                { offset: 0x1d, bit: 2, label: "Wall destroyed in Room 3" },
                                { offset: 0x1d, bit: 3, label: "Wall destroyed in Room 20" },
                                { offset: 0x1d, bit: 0, label: "Wall destroyed in Room 21" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Triumph Hallway",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xaf, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x26, bit: 6, label: "Potion HP in Room 0" },
                                { offset: 0x26, bit: 7, label: "Potion HP in Room 3", separator: true },
                                { offset: 0x1d, bit: 4, label: "Wall destroyed in Room 2" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Machine Tower",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xb0, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x32, bit: 5, label: "Iron Golem defeated in Room 1" },
                                { offset: 0x31, bit: 3, label: "Kick Boots in Room 2", separator: true },
                                { offset: 0x27, bit: 5, label: "Potion HP in Room 11" },
                                { offset: 0x27, bit: 7, label: "Potion HP in Room 14" },
                                { offset: 0x28, bit: 2, label: "Potion HP in Room 18" },
                                { offset: 0x27, bit: 0, label: "Potion HP in Room 22" },
                                { offset: 0x28, bit: 3, label: "Potion HP in Room 24" },
                                { offset: 0x27, bit: 2, label: "Potion MP in Room 16" },
                                { offset: 0x27, bit: 3, label: "Potion MP in Room 17" },
                                { offset: 0x28, bit: 4, label: "Potion MP in Room 23" },
                                { offset: 0x27, bit: 4, label: "Potion MP in Room 25" },
                                { offset: 0x28, bit: 0, label: "Potion Hearts in Room 7" },
                                { offset: 0x27, bit: 6, label: "Potion Hearts in Room 13" },
                                { offset: 0x28, bit: 1, label: "Potion Hearts in Room 15" },
                                { offset: 0x27, bit: 1, label: "Potion Hearts in Room 20", separator: true },
                                { offset: 0x1e, bit: 0, label: "Wall destroyed in Room 0" },
                                { offset: 0x1d, bit: 6, label: "Wall destroyed in Room 9" },
                                { offset: 0x1d, bit: 7, label: "Wall destroyed in Room 12" },
                                { offset: 0x1d, bit: 5, label: "Wall destroyed in Room 15" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Eternal Corridor",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xb1, bit: 0, label: "Location discovered" },
                                { offset: 0xa8, bit: 0, label: "Warp Room activated", separator: true },
                                { offset: 0x28, bit: 7, label: "Potion HP in Room 8" },
                                { offset: 0x28, bit: 5, label: "Potion Hearts in Room 6" },
                                { offset: 0x28, bit: 6, label: "Potion Hearts in Room 7", separator: true },
                                { offset: 0x1e, bit: 2, label: "Wall destroyed in Room 5" },
                                { offset: 0x1e, bit: 1, label: "Wall destroyed in Room 6" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Chapel Tower",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xb2, bit: 0, label: "Location discovered" },
                                { offset: 0xa9, bit: 0, label: "Warp Room activated", separator: true },
                                { offset: 0x32, bit: 6, label: "Adramelech defeated in Room 3" },
                                { offset: 0x33, bit: 5, label: "Discussion with Hugh after Adramelech defeated in Room 21", separator: true },
                                { offset: 0x29, bit: 0, label: "Potion HP in Room 10" },
                                { offset: 0x29, bit: 1, label: "Potion HP in Room 11" },
                                { offset: 0x29, bit: 2, label: "Potion HP in Room 17" },
                                { offset: 0x29, bit: 6, label: "Potion HP in Room 19" },
                                { offset: 0x2a, bit: 4, label: "Potion HP in Room 24" },
                                { offset: 0x2a, bit: 3, label: "Potion HP in Room 25" },
                                { offset: 0x2a, bit: 1, label: "Potion MP in Room 4" },
                                { offset: 0x29, bit: 7, label: "Potion MP in Room 9" },
                                { offset: 0x29, bit: 4, label: "Potion MP in Room 13" },
                                { offset: 0x29, bit: 5, label: "Potion MP in Room 14" },
                                { offset: 0x2a, bit: 2, label: "Potion MP in Room 26" },
                                { offset: 0x2a, bit: 0, label: "Potion Hearts in Room 5" },
                                { offset: 0x29, bit: 3, label: "Potion Hearts in Room 13", separator: true },
                                { offset: 0x1e, bit: 5, label: "Wall destroyed in Room 2" },
                                { offset: 0x1e, bit: 6, label: "Wall destroyed in Room 6" },
                                { offset: 0x1e, bit: 3, label: "Wall destroyed in Room 12" },
                                { offset: 0x1e, bit: 4, label: "Wall destroyed in Room 15" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Underground Warehouse",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xb3, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x33, bit: 0, label: "Death defeated in Room 19" },
                                { offset: 0x31, bit: 6, label: "Cleansing in Room 21", separator: true },
                                { offset: 0x21, bit: 3, label: "Good placement of movable boxe in Room 0" },
                                { offset: 0x21, bit: 4, label: "Good placement of movable boxes in Room 2" },
                                { offset: 0x21, bit: 5, label: "Good placement of movable boxes in Room 5" },
                                { offset: 0x21, bit: 6, label: "Good placement of movable boxes in Room 9" },
                                { offset: 0x21, bit: 7, label: "Good placement of movable boxes in Room 14" },
                                { offset: 0x22, bit: 0, label: "Good placement of movable boxes in Room 15", separator: true },
                                { offset: 0x2b, bit: 0, label: "Potion HP in Room 7" },
                                { offset: 0x2b, bit: 5, label: "Potion HP in Room 12" },
                                { offset: 0x2b, bit: 2, label: "Potion HP in Room 13" },
                                { offset: 0x2c, bit: 0, label: "Potion HP in Room 25" },
                                { offset: 0x2a, bit: 5, label: "Potion MP in Room 1" },
                                { offset: 0x2a, bit: 7, label: "Potion MP in Room 6" },
                                { offset: 0x2b, bit: 4, label: "Potion MP in Room 18" },
                                { offset: 0x2a, bit: 6, label: "Potion Hearts in Room 8" },
                                { offset: 0x2b, bit: 1, label: "Potion Hearts in Room 10" },
                                { offset: 0x2b, bit: 3, label: "Potion Hearts in Room 13" },
                                { offset: 0x2b, bit: 6, label: "Potion Hearts in Room 23" },
                                { offset: 0x2b, bit: 7, label: "Potion Hearts in Room 24", separator: true },
                                { offset: 0x1f, bit: 1, label: "Wall destroyed in Room 6" },
                                { offset: 0x1e, bit: 7, label: "Wall destroyed in Room 7" },
                                { offset: 0x1f, bit: 2, label: "Wall destroyed in Room 14" },
                                { offset: 0x1f, bit: 0, label: "Wall destroyed in Room 17" },
                                { offset: 0x1f, bit: 3, label: "Wall destroyed in Room 21" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Underground Gallery",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xb4, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x32, bit: 7, label: "Dragon Zombie defeated in Room 3" },
                                { offset: 0x31, bit: 4, label: "Heavy Ring in Room 0", separator: true },
                                { offset: 0x2c, bit: 4, label: "Potion HP in Room 6" },
                                { offset: 0x2c, bit: 1, label: "Potion HP in Room 11" },
                                { offset: 0x2c, bit: 7, label: "Potion HP in Room 22" },
                                { offset: 0x2c, bit: 5, label: "Potion MP in Room 6" },
                                { offset: 0x2d, bit: 1, label: "Potion MP in Room 16" },
                                { offset: 0x2c, bit: 6, label: "Potion MP in Room 20" },
                                { offset: 0x2c, bit: 3, label: "Potion Hearts in Room 9" },
                                { offset: 0x2c, bit: 2, label: "Potion Hearts in Room 10" },
                                { offset: 0x2d, bit: 0, label: "Potion Hearts in Room 12", separator: true },
                                { offset: 0x1f, bit: 5, label: "Wall destroyed in Room 1" },
                                { offset: 0x1f, bit: 4, label: "Wall destroyed in Room 13" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Underground Waterway",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Location discovered",
                              offset: 0xb5,
                              type: "variable",
                              dataType: "boolean",
                            },
                            {
                              name: "Cleaned Water",
                              offset: 0x3df,
                              type: "variable",
                              dataType: "boolean",
                              resource: "undergroundWaterwayWater",
                              separator: true,
                            },
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x1c, bit: 1, label: "Switches Position" },
                                { offset: 0x33, bit: 1, label: "Camilla defeated in Room 13" },
                                { offset: 0x31, bit: 7, label: "Roc Wind in Room 15", separator: true },
                                { offset: 0x2d, bit: 3, label: "Potion HP in Room 2" },
                                { offset: 0x2d, bit: 4, label: "Potion HP in Room 4" },
                                { offset: 0x2d, bit: 5, label: "Potion HP in Room 7" },
                                { offset: 0x2e, bit: 5, label: "Potion HP in Room 18" },
                                { offset: 0x2e, bit: 6, label: "Potion HP in Room 19" },
                                { offset: 0x2d, bit: 6, label: "Potion MP in Room 6" },
                                { offset: 0x2d, bit: 7, label: "Potion MP in Room 6" },
                                { offset: 0x2e, bit: 1, label: "Potion MP in Room 10" },
                                { offset: 0x2e, bit: 4, label: "Potion MP in Room 17" },
                                { offset: 0x2e, bit: 3, label: "Potion Hearts in Room 0" },
                                { offset: 0x2d, bit: 2, label: "Potion Hearts in Room 2" },
                                { offset: 0x2e, bit: 0, label: "Potion Hearts in Room 10" },
                                { offset: 0x2e, bit: 2, label: "Potion Hearts in Room 11", separator: true },
                                { offset: 0x1f, bit: 6, label: "Wall destroyed in Room 1" },
                                { offset: 0x1f, bit: 7, label: "Wall destroyed in Room 3" },
                                { offset: 0x20, bit: 0, label: "Wall destroyed in Room 5" },
                                { offset: 0x20, bit: 1, label: "Wall destroyed in Room 11" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Outer Wall",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xb6, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x2f, bit: 3, label: "Potion HP in Room 1" },
                                { offset: 0x2f, bit: 5, label: "Potion HP in Room 2" },
                                { offset: 0x2f, bit: 0, label: "Potion HP in Room 4" },
                                { offset: 0x2f, bit: 1, label: "Potion MP in Room 0" },
                                { offset: 0x2f, bit: 4, label: "Potion MP in Room 1" },
                                { offset: 0x2e, bit: 7, label: "Potion MP in Room 3" },
                                { offset: 0x2f, bit: 2, label: "Potion Hearts in Room 0" },
                                { offset: 0x2f, bit: 6, label: "Potion Hearts in Room 5", separator: true },
                                { offset: 0x20, bit: 2, label: "Wall destroyed in Room 3" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Observation Tower",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xb7, bit: 0, label: "Location discovered" },
                                { offset: 0xaa, bit: 0, label: "Warp Room activated", separator: true },
                                { offset: 0x33, bit: 2, label: "Hugh defeated in Room 1" },
                                { offset: 0x32, bit: 0, label: "Last Key in Room 0", separator: true },
                                { offset: 0x30, bit: 0, label: "Potion HP in Room 11" },
                                { offset: 0x30, bit: 6, label: "Potion HP in Room 18" },
                                { offset: 0x30, bit: 2, label: "Potion MP in Room 8" },
                                { offset: 0x30, bit: 4, label: "Potion MP in Room 20" },
                                { offset: 0x30, bit: 3, label: "Potion Hearts in Room 6" },
                                { offset: 0x2f, bit: 7, label: "Potion Hearts in Room 13" },
                                { offset: 0x30, bit: 1, label: "Potion Hearts in Room 17" },
                                { offset: 0x30, bit: 5, label: "Potion Hearts in Room 19", separator: true },
                                { offset: 0x20, bit: 3, label: "Wall destroyed in Room 3" },
                                { offset: 0x20, bit: 4, label: "Wall destroyed in Room 9" },
                                { offset: 0x20, bit: 6, label: "Wall destroyed in Room 9" },
                                { offset: 0x20, bit: 5, label: "Wall destroyed in Room 12" },
                                { offset: 0x20, bit: 7, label: "Wall destroyed in Room 14" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Ceremonial Room",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xb8, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x33, bit: 3, label: "Dracula 1st defeated in Room 1" },
                                { offset: 0x22, bit: 4, label: "Lights to Dracula 2nd in Room 1", separator: true },
                                { offset: 0x30, bit: 7, label: "Potion HP in Room 2", separator: true },
                                { offset: 0x21, bit: 0, label: "Wall destroyed in Room 0" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Battle Arena",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0xb9, bit: 0, label: "Location discovered", separator: true },
                                { offset: 0x32, bit: 2, label: "Shining Armor" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Debug Room",
                      items: [
                        {
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Debug Location discovered",
                              offset: 0xba,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Maps",
              planned: true,
              items: [
                {
                  name: "Map Revealance",
                  type: "section",
                  background: true,
                  items: [
                    {
                      name: "Link to secret rooms 1",
                      offset: 0xc0,
                      type: "variable",
                      dataType: "boolean",
                    },
                    {
                      name: "Link to secret rooms 2",
                      offset: 0xc1,
                      type: "variable",
                      dataType: "boolean",
                    },
                    {
                      name: "Link to secret rooms 3",
                      offset: 0xc2,
                      type: "variable",
                      dataType: "boolean",
                    },
                    {
                      name: "Link to secret rooms 4",
                      offset: 0xc3,
                      type: "variable",
                      dataType: "boolean",
                    },
                    {
                      name: "Link to secret rooms 5",
                      offset: 0xc4,
                      type: "variable",
                      dataType: "boolean",
                    },
                  ],
                },
              ],
            },
            {
              name: "Config",
              flex: true,
              items: [
                {
                  name: "Button Attack",
                  offset: 0x3cc,
                  type: "variable",
                  dataType: "uint16",
                  resource: "buttons",
                },
                {
                  name: "Button Jump",
                  offset: 0x3ce,
                  type: "variable",
                  dataType: "uint16",
                  resource: "buttons",
                },
                {
                  name: "Button Special Move",
                  offset: 0x3d0,
                  type: "variable",
                  dataType: "uint16",
                  resource: "buttons",
                },
                {
                  name: "Button DSS",
                  offset: 0x3d2,
                  type: "variable",
                  dataType: "uint16",
                  resource: "buttons",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    buttons: {
      0x1: "A",
      0x2: "B",
      0x100: "R",
      0x200: "L",
    },
    dssAttribute: {
      0x1: "DSS Salamander",
      0x2: "DSS Serpent",
      0x3: "DSS Mandragora",
      0x4: "DSS Golem",
      0x5: "DSS Cockatrice",
      0x6: "DSS Manticore",
      0x7: "DSS Griffin",
      0x8: "DSS Thunder Bird",
      0x9: "DSS Unicorn",
      0xa: "DSS Black Dog",
    },
    dssAction: {
      0x1: "DSS Mercury",
      0x2: "DSS Venus",
      0x3: "DSS Jupiter",
      0x4: "DSS Mars",
      0x5: "DSS Diana",
      0x6: "DSS Apollo",
      0x7: "DSS Neptune",
      0x8: "DSS Saturn",
      0x9: "DSS Uranus",
      0xa: "DSS Pluto",
    },
    equipments: {
      0x0: "-",
      0x1: "Leather Armor",
      0x2: "Bronze Armor",
      0x3: "Gold Armor",
      0x4: "Chain Mail",
      0x5: "Steel Armor",
      0x6: "Platinum Armor",
      0x7: "Diamond Armor",
      0x8: "Mirror Armor",
      0x9: "Needle Armor",
      0xa: "Dark Armor",
      0xb: "Shining Armor",
      0xc: "Cotton Robe",
      0xd: "Silk Robe",
      0xe: "Rainbow Robe",
      0xf: "Magic Robe",
      0x10: "Sage Robe",
      0x11: "Cotton Clothes",
      0x12: "Prison Garb",
      0x13: "Stylish Suit",
      0x14: "Night Suit",
      0x15: "Ninja Garb",
      0x16: "Soldier Fatigues",
      0x17: "Double Grips",
      0x18: "Star Bracelet",
      0x19: "Strengh Ring",
      0x1a: "Hard Ring",
      0x1b: "Intelligence Ring",
      0x1c: "Luck Ring",
      0x1d: "Cursed Ring",
      0x1e: "Strength Armband",
      0x1f: "Defense Armband",
      0x20: "Sage Armband",
      0x21: "Gambler Armband",
      0x22: "Wrist Band",
      0x23: "Gauntlet",
      0x24: "Arm Guard",
      0x25: "Magic Gauntlet",
      0x26: "Miracle Armband",
      0x27: "Toy Ring",
      0x28: "Bear Ring",
    },
    letters: {
      0x0: " ",
      0x1: "A",
      0x2: "B",
      0x3: "C",
      0x4: "D",
      0x5: "E",
      0x6: "F",
      0x7: "G",
      0x8: "H",
      0x9: "I",
      0xa: "J",
      0xb: "K",
      0xc: "L",
      0xd: "M",
      0xe: "N",
      0xf: "O",
      0x10: "P",
      0x11: "Q",
      0x12: "R",
      0x13: "S",
      0x14: "T",
      0x15: "U",
      0x16: "V",
      0x17: "W",
      0x18: "X",
      0x19: "Y",
      0x1a: "Z",
      0x1b: "&",
      0x1c: ".",
      0x1d: "'",
      0x1e: "-",
      0x1f: "!",
      0x20: "★",
      0x21: "j",
    },
    locations: {
      0x10b: "Catacomb: Room 11",
      0x111: "Catacomb: Room 17",
      0x119: "Catacomb: Room 25",
      0x202: "Abyss Stairway: Room 2",
      0x305: "Audience Room: Room 5",
      0x30e: "Audience Room: Room 14",
      0x311: "Audience Room: Room 17",
      0x506: "Machine Tower: Room 6",
      0x50a: "Machine Tower: Room 10",
      0x513: "Machine Tower: Room 19",
      0x707: "Chapel Tower: Room 7",
      0x710: "Chapel Tower: Room 16",
      0x71b: "Chapel Tower: Room 27",
      0x804: "Underground Warehouse: Room 4",
      0x810: "Underground Warehouse: Room 16",
      0x902: "Underground Gallery: Room 2",
      0x917: "Underground Gallery: Room 23",
      0xa08: "Underground Waterway: Room 8",
      0xa0c: "Underground Waterway: Room 12",
      0xc07: "Observation Tower: Room 7",
      0xf01: "Debug Room",
    },
    modes: {
      0x0: "Vampire Killer Mode",
      0x1: "Shooter Mode",
      0x2: "Magician Mode",
      0x3: "Fighter Mode",
      0x4: "Thief Mode",
    },
    subweapons: {
      0x0: "-",
      0x1: "Knife",
      0x2: "Axe",
      0x3: "Holy Water",
      0x4: "Cross",
      0x5: "Clock",
    },
    undergroundWaterwayWater: {
      0: 0x0,
      1: 0x3,
    },
  },
  resourcesOrder: {
    modes: [0x0, 0x2, 0x3, 0x1, 0x4],
  },
};

export default template;
