import type { GameJson } from "$lib/types";

const template: GameJson = {
  validator: {
    regions: {
      europe: {
        0x0: [0x4e, 0x47, 0x4d, 0x50], // "NGMP"
      },
      usa: {
        0x0: [0x4e, 0x47, 0x4d, 0x45], // "NGME"
      },
      japan: {},
    },
    text: "Drag 'n' drop here or click to add a save file.",
    hint: "If you're having trouble loading a save file from an Everdrive cartridge, please see the FAQ.",
    error: "Not a valid save file.",
  },
  items: [
    {
      id: "slots",
      length: 0x200,
      type: "container",
      instanceType: "tabs",
      instances: 3,
      enumeration: "Slot %d",
      disableSubinstanceIf: {
        offset: 0x108,
        type: "variable",
        dataType: "uint8",
        operator: "=",
        value: 0x0,
      },
      appendSubinstance: [
        {
          name: "Options",
          items: [
            {
              name: "Checksum Options",
              offset: 0x4,
              type: "checksum",
              dataType: "uint32",
              control: {
                offsetStart: 0x0,
                offsetEnd: 0x10,
              },
              bigEndian: true,
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  id: "language",
                  name: "Language",
                  offset: 0x8,
                  type: "variable",
                  dataType: "uint8",
                  resource: "languages",
                  test: true,
                },
                {
                  name: "Sound",
                  offset: 0x9,
                  type: "variable",
                  dataType: "uint8",
                  resource: "sounds",
                },
              ],
            },
          ],
        },
      ],
      items: [
        {
          name: "Checksum",
          offset: 0x104,
          type: "checksum",
          dataType: "uint32",
          control: {
            offsetStart: 0x100,
            offsetEnd: 0x230,
          },
          bigEndian: true,
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "entryPassCount-total-%index%",
                          name: "Entry Pass Count",
                          offset: 0x16e,
                          type: "variable",
                          dataType: "uint8",
                          disabled: true,
                          test: true,
                        },
                        {
                          name: "Location",
                          offset: 0x108,
                          type: "variable",
                          dataType: "uint8",
                          resource: "locations",
                          autocomplete: true,
                        },
                        {
                          name: "Unlocked Characters",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Goemon",
                              offset: 0x109,
                              type: "variable",
                              dataType: "boolean",
                              disabled: true,
                            },
                            {
                              name: "Ebisumaru",
                              offset: 0x109,
                              type: "variable",
                              dataType: "boolean",
                              disabled: true,
                            },
                            {
                              id: "characters",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x20f, bit: 7, label: "Sasuke" },
                                { offset: 0x212, bit: 7, label: "Yae" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Unlocked Powers",
                          type: "bitflags",
                          flags: [
                            { offset: 0x122, bit: 2, label: "Chain Pipe" },
                            { offset: 0x123, bit: 3, label: "Underwater Device" },
                          ],
                        },
                      ],
                    },
                    {
                      type: "section",
                      items: [
                        {
                          id: "costumes-%index%",
                          name: "Costumes",
                          type: "bitflags",
                          flags: [
                            { offset: 0x130, bit: 5, label: "Allow to buy alternatives costumes", separator: true },
                            { offset: 0x21c, bit: 0, label: "Goemon: Impact" },
                            { offset: 0x21d, bit: 0, label: "Goemon: Satchel" },
                            { offset: 0x21e, bit: 0, label: "Goemon: Turban", separator: true },
                            { offset: 0x220, bit: 0, label: "Ebisumaru: Sumo belt" },
                            { offset: 0x221, bit: 0, label: "Ebisumaru: Tights" },
                            { offset: 0x222, bit: 0, label: "Ebisumaru: Raccoon", separator: true },
                            { offset: 0x224, bit: 0, label: "Sasuke: Bloomers" },
                            { offset: 0x225, bit: 0, label: "Sasuke: Maid outfit" },
                            { offset: 0x226, bit: 0, label: "Sasuke: Fur coat", separator: true },
                            { offset: 0x228, bit: 0, label: "Yae: Kirameki Uniform" },
                            { offset: 0x229, bit: 0, label: "Yae: Rabbit fur" },
                            { offset: 0x22a, bit: 0, label: "Yae: Swimsuit" },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      name: "Unlocked Characters",
                      offset: 0x109,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Costume Goemon",
                      offset: 0x21b,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      name: "Costume Ebisumaru",
                      offset: 0x21f,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      name: "Costume Sasuke",
                      offset: 0x223,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      name: "Costume Yae",
                      offset: 0x227,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      type: "section",
                      items: [
                        {
                          id: "costumesBought-%index%",
                          name: "Costumes",
                          type: "bitflags",
                          flags: [
                            { offset: 0x131, bit: 0, label: "Goemon: Impact bought" },
                            { offset: 0x131, bit: 1, label: "Goemon: Satchel bought" },
                            { offset: 0x131, bit: 2, label: "Goemon: Turban bought", separator: true },
                            { offset: 0x131, bit: 3, label: "Ebisumaru: Sumo belt bought" },
                            { offset: 0x131, bit: 4, label: "Ebisumaru: Tights bought" },
                            { offset: 0x131, bit: 5, label: "Ebisumaru: Raccoon bought", separator: true },
                            { offset: 0x131, bit: 6, label: "Sasuke: Bloomers bought" },
                            { offset: 0x131, bit: 7, label: "Sasuke: Maid outfit bought" },
                            { offset: 0x132, bit: 0, label: "Sasuke: Fur coat bought", separator: true },
                            { offset: 0x132, bit: 1, label: "Yae: Kirameki Uniform bought" },
                            { offset: 0x132, bit: 2, label: "Yae: Rabbit fur bought" },
                            { offset: 0x132, bit: 3, label: "Yae: Swimsuit bought" },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Players",
              flex: true,
              items: [
                {
                  length: 0xa,
                  type: "container",
                  instanceType: "tabs",
                  instances: 4,
                  enumeration: "Player %d",
                  vertical: true,
                  flex: true,
                  items: [
                    {
                      name: "Character",
                      offset: 0x17a,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Lifes",
                      offset: 0x17b,
                      type: "variable",
                      dataType: "uint8",
                      operations: [{ "-": 1 }],
                      min: 2,
                      max: 99,
                    },
                    {
                      name: "Health",
                      offset: 0x17c,
                      type: "variable",
                      dataType: "uint8",
                      disabled: true,
                    },
                    {
                      name: "Armor",
                      offset: 0x17d,
                      type: "variable",
                      dataType: "uint8",
                      max: 3,
                    },
                    {
                      name: "Coins",
                      offset: 0x17e,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 999,
                      test: true,
                    },
                    {
                      name: "???",
                      offset: 0x180,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Weapon Level",
                      offset: 0x181,
                      type: "variable",
                      dataType: "uint8",
                      max: 2,
                    },
                    {
                      name: "Item",
                      offset: 0x182,
                      type: "variable",
                      dataType: "uint8",
                      resource: "items",
                    },
                    {
                      name: "???",
                      offset: 0x183,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
              ],
            },
            {
              name: "Levels",
              flex: true,
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Edo",
                      flex: true,
                      items: [
                        {
                          id: "entryPassCount-edo-%index%",
                          name: "Edo Entry Pass Count",
                          offset: 0x16e,
                          type: "variable",
                          dataType: "uint8",
                          hidden: true,
                        },
                        {
                          name: "Home of Wiseman",
                          type: "section",
                          background: true,
                          hidden: true,
                          items: [
                            {
                              name: "Cleared",
                              offset: 0x1aa,
                              type: "variable",
                              dataType: "boolean",
                            },
                          ],
                        },
                        {
                          name: "Lost'n Road",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1a2,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-edo-%index%-142",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11d, bit: 0, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ab,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Ringbell Pass",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1a4,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-edo-%index%-145",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11d, bit: 2, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ae,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Digadig Gold Mine",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1a5,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-edo-%index%-144",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x207, bit: 7, label: "Event: Skeleton Boss defeated", separator: true },
                                { offset: 0x11d, bit: 1, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ad,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          items: [
                            {
                              name: "Lost'n Town",
                              type: "section",
                              background: true,
                              items: [
                                {
                                  name: "Access",
                                  offset: 0x1a3,
                                  type: "variable",
                                  dataType: "boolean",
                                  resource: "levelsAccess",
                                  separator: true,
                                },
                                {
                                  id: "entryPass-edo-%index%",
                                  type: "bitflags",
                                  noMargin: true,
                                  flags: [
                                    { offset: 0x10a, bit: 1, label: "Beat Mania's LP", hidden: true },
                                    { offset: 0x10a, bit: 2, label: "Beat Mania's Mic", hidden: true },
                                    { offset: 0x10a, bit: 3, label: "Beat Mania's Headphones", hidden: true },
                                    { offset: 0x11c, bit: 6, label: "Entry Pass: Beat Mania" },
                                    { offset: 0x11c, bit: 7, label: "Entry Pass: Tomezo" },
                                    { offset: 0x122, bit: 3, label: "Entry Pass: Iguana Man" },
                                  ],
                                },
                                {
                                  name: "Cleared",
                                  offset: 0x1ac,
                                  type: "variable",
                                  dataType: "boolean",
                                  hidden: true,
                                },
                              ],
                            },
                            {
                              name: "Money given to Kenzo",
                              offset: 0x178,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              max: 100,
                            },
                          ],
                        },
                        {
                          name: "Edo Checkpoint",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access by Digadig Gold Mine",
                              offset: 0x1a6,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Access by Ringbell Pass",
                              offset: 0x1a7,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Doors Open",
                              offset: 0x1af,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                          ],
                        },
                        {
                          name: "Edo Castle",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1a8,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              id: "castleCleared-143",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x121, bit: 5, label: "Cleared" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1b0,
                              type: "variable",
                              dataType: "boolean",
                              resource: "castlesCleared",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Ryugu",
                      flex: true,
                      items: [
                        {
                          id: "entryPassCount-ryugu-%index%",
                          name: "Ryugu Entry Pass Count",
                          offset: 0x16f,
                          type: "variable",
                          dataType: "uint8",
                          hidden: true,
                        },
                        {
                          name: "Kappa Road",
                          type: "section",
                          background: true,
                          items: [
                            {
                              id: "entryPass-ryugu-%index%-157",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x10b, bit: 7, label: "Large octopus defeated", hidden: true },
                                { offset: 0x11d, bit: 4, label: "Entry Pass: Large octopus" },
                                { offset: 0x11d, bit: 6, label: "Entry Pass: Stage Clear (to Frog Mountain)" },
                                { offset: 0x11e, bit: 1, label: "Entry Pass: Stage Clear (to Naruto Road)" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ba,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Naruto Road",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1b2,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-ryugu-%index%-159",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x10c, bit: 0, label: "Large octopus defeated", hidden: true },
                                { offset: 0x11d, bit: 5, label: "Entry Pass: Large octopus" },
                                { offset: 0x11e, bit: 0, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1bd,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Frog Mountain",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1b6,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-ryugu-%index%-158",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11e, bit: 2, label: "Entry Pass: Iguana Man" },
                                { offset: 0x11d, bit: 7, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1bb,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Otohime Town",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access by Frog Mountain",
                              offset: 0x1b4,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Access by Naruto Road",
                              offset: 0x1b5,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-ryugu-%index%",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11d, bit: 3, label: "Entry Pass: Obisumaru" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1bc,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Ryugu Checkpoint",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1b3,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Doors Open",
                              offset: 0x1be,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                          ],
                        },
                        {
                          name: "Ryugu Castle",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1b7,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              id: "castleCleared-158",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x121, bit: 6, label: "Cleared" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1bf,
                              type: "variable",
                              dataType: "boolean",
                              resource: "castlesCleared",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Mafu Island",
                      flex: true,
                      items: [
                        {
                          id: "entryPassCount-mafuIsland-%index%",
                          name: "Mafu Island Entry Pass Count",
                          offset: 0x170,
                          type: "variable",
                          dataType: "uint8",
                          hidden: true,
                        },
                        {
                          name: "Kokeshi Road",
                          type: "section",
                          background: true,
                          items: [
                            {
                              id: "entryPass-mafuIsland-%index%-172",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11e, bit: 7, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ca,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Maneater Road",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1c2,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-mafuIsland-%index%-172",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11f, bit: 0, label: "Entry Pass: Stage Clear (to Pochan Lake)" },
                                { offset: 0x11f, bit: 3, label: "Entry Pass: Stage Clear (to Tomb Pass)" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1cb,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Pochan Lake",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1c3,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-mafuIsland-%index%-173",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11f, bit: 2, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1cc,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Tomb Pass",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1c4,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-mafuIsland-%index%-175",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11f, bit: 1, label: "Entry Pass: Stage Clear (to Spook Village)" },
                                { offset: 0x123, bit: 1, label: "Entry Pass: Stage Clear (to Mafu Checkpoint)" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ce,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Spook Village",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access by Pochan Lake",
                              offset: 0x1c5,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Access by Tomb Pass",
                              offset: 0x1c7,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-mafuIsland-%index%",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11e, bit: 3, label: "Entry Pass: Roadside guardian" },
                                { offset: 0x11e, bit: 4, label: "Entry Pass: Old woman" },
                                { offset: 0x11e, bit: 5, label: "Entry Pass: Fireworks Boss" },
                                { offset: 0x11e, bit: 6, label: "Entry Pass: Iguana Men" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1cd,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Mafu Checkpoint",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1c6,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Doors Open",
                              offset: 0x1cf,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                          ],
                        },
                        {
                          name: "Majin Castle",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1c8,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              id: "castleCleared-175",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x121, bit: 7, label: "Cleared" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1d0,
                              type: "variable",
                              dataType: "boolean",
                              resource: "castlesCleared",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Underworld",
                      flex: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          noMargin: true,
                          hidden: true,
                          items: [
                            {
                              id: "entryPassCount-underworld-%index%",
                              name: "Underworld Entry Pass Count",
                              offset: 0x171,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              id: "entryPassCount-creepVillage-%index%",
                              name: "Creep Village Entry Pass Count",
                              offset: 0x173,
                              type: "variable",
                              dataType: "uint8",
                            },
                          ],
                        },
                        {
                          name: "Kaiware Road",
                          type: "section",
                          background: true,
                          items: [
                            {
                              id: "entryPass-underworld-%index%-186",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x11f, bit: 5, label: "Entry Pass: Okiku" },
                                { offset: 0x120, bit: 0, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1da,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Mokeke Forest",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1d2,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-underworld-%index%-187",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x120, bit: 1, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1db,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Wonder Valley",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1d4,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-underworld-%index%-188",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x120, bit: 2, label: "Entry Pass: Stage Clear (to Tree Stump Village)" },
                                { offset: 0x123, bit: 2, label: "Entry Pass: Stage Clear (to Underworld Checkpoint)" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1dc,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          items: [
                            {
                              name: "Tree Stump Village",
                              type: "section",
                              background: true,
                              items: [
                                {
                                  name: "Access",
                                  offset: 0x1d5,
                                  type: "variable",
                                  dataType: "boolean",
                                  resource: "levelsAccess",
                                  separator: true,
                                },
                                {
                                  id: "entryPass-underworld-%index%",
                                  type: "bitflags",
                                  noMargin: true,
                                  flags: [
                                    { offset: 0x11f, bit: 4, label: "Entry Pass: Hide and seek" },
                                    { offset: 0x11f, bit: 6, label: "Entry Pass: Girl" },
                                    { offset: 0x11f, bit: 7, label: "Entry Pass: Kensuke" },
                                  ],
                                },
                                {
                                  name: "Cleared",
                                  offset: 0x1dd,
                                  type: "variable",
                                  dataType: "boolean",
                                  hidden: true,
                                },
                              ],
                            },
                            {
                              name: "Money given to Kensuke",
                              offset: 0x176,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              max: 3500,
                            },
                          ],
                        },
                        {
                          name: "Creep Village",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1d3,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-creepVillage-%index%",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x122, bit: 4, label: "Entry Pass: Waterfall" },
                                { offset: 0x122, bit: 7, label: "Entry Pass: Admirative Tengu" },
                                { offset: 0x123, bit: 0, label: "Entry Pass: Hungry Tengu" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1e0,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Underworld Checkpoint",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1d6,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Doors Open",
                              offset: 0x1de,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                          ],
                        },
                        {
                          name: "Underworld Castle",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1d7,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              id: "castleCleared-189",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x122, bit: 0, label: "Cleared" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1df,
                              type: "variable",
                              dataType: "boolean",
                              resource: "castlesCleared",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Floating Castle",
                      flex: true,
                      items: [
                        {
                          id: "entryPassCount-floatingCastle-%index%",
                          name: "Floating Castle Entry Pass Count",
                          offset: 0x172,
                          type: "variable",
                          dataType: "uint8",
                          hidden: true,
                        },
                        {
                          name: "Cloud Fortress",
                          type: "section",
                          background: true,
                          items: [
                            {
                              id: "entryPass-floatingCastle-%index%-201",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x121, bit: 0, label: "Entry Pass: Stage Clear (to Wind Castle Wall)" },
                                { offset: 0x121, bit: 3, label: "Entry Pass: Stage Clear (to Sky Garden)" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ea,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Wind Castle Wall",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1e2,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-floatingCastle-%index%-203",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x121, bit: 2, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ec,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Sky Garden",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1e3,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-floatingCastle-%index%-202",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x121, bit: 1, label: "Entry Pass: Stage Clear" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1eb,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Floating World Town",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access by Sky Garden",
                              offset: 0x1e4,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Access by Wind Castle",
                              offset: 0x1e6,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                              separator: true,
                            },
                            {
                              id: "entryPass-floatingCastle-%index%",
                              type: "bitflags",
                              noMargin: true,
                              flags: [
                                { offset: 0x120, bit: 4, label: "Entry Pass: Obisumaru" },
                                { offset: 0x120, bit: 5, label: "Entry Pass: Tagosaku" },
                                { offset: 0x120, bit: 6, label: "Entry Pass: Omatsu" },
                                { offset: 0x120, bit: 3, label: "Entry Pass: Scarfman 1" },
                                { offset: 0x120, bit: 7, label: "Entry Pass: Scarfman 2" },
                              ],
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ed,
                              type: "variable",
                              dataType: "boolean",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          name: "Floating Checkpoint",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1e5,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Doors Open",
                              offset: 0x1ee,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                          ],
                        },
                        {
                          name: "Dream Castle",
                          type: "section",
                          background: true,
                          items: [
                            {
                              name: "Access",
                              offset: 0x1e7,
                              type: "variable",
                              dataType: "boolean",
                              resource: "levelsAccess",
                            },
                            {
                              name: "Cleared",
                              offset: 0x1ef,
                              type: "variable",
                              dataType: "boolean",
                              resource: "castlesCleared",
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Vrac",
              flex: true,
              hidden: true,
              items: [
                {
                  type: "section",
                  items: [
                    {
                      name: "???",
                      type: "bitflags",
                      flags: [
                        { offset: 0x10a, bit: 0, label: "Lost'n Town: Beat Mania mission incomplete" },
                        { offset: 0x10a, bit: 4, label: "Lost'n Town: Meet Beat Mania" },
                        { offset: 0x10a, bit: 5, label: "Lost'n Town: Tomezo mission incomplete" },
                        { offset: 0x10a, bit: 6, label: "Lost'n Town: Meet with Tomezo" },
                        { offset: 0x10a, bit: 7, label: "Otohime Town: Obisumaru mission incomplete" },
                        { offset: 0x10b, bit: 0, label: "Frog Mountain: Race against Obisumaru won" },
                        { offset: 0x10b, bit: 1, label: "Otohime Town: Meet with Obisumaru" },
                        { offset: 0x10b, bit: 2, label: "Spook Village: Roadside guardian mission incomplete" },
                        { offset: 0x10b, bit: 4, label: "Spook Village: Meet with Roadside guardian" },
                        { offset: 0x10b, bit: 5, label: "Spook Village: Old woman mission incomplete" },
                        { offset: 0x10b, bit: 6, label: "Spook Village: Meet with Old woman" },
                        { offset: 0x10c, bit: 1, label: "???", hidden: true },
                        { offset: 0x10c, bit: 2, label: "Spook Village: Meet with Boss" },
                        { offset: 0x10c, bit: 4, label: "Tree Stump Village: Meet with Child" },
                        { offset: 0x10c, bit: 7, label: "Tree Stump Village: Girl mission incomplete" },
                        { offset: 0x10d, bit: 0, label: "Tree Stump Village: Meet with Girl" },
                        { offset: 0x10d, bit: 1, label: "Tree Stump Village: Meet with Kensuke" },
                        { offset: 0x10d, bit: 4, label: "???", hidden: true },
                        { offset: 0x10d, bit: 6, label: "Tree Stump Village: Red Hider found" },
                        { offset: 0x10d, bit: 7, label: "Tree Stump Village: Black Hider found" },
                        { offset: 0x10e, bit: 0, label: "Tree Stump Village: Blue Hider found" },
                        { offset: 0x10e, bit: 1, label: "Tree Stump Village: Green Hider found" },
                        { offset: 0x10e, bit: 2, label: "Tree Stump Village: Pink Hider found" },
                        { offset: 0x10e, bit: 3, label: "Tree Stump Village: Yellow Hider found" },
                        { offset: 0x10e, bit: 5, label: "???", hidden: true },
                        { offset: 0x10e, bit: 7, label: "???", hidden: true },
                        { offset: 0x10f, bit: 0, label: "Floating World Town: Meet with Omatsu" },
                        { offset: 0x10f, bit: 1, label: "Floating World Town: Omatsu mission incomplete" },
                        { offset: 0x10f, bit: 2, label: "Floating World Town: Omatsu husband found" },
                        { offset: 0x10f, bit: 3, label: "Floating World Town: Scarfman ask for a letter of introduction" },
                        { offset: 0x10f, bit: 4, label: "Floating World Town: Letter of introduction received" },
                        { offset: 0x10f, bit: 5, label: "Floating World Town: Meet with Scarfman" },
                        { offset: 0x10f, bit: 6, label: "Floating World Town: Scarfman mission 1 complete" },
                        { offset: 0x10f, bit: 7, label: "Floating World Town: Scarfman mission 2 complete" },
                        { offset: 0x110, bit: 0, label: "Floating World Town: Obisumaru mission incomplete" },
                        { offset: 0x110, bit: 1, label: "Wind Castle Wall: Race against Obisumaru won" },
                        { offset: 0x110, bit: 2, label: "Floating World Town: Meet with Obisumaru" },
                        { offset: 0x111, bit: 0, label: "Lost'n Town: Meet with Kenzo" },
                        { offset: 0x111, bit: 1, label: "Lost'n Town: 100 Coins given to Kenzo" },
                        { offset: 0x111, bit: 4, label: "Spook Village: Iguana Men Quest - Video received" },
                        { offset: 0x111, bit: 5, label: "Spook Village: Iguana Men Quest - Pencil received" },
                        { offset: 0x111, bit: 6, label: "Spook Village: Iguana Men Quest - Handkerchief received" },
                        { offset: 0x111, bit: 7, label: "Spook Village: Iguana Men Quest - Comic book received" },
                        { offset: 0x112, bit: 0, label: "Spook Village: Iguana Men Quest - Video given" },
                        { offset: 0x112, bit: 1, label: "Spook Village: Iguana Men Quest - Pencil given" },
                        { offset: 0x112, bit: 2, label: "Spook Village: Iguana Men Quest - Handkerchief given" },
                        { offset: 0x112, bit: 4, label: "???", hidden: true },
                        { offset: 0x112, bit: 5, label: "???", hidden: true },
                        { offset: 0x112, bit: 6, label: "Creep Village: Rice ball given to hungry Tengu 1" },
                        { offset: 0x112, bit: 7, label: "Creep Village: Rice ball given to hungry Tengu 2" },
                        { offset: 0x113, bit: 0, label: "Creep Village: Rice ball given to hungry Tengu 3" },
                        { offset: 0x113, bit: 1, label: "???", hidden: true },
                        { offset: 0x122, bit: 5, label: "Mum design dish bought" },
                        { offset: 0x122, bit: 6, label: "???", hidden: true },
                        { offset: 0x12f, bit: 4, label: "???", hidden: true },
                        { offset: 0x12f, bit: 5, label: "???", hidden: true },
                        { offset: 0x12f, bit: 6, label: "???", hidden: true },
                        { offset: 0x13c, bit: 0, label: "???", hidden: true },
                        { offset: 0x13c, bit: 1, label: "???", hidden: true },
                        { offset: 0x13c, bit: 2, label: "???", hidden: true },
                        { offset: 0x13c, bit: 3, label: "???", hidden: true },
                        { offset: 0x13c, bit: 5, label: "???", hidden: true },
                        { offset: 0x13c, bit: 6, label: "???", hidden: true },
                        { offset: 0x13c, bit: 7, label: "???", hidden: true },
                        { offset: 0x13d, bit: 1, label: "???", hidden: true },
                        { offset: 0x13d, bit: 2, label: "???", hidden: true },
                        { offset: 0x13d, bit: 3, label: "???", hidden: true },
                        { offset: 0x13d, bit: 4, label: "???", hidden: true },
                        { offset: 0x13d, bit: 5, label: "???", hidden: true },
                        { offset: 0x13d, bit: 6, label: "???", hidden: true },
                        { offset: 0x13d, bit: 7, label: "???", hidden: true },
                        { offset: 0x13e, bit: 1, label: "???", hidden: true },
                        { offset: 0x13e, bit: 3, label: "???", hidden: true },
                        { offset: 0x13e, bit: 4, label: "???", hidden: true },
                        { offset: 0x13e, bit: 5, label: "???", hidden: true },
                        { offset: 0x13e, bit: 6, label: "???", hidden: true },
                        { offset: 0x13e, bit: 7, label: "???", hidden: true },
                        { offset: 0x13f, bit: 0, label: "???", hidden: true },
                        { offset: 0x13f, bit: 1, label: "???", hidden: true },
                        { offset: 0x13f, bit: 4, label: "???", hidden: true },
                        { offset: 0x13f, bit: 7, label: "???", hidden: true },
                      ],
                    },
                    {
                      name: "??? 0x202",
                      offset: 0x202,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x203",
                      offset: 0x203,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x204",
                      offset: 0x204,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x205",
                      offset: 0x205,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x206",
                      offset: 0x206,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x209",
                      offset: 0x209,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x20a",
                      offset: 0x20a,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x20b",
                      offset: 0x20b,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x20c",
                      offset: 0x20c,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x20d",
                      offset: 0x20d,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x20e",
                      offset: 0x20e,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x210",
                      offset: 0x210,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x211",
                      offset: 0x211,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x213",
                      offset: 0x213,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Spook Village: Meet Wiseman",
                      offset: 0x214,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      name: "??? 0x215",
                      offset: 0x215,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x216",
                      offset: 0x216,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x217",
                      offset: 0x217,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x218",
                      offset: 0x218,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x219",
                      offset: 0x219,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x21a",
                      offset: 0x21a,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "??? 0x22b",
                      offset: 0x22b,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    items: {
      0x0: "-",
      0x1: "Rice balls",
      0x2: "Plum rice balls",
      0x3: "Fish rice balls",
    },
    levelsAccess: {
      0x0: "0",
      0x1: "3",
    },
    castlesCleared: {
      0x0: "0",
      0x1: "7",
    },
    languages: [
      // Europe
      {
        0x0: "English",
        0x1: "French",
        0x2: "German",
      },
      // USA
      {
        0x0: "English",
      },
      // Japan
      {
        0x0: "Japanese",
      },
    ],
    locations: {
      0x1: "Lost'n Town",
      0x2: "Otohime Town",
      0x3: "Spook Village",
      0x4: "Tree Stump Village",
      0x5: "Floating World Town",
      0x6: "Creep Village",
      0x7: "Home of Wiseman",
      0x8: "Kappa Road",
      0x9: "Kokeshi Road",
      0xa: "Kaiware Road",
      0xb: "Cloud Fortress",
      // 0xc: "Edo Castle", // Unused
      // 0xd: "Ryugu Castle", // Unused
      // 0xe: "Majin Castle", // Unused
      // 0xf: "Underworld Castle", // Unused
      // 0x10: "Dream Castle", // Unused
    },
    sounds: {
      0x0: "Stereo",
      0x1: "Monaural",
    },
  },
  resourcesOrder: {
    locations: [0x7, 0x1, 0x8, 0x2, 0x9, 0x3, 0xa, 0x4, 0x6, 0xb, 0x5],
  },
};

export default template;
