import type { GameJson } from "$lib/types";

export const europeUsaValidator = [
  0x4d, 0x56, 0x4c, 0x56, 0x53, 0x43, 0x50, 0x32, 0x5f, 0x53, 0x59, 0x53,
]; // "MVLVSCP2_SYS"
export const japanValidator = [
  0x4d, 0x56, 0x4c, 0x56, 0x53, 0x2e, 0x43, 0x32, 0x5f, 0x53, 0x59, 0x53,
]; // "MVLVS.C2_SYS"

const template: GameJson = {
  validator: {
    regions: {
      europe_usa: {
        $or: [
          { 0x4: europeUsaValidator },
          ...[...Array(100).keys()].map((index) => ({
            [0x400 + index * 0x20 + 0x4]: europeUsaValidator,
          })),
        ],
      },
      japan: {
        $or: [
          { 0x4: japanValidator },
          ...[...Array(100).keys()].map((index) => ({
            [0x400 + index * 0x20 + 0x4]: japanValidator,
          })),
        ],
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    hint: "Currently only works with DCI (.dci files)<br />and 128 KB VMU raw dump (.bin files).",
    error: "Not a valid save file.",
  },
  items: [
    {
      type: "section",
      flex: true,
      hidden: true,
      items: [
        {
          name: "Checksum",
          offset: 0x9a4,
          type: "checksum",
          dataType: "uint32",
          control: {
            offsetStart: 0x280,
            offsetEnd: 0x9a8,
          },
        },
        {
          id: "checksumVmu",
          name: "Checksum VMU",
          offset: 0x46,
          type: "checksum",
          dataType: "uint16",
          control: {
            offsetStart: 0x0,
            offsetEnd: 0x9a8,
          },
        },
      ],
    },
    {
      type: "tabs",
      items: [
        {
          name: "General",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Level",
                  offset: 0x28c,
                  type: "variable",
                  dataType: "uint8",
                  max: 99,
                },
                {
                  name: "Experience",
                  offset: 0x28d,
                  type: "variable",
                  dataType: "uint8",
                  max: 99,
                },
                {
                  name: "Play Time",
                  type: "group",
                  mode: "time",
                  items: [
                    {
                      offset: 0x2a5,
                      type: "variable",
                      dataType: "uint8",
                      max: 99,
                    },
                    {
                      offset: 0x2a6,
                      type: "variable",
                      dataType: "uint8",
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      offset: 0x2a7,
                      type: "variable",
                      dataType: "uint8",
                      leadingZeros: 1,
                      max: 59,
                      test: true,
                    },
                  ],
                },
                {
                  name: "Points",
                  offset: 0x28e,
                  type: "variable",
                  dataType: "uint16",
                  max: 9999,
                  hidden: [false, true],
                  test: true,
                },
              ],
            },
            {
              name: "Points",
              type: "section",
              flex: true,
              hidden: [true, false],
              items: [
                {
                  name: "D-pts.",
                  offset: 0x28e,
                  type: "variable",
                  dataType: "uint16",
                  max: 9999,
                },
                {
                  name: "N-pts.",
                  offset: 0x290,
                  type: "variable",
                  dataType: "uint16",
                  max: 9999,
                },
                {
                  name: "V-pts.",
                  offset: 0x292,
                  type: "variable",
                  dataType: "uint16",
                  max: 9999,
                },
              ],
            },
            {
              name: "Net Rank",
              type: "section",
              flex: true,
              hidden: [true, false],
              items: [
                {
                  name: "Win",
                  offset: 0x2a8,
                  type: "variable",
                  dataType: "uint16",
                  max: 9999,
                },
                {
                  name: "Lose",
                  offset: 0x2aa,
                  type: "variable",
                  dataType: "uint16",
                  max: 9999,
                },
                {
                  name: "Draw",
                  offset: 0x2ad,
                  type: "variable",
                  dataType: "uint8",
                  max: 99,
                },
                {
                  name: "Rank",
                  offset: 0x2ac,
                  type: "variable",
                  dataType: "uint8",
                  resource: "netRanks",
                },
              ],
            },
          ],
        },
        {
          name: "Shop",
          flex: true,
          items: [
            {
              name: "Characters",
              type: "bitflags",
              flags: [
                { offset: 0x296, bit: 7, label: "01 Cable" },
                { offset: 0x296, bit: 6, label: "02 Marrow" },
                { offset: 0x294, bit: 6, label: "03 Cyclops" },
                { offset: 0x295, bit: 3, label: "04 Captain America" },
                { offset: 0x295, bit: 0, label: "05 Psylocke" },
                { offset: 0x295, bit: 2, label: "06 Rogue" },
                { offset: 0x295, bit: 7, label: "07 Doctor Doom" },
                { offset: 0x29b, bit: 1, label: "08 Wolverine" },
                { offset: 0x295, bit: 1, label: "09 Iceman" },
                { offset: 0x295, bit: 4, label: "10 Spider-Man" },
                { offset: 0x295, bit: 5, label: "11 Hulk" },
                { offset: 0x295, bit: 6, label: "12 Venom" },
                { offset: 0x296, bit: 1, label: "13 Jill" },
                { offset: 0x296, bit: 0, label: "14 T.Bonne" },
                { offset: 0x296, bit: 3, label: "15 Ruby Heart" },
                { offset: 0x296, bit: 4, label: "16 Sonson" },
                { offset: 0x296, bit: 5, label: "17 Amingo" },
                { offset: 0x296, bit: 2, label: "18 Hayato" },
                { offset: 0x298, bit: 2, label: "19 Sakura" },
                { offset: 0x294, bit: 5, label: "20 Strider Hiryu" },
                { offset: 0x294, bit: 2, label: "21 Guile" },
                { offset: 0x294, bit: 0, label: "22 Ryu" },
                { offset: 0x294, bit: 1, label: "23 Zangief" },
                { offset: 0x294, bit: 4, label: "24 Anakaris" },
                { offset: 0x299, bit: 7, label: "25 Silver Samurai" },
                { offset: 0x299, bit: 0, label: "26 Gambit" },
                { offset: 0x299, bit: 1, label: "27 Juggernaut" },
                { offset: 0x299, bit: 4, label: "28 Magneto" },
                { offset: 0x299, bit: 5, label: "29 Shuma-Gorath" },
                { offset: 0x299, bit: 2, label: "30 Storm" },
                { offset: 0x294, bit: 7, label: "31 Wolverine" },
                { offset: 0x29a, bit: 0, label: "32 Omega Red" },
                { offset: 0x297, bit: 7, label: "33 B.B.Hood" },
                { offset: 0x297, bit: 6, label: "34 Akuma" },
                { offset: 0x29a, bit: 7, label: "35 Jin" },
                { offset: 0x294, bit: 3, label: "36 Morrigan" },
                { offset: 0x297, bit: 4, label: "37 Megaman" },
                { offset: 0x297, bit: 5, label: "38 Roll" },
                { offset: 0x29b, bit: 0, label: "39 Captain Commando" },
                { offset: 0x297, bit: 3, label: "40 Chun-Li" },
                { offset: 0x299, bit: 3, label: "41 Sabretooth" },
                { offset: 0x29a, bit: 5, label: "42 Blackheart" },
                { offset: 0x29a, bit: 1, label: "43 Spiral" },
                { offset: 0x29a, bit: 2, label: "44 Colossus" },
                { offset: 0x299, bit: 6, label: "45 War Machine" },
                { offset: 0x29a, bit: 3, label: "46 Iron Man" },
                { offset: 0x29a, bit: 6, label: "47 Thanos" },
                { offset: 0x29a, bit: 4, label: "48 Sentinel" },
                { offset: 0x298, bit: 7, label: "49 Ken" },
                { offset: 0x298, bit: 1, label: "50 Charlie" },
                { offset: 0x298, bit: 5, label: "51 Dhalsim" },
                { offset: 0x298, bit: 6, label: "52 M.Bison" },
                { offset: 0x298, bit: 3, label: "53 Dan" },
                { offset: 0x298, bit: 4, label: "54 Cammy" },
                { offset: 0x298, bit: 0, label: "55 Felicia" },
                { offset: 0x29b, bit: 2, label: "56 Servbot" },
              ],
            },
            {
              name: "New Colors",
              type: "bitflags",
              flags: [
                { offset: 0x29e, bit: 7, label: "01 Cable" },
                { offset: 0x29e, bit: 6, label: "02 Marrow" },
                { offset: 0x29c, bit: 6, label: "03 Cyclops" },
                { offset: 0x29d, bit: 3, label: "04 Captain America" },
                { offset: 0x29d, bit: 0, label: "05 Psylocke" },
                { offset: 0x29d, bit: 2, label: "06 Rogue" },
                { offset: 0x29d, bit: 7, label: "07 Doctor Doom" },
                { offset: 0x2a3, bit: 1, label: "08 Wolverine" },
                { offset: 0x29d, bit: 1, label: "09 Iceman" },
                { offset: 0x29d, bit: 4, label: "10 Spider-Man" },
                { offset: 0x29d, bit: 5, label: "11 Hulk" },
                { offset: 0x29d, bit: 6, label: "12 Venom" },
                { offset: 0x29e, bit: 1, label: "13 Jill" },
                { offset: 0x29e, bit: 0, label: "14 T.Bonne" },
                { offset: 0x29e, bit: 3, label: "15 Ruby Heart" },
                { offset: 0x29e, bit: 4, label: "16 Sonson" },
                { offset: 0x29e, bit: 5, label: "17 Amingo" },
                { offset: 0x29e, bit: 2, label: "18 Hayato" },
                { offset: 0x2a0, bit: 2, label: "19 Sakura" },
                { offset: 0x29c, bit: 5, label: "20 Strider Hiryu" },
                { offset: 0x29c, bit: 2, label: "21 Guile" },
                { offset: 0x29c, bit: 0, label: "22 Ryu" },
                { offset: 0x29c, bit: 1, label: "23 Zangief" },
                { offset: 0x29c, bit: 4, label: "24 Anakaris" },
                { offset: 0x2a1, bit: 7, label: "25 Silver Samurai" },
                { offset: 0x2a1, bit: 0, label: "26 Gambit" },
                { offset: 0x2a1, bit: 1, label: "27 Juggernaut" },
                { offset: 0x2a1, bit: 4, label: "28 Magneto" },
                { offset: 0x2a1, bit: 5, label: "29 Shuma-Gorath" },
                { offset: 0x2a1, bit: 2, label: "30 Storm" },
                { offset: 0x29c, bit: 7, label: "31 Wolverine" },
                { offset: 0x2a2, bit: 0, label: "32 Omega Red" },
                { offset: 0x29f, bit: 7, label: "33 B.B.Hood" },
                { offset: 0x29f, bit: 6, label: "34 Akuma" },
                { offset: 0x2a2, bit: 7, label: "35 Jin" },
                { offset: 0x29c, bit: 3, label: "36 Morrigan" },
                { offset: 0x29f, bit: 4, label: "37 Megaman" },
                { offset: 0x29f, bit: 5, label: "38 Roll" },
                { offset: 0x2a3, bit: 0, label: "39 Captain Commando" },
                { offset: 0x29f, bit: 3, label: "40 Chun-Li" },
                { offset: 0x2a1, bit: 3, label: "41 Sabretooth" },
                { offset: 0x2a2, bit: 5, label: "42 Blackheart" },
                { offset: 0x2a2, bit: 1, label: "43 Spiral" },
                { offset: 0x2a2, bit: 2, label: "44 Colossus" },
                { offset: 0x2a1, bit: 6, label: "45 War Machine" },
                { offset: 0x2a2, bit: 3, label: "46 Iron Man" },
                { offset: 0x2a2, bit: 6, label: "47 Thanos" },
                { offset: 0x2a2, bit: 4, label: "48 Sentinel" },
                { offset: 0x2a0, bit: 7, label: "49 Ken" },
                { offset: 0x2a0, bit: 1, label: "50 Charlie" },
                { offset: 0x2a0, bit: 5, label: "51 Dhalsim" },
                { offset: 0x2a0, bit: 6, label: "52 M.Bison" },
                { offset: 0x2a0, bit: 3, label: "53 Dan" },
                { offset: 0x2a0, bit: 4, label: "54 Cammy" },
                { offset: 0x2a0, bit: 0, label: "55 Felicia" },
                { offset: 0x2a3, bit: 2, label: "56 Servbot" },
              ],
            },
            {
              name: "Stages",
              offset: 0x2a4,
              type: "variable",
              dataType: "uint8",
              max: 7,
            },
          ],
        },
        {
          name: "Score Attack Ranking",
          items: [
            {
              length: 0x18,
              type: "container",
              instanceType: "tabs",
              instances: 20,
              resource: "rankings",
              vertical: true,
              items: [
                {
                  type: "section",
                  noMargin: true,
                  flex: true,
                  items: [
                    {
                      name: "&nbsp;",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Name",
                          offset: 0x534,
                          length: 0x3,
                          type: "variable",
                          dataType: "string",
                          letterDataType: "uint8",
                          resource: "letters",
                          fallback: 0x2a,
                        },
                        {
                          name: "Wins",
                          offset: 0x53e,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                      ],
                    },
                    {
                      name: "Character 1",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Character",
                          offset: 0x538,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          name: "Assist",
                          offset: 0x53b,
                          type: "variable",
                          dataType: "uint8",
                          resource: "assists",
                        },
                      ],
                    },
                    {
                      name: "Character 2",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Character",
                          offset: 0x539,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          name: "Assist",
                          offset: 0x53c,
                          type: "variable",
                          dataType: "uint8",
                          resource: "assists",
                        },
                      ],
                    },
                    {
                      name: "Character 3",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Character",
                          offset: 0x53a,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          name: "Assist",
                          offset: 0x53d,
                          type: "variable",
                          dataType: "uint8",
                          resource: "assists",
                        },
                      ],
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Progression",
                      type: "section",
                      background: true,
                      items: [
                        {
                          name: "Completed",
                          offset: 0x53f,
                          type: "variable",
                          dataType: "boolean",
                        },
                      ],
                    },
                    {
                      id: "score",
                      name: "Score",
                      offset: 0x540,
                      type: "variable",
                      dataType: "uint8",
                      max: 99999999999,
                    },
                    {
                      name: "Time",
                      type: "group",
                      mode: "chrono",
                      items: [
                        {
                          offset: 0x548,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          offset: 0x549,
                          type: "variable",
                          dataType: "uint8",
                          leadingZeros: 1,
                          max: 59,
                        },
                        {
                          offset: 0x54a,
                          type: "variable",
                          dataType: "uint8",
                          leadingZeros: 1,
                          max: 99,
                        },
                      ],
                    },
                    {
                      name: "Score",
                      offset: 0x540,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x541,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x542,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x543,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x544,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x545,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x546,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x547,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
                {
                  name: "???",
                  offset: 0x537,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "???",
                  offset: 0x54b,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
              ],
            },
          ],
        },
        {
          name: "Arcade Mode Ranking",
          items: [
            {
              length: 0x18,
              type: "container",
              instanceType: "tabs",
              instances: 20,
              resource: "rankings",
              vertical: true,
              items: [
                {
                  type: "section",
                  noMargin: true,
                  flex: true,
                  items: [
                    {
                      name: "&nbsp;",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Name",
                          offset: 0x2b4,
                          length: 0x3,
                          type: "variable",
                          dataType: "string",
                          letterDataType: "uint8",
                          resource: "letters",
                          fallback: 0x2a,
                        },
                        {
                          name: "Wins",
                          offset: 0x2be,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                      ],
                    },
                    {
                      name: "Character 1",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Character",
                          offset: 0x2b8,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          name: "Assist",
                          offset: 0x2bb,
                          type: "variable",
                          dataType: "uint8",
                          resource: "assists",
                        },
                      ],
                    },
                    {
                      name: "Character 2",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Character",
                          offset: 0x2b9,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          name: "Assist",
                          offset: 0x2bc,
                          type: "variable",
                          dataType: "uint8",
                          resource: "assists",
                        },
                      ],
                    },
                    {
                      name: "Character 3",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Character",
                          offset: 0x2ba,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          name: "Assist",
                          offset: 0x2bd,
                          type: "variable",
                          dataType: "uint8",
                          resource: "assists",
                        },
                      ],
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Progression",
                      type: "section",
                      background: true,
                      items: [
                        {
                          name: "Completed",
                          offset: 0x2bf,
                          type: "variable",
                          dataType: "boolean",
                        },
                      ],
                    },
                    {
                      id: "score",
                      name: "Score",
                      offset: 0x2c0,
                      type: "variable",
                      dataType: "uint8",
                      max: 99999999999,
                    },
                    {
                      name: "Time",
                      type: "group",
                      mode: "chrono",
                      items: [
                        {
                          offset: 0x2c8,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          offset: 0x2c9,
                          type: "variable",
                          dataType: "uint8",
                          leadingZeros: 1,
                          max: 59,
                        },
                        {
                          offset: 0x2ca,
                          type: "variable",
                          dataType: "uint8",
                          leadingZeros: 1,
                          max: 99,
                        },
                      ],
                    },
                    {
                      name: "Score",
                      offset: 0x2c0,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x2c1,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x2c2,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x2c3,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x2c4,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x2c5,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x2c6,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Score",
                      offset: 0x2c7,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
                {
                  name: "???",
                  offset: 0x2b7,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "???",
                  offset: 0x2cb,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
              ],
            },
          ],
        },
        {
          name: "Options",
          flex: true,
          items: [
            {
              type: "tabs",
              vertical: true,
              items: [
                {
                  name: "Game Option",
                  flex: true,
                  items: [
                    {
                      name: "Difficulty",
                      offset: 0x970,
                      type: "variable",
                      dataType: "uint8",
                      operations: [{ "+": 1 }],
                      min: 1,
                      max: 8,
                    },
                    {
                      name: "Time",
                      offset: 0x971,
                      type: "variable",
                      dataType: "uint8",
                      resource: "times",
                    },
                    {
                      name: "Damage",
                      offset: 0x972,
                      type: "variable",
                      dataType: "uint8",
                      operations: [{ "+": 1 }],
                      min: 1,
                      max: 4,
                    },
                    {
                      name: "Speed",
                      offset: 0x973,
                      type: "variable",
                      dataType: "uint8",
                      resource: "speeds",
                    },
                  ],
                },
                {
                  name: "Display",
                  flex: true,
                  items: [
                    {
                      name: "Display Adjust X",
                      offset: 0x982,
                      type: "variable",
                      dataType: "uint16",
                      resource: "displayAdjusts",
                    },
                    {
                      name: "Display Adjust Y",
                      offset: 0x986,
                      type: "variable",
                      dataType: "uint16",
                      resource: "displayAdjusts",
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    assists: {
      0x0: "α",
      0x1: "β",
      0x2: "γ",
    },
    characters: {
      0x0: "Ryu",
      0x1: "Zangief",
      0x2: "Guile",
      0x3: "Morrigan",
      0x4: "Anakaris",
      0x5: "Strider Hiryu",
      0x6: "Cyclops",
      0x7: "Wolverine",
      0x8: "Psylocke",
      0x9: "Iceman",
      0xa: "Rogue",
      0xb: "Captain America",
      0xc: "Spider-Man",
      0xd: "Hulk",
      0xe: "Venom",
      0xf: "Doctor Doom",
      0x10: "T.Bonne",
      0x11: "Jill",
      0x12: "Hayato",
      0x13: "Ruby Heart",
      0x14: "Sonson",
      0x15: "Amingo",
      0x16: "Marrow",
      0x17: "Cable",
      0x1b: "Chun-Li",
      0x1c: "Megaman",
      0x1d: "Roll",
      0x1e: "Akuma",
      0x1f: "B.B.Hood",
      0x20: "Felicia",
      0x21: "Charlie",
      0x22: "Sakura",
      0x23: "Dan",
      0x24: "Cammy",
      0x25: "Dhalsim",
      0x26: "M.Bison",
      0x27: "Ken",
      0x28: "Gambit",
      0x29: "Juggernaut",
      0x2a: "Storm",
      0x2b: "Sabretooth",
      0x2c: "Magneto",
      0x2d: "Shuma-Gorath",
      0x2e: "War Machine",
      0x2f: "Silver Samurai",
      0x30: "Omega Red",
      0x31: "Spiral",
      0x32: "Colossus",
      0x33: "Iron Man",
      0x34: "Sentinel",
      0x35: "Blackheart",
      0x36: "Thanos",
      0x37: "Jin",
      0x38: "Captain Commando",
      0x39: "Wolverine",
      0x3a: "Servbot",
    },
    displayAdjusts: {
      0x0: "0",
      0x3f80: "+1",
      0x4000: "+2",
      0x4040: "+3",
      0x4080: "+4",
      0x40a0: "+5",
      0x40c0: "+6",
      0x40e0: "+7",
      0x4100: "+8",
      0x4110: "+9",
      0x4120: "+10",
      0xbf80: "-1",
      0xc000: "-2",
      0xc040: "-3",
      0xc080: "-4",
      0xc0a0: "-5",
      0xc0c0: "-6",
      0xc0e0: "-7",
      0xc100: "-8",
      0xc110: "-9",
      0xc120: "-10",
    },
    letters: {
      0x0: "A",
      0x1: "B",
      0x2: "C",
      0x3: "D",
      0x4: "E",
      0x5: "F",
      0x6: "G",
      0x7: "H",
      0x8: "I",
      0x9: "J",
      0xa: "K",
      0xb: "L",
      0xc: "M",
      0xd: "N",
      0xe: "O",
      0xf: "P",
      0x10: "Q",
      0x11: "R",
      0x12: "S",
      0x13: "T",
      0x14: "U",
      0x15: "V",
      0x16: "W",
      0x17: "X",
      0x18: "Y",
      0x19: "Z",
      0x1a: ".",
      0x1b: ",",
      0x1c: "0",
      0x1d: "1",
      0x1e: "2",
      0x1f: "3",
      0x20: "4",
      0x21: "5",
      0x22: "6",
      0x23: "7",
      0x24: "8",
      0x25: "9",
      0x26: "!",
      0x27: "?",
      0x28: "♥",
      0x29: "&",
      0x2a: " ",
    },
    netRanks: {
      0x0: "G",
      0x1: "F",
      0x2: "E",
      0x3: "D",
      0x4: "C",
      0x5: "B",
      0x6: "A",
      0x7: "S",
    },
    rankings: {
      0x0: "1st Place",
      0x1: "2nd Place",
      0x2: "3rd Place",
      0x3: "4th Place",
      0x4: "5th Place",
      0x5: "6th Place",
      0x6: "7th Place",
      0x7: "8th Place",
      0x8: "9th Place",
      0x9: "10th Place",
      0xa: "11th Place",
      0xb: "12th Place",
      0xc: "13th Place",
      0xd: "14th Place",
      0xe: "15th Place",
      0xf: "16th Place",
      0x10: "17th Place",
      0x11: "18th Place",
      0x12: "19th Place",
      0x13: "20th Place",
    },
    speeds: {
      0x0: "Free",
      0x1: "Turbo",
      0x2: "Turbo2",
    },
    times: {
      0x0: "30",
      0x1: "60",
      0x2: "99",
      0x3: "∞",
    },
  },
  resourcesGroups: {
    characters: [
      {
        name: "Capcom",
        options: [
          0x1e, 0x15, 0x4, 0x1f, 0x24, 0x38, 0x21, 0x1b, 0x23, 0x25, 0x20, 0x2,
          0x12, 0x11, 0x37, 0x27, 0x26, 0x1c, 0x3, 0x1d, 0x13, 0x0, 0x22, 0x3a,
          0x14, 0x5, 0x10, 0x1,
        ],
      },
      {
        name: "Marvel",
        options: [
          0x35, 0x17, 0xb, 0x32, 0x6, 0xf, 0x28, 0xd, 0x9, 0x33, 0x29, 0x2c,
          0x16, 0x30, 0x8, 0xa, 0x2b, 0x34, 0x2d, 0x2f, 0xc, 0x31, 0x2a, 0x36,
          0xe, 0x2e, 0x39, 0x7,
        ],
      },
    ],
  },
  resourcesOrder: {
    netRanks: [0x7, 0x6, 0x5, 0x4, 0x3, 0x2, 0x1, 0x0],
    displayAdjusts: [
      0xc120, 0xc110, 0xc100, 0xc0e0, 0xc0c0, 0xc0a0, 0xc080, 0xc040, 0xc000,
      0xbf80, 0x0, 0x3f80, 0x4000, 0x4040, 0x4080, 0x40a0, 0x40c0, 0x40e0,
      0x4100, 0x4110, 0x4120,
    ],
  },
};

export default template;
