import type { GameJson } from "$lib/types";

import {
  items,
  itemsGroups,
  itemsOrder,
  keyItems,
  keyItemsOrder,
  locations,
  locationsGroups,
  locationsOrder,
} from "./utils/resource";

const template: GameJson = {
  validator: {
    regions: {
      europe: {
        $or: [...Array(0x4).keys()].map((index) => ({
          [index * 0x4000]: [
            0x4d, 0x61, 0x72, 0x69, 0x6f, 0x20, 0x53, 0x74, 0x6f, 0x72, 0x79,
            0x20, 0x30, 0x30, 0x36,
          ], // "Mario Story 006"
        })),
      },
      usa: {
        $or: [...Array(0x4).keys()].map((index) => ({
          [index * 0x4000]: [
            0x4d, 0x61, 0x72, 0x69, 0x6f, 0x20, 0x53, 0x74, 0x6f, 0x72, 0x79,
            0x20, 0x30, 0x30, 0x36,
          ], // "Mario Story 006"
        })),
      },
      japan: {
        $or: [...Array(0x4).keys()].map((index) => ({
          [index * 0x4000]: [
            0x4d, 0x61, 0x72, 0x69, 0x6f, 0x20, 0x53, 0x74, 0x6f, 0x72, 0x79,
            0x20, 0x30, 0x30, 0x36,
          ], // "Mario Story 006"
        })),
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    hint: "If you're having trouble loading a save file from an <b>Everdrive</b> cartridge, please see the FAQ.",
    error: "Not a valid save file.",
  },
  items: [
    {
      id: "slots",
      length: 0x4000,
      type: "container",
      instanceType: "tabs",
      instances: 4,
      enumeration: "Slot %d",
      items: [
        {
          type: "section",
          flex: true,
          hidden: true,
          items: [
            {
              id: "checksum1",
              name: "Checksum",
              offset: 0x30,
              type: "checksum",
              dataType: "uint32",
              bigEndian: true,
              control: {
                offsetStart: 0x0,
                offsetEnd: 0x1380,
              },
            },
            {
              id: "checksum2",
              name: "Checksum",
              offset: 0x34,
              type: "checksum",
              dataType: "uint32",
              bigEndian: true,
              control: {
                offsetStart: 0x0,
                offsetEnd: 0x1380,
              },
            },
          ],
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Filename",
                      offset: 0x12f3,
                      length: 0x8,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      fallback: 0xf7,
                      resource: "letters",
                      test: true,
                    },
                    {
                      name: "Save Count",
                      offset: 0x3c,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Playtime",
                      type: "group",
                      mode: "time",
                      items: [
                        {
                          id: "savePreview-4080",
                          offset: 0x2fc,
                          type: "variable",
                          dataType: "uint32",
                          bigEndian: true,
                          operations: [
                            { "/": 60 },
                            {
                              convert: {
                                from: "seconds",
                                to: "hours",
                              },
                            },
                          ],
                          max: 99,
                        },
                        {
                          id: "savePreview-4080",
                          offset: 0x2fc,
                          type: "variable",
                          dataType: "uint32",
                          bigEndian: true,
                          operations: [
                            { "/": 60 },
                            {
                              convert: {
                                from: "seconds",
                                to: "minutes",
                              },
                            },
                          ],
                          leadingZeros: 1,
                          max: 59,
                        },
                        {
                          id: "savePreview-4080",
                          offset: 0x2fc,
                          type: "variable",
                          dataType: "uint32",
                          bigEndian: true,
                          operations: [
                            { "/": 60 },
                            {
                              convert: {
                                from: "seconds",
                                to: "seconds",
                              },
                            },
                          ],
                          leadingZeros: 1,
                          max: 59,
                        },
                      ],
                    },
                    {
                      id: "location",
                      name: "Location",
                      offset: 0x468,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      resource: "locations",
                      size: "lg",
                      autocomplete: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Partner",
                      offset: 0x52,
                      type: "variable",
                      dataType: "uint8",
                      resource: "partners",
                    },
                    {
                      name: "Coins",
                      offset: 0x4c,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 999,
                    },
                    {
                      name: "Star Pieces",
                      offset: 0x4f,
                      type: "variable",
                      dataType: "uint8",
                      max: 160,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      name: "Playtime (Save Preview)",
                      offset: 0x12ec,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Spirits (Save Preview)",
                      offset: 0x12f0,
                      type: "variable",
                      dataType: "int8",
                      hidden: true,
                    },
                    {
                      name: "Level (Save Preview)",
                      offset: 0x12f2,
                      type: "variable",
                      dataType: "int8",
                      hidden: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      name: "Position X",
                      offset: 0x12e6,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Position Y",
                      offset: 0x12e8,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Position Z",
                      offset: 0x12ea,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      hidden: true,
                    },
                  ],
                },
                {
                  id: "spirits",
                  name: "Spirits",
                  type: "bitflags",
                  flags: [
                    { offset: 0x2ce, bit: 0, label: "Eldstar" },
                    { offset: 0x2ce, bit: 0, label: "Mamar" },
                    { offset: 0x2ce, bit: 0, label: "Skolar" },
                    { offset: 0x2ce, bit: 0, label: "Muskular" },
                    { offset: 0x2ce, bit: 0, label: "Misstar" },
                    { offset: 0x2ce, bit: 0, label: "Klevar" },
                    { offset: 0x2ce, bit: 0, label: "Kalmar" },
                  ],
                },
              ],
            },
            {
              name: "Stats",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "savePreview-4777",
                      name: "Level",
                      offset: 0x49,
                      type: "variable",
                      dataType: "uint8",
                      min: 1,
                      max: 27,
                    },
                    {
                      name: "Star Points",
                      offset: 0x50,
                      type: "variable",
                      dataType: "uint8",
                      max: 99,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "HP",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          offset: 0x42,
                          type: "variable",
                          dataType: "uint8",
                          max: 75,
                        },
                        {
                          id: "baseStats",
                          offset: 0x43,
                          type: "variable",
                          dataType: "uint8",
                          max: 75,
                        },
                      ],
                    },
                    {
                      name: "FP",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          offset: 0x45,
                          type: "variable",
                          dataType: "uint8",
                          max: 75,
                        },
                        {
                          id: "baseStats",
                          offset: 0x46,
                          type: "variable",
                          dataType: "uint8",
                          max: 75,
                        },
                      ],
                    },
                    {
                      name: "BP",
                      offset: 0x48,
                      type: "variable",
                      dataType: "uint8",
                      max: 30,
                    },
                    {
                      name: "Star Energy",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          offset: 0x2d0,
                          type: "variable",
                          dataType: "uint8",
                          max: 7,
                        },
                        {
                          id: "savePreview-4130",
                          offset: 0x2ce,
                          type: "variable",
                          dataType: "uint8",
                          max: 7,
                        },
                      ],
                    },
                    {
                      name: "Base HP",
                      offset: 0x44,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Base Max FP",
                      offset: 0x47,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Boots",
                      offset: 0x40,
                      type: "variable",
                      dataType: "uint8",
                      resource: "boots",
                    },
                    {
                      name: "Hammer",
                      offset: 0x41,
                      type: "variable",
                      dataType: "uint8",
                      resource: "hammers",
                    },
                  ],
                },
              ],
            },
            {
              name: "Badges",
              flex: true,
              items: [
                {
                  id: "badges-obtained",
                  name: "Obtained",
                  type: "bitflags",
                  flags: [{ offset: 0xf4, bit: 0, label: "Dummy" }] },
                {
                  id: "badges-equipped",
                  name: "Equipped",
                  type: "bitflags",
                  flags: [{ offset: 0x248, bit: 0, label: "Dummy" }] },
              ],
            },
            {
              name: "Items",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Key Items",
                      flex: true,
                      items: [...Array(32).keys()].map((index) => ({
                        name: `Item ${index + 1}`,
                        offset: 0xb4 + index * 0x2,
                        type: "variable",
                        dataType: "uint16",
                        bigEndian: true,
                        resource: "keyItems",
                        autocomplete: true,
                      })),
                    },
                    {
                      name: "Items",
                      flex: true,
                      items: [...Array(10).keys()].map((index) => ({
                        name: `Item ${index + 1}`,
                        offset: 0x1f4 + index * 0x2,
                        type: "variable",
                        dataType: "uint16",
                        bigEndian: true,
                        resource: "items",
                        autocomplete: true,
                      })),
                    },
                    {
                      name: "Stored Items",
                      flex: true,
                      items: [...Array(32).keys()].map((index) => ({
                        name: `Item ${index + 1}`,
                        offset: 0x208 + index * 0x2,
                        type: "variable",
                        dataType: "uint16",
                        bigEndian: true,
                        resource: "items",
                        autocomplete: true,
                      })),
                    },
                  ],
                },
              ],
            },
            {
              name: "Party",
              items: [
                {
                  id: "party",
                  length: 0x8,
                  type: "container",
                  instanceType: "section",
                  instances: 8,
                  resource: "characters",
                  flex: true,
                  items: [
                    {
                      name: "Status",
                      offset: 0x5c,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterStatus",
                    },
                    {
                      name: "Rank",
                      offset: 0x5d,
                      type: "variable",
                      dataType: "uint8",
                      resource: "ranks",
                    },
                  ],
                },
              ],
            },
            {
              name: "Events",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Koopa Koot's Favors",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          hidden: true,
                          items: [
                            {
                              name: "Current Favors",
                              offset: 0x120c,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Completed Favors",
                              offset: 0x120b,
                              type: "variable",
                              dataType: "uint8",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Unlocked",
                              type: "bitflags",
                              flags: [
                                { offset: 0x1086, bit: 3, label: "Koopa Legends book" },
                                { offset: 0x1086, bit: 6, label: "Sleepy Sheep" },
                                { offset: 0x1085, bit: 1, label: "Tape" },
                                { offset: 0x1085, bit: 4, label: "Koopa Tea" },
                                { offset: 0x1085, bit: 7, label: "Autograph (Luigi)" },
                                { offset: 0x1084, bit: 2, label: "Empty Wallet" },
                                { offset: 0x1084, bit: 5, label: "Tasty Tonic" },
                                { offset: 0x108b, bit: 0, label: "Autograph (Merluvlee)" },
                                { offset: 0x108b, bit: 3, label: "Toad Town News" },
                                { offset: 0x108b, bit: 6, label: "Life Shroom" },
                                { offset: 0x108a, bit: 1, label: "Nutty Cake" },
                                { offset: 0x108a, bit: 4, label: "Bob-ombs" },
                                { offset: 0x108a, bit: 7, label: "Old Photo" },
                                { offset: 0x1089, bit: 2, label: "Koopasta" },
                                { offset: 0x1089, bit: 5, label: "Glasses" },
                                { offset: 0x1088, bit: 0, label: "Lime" },
                                { offset: 0x1088, bit: 3, label: "Kooky Cookie" },
                                { offset: 0x1088, bit: 6, label: "Package" },
                                { offset: 0x108f, bit: 1, label: "Coconuts" },
                                { offset: 0x108f, bit: 4, label: "Red Jar" },
                              ],
                            },
                            {
                              id: "koopaKoots",
                              name: "Completed",
                              type: "bitflags",
                              flags: [
                                { offset: 0x1086, bit: 5, label: "Koopa Legends book" },
                                { offset: 0x1085, bit: 0, label: "Sleepy Sheep" },
                                { offset: 0x1085, bit: 3, label: "Tape" },
                                { offset: 0x1085, bit: 6, label: "Koopa Tea" },
                                { offset: 0x1084, bit: 1, label: "Autograph (Luigi)" },
                                { offset: 0x1084, bit: 4, label: "Empty Wallet" },
                                { offset: 0x1084, bit: 7, label: "Tasty Tonic" },
                                { offset: 0x108b, bit: 2, label: "Autograph (Merluvlee)" },
                                { offset: 0x108b, bit: 5, label: "Toad Town News" },
                                { offset: 0x108a, bit: 0, label: "Life Shroom" },
                                { offset: 0x108a, bit: 3, label: "Nutty Cake" },
                                { offset: 0x108a, bit: 6, label: "Bob-ombs" },
                                { offset: 0x1089, bit: 1, label: "Old Photo" },
                                { offset: 0x1089, bit: 4, label: "Koopasta" },
                                { offset: 0x1089, bit: 7, label: "Glasses" },
                                { offset: 0x1088, bit: 2, label: "Lime" },
                                { offset: 0x1088, bit: 5, label: "Kooky Cookie" },
                                { offset: 0x108f, bit: 0, label: "Package" },
                                { offset: 0x108f, bit: 3, label: "Coconuts" },
                                { offset: 0x108f, bit: 6, label: "Red Jar" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Li'l-Oinks",
                      items: [
                        {
                          name: "Li'l-Oinks",
                          offset: 0x10cd,
                          type: "variable",
                          dataType: "uint8",
                          max: 10,
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [...Array(10).keys()].map((index) => ({
                            id: `liLShoink-${index}`,
                            name: `Li'l Shoink ${index + 1}`,
                            offset: 0x10ce + index,
                            type: "variable",
                            dataType: "uint8",
                            resource: "liLShoinks",
                          })),
                        },
                      ],
                    },
                    {
                      name: "Star Pieces",
                      flex: true,
                      items: [
                        {
                          name: "Collected",
                          type: "section",
                          items: [
                            {
                              type: "bitflags",
                              flags: [
                                { offset: 0xfba, bit: 2, label: "<b>Goomba Village:</b> On a ledge" },
                                { offset: 0xfb9, bit: 6, label: "<b>Goomba Village:</b> Under a secret panel at the west of the village" },
                                { offset: 0xfb8, bit: 0, label: "<b>Goomba Village:</b> Under a secret panel near a heart block", separator: true },
                                { offset: 0xfb9, bit: 2, label: "<b>Goomba Road:</b> In a tree near the castle" },
                                { offset: 0xfb8, bit: 2, label: "<b>Goomba Road:</b> Under a secret panel near the castle", separator: true },
                                { offset: 0xfd7, bit: 7, label: "<b>Toad Town:</b> Under a secret panel near Shroom Grocery" },
                                { offset: 0xfd6, bit: 1, label: "<b>Toad Town:</b> Under a secret panel near Forever Forest" },
                                { offset: 0xfd6, bit: 2, label: "<b>Toad Town:</b> Under a secret panel near the train station" },
                                { offset: 0xfd6, bit: 4, label: "<b>Toad Town:</b> Under a secret panel near Club 64" },
                                { offset: 0xfd6, bit: 5, label: "<b>Toad Town:</b> By crossing the pond" },
                                { offset: 0xfd6, bit: 6, label: "<b>Toad Town:</b> In a tree near Merlon's house" },
                                { offset: 0xfcd, bit: 4, label: "<b>Toad Town:</b> By returning the Dictionary to Russ T." },
                                { offset: 0xfd2, bit: 2, label: "<b>Toad Town:</b> By returning the Mailbag to the post office", separator: true },
                                { offset: 0xfe1, bit: 4, label: "<b>Toad Town Tunnels:</b> In a moving platforms room", separator: true },
                                { offset: 0xff0, bit: 2, label: "<b>Shooting Star Summit:</b> Under a secret panel near a bridge" },
                                { offset: 0xff0, bit: 3, label: "<b>Shooting Star Summit:</b> Under a secret panel near the stairs" },
                                { offset: 0xff0, bit: 4, label: "<b>Shooting Star Summit:</b> Under a secret panel near Meluvlee's house" },
                                { offset: 0xff7, bit: 0, label: "<b>Shooting Star Summit:</b> Near the stairs", separator: true },
                                { offset: 0xffb, bit: 3, label: "<b>Koopa Village:</b> On a floating brick" },
                                { offset: 0xff8, bit: 6, label: "<b>Koopa Village:</b> Under a secret panel near Koopa's Shop", separator: true },
                                { offset: 0xffb, bit: 4, label: "<b>Pleasant Path:</b> On a small island" },
                                { offset: 0xff9, bit: 1, label: "<b>Pleasant Path:</b> In a tree near the fortress" },
                                { offset: 0xfff, bit: 0, label: "<b>Pleasant Path:</b> Under a secret panel near a wooden bridge" },
                                { offset: 0xfff, bit: 1, label: "<b>Pleasant Path:</b> Under a secret panel near a wooden bridge", separator: true },
                                { offset: 0x1006, bit: 7, label: "<b>Mt. Rugged:</b> On a wooden plank" },
                                { offset: 0x1005, bit: 0, label: "<b>Mt. Rugged:</b> On a ledge" },
                                { offset: 0x100a, bit: 5, label: "<b>Mt. Rugged:</b> Under a secret panel near a slide", separator: true },
                                { offset: 0x1010, bit: 4, label: "<b>Dry Dry Desert:</b> Under a secret panel in front of a statue" },
                                { offset: 0x1011, bit: 2, label: "<b>Dry Dry Desert:</b> By returning the Artifact to Kolorado", separator: true },
                                { offset: 0x100d, bit: 4, label: "<b>Dry Dry Outpost:</b> Under a secret panel on a rooftop", separator: true },
                                { offset: 0x101d, bit: 5, label: "<b>Dry Dry Ruins:</b> Inside a sand room", separator: true },
                                { offset: 0x102b, bit: 1, label: "<b>Boo's Mansion:</b> Under a secret panel near the couch" },
                                { offset: 0x102b, bit: 4, label: "<b>Boo's Mansion:</b> Under a secret panel near the clock" },
                                { offset: 0x102a, bit: 4, label: "<b>Boo's Mansion:</b> Under a secret panel in the room above Boo's Shop" },
                                { offset: 0x1029, bit: 0, label: "<b>Boo's Mansion:</b> Inside a crate" },
                                { offset: 0x1029, bit: 4, label: "<b>Boo's Mansion:</b> Under a secret panel below a chandelier", separator: true },
                                { offset: 0x1027, bit: 5, label: "<b>Gusty Gulch:</b> Under a secret panel at the entrance" },
                                { offset: 0x102c, bit: 3, label: "<b>Gusty Gulch:</b> Behind some rocks", separator: true },
                                { offset: 0x1031, bit: 2, label: "<b>Tubba Blubba's Castle:</b> On a dining table" },
                                { offset: 0x1030, bit: 2, label: "<b>Tubba Blubba's Castle:</b> On a desk", separator: true },
                                { offset: 0x103e, bit: 4, label: "<b>Shy Guy's Toy Box:</b> At the top of a dollhouse" },
                                { offset: 0x103e, bit: 5, label: "<b>Shy Guy's Toy Box:</b> Behind a pillar" },
                                { offset: 0x1041, bit: 6, label: "<b>Shy Guy's Toy Box:</b> in the colored stairs room" },
                                { offset: 0x1047, bit: 6, label: "<b>Shy Guy's Toy Box:</b> Under a secret panel at the Blue Station" },
                                { offset: 0x1047, bit: 7, label: "<b>Shy Guy's Toy Box:</b> Under a secret panel at the Pink Station" },
                                { offset: 0x1046, bit: 0, label: "<b>Shy Guy's Toy Box:</b> Under a secret panel at the Green Station" },
                                { offset: 0x1046, bit: 1, label: "<b>Shy Guy's Toy Box:</b> Under a secret panel at the Red Station", separator: true },
                                { offset: 0x104d, bit: 5, label: "<b>Yoshi's Village:</b> Under a secret panel in front of a statue", separator: true },
                                { offset: 0x104a, bit: 5, label: "<b>Jade Jungle:</b> On a island" },
                                { offset: 0x104f, bit: 4, label: "<b>Jade Jungle:</b> In a palm tree on the beach" },
                                { offset: 0x104d, bit: 6, label: "<b>Jade Jungle:</b> Under a secret panel in the room before the giant tree" },
                                { offset: 0x1053, bit: 2, label: "<b>Jade Jungle:</b> Underwater", separator: true },
                                { offset: 0x1054, bit: 2, label: "<b>Mt. Lavalava:</b> Under a secret panel near a Super Block" },
                                { offset: 0x1054, bit: 3, label: "<b>Mt. Lavalava:</b> Under a secret panel near a heart block", separator: true },
                                { offset: 0x105f, bit: 5, label: "<b>Flower Fields:</b> Hidden on a flower patch" },
                                { offset: 0x105e, bit: 3, label: "<b>Flower Fields:</b> At the end of a path" },
                                { offset: 0x105e, bit: 4, label: "<b>Flower Fields:</b> Hidden above an arch" },
                                { offset: 0x105c, bit: 4, label: "<b>Flower Fields:</b> Under a secret panel next to Petunia" },
                                { offset: 0x105c, bit: 6, label: "<b>Flower Fields:</b> Under a secret panel next to the pond" },
                                { offset: 0x105c, bit: 7, label: "<b>Flower Fields:</b> Under a secret panel near the Yellow Berry tree", separator: true },
                                { offset: 0x1060, bit: 4, label: "<b>Shiver City:</b> Under a secret panel near the Mayor's house", separator: true },
                                { offset: 0x1067, bit: 5, label: "<b>Shiver Snowfield:</b> Under a secret panel near Shiver Mountain", separator: true },
                                { offset: 0x1064, bit: 0, label: "<b>Shiver Mountain:</b> Below a save block", separator: true },
                                { offset: 0x106f, bit: 2, label: "<b>Crystal Palace:</b> Inside a cave" },
                                { offset: 0x106f, bit: 6, label: "<b>Crystal Palace:</b> Under a secret panel near the big statue" },
                                { offset: 0x106e, bit: 0, label: "<b>Crystal Palace:</b> Under a secret panel near the small statue" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Related to Events (read-only)",
                          type: "section",
                          items: [
                            {
                              id: "relatedStarPieces",
                              type: "bitflags",
                              flags: [
                                { offset: 0xfb0, bit: 6, label: "<b>Goomba Village:</b> Dolly found", separator: true },
                                { offset: 0x10e8, bit: 1, label: "<b>Rip Cheato:</b> 1st item bought" },
                                { offset: 0x10e8, bit: 5, label: "<b>Rip Cheato:</b> 5th item bought" },
                                { offset: 0x10e8, bit: 10, label: "<b>Rip Cheato:</b> 10th item bought", separator: true },
                                { offset: 0x120b, bit: 4, label: "<b>Koopa Koot:</b> 4 favors completed" },
                                { offset: 0x120b, bit: 8, label: "<b>Koopa Koot:</b> 8 favors completed" },
                                { offset: 0x120b, bit: 12, label: "<b>Koopa Koot:</b> 12 favors completed" },
                                { offset: 0x120b, bit: 16, label: "<b>Koopa Koot:</b> 16 favors completed" },
                                { offset: 0x120b, bit: 20, label: "<b>Koopa Koot:</b> 20 favors completed", separator: true },
                                { offset: 0x100b, bit: 1, label: "<b>Letter:</b> Letter to Merlon found" },
                                { offset: 0x100b, bit: 2, label: "<b>Letter:</b> Letter to Kolorado found" },
                                { offset: 0x100d, bit: 5, label: "<b>Letter:</b> Letter to Nomadimouse found" },
                                { offset: 0x101b, bit: 0, label: "<b>Letter:</b> Letter to Goompa found" },
                                { offset: 0x101b, bit: 1, label: "<b>Letter:</b> Letter to Mort T. found" },
                                { offset: 0x102e, bit: 6, label: "<b>Letter:</b> Letter to Fice T. found" },
                                { offset: 0x104b, bit: 6, label: "<b>Letter:</b> Letter to Igor found" },
                                { offset: 0x104a, bit: 3, label: "<b>Letter:</b> Letter to Russ T. found" },
                                { offset: 0x105e, bit: 5, label: "<b>Letter:</b> Letter to Minh T. found" },
                                { offset: 0x1067, bit: 6, label: "<b>Letter:</b> Letter to Mayor Penguin found" },
                                { offset: 0x1066, bit: 1, label: "<b>Letter:</b> Letter to Merlow found", separator: true },
                                ...[...Array(64).keys()].map((index) => ({
                                  offset: 0x1210,
                                  bit: index + 1,
                                  label: `<b>Chuck Quizmo's Quizzes:</b> Quizz ${index + 1} completed`,
                                })),
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Super Blocks",
                      items: [
                        {
                          type: "bitflags",
                          flags: [
                            { offset: 0xfe5, bit: 1, label: "<b>Toad Town Tunnels:</b> In a moving platforms room" },
                            { offset: 0xfe5, bit: 2, label: "<b>Toad Town Tunnels:</b> Near Boo's Mansion warp room" },
                            { offset: 0xfe5, bit: 3, label: "<b>Toad Town Tunnels:</b> Near metal blocks" },
                            { offset: 0xfe5, bit: 4, label: "<b>Toad Town Tunnels:</b> In the Shiver City warp room" },
                            { offset: 0xfe5, bit: 5, label: "<b>Toad Town Tunnels:</b> From the entrance of Toad Town" },
                            { offset: 0x1009, bit: 1, label: "<b>Mt. Rugged:</b> Near a stone block" },
                            { offset: 0x1014, bit: 5, label: "<b>Dry Dry Desert:</b> In the oasis area" },
                            { offset: 0x1023, bit: 7, label: "<b>Dry Dry Ruins:</b> Near a breakable wall" },
                            { offset: 0x1031, bit: 6, label: "<b>Tubba Blubba's Castle:</b> In the stairs room" },
                            { offset: 0x1046, bit: 2, label: "<b>Shy Guy's Toy Box:</b> Near a flower platform" },
                            { offset: 0x104c, bit: 6, label: "<b>Jade Jungle:</b> In the bridges area" },
                            { offset: 0x1055, bit: 0, label: "<b>Mt. Lavalava:</b> In the fireballs room" },
                            { offset: 0x1055, bit: 1, label: "<b>Mt. Lavalava:</b> On an elevated ledge" },
                            { offset: 0x105c, bit: 2, label: "<b>Flower Fields:</b> In the Crazee Dayzees area" },
                            { offset: 0x105c, bit: 3, label: "<b>Flower Fields:</b> In the puzzle area" },
                            { offset: 0x1065, bit: 1, label: "<b>Shiver Mountain:</b> At the top of some stairs" },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Tayce T.'s Recipes",
                      flex: true,
                      items: [
                        {
                          type: "bitflags",
                          flags: [
                            { offset: 0xfd5, bit: 7, label: "Apple Pie" },
                            { offset: 0xfdb, bit: 6, label: "Big Cookie" },
                            { offset: 0xfdb, bit: 1, label: "Bland Meal" },
                            { offset: 0xfd8, bit: 6, label: "Boiled Egg" },
                            { offset: 0xfdb, bit: 7, label: "Cake" },
                            { offset: 0xfd9, bit: 5, label: "Coco Pop" },
                            { offset: 0xfdb, bit: 3, label: "Deluxe Feast" },
                            { offset: 0xfdf, bit: 2, label: "Dizzy Dial" },
                            { offset: 0xfda, bit: 6, label: "Egg Missile" },
                            { offset: 0xfd9, bit: 2, label: "Electro Pop" },
                            { offset: 0xfde, bit: 1, label: "Fire Flower" },
                            { offset: 0xfd9, bit: 3, label: "Fire Pop" },
                            { offset: 0xfda, bit: 7, label: "Fried Egg" },
                            { offset: 0xfd4, bit: 4, label: "Fried Shroom" },
                            { offset: 0xfd8, bit: 2, label: "Frozen Fries" },
                            { offset: 0xfdb, bit: 5, label: "Healty Juice" },
                            { offset: 0xfd9, bit: 1, label: "Honey Candy" },
                            { offset: 0xfd9, bit: 0, label: "Honey Shroom" },
                            { offset: 0xfda, bit: 2, label: "Honey Super" },
                            { offset: 0xfd4, bit: 0, label: "Honey Ultra" },
                            { offset: 0xfd4, bit: 7, label: "Hot Shroom" },
                            { offset: 0xfd9, bit: 7, label: "Jelly Pop" },
                            { offset: 0xfdf, bit: 0, label: "Jelly Shroom" },
                            { offset: 0xfda, bit: 4, label: "Jelly Super" },
                            { offset: 0xfd4, bit: 2, label: "Jelly Ultra" },
                          ],
                        },
                        {
                          type: "bitflags",
                          flags: [
                            { offset: 0xfd8, bit: 1, label: "Kooky Cookie" },
                            { offset: 0xfda, bit: 1, label: "Koopa Tea" },
                            { offset: 0xfd4, bit: 3, label: "Koopasta" },
                            { offset: 0xfd9, bit: 6, label: "Lemon Candy" },
                            { offset: 0xfdf, bit: 5, label: "Life Shroom" },
                            { offset: 0xfd9, bit: 4, label: "Lime Candy" },
                            { offset: 0xfd8, bit: 5, label: "Maple Shroom" },
                            { offset: 0xfda, bit: 3, label: "Maple Super" },
                            { offset: 0xfd4, bit: 1, label: "Maple Ultra" },
                            { offset: 0xfd8, bit: 4, label: "Nutty Cake" },
                            { offset: 0xfd8, bit: 3, label: "Potato Salad" },
                            { offset: 0xfd4, bit: 5, label: "Shroom Cake" },
                            { offset: 0xfd4, bit: 6, label: "Shroom Steak" },
                            { offset: 0xfdf, bit: 7, label: "Sleepy Sheep" },
                            { offset: 0xfda, bit: 5, label: "Spaghetti" },
                            { offset: 0xfdb, bit: 4, label: "Special Shake" },
                            { offset: 0xfd5, bit: 6, label: "Spicy Soup" },
                            { offset: 0xfd8, bit: 0, label: "Strange Cake" },
                            { offset: 0xfdf, bit: 3, label: "Super Soda" },
                            { offset: 0xfdb, bit: 0, label: "Sweet Shroom" },
                            { offset: 0xfdf, bit: 1, label: "Tasty Tonic" },
                            { offset: 0xfde, bit: 0, label: "Thunder Rage" },
                            { offset: 0xfdf, bit: 6, label: "Volt Shroom" },
                            { offset: 0xfd8, bit: 7, label: "Yoshi Cookie" },
                            { offset: 0xfdb, bit: 2, label: "Yummy Meal" },
                          ],
                        },
                        {
                          type: "bitflags",
                          flags: [
                            { offset: 0xfdf, bit: 4, label: "???", hidden: true },
                            { offset: 0xfda, bit: 0, label: "Mistake" },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Miscellaneous",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Coins Earned",
                              offset: 0x2f4,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999,
                            },
                            {
                              id: "totalBadges",
                              name: "Badges Collected",
                              offset: 0xf4,
                              type: "variable",
                              dataType: "uint8",
                              disabled: true,
                            },
                            {
                              name: "Star Pieces Collected",
                              offset: 0x36c,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              max: 160,
                            },
                            {
                              id: "totalRecipes",
                              name: "Tayce T.'s Recipes",
                              offset: 0xfd4,
                              type: "variable",
                              dataType: "uint8",
                              disabled: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Chuck Quizmo's Quizzes",
                              type: "group",
                              mode: "fraction",
                              items: [
                                {
                                  id: "quizzes",
                                  offset: 0x302,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                  max: 64,
                                },
                                {
                                  offset: 0x300,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                  max: 999,
                                },
                              ],
                            },
                            {
                              name: "Corrects Quizzes (Flags)",
                              offset: 0x1210,
                              type: "variable",
                              dataType: "uint8",
                              bigEndian: true,
                              hidden: true,
                            },
                            {
                              name: "Rip Cheato Items Bought",
                              offset: 0x10e8,
                              type: "variable",
                              dataType: "uint8",
                              max: 10,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          noMargin: true,
                          items: [
                            {
                              name: "Number of Battles",
                              offset: 0x2e2,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              max: 9999,
                            },
                            {
                              name: "Victories",
                              offset: 0x2e4,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                            },
                            {
                              name: "Times Fled",
                              type: "group",
                              mode: "fraction",
                              items: [
                                {
                                  offset: 0x2e8,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                },
                                {
                                  offset: 0x2e6,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                },
                              ],
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Your First Strikes",
                              offset: 0x2dc,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              max: 9999,
                            },
                            {
                              name: "Enemies' First Strikes",
                              offset: 0x2de,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              max: 9999,
                            },
                            {
                              name: "Total Power Bounces",
                              offset: 0x2e0,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    boots: {
      0x0: "Boots",
      0x1: "Super Boots",
      0x2: "Ultra Boots",
      0xff: "-",
    },
    characterStatus: {
      0x0: "-",
      0x1: "In Party",
    },
    characters: {
      0x0: "Goombario",
      0x1: "Kooper",
      0x2: "Bombette",
      0x3: "Parakarry",
      0x4: "Watt",
      0x5: "Sushie",
      0x6: "Lakilester",
      0x7: "Bow",
    },
    empty: {
      0x0: "-",
    },
    hammers: {
      0x0: "Hammer",
      0x1: "Super Hammer",
      0x2: "Ultra Hammer",
      0xff: "-",
    },
    items: {
      0x0: "-",
      ...items,
    },
    keyItems: {
      0x0: "-",
      ...keyItems,
    },
    letters: [
      // Europe
      {
        0x0: "♪",
        0xd: "-",
        0xe: ".",
        0x10: "0",
        0x11: "1",
        0x12: "2",
        0x13: "3",
        0x14: "4",
        0x15: "5",
        0x16: "6",
        0x17: "7",
        0x18: "8",
        0x19: "9",
        0x20: "@",
        0x21: "A",
        0x22: "B",
        0x23: "C",
        0x24: "D",
        0x25: "E",
        0x26: "F",
        0x27: "G",
        0x28: "H",
        0x29: "I",
        0x2a: "J",
        0x2b: "K",
        0x2c: "L",
        0x2d: "M",
        0x2e: "N",
        0x2f: "O",
        0x30: "P",
        0x31: "Q",
        0x32: "R",
        0x33: "S",
        0x34: "T",
        0x35: "U",
        0x36: "V",
        0x37: "W",
        0x38: "X",
        0x39: "Y",
        0x3a: "Z",
        0x41: "a",
        0x42: "b",
        0x43: "c",
        0x44: "d",
        0x45: "e",
        0x46: "f",
        0x47: "g",
        0x48: "h",
        0x49: "i",
        0x4a: "j",
        0x4b: "k",
        0x4c: "l",
        0x4d: "m",
        0x4e: "n",
        0x4f: "o",
        0x50: "p",
        0x51: "q",
        0x52: "r",
        0x53: "s",
        0x54: "t",
        0x55: "u",
        0x56: "v",
        0x57: "w",
        0x58: "x",
        0x59: "y",
        0x5a: "z",
        0x61: "Á",
        0x66: "É",
        0x6a: "Í",
        0x6d: "Ñ",
        0x6f: "Ó",
        0x73: "Ú",
        0x76: "ẞ",
        0x77: "à",
        0x78: "á",
        0x79: "â",
        0x7a: "ä",
        0x7b: "ç",
        0x7c: "è",
        0x7d: "é",
        0x7e: "ê",
        0x7f: "ë",
        0x81: "í",
        0x82: "î",
        0x84: "ñ",
        0x86: "ó",
        0x87: "ô",
        0x88: "ö",
        0x89: "ù",
        0x8a: "ú",
        0x8b: "û",
        0x8c: "ü",
        0x90: "♡",
        0x91: "☆",
        0xf7: " ",
      },
      // USA
      {
        0x0: "♪",
        0xd: "-",
        0xe: ".",
        0x10: "0",
        0x11: "1",
        0x12: "2",
        0x13: "3",
        0x14: "4",
        0x15: "5",
        0x16: "6",
        0x17: "7",
        0x18: "8",
        0x19: "9",
        0x20: "@",
        0x21: "A",
        0x22: "B",
        0x23: "C",
        0x24: "D",
        0x25: "E",
        0x26: "F",
        0x27: "G",
        0x28: "H",
        0x29: "I",
        0x2a: "J",
        0x2b: "K",
        0x2c: "L",
        0x2d: "M",
        0x2e: "N",
        0x2f: "O",
        0x30: "P",
        0x31: "Q",
        0x32: "R",
        0x33: "S",
        0x34: "T",
        0x35: "U",
        0x36: "V",
        0x37: "W",
        0x38: "X",
        0x39: "Y",
        0x3a: "Z",
        0x41: "a",
        0x42: "b",
        0x43: "c",
        0x44: "d",
        0x45: "e",
        0x46: "f",
        0x47: "g",
        0x48: "h",
        0x49: "i",
        0x4a: "j",
        0x4b: "k",
        0x4c: "l",
        0x4d: "m",
        0x4e: "n",
        0x4f: "o",
        0x50: "p",
        0x51: "q",
        0x52: "r",
        0x53: "s",
        0x54: "t",
        0x55: "u",
        0x56: "v",
        0x57: "w",
        0x58: "x",
        0x59: "y",
        0x5a: "z",
        0x90: "♡",
        0x91: "☆",
        0xf7: " ",
      },
      // Japan
      {
        0x0: "あ",
        0x1: "い",
        0x2: "う",
        0x3: "え",
        0x4: "お",
        0x5: "か",
        0x6: "き",
        0x7: "く",
        0x8: "け",
        0x9: "こ",
        0xa: "さ",
        0xb: "し",
        0xc: "す",
        0xd: "せ",
        0xe: "そ",
        0xf: "た",
        0x10: "ち",
        0x11: "つ",
        0x12: "て",
        0x13: "と",
        0x14: "な",
        0x15: "に",
        0x16: "ぬ",
        0x17: "ね",
        0x18: "の",
        0x19: "は",
        0x1a: "ひ",
        0x1b: "ふ",
        0x1c: "へ",
        0x1d: "ほ",
        0x1e: "ま",
        0x1f: "み",
        0x20: "む",
        0x21: "め",
        0x22: "も",
        0x23: "や",
        0x24: "ゆ",
        0x25: "よ",
        0x26: "ら",
        0x27: "り",
        0x28: "る",
        0x29: "れ",
        0x2a: "ろ",
        0x2b: "わ",
        0x2c: "を",
        0x2d: "ん",
        0x2e: "ゔ",
        0x2f: "が",
        0x30: "ぎ",
        0x31: "ぐ",
        0x32: "げ",
        0x33: "ご",
        0x34: "ざ",
        0x35: "じ",
        0x36: "ず",
        0x37: "ぜ",
        0x38: "ぞ",
        0x39: "だ",
        0x3a: "ぢ",
        0x3b: "づ",
        0x3c: "で",
        0x3d: "ど",
        0x3e: "ば",
        0x3f: "び",
        0x40: "ぶ",
        0x41: "べ",
        0x42: "ぼ",
        0x43: "ぱ",
        0x44: "ぴ",
        0x45: "ぷ",
        0x46: "ぺ",
        0x47: "ぽ",
        0x48: "ぁ",
        0x49: "ぃ",
        0x4a: "ぅ",
        0x4b: "ぇ",
        0x4c: "ぉ",
        0x4d: "っ",
        0x4e: "ゃ",
        0x4f: "ゅ",
        0x50: "ょ",
        0x51: "ア",
        0x52: "イ",
        0x53: "ウ",
        0x54: "エ",
        0x55: "オ",
        0x56: "カ",
        0x57: "キ",
        0x58: "ク",
        0x59: "ケ",
        0x5a: "コ",
        0x5b: "サ",
        0x5c: "シ",
        0x5d: "ス",
        0x5e: "セ",
        0x5f: "ソ",
        0x60: "タ",
        0x61: "チ",
        0x62: "ツ",
        0x63: "テ",
        0x64: "ト",
        0x65: "ナ",
        0x66: "ニ",
        0x67: "ヌ",
        0x68: "ネ",
        0x69: "ノ",
        0x6a: "ハ",
        0x6b: "ヒ",
        0x6c: "フ",
        0x6d: "ヘ",
        0x6e: "ホ",
        0x6f: "マ",
        0x70: "ミ",
        0x71: "ム",
        0x72: "メ",
        0x73: "モ",
        0x74: "ヤ",
        0x75: "ユ",
        0x76: "ヨ",
        0x77: "ラ",
        0x78: "リ",
        0x79: "ル",
        0x7a: "レ",
        0x7b: "ロ",
        0x7c: "ワ",
        0x7d: "ヲ",
        0x7e: "ン",
        0x7f: "ヴ",
        0x80: "ガ",
        0x81: "ギ",
        0x82: "グ",
        0x83: "ゲ",
        0x84: "ゴ",
        0x85: "ザ",
        0x86: "ジ",
        0x87: "ズ",
        0x88: "ゼ",
        0x89: "ゾ",
        0x8a: "ダ",
        0x8b: "ヂ",
        0x8c: "ヅ",
        0x8d: "デ",
        0x8e: "ド",
        0x8f: "バ",
        0x90: "ビ",
        0x91: "ブ",
        0x92: "ベ",
        0x93: "ボ",
        0x94: "パ",
        0x95: "ピ",
        0x96: "プ",
        0x97: "ペ",
        0x98: "ポ",
        0x99: "ァ",
        0x9a: "ィ",
        0x9b: "ゥ",
        0x9c: "ェ",
        0x9d: "ォ",
        0x9e: "ッ",
        0x9f: "ャ",
        0xa0: "ュ",
        0xa1: "ョ",
        0xa2: "ー",
        0xa3: "~",
        0xa7: "0",
        0xa8: "1",
        0xa9: "2",
        0xaa: "3",
        0xab: "4",
        0xac: "5",
        0xad: "6",
        0xae: "7",
        0xaf: "8",
        0xb0: "9",
        0xb5: "!",
        0xb6: "?",
        0xba: ".",
        0xbd: "♡",
        0xbe: "☆",
        0xc3: "・",
        0xf7: " ",
      },
    ],
    liLShoinks: {
      0x0: "Black",
      0x1: "White",
      0x2: "Pink",
      0x3: "Tiger",
      0x4: "Shroom",
      0x5: "Flower",
      0x6: "Star",
      0x7: "Question Mark",
      0x8: "Silver",
      0x9: "Gold",
    },
    locations,
    partners: {
      0x0: "-",
      0x1: "Goombario",
      0x2: "Kooper",
      0x3: "Bombette",
      0x4: "Parakarry",
      0x6: "Watt",
      0x7: "Sushie",
      0x8: "Lakilester",
      0x9: "Bow",
    },
    ranks: {
      0x0: "-",
      0x1: "Super-rank",
      0x2: "Ultra-rank",
    },
  },
  resourcesGroups: {
    items: itemsGroups,
    locations: locationsGroups,
  },
  resourcesOrder: {
    boots: [0xff],
    hammers: [0xff],
    keyItems: keyItemsOrder,
    items: itemsOrder,
    locations: locationsOrder,
  },
};

export default template;
