import { bitToOffset } from "$lib/utils/bytes";

import type { GameJson, ItemBitflags } from "$lib/types";

import { techTypes } from "../saveEditor/utils/resource";

const template: GameJson = {
  validator: {
    platforms: {
      supernintendo: {
        usa: {
          0xffb0: [0x43, 0x33, 0x41, 0x43, 0x54, 0x45], // "C3ACTE"
        },
        japan: {
          0xffb0: [0x43, 0x33, 0x41, 0x43, 0x54, 0x4a], // "C3ACTJ"
        },
      },
    },
    text: "Drag 'n' drop here or click to add a rom file.",
    error: "Not a valid rom file.",
  },
  items: [
    {
      type: "tabs",
      items: [
        {
          name: "Party",
          items: [
            {
              id: "party",
              instanceId: "characters",
              length: 0x50,
              type: "container",
              instanceType: "tabs",
              instances: 7,
              resource: "characterNames",
              vertical: true,
              items: [
                {
                  type: "tabs",
                  items: [
                    {
                      name: "Status",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              type: "component",
                              component: "PartyPortraitSelector",
                              props: { characterIndex: "characters" },
                            },
                            {
                              id: "cName-%index%",
                              name: "Name",
                              dataViewAltKey: "init",
                              offset: 0x8a,
                              length: 0x5,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              endCode: 0x0,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              disabled: true,
                            },
                            {
                              name: "Element",
                              offset: 0xc0001,
                              type: "variable",
                              dataType: "upper4",
                              resource: "elements",
                            },
                            {
                              name: "Element Value?",
                              offset: 0xc0001,
                              type: "variable",
                              dataType: "lower4",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "cLevel",
                              name: "Level",
                              offset: 0xc0012,
                              type: "variable",
                              dataType: "uint8",
                              min: 1,
                              max: 99,
                            },
                            {
                              id: "cExperience",
                              name: "Experience",
                              offset: 0xc0013,
                              type: "variable",
                              dataType: "uint24",
                              max: 9999999,
                            },
                            {
                              name: "Tech Points",
                              offset: 0xc0016,
                              type: "variable",
                              dataType: "uint24",
                              max: 9999999,
                            },
                            {
                              name: "Next Experience",
                              offset: 0xc002b,
                              type: "variable",
                              dataType: "uint16",
                              hidden: true,
                            },
                            {
                              name: "Next Tech Points",
                              offset: 0xc002d,
                              type: "variable",
                              dataType: "uint16",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "HP",
                              type: "group",
                              mode: "fraction",
                              items: [
                                {
                                  offset: 0xc0003,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                                {
                                  offset: 0xc0005,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                              ],
                            },
                            {
                              name: "MP",
                              type: "group",
                              mode: "fraction",
                              items: [
                                {
                                  offset: 0xc0007,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 99,
                                },
                                {
                                  offset: 0xc0009,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 99,
                                },
                              ],
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          hidden: true,
                          items: [
                            {
                              name: "Base Power",
                              offset: 0xc000b,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Stamina",
                              offset: 0xc000c,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Speed",
                              offset: 0xc000d,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Magic",
                              offset: 0xc000e,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Hit",
                              offset: 0xc000f,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Evade",
                              offset: 0xc0010,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Magic Defense",
                              offset: 0xc0011,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "baseStats-36",
                              name: "Base Power",
                              offset: 0xc002f,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              id: "baseStats-36",
                              name: "Base Stamina",
                              offset: 0xc0030,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              id: "baseStats-36",
                              name: "Base Speed",
                              offset: 0xc0031,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              id: "baseStats-38",
                              name: "Base Magic",
                              offset: 0xc0034,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              id: "baseStats-35",
                              name: "Base Hit",
                              offset: 0xc0032,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              id: "baseStats-35",
                              name: "Base Evade",
                              offset: 0xc0033,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              id: "baseStats-36",
                              name: "Base Magic Defense",
                              offset: 0xc0035,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Equipment",
                      flex: true,
                      items: [
                        {
                          name: "Weapon",
                          offset: 0xc0029,
                          type: "variable",
                          dataType: "uint8",
                          resource: "weapons",
                          autocomplete: true,
                        },
                        {
                          name: "Helmet",
                          offset: 0xc0027,
                          type: "variable",
                          dataType: "uint8",
                          resource: "helmets",
                          autocomplete: true,
                        },
                        {
                          name: "Armor",
                          offset: 0xc0028,
                          type: "variable",
                          dataType: "uint8",
                          resource: "armors",
                          autocomplete: true,
                        },
                        {
                          name: "Accessory",
                          offset: 0xc002a,
                          type: "variable",
                          dataType: "uint8",
                          resource: "accessories",
                          autocomplete: true,
                        },
                      ],
                    },
                    {
                      name: "Tech",
                      flex: true,
                      items: [
                        {
                          name: "Tech Count",
                          offset: 0xc0230,
                          type: "variable",
                          dataType: "uint8",
                          overrideShift: {
                            parent: 1,
                            shift: 0x1,
                          },
                          hidden: true,
                        },
                        ...techTypes.map(
                          (type, index) =>
                            ({
                              id: `tech-%index%-${index}`,
                              name: type.name,
                              type: "bitflags",
                              flags: type.tech.map((tech) => ({
                                offset: 0xc0237 + bitToOffset(tech.index),
                                bit: tech.index % 8,
                                label: tech.name,
                              })),
                            }) as ItemBitflags,
                        ),
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Inventory",
          items: [
            {
              type: "tabs",
              items: [
                {
                  name: "Weapons",
                  items: [
                    {
                      id: "weapons",
                      length: 0x5,
                      type: "container",
                      instanceType: "tabs",
                      instances: 90,
                      resource: "weaponNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-weapons",
                              name: "Name",
                              offset: 0x1,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-weapons",
                              name: "Icon",
                              offset: 0x0,
                              type: "variable",
                              dataType: "uint8",
                              resource: "icons",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              name: "Price",
                              offset: 0xc06a5,
                              type: "variable",
                              dataType: "uint16",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Attack",
                              offset: 0xc0262,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Critical Rate",
                              offset: 0xc0264,
                              type: "variable",
                              dataType: "uint8",
                              max: 100,
                              suffix: "%",
                            },
                            {
                              name: "Bonus Stats",
                              offset: 0xc06a8,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              resource: "equipmentBonusStatsNames",
                              autocomplete: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Effect",
                              offset: 0xc0265,
                              type: "variable",
                              dataType: "uint16",
                              resource: "weaponEffects",
                              size: "lg",
                              autocomplete: true,
                            },
                            {
                              name: "Resistance?",
                              offset: 0xc06a9,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Equippable by",
                              type: "bitflags",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              flags: [
                                { offset: 0xc06a7, bit: 7, label: "Crono" },
                                { offset: 0xc06a7, bit: 6, label: "Marle" },
                                { offset: 0xc06a7, bit: 5, label: "Lucca" },
                                { offset: 0xc06a7, bit: 4, label: "Robo" },
                                { offset: 0xc06a7, bit: 3, label: "Frog" },
                                { offset: 0xc06a7, bit: 2, label: "Ayla" },
                                { offset: 0xc06a7, bit: 1, label: "Magus" },
                                { offset: 0xc06a7, bit: 0, label: "???", hidden: true },
                              ],
                            },
                            {
                              name: "Special",
                              type: "bitflags",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              flags: [
                                { offset: 0xc06a4, bit: 0, label: "???", hidden: true },
                                { offset: 0xc06a4, bit: 1, label: "???", hidden: true },
                                { offset: 0xc06a4, bit: 2, label: "Can't be sold" },
                                { offset: 0xc06a4, bit: 3, label: "???", hidden: true },
                                { offset: 0xc06a4, bit: 4, label: "Not transferable on New Game +" },
                                { offset: 0xc06a4, bit: 5, label: "???", hidden: true },
                                { offset: 0xc06a4, bit: 6, label: "???", hidden: true },
                                { offset: 0xc06a4, bit: 7, label: "???", hidden: true },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Armor",
                  items: [
                    {
                      id: "armor",
                      length: 0x3,
                      type: "container",
                      instanceType: "tabs",
                      instances: 33,
                      resource: "armorNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-armors",
                              name: "Name",
                              offset: 0x1,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-armors",
                              name: "Icon",
                              offset: 0x0,
                              type: "variable",
                              dataType: "uint8",
                              resource: "icons",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              name: "Price",
                              offset: 0xc08c1,
                              type: "variable",
                              dataType: "uint16",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Defense",
                              offset: 0xc047e,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Bonus Stats",
                              offset: 0xc08c4,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              resource: "equipmentBonusStatsNames",
                              autocomplete: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Effect",
                              offset: 0xc047f,
                              type: "variable",
                              dataType: "uint16",
                              resource: "armorEffects",
                              size: "lg",
                              autocomplete: true,
                            },
                            {
                              name: "Resistance",
                              offset: 0xc08c5,
                              type: "variable",
                              dataType: "uint8",
                              resource: "armorResistances",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              size: "lg",
                              autocomplete: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Equippable by",
                              type: "bitflags",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              flags: [
                                { offset: 0xc08c3, bit: 7, label: "Crono" },
                                { offset: 0xc08c3, bit: 6, label: "Marle" },
                                { offset: 0xc08c3, bit: 5, label: "Lucca" },
                                { offset: 0xc08c3, bit: 4, label: "Robo" },
                                { offset: 0xc08c3, bit: 3, label: "Frog" },
                                { offset: 0xc08c3, bit: 2, label: "Ayla" },
                                { offset: 0xc08c3, bit: 1, label: "Magus" },
                                { offset: 0xc08c3, bit: 0, label: "???", hidden: true },
                              ],
                            },
                            {
                              name: "Special",
                              type: "bitflags",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              flags: [
                                { offset: 0xc08c0, bit: 0, label: "???", hidden: true },
                                { offset: 0xc08c0, bit: 1, label: "???", hidden: true },
                                { offset: 0xc08c0, bit: 2, label: "Can't be sold" },
                                { offset: 0xc08c0, bit: 3, label: "???", hidden: true },
                                { offset: 0xc08c0, bit: 4, label: "Not transferable on New Game +" },
                                { offset: 0xc08c0, bit: 5, label: "???", hidden: true },
                                { offset: 0xc08c0, bit: 6, label: "???", hidden: true },
                                { offset: 0xc08c0, bit: 7, label: "???", hidden: true },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Helmets",
                  items: [
                    {
                      id: "helmets",
                      length: 0x3,
                      type: "container",
                      instanceType: "tabs",
                      instances: 25,
                      resource: "helmetNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-helmets",
                              name: "Name",
                              offset: 0x1,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-helmets",
                              name: "Icon",
                              offset: 0x0,
                              type: "variable",
                              dataType: "uint8",
                              resource: "icons",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              name: "Price",
                              offset: 0xc0987,
                              type: "variable",
                              dataType: "uint16",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Defense",
                              offset: 0xc04e1,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Bonus Stats",
                              offset: 0xc098a,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              resource: "equipmentBonusStatsNames",
                              autocomplete: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Effect",
                              offset: 0xc04e2,
                              type: "variable",
                              dataType: "uint16",
                              resource: "armorEffects",
                              size: "lg",
                              autocomplete: true,
                            },
                            {
                              name: "Resistance",
                              offset: 0xc098b,
                              type: "variable",
                              dataType: "uint8",
                              resource: "armorResistances",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              size: "lg",
                              autocomplete: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Equippable by",
                              type: "bitflags",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              flags: [
                                { offset: 0xc0989, bit: 7, label: "Crono" },
                                { offset: 0xc0989, bit: 6, label: "Marle" },
                                { offset: 0xc0989, bit: 5, label: "Lucca" },
                                { offset: 0xc0989, bit: 4, label: "Robo" },
                                { offset: 0xc0989, bit: 3, label: "Frog" },
                                { offset: 0xc0989, bit: 2, label: "Ayla" },
                                { offset: 0xc0989, bit: 1, label: "Magus" },
                                { offset: 0xc0989, bit: 0, label: "???", hidden: true },
                              ],
                            },
                            {
                              name: "Special",
                              type: "bitflags",
                              overrideShift: {
                                parent: 1,
                                shift: 0x6,
                              },
                              flags: [
                                { offset: 0xc0986, bit: 0, label: "???", hidden: true },
                                { offset: 0xc0986, bit: 1, label: "???", hidden: true },
                                { offset: 0xc0986, bit: 2, label: "Can't be sold" },
                                { offset: 0xc0986, bit: 3, label: "???", hidden: true },
                                { offset: 0xc0986, bit: 4, label: "Not transferable on New Game +" },
                                { offset: 0xc0986, bit: 5, label: "???", hidden: true },
                                { offset: 0xc0986, bit: 6, label: "???", hidden: true },
                                { offset: 0xc0986, bit: 7, label: "???", hidden: true },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Accessories",
                  items: [
                    {
                      id: "accessories",
                      length: 0x4,
                      type: "container",
                      instanceType: "tabs",
                      instances: 40,
                      resource: "accessoryNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-accessories",
                              name: "Name",
                              offset: 0x1,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-accessories",
                              name: "Icon",
                              offset: 0x0,
                              type: "variable",
                              dataType: "uint8",
                              resource: "icons",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              name: "Price",
                              offset: 0xc0a1d,
                              type: "variable",
                              dataType: "uint16",
                              overrideShift: {
                                parent: 1,
                                shift: 0x4,
                              },
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          hidden: true,
                          items: [
                            {
                              name: "Unknown c052c",
                              offset: 0xc052c,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Unknown c052d",
                              offset: 0xc052d,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Bonus Stats",
                              offset: 0xc052e,
                              type: "variable",
                              dataType: "uint8",
                              resource: "equipmentBonusStatsNames",
                              autocomplete: true,
                              hidden: true,
                            },
                            {
                              name: "Unknown c052f",
                              offset: 0xc052f,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Resistance?",
                              offset: 0xc0a1e,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0x4,
                              },
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Equippable by",
                              type: "bitflags",
                              overrideShift: {
                                parent: 1,
                                shift: 0x4,
                              },
                              flags: [
                                { offset: 0xc0a1f, bit: 7, label: "Crono" },
                                { offset: 0xc0a1f, bit: 6, label: "Marle" },
                                { offset: 0xc0a1f, bit: 5, label: "Lucca" },
                                { offset: 0xc0a1f, bit: 4, label: "Robo" },
                                { offset: 0xc0a1f, bit: 3, label: "Frog" },
                                { offset: 0xc0a1f, bit: 2, label: "Ayla" },
                                { offset: 0xc0a1f, bit: 1, label: "Magus" },
                                { offset: 0xc0a1f, bit: 0, label: "???", hidden: true },
                              ],
                            },
                            {
                              name: "Special",
                              type: "bitflags",
                              overrideShift: {
                                parent: 1,
                                shift: 0x4,
                              },
                              flags: [
                                { offset: 0xc0a1c, bit: 0, label: "???", hidden: true },
                                { offset: 0xc0a1c, bit: 1, label: "???", hidden: true },
                                { offset: 0xc0a1c, bit: 2, label: "Can't be sold" },
                                { offset: 0xc0a1c, bit: 3, label: "???", hidden: true },
                                { offset: 0xc0a1c, bit: 4, label: "Not transferable on New Game +" },
                                { offset: 0xc0a1c, bit: 5, label: "???", hidden: true },
                                { offset: 0xc0a1c, bit: 6, label: "???", hidden: true },
                                { offset: 0xc0a1c, bit: 7, label: "???", hidden: true },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Items",
                  items: [
                    {
                      id: "items",
                      length: 0x4,
                      type: "container",
                      instanceType: "tabs",
                      instances: 20,
                      resource: "itemNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-items",
                              name: "Name",
                              offset: 0x1,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-items",
                              name: "Icon",
                              offset: 0x0,
                              type: "variable",
                              dataType: "uint8",
                              resource: "icons",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              name: "Price",
                              offset: 0xc0abd,
                              type: "variable",
                              dataType: "uint16",
                              overrideShift: {
                                parent: 1,
                                shift: 0x3,
                              },
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Unknown c05cc",
                              offset: 0xc05cc,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Unknown c05cd",
                              offset: 0xc05cd,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Unknown c05ce",
                              offset: 0xc05ce,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Unknown c05cf",
                              offset: 0xc05cf,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Unknown c0abc",
                              offset: 0xc0abc,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0x3,
                              },
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Key Items",
                  planned: true,
                  items: [],
                },
              ],
            },
          ],
        },
        {
          name: "Tech",
          planned: true,
          items: [],
        },
        {
          name: "Enemies",
          items: [
            {
              id: "enemies",
              length: 0x17,
              type: "container",
              instanceType: "tabs",
              instances: 256,
              resource: "enemyNames",
              vertical: true,
              items: [
                {
                  type: "tabs",
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "eEnemy",
                              name: "Name",
                              offset: 0x1e00,
                              length: 0xb,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Level",
                              offset: 0x2,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              name: "HP",
                              offset: 0x0,
                              type: "variable",
                              dataType: "uint16",
                              max: 32767,
                            },
                            {
                              name: "Attack",
                              offset: 0xe,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Defense",
                              offset: 0xf,
                              type: "variable",
                              dataType: "uint8",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Power",
                              offset: 0x8,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Speed",
                              offset: 0x9,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Magic",
                              offset: 0xa,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Hit",
                              offset: 0xb,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Evade",
                              offset: 0xc,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Magic Defense",
                              offset: 0xd,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Unknown 3",
                              offset: 0x3,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Unknown 5",
                              offset: 0x5,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Unknown 6",
                              offset: 0x6,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Unknown 7",
                              offset: 0x7,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Unknown 16",
                              offset: 0x16,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          noMargin: true,
                          items: [
                            {
                              id: "eDrops",
                              name: "Experience",
                              offset: 0x1700,
                              type: "variable",
                              dataType: "uint16",
                              overrideShift: {
                                parent: 1,
                                shift: 0x7,
                              },
                            },
                            {
                              id: "eDrops",
                              name: "Gold",
                              offset: 0x1702,
                              type: "variable",
                              dataType: "uint16",
                              overrideShift: {
                                parent: 1,
                                shift: 0x7,
                              },
                            },
                            {
                              id: "eDrops",
                              name: "Tech Points",
                              offset: 0x1706,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0x7,
                              },
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "eDrops",
                              name: "Drop Item",
                              offset: 0x1704,
                              type: "variable",
                              dataType: "uint8",
                              resource: "items",
                              overrideShift: {
                                parent: 1,
                                shift: 0x7,
                              },
                              autocomplete: true,
                            },
                            {
                              id: "eDrops",
                              name: "Charmable Item",
                              offset: 0x1705,
                              type: "variable",
                              dataType: "uint8",
                              resource: "items",
                              overrideShift: {
                                parent: 1,
                                shift: 0x7,
                              },
                              autocomplete: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Weaknesses",
                      items: [
                        {
                          name: "Elements",
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Lightning",
                              type: "group",
                              items: [
                                {
                                  offset: 0x10,
                                  type: "variable",
                                  dataType: "bit",
                                  bit: 7,
                                  resource: "elementStatus",
                                },
                                {
                                  offset: 0x10,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: {
                                    bitStart: 0,
                                    bitLength: 7,
                                  },
                                  resource: "elementValues",
                                },
                              ],
                            },
                            {
                              name: "Shadow",
                              type: "group",
                              items: [
                                {
                                  offset: 0x11,
                                  type: "variable",
                                  dataType: "bit",
                                  bit: 7,
                                  resource: "elementStatus",
                                },
                                {
                                  offset: 0x11,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: {
                                    bitStart: 0,
                                    bitLength: 7,
                                  },
                                  resource: "elementValues",
                                },
                              ],
                            },
                            {
                              name: "Fire",
                              type: "group",
                              items: [
                                {
                                  offset: 0x13,
                                  type: "variable",
                                  dataType: "bit",
                                  bit: 7,
                                  resource: "elementStatus",
                                },
                                {
                                  offset: 0x13,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: {
                                    bitStart: 0,
                                    bitLength: 7,
                                  },
                                  resource: "elementValues",
                                },
                              ],
                            },
                            {
                              name: "Water",
                              type: "group",
                              items: [
                                {
                                  offset: 0x12,
                                  type: "variable",
                                  dataType: "bit",
                                  bit: 7,
                                  resource: "elementStatus",
                                },
                                {
                                  offset: 0x12,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: {
                                    bitStart: 0,
                                    bitLength: 7,
                                  },
                                  resource: "elementValues",
                                },
                              ],
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Abilities",
                              type: "bitflags",
                              reversed: true,
                              flags: [
                                { offset: 0x14, bit: 2, label: "Physical Attacks" },
                                { offset: 0x14, bit: 0, label: "???", hidden: true },
                                { offset: 0x14, bit: 1, label: "Rock Throw" },
                                { offset: 0x14, bit: 3, label: "???", hidden: true },
                                { offset: 0x14, bit: 4, label: "???", hidden: true },
                                { offset: 0x14, bit: 5, label: "Slurp Cut" },
                                { offset: 0x14, bit: 6, label: "Beat Toss" },
                                { offset: 0x14, bit: 7, label: "Black Hole" },
                              ],
                            },
                            {
                              name: "Condition",
                              type: "bitflags",
                              reversed: true,
                              flags: [
                                { offset: 0x4, bit: 0, label: "Slow?", hidden: true },
                                { offset: 0x4, bit: 1, label: "Sleep" },
                                { offset: 0x4, bit: 2, label: "Confusion" },
                                { offset: 0x4, bit: 3, label: "???", hidden: true },
                                { offset: 0x4, bit: 4, label: "???", hidden: true },
                                { offset: 0x4, bit: 5, label: "???", hidden: true },
                                { offset: 0x4, bit: 6, label: "Slow?", hidden: true },
                                { offset: 0x4, bit: 7, label: "Stop" },
                              ],
                            },
                            {
                              name: "Type",
                              type: "bitflags",
                              flags: [
                                { offset: 0x15, bit: 0, label: "Is Boss?", hidden: true },
                                { offset: 0x15, bit: 1, label: "???", hidden: true },
                                { offset: 0x15, bit: 2, label: "???", hidden: true },
                                { offset: 0x15, bit: 3, label: "Magic" },
                                { offset: 0x15, bit: 4, label: "???", hidden: true },
                                { offset: 0x15, bit: 5, label: "???", hidden: true },
                                { offset: 0x15, bit: 6, label: "Machine" },
                                { offset: 0x15, bit: 7, label: "Undead" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Shops",
          items: [
            {
              id: "shops",
              type: "tabs",
              vertical: true,
              items: [
                {
                  name: "Dummy",
                  flex: true,
                  items: [
                    {
                      name: "Dummy",
                      offset: 0x0,
                      type: "variable",
                      dataType: "uint8",
                      resource: "items",
                      autocomplete: true,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Miscellaneous",
          items: [
            {
              type: "tabs",
              items: [
                {
                  name: "Equipment Bonus Stats",
                  items: [
                    {
                      id: "equipmentBonusStats",
                      length: 0x2,
                      type: "container",
                      instanceType: "tabs",
                      instances: 22,
                      resource: "equipmentBonusStatsNames",
                      vertical: true,
                      flex: true,
                      items: [
                        {
                          id: "mEquipmentBonusStats",
                          name: "Attributes",
                          type: "bitflags",
                          flags: [
                            { offset: 0x0, bit: 7, label: "Power" },
                            { offset: 0x0, bit: 6, label: "Speed" },
                            { offset: 0x0, bit: 5, label: "Stamina" },
                            { offset: 0x0, bit: 2, label: "Magic" },
                            { offset: 0x0, bit: 4, label: "Hit" },
                            { offset: 0x0, bit: 3, label: "Evade" },
                            { offset: 0x0, bit: 1, label: "Magic Defense" },
                            { offset: 0x0, bit: 0, label: "???", hidden: true },
                          ],
                        },
                        {
                          id: "mEquipmentBonusStatsValue-%index%",
                          name: "Value",
                          offset: 0x1,
                          type: "variable",
                          dataType: "uint8",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Map Viewer",
          items: [
            {
              instanceId: "mapViewer",
              length: 0x2,
              type: "container",
              instanceType: "tabs",
              instances: 512,
              enumeration: "Map %d",
              vertical: true,
              flex: true,
              items: [
                {
                  type: "component",
                  component: "MapViewer",
                  props: { roomIndex: "mapViewer" },
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    accessories: "getInventoryNames('accessories', true)",
    accessoryNames: "getInventoryNames('accessories')",
    armorEffects: {
      0x0: "-",
      0x117: "Cuts physical damage by 1/3",
      0x11a: 'Absorbs 50% of "Lightning" hits',
      0x11b: 'Absorbs 50% of "Shadow" hits',
      0x11c: 'Absorbs 50% of "Water" hits',
      0x11d: 'Absorbs 50% of "Fire" hits',
      0x11f: 'Absorbs "Lightning" hits',
      0x120: 'Absorbs "Shadow" hits',
      0x121: 'Absorbs "Water" hits',
      0x122: 'Absorbs "Fire" hits',
      0x12a: 'Prevents "Chaos"',
      0x12b: 'Prevents "Lock"',
      0x12c: 'Prevents "Stop", "Slow"',
      0x12d: "Protects status",
      0x131: "Cuts Mg attack by 1/3",
      0x132: 'Inflicts "Chaos"',
      0x133: "50% less time between attacks",
    },
    armorNames: "getInventoryNames('armors')",
    armorResistances: {
      0x0: "-",
      0x15: 'Cuts "Fire" hits by 50%',
      0x1f: 'Cuts "Fire" hits by 80%',
      0x25: 'Cuts "Water" hits by 50%',
      0x2f: 'Cuts "Water" hits by 80%',
      0x45: 'Cuts "Shadow" hits by 50%',
      0x4f: 'Cuts "Shadow" hits by 80%',
      0x85: 'Cuts "Lightning" hits by 50%',
      0x8f: 'Cuts "Lightning" hits by 80%',
    },
    armors: "getInventoryNames('armors', true)",
    equipmentBonusStatsNames: "getEquipmentBonusStatsNames()",
    characterNames: "getCharacterNames()",
    elementStatus: {
      0x0: "Damage",
      0x1: "Absorb",
    },
    elementValues: {
      0x0: "0",
      0x1: "x4",
      0x2: "x2",
      0x3: "x1.33",
      0x4: "x1",
      0x5: "x0.8",
      0x6: "x0.67",
      0x7: "0.57",
      0x8: "x0.5",
      0xf: "x0.27",
      0x10: "x0.25",
      0x20: "x0.13",
      0x40: "x0.02",
    },
    elements: {
      0x1: "Fire",
      0x2: "Water",
      0x4: "Shadow",
      0x8: "Lightning",
    },
    enemyNames: "getEnemyNames()",
    helmetNames: "getInventoryNames('helmets')",
    helmets: "getInventoryNames('helmets', true)",
    icons: {
      0x20: "Katana",
      0x21: "Bow",
      0x22: "Gun",
      0x23: "Arm",
      0x24: "Swords",
      0x25: "Fist",
      0x26: "Scythe",
      0x27: "Helmets",
      0x28: "Armor",
      0x29: "Accessories",
      0xef: "-",
      0xff: "[space]",
    },
    itemNames: "getInventoryNames('items')",
    items: "getInventoryNames('*', true)",
    letters: [
      // USA
      {
        0xa0: "A",
        0xa1: "B",
        0xa2: "C",
        0xa3: "D",
        0xa4: "E",
        0xa5: "F",
        0xa6: "G",
        0xa7: "H",
        0xa8: "I",
        0xa9: "J",
        0xaa: "K",
        0xab: "L",
        0xac: "M",
        0xad: "N",
        0xae: "O",
        0xaf: "P",
        0xb0: "Q",
        0xb1: "R",
        0xb2: "S",
        0xb3: "T",
        0xb4: "U",
        0xb5: "V",
        0xb6: "W",
        0xb7: "X",
        0xb8: "Y",
        0xb9: "Z",
        0xba: "a",
        0xbb: "b",
        0xbc: "c",
        0xbd: "d",
        0xbe: "e",
        0xbf: "f",
        0xc0: "g",
        0xc1: "h",
        0xc2: "i",
        0xc3: "j",
        0xc4: "k",
        0xc5: "l",
        0xc6: "m",
        0xc7: "n",
        0xc8: "o",
        0xc9: "p",
        0xca: "q",
        0xcb: "r",
        0xcc: "s",
        0xcd: "t",
        0xce: "u",
        0xcf: "v",
        0xd0: "w",
        0xd1: "x",
        0xd2: "y",
        0xd3: "z",
        0xd4: "0",
        0xd5: "1",
        0xd6: "2",
        0xd7: "3",
        0xd8: "4",
        0xd9: "5",
        0xda: "6",
        0xdb: "7",
        0xdc: "8",
        0xdd: "9",
        0xde: "!",
        0xdf: "?",
        0xe0: "/",
        0xe1: "“",
        0xe2: "”",
        0xe3: ":",
        0xe4: "&",
        0xe5: "(",
        0xe6: ")",
        0xe7: "'",
        0xe8: ".",
        0xe9: ",",
        0xea: "=",
        0xeb: "-",
        0xec: "+",
        0xed: "%",
        0xef: " ",
        0xf3: "#",
      },
      // Japan
      {
        0x40: "バ",
        0x41: "ば",
        0x42: "ビ",
        0x43: "び",
        0x44: "ブ",
        0x45: "ぶ",
        0x46: "ベ",
        0x47: "べ",
        0x48: "ボ",
        0x49: "ぼ",
        0x4a: "ガ",
        0x4b: "が",
        0x4c: "ギ",
        0x4d: "ぎ",
        0x4e: "グ",
        0x4f: "ぐ",
        0x50: "ゲ",
        0x51: "げ",
        0x52: "ゴ",
        0x53: "ご",
        0x54: "ザ",
        0x55: "ざ",
        0x56: "ジ",
        0x57: "じ",
        0x58: "ズ",
        0x59: "ず",
        0x5a: "ゼ",
        0x5b: "ぜ",
        0x5c: "ゾ",
        0x5d: "ぞ",
        0x5e: "ダ",
        0x5f: "だ",
        0x60: "ヂ",
        0x61: "ぢ",
        0x62: "ヅ",
        0x63: "づ",
        0x64: "デ",
        0x65: "で",
        0x66: "ド",
        0x67: "ど",
        0x68: "ヴ",
        0x69: "パ",
        0x6a: "ぱ",
        0x6b: "ピ",
        0x6c: "ぴ",
        0x6d: "プ",
        0x6e: "ぷ",
        0x6f: "ペ",
        0x70: "ぺ",
        0x71: "ポ",
        0x72: "ぽ",
        0x73: "0",
        0x74: "1",
        0x75: "2",
        0x76: "3",
        0x77: "4",
        0x78: "5",
        0x79: "6",
        0x7a: "7",
        0x7b: "8",
        0x7c: "9",
        0x80: "ハ",
        0x81: "は",
        0x82: "ヒ",
        0x83: "ひ",
        0x84: "フ",
        0x85: "ふ",
        0x86: "ヘ",
        0x87: "へ",
        0x88: "ホ",
        0x89: "ほ",
        0x8a: "カ",
        0x8b: "か",
        0x8c: "キ",
        0x8d: "き",
        0x8e: "ク",
        0x8f: "く",
        0x90: "ケ",
        0x91: "け",
        0x92: "コ",
        0x93: "こ",
        0x94: "サ",
        0x95: "さ",
        0x96: "シ",
        0x97: "し",
        0x98: "ス",
        0x99: "す",
        0x9a: "セ",
        0x9b: "せ",
        0x9c: "ソ",
        0x9d: "そ",
        0x9e: "タ",
        0x9f: "た",
        0xa0: "チ",
        0xa1: "ち",
        0xa2: "ツ",
        0xa3: "つ",
        0xa4: "テ",
        0xa5: "て",
        0xa6: "ト",
        0xa7: "と",
        0xa8: "ウ",
        0xa9: "う",
        0xaa: "ア",
        0xab: "あ",
        0xac: "イ",
        0xad: "い",
        0xae: "エ",
        0xaf: "え",
        0xb0: "オ",
        0xb1: "お",
        0xb2: "ナ",
        0xb3: "な",
        0xb4: "ニ",
        0xb5: "に",
        0xb6: "ヌ",
        0xb7: "ぬ",
        0xb8: "ネ",
        0xb9: "ね",
        0xba: "ノ",
        0xbb: "の",
        0xbc: "マ",
        0xbd: "ま",
        0xbe: "ミ",
        0xbf: "み",
        0xc0: "ヤ",
        0xc1: "や",
        0xc2: "ユ",
        0xc3: "ゆ",
        0xc4: "ヨ",
        0xc5: "よ",
        0xc6: "ワ",
        0xc7: "わ",
        0xc8: "ン",
        0xc9: "ん",
        0xca: "ヲ",
        0xcb: "を",
        0xcc: "ッ",
        0xcd: "っ",
        0xce: "ャ",
        0xcf: "ゃ",
        0xd0: "ム",
        0xd1: "む",
        0xd2: "メ",
        0xd3: "め",
        0xd4: "モ",
        0xd5: "も",
        0xd6: "ラ",
        0xd7: "ら",
        0xd8: "リ",
        0xd9: "り",
        0xda: "ル",
        0xdb: "る",
        0xdc: "レ",
        0xdd: "れ",
        0xde: "ロ",
        0xdf: "ろ",
        0xe0: "ュ",
        0xe1: "ゅ",
        0xe2: "ョ",
        0xe3: "ょ",
        0xe4: "ァ",
        0xe5: "-",
        0xe6: "ィ",
        0xe8: "ゥ",
        0xe9: "!",
        0xea: "ェ",
        0xeb: "?",
        0xec: "ォ",
        0xed: "/",
        0xfd: "魔",
        0xfe: "王",
        0xff: " ",
      },
    ],
    portraits: {
      0x0: "Crono",
      0x1: "Marle",
      0x2: "Lucca",
      0x3: "Robo",
      0x4: "Frog",
      0x5: "Ayla",
      0x6: "Magus",
    },
    weaponEffects: {
      0x0: "-",
      0x102: "Damage can vary",
      0x10c: "1.5x hit on Mg enemies",
      0x10d: "2x hit on Mg enemies",
      0x116: "Attack up when ally falls",
      0x118: "Cuts enemy's HP by 1/2",
      0x119: "Attack changes below 10 HP",
      0x126: 'Random "Stop"',
      0x127: 'Random "Slow"',
      0x128: 'Random "Stop" on machines',
      0x129: 'Random "Chaos"',
      0x12e: 'Inflicts "Chaos"',
      0x12f: "4x damage at critical",
      0x138: "9999 at critical",
    },
    weaponNames: "getInventoryNames('weapons')",
    weapons: "getInventoryNames('weapons', true)",
  },
  resourcesOrder: {
    elements: [0x8, 0x4, 0x2, 0x1],
    icons: [0xef, 0xff],
  },
};

export default template;
