import type { GameJson, ItemTab } from "$lib/types";

import { circuits } from "./utils/resource";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa_japan: {},
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      id: "slots",
      length: 0x80,
      type: "container",
      instanceType: "tabs",
      instances: 8,
      enumeration: "Slot %d",
      disableSubinstanceIf: {
        offset: 0x100,
        type: "variable",
        dataType: "uint8",
        operator: "=",
        value: 0x0,
      },
      appendSubinstance: [
        {
          name: "Records",
          items: [
            {
              type: "tabs",
              vertical: true,
              items: circuits.map((circuit, circuitIndex) => {
                const scoreShift = circuitIndex * 0x80;

                return {
                  name: circuit.name,
                  items: [
                    {
                      type: "tabs",
                      vertical: true,
                      items: [
                        ...circuit.opponents.map((opponent, index) => {
                          const timeShift = circuitIndex * 0x200 + index * 0x80;

                          return {
                            name: opponent,
                            items: [
                              {
                                name: "Checksum",
                                offset: 0x601 + timeShift,
                                type: "checksum",
                                dataType: "uint16",
                                control: {
                                  offsetStart: 0x604 + timeShift,
                                  offsetEnd: 0x680 + timeShift,
                                },
                              },
                              {
                                length: 0x0,
                                type: "container",
                                instanceType: "section",
                                instances: 11,
                                enumeration: "%o Place",
                                flex: true,
                                items: [
                                  {
                                    id: "records-name-%index%",
                                    name: "Name",
                                    offset: 0x611 + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    resource: "names",
                                    autocomplete: true,
                                  },
                                  {
                                    name: "Best Time",
                                    type: "group",
                                    mode: "time",
                                    items: [
                                      {
                                        id: "records-minutes-%index%",
                                        offset: 0x616 + timeShift,
                                        type: "variable",
                                        dataType: "uint8",
                                        max: 9,
                                      },
                                      {
                                        id: "records-seconds-%index%-0-number-1",
                                        offset: 0x614 + timeShift,
                                        type: "variable",
                                        dataType: "uint16",
                                        leadingZeros: 1,
                                        max: 59,
                                      },
                                      {
                                        id: "records-milliseconds-%index%-0-number-1",
                                        offset: 0x612 + timeShift,
                                        type: "variable",
                                        dataType: "uint16",
                                        leadingZeros: 1,
                                        max: 99,
                                      },
                                    ],
                                  },
                                ],
                              },
                              {
                                type: "section",
                                flex: true,
                                hidden: true,
                                items: [
                                  {
                                    name: "1st Place",
                                    offset: 0x605 + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "2nd Place",
                                    offset: 0x606 + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "3rd Place",
                                    offset: 0x607 + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "4th Place",
                                    offset: 0x608 + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "5th Place",
                                    offset: 0x609 + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "6th Place",
                                    offset: 0x60a + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "7th Place",
                                    offset: 0x60b + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "8th Place",
                                    offset: 0x60c + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "9th Place",
                                    offset: 0x60d + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "10th Place",
                                    offset: 0x60e + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                  {
                                    name: "11th Place",
                                    offset: 0x60f + timeShift,
                                    type: "variable",
                                    dataType: "uint8",
                                    hidden: true,
                                  },
                                ],
                              },
                            ],
                          };
                        }),
                        {
                          name: "Circuit Scores",
                          items: [
                            {
                              name: "Checksum",
                              offset: 0xe01 + scoreShift,
                              type: "checksum",
                              dataType: "uint16",
                              control: {
                                offsetStart: 0xe04 + scoreShift,
                                offsetEnd: 0xe80 + scoreShift,
                              },
                            },
                            {
                              length: 0x0,
                              type: "container",
                              instanceType: "section",
                              instances: 11,
                              enumeration: "%o Place",
                              flex: true,
                              items: [
                                {
                                  id: "records-name-%index%",
                                  name: "Name",
                                  offset: 0xe11 + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "names",
                                  autocomplete: true,
                                },
                                {
                                  id: "records-score-%index%-0-number-5",
                                  name: "Score",
                                  offset: 0xe12 + scoreShift,
                                  type: "variable",
                                  dataType: "uint32",
                                  max: 999990,
                                  step: 10,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              hidden: true,
                              items: [
                                {
                                  name: "1st Place",
                                  offset: 0xe05 + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "2nd Place",
                                  offset: 0xe06 + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "3rd Place",
                                  offset: 0xe07 + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "4th Place",
                                  offset: 0xe08 + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "5th Place",
                                  offset: 0xe09 + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "6th Place",
                                  offset: 0xe0a + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "7th Place",
                                  offset: 0xe0b + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "8th Place",
                                  offset: 0xe0c + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "9th Place",
                                  offset: 0xe0d + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "10th Place",
                                  offset: 0xe0e + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "11th Place",
                                  offset: 0xe0f + scoreShift,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                } as ItemTab;
              }),
            },
          ],
        },
      ],
      items: [
        {
          name: "Checksum",
          offset: 0x101,
          type: "checksum",
          dataType: "uint16",
          control: {
            offsetStart: 0x104,
            offsetEnd: 0x180,
          },
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "name-%index%",
                      name: "Name",
                      offset: 0x108,
                      length: 0x8,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      fallback: 0xef,
                      resource: "letters",
                      test: true,
                    },
                    {
                      name: "Championship Progression",
                      offset: 0x104,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Beaten Opponents",
                      offset: 0x105,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      id: "wins",
                      name: "Wins",
                      offset: 0x17e,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      name: "Losses",
                      offset: 0x17f,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "opponents-0",
                          name: "Minor Circuit",
                          type: "bitflags",
                          flags: [
                            { offset: 0x105, bit: 0, label: "Gabby Jay" },
                            { offset: 0x105, bit: 1, label: "Bear Hugger" },
                            { offset: 0x105, bit: 2, label: "Piston Hurricane" },
                            { offset: 0x105, bit: 3, label: "Bald Bull" },
                          ],
                        },
                        {
                          id: "opponents-1",
                          name: "Major Circuit",
                          type: "bitflags",
                          flags: [
                            { offset: 0x105, bit: 0, label: "Bob Charlie" },
                            { offset: 0x105, bit: 1, label: "Dragon Chan" },
                            { offset: 0x105, bit: 2, label: "Masked Muscle" },
                            { offset: 0x105, bit: 3, label: "Mr.Sandman" },
                          ],
                        },
                        {
                          id: "opponents-2",
                          name: "World Circuit",
                          type: "bitflags",
                          flags: [
                            { offset: 0x105, bit: 0, label: "Aran Ryan" },
                            { offset: 0x105, bit: 1, label: "Heike Kagero" },
                            { offset: 0x105, bit: 2, label: "Mad Clown" },
                            { offset: 0x105, bit: 3, label: "Super Machoman" },
                          ],
                        },
                        {
                          id: "opponents-3",
                          name: "Special Circuit",
                          type: "bitflags",
                          flags: [
                            { offset: 0x105, bit: 0, label: "Narcis Prince" },
                            { offset: 0x105, bit: 1, label: "Hoy Quarlow" },
                            { offset: 0x105, bit: 2, label: "Rick Bruiser" },
                            { offset: 0x105, bit: 3, label: "Nick Bruiser" },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Championship",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: circuits.map(
                    (circuit, circuitIndex) =>
                      ({
                        name: circuit.name,
                        items: [
                          {
                            type: "section",
                            flex: true,
                            items: [
                              ...circuit.opponents.map((opponent, index) => {
                                const shift = circuitIndex * 0x14 + index * 0x5;

                                return {
                                  name: opponent,
                                  type: "group",
                                  mode: "time",
                                  items: [
                                    {
                                      id: `circuitProgression-${circuitIndex}-minutes-${index}`,
                                      offset: 0x118 + shift,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 9,
                                    },
                                    {
                                      id: `circuitProgression-${circuitIndex}-seconds-${index}-number-1`,
                                      offset: 0x116 + shift,
                                      type: "variable",
                                      dataType: "uint16",
                                      leadingZeros: 1,
                                      max: 59,
                                    },
                                    {
                                      id: `circuitProgression-${circuitIndex}-milliseconds-${index}-number-1`,
                                      offset: 0x114 + shift,
                                      type: "variable",
                                      dataType: "uint16",
                                      leadingZeros: 1,
                                      max: 99,
                                    },
                                  ],
                                };
                              }),
                            ],
                          },
                          {
                            type: "section",
                            flex: true,
                            items: [
                              {
                                name: "Wins",
                                offset: 0x110 + circuitIndex,
                                type: "variable",
                                dataType: "upper4",
                                disabled: true,
                              },
                              {
                                id: `circuitProgression-${circuitIndex}-losses`,
                                name: "Losses",
                                offset: 0x110 + circuitIndex,
                                type: "variable",
                                dataType: "lower4",
                                max: 3,
                              },
                              {
                                id: `circuitProgression-${circuitIndex}-score-0-number-5`,
                                name: "Score",
                                offset: 0x164 + circuitIndex * 0x6,
                                type: "variable",
                                dataType: "uint32",
                                max: 999990,
                                step: 10,
                              },
                            ],
                          },
                        ],
                      }) as ItemTab,
                  ),
                },
              ],
            },
            {
              name: "Button Setting",
              flex: true,
              items: [
                {
                  name: "Right Punch",
                  offset: 0x106,
                  type: "variable",
                  dataType: "lower4",
                  resource: "buttons",
                },
                {
                  name: "Left Punch",
                  offset: 0x106,
                  type: "variable",
                  dataType: "upper4",
                  resource: "buttons",
                },
                {
                  name: "Knockout Punch",
                  offset: 0x107,
                  type: "variable",
                  dataType: "lower4",
                  resource: "buttons",
                },
                {
                  name: "Power Up",
                  offset: 0x107,
                  type: "variable",
                  dataType: "upper4",
                  resource: "buttons",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    buttons: {
      0x0: "R",
      0x1: "L",
      0x2: "X",
      0x3: "A",
      0x4: "Y",
      0x5: "B",
      0x6: "Auto",
    },
    letters: {
      0x0: "0",
      0x1: "1",
      0x2: "2",
      0x3: "3",
      0x4: "4",
      0x5: "5",
      0x6: "6",
      0x7: "7",
      0x8: "8",
      0x9: "9",
      0xa: "A",
      0xb: "B",
      0xc: "C",
      0xd: "D",
      0xe: "E",
      0xf: "F",
      0x10: "G",
      0x11: "H",
      0x12: "I",
      0x13: "J",
      0x14: "K",
      0x15: "L",
      0x16: "M",
      0x17: "N",
      0x18: "O",
      0x19: "P",
      0x1a: "Q",
      0x1b: "R",
      0x1c: "S",
      0x1d: "T",
      0x1e: "U",
      0x1f: "V",
      0x20: "W",
      0x21: "X",
      0x22: "Y",
      0x23: "Z",
      0x24: "a",
      0x25: "b",
      0x26: "c",
      0x27: "d",
      0x28: "e",
      0x29: "f",
      0x2a: "g",
      0x2b: "h",
      0x2c: "i",
      0x2d: "j",
      0x2e: "k",
      0x2f: "l",
      0x30: "m",
      0x31: "n",
      0x32: "o",
      0x33: "p",
      0x34: "q",
      0x35: "r",
      0x36: "s",
      0x37: "t",
      0x38: "u",
      0x39: "v",
      0x3a: "w",
      0x3b: "x",
      0x3c: "y",
      0x3d: "z",
      0x3e: "あ",
      0x3f: "い",
      0x40: "う",
      0x41: "え",
      0x42: "お",
      0x43: "か",
      0x44: "き",
      0x45: "く",
      0x46: "け",
      0x47: "こ",
      0x48: "さ",
      0x49: "し",
      0x4a: "す",
      0x4b: "せ",
      0x4c: "そ",
      0x4d: "た",
      0x4e: "ち",
      0x4f: "つ",
      0x50: "て",
      0x51: "と",
      0x52: "な",
      0x53: "に",
      0x54: "ぬ",
      0x55: "ね",
      0x56: "の",
      0x57: "は",
      0x58: "ひ",
      0x59: "ふ",
      0x5a: "へ",
      0x5b: "ほ",
      0x5c: "ま",
      0x5d: "み",
      0x5e: "む",
      0x5f: "め",
      0x60: "も",
      0x61: "や",
      0x62: "ゆ",
      0x63: "よ",
      0x64: "ら",
      0x65: "り",
      0x66: "る",
      0x67: "れ",
      0x68: "ろ",
      0x69: "わ",
      0x6a: "を",
      0x6b: "ん",
      0x6c: "ア",
      0x6d: "イ",
      0x6e: "ウ",
      0x6f: "エ",
      0x70: "オ",
      0x71: "カ",
      0x72: "キ",
      0x73: "ク",
      0x74: "ケ",
      0x75: "コ",
      0x76: "サ",
      0x77: "シ",
      0x78: "ス",
      0x79: "セ",
      0x7a: "ソ",
      0x7b: "タ",
      0x7c: "チ",
      0x7d: "ツ",
      0x7e: "テ",
      0x7f: "ト",
      0x80: "ナ",
      0x81: "ニ",
      0x82: "ヌ",
      0x83: "ネ",
      0x84: "ノ",
      0x85: "ハ",
      0x86: "ヒ",
      0x87: "フ",
      0x88: "ヘ",
      0x89: "ホ",
      0x8a: "マ",
      0x8b: "ミ",
      0x8c: "ム",
      0x8d: "メ",
      0x8e: "モ",
      0x8f: "ヤ",
      0x90: "ユ",
      0x91: "ヨ",
      0x92: "ラ",
      0x93: "リ",
      0x94: "ル",
      0x95: "レ",
      0x96: "ロ",
      0x97: "ワ",
      0x98: "ヲ",
      0x99: "ン",
      0x9a: "が",
      0x9b: "ぎ",
      0x9c: "ぐ",
      0x9d: "げ",
      0x9e: "ご",
      0x9f: "ざ",
      0xa0: "じ",
      0xa1: "ず",
      0xa2: "ぜ",
      0xa3: "ぞ",
      0xa4: "だ",
      0xa5: "ぢ",
      0xa6: "づ",
      0xa7: "で",
      0xa8: "ど",
      0xa9: "ば",
      0xaa: "び",
      0xab: "ぶ",
      0xac: "べ",
      0xad: "ぼ",
      0xae: "ぱ",
      0xaf: "ぴ",
      0xb0: "ぷ",
      0xb1: "ぺ",
      0xb2: "ぽ",
      0xb3: "ガ",
      0xb4: "ギ",
      0xb5: "グ",
      0xb6: "ゲ",
      0xb7: "ゴ",
      0xb8: "ザ",
      0xb9: "ジ",
      0xba: "ズ",
      0xbb: "ゼ",
      0xbc: "ゾ",
      0xbd: "ダ",
      0xbe: "ヂ",
      0xbf: "ヅ",
      0xc0: "デ",
      0xc1: "ド",
      0xc2: "バ",
      0xc3: "ビ",
      0xc4: "ブ",
      0xc5: "ベ",
      0xc6: "ボ",
      0xc7: "パ",
      0xc8: "ピ",
      0xc9: "プ",
      0xca: "ペ",
      0xcb: "ポ",
      0xcc: "ぁ",
      0xcd: "ぃ",
      0xce: "ぅ",
      0xcf: "ぇ",
      0xd0: "ぉ",
      0xd1: "ゃ",
      0xd2: "ゅ",
      0xd3: "ょ",
      0xd4: "っ",
      0xd5: "ァ",
      0xd6: "ィ",
      0xd7: "ゥ",
      0xd8: "ェ",
      0xd9: "ォ",
      0xda: "ャ",
      0xdb: "ュ",
      0xdc: "ョ",
      0xdd: "ッ",
      0xde: ",",
      0xdf: ".",
      0xe2: ":",
      0xe4: "-",
      0xe5: "~",
      0xe6: "・",
      0xe9: "?",
      0xea: "!",
      0xed: "(",
      0xee: ")",
      0xef: " ",
      0xf0: "'",
    },
    names: "getNames()",
  },
};

export default template;
