import type { GameJson } from "$lib/types";

const template: GameJson = {
  validator: {
    regions: {
      europe: { 0x0: [0x48, 0x55, 0x44, 0x53, 0x4f, 0x4e] },
      usa: { 0x0: [0x48, 0x55, 0x44, 0x53, 0x4f, 0x4e] },
      japan: { 0x0: [0x48, 0x55, 0x44, 0x53, 0x4f, 0x4e] },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      name: "Checksum",
      offset: 0x1f8,
      type: "checksum",
      dataType: "uint16",
      bigEndian: true,
      control: {
        offsetStart: 0x8,
        offsetEnd: 0x1fa,
      },
    },
    {
      type: "tabs",
      items: [
        {
          name: "General",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Title Screen Background",
                  offset: 0x4e,
                  type: "variable",
                  dataType: "uint8",
                  resource: "backgrounds",
                },
                {
                  name: "Stars",
                  offset: 0x4c,
                  type: "variable",
                  dataType: "uint16",
                  bigEndian: true,
                  max: 100,
                },
                {
                  name: "Coins",
                  offset: 0x48,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  max: 99999,
                  test: true,
                },
                {
                  name: "Coin Box",
                  offset: 0x4f,
                  type: "variable",
                  dataType: "uint8",
                  resource: "coinBoxes",
                },
                {
                  name: "Events",
                  hidden: true,
                  type: "bitflags",
                  flags: [
                    { offset: 0x50, bit: 1, label: "Game Rules Heard" },
                    { offset: 0x50, bit: 2, label: "Toad first talk" },
                    { offset: 0x50, bit: 3, label: "Bowser Note Read" },
                  ],
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Unlocked Items",
                  type: "bitflags",
                  flags: [
                    { offset: 0x53, bit: 1, label: "Plus Block" },
                    { offset: 0x53, bit: 2, label: "Minus Block" },
                    { offset: 0x53, bit: 3, label: "Speed Block" },
                    { offset: 0x53, bit: 4, label: "Slow Block" },
                    { offset: 0x53, bit: 5, label: "Warp Block" },
                    { offset: 0x53, bit: 6, label: "Event Block" },
                    { offset: 0x54, bit: 0, label: "No Koopa" },
                    { offset: 0x54, bit: 1, label: "No Boo", separator: true },
                    { offset: 0x54, bit: 2, label: "Record" },
                    { offset: 0x53, bit: 7, label: "Mecha Fly Guy" },
                    { offset: 0x54, bit: 3, label: "Talking Parot" },
                    { offset: 0x54, bit: 4, label: "Lucky Box" },
                    { offset: 0x54, bit: 5, label: "Casino Box" },
                    { offset: 0x54, bit: 6, label: "Gameballs" },
                    { offset: 0x54, bit: 7, label: "Magma Mountain" },
                    { offset: 0x55, bit: 0, label: "Credits" },
                    { offset: 0x55, bit: 1, label: "???", hidden: true },
                    { offset: 0x55, bit: 2, label: "???", hidden: true },
                    { offset: 0x55, bit: 3, label: "???", hidden: true },
                    { offset: 0x55, bit: 4, label: "???", hidden: true },
                    { offset: 0x55, bit: 5, label: "???", hidden: true },
                    { offset: 0x55, bit: 6, label: "???", hidden: true },
                    { offset: 0x55, bit: 7, label: "???", hidden: true },
                    { offset: 0x56, bit: 0, label: "???", hidden: true },
                    { offset: 0x56, bit: 1, label: "???", hidden: true },
                    { offset: 0x56, bit: 2, label: "???", hidden: true },
                    { offset: 0x56, bit: 3, label: "???", hidden: true },
                    { offset: 0x56, bit: 4, label: "???", hidden: true },
                    { offset: 0x56, bit: 5, label: "???", hidden: true },
                    { offset: 0x56, bit: 6, label: "???", hidden: true },
                    { offset: 0x56, bit: 7, label: "???", hidden: true },
                    { offset: 0x57, bit: 0, label: "???", hidden: true },
                    { offset: 0x57, bit: 1, label: "???", hidden: true },
                    { offset: 0x57, bit: 2, label: "???", hidden: true },
                    { offset: 0x57, bit: 3, label: "???", hidden: true },
                    { offset: 0x57, bit: 4, label: "???", hidden: true },
                    { offset: 0x57, bit: 5, label: "???", hidden: true },
                    { offset: 0x57, bit: 6, label: "???", hidden: true },
                    { offset: 0x57, bit: 7, label: "???", hidden: true },
                  ],
                },
                {
                  name: "Active Items",
                  type: "bitflags",
                  flags: [
                    { offset: 0x50, bit: 7, label: "Plus Block" },
                    { offset: 0x51, bit: 0, label: "Minus Block" },
                    { offset: 0x51, bit: 1, label: "Speed Block" },
                    { offset: 0x51, bit: 2, label: "Slow Block" },
                    { offset: 0x51, bit: 3, label: "Warp Block" },
                    { offset: 0x51, bit: 4, label: "Event Block" },
                    { offset: 0x51, bit: 6, label: "No Koopa" },
                    { offset: 0x51, bit: 7, label: "No Boo" },
                  ],
                },
                {
                  name: "???",
                  offset: 0xd3,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "???",
                  offset: 0x103,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "???",
                  offset: 0x133,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
              ],
            },
          ],
        },
        {
          name: "Warp Pipe",
          items: [
            {
              name: "Boards Played",
              type: "bitflags",
              hidden: true,
              flags: [
                { offset: 0x52, bit: 1, label: "DK's Jungle Adventure" },
                { offset: 0x52, bit: 2, label: "Peach's Birthday Cake" },
                { offset: 0x52, bit: 3, label: "Yoshi's Tropical Island" },
                { offset: 0x52, bit: 4, label: "Wario's Battle Canyon" },
                { offset: 0x52, bit: 5, label: "Luigi's Engine Room" },
                { offset: 0x52, bit: 6, label: "Mario's Rainbow Castle" },
                { offset: 0x52, bit: 7, label: "Bowser's Magma Mountain" },
                { offset: 0x53, bit: 0, label: "Eternal Star" },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "DK's Jungle Adventure",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Status",
                      offset: 0x28,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      disabled: true,
                      resource: "boardStatus",
                    },
                    {
                      id: "boardPlayed-0",
                      name: "Played",
                      offset: 0x28,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      binary: {
                        bitStart: 0,
                        bitLength: 15,
                      },
                      max: 999,
                    },
                    {
                      name: "Stars",
                      offset: 0x2a,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 9999,
                    },
                  ],
                },
                {
                  name: "Peach's Birthday Cake",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Status",
                      offset: 0x2c,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      disabled: true,
                      resource: "boardStatus",
                    },
                    {
                      id: "boardPlayed-1",
                      name: "Played",
                      offset: 0x2c,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      binary: {
                        bitStart: 0,
                        bitLength: 15,
                      },
                      max: 999,
                    },
                    {
                      name: "Stars",
                      offset: 0x2e,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 9999,
                    },
                  ],
                },
                {
                  name: "Yoshi's Tropical Island",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Status",
                      offset: 0x30,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      disabled: true,
                      resource: "boardStatus",
                    },
                    {
                      id: "boardPlayed-2",
                      name: "Played",
                      offset: 0x30,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      binary: {
                        bitStart: 0,
                        bitLength: 15,
                      },
                      max: 999,
                    },
                    {
                      name: "Stars",
                      offset: 0x32,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 9999,
                    },
                  ],
                },
                {
                  name: "Wario's Battle Canyon",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Status",
                      offset: 0x34,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      disabled: true,
                      resource: "boardStatus",
                    },
                    {
                      id: "boardPlayed-3",
                      name: "Played",
                      offset: 0x34,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      binary: {
                        bitStart: 0,
                        bitLength: 15,
                      },
                      max: 999,
                    },
                    {
                      name: "Stars",
                      offset: 0x36,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 9999,
                    },
                  ],
                },
                {
                  name: "Luigi's Engine Room",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Status",
                      offset: 0x38,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      disabled: true,
                      resource: "boardStatus",
                    },
                    {
                      id: "boardPlayed-4",
                      name: "Played",
                      offset: 0x38,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      binary: {
                        bitStart: 0,
                        bitLength: 15,
                      },
                      max: 999,
                    },
                    {
                      name: "Stars",
                      offset: 0x3a,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 9999,
                    },
                  ],
                },
                {
                  name: "Mario's Rainbow Castle",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Status",
                      offset: 0x3c,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      disabled: true,
                      resource: "boardStatus",
                    },
                    {
                      id: "boardPlayed-5",
                      name: "Played",
                      offset: 0x3c,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      binary: {
                        bitStart: 0,
                        bitLength: 15,
                      },
                      max: 999,
                    },
                    {
                      name: "Stars",
                      offset: 0x3e,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 9999,
                    },
                  ],
                },
                {
                  name: "Bowser's Magma Mountain",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Status",
                      offset: 0x40,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      resource: "boardStatus",
                    },
                    {
                      id: "boardPlayed-6",
                      name: "Played",
                      offset: 0x40,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      binary: {
                        bitStart: 0,
                        bitLength: 15,
                      },
                      max: 999,
                    },
                    {
                      name: "Stars",
                      offset: 0x42,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 9999,
                    },
                  ],
                },
                {
                  name: "Eternal Star",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Status",
                      offset: 0x44,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      resource: "boardStatus",
                    },
                    {
                      id: "boardPlayed-7",
                      name: "Played",
                      offset: 0x44,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      binary: {
                        bitStart: 0,
                        bitLength: 15,
                      },
                      max: 999,
                    },
                    {
                      name: "Stars",
                      offset: 0x46,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      max: 9999,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Mini-Game House",
          flex: true,
          items: [
            {
              type: "tabs",
              vertical: true,
              items: [
                {
                  name: "4-Player Games",
                  flex: true,
                  items: [
                    {
                      name: "Played",
                      type: "bitflags",
                      flags: [
                        { offset: 0x1a, bit: 3, label: "Buried Treasure" },
                        { offset: 0x1a, bit: 4, label: "Treasure Divers" },
                        { offset: 0x1a, bit: 7, label: "Hot Bob-omb" },
                        { offset: 0x1b, bit: 3, label: "Musical Mushroom" },
                        { offset: 0x1b, bit: 5, label: "Crazy Cutter" },
                        { offset: 0x1b, bit: 6, label: "Face Lift" },
                        { offset: 0x1c, bit: 3, label: "Balloon Burst" },
                        { offset: 0x1c, bit: 4, label: "Coin Block Blitz" },
                        { offset: 0x1c, bit: 6, label: "Skateboard Scamper" },
                        { offset: 0x1c, bit: 7, label: "Box Mountain Mayhem", separator: true },
                        { offset: 0x1d, bit: 0, label: "Platform Peril" },
                        { offset: 0x1d, bit: 2, label: "Mushroom Mix-Up" },
                        { offset: 0x1d, bit: 4, label: "Grab Bag" },
                        { offset: 0x1d, bit: 6, label: "Bumber Balls" },
                        { offset: 0x1e, bit: 1, label: "Tipsy Tourney" },
                        { offset: 0x1e, bit: 2, label: "Bombs Away" },
                        { offset: 0x1e, bit: 6, label: "Mario Bandstand" },
                        { offset: 0x1f, bit: 0, label: "Shy Guy Says" },
                        { offset: 0x1f, bit: 3, label: "Cast Aways" },
                        { offset: 0x1f, bit: 4, label: "Key-pa-Way", separator: true },
                        { offset: 0x1f, bit: 5, label: "Running of the Bulb" },
                        { offset: 0x1f, bit: 6, label: "Hot Rope Jump" },
                        { offset: 0x20, bit: 7, label: "Hammer Drop" },
                        { offset: 0x1a, bit: 6, label: "Slot Car Derby 1" },
                        { offset: 0x1b, bit: 0, label: "Slot Car Derby 2" },
                      ],
                    },
                    {
                      name: "Bought",
                      type: "bitflags",
                      flags: [
                        { offset: 0x21, bit: 3, label: "Buried Treasure" },
                        { offset: 0x21, bit: 4, label: "Treasure Divers" },
                        { offset: 0x21, bit: 7, label: "Hot Bob-omb" },
                        { offset: 0x22, bit: 3, label: "Musical Mushroom" },
                        { offset: 0x22, bit: 5, label: "Crazy Cutter" },
                        { offset: 0x22, bit: 6, label: "Face Lift" },
                        { offset: 0x23, bit: 3, label: "Balloon Burst" },
                        { offset: 0x23, bit: 4, label: "Coin Block Blitz" },
                        { offset: 0x23, bit: 6, label: "Skateboard Scamper" },
                        { offset: 0x23, bit: 7, label: "Box Mountain Mayhem", separator: true },
                        { offset: 0x24, bit: 0, label: "Platform Peril" },
                        { offset: 0x24, bit: 2, label: "Mushroom Mix-Up" },
                        { offset: 0x24, bit: 4, label: "Grab Bag" },
                        { offset: 0x24, bit: 6, label: "Bumber Balls" },
                        { offset: 0x25, bit: 1, label: "Tipsy Tourney" },
                        { offset: 0x25, bit: 2, label: "Bombs Away" },
                        { offset: 0x25, bit: 6, label: "Mario Bandstand" },
                        { offset: 0x26, bit: 0, label: "Shy Guy Says" },
                        { offset: 0x26, bit: 3, label: "Cast Aways" },
                        { offset: 0x26, bit: 4, label: "Key-pa-Way", separator: true },
                        { offset: 0x26, bit: 5, label: "Running of the Bulb" },
                        { offset: 0x26, bit: 6, label: "Hot Rope Jump" },
                        { offset: 0x27, bit: 7, label: "Hammer Drop" },
                        { offset: 0x21, bit: 6, label: "Slot Car Derby 1" },
                        { offset: 0x22, bit: 0, label: "Slot Car Derby 2" },
                      ],
                    },
                  ],
                },
                {
                  name: "1 vs. 3 Player Games",
                  flex: true,
                  items: [
                    {
                      name: "Played",
                      type: "bitflags",
                      flags: [
                        { offset: 0x1b, bit: 1, label: "Pipe Maze" },
                        { offset: 0x1c, bit: 0, label: "Bash 'n' Cash" },
                        { offset: 0x1c, bit: 1, label: "Bowl Over" },
                        { offset: 0x1c, bit: 5, label: "Coin Block Bash" },
                        { offset: 0x1d, bit: 7, label: "TightRope Treachery" },
                        { offset: 0x1e, bit: 3, label: "Crane Game" },
                        { offset: 0x20, bit: 2, label: "Piranha's Pursuit" },
                        { offset: 0x20, bit: 3, label: "Tug o' War" },
                        { offset: 0x20, bit: 4, label: "Paddle Battle" },
                        { offset: 0x20, bit: 6, label: "Coin Shower Flower" },
                      ],
                    },
                    {
                      name: "Bought",
                      type: "bitflags",
                      flags: [
                        { offset: 0x22, bit: 1, label: "Pipe Maze" },
                        { offset: 0x23, bit: 0, label: "Bash 'n' Cash" },
                        { offset: 0x23, bit: 1, label: "Bowl Over" },
                        { offset: 0x23, bit: 5, label: "Coin Block Bash" },
                        { offset: 0x24, bit: 7, label: "TightRope Treachery" },
                        { offset: 0x25, bit: 3, label: "Crane Game" },
                        { offset: 0x27, bit: 2, label: "Piranha's Pursuit" },
                        { offset: 0x27, bit: 3, label: "Tug o' War" },
                        { offset: 0x27, bit: 4, label: "Paddle Battle" },
                        { offset: 0x27, bit: 6, label: "Coin Shower Flower" },
                      ],
                    },
                  ],
                },
                {
                  name: "2 vs. 2 Player Games",
                  flex: true,
                  items: [
                    {
                      name: "Played",
                      type: "bitflags",
                      flags: [
                        { offset: 0x1d, bit: 5, label: "Bobsled Run" },
                        { offset: 0x1e, bit: 7, label: "Desert Dash" },
                        { offset: 0x1f, bit: 2, label: "Bombsketball" },
                        { offset: 0x1f, bit: 7, label: "Handcar Havoc" },
                        { offset: 0x20, bit: 1, label: "Deep Sea Divers" },
                      ],
                    },
                    {
                      name: "Bought",
                      type: "bitflags",
                      flags: [
                        { offset: 0x24, bit: 5, label: "Bobsled Run" },
                        { offset: 0x25, bit: 7, label: "Desert Dash" },
                        { offset: 0x26, bit: 2, label: "Bombsketball" },
                        { offset: 0x26, bit: 7, label: "Handcar Havoc" },
                        { offset: 0x27, bit: 1, label: "Deep Sea Divers" },
                      ],
                    },
                  ],
                },
                {
                  name: "1-Player Games",
                  flex: true,
                  items: [
                    {
                      name: "Played",
                      type: "bitflags",
                      flags: [
                        { offset: 0x1a, bit: 0, label: "Memory Match" },
                        { offset: 0x1a, bit: 2, label: "Slot Machine" },
                        { offset: 0x1a, bit: 5, label: "Shell Game" },
                        { offset: 0x1b, bit: 2, label: "Ghost Guess" },
                        { offset: 0x1b, bit: 4, label: "Pedal Power" },
                        { offset: 0x1b, bit: 7, label: "Whack-a-Plant" },
                        { offset: 0x1c, bit: 2, label: "Ground Pound" },
                        { offset: 0x1d, bit: 1, label: "Teetering Towers" },
                        { offset: 0x1e, bit: 0, label: "Knock Block Tower" },
                        { offset: 0x1f, bit: 1, label: "Limbo Dance" },
                        { offset: 0x1d, bit: 3, label: "Bumber Ball Maze 1" },
                        { offset: 0x1e, bit: 4, label: "Bumber Ball Maze 2" },
                        { offset: 0x20, bit: 5, label: "Bumber Ball Maze 3" },
                        { offset: 0x1e, bit: 5, label: "???", hidden: true },
                      ],
                    },
                    {
                      name: "Bought",
                      type: "bitflags",
                      flags: [
                        { offset: 0x21, bit: 0, label: "Memory Match" },
                        { offset: 0x21, bit: 2, label: "Slot Machine" },
                        { offset: 0x21, bit: 5, label: "Shell Game" },
                        { offset: 0x22, bit: 2, label: "Ghost Guess" },
                        { offset: 0x22, bit: 4, label: "Pedal Power" },
                        { offset: 0x22, bit: 7, label: "Whack-a-Plant" },
                        { offset: 0x23, bit: 2, label: "Ground Pound" },
                        { offset: 0x24, bit: 1, label: "Teetering Towers" },
                        { offset: 0x25, bit: 0, label: "Knock Block Tower" },
                        { offset: 0x26, bit: 1, label: "Limbo Dance" },
                        { offset: 0x24, bit: 3, label: "Bumber Ball Maze 1" },
                        { offset: 0x25, bit: 4, label: "Bumber Ball Maze 2" },
                        { offset: 0x27, bit: 5, label: "Bumber Ball Maze 3" },
                        { offset: 0x25, bit: 5, label: "???", hidden: true },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Mini-Game Island",
          items: [
            {
              type: "tabs",
              vertical: true,
              items: [
                {
                  name: "General",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Player Character",
                          offset: 0x182,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                        },
                        {
                          name: "Computer Character",
                          offset: 0x183,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                        },
                        {
                          name: "Map",
                          offset: 0x184,
                          type: "variable",
                          dataType: "uint8",
                          hidden: true,
                        },
                        {
                          name: "Lifes",
                          offset: 0x185,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Coins",
                          offset: 0x18e,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          name: "Position",
                          offset: 0x18f,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          hidden: true,
                        },
                        {
                          id: "koopaTroopaSpace",
                          name: "Koopa Troopa Space",
                          offset: 0x18f,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          resource: "koopaTroopaSpaces",
                        },
                      ],
                    },
                    {
                      name: "Events",
                      hidden: true,
                      type: "bitflags",
                      flags: [
                        { offset: 0x186, bit: 0, label: "Initialized" },
                        { offset: 0x186, bit: 1, label: "???", hidden: true },
                        { offset: 0x186, bit: 3, label: "A Game Played" },
                        { offset: 0x186, bit: 6, label: "???", hidden: true },
                      ],
                    },
                  ],
                },
                {
                  name: "Cleared Mini-Games",
                  flex: true,
                  items: [
                    {
                      name: "World 1",
                      type: "bitflags",
                      flags: [
                        { offset: 0x186, bit: 7, label: "World 1-1" },
                        { offset: 0x187, bit: 0, label: "World 1-2" },
                        { offset: 0x187, bit: 1, label: "World 1-3" },
                        { offset: 0x187, bit: 2, label: "World 1-4" },
                      ],
                    },
                    {
                      name: "World 2",
                      type: "bitflags",
                      flags: [
                        { offset: 0x187, bit: 3, label: "World 2-1" },
                        { offset: 0x187, bit: 4, label: "World 2-2" },
                        { offset: 0x187, bit: 5, label: "World 2-3" },
                        { offset: 0x187, bit: 6, label: "World 2-4" },
                        { offset: 0x187, bit: 7, label: "World 2-5" },
                      ],
                    },
                    {
                      name: "World 3",
                      type: "bitflags",
                      flags: [
                        { offset: 0x188, bit: 0, label: "World 3-1" },
                        { offset: 0x188, bit: 1, label: "World 3-2" },
                        { offset: 0x188, bit: 2, label: "World 3-3" },
                        { offset: 0x188, bit: 3, label: "World 3-4" },
                        { offset: 0x188, bit: 4, label: "World 3-5" },
                      ],
                    },
                    {
                      name: "World 4",
                      type: "bitflags",
                      flags: [
                        { offset: 0x188, bit: 5, label: "World 4-1" },
                        { offset: 0x188, bit: 6, label: "World 4-2" },
                        { offset: 0x188, bit: 7, label: "World 4-3" },
                        { offset: 0x189, bit: 0, label: "World 4-4" },
                      ],
                    },
                    {
                      name: "World 5",
                      type: "bitflags",
                      flags: [
                        { offset: 0x189, bit: 1, label: "World 5-1" },
                        { offset: 0x189, bit: 2, label: "World 5-2" },
                        { offset: 0x189, bit: 3, label: "World 5-3" },
                        { offset: 0x189, bit: 4, label: "World 5-4" },
                        { offset: 0x189, bit: 5, label: "World 5-5" },
                        { offset: 0x189, bit: 6, label: "World 5-6" },
                        { offset: 0x189, bit: 7, label: "World 5-7" },
                        { offset: 0x18a, bit: 0, label: "World 5-8" },
                      ],
                    },
                    {
                      name: "World 6",
                      type: "bitflags",
                      flags: [
                        { offset: 0x18a, bit: 1, label: "World 6-1" },
                        { offset: 0x18a, bit: 2, label: "World 6-2" },
                        { offset: 0x18a, bit: 3, label: "World 6-3" },
                        { offset: 0x18a, bit: 4, label: "World 6-4" },
                        { offset: 0x18a, bit: 5, label: "World 6-5" },
                        { offset: 0x18a, bit: 6, label: "World 6-6" },
                      ],
                    },
                    {
                      name: "World 7",
                      type: "bitflags",
                      flags: [
                        { offset: 0x18a, bit: 7, label: "World 7-1" },
                        { offset: 0x18b, bit: 0, label: "World 7-2" },
                        { offset: 0x18b, bit: 1, label: "World 7-3" },
                        { offset: 0x18b, bit: 2, label: "World 7-4" },
                        { offset: 0x18b, bit: 3, label: "World 7-5" },
                        { offset: 0x18b, bit: 4, label: "World 7-6" },
                      ],
                    },
                    {
                      name: "World 8",
                      type: "bitflags",
                      flags: [
                        { offset: 0x18b, bit: 5, label: "World 8-1" },
                        { offset: 0x18b, bit: 6, label: "World 8-2" },
                        { offset: 0x18b, bit: 7, label: "World 8-3" },
                        { offset: 0x18c, bit: 0, label: "World 8-4" },
                        { offset: 0x18c, bit: 1, label: "World 8-5" },
                        { offset: 0x18c, bit: 2, label: "World 8-6" },
                      ],
                    },
                    {
                      name: "World 9",
                      type: "bitflags",
                      flags: [
                        { offset: 0x18c, bit: 3, label: "World 9-1" },
                        { offset: 0x18c, bit: 4, label: "World 9-2" },
                        { offset: 0x18c, bit: 5, label: "World 9-3" },
                        { offset: 0x18c, bit: 6, label: "World 9-4" },
                        { offset: 0x18c, bit: 7, label: "World 9-5" },
                        { offset: 0x18d, bit: 0, label: "Goal Space" },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Records",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Mecha Fly Guy",
                  type: "group",
                  mode: "chrono",
                  items: [
                    {
                      id: "time-25",
                      offset: 0x12,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 25 },
                        {
                          convert: {
                            from: "seconds",
                            to: "minutes",
                          },
                        },
                      ],
                      max: 9,
                    },
                    {
                      id: "time-25",
                      offset: 0x12,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 25 },
                        {
                          convert: {
                            from: "seconds",
                            to: "seconds",
                          },
                        },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      id: "time-25",
                      offset: 0x12,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 25 },
                        {
                          convert: {
                            from: "seconds",
                            to: "milliseconds",
                          },
                        },
                      ],
                      leadingZeros: 2,
                      max: 999,
                      step: 100,
                    },
                  ],
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Slot Car Derby 1",
                  type: "group",
                  mode: "chrono",
                  items: [
                    {
                      id: "time-25",
                      offset: 0xc,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 25 },
                        {
                          convert: {
                            from: "seconds",
                            to: "minutes",
                          },
                        },
                      ],
                      max: 9,
                    },
                    {
                      id: "time-25",
                      offset: 0xc,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 25 },
                        {
                          convert: {
                            from: "seconds",
                            to: "seconds",
                          },
                        },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      id: "time-25",
                      offset: 0xc,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 25 },
                        {
                          convert: {
                            from: "seconds",
                            to: "milliseconds",
                          },
                        },
                      ],
                      leadingZeros: 2,
                      max: 999,
                      step: 100,
                    },
                  ],
                },
                {
                  name: "Slot Car Derby 2",
                  type: "group",
                  mode: "chrono",
                  items: [
                    {
                      id: "time-25",
                      offset: 0xe,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 25 },
                        {
                          convert: {
                            from: "seconds",
                            to: "minutes",
                          },
                        },
                      ],
                      max: 9,
                    },
                    {
                      id: "time-25",
                      offset: 0xe,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 25 },
                        {
                          convert: {
                            from: "seconds",
                            to: "seconds",
                          },
                        },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      id: "time-25",
                      offset: 0xe,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 25 },
                        {
                          convert: {
                            from: "seconds",
                            to: "milliseconds",
                          },
                        },
                      ],
                      leadingZeros: 2,
                      max: 999,
                      step: 100,
                    },
                  ],
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Bobsled Run",
                  type: "group",
                  mode: "chrono",
                  items: [
                    {
                      id: "time-50",
                      offset: 0xa,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "minutes",
                          },
                        },
                      ],
                      max: 9,
                    },
                    {
                      id: "time-50",
                      offset: 0xa,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "seconds",
                          },
                        },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      id: "time-50",
                      offset: 0xa,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "milliseconds",
                          },
                        },
                      ],
                      leadingZeros: 2,
                      max: 999,
                      step: 100,
                    },
                  ],
                },
                {
                  name: "Handcar Havoc",
                  type: "group",
                  mode: "chrono",
                  items: [
                    {
                      id: "time-50",
                      offset: 0x10,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "minutes",
                          },
                        },
                      ],
                      max: 9,
                    },
                    {
                      id: "time-50",
                      offset: 0x10,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "seconds",
                          },
                        },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      id: "time-50",
                      offset: 0x10,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "milliseconds",
                          },
                        },
                      ],
                      leadingZeros: 2,
                      max: 999,
                      step: 100,
                    },
                  ],
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Bumber Ball Maze 1",
                  type: "group",
                  mode: "chrono",
                  items: [
                    {
                      id: "time-50",
                      offset: 0x14,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "minutes",
                          },
                        },
                      ],
                      max: 9,
                    },
                    {
                      id: "time-50",
                      offset: 0x14,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "seconds",
                          },
                        },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      id: "time-50",
                      offset: 0x14,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "milliseconds",
                          },
                        },
                      ],
                      leadingZeros: 2,
                      max: 999,
                      step: 100,
                    },
                  ],
                },
                {
                  name: "Bumber Ball Maze 2",
                  type: "group",
                  mode: "chrono",
                  items: [
                    {
                      id: "time-50",
                      offset: 0x16,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "minutes",
                          },
                        },
                      ],
                      max: 9,
                    },
                    {
                      id: "time-50",
                      offset: 0x16,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "seconds",
                          },
                        },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      id: "time-50",
                      offset: 0x16,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "milliseconds",
                          },
                        },
                      ],
                      leadingZeros: 2,
                      max: 999,
                      step: 100,
                    },
                  ],
                },
                {
                  name: "Bumber Ball Maze 3",
                  type: "group",
                  mode: "chrono",
                  items: [
                    {
                      id: "time-50",
                      offset: 0x18,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "minutes",
                          },
                        },
                      ],
                      max: 9,
                    },
                    {
                      id: "time-50",
                      offset: 0x18,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "seconds",
                          },
                        },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      id: "time-50",
                      offset: 0x18,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      operations: [
                        { "/": 50 },
                        {
                          convert: {
                            from: "seconds",
                            to: "milliseconds",
                          },
                        },
                      ],
                      leadingZeros: 2,
                      max: 999,
                      step: 100,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Option House",
          flex: true,
          items: [
            {
              id: "language",
              name: "Language",
              offset: 0x9,
              type: "variable",
              dataType: "uint8",
              resource: "languages",
              test: true,
            },
            {
              name: "Sound Settings",
              offset: 0x52,
              type: "variable",
              dataType: "bit",
              bit: 0,
              resource: "sounds",
            },
          ],
        },
      ],
    },
  ],
  resources: {
    backgrounds: {
      0x0: "Flying Mario",
      0x1: "Luigi's Engine Room",
      0x2: "Birthday Cake",
      0x3: "Beach Volleyball",
      0x4: "Bob-omb War",
      0x5: "Jungle",
      0xff: "Initial",
    },
    boardStatus: {
      0x0: "-",
      0x1: "Unlocked",
    },
    characters: {
      0x0: "Mario",
      0x1: "Luigi",
      0x2: "Peach",
      0x3: "Yoshi",
      0x4: "Wario",
      0x5: "DK",
    },
    coinBoxes: {
      0x0: "Coin Box",
      0x1: "Lucky Box",
      0x2: "Casino Box",
    },
    koopaTroopaSpaces: {
      0x0: "-",
      0x100: "World 1",
      0x105: "World 2",
      0x10b: "World 3",
      0x205: "World 4",
      0x301: "World 6",
      0x501: "World 9",
      0x507: "Goal Space",
      0x30001: "World 7",
      0x40001: "World 8",
    },
    languages: [
      // Europe
      {
        0x0: "-",
        0x2: "English",
        0x3: "French",
        0x4: "German",
      },
      // USA
      {
        0x0: "English",
      },
      // Japan
      {
        0x0: "Japanese",
      },
    ],
    sounds: {
      0x0: "Mono",
      0x1: "Stereo",
    },
  },
  resourcesOrder: {
    backgrounds: [0xff],
    koopaTroopaSpaces: [
      0x0, 0x100, 0x105, 0x10b, 0x205, 0x301, 0x30001, 0x40001, 0x501, 0x507,
    ],
  },
};

export default template;
