export const enemies = [
  { index: 0x0, name: "001 Bat", drops: [false, false] },
  { index: 0x1, name: "002 Zombie", drops: [true, true] },
  { index: 0x2, name: "003 Skeleton", drops: [false, false] },
  { index: 0x3, name: "004 Merman", drops: [false, false] },
  { index: 0x4, name: "005 Axe Armor", drops: [true, false] },
  { index: 0x5, name: "006 Skull Archer", drops: [false, false] },
  { index: 0x6, name: "007 Peeping Eye", drops: [false, false] },
  { index: 0x7, name: "008 Killer Fish", drops: [false, true] },
  { index: 0x8, name: "009 Bone Pillar", drops: [false, true] },
  { index: 0x9, name: "010 Blue Crow", drops: [false, false] },
  { index: 0xa, name: "011 Buer", drops: [false, false] },
  { index: 0xb, name: "012 White Dragon", drops: [false, false] },
  { index: 0xc, name: "013 Zombie Soldier", drops: [true, true] },
  { index: 0xd, name: "014 Skeleton Knight", drops: [true, false] },
  { index: 0xe, name: "015 Ghost", drops: [false, false] },
  { index: 0xf, name: "016 Siren", drops: [false, false] },
  { index: 0x10, name: "017 Tiny Devil", drops: [false, true] },
  { index: 0x11, name: "018 Durga", drops: [true, true] },
  { index: 0x12, name: "019 Rock Armor", drops: [true, true] },
  { index: 0x13, name: "020 Giant Ghost", drops: [false, false] },
  { index: 0x14, name: "021 Winged Skeleton", drops: [true, false] },
  { index: 0x15, name: "022 Minotaur", drops: [true, true] },
  { index: 0x16, name: "023 Student Witch", drops: [true, true] },
  { index: 0x17, name: "024 Arachne", drops: [true, false] },
  { index: 0x18, name: "025 Fleaman", drops: [false, true] },
  { index: 0x19, name: "026 Evil Butcher", drops: [true, true] },
  { index: 0x1a, name: "027 Quezlcoatl", drops: [false, true] },
  { index: 0x1b, name: "028 Ectoplasm", drops: [true, false] },
  { index: 0x1c, name: "029 Catoblepas", drops: [false, true] },
  { index: 0x1d, name: "030 Ghost Dancer", drops: [false, true] },
  { index: 0x1e, name: "031 Waiter Skeleton", drops: [false, true] },
  { index: 0x1f, name: "032 Killer Doll", drops: [false, false] },
  { index: 0x20, name: "033 Zombie Officier", drops: [true, true] },
  { index: 0x21, name: "034 Creaking Skill", drops: [false, false] },
  { index: 0x22, name: "035 Wooden Golem", drops: [false, true] },
  { index: 0x23, name: "036 Tsuchinoko", drops: [false, false] },
  { index: 0x24, name: "037 Persephone", drops: [true, true] },
  { index: 0x25, name: "038 Lilith", drops: [true, false] },
  { index: 0x26, name: "039 Nemesis", drops: [false, false] },
  { index: 0x27, name: "040 Kyoma Demon", drops: [false, false] },
  { index: 0x28, name: "041 Chronomage", drops: [true, false] },
  { index: 0x29, name: "042 Valkyrie", drops: [true, true] },
  { index: 0x2a, name: "043 Witch", drops: [true, true] },
  { index: 0x2b, name: "044 Curly", drops: [true, true] },
  { index: 0x2c, name: "045 Altair", drops: [false, false] },
  { index: 0x2d, name: "046 Red Crow", drops: [false, false] },
  { index: 0x2e, name: "047 Cockatrice", drops: [false, true] },
  { index: 0x2f, name: "048 Dead Warrior", drops: [false, true] },
  { index: 0x30, name: "049 Devil", drops: [true, true] },
  { index: 0x31, name: "050 Imp", drops: [true, false] },
  { index: 0x32, name: "051 Werewolf", drops: [true, true] },
  { index: 0x33, name: "052 Gorgon", drops: [true, true] },
  { index: 0x34, name: "053 Disc Armor", drops: [true, false] },
  { index: 0x35, name: "054 Golem", drops: [false, true] },
  { index: 0x36, name: "055 Manticore", drops: [false, true] },
  { index: 0x37, name: "056 Gremlin", drops: [false, false] },
  { index: 0x38, name: "057 Harpy", drops: [false, false] },
  { index: 0x39, name: "058 Medusa Head", drops: [false, false] },
  { index: 0x3a, name: "059 Bomber Armor", drops: [true, false] },
  { index: 0x3b, name: "060 Lightning Doll", drops: [false, false] },
  { index: 0x3c, name: "061 Great Armor", drops: [true, true] },
  { index: 0x3d, name: "062 Une", drops: [false, false] },
  { index: 0x3e, name: "063 Giant Worm", drops: [false, true] },
  { index: 0x3f, name: "064 Needles", drops: [false, true] },
  { index: 0x40, name: "065 Man-Eater", drops: [false, true] },
  { index: 0x41, name: "066 Fish Head", drops: [false, false] },
  { index: 0x42, name: "067 Nightmare", drops: [true, false] },
  { index: 0x43, name: "068 Triton", drops: [true, true] },
  { index: 0x44, name: "069 Slime", drops: [false, false] },
  { index: 0x45, name: "070 Big Golem", drops: [false, true] },
  { index: 0x46, name: "071 Dryad", drops: [true, true] },
  { index: 0x47, name: "072 Poison Worm", drops: [true, false] },
  { index: 0x48, name: "073 Arc Demon", drops: [false, true] },
  { index: 0x49, name: "074 Cagnazzo", drops: [true, true] },
  { index: 0x4a, name: "075 Ripper", drops: [true, false] },
  { index: 0x4b, name: "076 Werejaguar", drops: [true, false] },
  { index: 0x4c, name: "077 Ukoback", drops: [false, false] },
  { index: 0x4d, name: "078 Alura Une", drops: [false, true] },
  { index: 0x4e, name: "079 Biphron", drops: [false, false] },
  { index: 0x4f, name: "080 Mandragora", drops: [false, false] },
  { index: 0x50, name: "081 Flesh Golem", drops: [true, true] },
  { index: 0x51, name: "082 Sky Fish", drops: [false, false] },
  { index: 0x52, name: "083 Dead Crusader", drops: [true, true] },
  { index: 0x53, name: "084 Kicker Skeleton", drops: [true, true] },
  { index: 0x54, name: "085 Weretiger", drops: [true, false] },
  { index: 0x55, name: "086 Killer Mantle", drops: [false, true] },
  { index: 0x56, name: "087 Mudman", drops: [false, false] },
  { index: 0x57, name: "088 Gargoyle", drops: [false, false] },
  { index: 0x58, name: "089 Red Minotaur", drops: [true, true] },
  { index: 0x59, name: "090 Beam Skeleton", drops: [false, false] },
  { index: 0x5a, name: "091 Alastor", drops: [false, false] },
  { index: 0x5b, name: "092 Skull Millione", drops: [true, true] },
  { index: 0x5c, name: "093 Giant Skeleton", drops: [false, true] },
  { index: 0x5d, name: "094 Gladiator", drops: [false, false] },
  { index: 0x5e, name: "095 Bael", drops: [false, false] },
  { index: 0x5f, name: "096 Succubus", drops: [true, true] },
  { index: 0x60, name: "097 Mimic", drops: [false, false] },
  { index: 0x61, name: "098 Stolas", drops: [false, true] },
  { index: 0x62, name: "099 Erinys", drops: [false, true] },
  { index: 0x63, name: "100 Lubicant", drops: [false, true] },
  { index: 0x64, name: "101 Basilisk", drops: [false, true] },
  { index: 0x65, name: "102 Iron Golem", drops: [false, false] },
  { index: 0x66, name: "103 Demon Lord", drops: [true, true] },
  { index: 0x67, name: "104 Final Guard", drops: [true, true] },
  { index: 0x68, name: "105 Flame Demon", drops: [false, true] },
  { index: 0x69, name: "106 Shadow Knight", drops: [false, true] },
  { index: 0x6a, name: "107 Head Hunter", drops: [false, false] },
  { index: 0x6b, name: "108 Death", drops: [false, false] },
  { index: 0x6c, name: "109 Legion", drops: [false, false] },
  { index: 0x6d, name: "110 Balore", drops: [false, false] },
  { index: 0x6e, name: "111 Belmont", drops: [false, false] },
  { index: 0x6f, name: "112 Graham", drops: [false, false] },
];
