import type { GameJson } from "$lib/types";

import { pokemonStatsFragment } from "./utils/fragment";
import {
  items,
  itemsGroups,
  itemsOrder,
  moves,
  pokemonList,
  pokemons,
  pokemonsOrder,
} from "./utils/resource";

const template: GameJson = {
  validator: {
    platforms: {
      gameboy: {
        europe_usa_france_germany_italy_spain: {},
        japan: {},
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      type: "section",
      flex: true,
      hidden: true,
      items: [
        {
          id: "checksum",
          name: "Checksum",
          offset: 0x3523,
          type: "checksum",
          dataType: "uint8",
          control: {
            offsetStart: 0x2598,
            offsetEnd: 0x3523,
          },
        },
        {
          id: "checksumBoxes",
          name: "Checksum Boxes 1-6",
          offset: 0x5a4c,
          type: "checksum",
          dataType: "uint8",
          control: {
            offsetStart: 0x4000,
            offsetEnd: 0x5a4c,
          },
        },
        {
          id: "checksumBoxes",
          name: "Checksum Boxes 6-12",
          offset: 0x7a4c,
          type: "checksum",
          dataType: "uint8",
          control: {
            offsetStart: 0x6000,
            offsetEnd: 0x7a4c,
          },
        },
      ],
    },
    {
      type: "tabs",
      onTabChange: "onMainTabChange(%d)",
      items: [
        {
          name: "General",
          items: [
            {
              type: "tabs",
              vertical: true,
              items: [
                {
                  name: "General",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "name-trainerName",
                          name: "Trainer Name",
                          offset: 0x2598,
                          length: 0x7,
                          type: "variable",
                          dataType: "string",
                          letterDataType: "uint8",
                          fallback: 0x7f,
                          endCode: 0x50,
                          resource: "letters",
                          test: true,
                        },
                        {
                          name: "No ID",
                          offset: 0x2605,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                        },
                        {
                          id: "name-japanShift",
                          name: "Rival Name",
                          offset: 0x25f6,
                          length: 0x7,
                          type: "variable",
                          dataType: "string",
                          letterDataType: "uint8",
                          fallback: 0x7f,
                          endCode: 0x50,
                          resource: "letters",
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "badges",
                          name: "Badges",
                          offset: 0x2602,
                          type: "variable",
                          dataType: "uint8",
                          disabled: true,
                        },
                        {
                          id: "ownedPokemon-japanShift",
                          name: "Owned Pokémon",
                          offset: 0x25a3,
                          type: "variable",
                          dataType: "uint8",
                          disabled: true,
                        },
                        {
                          name: "Playtime",
                          type: "group",
                          mode: "time",
                          items: [
                            {
                              offset: 0x2ced,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              offset: 0x2cef,
                              type: "variable",
                              dataType: "uint8",
                              leadingZeros: 1,
                              max: 59,
                            },
                            {
                              offset: 0x2cf0,
                              type: "variable",
                              dataType: "uint8",
                              leadingZeros: 1,
                              max: 59,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "japanShift",
                          name: "Money",
                          offset: 0x25f3,
                          type: "variable",
                          dataType: "uint24",
                          bigEndian: true,
                          binaryCodedDecimal: true,
                        },
                        {
                          name: "Casino Coins",
                          offset: 0x2850,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          binaryCodedDecimal: true,
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "yellowOnly",
                          name: "Pikachu's Friendship",
                          offset: 0x271c,
                          type: "variable",
                          dataType: "uint8",
                        },
                        {
                          id: "isYellowVersion",
                          name: "Is Yellow Version",
                          offset: 0x271d,
                          type: "variable",
                          dataType: "uint8",
                          hidden: true,
                        },
                        {
                          id: "currentBox",
                          name: "Current Box",
                          offset: 0x284c,
                          type: "variable",
                          dataType: "uint8",
                          binary: { bitStart: 0, bitLength: 7 },
                          operations: [{ "+": 1 }],
                          hidden: true,
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Badges",
                  items: [
                    {
                      type: "bitflags",
                      flags: [
                        { offset: 0x2602, bit: 0, label: "Boulder Badge" },
                        { offset: 0x2602, bit: 1, label: "Cascade Badge" },
                        { offset: 0x2602, bit: 2, label: "Thunder Badge" },
                        { offset: 0x2602, bit: 3, label: "Rainbow Badge" },
                        { offset: 0x2602, bit: 4, label: "Soul Badge" },
                        { offset: 0x2602, bit: 5, label: "Marsh Badge" },
                        { offset: 0x2602, bit: 6, label: "Volcano Badge" },
                        { offset: 0x2602, bit: 7, label: "Earth Badge" },
                      ],
                    },
                  ],
                },
                {
                  name: "Pokédex",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Pokédex",
                          offset: 0x29f7,
                          type: "variable",
                          dataType: "bit",
                          bit: 5,
                          resource: "booleanObtained",
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "japanShift",
                          name: "Seen",
                          type: "bitflags",
                          flags: pokemonList.map((pokemon, index) => ({
                            offset: Math.floor(0x25b6 + index / 0x8),
                            bit: index % 8,
                            label: pokemon.name,
                          })),
                        },
                        {
                          id: "japanShift",
                          name: "Owned",
                          type: "bitflags",
                          flags: pokemonList.map((pokemon, index) => ({
                            offset: Math.floor(0x25a3 + index / 0x8),
                            bit: index % 8,
                            label: pokemon.name,
                          })),
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Visited Places",
                  items: [
                    {
                      type: "bitflags",
                      flags: [
                        { offset: 0x29b7, bit: 0, label: "Pallet Town" },
                        { offset: 0x29b7, bit: 1, label: "Viridian City" },
                        { offset: 0x29b7, bit: 2, label: "Pewter City" },
                        { offset: 0x29b7, bit: 3, label: "Cerulean City" },
                        { offset: 0x29b7, bit: 4, label: "Lavender Town" },
                        { offset: 0x29b7, bit: 5, label: "Vermilion City" },
                        { offset: 0x29b7, bit: 6, label: "Celadon City" },
                        { offset: 0x29b8, bit: 2, label: "Saffron City" },
                        { offset: 0x29b7, bit: 7, label: "Fuchsia City" },
                        { offset: 0x29b8, bit: 0, label: "Cinnabar Island" },
                        { offset: 0x29b8, bit: 1, label: "Indigo Plateau" },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Pokémon",
          items: [
            {
              id: "boxes",
              length: 0x462,
              type: "container",
              instanceType: "tabs",
              instances: 12,
              enumeration: "Box %d",
              onTabChange: "onBoxChange(%d)",
              prependSubinstance: [
                {
                  name: "Party",
                  items: [
                    {
                      id: "pokemonSlots-party",
                      name: "Slots",
                      offset: 0x2f2c,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      id: "pokemonTabs-party",
                      length: 0x2c,
                      type: "container",
                      instanceType: "tabs",
                      instances: 6,
                      resource: "pokemonNames",
                      vertical: true,
                      onTabChange: "onPokemonChange(%d, '%itemId%')",
                      items: [
                        pokemonStatsFragment("party", 0x307e, 0x2f34, 0x303c, 0x2f2d),
                      ],
                    },
                  ],
                },
              ],
              items: [
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      id: "checksumBox-%index%",
                      name: "Checksum",
                      offset: 0x5a4d,
                      type: "checksum",
                      dataType: "uint8",
                      control: {
                        offsetStart: 0x4000,
                        offsetEnd: 0x4462,
                      },
                      overrideShift: { parent: 1, shift: 0x1 },
                    },
                    {
                      id: "pokemonSlots-box%index%",
                      name: "Slots",
                      offset: 0x4000,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
                {
                  id: "pokemonTabs-box%index%",
                  length: 0x21,
                  type: "container",
                  instanceType: "tabs",
                  instances: 20,
                  resource: "pokemonNames",
                  vertical: true,
                  onTabChange: "onPokemonChange(%d, '%itemId%')",
                  items: [
                    pokemonStatsFragment("box%parent%", 0x4386, 0x4016, 0x42aa, 0x4001),
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Daycare",
          items: [
            {
              id: "pokemonSection-daycare",
              length: 0x2c,
              type: "container",
              instanceType: "section",
              instances: 1,
              items: [
                pokemonStatsFragment("daycare", 0x2cf5, 0x2d0b, 0x2d00, 0x0, 0x2cf4),
              ],
            },
          ],
        },
        {
          name: "Inventory",
          items: [
            {
              type: "tabs",
              items: [
                {
                  name: "Bag",
                  items: [
                    {
                      id: "itemSlots-japanShift",
                      name: "Slots",
                      offset: 0x25c9,
                      type: "variable",
                      dataType: "uint8",
                      max: 20,
                    },
                    {
                      id: "bagItems",
                      length: 0x2,
                      type: "container",
                      instanceType: "section",
                      instances: 20,
                      vertical: true,
                      flex: true,
                      noMargin: true,
                      items: [
                        {
                          id: "item-%index%-1",
                          name: "Item %d",
                          offset: 0x25ca,
                          type: "variable",
                          dataType: "uint8",
                          resource: "items",
                          autocomplete: true,
                        },
                        {
                          id: "item-%index%-2",
                          name: "Quantity",
                          offset: 0x25cb,
                          type: "variable",
                          dataType: "uint8",
                          min: 1,
                          max: 99,
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Storage PC",
                  items: [
                    {
                      id: "itemSlots",
                      name: "Slots",
                      offset: 0x27e6,
                      type: "variable",
                      dataType: "uint8",
                      max: 50,
                    },
                    {
                      length: 0x2,
                      type: "container",
                      instanceType: "section",
                      instances: 50,
                      vertical: true,
                      flex: true,
                      noMargin: true,
                      items: [
                        {
                          id: "item-%index%-1",
                          name: "Item %d",
                          offset: 0x27e7,
                          type: "variable",
                          dataType: "uint8",
                          resource: "items",
                          autocomplete: true,
                        },
                        {
                          id: "item-%index%-2",
                          name: "Quantity",
                          offset: 0x27e8,
                          type: "variable",
                          dataType: "uint8",
                          min: 1,
                          max: 99,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Hall of Fame",
          items: [
            {
              id: "hallOfFameTabs",
              length: 0x60,
              type: "container",
              instanceType: "tabs",
              instances: 50,
              enumeration: "Entry %d",
              vertical: true,
              prependSubinstance: [
                {
                  name: "General",
                  items: [
                    {
                      id: "hallOfFameSlots",
                      name: "Indigo League Victories",
                      offset: 0x284e,
                      type: "variable",
                      dataType: "uint8",
                    },
                  ],
                },
              ],
              items: [
                {
                  id: "hallOfFameSections",
                  length: 0x10,
                  type: "container",
                  instanceType: "section",
                  instances: 6,
                  flex: true,
                  noMargin: true,
                  items: [
                    {
                      id: "name-hallOfFame-%index%-2",
                      name: "Name",
                      offset: 0x59a,
                      length: 0xa,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      fallback: 0x7f,
                      endCode: 0x50,
                      resource: "letters",
                    },
                    {
                      id: "hallOfFame-%index%-0",
                      name: "Pokémon",
                      offset: 0x598,
                      type: "variable",
                      dataType: "uint8",
                      resource: "pokemons",
                      autocomplete: true,
                    },
                    {
                      id: "hallOfFame-%index%-1",
                      name: "Level",
                      offset: 0x599,
                      type: "variable",
                      dataType: "uint8",
                      min: 1,
                      max: 100,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Events",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  id: "yellowExclude",
                  name: "Trainer's Pokémon",
                  offset: 0x29c3,
                  type: "variable",
                  dataType: "uint8",
                  resource: "starters",
                },
                {
                  id: "yellowExclude",
                  name: "Rival's Pokémon",
                  offset: 0x29c1,
                  type: "variable",
                  dataType: "uint8",
                  resource: "starters",
                },
              ],
            },
          ],
        },
        {
          name: "Options",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Text Speed",
                  offset: 0x2601,
                  type: "variable",
                  dataType: "uint8",
                  binary: { bitStart: 1, bitLength: 2 },
                  resource: "textSpeeds",
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Battle Animation",
                  offset: 0x2601,
                  type: "variable",
                  dataType: "bit",
                  bit: 7,
                  resource: "optionBooleanReversed",
                },
                {
                  name: "Battle Style",
                  offset: 0x2601,
                  type: "variable",
                  dataType: "bit",
                  bit: 6,
                  resource: "battleStyles",
                },
              ],
            },
            {
              id: "yellowOnly",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Sound",
                  offset: 0x2601,
                  type: "variable",
                  dataType: "uint8",
                  binary: { bitStart: 4, bitLength: 2 },
                  resource: "sounds",
                },
                {
                  name: "Print",
                  offset: 0x2744,
                  type: "variable",
                  dataType: "uint8",
                  resource: "prints",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    battleStyles: {
      0x0: "Shift",
      0x1: "Set",
    },
    booleanObtained: {
      0x0: "-",
      0x1: "Obtained",
    },
    items: {
      0x0: "-",
      ...items,
    },
    letters: [
      // Europe / USA / France / Germany / Italy / Spain
      {
        0x5d: "⒯",
        0x7f: " ",
        0x80: "A",
        0x81: "B",
        0x82: "C",
        0x83: "D",
        0x84: "E",
        0x85: "F",
        0x86: "G",
        0x87: "H",
        0x88: "I",
        0x89: "J",
        0x8a: "K",
        0x8b: "L",
        0x8c: "M",
        0x8d: "N",
        0x8e: "O",
        0x8f: "P",
        0x90: "Q",
        0x91: "R",
        0x92: "S",
        0x93: "T",
        0x94: "U",
        0x95: "V",
        0x96: "W",
        0x97: "X",
        0x98: "Y",
        0x99: "Z",
        0x9a: "(",
        0x9b: ")",
        0x9c: ":",
        0x9d: ";",
        0x9e: "[",
        0x9f: "]",
        0xa0: "a",
        0xa1: "b",
        0xa2: "c",
        0xa3: "d",
        0xa4: "e",
        0xa5: "f",
        0xa6: "g",
        0xa7: "h",
        0xa8: "i",
        0xa9: "j",
        0xaa: "k",
        0xab: "l",
        0xac: "m",
        0xad: "n",
        0xae: "o",
        0xaf: "p",
        0xb0: "q",
        0xb1: "r",
        0xb2: "s",
        0xb3: "t",
        0xb4: "u",
        0xb5: "v",
        0xb6: "w",
        0xb7: "x",
        0xb8: "y",
        0xb9: "z",
        0xc0: "Ä",
        0xc1: "Ö",
        0xc2: "Ü",
        0xc3: "ä",
        0xc4: "ö",
        0xc5: "ü",
        0xe1: "⒫",
        0xe2: "⒨",
        0xe3: "-",
        0xe6: "?",
        0xe7: "!",
        0xef: "♂",
        0xf1: "×",
        0xf2: ".",
        0xf3: "/",
        0xf4: ",",
        0xf5: "♀",
      },
      // Japan
      {
        0x5: "ガ",
        0x6: "ギ",
        0x7: "グ",
        0x8: "ゲ",
        0x9: "ゴ",
        0xa: "ザ",
        0xb: "ジ",
        0xc: "ズ",
        0xd: "ゼ",
        0xe: "ゾ",
        0xf: "ダ",
        0x10: "ヂ",
        0x11: "ヅ",
        0x12: "デ",
        0x13: "ド",
        0x19: "バ",
        0x1a: "ビ",
        0x1b: "ブ",
        0x1c: "ボ",
        0x26: "が",
        0x27: "ぎ",
        0x28: "ぐ",
        0x29: "げ",
        0x2a: "ご",
        0x2b: "ざ",
        0x2c: "じ",
        0x2d: "ず",
        0x2e: "ぜ",
        0x2f: "ぞ",
        0x30: "だ",
        0x31: "ぢ",
        0x32: "づ",
        0x33: "で",
        0x34: "ど",
        0x3a: "ば",
        0x3b: "び",
        0x3c: "ぶ",
        0x3d: "べ",
        0x3e: "ぼ",
        0x40: "パ",
        0x41: "ピ",
        0x42: "プ",
        0x43: "ポ",
        0x44: "ぱ",
        0x45: "ぴ",
        0x46: "ぷ",
        0x47: "ぺ",
        0x48: "ぽ",
        0x7f: " ",
        0x80: "ア",
        0x81: "イ",
        0x82: "ウ",
        0x83: "エ",
        0x84: "オ",
        0x85: "カ",
        0x86: "キ",
        0x87: "ク",
        0x88: "ケ",
        0x89: "コ",
        0x8a: "サ",
        0x8b: "シ",
        0x8c: "ス",
        0x8d: "セ",
        0x8e: "ソ",
        0x8f: "タ",
        0x90: "チ",
        0x91: "ツ",
        0x92: "テ",
        0x93: "ト",
        0x94: "ナ",
        0x95: "ニ",
        0x96: "ヌ",
        0x97: "ネ",
        0x98: "ノ",
        0x99: "ハ",
        0x9a: "ヒ",
        0x9b: "フ",
        0x9c: "ホ",
        0x9d: "マ",
        0x9e: "ミ",
        0x9f: "ム",
        0xa0: "メ",
        0xa1: "モ",
        0xa2: "ヤ",
        0xa3: "ユ",
        0xa4: "ヨ",
        0xa5: "ラ",
        0xa6: "ル",
        0xa7: "レ",
        0xa8: "ロ",
        0xa9: "ワ",
        0xab: "ン",
        0xac: "ッ",
        0xad: "ャ",
        0xae: "ュ",
        0xaf: "ョ",
        0xb1: "あ",
        0xb2: "い",
        0xb3: "う",
        0xb4: "え",
        0xb5: "お",
        0xb6: "か",
        0xb7: "き",
        0xb8: "く",
        0xb9: "け",
        0xba: "こ",
        0xbb: "さ",
        0xbc: "し",
        0xbd: "す",
        0xbe: "せ",
        0xbf: "そ",
        0xc0: "た",
        0xc1: "ち",
        0xc2: "つ",
        0xc3: "て",
        0xc4: "と",
        0xc5: "な",
        0xc6: "に",
        0xc7: "ぬ",
        0xc8: "ね",
        0xc9: "の",
        0xca: "は",
        0xcb: "ひ",
        0xcc: "ふ",
        0xcd: "へ",
        0xce: "ほ",
        0xcf: "ま",
        0xd0: "み",
        0xd1: "む",
        0xd2: "め",
        0xd3: "も",
        0xd4: "や",
        0xd5: "ゆ",
        0xd6: "よ",
        0xd7: "ら",
        0xd8: "リ",
        0xd9: "る",
        0xda: "れ",
        0xdb: "ろ",
        0xdc: "わ",
        0xde: "ん",
        0xdf: "っ",
        0xe0: "ゃ",
        0xe1: "ゅ",
        0xe2: "ょ",
        0xe3: "ー",
      },
    ],
    move0PPs: {
      0x0: "0",
      0x1: "0",
      0x2: "0",
      0x3: "0",
    },
    move5PPs: {
      0x0: "5",
      0x1: "6",
      0x2: "7",
      0x3: "8",
    },
    move10PPs: {
      0x0: "10",
      0x1: "12",
      0x2: "14",
      0x3: "16",
    },
    move15PPs: {
      0x0: "15",
      0x1: "18",
      0x2: "21",
      0x3: "24",
    },
    move20PPs: {
      0x0: "20",
      0x1: "24",
      0x2: "28",
      0x3: "32",
    },
    move25PPs: {
      0x0: "25",
      0x1: "30",
      0x2: "35",
      0x3: "40",
    },
    move30PPs: {
      0x0: "30",
      0x1: "36",
      0x2: "42",
      0x3: "48",
    },
    move35PPs: {
      0x0: "35",
      0x1: "42",
      0x2: "49",
      0x3: "56",
    },
    move40PPs: {
      0x0: "40",
      0x1: "47",
      0x2: "54",
      0x3: "61",
    },
    moves: {
      0x0: "-",
      ...moves,
    },
    optionBooleanReversed: {
      0x0: "On",
      0x1: "Off",
    },
    pokemonNames: "getPokemonNames('party')",
    pokemons: {
      ...pokemons,
      0xff: "-",
    },
    prints: {
      0x0: "Lightest",
      0x20: "Lighter",
      0x40: "Normal",
      0x60: "Darker",
      0x7f: "Darkest",
    },
    sounds: {
      0x0: "Mono",
      0x1: "Earphone 1",
      0x2: "Earphone 2",
      0x3: "Earphone 3",
    },
    starters: {
      0x0: "-",
      0x99: "001 Bulbasaur",
      0xb0: "004 Charmander",
      0xb1: "007 Squirtle",
    },
    textSpeeds: {
      0x0: "Fast",
      0x1: "Medium",
      0x2: "Slow",
    },
    types: {
      0x0: "Normal",
      0x1: "Fighting",
      0x2: "Flying",
      0x3: "Poison",
      0x4: "Ground",
      0x5: "Rock",
      0x7: "Bug",
      0x8: "Ghost",
      0x14: "Fire",
      0x15: "Water",
      0x16: "Grass",
      0x17: "Electric",
      0x18: "Psychic",
      0x19: "Ice",
      0x1a: "Dragon",
      0xff: "-",
    },
  },
  resourcesGroups: {
    items: itemsGroups,
  },
  resourcesOrder: {
    items: itemsOrder,
    pokemons: [0xff, ...pokemonsOrder],
  },
};

export default template;
