import type { GameJson } from "$lib/types";

import {
  accessories,
  armors,
  armorsGroups,
  characters,
  equipments,
  equipmentsGroups,
  equipmentsOrder,
  items,
  itemsGroups,
  locations,
  locationsGroups,
  locationsOrder,
  specialItems,
  weapons,
  weaponsGroups,
} from "./utils/resource";

const template: GameJson = {
  validator: {
    platforms: {
      supernintendo: {
        usa: true,
        japan: true,
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      length: 0x800,
      type: "container",
      instanceType: "tabs",
      instances: 4,
      enumeration: "Slot %d",
      disableSubinstanceIf: {
        offset: 0x0,
        type: "variable",
        dataType: "uint8",
        operator: "=",
        value: 0xff,
      },
      items: [
        {
          name: "Checksum",
          offset: 0x7fc,
          type: "checksum",
          dataType: "uint16",
          control: {
            offsetStart: 0x0,
            offsetEnd: 0x7fc,
          },
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "filename",
                              name: "Filename",
                              offset: 0xb5,
                              length: 0x8,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0x20,
                              regex: "[ ./0-9:A-Za-z]",
                              test: true,
                            },
                            {
                              name: "Star Pieces",
                              offset: 0x4c5,
                              type: "variable",
                              dataType: "uint8",
                              max: 6,
                            },
                            {
                              name: "Flowers",
                              type: "group",
                              mode: "fraction",
                              linked: true,
                              items: [
                                {
                                  id: "current",
                                  offset: 0xb1,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  offset: 0xb2,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 99,
                                },
                              ],
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "location",
                              name: "Location",
                              offset: 0x3c0,
                              type: "variable",
                              dataType: "uint16",
                              resource: "locations",
                              size: "lg",
                              autocomplete: true,
                            },
                            {
                              name: "Coins",
                              offset: 0xaf,
                              type: "variable",
                              dataType: "uint16",
                              max: 999,
                            },
                            {
                              name: "Frog Coins",
                              offset: 0xb3,
                              type: "variable",
                              dataType: "uint16",
                              max: 999,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          hidden: true,
                          items: [
                            {
                              name: "Location (Save Preview)",
                              offset: 0x4cf,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Position X",
                              offset: 0x3d1,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Position Y",
                              offset: 0x3d3,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          hidden: true,
                          items: [
                            {
                              name: "Events Position X",
                              offset: 0x3e0,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Events Position Y",
                              offset: 0x3e1,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Layer 1 Position X",
                              offset: 0x3e2,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Layer 1 Position Y",
                              offset: 0x3e3,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Layer 2 Position X",
                              offset: 0x3e4,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Layer 2 Position Y",
                              offset: 0x3e5,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Layer 3 Position X",
                              offset: 0x3e6,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Layer 3 Position Y",
                              offset: 0x3e7,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Beetle Mania Hi-Score",
                              offset: 0x4d3,
                              type: "variable",
                              dataType: "uint32",
                              binaryCodedDecimal: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Unlocked Menus",
                              type: "bitflags",
                              flags: [
                                { offset: 0x452, bit: 0, label: "Map" },
                                { offset: 0x452, bit: 1, label: "Star Pieces" },
                                { offset: 0x452, bit: 2, label: "Switch" },
                                { offset: 0x452, bit: 3, label: "Game" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Formation",
                      items: [
                        {
                          name: "Number of Characters",
                          offset: 0x3c2,
                          type: "variable",
                          dataType: "uint8",
                          min: 1,
                          max: 5,
                        },
                        {
                          name: "Main",
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "formation-0",
                              name: "Character 1",
                              offset: 0x3c3,
                              type: "variable",
                              dataType: "uint8",
                              resource: "characters",
                            },
                            {
                              id: "formation-1",
                              name: "Character 2",
                              offset: 0x3c4,
                              type: "variable",
                              dataType: "uint8",
                              resource: "characters",
                            },
                            {
                              id: "formation-2",
                              name: "Character 3",
                              offset: 0x3c5,
                              type: "variable",
                              dataType: "uint8",
                              resource: "characters",
                            },
                          ],
                        },
                        {
                          name: "Reserve",
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "formation-3",
                              name: "Character 1",
                              offset: 0x3c6,
                              type: "variable",
                              dataType: "uint8",
                              resource: "characters",
                            },
                            {
                              id: "formation-4",
                              name: "Character 2",
                              offset: 0x3c7,
                              type: "variable",
                              dataType: "uint8",
                              resource: "characters",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "World Map",
                      flex: true,
                      items: [
                        {
                          name: "Locations",
                          type: "bitflags",
                          flags: [
                            { offset: 0x455, bit: 1, label: "Mario's Pad" },
                            { offset: 0x458, bit: 3, label: "Vista Hill" },
                            { offset: 0x455, bit: 2, label: "Mushroom Way" },
                            { offset: 0x455, bit: 3, label: "Mushroom Kingdom" },
                            { offset: 0x455, bit: 4, label: "Bandit's Way" },
                            { offset: 0x455, bit: 5, label: "Kero Sewers" },
                            { offset: 0x455, bit: 6, label: "Midas River" },
                            { offset: 0x455, bit: 7, label: "Tadpole Pond" },
                            { offset: 0x456, bit: 1, label: "Rose Way" },
                            { offset: 0x456, bit: 2, label: "Rose Town" },
                            { offset: 0x456, bit: 3, label: "Forest Maze" },
                            { offset: 0x456, bit: 4, label: "Pipe Vault" },
                            { offset: 0x456, bit: 5, label: "Yo'ster Isle" },
                            { offset: 0x456, bit: 6, label: "Moleville" },
                            { offset: 0x456, bit: 7, label: "Booster Pass" },
                            { offset: 0x457, bit: 0, label: "Booster Tower" },
                            { offset: 0x458, bit: 4, label: "Booster Hill" },
                            { offset: 0x457, bit: 1, label: "Marrymore" },
                            { offset: 0x457, bit: 2, label: "Star Hill" },
                            { offset: 0x457, bit: 3, label: "Seaside Town" },
                            { offset: 0x457, bit: 4, label: "Sea" },
                            { offset: 0x457, bit: 5, label: "Sunken Ship" },
                            { offset: 0x457, bit: 6, label: "Land's End" },
                            { offset: 0x457, bit: 7, label: "Monstro Town" },
                            { offset: 0x458, bit: 0, label: "Bean Valley" },
                            { offset: 0x458, bit: 6, label: "Grate Guy's Casino" },
                            { offset: 0x458, bit: 1, label: "Nimbus Land" },
                            { offset: 0x458, bit: 2, label: "Barrel Volcano" },
                            { offset: 0x455, bit: 0, label: "Bowser's Keep", hidden: true },
                            { offset: 0x458, bit: 5, label: "Gate" },
                            { offset: 0x456, bit: 0, label: "???", hidden: true },
                            { offset: 0x458, bit: 7, label: "???", hidden: true },
                          ],
                        },
                        {
                          name: "Roads",
                          type: "bitflags",
                          flags: [
                            { offset: 0x460, bit: 3, label: "Mario's Pad - Vista Hill" },
                            { offset: 0x45d, bit: 2, label: "Mario's Pad - Mushroom Way" },
                            { offset: 0x45d, bit: 3, label: "Mushroom Way - Mushroom Kingdom" },
                            { offset: 0x45d, bit: 4, label: "Mushroom Kingdom - Bandit's Way" },
                            { offset: 0x45d, bit: 5, label: "Mushroom Kingdom - Kero Sewers" },
                            { offset: 0x45d, bit: 6, label: "Kero Sewers - Midas River" },
                            { offset: 0x45d, bit: 7, label: "Midas River - Tadpole Pond" },
                            { offset: 0x45e, bit: 0, label: "Tadpole Pond - Rose Way" },
                            { offset: 0x45e, bit: 2, label: "Rose Way - Rose Town" },
                            { offset: 0x45e, bit: 3, label: "Rose Town - Forest Maze" },
                            { offset: 0x45e, bit: 4, label: "Rose Town - Pipe Vault" },
                            { offset: 0x45e, bit: 5, label: "Pipe Vault - Yo'ster Isle" },
                            { offset: 0x45e, bit: 6, label: "Moleville - Booster Pass" },
                            { offset: 0x45e, bit: 7, label: "Booster Pass - Booster Tower" },
                            { offset: 0x45f, bit: 0, label: "Booster Tower - Booster Hill" },
                            { offset: 0x460, bit: 4, label: "Booster Hill - Marrymore" },
                            { offset: 0x45f, bit: 1, label: "Marrymore - Star Hill" },
                            { offset: 0x45f, bit: 2, label: "Star Hill - Seaside Town" },
                            { offset: 0x45f, bit: 3, label: "Seaside Town - Sea" },
                            { offset: 0x45f, bit: 4, label: "Sea - Sunken Ship" },
                            { offset: 0x45f, bit: 5, label: "Seaside Town - Land's End" },
                            { offset: 0x45f, bit: 6, label: "Land's End - Monstro Town" },
                            { offset: 0x45f, bit: 7, label: "Land's End - Bean Valley" },
                            { offset: 0x460, bit: 6, label: "Bean Valley - Grate Guy's Casino" },
                            { offset: 0x460, bit: 0, label: "Bean Valley - Nimbus Land" },
                            { offset: 0x460, bit: 1, label: "Nimbus Land - Barrel Volcano" },
                            { offset: 0x460, bit: 2, label: "Nimbus Land - Bowser's Keep" },
                            { offset: 0x460, bit: 5, label: "Bowser's Keep - Gate" },
                            { offset: 0x460, bit: 7, label: "Vista Hill - Bowser's Keep" },
                            { offset: 0x45d, bit: 1, label: "Mario's Pad - Bowser's Keep", hidden: true },
                            { offset: 0x45d, bit: 0, label: "???", hidden: true },
                            { offset: 0x45e, bit: 1, label: "???", hidden: true },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Party",
              items: [
                {
                  length: 0x14,
                  type: "container",
                  instanceType: "tabs",
                  instances: 5,
                  resource: "characters",
                  vertical: true,
                  items: [
                    {
                      type: "tabs",
                      items: [
                        {
                          name: "Status",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Level",
                                  offset: 0x0,
                                  type: "variable",
                                  dataType: "uint8",
                                  min: 1,
                                  max: 30,
                                },
                                {
                                  name: "Experience",
                                  offset: 0xa,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 9999,
                                },
                                {
                                  name: "HP",
                                  type: "group",
                                  mode: "fraction",
                                  linked: true,
                                  items: [
                                    {
                                      id: "current",
                                      offset: 0x1,
                                      type: "variable",
                                      dataType: "uint16",
                                    },
                                    {
                                      offset: 0x3,
                                      type: "variable",
                                      dataType: "uint16",
                                      max: 999,
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Speed",
                                  offset: 0x5,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  name: "Attack",
                                  offset: 0x6,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  name: "Defense",
                                  offset: 0x7,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  name: "Magic Attack",
                                  offset: 0x8,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  name: "Magic Defense",
                                  offset: 0x9,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  id: "techniques-0-%index%",
                                  name: "Techniques",
                                  type: "bitflags",
                                  hidden: true,
                                  flags: [
                                    { offset: 0x10, bit: 0, label: "Jump" },
                                    { offset: 0x10, bit: 1, label: "Fire Orb" },
                                    { offset: 0x10, bit: 2, label: "Super Jump" },
                                    { offset: 0x10, bit: 3, label: "Super Flame" },
                                    { offset: 0x10, bit: 4, label: "Ultra Jump" },
                                    { offset: 0x10, bit: 5, label: "Ultra Flame" },
                                  ],
                                },
                                {
                                  id: "techniques-1-%index%",
                                  name: "Techniques",
                                  type: "bitflags",
                                  hidden: true,
                                  flags: [
                                    { offset: 0x10, bit: 6, label: "Therapy" },
                                    { offset: 0x10, bit: 7, label: "Group Hug" },
                                    { offset: 0x11, bit: 0, label: "Sleepy Time" },
                                    { offset: 0x11, bit: 1, label: "Come Back" },
                                    { offset: 0x11, bit: 2, label: "Mute" },
                                    { offset: 0x11, bit: 3, label: "Psych Bomb" },
                                  ],
                                },
                                {
                                  id: "techniques-2-%index%",
                                  name: "Techniques",
                                  type: "bitflags",
                                  hidden: true,
                                  flags: [
                                    { offset: 0x11, bit: 4, label: "Terrorize" },
                                    { offset: 0x11, bit: 5, label: "Poison Gaz" },
                                    { offset: 0x11, bit: 6, label: "Crusher" },
                                    { offset: 0x11, bit: 7, label: "Bowser Crush" },
                                  ],
                                },
                                {
                                  id: "techniques-3-%index%",
                                  name: "Techniques",
                                  type: "bitflags",
                                  hidden: true,
                                  flags: [
                                    { offset: 0x12, bit: 0, label: "Geno Beam" },
                                    { offset: 0x12, bit: 1, label: "Geno Boost" },
                                    { offset: 0x12, bit: 2, label: "Geno Whirl" },
                                    { offset: 0x12, bit: 3, label: "Geno Blast" },
                                    { offset: 0x12, bit: 4, label: "Geno Flash" },
                                  ],
                                },
                                {
                                  id: "techniques-4-%index%",
                                  name: "Techniques",
                                  type: "bitflags",
                                  hidden: true,
                                  flags: [
                                    { offset: 0x12, bit: 5, label: "Thunderbolt" },
                                    { offset: 0x12, bit: 6, label: "HP Rain" },
                                    { offset: 0x12, bit: 7, label: "Psychopath" },
                                    { offset: 0x13, bit: 0, label: "Shocker" },
                                    { offset: 0x13, bit: 1, label: "Snowy" },
                                    { offset: 0x13, bit: 2, label: "Star Rain" },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Equipment",
                          flex: true,
                          items: [
                            {
                              name: "Weapon",
                              offset: 0xc,
                              type: "variable",
                              dataType: "uint8",
                              resource: "weapons",
                              autocomplete: true,
                            },
                            {
                              name: "Armor",
                              offset: 0xd,
                              type: "variable",
                              dataType: "uint8",
                              resource: "armors",
                              autocomplete: true,
                            },
                            {
                              name: "Accessory",
                              offset: 0xe,
                              type: "variable",
                              dataType: "uint8",
                              resource: "accessories",
                              autocomplete: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Inventory",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Equipment",
                      flex: true,
                      items: [...Array(30).keys()].map((index) => ({
                        name: `Item ${index + 1}`,
                        offset: 0x64 + index,
                        type: "variable",
                        dataType: "uint8",
                        resource: "equipments",
                        autocomplete: true,
                      })),
                    },
                    {
                      name: "Items",
                      flex: true,
                      items: [...Array(30).keys()].map((index) => ({
                        name: `Item ${index + 1}`,
                        offset: 0x82 + index,
                        type: "variable",
                        dataType: "uint8",
                        resource: "items",
                        autocomplete: true,
                      })),
                    },
                    {
                      name: "Special Items",
                      flex: true,
                      items: [...Array(15).keys()].map((index) => ({
                        name: `Item ${index + 1}`,
                        offset: 0xa0 + index,
                        type: "variable",
                        dataType: "uint8",
                        resource: "specialItems",
                        autocomplete: true,
                      })),
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    accessories: {
      ...accessories,
      0xff: "-",
    },
    armors: {
      ...armors,
      0xff: "-",
    },
    characters,
    empty: {
      0x0: "-",
    },
    equipments: {
      ...equipments,
      0xff: "-",
    },
    items: {
      ...items,
      0xff: "-",
    },
    letters: {
      0x20: " ",
      0x2a: ".",
      0x3a: "~",
      0x5b: "ー",
      0x5e: "っ",
      0x5f: "ッ",
      0x60: "ぁ",
      0x61: "ァ",
      0x62: "ぃ",
      0x63: "ィ",
      0x64: "ぅ",
      0x65: "ゥ",
      0x66: "ぇ",
      0x67: "ェ",
      0x68: "ぉ",
      0x69: "ォ",
      0x6a: "ゃ",
      0x6b: "ャ",
      0x6c: "ゅ",
      0x6d: "ュ",
      0x6e: "ょ",
      0x6f: "ョ",
      0x70: "あ",
      0x71: "ア",
      0x72: "い",
      0x73: "イ",
      0x74: "う",
      0x75: "ウ",
      0x76: "え",
      0x77: "エ",
      0x78: "お",
      0x79: "オ",
      0x7a: "か",
      0x7b: "カ",
      0x7c: "き",
      0x7d: "キ",
      0x7e: "く",
      0x7f: "ク",
      0x80: "け",
      0x81: "ケ",
      0x82: "こ",
      0x83: "コ",
      0x84: "さ",
      0x85: "サ",
      0x86: "し",
      0x87: "シ",
      0x88: "す",
      0x89: "ス",
      0x8a: "せ",
      0x8b: "セ",
      0x8c: "そ",
      0x8d: "ソ",
      0x8e: "た",
      0x8f: "タ",
      0x90: "ち",
      0x91: "チ",
      0x92: "つ",
      0x93: "ツ",
      0x94: "て",
      0x95: "テ",
      0x96: "と",
      0x97: "ト",
      0x98: "な",
      0x99: "ナ",
      0x9a: "に",
      0x9b: "ニ",
      0x9c: "ぬ",
      0x9d: "ヌ",
      0x9e: "ね",
      0x9f: "ネ",
      0xa0: "の",
      0xa1: "ノ",
      0xa2: "は",
      0xa3: "ハ",
      0xa4: "ひ",
      0xa5: "ヒ",
      0xa6: "ふ",
      0xa7: "フ",
      0xa8: "へ",
      0xa9: "ヘ",
      0xaa: "ほ",
      0xab: "ホ",
      0xac: "ま",
      0xad: "マ",
      0xae: "み",
      0xaf: "ミ",
      0xb0: "む",
      0xb1: "ム",
      0xb2: "め",
      0xb3: "メ",
      0xb4: "も",
      0xb5: "モ",
      0xb6: "や",
      0xb7: "ヤ",
      0xb8: "ゆ",
      0xb9: "ユ",
      0xba: "よ",
      0xbb: "ヨ",
      0xbc: "ら",
      0xbd: "ラ",
      0xbe: "り",
      0xbf: "リ",
      0xc0: "る",
      0xc1: "ル",
      0xc2: "れ",
      0xc3: "レ",
      0xc4: "ろ",
      0xc5: "ロ",
      0xc6: "わ",
      0xc7: "ワ",
      0xc8: "を",
      0xc9: "ヲ",
      0xca: "ん",
      0xcb: "ン",
      0xcc: "ゔ",
      0xcd: "ヴ",
      0xce: "が",
      0xcf: "ガ",
      0xd0: "ぎ",
      0xd1: "ギ",
      0xd2: "ぐ",
      0xd3: "グ",
      0xd4: "げ",
      0xd5: "ゲ",
      0xd6: "ご",
      0xd7: "ゴ",
      0xd8: "ざ",
      0xd9: "ザ",
      0xda: "じ",
      0xdb: "ジ",
      0xdc: "ず",
      0xdd: "ズ",
      0xde: "ぜ",
      0xdf: "ゼ",
      0xe0: "ぞ",
      0xe1: "ゾ",
      0xe2: "だ",
      0xe3: "ダ",
      0xe4: "ぢ",
      0xe5: "ヂ",
      0xe6: "づ",
      0xe7: "ヅ",
      0xe8: "で",
      0xe9: "デ",
      0xea: "ど",
      0xeb: "ド",
      0xec: "ば",
      0xed: "バ",
      0xee: "び",
      0xef: "ビ",
      0xf0: "ぶ",
      0xf1: "ブ",
      0xf2: "べ",
      0xf3: "ベ",
      0xf4: "ぼ",
      0xf5: "ボ",
      0xf6: "ぱ",
      0xf7: "パ",
      0xf8: "ぴ",
      0xf9: "ピ",
      0xfa: "ぷ",
      0xfb: "プ",
      0xfc: "ぺ",
      0xfd: "ペ",
      0xfe: "ぽ",
      0xff: "ポ",
    },
    locations,
    specialItems: {
      ...specialItems,
      0xff: "-",
    },
    weapons: {
      ...weapons,
      0xff: "-",
    },
  },
  resourcesGroups: {
    armors: armorsGroups,
    items: itemsGroups,
    equipments: equipmentsGroups,
    locations: locationsGroups,
    weapons: weaponsGroups,
  },
  resourcesOrder: {
    accessories: [0xff],
    armors: [0xff],
    characters: [0xff],
    equipments: equipmentsOrder,
    items: [0xff],
    locations: locationsOrder,
    specialItems: [0xff],
    weapons: [0xff],
  },
};

export default template;
