import type { GameJson } from "$lib/types";

import { items, itemsGroups, itemsOrder } from "./utils/resource";

const template: GameJson = {
  validator: {
    regions: {
      europe: { 0x0: [0x47, 0x42, 0x5a, 0x50, 0x30, 0x38] }, // "GBZP08"
      usa: { 0x0: [0x47, 0x42, 0x5a, 0x45, 0x30, 0x38] }, // "GBZE08"
      japan: { 0x0: [0x47, 0x42, 0x5a, 0x4a, 0x30, 0x38] }, // "GBZJ08"
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      id: "checksum",
      name: "Checksum",
      offset: 0x1203c,
      type: "checksum",
      dataType: "uint32",
      bigEndian: true,
      control: {
        offsetStart: 0x40,
        offsetEnd: 0x1203c,
      },
      overrideShift: {
        parent: 1,
        shift: 0x0,
      },
    },
    {
      type: "tabs",
      items: [
        {
          name: "General",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  id: "savePreview-5736",
                  name: "Difficulty",
                  offset: 0x16af,
                  type: "variable",
                  dataType: "uint8",
                  resource: "difficulties",
                },
                {
                  name: "Difficulty (Save Preview)",
                  offset: 0x47,
                  type: "variable",
                  dataType: "uint8",
                  resource: "difficulties",
                  overrideShift: {
                    parent: 1,
                    shift: 0x0,
                  },
                  hidden: true,
                },
                {
                  name: "Disc",
                  offset: 0x16c6,
                  type: "variable",
                  dataType: "uint16",
                  bigEndian: true,
                  resource: "discs",
                  disabled: true,
                },
                {
                  name: "Playtime",
                  type: "group",
                  mode: "time",
                  items: [
                    {
                      offset: 0x16b4,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      operations: [
                        { "/": 60 },
                        { convert: { from: "seconds", to: "hours" } },
                      ],
                      max: 99,
                    },
                    {
                      offset: 0x16b4,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      operations: [
                        { "/": 60 },
                        { convert: { from: "seconds", to: "minutes" } },
                      ],
                      leadingZeros: 1,
                      max: 59,
                      test: true,
                    },
                    {
                      offset: 0x16b4,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      operations: [
                        { "/": 60 },
                        { convert: { from: "seconds", to: "seconds" } },
                      ],
                      leadingZeros: 1,
                      max: 59,
                      test: true,
                    },
                  ],
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Character",
                  offset: 0x114ac,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  resource: "characters",
                  disabled: true,
                },
                {
                  id: "savePreview-5739",
                  name: "Save Count",
                  offset: 0x16b0,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  operations: [{ "+": 1 }],
                  min: 1,
                },
                {
                  name: "Location",
                  offset: 0x44,
                  type: "variable",
                  dataType: "uint8",
                  resource: "locations",
                  size: "lg",
                  disabled: true,
                },
                {
                  id: "saveCount",
                  name: "Save Count (Save Preview)",
                  offset: 0x45,
                  type: "variable",
                  dataType: "uint8",
                  overrideShift: {
                    parent: 1,
                    shift: 0x0,
                  },
                  hidden: true,
                },
              ],
            },
            {
              name: "Formation",
              type: "section",
              flex: true,
              hidden: true,
              items: [
                {
                  name: "Character 1",
                  offset: 0x114ac,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  resource: "characters",
                  hidden: true,
                },
                {
                  name: "Character 2",
                  offset: 0x114b0,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  resource: "characters",
                  hidden: true,
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Story Rewards",
                  type: "bitflags",
                  flags: [
                    { offset: 0x16ab, bit: 0, label: "Leech Hunter" },
                    { offset: 0x16ab, bit: 1, label: "Closet Key" },
                    { offset: 0x16ab, bit: 2, label: "Sub-Machinegun" },
                    { offset: 0x16ab, bit: 3, label: "Rocket Launcher" },
                  ],
                },
                {
                  name: "Leech Hunter Rewards",
                  type: "bitflags",
                  flags: [
                    { offset: 0x16aa, bit: 0, label: "Sub-Machinegun Ammo" },
                    { offset: 0x16ab, bit: 7, label: "Infinite Handgun Ammo" },
                    { offset: 0x16ab, bit: 6, label: "Infinite Hunting Gun Ammo" },
                    { offset: 0x16ab, bit: 5, label: "Magnum Revolver" },
                    { offset: 0x16ab, bit: 4, label: "Infinite Ammo" },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Party",
          items: [
            {
              type: "tabs",
              vertical: true,
              items: [
                {
                  name: "Rebecca Chambers",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Health",
                          offset: 0x22c8,
                          type: "variable",
                          dataType: "uint32",
                          bigEndian: true,
                          max: 150,
                        },
                        {
                          name: "Outfit",
                          offset: 0x16c0,
                          type: "variable",
                          dataType: "uint8",
                          bigEndian: true,
                          resource: "rebeccaOutfits",
                        },
                      ],
                    },
                    {
                      name: "Position",
                      type: "section",
                      flex: true,
                      hidden: true,
                      items: [
                        {
                          name: "Position X",
                          offset: 0x22b0,
                          type: "variable",
                          dataType: "float32",
                          bigEndian: true,
                          hidden: true,
                        },
                        {
                          name: "Position Y",
                          offset: 0x22b4,
                          type: "variable",
                          dataType: "float32",
                          bigEndian: true,
                          hidden: true,
                        },
                        {
                          name: "Position Z",
                          offset: 0x22b8,
                          type: "variable",
                          dataType: "float32",
                          bigEndian: true,
                          hidden: true,
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      noMargin: true,
                      items: [
                        {
                          name: "Personal",
                          offset: 0x114d0,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          resource: "items",
                          size: "lg",
                          autocomplete: true,
                        },
                        {
                          name: "Personal Quantity",
                          offset: 0x114d2,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          hidden: true,
                        },
                        {
                          name: "Equipped Slot",
                          offset: 0x114d6,
                          type: "variable",
                          dataType: "uint8",
                          hidden: true,
                        },
                      ],
                    },
                    {
                      length: 0x4,
                      type: "container",
                      instanceType: "section",
                      instances: 6,
                      flex: true,
                      noMargin: true,
                      items: [
                        {
                          id: "item-%index%",
                          name: "Item %d",
                          offset: 0x114b8,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          resource: "items",
                          size: "lg",
                          autocomplete: true,
                        },
                        {
                          id: "quantity",
                          name: "Quantity",
                          offset: 0x114ba,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          max: 9999,
                        },
                        {
                          id: "infiniteAmmo",
                          name: "Infinite Ammo",
                          offset: 0x114ba,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          resource: "booleanEnabled",
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Billy Coen",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Health",
                          offset: 0x2388,
                          type: "variable",
                          dataType: "uint32",
                          bigEndian: true,
                          max: 250,
                        },
                        {
                          name: "Outfit",
                          offset: 0x16c1,
                          type: "variable",
                          dataType: "uint8",
                          bigEndian: true,
                          resource: "billyOutfits",
                        },
                      ],
                    },
                    {
                      name: "Position",
                      type: "section",
                      flex: true,
                      hidden: true,
                      items: [
                        {
                          name: "Position X",
                          offset: 0x2370,
                          type: "variable",
                          dataType: "float32",
                          bigEndian: true,
                          hidden: true,
                        },
                        {
                          name: "Position Y",
                          offset: 0x2374,
                          type: "variable",
                          dataType: "float32",
                          bigEndian: true,
                          hidden: true,
                        },
                        {
                          name: "Position Z",
                          offset: 0x2378,
                          type: "variable",
                          dataType: "float32",
                          bigEndian: true,
                          hidden: true,
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      noMargin: true,
                      items: [
                        {
                          name: "Personal",
                          offset: 0x114f0,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          resource: "items",
                          size: "lg",
                          autocomplete: true,
                        },
                        {
                          name: "Personal Quantity",
                          offset: 0x114f2,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          hidden: true,
                        },
                        {
                          name: "Equipped Slot",
                          offset: 0x114f6,
                          type: "variable",
                          dataType: "uint8",
                          hidden: true,
                        },
                      ],
                    },
                    {
                      length: 0x4,
                      type: "container",
                      instanceType: "section",
                      instances: 6,
                      flex: true,
                      noMargin: true,
                      items: [
                        {
                          id: "item-%index%",
                          name: "Item %d",
                          offset: 0x114d8,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          resource: "items",
                          size: "lg",
                          autocomplete: true,
                        },
                        {
                          id: "quantity",
                          name: "Quantity",
                          offset: 0x114da,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          max: 9999,
                        },
                        {
                          id: "infiniteAmmo",
                          name: "Infinite Ammo",
                          offset: 0x114da,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          resource: "booleanEnabled",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Maps",
          items: [
            {
              type: "bitflags",
              flags: [
                { offset: 0x1726, bit: 0, label: "Train" },
                { offset: 0x1726, bit: 1, label: "Training Facility" },
                { offset: 0x1726, bit: 2, label: "Facility Basement" },
                { offset: 0x1726, bit: 3, label: "Laboratory" },
                { offset: 0x1726, bit: 4, label: "Factory" },
                { offset: 0x1726, bit: 5, label: "Treatment Plant" },
              ],
            },
          ],
        },
        {
          name: "Files",
          flex: true,
          items: [
            {
              name: "File 1",
              type: "bitflags",
              flags: [
                { offset: 0x1725, bit: 3, label: "Player's Manual 1" },
                { offset: 0x1725, bit: 4, label: "Player's Manual 2" },
                { offset: 0x1725, bit: 5, label: "Court Order for Transportation" },
                { offset: 0x1729, bit: 0, label: "Hookshot Operator's Manual" },
                { offset: 0x1725, bit: 6, label: "Investigation Orders" },
                { offset: 0x1725, bit: 7, label: "Notice to Supervisors" },
                { offset: 0x1724, bit: 0, label: "Passenger's Diary" },
                { offset: 0x1724, bit: 1, label: "Brake Operation Manual" },
                { offset: 0x1724, bit: 2, label: "Note from Conductor" },
                { offset: 0x1724, bit: 3, label: "Regulations for Trainees" },
              ],
            },
            {
              name: "File 2",
              type: "bitflags",
              flags: [
                { offset: 0x1724, bit: 4, label: "Notice to All Staff" },
                { offset: 0x1724, bit: 5, label: "Marcus' Diary 1" },
                { offset: 0x1724, bit: 6, label: "Assistant Director's Diary" },
                { offset: 0x1724, bit: 7, label: "About the Power Regulator" },
                { offset: 0x172b, bit: 0, label: "A Verse of Poetry" },
                { offset: 0x172b, bit: 1, label: "Management Trainee's Diary" },
                { offset: 0x172a, bit: 3, label: "Microfilm Image" },
                { offset: 0x172b, bit: 3, label: "Inmates List" },
                { offset: 0x172b, bit: 4, label: "1st Investigation Unit Notes" },
                { offset: 0x172b, bit: 5, label: "Marcus' Diary 2" },
              ],
            },
            {
              name: "File 3",
              type: "bitflags",
              flags: [
                { offset: 0x172b, bit: 6, label: "Old Photograph" },
                { offset: 0x172b, bit: 7, label: "Investigator's Report" },
                { offset: 0x172a, bit: 0, label: "Leech Growth Records" },
                { offset: 0x172a, bit: 1, label: "Laboratory Manager's Diary" },
                { offset: 0x172a, bit: 2, label: "B.O.W. Report" },
                { offset: 0x172a, bit: 7, label: "About Battery Fluid" },
                { offset: 0x172a, bit: 4, label: "Investigator's Report 2" },
                { offset: 0x172a, bit: 5, label: "Treatment Plant Manager's Diary" },
                { offset: 0x172a, bit: 6, label: "Gate Operation Manual" },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    billyOutfits: {
      0x0: "Normal",
      0x1: "Jacket",
    },
    booleanEnabled: {
      0x0: "-",
      0x1: "Enabled",
    },
    characters: {
      0x2b: "Rebecca",
      0x2e: "Billy",
    },
    difficulties: {
      0x0: "Easy",
      0x1: "Normal",
      0x2: "Hard",
    },
    discs: {
      0x0: "Disc 1",
      0x1: "Disc 2",
    },
    items: {
      0x0: "-",
      ...items,
    },
    locations: {
      0x1: "Train 1F - Cabin",
      0x2: "Training Facility 1F - Hall",
      0x3: "Training Facility 2F - Conference Room",
      0x4: "Facility Basement B1 - Observation Room",
      0x5: "Laboratory 1F - Church",
      0x6: "Laboratory B1 - Machine Room",
      0x7: "Laboratory B2 - Library",
      0x8: "Factory 1F - Panel Room",
      0x9: "Treatment Plant B5 - Control Room",
      0xa: "Treatment Plant B6 - Lodgings",
      0xb: "Treatment Plant B9 - Storage",
      0xc: "Clear",
      0xd: "Facility Basement B2 - B2F",
    },
    rebeccaOutfits: {
      0x0: "Normal",
      0x1: "Leather",
      0x2: "Cowgirl",
    },
  },
  resourcesGroups: {
    items: itemsGroups,
  },
  resourcesOrder: {
    items: itemsOrder,
  },
};

export default template;
