import type { GameJson } from "$lib/types";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa: {
        0x0: [0x42, 0x41, 0x4b, 0x55],
      },
      japan: {
        0x0: [0x42, 0x41, 0x4b, 0x55],
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      id: "slots",
      length: 0x90,
      type: "container",
      instanceType: "tabs",
      instances: 3,
      enumeration: "Slot %d",
      disableSubinstanceIf: {
        offset: 0xc,
        type: "variable",
        dataType: "uint8",
        value: 0x0,
      },
      appendSubinstance: [
        {
          name: "Options",
          items: [
            {
              name: "Unlocked Options",
              type: "bitflags",
              flags: [
                { offset: 0x4, bit: 0, label: "???", hidden: true },
                { offset: 0x4, bit: 1, label: "???", hidden: true },
                { offset: 0x4, bit: 2, label: "???", hidden: true },
                { offset: 0x4, bit: 3, label: "???", hidden: true },
                { offset: 0x4, bit: 4, label: "???", hidden: true },
                { offset: 0x4, bit: 5, label: "Music" },
                { offset: 0x4, bit: 6, label: "Full Power" },
                { offset: 0x4, bit: 7, label: "View Credits" },
              ],
            },
          ],
        },
      ],
      items: [
        {
          type: "section",
          flex: true,
          hidden: true,
          items: [...Array(0x12).keys()].map((index) => {
            let offset = index * 0x8 + 0x7;
            let offsetStart = index * 0x8;
            let length = 0x8;

            if (index === 2) {
              offset = 0x18;
              offsetStart = 0x10;
              length = 0x9;
            } else if (index === 3) {
              offset = 0x1f;
              offsetStart = 0x19;
              length = 0x7;
            }

            return {
              name: `Checksum ${index + 1}`,
              offset,
              type: "checksum",
              dataType: "uint8",
              control: {
                offsetStart,
                offsetEnd: offsetStart + length,
              },
            };
          }),
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              flex: true,
              items: [
                {
                  name: "Play Time",
                  type: "group",
                  mode: "time",
                  items: [
                    {
                      offset: 0x8,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      operations: [
                        { convert: { from: "seconds", to: "hours" } },
                      ],
                      max: 99,
                    },
                    {
                      offset: 0x8,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      operations: [
                        { convert: { from: "seconds", to: "minutes" } },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                    {
                      offset: 0x8,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      operations: [
                        { convert: { from: "seconds", to: "seconds" } },
                      ],
                      leadingZeros: 1,
                      max: 59,
                    },
                  ],
                },
                {
                  name: "Difficulty",
                  offset: 0xe,
                  type: "variable",
                  dataType: "uint8",
                  resource: "difficulties",
                },
                {
                  name: "???",
                  offset: 0x19,
                  type: "variable",
                  dataType: "bit",
                  bit: 0,
                  hidden: true,
                },
                {
                  name: "???",
                  offset: 0x19,
                  type: "variable",
                  dataType: "bit",
                  bit: 1,
                  hidden: true,
                },
                {
                  name: "Rainbow Palace Unlocked",
                  offset: 0x19,
                  type: "variable",
                  dataType: "bit",
                  bit: 7,
                },
              ],
            },
            {
              name: "Levels",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Green Garden",
                      flex: true,
                      items: [
                        {
                          name: "Stage 1",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x20,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x82, bit: 0, label: "Gold Card 1" },
                                { offset: 0x82, bit: 1, label: "Gold Card 2" },
                                { offset: 0x82, bit: 2, label: "Gold Card 3" },
                                { offset: 0x82, bit: 3, label: "Gold Card 4" },
                                { offset: 0x82, bit: 4, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 2",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x23,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x82, bit: 5, label: "Gold Card 1" },
                                { offset: 0x82, bit: 6, label: "Gold Card 2" },
                                { offset: 0x82, bit: 7, label: "Gold Card 3" },
                                { offset: 0x83, bit: 0, label: "Gold Card 4" },
                                { offset: 0x83, bit: 1, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 3",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x28,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x83, bit: 2, label: "Gold Card 1" },
                                { offset: 0x83, bit: 3, label: "Gold Card 2" },
                                { offset: 0x83, bit: 4, label: "Gold Card 3" },
                                { offset: 0x83, bit: 5, label: "Gold Card 4" },
                                { offset: 0x83, bit: 6, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 4",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x2b,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x83, bit: 7, label: "Gold Card 1" },
                                { offset: 0x84, bit: 0, label: "Gold Card 2" },
                                { offset: 0x84, bit: 1, label: "Gold Card 3" },
                                { offset: 0x84, bit: 2, label: "Gold Card 4" },
                                { offset: 0x84, bit: 3, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Blue Resort",
                      flex: true,
                      items: [
                        {
                          name: "Stage 1",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x30,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x84, bit: 4, label: "Gold Card 1" },
                                { offset: 0x84, bit: 5, label: "Gold Card 2" },
                                { offset: 0x84, bit: 6, label: "Gold Card 3" },
                                { offset: 0x84, bit: 7, label: "Gold Card 4" },
                                { offset: 0x85, bit: 0, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 2",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x33,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x85, bit: 1, label: "Gold Card 1" },
                                { offset: 0x85, bit: 2, label: "Gold Card 2" },
                                { offset: 0x85, bit: 3, label: "Gold Card 3" },
                                { offset: 0x85, bit: 4, label: "Gold Card 4" },
                                { offset: 0x85, bit: 5, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 3",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x38,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x85, bit: 6, label: "Gold Card 1" },
                                { offset: 0x85, bit: 7, label: "Gold Card 2" },
                                { offset: 0x86, bit: 0, label: "Gold Card 3" },
                                { offset: 0x86, bit: 1, label: "Gold Card 4" },
                                { offset: 0x86, bit: 2, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 4",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x3b,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x86, bit: 3, label: "Gold Card 1" },
                                { offset: 0x86, bit: 4, label: "Gold Card 2" },
                                { offset: 0x86, bit: 5, label: "Gold Card 3" },
                                { offset: 0x86, bit: 6, label: "Gold Card 4" },
                                { offset: 0x86, bit: 7, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Red Mountain",
                      flex: true,
                      items: [
                        {
                          name: "Stage 1",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x40,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x88, bit: 0, label: "Gold Card 1" },
                                { offset: 0x88, bit: 1, label: "Gold Card 2" },
                                { offset: 0x88, bit: 2, label: "Gold Card 3" },
                                { offset: 0x88, bit: 3, label: "Gold Card 4" },
                                { offset: 0x88, bit: 4, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 2",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x43,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x88, bit: 5, label: "Gold Card 1" },
                                { offset: 0x88, bit: 6, label: "Gold Card 2" },
                                { offset: 0x88, bit: 7, label: "Gold Card 3" },
                                { offset: 0x89, bit: 0, label: "Gold Card 4" },
                                { offset: 0x89, bit: 1, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 3",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x48,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x89, bit: 2, label: "Gold Card 1" },
                                { offset: 0x89, bit: 3, label: "Gold Card 2" },
                                { offset: 0x89, bit: 4, label: "Gold Card 3" },
                                { offset: 0x89, bit: 5, label: "Gold Card 4" },
                                { offset: 0x89, bit: 6, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 4",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x4b,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x89, bit: 7, label: "Gold Card 1" },
                                { offset: 0x8a, bit: 0, label: "Gold Card 2" },
                                { offset: 0x8a, bit: 1, label: "Gold Card 3" },
                                { offset: 0x8a, bit: 2, label: "Gold Card 4" },
                                { offset: 0x8a, bit: 3, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "White Glacier",
                      flex: true,
                      items: [
                        {
                          name: "Stage 1",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x50,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x8a, bit: 4, label: "Gold Card 1" },
                                { offset: 0x8a, bit: 5, label: "Gold Card 2" },
                                { offset: 0x8a, bit: 6, label: "Gold Card 3" },
                                { offset: 0x8a, bit: 7, label: "Gold Card 4" },
                                { offset: 0x8b, bit: 0, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 2",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x53,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x8b, bit: 1, label: "Gold Card 1" },
                                { offset: 0x8b, bit: 2, label: "Gold Card 2" },
                                { offset: 0x8b, bit: 3, label: "Gold Card 3" },
                                { offset: 0x8b, bit: 4, label: "Gold Card 4" },
                                { offset: 0x8b, bit: 5, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 3",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x58,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x8b, bit: 6, label: "Gold Card 1" },
                                { offset: 0x8b, bit: 7, label: "Gold Card 2" },
                                { offset: 0x8c, bit: 0, label: "Gold Card 3" },
                                { offset: 0x8c, bit: 1, label: "Gold Card 4" },
                                { offset: 0x8c, bit: 2, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 4",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x5b,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x8c, bit: 3, label: "Gold Card 1" },
                                { offset: 0x8c, bit: 4, label: "Gold Card 2" },
                                { offset: 0x8c, bit: 5, label: "Gold Card 3" },
                                { offset: 0x8c, bit: 6, label: "Gold Card 4" },
                                { offset: 0x8c, bit: 7, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Black Fortress",
                      flex: true,
                      items: [
                        {
                          name: "Stage 1",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x60,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x8d, bit: 0, label: "Gold Card 1" },
                                { offset: 0x8d, bit: 1, label: "Gold Card 2" },
                                { offset: 0x8d, bit: 2, label: "Gold Card 3" },
                                { offset: 0x8d, bit: 3, label: "Gold Card 4" },
                                { offset: 0x8d, bit: 4, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 2",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x63,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x8d, bit: 5, label: "Gold Card 1" },
                                { offset: 0x8d, bit: 6, label: "Gold Card 2" },
                                { offset: 0x8d, bit: 7, label: "Gold Card 3" },
                                { offset: 0x8e, bit: 0, label: "Gold Card 4" },
                                { offset: 0x8e, bit: 1, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 3",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x68,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x8e, bit: 2, label: "Gold Card 1" },
                                { offset: 0x8e, bit: 3, label: "Gold Card 2" },
                                { offset: 0x8e, bit: 4, label: "Gold Card 3" },
                                { offset: 0x8e, bit: 5, label: "Gold Card 4" },
                                { offset: 0x8e, bit: 6, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 4",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x6b,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x8e, bit: 7, label: "Gold Card 1" },
                                { offset: 0x90, bit: 0, label: "Gold Card 2" },
                                { offset: 0x90, bit: 1, label: "Gold Card 3" },
                                { offset: 0x90, bit: 2, label: "Gold Card 4" },
                                { offset: 0x90, bit: 3, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Rainbow Palace",
                      flex: true,
                      items: [
                        {
                          name: "Stage 1",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x70,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x90, bit: 4, label: "Gold Card 1" },
                                { offset: 0x90, bit: 5, label: "Gold Card 2" },
                                { offset: 0x90, bit: 6, label: "Gold Card 3" },
                                { offset: 0x90, bit: 7, label: "Gold Card 4" },
                                { offset: 0x91, bit: 0, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 2",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x73,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x91, bit: 1, label: "Gold Card 1" },
                                { offset: 0x91, bit: 2, label: "Gold Card 2" },
                                { offset: 0x91, bit: 3, label: "Gold Card 3" },
                                { offset: 0x91, bit: 4, label: "Gold Card 4" },
                                { offset: 0x91, bit: 5, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 3",
                          type: "section",
                          items: [
                            {
                              id: "time-1",
                              name: "Time",
                              offset: 0x78,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x91, bit: 6, label: "Gold Card 1" },
                                { offset: 0x91, bit: 7, label: "Gold Card 2" },
                                { offset: 0x92, bit: 0, label: "Gold Card 3" },
                                { offset: 0x92, bit: 1, label: "Gold Card 4" },
                                { offset: 0x92, bit: 2, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Stage 4",
                          type: "section",
                          items: [
                            {
                              id: "time-2",
                              name: "Time",
                              offset: 0x7b,
                              type: "variable",
                              dataType: "uint32",
                              bigEndian: true,
                              max: 99999999,
                            },
                            {
                              name: "Gold Cards",
                              type: "bitflags",
                              flags: [
                                { offset: 0x92, bit: 3, label: "Gold Card 1" },
                                { offset: 0x92, bit: 4, label: "Gold Card 2" },
                                { offset: 0x92, bit: 5, label: "Gold Card 3" },
                                { offset: 0x92, bit: 6, label: "Gold Card 4" },
                                { offset: 0x92, bit: 7, label: "Gold Card 5" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Custom",
              items: [
                {
                  type: "section",
                  items: [
                    {
                      name: "Filename",
                      offset: 0x10,
                      length: 0x8,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      fallback: 0xf,
                      resource: "letters",
                      test: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      type: "section",
                      items: [
                        {
                          name: "Head",
                          offset: 0x1b,
                          type: "variable",
                          dataType: "lower4",
                          resource: "head",
                          autocomplete: true,
                        },
                        {
                          name: "Body Parts",
                          type: "bitflags",
                          flags: [
                            {
                              offset: 0x1d,
                              bit: 0,
                              label: "???",
                              hidden: true,
                            },
                            { offset: 0x1d, bit: 1, label: "Knight Helmet" },
                            { offset: 0x1d, bit: 2, label: "Dragon Head" },
                            { offset: 0x1d, bit: 3, label: "Iron Googles" },
                            { offset: 0x1d, bit: 4, label: "Cat Hood" },
                            { offset: 0x1d, bit: 5, label: "Ponytails" },
                            { offset: 0x1d, bit: 6, label: "Sunglasses" },
                            {
                              offset: 0x1d,
                              bit: 7,
                              label: "???",
                              hidden: true,
                            },
                            { offset: 0x93, bit: 0, label: "Chicken Head" },
                            { offset: 0x93, bit: 1, label: "Samourai Head" },
                            { offset: 0x93, bit: 2, label: "Clown Smile" },
                            { offset: 0x93, bit: 3, label: "Gold Visor" },
                            {
                              offset: 0x93,
                              bit: 4,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x93,
                              bit: 5,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x93,
                              bit: 6,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x93,
                              bit: 7,
                              label: "???",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      type: "section",
                      items: [
                        {
                          name: "Body",
                          offset: 0x1b,
                          type: "variable",
                          dataType: "upper4",
                          resource: "body",
                          autocomplete: true,
                        },
                        {
                          name: "Body Parts",
                          type: "bitflags",
                          flags: [
                            {
                              offset: 0x1e,
                              bit: 0,
                              label: "???",
                              hidden: true,
                            },
                            { offset: 0x1e, bit: 1, label: "Knight Armor" },
                            { offset: 0x1e, bit: 2, label: "Dragon Mail" },
                            { offset: 0x1e, bit: 3, label: "Iron Armor" },
                            { offset: 0x1e, bit: 4, label: "Cat Suit" },
                            { offset: 0x1e, bit: 5, label: "Dress" },
                            { offset: 0x1e, bit: 6, label: "Duck Float" },
                            {
                              offset: 0x1e,
                              bit: 7,
                              label: "???",
                              hidden: true,
                            },
                            { offset: 0x94, bit: 0, label: "Rocking Horse" },
                            { offset: 0x94, bit: 1, label: "Shogun Kimono" },
                            { offset: 0x94, bit: 2, label: "Karate Ware" },
                            { offset: 0x94, bit: 3, label: "Gold Armor" },
                            {
                              offset: 0x94,
                              bit: 4,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x94,
                              bit: 5,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x94,
                              bit: 6,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x94,
                              bit: 7,
                              label: "???",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      type: "section",
                      items: [
                        {
                          name: "Arms",
                          offset: 0x1c,
                          type: "variable",
                          dataType: "lower4",
                          resource: "arms",
                          autocomplete: true,
                        },
                        {
                          name: "Body Parts",
                          type: "bitflags",
                          flags: [
                            {
                              offset: 0x80,
                              bit: 0,
                              label: "???",
                              hidden: true,
                            },
                            { offset: 0x80, bit: 1, label: "Knight Sword" },
                            { offset: 0x80, bit: 2, label: "Dragon Gloves" },
                            { offset: 0x80, bit: 3, label: "Iron Knuckles" },
                            { offset: 0x80, bit: 4, label: "Cat Paws" },
                            { offset: 0x80, bit: 5, label: "Slash Claws" },
                            { offset: 0x80, bit: 6, label: "Drill Arms" },
                            {
                              offset: 0x80,
                              bit: 7,
                              label: "???",
                              hidden: true,
                            },
                            { offset: 0x95, bit: 0, label: "Chicken Wings" },
                            { offset: 0x95, bit: 1, label: "Fans" },
                            { offset: 0x95, bit: 2, label: "Boxing Gloves" },
                            { offset: 0x95, bit: 3, label: "Gold Gloves" },
                            {
                              offset: 0x95,
                              bit: 4,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x95,
                              bit: 5,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x95,
                              bit: 6,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x95,
                              bit: 7,
                              label: "???",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      type: "section",
                      items: [
                        {
                          name: "Legs",
                          offset: 0x1c,
                          type: "variable",
                          dataType: "upper4",
                          resource: "legs",
                          autocomplete: true,
                        },
                        {
                          name: "Body Parts",
                          type: "bitflags",
                          flags: [
                            {
                              offset: 0x81,
                              bit: 0,
                              label: "???",
                              hidden: true,
                            },
                            { offset: 0x81, bit: 1, label: "Knight Shoes" },
                            { offset: 0x81, bit: 2, label: "Dragon Spikes" },
                            { offset: 0x81, bit: 3, label: "Iron Sneakers" },
                            { offset: 0x81, bit: 4, label: "Cat Paws" },
                            { offset: 0x81, bit: 5, label: "High Tops" },
                            { offset: 0x81, bit: 6, label: "Duck Feet" },
                            {
                              offset: 0x81,
                              bit: 7,
                              label: "???",
                              hidden: true,
                            },
                            { offset: 0x96, bit: 0, label: "Bubby Socks" },
                            { offset: 0x96, bit: 1, label: "High Heels" },
                            { offset: 0x96, bit: 2, label: "Clogs" },
                            { offset: 0x96, bit: 3, label: "Gold Boots" },
                            {
                              offset: 0x96,
                              bit: 4,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x96,
                              bit: 5,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x96,
                              bit: 6,
                              label: "???",
                              hidden: true,
                            },
                            {
                              offset: 0x96,
                              bit: 7,
                              label: "???",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    arms: {
      0x0: "-",
      0x1: "Knight Sword",
      0x2: "Dragon Gloves",
      0x3: "Iron Knuckles",
      0x4: "Cat Paws",
      0x5: "Slash Claws",
      0x6: "Drill Arms",
      0x7: "Chicken Wings",
      0x8: "Fans",
      0x9: "Boxing Gloves",
      0xa: "Gold Gloves",
    },
    body: {
      0x0: "-",
      0x1: "Knight Armor",
      0x2: "Dragon Mail",
      0x3: "Iron Armor",
      0x4: "Cat Suit",
      0x5: "Dress",
      0x6: "Duck Float",
      0x7: "Rocking Horse",
      0x8: "Shogun Kimono",
      0x9: "Karate Ware",
      0xa: "Gold Armor",
    },
    difficulties: {
      0x0: "Normal",
      0x80: "Hard",
    },
    head: {
      0x0: "-",
      0x1: "Knight Helmet",
      0x2: "Dragon Head",
      0x3: "Iron Googles",
      0x4: "Cat Hood",
      0x5: "Ponytails",
      0x6: "Sunglasses",
      0x7: "Chicken Head",
      0x8: "Samourai Head",
      0x9: "Clown Smile",
      0xa: "Gold Visor",
    },
    legs: {
      0x0: "-",
      0x1: "Knight Shoes",
      0x2: "Dragon Spikes",
      0x3: "Iron Sneakers",
      0x4: "Cat Paws",
      0x5: "High Tops",
      0x6: "Duck Feet",
      0x7: "Bubby Socks",
      0x8: "High Heels",
      0x9: "Clogs",
      0xa: "Gold Boots",
    },
    letters: [
      // Europe / USA
      {
        0x0: " ",
        0xf: " ",
        0x10: "0",
        0x11: "1",
        0x12: "2",
        0x13: "3",
        0x14: "4",
        0x15: "5",
        0x16: "6",
        0x17: "7",
        0x18: "8",
        0x19: "9",
        0x1a: "A",
        0x1b: "B",
        0x1c: "C",
        0x1d: "D",
        0x1e: "E",
        0x1f: "F",
        0x20: "G",
        0x21: "H",
        0x22: "I",
        0x23: "J",
        0x24: "K",
        0x25: "L",
        0x26: "M",
        0x27: "N",
        0x28: "O",
        0x29: "P",
        0x2a: "Q",
        0x2b: "R",
        0x2c: "S",
        0x2d: "T",
        0x2e: "U",
        0x2f: "V",
        0x30: "W",
        0x31: "X",
        0x32: "Y",
        0x33: "Z",
        0x3a: "a",
        0x3b: "b",
        0x3c: "c",
        0x3d: "d",
        0x3e: "e",
        0x3f: "f",
        0x40: "g",
        0x41: "h",
        0x42: "i",
        0x43: "j",
        0x44: "k",
        0x45: "l",
        0x46: "m",
        0x47: "n",
        0x48: "o",
        0x49: "p",
        0x4a: "q",
        0x4b: "r",
        0x4c: "s",
        0x4d: "t",
        0x4e: "u",
        0x4f: "v",
        0x50: "w",
        0x51: "x",
        0x52: "y",
        0x53: "z",
        0xf6: "!",
        0xf7: "?",
        0xf8: ".",
        0xf9: "-",
        0xfa: "♥",
      },
      // Japan
      {
        0x0: " ",
        0xf: " ",
        0x10: "0",
        0x11: "1",
        0x12: "2",
        0x13: "3",
        0x14: "4",
        0x15: "5",
        0x16: "6",
        0x17: "7",
        0x18: "8",
        0x19: "9",
        0x1a: "A",
        0x1b: "B",
        0x1c: "C",
        0x1d: "D",
        0x1e: "E",
        0x1f: "F",
        0x20: "G",
        0x21: "H",
        0x22: "I",
        0x23: "J",
        0x24: "K",
        0x25: "L",
        0x26: "M",
        0x27: "N",
        0x28: "O",
        0x29: "P",
        0x2a: "Q",
        0x2b: "R",
        0x2c: "S",
        0x2d: "T",
        0x2e: "U",
        0x2f: "V",
        0x30: "W",
        0x31: "X",
        0x32: "Y",
        0x33: "Z",
        0x3a: "a",
        0x3b: "b",
        0x3c: "c",
        0x3d: "d",
        0x3e: "e",
        0x3f: "f",
        0x40: "g",
        0x41: "h",
        0x42: "i",
        0x43: "j",
        0x44: "k",
        0x45: "l",
        0x46: "m",
        0x47: "n",
        0x48: "o",
        0x49: "p",
        0x4a: "q",
        0x4b: "r",
        0x4c: "s",
        0x4d: "t",
        0x4e: "u",
        0x4f: "v",
        0x50: "w",
        0x51: "x",
        0x52: "y",
        0x53: "z",
        0x55: "ァ",
        0x56: "ィ",
        0x57: "ゥ",
        0x58: "ェ",
        0x59: "ォ",
        0x5a: "ッ",
        0x5b: "ャ",
        0x5c: "ュ",
        0x5d: "ョ",
        0x5e: "ヲ",
        0x5f: "ン",
        0x60: "ア",
        0x61: "イ",
        0x62: "ウ",
        0x63: "エ",
        0x64: "オ",
        0x65: "カ",
        0x66: "キ",
        0x67: "ク",
        0x68: "ケ",
        0x69: "コ",
        0x6a: "サ",
        0x6b: "シ",
        0x6c: "ス",
        0x6d: "セ",
        0x6e: "ソ",
        0x6f: "タ",
        0x70: "チ",
        0x71: "ツ",
        0x72: "テ",
        0x73: "ト",
        0x74: "ナ",
        0x75: "ニ",
        0x76: "ヌ",
        0x77: "ネ",
        0x78: "ノ",
        0x79: "ハ",
        0x7a: "ヒ",
        0x7b: "フ",
        0x7c: "ヘ",
        0x7d: "ホ",
        0x7e: "マ",
        0x7f: "ミ",
        0x80: "ム",
        0x81: "メ",
        0x82: "モ",
        0x83: "ヤ",
        0x84: "ユ",
        0x85: "ヨ",
        0x86: "ラ",
        0x87: "リ",
        0x88: "ル",
        0x89: "レ",
        0x8a: "ロ",
        0x8b: "ワ",
        0x8c: "ガ",
        0x8d: "ギ",
        0x8e: "グ",
        0x8f: "ゲ",
        0x90: "ゴ",
        0x91: "ザ",
        0x92: "ジ",
        0x93: "ズ",
        0x94: "ゼ",
        0x95: "ゾ",
        0x96: "ダ",
        0x97: "ヂ",
        0x98: "ヅ",
        0x99: "デ",
        0x9a: "ド",
        0x9b: "バ",
        0x9c: "ビ",
        0x9d: "ブ",
        0x9e: "ベ",
        0x9f: "ボ",
        0xa0: "パ",
        0xa1: "ピ",
        0xa2: "プ",
        0xa3: "ペ",
        0xa4: "ポ",
        0xa5: "ぁ",
        0xa6: "ぃ",
        0xa7: "ぅ",
        0xa8: "ぇ",
        0xa9: "ぉ",
        0xaa: "っ",
        0xab: "ゃ",
        0xac: "ゅ",
        0xad: "ょ",
        0xae: "を",
        0xaf: "ん",
        0xb0: "あ",
        0xb1: "い",
        0xb2: "う",
        0xb3: "え",
        0xb4: "お",
        0xb5: "か",
        0xb6: "き",
        0xb7: "く",
        0xb8: "け",
        0xb9: "こ",
        0xba: "さ",
        0xbb: "し",
        0xbc: "す",
        0xbd: "せ",
        0xbe: "そ",
        0xbf: "た",
        0xc0: "ち",
        0xc1: "つ",
        0xc2: "て",
        0xc3: "と",
        0xc4: "な",
        0xc5: "に",
        0xc6: "ぬ",
        0xc7: "ね",
        0xc8: "の",
        0xc9: "は",
        0xca: "ひ",
        0xcb: "ふ",
        0xcc: "へ",
        0xcd: "ほ",
        0xce: "ま",
        0xcf: "み",
        0xd0: "む",
        0xd1: "め",
        0xd2: "も",
        0xd3: "や",
        0xd4: "ゆ",
        0xd5: "よ",
        0xd6: "ら",
        0xd7: "り",
        0xd8: "る",
        0xd9: "れ",
        0xda: "ろ",
        0xdb: "わ",
        0xdc: "が",
        0xdd: "ぎ",
        0xde: "ぐ",
        0xdf: "げ",
        0xe0: "ご",
        0xe1: "ざ",
        0xe2: "じ",
        0xe3: "ず",
        0xe4: "ぜ",
        0xe5: "ぞ",
        0xe6: "だ",
        0xe7: "ぢ",
        0xe8: "づ",
        0xe9: "で",
        0xea: "ど",
        0xeb: "ば",
        0xec: "び",
        0xed: "ぶ",
        0xee: "べ",
        0xef: "ぼ",
        0xf0: "ぱ",
        0xf1: "ぴ",
        0xf2: "ぷ",
        0xf3: "ぺ",
        0xf4: "ぽ",
        0xf6: "!",
        0xf7: "?",
        0xf8: ".",
        0xf9: "ー",
        0xfa: "♥",
      },
    ],
  },
};

export default template;
