import { Resource, ResourceGroups } from "$lib/types";

export const abilityTypes = [
  {
    index: 0x7,
    name: "White Magic",
    abilities: [
      { index: 0x13c, abilityId: 0x6, name: "Cure" },
      { index: 0x13d, abilityId: 0x7, name: "Cura" },
      { index: 0x13e, abilityId: 0x8, name: "Curaga" },
      { index: 0x13f, abilityId: 0x9, name: "Curaja" },
      { index: 0x140, abilityId: 0xa, name: "Esuna" },
      { index: 0x141, abilityId: 0xb, name: "Life" },
      { index: 0x142, abilityId: 0xc, name: "Full-Life" },
      { index: 0x143, abilityId: 0xd, name: "Hold" },
      { index: 0x144, abilityId: 0xe, name: "Silence" },
      { index: 0x145, abilityId: 0xf, name: "Confuse" },
      { index: 0x146, abilityId: 0x10, name: "Blink" },
      { index: 0x147, abilityId: 0x11, name: "Protect" },
      { index: 0x148, abilityId: 0x12, name: "Shell" },
      { index: 0x149, abilityId: 0x13, name: "Slow" },
      { index: 0x14a, abilityId: 0x14, name: "Haste" },
      { index: 0x14b, abilityId: 0x15, name: "Berserk" },
      { index: 0x14c, abilityId: 0x16, name: "Reflect" },
      { index: 0x14d, abilityId: 0x17, name: "Holy" },
      { index: 0x14e, abilityId: 0x18, name: "Dispel" },
      { index: 0x14f, abilityId: 0x19, name: "Scan" },
      { index: 0x150, abilityId: 0x1a, name: "Mini" },
      { index: 0x151, abilityId: 0x1b, name: "Teleport" },
      { index: 0x152, abilityId: 0x1c, name: "Sight" },
      { index: 0x153, abilityId: 0x1d, name: "Float" },
    ],
  },
  {
    index: 0x8,
    name: "Black Magic",
    abilities: [
      { index: 0x157, abilityId: 0x21, name: "Fire" },
      { index: 0x158, abilityId: 0x22, name: "Fira" },
      { index: 0x159, abilityId: 0x23, name: "Firaga" },
      { index: 0x15a, abilityId: 0x24, name: "Blizzard" },
      { index: 0x15b, abilityId: 0x25, name: "Blizzara" },
      { index: 0x15c, abilityId: 0x26, name: "Blizzaga" },
      { index: 0x15d, abilityId: 0x27, name: "Thunder" },
      { index: 0x15e, abilityId: 0x28, name: "Thundara" },
      { index: 0x15f, abilityId: 0x29, name: "Thundaga" },
      { index: 0x160, abilityId: 0x2a, name: "Sleep" },
      { index: 0x161, abilityId: 0x2b, name: "Poison" },
      { index: 0x162, abilityId: 0x2c, name: "Warp" },
      { index: 0x163, abilityId: 0x2d, name: "Toad" },
      { index: 0x164, abilityId: 0x2e, name: "Stop" },
      { index: 0x165, abilityId: 0x2f, name: "Osmose" },
      { index: 0x166, abilityId: 0x30, name: "Bio" },
      { index: 0x167, abilityId: 0x31, name: "Tornado" },
      { index: 0x168, abilityId: 0x32, name: "Break" },
      { index: 0x169, abilityId: 0x33, name: "Pig" },
      { index: 0x16a, abilityId: 0x34, name: "Quake" },
      { index: 0x16b, abilityId: 0x35, name: "Death" },
      { index: 0x16c, abilityId: 0x36, name: "Meteor" },
      { index: 0x16d, abilityId: 0x37, name: "Flare" },
      { index: 0x16e, abilityId: 0x38, name: "Drain" },
    ],
  },
  {
    index: 0x9,
    name: "Summons",
    abilities: [
      { index: 0x173, abilityId: 0x3d, name: "Goblin" },
      { index: 0x174, abilityId: 0x3e, name: "Bomb" },
      { index: 0x175, abilityId: 0x3f, name: "Cockatrice" },
      { index: 0x176, abilityId: 0x40, name: "Mind Flayer" },
      { index: 0x177, abilityId: 0x41, name: "Chocobo" },
      { index: 0x178, abilityId: 0x42, name: "Shiva" },
      { index: 0x179, abilityId: 0x43, name: "Ramuh" },
      { index: 0x17a, abilityId: 0x44, name: "Ifrit" },
      { index: 0x17b, abilityId: 0x45, name: "Titan" },
      { index: 0x17c, abilityId: 0x46, name: "Mist Dragon" },
      { index: 0x17d, abilityId: 0x47, name: "Sylph" },
      { index: 0x17e, abilityId: 0x48, name: "Odin" },
      { index: 0x17f, abilityId: 0x49, name: "Leviathan" },
      { index: 0x180, abilityId: 0x4a, name: "Asura" },
      { index: 0x181, abilityId: 0x4b, name: "Bahamut" },
    ],
  },
  {
    index: 0xf,
    name: "Ninjutsu",
    abilities: [
      { index: 0x18b, abilityId: 0x55, name: "Flame" },
      { index: 0x18c, abilityId: 0x56, name: "Flood" },
      { index: 0x18d, abilityId: 0x57, name: "Blitz" },
      { index: 0x18e, abilityId: 0x58, name: "Smoke" },
      { index: 0x18f, abilityId: 0x59, name: "Pin" },
      { index: 0x190, abilityId: 0x5a, name: "Mirage" },
    ],
  },
];

export const locations: { [key: string]: string } = {
  MSG_MAP_NAME_01: "Overworld",
  MSG_MAP_NAME_02: "Underworld",
  MSG_MAP_NAME_03: "Moon",
  MSG_MAP_NAME_04: "Castle Baron",
  MSG_MAP_NAME_05: "Town of Baron",
  MSG_MAP_NAME_06: "Kaipo, Oasis of the Desert",
  MSG_MAP_NAME_07: "Damcyan Castle",
  MSG_MAP_NAME_08: "Fabul Castle",
  MSG_MAP_NAME_09: "Mysidia",
  MSG_MAP_NAME_10: "Mist",
  MSG_MAP_NAME_11: "Mythril",
  MSG_MAP_NAME_12: "Eblan Castle",
  MSG_MAP_NAME_13: "Town of Troia",
  MSG_MAP_NAME_14: "Troia Castle",
  MSG_MAP_NAME_15: "Agart",
  MSG_MAP_NAME_16: "Adamant Grotto",
  MSG_MAP_NAME_17: "Dwarven Castle",
  MSG_MAP_NAME_18: "Tomra",
  MSG_MAP_NAME_19: "Kokkol's Smithy",
  MSG_MAP_NAME_20: "Hummingway Home",
  MSG_MAP_NAME_21: "Crystal Palace",
  MSG_MAP_NAME_23: "Chocobo Village",
  MSG_MAP_NAME_24: "Underground Waterway",
  MSG_MAP_NAME_25: "Antlion Cave",
  MSG_MAP_NAME_26: "Mt. Hobs",
  MSG_MAP_NAME_27: "Mt. Ordeals",
  MSG_MAP_NAME_28: "Old Waterway",
  MSG_MAP_NAME_29: "Magnetic Cavern",
  MSG_MAP_NAME_30: "Tower of Zot",
  MSG_MAP_NAME_31: "Tower of Babel",
  MSG_MAP_NAME_32: "Cave of Eblan",
  MSG_MAP_NAME_33: "Sylvan Cave",
  MSG_MAP_NAME_34: "Cave of Summons",
  MSG_MAP_NAME_35: "Land of Summons",
  MSG_MAP_NAME_36: "Sealed Cavern",
  MSG_MAP_NAME_37: "Lunar Path",
  MSG_MAP_NAME_38: "Cave of Bahamut",
  MSG_MAP_NAME_39: "Giant of Babel",
  MSG_MAP_NAME_40: "Lunar Subterrane",
  MSG_MAP_NAME_41: "Mist Cave",
  MSG_MAP_NAME_42: "CECIL)'s Chamber",
  MSG_MAP_NAME_43: "Black Magic Research Lab",
  MSG_MAP_NAME_44: "White Magic Research Lab",
  MSG_MAP_NAME_45: "CID)'s House",
  MSG_MAP_NAME_46: "ROZA)'s House",
  MSG_MAP_NAME_47: "Training Room",
  MSG_MAP_NAME_48: "Manor of Prayers",
  MSG_MAP_NAME_49: "King's Pub",
  MSG_MAP_NAME_50: "Black Chocobo Farm",
  MSG_MAP_NAME_51: "Chocobo Farm B1",
  MSG_MAP_NAME_52: "Observatory",
  MSG_MAP_NAME_53: "Observation Room",
  MSG_MAP_NAME_54: "Dwarven Base",
  MSG_MAP_NAME_55: "Lali-ho Pub",
  MSG_MAP_NAME_56: "Waterfall",
  MSG_MAP_NAME_59: "Antlion Nest",
  MSG_MAP_NAME_60: "Path to the Tower of Babel",
  MSG_MAP_NAME_62: "Library",
  MSG_MAP_NAME_63: "Mouth of the Giant",
  MSG_MAP_NAME_64: "Neck of the Giant",
  MSG_MAP_NAME_65: "Chest of the Giant",
  MSG_MAP_NAME_66: "Stomach of the Giant",
  MSG_MAP_NAME_67: "Inner Path of the Giant",
  MSG_MAP_NAME_69: "Eblan Settlement",
  MSG_MAP_NAME_70: "Chocobo Forest, Baron Area",
  MSG_MAP_NAME_71: "Chocobo Forest, Fabul Area",
  MSG_MAP_NAME_72: "Chocobo Forest, Mysidia Area",
  MSG_MAP_NAME_73: "Chocobo Forest, Troia Area",
  MSG_MAP_NAME_74: "Chocobo Forest, Southern Island",
  MSG_MAP_NAME_75: "Sylvan Cottage",
  MSG_MAP_NAME_76: "Subterranean Lake",
  MSG_MAP_NAME_77: "Mist Cave, South Entrance",
  MSG_MAP_NAME_78: "Mist Cave, North Entrance",
  MSG_MAP_NAME_79: "Underground Waterway, South Entrance",
  MSG_MAP_NAME_80: "Underground Waterway, North Entrance",
  MSG_MAP_NAME_81: "Mt. Hobs, West Entrance",
  MSG_MAP_NAME_82: "Mt. Hobs, East Entrance",
  MSG_MAP_NAME_83: "Western Lunar Path, South Entrance",
  MSG_MAP_NAME_84: "Western Lunar Path, North Entrance",
  MSG_MAP_NAME_85: "Eastern Lunar Path, North Entrance",
  MSG_MAP_NAME_86: "Eastern Lunar Path, South Entrance",
  MSG_MAP_NAME_87: "Tower of Worship",
  MSG_MAP_NAME_88: "Eastern Lunar Path",
  MSG_MAP_NAME_89: "Western Lunar Path",
  MSG_MAP_NAME_90: "Infirmary",
};

export const bestiary = [
  { index: 0x1, name: "001 Goblin" },
  { index: 0x3, name: "002 Helldiver" },
  { index: 0x4, name: "003 Floating Eyeball" },
  { index: 0x8, name: "004 Sword Rat" },
  { index: 0x5, name: "005 Insectus" },
  { index: 0xa, name: "006 Desert Sahagin" },
  { index: 0xb, name: "007 Flying Eyes" },
  { index: 0xc, name: "008 Hundlegs" },
  { index: 0xd, name: "009 Sand Worm" },
  { index: 0x14, name: "010 Red Mousse" },
  { index: 0xe, name: "011 Gigantoad" },
  { index: 0x10, name: "012 Zombie" },
  { index: 0xf, name: "013 Vile Shell" },
  { index: 0x13, name: "014 Toadgre" },
  { index: 0x16, name: "015 Sahagin" },
  { index: 0x11, name: "016 Killer Fish" },
  { index: 0x9, name: "017 Tiny Mage" },
  { index: 0x2a, name: "018 Water Bug" },
  { index: 0x2b, name: "019 Alligator" },
  { index: 0x1e, name: "020 Baron Soldier" },
  { index: 0x1f, name: "021 General" },
  { index: 0x1c, name: "022 Domovoi" },
  { index: 0x15, name: "023 Yellow Jelly" },
  { index: 0x2, name: "024 Basilisk" },
  { index: 0x17, name: "025 Leshy" },
  { index: 0x1b, name: "026 Adamantoise" },
  { index: 0x56, name: "027 Bomb" },
  { index: 0x23, name: "028 Spirit" },
  { index: 0x57, name: "029 Gray Bomb" },
  { index: 0x24, name: "030 Skeleton" },
  { index: 0x25, name: "031 Cockatrice" },
  { index: 0x26, name: "032 Gargoyle" },
  { index: 0x30, name: "033 Bloodbones" },
  { index: 0x20, name: "034 Gatlinger" },
  { index: 0x2d, name: "035 Baron Warrior" },
  { index: 0x2e, name: "036 Captain" },
  { index: 0x29, name: "037 Zu" },
  { index: 0x2f, name: "038 Soul" },
  { index: 0x31, name: "039 Ghoul" },
  { index: 0x33, name: "040 Revenant" },
  { index: 0x5e, name: "041 Lilith" },
  { index: 0xd4, name: "042 Skullnant" },
  { index: 0x2c, name: "043 Splasher" },
  { index: 0x39, name: "044 Hydra" },
  { index: 0x3b, name: "045 Baron Guard" },
  { index: 0x37, name: "046 Electrofish" },
  { index: 0x38, name: "047 Gigas Gator" },
  { index: 0x4a, name: "048 Death Shell" },
  { index: 0x3a, name: "049 Flood Worm" },
  { index: 0x3e, name: "050 Twin Snake" },
  { index: 0x7, name: "051 Treant" },
  { index: 0x43, name: "052 Cait Sith" },
  { index: 0x3d, name: "053 Hell Needle" },
  { index: 0x22, name: "054 Death Flower" },
  { index: 0x34, name: "055 Draculady" },
  { index: 0x35, name: "056 Cave Naga" },
  { index: 0x40, name: "057 Mind Flayer" },
  { index: 0x6, name: "058 Cave Bat" },
  { index: 0x42, name: "059 Ogre" },
  { index: 0x1d, name: "060 Purple Bavarois" },
  { index: 0x48, name: "061 Puppet" },
  { index: 0x7b, name: "062 Sorceress" },
  { index: 0x44, name: "063 Black Knight" },
  { index: 0x45, name: "064 Centaur Knight" },
  { index: 0x71, name: "065 Gremlin" },
  { index: 0x4e, name: "066 Soldieress" },
  { index: 0x47, name: "067 Puppeteer" },
  { index: 0x76, name: "068 Ice Lizard" },
  { index: 0x79, name: "069 Cold Beast" },
  { index: 0x59, name: "070 Hell Turtle" },
  { index: 0x27, name: "071 Roc Baby" },
  { index: 0x12, name: "072 Blood Flower" },
  { index: 0x62, name: "073 Roc" },
  { index: 0x61, name: "074 Mors" },
  { index: 0x94, name: "075 Steel Golem" },
  { index: 0x19, name: "076 Goblin Captain" },
  { index: 0x4d, name: "077 Armadillo" },
  { index: 0x53, name: "078 Magma Tortoise" },
  { index: 0x72, name: "079 Undergrounder" },
  { index: 0x77, name: "080 Hell Flapper" },
  { index: 0x18, name: "081 Chrysalis" },
  { index: 0x49, name: "082 Gloomwing" },
  { index: 0x5c, name: "083 Gorgon" },
  { index: 0xe0, name: "084 Mystery Egg" },
  { index: 0x5a, name: "085 Ironback" },
  { index: 0x82, name: "086 White Mousse" },
  { index: 0x41, name: "087 Naga" },
  { index: 0x65, name: "088 Evil Doll" },
  { index: 0x51, name: "089 Medusa" },
  { index: 0x68, name: "090 Fiery Knight" },
  { index: 0x6e, name: "091 Coeurl" },
  { index: 0x6a, name: "092 Balloon" },
  { index: 0x58, name: "093 Chimera" },
  { index: 0x1a, name: "094 Black Lizard" },
  { index: 0x63, name: "095 Sorcerer" },
  { index: 0x4f, name: "096 Ghost Knight" },
  { index: 0x5f, name: "097 Lamia Matriarch" },
  { index: 0x3c, name: "098 Lamia" },
  { index: 0x3f, name: "099 Grudger" },
  { index: 0x5b, name: "100 Fiery Hound" },
  { index: 0x88, name: "101 Security Eye" },
  { index: 0x64, name: "102 Mad Ogre" },
  { index: 0x86, name: "103 Green Dragon" },
  { index: 0x5d, name: "104 Stone Golem" },
  { index: 0x85, name: "105 Mythril Golem" },
  { index: 0x66, name: "106 Bloody Bat" },
  { index: 0x32, name: "107 Skuldier" },
  { index: 0x60, name: "108 Tiny Toad" },
  { index: 0x7d, name: "109 Bog Witch" },
  { index: 0x55, name: "110 Evil Dreamer" },
  { index: 0x7e, name: "111 Mammon" },
  { index: 0x8c, name: "112 Malboro" },
  { index: 0x28, name: "113 Belphegor" },
  { index: 0x74, name: "114 Bloody Eye" },
  { index: 0x4c, name: "115 Warrior" },
  { index: 0x8f, name: "116 Mini Satana" },
  { index: 0x7a, name: "117 Summoner" },
  { index: 0x67, name: "118 Arachne" },
  { index: 0x9e, name: "119 Thunder Dragon" },
  { index: 0x78, name: "120 Evil Bat" },
  { index: 0x4b, name: "121 Screamer" },
  { index: 0x50, name: "122 King Naga" },
  { index: 0x46, name: "123 Miss Vamp" },
  { index: 0x8e, name: "124 Yellow Dragon" },
  { index: 0x7f, name: "125 Chimera Brain" },
  { index: 0x7c, name: "126 Trap Door" },
  { index: 0x80, name: "127 Lunar Virus" },
  { index: 0x90, name: "128 Eukaryote" },
  { index: 0x75, name: "129 Crawler" },
  { index: 0x9a, name: "130 Prokaryote" },
  { index: 0x73, name: "131 Abyss Worm" },
  { index: 0x83, name: "132 Black Flan" },
  { index: 0x6b, name: "133 Dark Grenade" },
  { index: 0x70, name: "134 Tarantula" },
  { index: 0x69, name: "135 Beamer" },
  { index: 0x92, name: "136 Centaurion" },
  { index: 0x89, name: "137 Mech Soldier" },
  { index: 0x97, name: "138 Searcher" },
  { index: 0x6d, name: "139 Last Arm" },
  { index: 0x8a, name: "140 Giant Soldier" },
  { index: 0x6f, name: "141 Mech Dragon" },
  { index: 0x8b, name: "142 Selene Guardian" },
  { index: 0x98, name: "143 Dark Sage" },
  { index: 0x8d, name: "144 Silver Dragon" },
  { index: 0x9d, name: "145 Gold Dragon" },
  { index: 0x36, name: "146 Bone Dragon" },
  { index: 0x52, name: "147 Dinozombie" },
  { index: 0x21, name: "148 Li\'l Murderer" },
  { index: 0x93, name: "149 Giant Warrior" },
  { index: 0x9c, name: "150 Blue Dragon" },
  { index: 0xa0, name: "151 Red Dragon" },
  { index: 0x95, name: "152 Ahriman" },
  { index: 0xa1, name: "153 Behemoth" },
  { index: 0x91, name: "154 Wicked Mask" },
  { index: 0x84, name: "155 Zemus\'s Mind" },
  { index: 0x81, name: "156 Zemus\'s Breath" },
  { index: 0x87, name: "157 Flan Princess" },
  { index: 0xa3, name: "158 Octomammoth" },
  { index: 0xa4, name: "159 Antlion" },
  { index: 0xa5, name: "160 Mom Bomb" },
  { index: 0xa8, name: "161 Baigan" },
  { index: 0xa9, name: "162 Right Arm" },
  { index: 0xaa, name: "163 Left Arm" },
  { index: 0xad, name: "164 Dark Elf" },
  { index: 0xc4, name: "165 Dark Dragon" },
  { index: 0xae, name: "166 Sandy" },
  { index: 0xaf, name: "167 Cindy" },
  { index: 0xb0, name: "168 Mindy" },
  { index: 0xb3, name: "169 Calco" },
  { index: 0xd3, name: "170 Brina" },
  { index: 0xb4, name: "171 Calcobrena" },
  { index: 0xb5, name: "172 Golbez" },
  { index: 0xb7, name: "173 Doctor" },
  { index: 0xb8, name: "174 Barnabas" },
  { index: 0xb9, name: "175 Dr. Lugae" },
  { index: 0xd5, name: "176 Barnabas-Z" },
  { index: 0xa6, name: "177 Scarmiglione" },
  { index: 0xa7, name: "178 Scarmiglione" },
  { index: 0xab, name: "179 Cagnazzo" },
  { index: 0xb2, name: "180 Barbariccia" },
  { index: 0xbc, name: "181 Rubicante" },
  { index: 0xc0, name: "182 Demon Wall" },
  { index: 0xc7, name: "183 Defense Node" },
  { index: 0xd6, name: "184 Attack Node" },
  { index: 0xc6, name: "185 CPU" },
  { index: 0x96, name: "186 Lunasaur" },
  { index: 0x6c, name: "187 Plague" },
  { index: 0x9f, name: "188 White Dragon" },
  { index: 0x9b, name: "189 Ogopogo" },
  { index: 0x99, name: "190 Dark Bahamut" },
  { index: 0xa2, name: "191 Mist Dragon" },
  { index: 0xc1, name: "192 Asura" },
  { index: 0xbe, name: "193 Leviathan" },
  { index: 0xbd, name: "194 Odin" },
  { index: 0xbf, name: "195 Bahamut" },
  { index: 0xc9, name: "196 Zeromus" },
  { index: 0xca, name: "197 Zeromus" },
];

export const charactersStatus = [
  // Cecil (Dark Knight)
  {
    level: 10,
    currentExp: 1500,
    favoredHand: "right",
    maxHp: 200,
    maxMp: 0,
    power: 13,
    agility: 10,
    vitality: 11,
    intelligence: 6,
    spirit: 3,
  },
  // Kain
  {
    level: 10,
    currentExp: 1150,
    favoredHand: "left",
    maxHp: 190,
    maxMp: 0,
    power: 9,
    agility: 11,
    vitality: 9,
    intelligence: 6,
    spirit: 12,
  },
  // Rosa
  {
    level: 10,
    currentExp: 1070,
    favoredHand: "right",
    maxHp: 150,
    maxMp: 80,
    power: 8,
    agility: 8,
    vitality: 6,
    intelligence: 10,
    spirit: 18,
  },
  // Rydia
  {
    level: 1,
    currentExp: 0,
    favoredHand: "right",
    maxHp: 30,
    maxMp: 10,
    power: 3,
    agility: 4,
    vitality: 2,
    intelligence: 8,
    spirit: 5,
  },
  // Cid
  {
    level: 20,
    currentExp: 13377,
    favoredHand: "right",
    maxHp: 788,
    maxMp: 0,
    power: 21,
    agility: 9,
    vitality: 24,
    intelligence: 5,
    spirit: 5,
  },
  // Tellah
  {
    level: 20,
    currentExp: 27437,
    favoredHand: "right",
    maxHp: 340,
    maxMp: 90,
    power: 5,
    agility: 8,
    vitality: 7,
    intelligence: 16,
    spirit: 16,
  },
  // Edward
  {
    level: 5,
    currentExp: 194,
    favoredHand: "right",
    maxHp: 60,
    maxMp: 0,
    power: 6,
    agility: 9,
    vitality: 2,
    intelligence: 7,
    spirit: 7,
  },
  // Yang
  {
    level: 10,
    currentExp: 1031,
    favoredHand: "both",
    maxHp: 300,
    maxMp: 0,
    power: 12,
    agility: 8,
    vitality: 15,
    intelligence: 2,
    spirit: 3,
  },
  // Palom
  {
    level: 10,
    currentExp: 979,
    favoredHand: "left",
    maxHp: 100,
    maxMp: 50,
    power: 7,
    agility: 8,
    vitality: 5,
    intelligence: 15,
    spirit: 10,
  },
  // Porom
  {
    level: 10,
    currentExp: 979,
    favoredHand: "right",
    maxHp: 110,
    maxMp: 50,
    power: 8,
    agility: 7,
    vitality: 6,
    intelligence: 10,
    spirit: 15,
  },
  // Edge
  {
    level: 25,
    currentExp: 32389,
    favoredHand: "both",
    maxHp: 790,
    maxMp: 60,
    power: 20,
    agility: 23,
    vitality: 17,
    intelligence: 12,
    spirit: 12,
  },
  // FuSoYa
  {
    level: 50,
    currentExp: 503933,
    favoredHand: "right",
    maxHp: 1900,
    maxMp: 190,
    power: 10,
    agility: 20,
    vitality: 10,
    intelligence: 40,
    spirit: 40,
  },
  // Cecil (Paladin)
  {
    level: 1,
    currentExp: 0,
    favoredHand: "right",
    maxHp: 600,
    maxMp: 10,
    power: 10,
    agility: 13,
    vitality: 10,
    intelligence: 5,
    spirit: 8,
  },
];

export const inventory = [
  {
    name: "Items",
    sections: [
      {
        name: "",
        items: [
          { index: 0x2, name: "Potion" },
          { index: 0x3, name: "Hi-Potion" },
          { index: 0x4, name: "X-Potion" },
          { index: 0x5, name: "Ether" },
          { index: 0x6, name: "Dry Ether" },
          { index: 0x7, name: "Elixir" },
          { index: 0x9, name: "Phoenix Down" },
          { index: 0xa, name: "Gold Needle" },
          { index: 0xb, name: "Maiden's Kiss" },
          { index: 0xc, name: "Mallet" },
          { index: 0xd, name: "Diet Food" },
          { index: 0xe, name: "Echo Herbs" },
          { index: 0xf, name: "Eye Drops" },
          { index: 0x10, name: "Antidote" },
          { index: 0x11, name: "Cross" },
          { index: 0x12, name: "Remedy" },
          { index: 0x13, name: "Alarm Clock" },
          { index: 0x14, name: "Unicorn Horn" },
          { index: 0x15, name: "Tent" },
          { index: 0x16, name: "Cottage" },
          { index: 0x17, name: "Emergency Exit" },
          { index: 0x18, name: "Dwarven Bread" },
          { index: 0x19, name: "Gysahl Greens" },
          { index: 0x1a, name: "Gysahl Whistle" },
          { index: 0x1b, name: "Golden Apple" },
          { index: 0x1c, name: "Silver Apple" },
          { index: 0x1d, name: "Soma Drop" },
          { index: 0x1e, name: "Siren" },
          { index: 0x21, name: "Red Fang" },
          { index: 0x22, name: "White Fang" },
          { index: 0x23, name: "Blue Fang" },
          { index: 0x24, name: "Bomb Fragment" },
          { index: 0x25, name: "Bomb Arm" },
          { index: 0x26, name: "Antarctic Wind" },
          { index: 0x27, name: "Arctic Wind" },
          { index: 0x28, name: "Zeus's Wrath" },
          { index: 0x29, name: "Rage of the Gods" },
          { index: 0x2a, name: "Gaia Drum" },
          { index: 0x2b, name: "Bomb Core" },
          { index: 0x2c, name: "Stardust" },
          { index: 0x2d, name: "Lilith's Kiss" },
          { index: 0x2e, name: "Vampire Fang" },
          { index: 0x2f, name: "Spider's Silk" },
          { index: 0x30, name: "Bell of Silence" },
          { index: 0x31, name: "Coeurl Whisker" },
          { index: 0x32, name: "Bestiary" },
          { index: 0x33, name: "Hourglass" },
          { index: 0x34, name: "Silver Hourglass" },
          { index: 0x35, name: "Gold Hourglass" },
          { index: 0x36, name: "Bacchus's Cider" },
          { index: 0x37, name: "Hermes Shoes" },
          { index: 0x38, name: "Decoy" },
          { index: 0x39, name: "Light Curtain" },
          { index: 0x3a, name: "Lunar Curtain" },
          { index: 0x3b, name: "Crystal" },
          { index: 0x3c, name: "Membership Pass" },
          { index: 0x4c, name: "Goblin" },
          { index: 0x4d, name: "Bomb" },
          { index: 0x4e, name: "Cockatrice" },
          { index: 0x4f, name: "Mind Flayer" },
          { index: 0x208, name: "Grimoire" },
        ],
      },
    ],
  },
  {
    name: "Key Items",
    sections: [
      {
        name: "",
        items: [
          { index: 0x3e, name: "Frying Pan" },
          { index: 0x3f, name: "Adamantite" },
          { index: 0x40, name: "Sand Ruby" },
          { index: 0x41, name: "Dark Matter" },
          { index: 0x42, name: "Earth Crystal" },
          { index: 0x43, name: "Rat Tail" },
          { index: 0x44, name: "Baron Key" },
          { index: 0x45, name: "Twin Harp" },
          { index: 0x46, name: "Pink Tail" },
          { index: 0x47, name: "Bomb Ring" },
          { index: 0x48, name: "Magma Rock" },
          { index: 0x49, name: "Dark Crystal" },
          { index: 0x4a, name: "Luca's Necklace" },
          { index: 0x4b, name: "Dr. Lugae's Key" },
        ],
      },
    ],
  },
  {
    name: "Weapons",
    sections: [
      {
        name: "Dark Swords",
        items: [
          { index: 0x80, name: "Dark Sword" },
          { index: 0x81, name: "Shadowblade" },
          { index: 0x82, name: "Deathbringer" },
        ],
      },
      {
        name: "Holy Swords",
        items: [
          { index: 0x83, name: "Sword of Legend" },
          { index: 0x84, name: "Light Sword" },
          { index: 0x85, name: "Excalibur" },
          { index: 0x86, name: "Ragnarok" },
        ],
      },
      {
        name: "Swords",
        items: [
          { index: 0x87, name: "Ancient Sword" },
          { index: 0x88, name: "Blood Sword" },
          { index: 0x89, name: "Mythril Sword" },
          { index: 0x8a, name: "Sleep Blade" },
          { index: 0x8b, name: "Flame Sword" },
          { index: 0x8c, name: "Icebrand" },
          { index: 0x8d, name: "Gorgon Blade" },
          { index: 0x8e, name: "Avenger" },
          { index: 0x8f, name: "Defender" },
        ],
      },
      {
        name: "Spears",
        items: [
          { index: 0x94, name: "Spear" },
          { index: 0x95, name: "Wind Spear" },
          { index: 0x96, name: "Fire Lance" },
          { index: 0x97, name: "Ice Lance" },
          { index: 0x98, name: "Blood Lance" },
          { index: 0x99, name: "Gungnir" },
          { index: 0x9a, name: "Wyvern Lance" },
          { index: 0x9b, name: "Holy Lance" },
        ],
      },
      {
        name: "Knives",
        items: [
          { index: 0x9c, name: "Mythril Knife" },
          { index: 0x9d, name: "Dancing Dagger" },
          { index: 0x9e, name: "Mage Masher" },
          { index: 0x9f, name: "Knife" },
        ],
      },
      {
        name: "Harps",
        items: [
          { index: 0xa0, name: "Dreamer's Harp" },
          { index: 0xa1, name: "Lamia's Harp" },
        ],
      },
      {
        name: "Claws",
        items: [
          { index: 0xa2, name: "Fire Claw" },
          { index: 0xa3, name: "Ice Claw" },
          { index: 0xa4, name: "Thunder Claw" },
          { index: 0xa5, name: "Fairy Claw" },
          { index: 0xa6, name: "Hell Claw" },
          { index: 0xa7, name: "Cat Claw" },
        ],
      },
      {
        name: "Hammers",
        items: [
          { index: 0xa8, name: "Wooden Hammer" },
          { index: 0xa9, name: "Mythril Hammer" },
          { index: 0xaa, name: "Gaia Hammer" },
        ],
      },
      {
        name: "Axes",
        items: [
          { index: 0xab, name: "Dwarven Axe" },
          { index: 0xac, name: "Ogrekiller" },
          { index: 0xad, name: "Poison Axe" },
          { index: 0xae, name: "Rune Axe" },
        ],
      },
      {
        name: "Ninja Swords",
        items: [
          { index: 0xaf, name: "Kunai" },
          { index: 0xb0, name: "Ashura" },
          { index: 0xb1, name: "Kotetsu" },
          { index: 0xb2, name: "Kikuichimonji" },
          { index: 0xb3, name: "Murasame" },
          { index: 0xb4, name: "Masamune" },
        ],
      },
      {
        name: "Rods",
        items: [
          { index: 0xb5, name: "Rod" },
          { index: 0xb6, name: "Flame Rod" },
          { index: 0xb7, name: "Ice Rod" },
          { index: 0xb8, name: "Thunder Rod" },
          { index: 0xb9, name: "Lilith Rod" },
          { index: 0xba, name: "Rod of Change" },
          { index: 0xbb, name: "Fairy Rod" },
          { index: 0xbc, name: "Stardust Rod" },
        ],
      },
      {
        name: "Staves",
        items: [
          { index: 0xbd, name: "Staff" },
          { index: 0xbe, name: "Healing Staff" },
          { index: 0xbf, name: "Mythril Staff" },
          { index: 0xc0, name: "Power Staff" },
          { index: 0xc1, name: "Kinesis Staff" },
          { index: 0xc2, name: "Sage's Staff" },
          { index: 0xc3, name: "Rune Staff" },
        ],
      },
      {
        name: "Bows",
        items: [
          { index: 0xc4, name: "Bow" },
          { index: 0xc6, name: "Great Bow" },
          { index: 0xc7, name: "Killer Bow" },
          { index: 0xc8, name: "Elven Bow" },
          { index: 0xc9, name: "Yoichi's Bow" },
          { index: 0xca, name: "Artemis's Bow" },
          { index: 0x209, name: "Crossbow" },
        ],
      },
      {
        name: "Arrows",
        items: [
          { index: 0xcb, name: "Medusa Arrow" },
          { index: 0xcc, name: "Iron Arrow" },
          { index: 0xcd, name: "Holy Arrow" },
          { index: 0xce, name: "Fire Arrow" },
          { index: 0xcf, name: "Ice Arrow" },
          { index: 0xd0, name: "Thunder Arrow" },
          { index: 0xd1, name: "Blinding Arrow" },
          { index: 0xd2, name: "Poison Arrow" },
          { index: 0xd3, name: "Mute Arrow" },
          { index: 0xd4, name: "Angel Arrow" },
          { index: 0xd5, name: "Yoichi Arrow" },
          { index: 0xd6, name: "Artemis Arrow" },
        ],
      },
      {
        name: "Whips",
        items: [
          { index: 0xd7, name: "Whip" },
          { index: 0xd8, name: "Chain Whip" },
          { index: 0xd9, name: "Blitz Whip" },
          { index: 0xda, name: "Flame Whip" },
          { index: 0xdb, name: "Dragon's Whisker" },
        ],
      },
      {
        name: "Boomerangs",
        items: [
          { index: 0xdc, name: "Boomerang" },
          { index: 0xdd, name: "Moonring Blade" },
        ],
      },
      {
        name: "Shurikens",
        items: [
          { index: 0xde, name: "Shuriken" },
          { index: 0xdf, name: "Fuma Shuriken" },
        ],
      },
    ],
  },
  {
    name: "Shields",
    sections: [
      {
        name: "",
        items: [
          { index: 0xe4, name: "Iron Shield" },
          { index: 0xe5, name: "Dark Shield" },
          { index: 0xe6, name: "Demon Shield" },
          { index: 0xe7, name: "Light Shield" },
          { index: 0xe8, name: "Mythril Shield" },
          { index: 0xe9, name: "Flame Shield" },
          { index: 0xea, name: "Ice Shield" },
          { index: 0xeb, name: "Diamond Shield" },
          { index: 0xec, name: "Aegis Shield" },
          { index: 0xed, name: "Genji Shield" },
          { index: 0xee, name: "Dragon Shield" },
          { index: 0xef, name: "Crystal Shield" },
        ],
      },
    ],
  },
  {
    name: "Hats",
    sections: [
      {
        name: "",
        items: [
          { index: 0xf1, name: "Leather Cap" },
          { index: 0xf2, name: "Headband" },
          { index: 0xf3, name: "Feathered Cap" },
          { index: 0xf4, name: "Iron Helm" },
          { index: 0xf5, name: "Wizard's Hat" },
          { index: 0xf6, name: "Green Beret" },
          { index: 0xf7, name: "Dark Helm" },
          { index: 0xf8, name: "Hades Helm" },
          { index: 0xf9, name: "Sage's Miter" },
          { index: 0xfa, name: "Black Cowl" },
          { index: 0xfb, name: "Demon Helm" },
          { index: 0xfc, name: "Light Helm" },
          { index: 0xfd, name: "Gold Hairpin" },
          { index: 0xfe, name: "Mythril Helm" },
          { index: 0xff, name: "Diamond Helm" },
          { index: 0x100, name: "Ribbon" },
          { index: 0x101, name: "Genji Helm" },
          { index: 0x102, name: "Dragon Helm" },
          { index: 0x103, name: "Crystal Helm" },
          { index: 0x104, name: "Glass Mask" },
        ],
      },
    ],
  },
  {
    name: "Armor",
    sections: [
      {
        name: "Armor",
        items: [
          { index: 0x10b, name: "Iron Armor" },
          { index: 0x10c, name: "Dark Armor" },
          { index: 0x10f, name: "Hades Armor" },
          { index: 0x111, name: "Demon Armor" },
          { index: 0x113, name: "Knight's Armor" },
          { index: 0x115, name: "Mythril Armor" },
          { index: 0x116, name: "Flame Mail" },
          { index: 0x118, name: "Ice Armor" },
          { index: 0x11a, name: "Diamond Armor" },
          { index: 0x11c, name: "Genji Armor" },
          { index: 0x11f, name: "Crystal Mail" },
          { index: 0x120, name: "Adamant Armor" },
        ],
      },
      {
        name: "Light Armor",
        items: [
          { index: 0x106, name: "Clothes" },
          { index: 0x107, name: "Prisoners' Wear" },
          { index: 0x108, name: "Leather Garb" },
          { index: 0x109, name: "Bard's Tunic" },
          { index: 0x10a, name: "Gaia Gear" },
          { index: 0x10d, name: "Sage's Surplice" },
          { index: 0x10e, name: "Kenpo Gi" },
          { index: 0x110, name: "Black Robe" },
          { index: 0x112, name: "Black Belt Gi" },
          { index: 0x114, name: "Light Robe" },
          { index: 0x117, name: "Power Sash" },
          { index: 0x119, name: "White Robe" },
          { index: 0x11b, name: "Minerva Bustier" },
          { index: 0x11d, name: "Dragon Mail" },
          { index: 0x11e, name: "Black Garb" },
        ],
      },
    ],
  },
  {
    name: "Gloves",
    sections: [
      {
        name: "",
        items: [
          { index: 0x122, name: "Ruby Ring" },
          { index: 0x123, name: "Cursed Ring" },
          { index: 0x124, name: "Iron Gloves" },
          { index: 0x125, name: "Dark Gloves" },
          { index: 0x126, name: "Iron Armlet" },
          { index: 0x127, name: "Power Armlet" },
          { index: 0x128, name: "Hades Gloves" },
          { index: 0x129, name: "Demon Gloves" },
          { index: 0x12a, name: "Silver Armlet" },
          { index: 0x12b, name: "Gauntlets" },
          { index: 0x12c, name: "Rune Armlet" },
          { index: 0x12d, name: "Mythril Gloves" },
          { index: 0x12e, name: "Diamond Armlet" },
          { index: 0x12f, name: "Diamond Gloves" },
          { index: 0x130, name: "Genji Gloves" },
          { index: 0x131, name: "Dragon Gloves" },
          { index: 0x132, name: "Giant's Gloves" },
          { index: 0x133, name: "Crystal Gloves" },
          { index: 0x134, name: "Protect Ring" },
          { index: 0x135, name: "Crystal Ring" },
        ],
      },
    ],
  },
];

export const arms: Resource = [];
export const bodies: Resource = [];
export const hands: Resource = [];
export const heads: Resource = [];

export const bodiesGroups = inventory.reduce(
  (groups: ResourceGroups, type, typeIndex) => {
    if (typeIndex === 5) {
      type.sections.forEach((section) => {
        groups.push({ name: section.name, options: [] });
      });
    }

    return groups;
  },
  [],
);

export const handsGroups = inventory.reduce(
  (groups: ResourceGroups, type, typeIndex) => {
    if (typeIndex === 2) {
      type.sections.forEach((section) => {
        groups.push({ name: section.name, options: [] });
      });
    } else if (typeIndex === 3) {
      groups.push({ name: type.name, options: [] });
    }

    return groups;
  },
  [],
);

inventory.forEach((type, typeIndex) => {
  type.sections.forEach((section, sectionIndex) => {
    section.items.forEach((item) => {
      switch (typeIndex) {
        case 2:
          hands[item.index] = item.name;
          handsGroups[sectionIndex].options.push(item.index);
          break;
        case 3:
          hands[item.index] = item.name;
          handsGroups.at(-1)!.options.push(item.index);
          break;
        case 4:
          heads[item.index] = item.name;
          break;
        case 5:
          bodies[item.index] = item.name;
          bodiesGroups[sectionIndex].options.push(item.index);
          break;
        case 6:
          arms[item.index] = item.name;
          break;
      }
    });
  });
});

export const vehicles = [
  { index: 0x0, name: "???" },
  { index: 0x1, name: "Hovercraft" },
  { index: 0x2, name: "Entreprise" },
  { index: 0x3, name: "Falcon (Underworld)" },
  { index: 0x4, name: "Lunar Whale (Overworld)" },
  { index: 0x5, name: "Chocobo" },
  { index: 0x6, name: "Black Chocobo" },
  { index: 0x7, name: "Falcon (Upgraded / Underworld)" },
  { index: 0x8, name: "Falcon (Drill)" },
  { index: 0x9, name: "Entreprise (Hook)" },
  { index: 0xa, name: "Lunar Whale (Moon)" },
];
