import type { GameJson } from "$lib/types";

import { X09_POINTERS } from "./utils/constants";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa: { 0x20: [0x4d, 0x4b, 0x2d, 0x38, 0x31, 0x33, 0x30, 0x36] }, // "MK-81306"
      japan: { 0x20: [0x54, 0x2d, 0x33, 0x33, 0x31, 0x30, 0x31, 0x47] }, // "T-33101G"
    },
    text: "Drag 'n' drop here or click to add a rom file.",
    hint: "Only works with .bin (merged) and .iso files.",
    error: "Not a valid rom file.",
  },
  items: [
    {
      type: "tabs",
      items: [
        {
          name: "Party",
          items: [
            {
              pointer: X09_POINTERS.party,
              length: 0x20,
              type: "container",
              instanceType: "tabs",
              instances: 8,
              resource: "characterNames",
              vertical: true,
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "cName-%index%",
                      name: "Name",
                      offset: 0x0,
                      length: 0x6,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      disabled: true,
                    },
                    {
                      name: "Class",
                      dataViewAltKey: "x09",
                      offset: 0x0,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "classes",
                      autocomplete: true,
                    },
                    {
                      name: "???",
                      dataViewAltKey: "x09",
                      offset: 0x2,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Experience",
                      dataViewAltKey: "x09",
                      offset: 0x4,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      disabled: true,
                    },
                    {
                      name: "Base Next Experience",
                      dataViewAltKey: "x09",
                      offset: 0xc,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Next Experience",
                      dataViewAltKey: "x09",
                      offset: 0x8,
                      type: "variable",
                      dataType: "uint32",
                      bigEndian: true,
                      hidden: true,
                    },
                  ],
                },
                {
                  length: 0x2,
                  type: "container",
                  instanceType: "section",
                  instances: 8,
                  flex: true,
                  noMargin: true,
                  items: [
                    {
                      id: "cItem",
                      name: "Item %d",
                      dataViewAltKey: "x09",
                      offset: 0x10,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      binary: {
                        bitStart: 0,
                        bitLength: 12,
                      },
                      resource: "itemNames",
                      autocomplete: true,
                    },
                    {
                      id: "cItemStatus",
                      name: "Status",
                      dataViewAltKey: "x09",
                      offset: 0x10,
                      type: "variable",
                      dataType: "uint8",
                      binary: {
                        bitStart: 6,
                        bitLength: 2,
                      },
                      resource: "itemStatus",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Classes",
          planned: true,
          items: [
            {
              pointer: X09_POINTERS.classes,
              length: 0x50,
              type: "container",
              instanceType: "tabs",
              instances: 16,
              resource: "classNames",
              vertical: true,
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "clName-%index%",
                      name: "Name",
                      offset: 0x0,
                      length: 0x6,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      disabled: true,
                    },
                  ],
                },
                {
                  length: 0x8,
                  type: "container",
                  instanceType: "section",
                  instances: 10,
                  resource: "stats",
                  flex: true,
                  items: [
                    {
                      name: "???",
                      dataViewAltKey: "x09",
                      offset: 0x0,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      // min: 0
                      // max: 0
                    },
                    {
                      name: "???",
                      dataViewAltKey: "x09",
                      offset: 0x2,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      // min: 0
                      // max: 0
                    },
                    {
                      name: "???",
                      dataViewAltKey: "x09",
                      offset: 0x4,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      // min: 0
                      // max: 0
                    },
                    {
                      name: "???",
                      dataViewAltKey: "x09",
                      offset: 0x6,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      // min: 0
                      // max: 0
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Magic",
          items: [
            {
              pointer: X09_POINTERS.magic,
              length: 0x3c,
              type: "container",
              instanceType: "tabs",
              instances: 14,
              enumeration: "Page %d",
              vertical: true,
              items: [
                {
                  length: 0x6,
                  type: "container",
                  instanceType: "section",
                  instances: 10,
                  noMargin: true,
                  flex: true,
                  items: [
                    {
                      name: "Class",
                      dataViewAltKey: "x09",
                      offset: 0x0,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "classes",
                      autocomplete: true,
                    },
                    {
                      name: "Required Level",
                      dataViewAltKey: "x09",
                      offset: 0x2,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      min: 1,
                      max: 99,
                    },
                    {
                      name: "Spell",
                      dataViewAltKey: "x09",
                      offset: 0x4,
                      type: "variable",
                      dataType: "uint8",
                      resource: "spellNames",
                      autocomplete: true,
                    },
                    {
                      name: "Level",
                      dataViewAltKey: "x09",
                      offset: 0x5,
                      type: "variable",
                      dataType: "uint8",
                      operations: [{ "+": 1 }],
                      min: 1,
                      max: 4,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Items",
          items: [
            {
              pointer: X09_POINTERS.items,
              instanceId: "items",
              length: 0x10,
              type: "container",
              instanceType: "tabs",
              instances: 210,
              resource: "itemNames",
              vertical: true,
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      type: "component",
                      component: "IconCanvas",
                      props: { itemIndex: "items" },
                    },
                    {
                      id: "iName-%index%",
                      name: "Name",
                      offset: 0x0,
                      length: 0xe,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      disabled: true,
                    },
                    {
                      id: "iDescription-%index%",
                      name: "Description",
                      offset: 0x0,
                      length: 0xe,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      size: "xl",
                      disabled: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Type",
                      dataViewAltKey: "x09",
                      offset: 0x3,
                      type: "variable",
                      dataType: "uint8",
                      resource: "itemTypeNames",
                      autocomplete: true,
                    },
                    {
                      name: "Price",
                      dataViewAltKey: "x09",
                      offset: 0x0,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Equippable by",
                      dataViewAltKey: "x09",
                      type: "bitflags",
                      flags: [
                        { offset: 0x7, bit: 0, label: "Swordsman" },
                        { offset: 0x7, bit: 1, label: "Shaman" },
                        { offset: 0x7, bit: 2, label: "Ninja" },
                        { offset: 0x7, bit: 3, label: "Dragon Warrior" },
                        { offset: 0x7, bit: 4, label: "Kunoichi" },
                        { offset: 0x7, bit: 5, label: "Magician" },
                        { offset: 0x7, bit: 6, label: "Halfling" },
                        { offset: 0x7, bit: 7, label: "Knight" },
                        { offset: 0x6, bit: 0, label: "Champion" },
                        { offset: 0x6, bit: 1, label: "Summoner" },
                        { offset: 0x6, bit: 2, label: "Master Ninja" },
                        { offset: 0x6, bit: 3, label: "Dragon Knight" },
                        { offset: 0x6, bit: 4, label: "Chief Kunoichi" },
                        { offset: 0x6, bit: 5, label: "Sorcerer" },
                        { offset: 0x6, bit: 6, label: "Berserker" },
                        { offset: 0x6, bit: 7, label: "Paladin" },
                      ],
                    },
                    {
                      type: "section",
                      items: [
                        {
                          name: "Special",
                          dataViewAltKey: "x09",
                          type: "bitflags",
                          flags: [
                            { offset: 0x2, bit: 0, label: "Curses when equipped" },
                            { offset: 0x2, bit: 1, label: "Usable" },
                            { offset: 0x2, bit: 2, label: "Consumable" },
                            { offset: 0x2, bit: 3, label: "Rare item" },
                            { offset: 0x2, bit: 4, label: "Quest item" },
                            { offset: 0x2, bit: 5, label: "???", hidden: true },
                            { offset: 0x2, bit: 6, label: "???", hidden: true },
                            { offset: 0x2, bit: 7, label: "???", hidden: true },
                          ],
                        },
                        {
                          name: "Body Parts",
                          dataViewAltKey: "x09",
                          type: "bitflags",
                          flags: [
                            { offset: 0x5, bit: 0, label: "Head" },
                            { offset: 0x5, bit: 1, label: "Left Hand" },
                            { offset: 0x5, bit: 2, label: "Right Hand" },
                            { offset: 0x5, bit: 3, label: "Left Arm" },
                            { offset: 0x5, bit: 4, label: "Right Arm" },
                            { offset: 0x5, bit: 5, label: "Left Shoulder" },
                            { offset: 0x5, bit: 6, label: "Right Shoulder" },
                            { offset: 0x5, bit: 7, label: "Torso" },
                            { offset: 0x4, bit: 0, label: "Waist" },
                            { offset: 0x4, bit: 1, label: "Legs" },
                            { offset: 0x4, bit: 2, label: "Feet" },
                            { offset: 0x4, bit: 3, label: "???", hidden: true },
                            { offset: 0x4, bit: 4, label: "???", hidden: true },
                            { offset: 0x4, bit: 5, label: "???", hidden: true },
                            { offset: 0x4, bit: 6, label: "???", hidden: true },
                            { offset: 0x4, bit: 7, label: "???", hidden: true },
                          ],
                        },
                      ],
                    },
                    {
                      length: 0x1,
                      type: "container",
                      instanceType: "section",
                      instances: 4,
                      flex: true,
                      noMargin: true,
                      items: [
                        {
                          id: "iEffectType",
                          name: "Effect %d",
                          dataViewAltKey: "x09",
                          offset: 0x8,
                          type: "variable",
                          dataType: "uint8",
                          resource: "itemEffects",
                          autocomplete: true,
                        },
                        {
                          id: "iEffectValue",
                          name: "Value",
                          dataViewAltKey: "x09",
                          offset: 0xc,
                          type: "variable",
                          dataType: "int8",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Enemies",
          items: [
            {
              pointer: X09_POINTERS.enemies,
              length: 0x50,
              type: "container",
              instanceType: "tabs",
              instances: 104,
              resource: "enemyNames",
              vertical: true,
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "eName-%index%",
                      name: "Name",
                      offset: 0x0,
                      length: 0xe,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      disabled: true,
                    },
                    {
                      name: "Turns",
                      dataViewAltKey: "x09",
                      offset: 0x14,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      min: 1,
                      max: 30,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  noMargin: true,
                  items: [
                    {
                      name: "HP",
                      dataViewAltKey: "x09",
                      offset: 0x0,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      min: 0,
                    },
                    {
                      name: "MP",
                      dataViewAltKey: "x09",
                      offset: 0x2,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      min: 0,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Attack",
                      dataViewAltKey: "x09",
                      offset: 0x4,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      min: 0,
                    },
                    {
                      name: "Defense",
                      dataViewAltKey: "x09",
                      offset: 0x6,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      min: 0,
                    },
                    {
                      name: "Magic Defense",
                      dataViewAltKey: "x09",
                      offset: 0x10,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      min: 0,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Gold",
                      dataViewAltKey: "x09",
                      offset: 0x44,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      min: 0,
                    },
                    {
                      name: "Experience",
                      dataViewAltKey: "x09",
                      offset: 0x46,
                      type: "variable",
                      dataType: "int16",
                      bigEndian: true,
                      min: 0,
                    },
                    {
                      name: "Drop Item",
                      dataViewAltKey: "x09",
                      offset: 0x4a,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "dropItems",
                      autocomplete: true,
                    },
                    {
                      name: "Drop Rate",
                      dataViewAltKey: "x09",
                      offset: 0x4d,
                      type: "variable",
                      dataType: "uint8",
                      resource: "enemyDropRates",
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      id: "ability",
                      name: "Ability 1",
                      dataViewAltKey: "x09",
                      offset: 0x20,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "abilities",
                      autocomplete: true,
                    },
                    {
                      id: "ability",
                      name: "Ability 2",
                      dataViewAltKey: "x09",
                      offset: 0x22,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "abilities",
                      autocomplete: true,
                    },
                    {
                      id: "ability",
                      name: "Ability 3",
                      dataViewAltKey: "x09",
                      offset: 0x24,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "abilities",
                      autocomplete: true,
                    },
                    {
                      id: "ability",
                      name: "Ability 4",
                      dataViewAltKey: "x09",
                      offset: 0x26,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "abilities",
                      autocomplete: true,
                    },
                    {
                      id: "ability",
                      name: "Ability 5",
                      dataViewAltKey: "x09",
                      offset: 0x28,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "abilities",
                      autocomplete: true,
                    },
                    {
                      id: "ability",
                      name: "Ability 6",
                      dataViewAltKey: "x09",
                      offset: 0x2a,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "abilities",
                      autocomplete: true,
                    },
                    {
                      id: "ability",
                      name: "Ability 7",
                      dataViewAltKey: "x09",
                      offset: 0x2c,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "abilities",
                      autocomplete: true,
                    },
                    {
                      id: "ability",
                      name: "Ability 8",
                      dataViewAltKey: "x09",
                      offset: 0x2e,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      resource: "abilities",
                      autocomplete: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      name: "Unknown 8",
                      dataViewAltKey: "x09",
                      offset: 0x8,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Unknown e",
                      dataViewAltKey: "x09",
                      offset: 0xe,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Unknown 1a",
                      dataViewAltKey: "x09",
                      offset: 0x1a,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Unknown 1c",
                      dataViewAltKey: "x09",
                      offset: 0x1c,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      hidden: true,
                    },
                    {
                      name: "Unknown 42",
                      dataViewAltKey: "x09",
                      offset: 0x42,
                      type: "variable",
                      dataType: "uint16",
                      bigEndian: true,
                      hidden: true,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Shops",
          items: [
            {
              type: "tabs",
              items: [
                {
                  name: "Purchasable Items",
                  items: [
                    {
                      id: "shops",
                      pointer: X09_POINTERS.shops,
                      length: 0x0,
                      type: "container",
                      instanceType: "tabs",
                      instances: 0,
                      enumeration: "Shop %d",
                      vertical: true,
                      items: [...Array(20).keys()].map((index) => ({
                        id: `shopItemSection-%index%-${index}`,
                        type: "section",
                        flex: true,
                        noMargin: true,
                        items: [
                          {
                            id: `shopItem-%index%-${index}-item`,
                            name: `Item ${index + 1}`,
                            dataViewAltKey: "x09",
                            offset: 0x0,
                            type: "variable",
                            dataType: "uint16",
                            bigEndian: true,
                            resource: "itemNames",
                            autocomplete: true,
                          },
                          {
                            id: `shopItem-%index%-${index}-type`,
                            name: "Type",
                            dataViewAltKey: "x09",
                            offset: 0x0,
                            type: "variable",
                            dataType: "uint16",
                            bigEndian: true,
                            resource: "saleType",
                            disabled: true,
                          },
                          {
                            id: `shopItem-%index%-${index}-flag`,
                            name: "Flag",
                            dataViewAltKey: "x09",
                            offset: 0x2,
                            type: "variable",
                            dataType: "uint16",
                            bigEndian: true,
                          },
                        ],
                      })),
                    },
                  ],
                },
                {
                  name: "Sellable Items",
                  items: [
                    {
                      pointer: X09_POINTERS.blacksmith,
                      length: 0x0,
                      type: "container",
                      instanceType: "section",
                      instances: 1,
                      flex: true,
                      items: [...Array(116).keys()].map((index) => ({
                        name: `Item ${index + 1}`,
                        dataViewAltKey: "x09",
                        offset: index * 0x2,
                        type: "variable",
                        dataType: "uint16",
                        bigEndian: true,
                        resource: "dropItems",
                        autocomplete: true,
                      })),
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Blacksmith",
          items: [
            {
              pointer: X09_POINTERS.blacksmith,
              length: 0x0,
              type: "container",
              instanceType: "section",
              instances: 1,
              items: [
                {
                  type: "tabs",
                  items: [
                    {
                      name: "Mithril Ingot",
                      items: [
                        {
                          length: 0x8,
                          type: "container",
                          instanceType: "section",
                          instances: 8,
                          resource: "characters",
                          flex: true,
                          items: [
                            {
                              name: "Item 1",
                              dataViewAltKey: "x09",
                              offset: 0x180,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                            {
                              name: "Item 2",
                              dataViewAltKey: "x09",
                              offset: 0x182,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                            {
                              name: "Item 3",
                              dataViewAltKey: "x09",
                              offset: 0x184,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                            {
                              name: "Item 4",
                              dataViewAltKey: "x09",
                              offset: 0x186,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Mithril Ore",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          noMargin: true,
                          items: [
                            {
                              name: "Item 1",
                              dataViewAltKey: "x09",
                              offset: 0x1c0,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                            {
                              name: "Item 2",
                              dataViewAltKey: "x09",
                              offset: 0x1c2,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                            {
                              name: "Item 3",
                              dataViewAltKey: "x09",
                              offset: 0x1c4,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                            {
                              name: "Item 4",
                              dataViewAltKey: "x09",
                              offset: 0x1c6,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          noMargin: true,
                          items: [
                            {
                              name: "Item 5",
                              dataViewAltKey: "x09",
                              offset: 0x1c8,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                            {
                              name: "Item 6",
                              dataViewAltKey: "x09",
                              offset: 0x1ca,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                            {
                              name: "Item 7",
                              dataViewAltKey: "x09",
                              offset: 0x1cc,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                            {
                              name: "Item 8",
                              dataViewAltKey: "x09",
                              offset: 0x1ce,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              resource: "dropItems",
                              autocomplete: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Asset Viewer",
          items: [
            {
              type: "tabs",
              items: [
                {
                  name: "Text Files",
                  items: [
                    {
                      id: "assetViewer-txt",
                      instanceId: "txtViewer",
                      length: 0x2,
                      type: "container",
                      instanceType: "tabs",
                      instances: 0,
                      resource: "assetTxtNames",
                      vertical: true,
                      flex: true,
                      items: [
                        {
                          type: "component",
                          component: "TxtViewer",
                          props: { assetIndex: "txtViewer" },
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Images",
                  items: [
                    {
                      id: "assetViewer-image",
                      instanceId: "imageViewer",
                      length: 0x2,
                      type: "container",
                      instanceType: "tabs",
                      instances: 0,
                      resource: "assetImageNames",
                      vertical: true,
                      flex: true,
                      items: [
                        {
                          type: "component",
                          component: "ImageViewer",
                          props: { assetIndex: "imageViewer", type: "image" },
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Sprites",
                  items: [
                    {
                      id: "assetViewer-sprite",
                      instanceId: "spriteViewer",
                      length: 0x2,
                      type: "container",
                      instanceType: "tabs",
                      instances: 0,
                      resource: "assetSpriteNames",
                      vertical: true,
                      flex: true,
                      items: [
                        {
                          type: "component",
                          component: "ImageViewer",
                          props: { assetIndex: "spriteViewer", type: "sprite" },
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    assetTxtNames: "getAssetNames('txt')",
    assetImageNames: "getAssetNames('image')",
    assetSpriteNames: "getAssetNames('sprite')",
    characterNames: "getCharacterNames()",
    characters: {
      0x0: "Arthur",
      0x1: "Melody",
      0x2: "Rodi",
      0x3: "Basso",
      0x4: "Akane",
      0x5: "Forte",
      0x6: "Doyle",
      0x7: "Lisa",
    },
    classNames: "getClassNames(true)",
    classes: "getClassNames()",
    dropItems: "getItemNames(true)",
    enemyDropRates: {
      0x0: "-",
      0x1: "100.00%",
      0x2: "50.00%",
      0x3: "33.33%",
      0x4: "25.00%",
      0x5: "20.00%",
      0x6: "16.66%",
      0x7: "14.285%",
      0x8: "12.50%",
      0x9: "6.25%",
      0xa: "3.125%",
      0xb: "1.562%",
      0xc: "0.781%",
      0xd: "0.390%",
      0xe: "On Hit",
    },
    enemyNames: "getEnemyNames()",
    itemEffects: {
      0x0: "+ Attack",
      0x1: "+ Defense",
      0x2: "+ Agility",
      0x3: "+ Critical",
      0x4: "+ Technique",
      0x5: "+ Luck",
      0x6: "+ Magic Defense",
      0x7: "+ Breath Defense",
      0x10: "Inflict Poison",
      0x11: "Inflict Sleep",
      0x12: "Inflict Paralyse",
      0x13: "Inflict Confusion",
      0x14: "Inflict Blind",
      0x15: "Inflict Silence",
      0x17: "???",
      0x18: "???",
      0x20: "HP Regen",
      0x21: "MP Regen",
      0xff: "-",
    },
    itemNames: "getItemNames()",
    itemStatus: {
      0x0: "-",
      0x1: "Broken",
      0x2: "Equipped",
      0x3: "Broken + Equipped",
    },
    itemTypeNames: "getItemTypeNames()",
    saleType: {
      0x0: "Sale",
      0x1: "???",
      0x2: "Haggle",
    },
    spellNames: "getSpellNames()",
    stats: {
      0x0: "Max HP",
      0x1: "Max MP",
      0x2: "Attack",
      0x3: "Defense",
      0x4: "Agility",
      0x5: "Critical",
      0x6: "Technique",
      0x7: "Luck",
      0x8: "Magic Defense",
      0x9: "Breath Defense",
    },
  },
  resourcesOrder: {
    dropItems: [0xffff],
    itemEffects: [0xff],
    itemNames: [0xfff],
  },
};

export default template;
