import type { GameJson } from "$lib/types";

const template: GameJson = {
  validator: {
    regions: {
      usa: {
        0xffb0: [0x43, 0x33, 0x41, 0x43, 0x54, 0x45], // C3ACTE
      },
      japan: {
        0xffb0: [0x43, 0x33, 0x41, 0x43, 0x54, 0x4a], // C3ACTJ
      },
    },
    text: "Drag 'n' drop here or click to add a rom file.",
    error: "Not a valid rom file.",
  },
  items: [
    {
      type: "tabs",
      items: [
        {
          name: "Party",
          items: [
            {
              // id: "party",
              length: 0x50,
              type: "container",
              instanceType: "tabs",
              instances: 7,
              resource: "characterNames",
              vertical: true,
              items: [
                {
                  type: "tabs",
                  items: [
                    {
                      name: "Status",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Portrait",
                              offset: 0xc0000,
                              type: "variable",
                              dataType: "uint8",
                              resource: "portraits",
                            },
                            // {
                            //   id: "cName-%index%",
                            //   name: "Name",
                            //   offset: 0x1b006e,
                            //   length: 0x5,
                            //   type: "variable",
                            //   dataType: "string",
                            //   letterDataType: "uint8",
                            //   fallback: 0xef,
                            //   endCode: 0x0,
                            //   resource: "letters",
                            //   overrideShift: {
                            //     parent: 1,
                            //     shift: 0x6,
                            //   },
                            // },
                            {
                              // id: "level",
                              name: "Level",
                              offset: 0xc0012,
                              type: "variable",
                              dataType: "uint8",
                              min: 1,
                              max: 99,
                            },
                            {
                              // id: "experience",
                              name: "Experience",
                              offset: 0xc0013,
                              type: "variable",
                              dataType: "uint24",
                              max: 9999999,
                            },
                            {
                              name: "Tech Points",
                              offset: 0xc0016,
                              type: "variable",
                              dataType: "uint24",
                              max: 9999999,
                            },
                            {
                              name: "Next Experience",
                              offset: 0xc002b,
                              type: "variable",
                              dataType: "uint16",
                              hidden: true,
                            },
                            {
                              name: "Next Tech Points",
                              offset: 0xc002d,
                              type: "variable",
                              dataType: "uint16",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "HP",
                              type: "group",
                              mode: "fraction",
                              items: [
                                {
                                  offset: 0xc0003,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                                {
                                  offset: 0xc0005,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                              ],
                            },
                            {
                              name: "MP",
                              type: "group",
                              mode: "fraction",
                              items: [
                                {
                                  offset: 0xc0007,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 99,
                                },
                                {
                                  offset: 0xc0009,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 99,
                                },
                              ],
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              // id: "baseStats-36",
                              name: "Base Power",
                              offset: 0xc000b,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              // id: "baseStats-36",
                              name: "Base Stamina",
                              offset: 0xc000c,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              // id: "baseStats-36",
                              name: "Base Speed",
                              offset: 0xc000d,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              // id: "baseStats-38",
                              name: "Base Magic",
                              offset: 0xc000e,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              // id: "baseStats-35",
                              name: "Base Hit",
                              offset: 0xc000f,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              // id: "baseStats-35",
                              name: "Base Evade",
                              offset: 0xc0010,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                            {
                              // id: "baseStats-36",
                              name: "Base Magic Defense",
                              offset: 0xc0011,
                              type: "variable",
                              dataType: "uint8",
                              max: 99,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          hidden: true,
                          items: [
                            {
                              name: "Base Power",
                              offset: 0xc002f,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Stamina",
                              offset: 0xc0030,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Speed",
                              offset: 0xc0031,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Magic",
                              offset: 0xc0034,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Hit",
                              offset: 0xc0032,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Evade",
                              offset: 0xc0033,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Base Magic Defense",
                              offset: 0xc0035,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Equipment",
                      flex: true,
                      items: [
                        {
                          name: "Weapon",
                          offset: 0xc0029,
                          type: "variable",
                          dataType: "uint8",
                          resource: "weapons",
                          autocomplete: true,
                        },
                        {
                          name: "Helmet",
                          offset: 0xc0027,
                          type: "variable",
                          dataType: "uint8",
                          resource: "helmets",
                          autocomplete: true,
                        },
                        {
                          name: "Armor",
                          offset: 0xc0028,
                          type: "variable",
                          dataType: "uint8",
                          resource: "armors",
                          autocomplete: true,
                        },
                        {
                          name: "Accessory",
                          offset: 0xc002a,
                          type: "variable",
                          dataType: "uint8",
                          resource: "accessories",
                          autocomplete: true,
                        },
                      ],
                    },
                    {
                      name: "Tech",
                      flex: true,
                      items: [
                        {
                          name: "Tech Count",
                          offset: 0xc0230,
                          type: "variable",
                          dataType: "uint8",
                          overrideShift: {
                            parent: 1,
                            shift: 0x1,
                          },
                          hidden: true,
                        },
                        // ...tech.map(
                        //   (type, index) =>
                        //     ({
                        //       id: `tech-%index%-${index}`,
                        //       name: type.name,
                        //       type: "bitflags",
                        //       flags: type.techs.map((tech) => ({
                        //         offset: 0xc0237 + bitToOffset(tech.index),
                        //         bit: tech.index % 8,
                        //         label: tech.name,
                        //       })),
                        //     }) as ItemBitflags,
                        // ),
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Inventory",
          items: [
            {
              type: "tabs",
              items: [
                {
                  name: "Weapons",
                  items: [
                    {
                      id: "weapons",
                      length: 0x05,
                      type: "container",
                      instanceType: "tabs",
                      instances: 90,
                      resource: "weaponNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-weapons",
                              name: "Name",
                              offset: 0xc0b5f,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-weapons",
                              name: "Icon",
                              offset: 0xc0b5e,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                              resource: "icons",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Attack",
                              offset: 0xc0262,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                            },
                            {
                              name: "Unknown c0263",
                              offset: 0xc0263,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c0264",
                              offset: 0xc0264,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c0265",
                              offset: 0xc0265,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c0266",
                              offset: 0xc0266,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Armor",
                  items: [
                    {
                      id: "armor",
                      length: 0x03,
                      type: "container",
                      instanceType: "tabs",
                      instances: 33,
                      resource: "armorNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-armors",
                              name: "Name",
                              offset: 0xc0b5f,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-armors",
                              name: "Icon",
                              offset: 0xc0b5e,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                              resource: "icons",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Defense",
                              offset: 0xc047e,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                            },
                            {
                              name: "Unknown c047f",
                              offset: 0xc047f,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c0480",
                              offset: 0xc0480,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Helmets",
                  items: [
                    {
                      id: "helmets",
                      length: 0x03,
                      type: "container",
                      instanceType: "tabs",
                      instances: 25,
                      resource: "helmetNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-helmets",
                              name: "Name",
                              offset: 0xc0b5f,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-helmets",
                              name: "Icon",
                              offset: 0xc0b5e,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                              resource: "icons",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Defense",
                              offset: 0xc04e1,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                            },
                            {
                              name: "Unknown c04e2",
                              offset: 0xc04e2,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c04e3",
                              offset: 0xc04e3,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Accessories",
                  items: [
                    {
                      id: "accessories",
                      length: 0x04,
                      type: "container",
                      instanceType: "tabs",
                      instances: 40,
                      resource: "accessoryNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-accessories",
                              name: "Name",
                              offset: 0xc0b5f,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-accessories",
                              name: "Icon",
                              offset: 0xc0b5e,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                              resource: "icons",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Unknown c052c",
                              offset: 0xc052c,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c052d",
                              offset: 0xc052d,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c052e",
                              offset: 0xc052e,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c052f",
                              offset: 0xc052f,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Items",
                  items: [
                    {
                      id: "items",
                      length: 0x04,
                      type: "container",
                      instanceType: "tabs",
                      instances: 19,
                      resource: "itemNames",
                      vertical: true,
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "iName-items",
                              name: "Name",
                              offset: 0xc0b5f,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xef,
                              resource: "letters",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                            },
                            {
                              id: "iIcon-items",
                              name: "Icon",
                              offset: 0xc0b5e,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0xb,
                              },
                              resource: "icons",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Effect?",
                              offset: 0xc05cc,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c05cd",
                              offset: 0xc05cd,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c05ce",
                              offset: 0xc05ce,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                            {
                              name: "Unknown c05cf",
                              offset: 0xc05cf,
                              type: "variable",
                              dataType: "uint8",
                              // max:
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Enemies",
          items: [
            {
              id: "enemies",
              length: 0x17,
              type: "container",
              instanceType: "tabs",
              instances: 256,
              resource: "enemyNames",
              vertical: true,
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "eEnemy",
                      name: "Name",
                      offset: 0x1e00,
                      length: 0xb,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      fallback: 0xef,
                      resource: "letters",
                      overrideShift: {
                        parent: 1,
                        shift: 0xb,
                      },
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "HP",
                      offset: 0x0,
                      type: "variable",
                      dataType: "uint16",
                      // max: 999,
                    },
                    {
                      name: "Unknown 2",
                      offset: 0x2,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 3",
                      offset: 0x3,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 4",
                      offset: 0x4,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 5",
                      offset: 0x5,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 6",
                      offset: 0x6,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 7",
                      offset: 0x7,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 8",
                      offset: 0x8,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 9",
                      offset: 0x9,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown a",
                      offset: 0xa,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Precision",
                      offset: 0xb,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                    },
                    {
                      name: "Evade",
                      offset: 0xc,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                    },
                    {
                      name: "Magic Defense",
                      offset: 0xd,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                    },
                    {
                      name: "Attack",
                      offset: 0xe,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                    },
                    {
                      name: "Defense",
                      offset: 0xf,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                    },
                    {
                      name: "Unknown 10",
                      offset: 0x10,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 11",
                      offset: 0x11,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 12",
                      offset: 0x12,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 13",
                      offset: 0x13,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 14",
                      offset: 0x14,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Death Animation?",
                      offset: 0x15,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                    {
                      name: "Unknown 16",
                      offset: 0x16,
                      type: "variable",
                      dataType: "uint8",
                      // max: ,
                      hidden: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "eDrops",
                      name: "Experience",
                      offset: 0x1700,
                      type: "variable",
                      dataType: "uint16",
                      overrideShift: {
                        parent: 1,
                        shift: 0x7,
                      },
                      // max: ,
                    },
                    {
                      id: "eDrops",
                      name: "Gold",
                      offset: 0x1702,
                      type: "variable",
                      dataType: "uint16",
                      overrideShift: {
                        parent: 1,
                        shift: 0x7,
                      },
                      // max: ,
                    },
                    {
                      id: "eDrops",
                      name: "Drop Item",
                      offset: 0x1704,
                      type: "variable",
                      dataType: "uint8",
                      overrideShift: {
                        parent: 1,
                        shift: 0x7,
                      },
                      resource: "dropItems",
                      autocomplete: true,
                    },
                    {
                      id: "eDrops",
                      name: "Unknown 1705",
                      offset: 0x1705,
                      type: "variable",
                      dataType: "uint8",
                      overrideShift: {
                        parent: 1,
                        shift: 0x7,
                      },
                      // max: ,
                      hidden: true,
                    },
                    {
                      id: "eDrops",
                      name: "Tech Points",
                      offset: 0x1706,
                      type: "variable",
                      dataType: "uint8",
                      overrideShift: {
                        parent: 1,
                        shift: 0x7,
                      },
                      // max: ,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Shops",
          items: [],
        },
        {
          name: "Map Viewer",
          items: [
            {
              instanceId: "mapViewer",
              length: 0x2,
              type: "container",
              instanceType: "tabs",
              instances: 255,
              enumeration: "Map %d",
              vertical: true,
              flex: true,
              items: [
                {
                  type: "component",
                  component: "MapViewer",
                  props: { roomIndex: "mapViewer" },
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    accessories: "getInventoryNames('accessories', true)",
    accessoryNames: "getInventoryNames('accessories')",
    armorNames: "getInventoryNames('armors')",
    armors: "getInventoryNames('armors', true)",
    dropItems: "getInventoryNames('*', true)",
    enemyNames: "getEnemyNames()",
    helmetNames: "getInventoryNames('helmets')",
    helmets: "getInventoryNames('helmets', true)",
    icons: {
      0x20: "Katana",
      0x21: "Bow",
      0x22: "Gun",
      0x23: "Arm",
      0x24: "Swords",
      0x25: "Fist",
      0x26: "Scythe",
      0x27: "Helmets",
      0x28: "Armor",
      0x29: "Accessories",
      0xef: "-",
      0xff: "[space]",
    },
    itemNames: "getInventoryNames('items')",
    letters: [
      // USA
      {
        0xa0: "A",
        0xa1: "B",
        0xa2: "C",
        0xa3: "D",
        0xa4: "E",
        0xa5: "F",
        0xa6: "G",
        0xa7: "H",
        0xa8: "I",
        0xa9: "J",
        0xaa: "K",
        0xab: "L",
        0xac: "M",
        0xad: "N",
        0xae: "O",
        0xaf: "P",
        0xb0: "Q",
        0xb1: "R",
        0xb2: "S",
        0xb3: "T",
        0xb4: "U",
        0xb5: "V",
        0xb6: "W",
        0xb7: "X",
        0xb8: "Y",
        0xb9: "Z",
        0xba: "a",
        0xbb: "b",
        0xbc: "c",
        0xbd: "d",
        0xbe: "e",
        0xbf: "f",
        0xc0: "g",
        0xc1: "h",
        0xc2: "i",
        0xc3: "j",
        0xc4: "k",
        0xc5: "l",
        0xc6: "m",
        0xc7: "n",
        0xc8: "o",
        0xc9: "p",
        0xca: "q",
        0xcb: "r",
        0xcc: "s",
        0xcd: "t",
        0xce: "u",
        0xcf: "v",
        0xd0: "w",
        0xd1: "x",
        0xd2: "y",
        0xd3: "z",
        0xd4: "0",
        0xd5: "1",
        0xd6: "2",
        0xd7: "3",
        0xd8: "4",
        0xd9: "5",
        0xda: "6",
        0xdb: "7",
        0xdc: "8",
        0xdd: "9",
        0xde: "!",
        0xdf: "?",
        0xe0: "/",
        0xe1: "“",
        0xe2: "”",
        0xe3: ":",
        0xe4: "&",
        0xe5: "(",
        0xe6: ")",
        0xe7: "'",
        0xe8: ".",
        0xe9: ",",
        0xea: "=",
        0xeb: "-",
        0xec: "+",
        0xed: "%",
        0xef: " ",
        0xf3: "#",
      },
      // Japan
      {
        0x40: "バ",
        0x41: "ば",
        0x42: "ビ",
        0x43: "び",
        0x44: "ブ",
        0x45: "ぶ",
        0x46: "ベ",
        0x47: "べ",
        0x48: "ボ",
        0x49: "ぼ",
        0x4a: "ガ",
        0x4b: "が",
        0x4c: "ギ",
        0x4d: "ぎ",
        0x4e: "グ",
        0x4f: "ぐ",
        0x50: "ゲ",
        0x51: "げ",
        0x52: "ゴ",
        0x53: "ご",
        0x54: "ザ",
        0x55: "ざ",
        0x56: "ジ",
        0x57: "じ",
        0x58: "ズ",
        0x59: "ず",
        0x5a: "ゼ",
        0x5b: "ぜ",
        0x5c: "ゾ",
        0x5d: "ぞ",
        0x5e: "ダ",
        0x5f: "だ",
        0x60: "ヂ",
        0x61: "ぢ",
        0x62: "ヅ",
        0x63: "づ",
        0x64: "デ",
        0x65: "で",
        0x66: "ド",
        0x67: "ど",
        0x68: "ヴ",
        0x69: "パ",
        0x6a: "ぱ",
        0x6b: "ピ",
        0x6c: "ぴ",
        0x6d: "プ",
        0x6e: "ぷ",
        0x6f: "ペ",
        0x70: "ぺ",
        0x71: "ポ",
        0x72: "ぽ",
        0x73: "0",
        0x74: "1",
        0x75: "2",
        0x76: "3",
        0x77: "4",
        0x78: "5",
        0x79: "6",
        0x7a: "7",
        0x7b: "8",
        0x7c: "9",
        0x80: "ハ",
        0x81: "は",
        0x82: "ヒ",
        0x83: "ひ",
        0x84: "フ",
        0x85: "ふ",
        0x86: "ヘ",
        0x87: "へ",
        0x88: "ホ",
        0x89: "ほ",
        0x8a: "カ",
        0x8b: "か",
        0x8c: "キ",
        0x8d: "き",
        0x8e: "ク",
        0x8f: "く",
        0x90: "ケ",
        0x91: "け",
        0x92: "コ",
        0x93: "こ",
        0x94: "サ",
        0x95: "さ",
        0x96: "シ",
        0x97: "し",
        0x98: "ス",
        0x99: "す",
        0x9a: "セ",
        0x9b: "せ",
        0x9c: "ソ",
        0x9d: "そ",
        0x9e: "タ",
        0x9f: "た",
        0xa0: "チ",
        0xa1: "ち",
        0xa2: "ツ",
        0xa3: "つ",
        0xa4: "テ",
        0xa5: "て",
        0xa6: "ト",
        0xa7: "と",
        0xa8: "ウ",
        0xa9: "う",
        0xaa: "ア",
        0xab: "あ",
        0xac: "イ",
        0xad: "い",
        0xae: "エ",
        0xaf: "え",
        0xb0: "オ",
        0xb1: "お",
        0xb2: "ナ",
        0xb3: "な",
        0xb4: "ニ",
        0xb5: "に",
        0xb6: "ヌ",
        0xb7: "ぬ",
        0xb8: "ネ",
        0xb9: "ね",
        0xba: "ノ",
        0xbb: "の",
        0xbc: "マ",
        0xbd: "ま",
        0xbe: "ミ",
        0xbf: "み",
        0xc0: "ヤ",
        0xc1: "や",
        0xc2: "ユ",
        0xc3: "ゆ",
        0xc4: "ヨ",
        0xc5: "よ",
        0xc6: "ワ",
        0xc7: "わ",
        0xc8: "ン",
        0xc9: "ん",
        0xca: "ヲ",
        0xcb: "を",
        0xcc: "ッ",
        0xcd: "っ",
        0xce: "ャ",
        0xcf: "ゃ",
        0xd0: "ム",
        0xd1: "む",
        0xd2: "メ",
        0xd3: "め",
        0xd4: "モ",
        0xd5: "も",
        0xd6: "ラ",
        0xd7: "ら",
        0xd8: "リ",
        0xd9: "り",
        0xda: "ル",
        0xdb: "る",
        0xdc: "レ",
        0xdd: "れ",
        0xde: "ロ",
        0xdf: "ろ",
        0xe0: "ュ",
        0xe1: "ゅ",
        0xe2: "ョ",
        0xe3: "ょ",
        0xe4: "ァ",
        0xe5: "-",
        0xe6: "ィ",
        0xe8: "ゥ",
        0xe9: "!",
        0xea: "ェ",
        0xeb: "?",
        0xec: "ォ",
        0xed: "/",
        0xfd: "魔",
        0xfe: "王",
        0xff: " ",
      },
    ],
    portraits: {
      0x0: "Crono",
      0x1: "Marle",
      0x2: "Lucca",
      0x3: "Robo",
      0x4: "Frog",
      0x5: "Ayla",
      0x6: "Magus",
    },
    weaponNames: "getInventoryNames('weapons')",
    weapons: "getInventoryNames('weapons', true)",
  },
  resourcesOrder: {
    icons: [0xef, 0xff],
  },
};

export default template;
