import type { Resource } from "$lib/types";

export const characters = [
  { index: 0x00, wmIndex: 0x15, name: "Raphael" },
  { index: 0x01, wmIndex: 0x16, name: "Talim" },
  { index: 0x02, wmIndex: 0x1a, name: "Yunsung" },
  { index: 0x03, wmIndex: 0x17, name: "Cassandra" },
  { index: 0x04, wmIndex: 0x01, name: "Mitsurugi" },
  { index: 0x05, wmIndex: 0x03, name: "Taki" },
  { index: 0x06, wmIndex: 0x05, name: "Voldo" },
  { index: 0x07, wmIndex: 0x11, name: "Nightmare" },
  { index: 0x08, wmIndex: 0x12, name: "Astraroth" },
  { index: 0x09, wmIndex: 0x0b, name: "Ivy" },
  { index: 0x0a, wmIndex: 0x0c, name: "Kilik" },
  { index: 0x0b, wmIndex: 0x0d, name: "Xianghua" },
  { index: 0x0c, wmIndex: 0x04, name: "Maxi" },
  { index: 0x0d, wmIndex: 0x19, name: "Necrid" },
  { index: 0x0e, wmIndex: 0x1b, name: "%character%" },
  { index: 0x0f, wmIndex: 0x06, name: "Sophitia" },
  { index: 0x10, wmIndex: 0x02, name: "Seung Mina" },
  { index: 0x11, wmIndex: 0x0f, name: "Yoshimitsu" },
  { index: 0x12, wmIndex: 0x18, name: "Charade" },
  { index: 0x13, wmIndex: 0x14, name: "Cervantes" },
  { index: 0x14, wmIndex: 0x13, name: "Inferno" },
  { index: 0x15, wmIndex: 0x1e, name: "Lizardman" },
  { index: 0x16, wmIndex: 0x1f, name: "Assassin" },
  { index: 0x17, wmIndex: 0x20, name: "Berserker" },
];

// prettier-ignore
export const classList = [
  { experience:        0, name: "Newcomer" },
  { experience:     1500, name: "Iron Neophyte" },
  { experience:     2500, name: "Bronze Neophyte" },
  { experience:     3500, name: "Silver Neophyte" },
  { experience:     4500, name: "Gold Neophyte" },
  { experience:     6000, name: "Platinum Neophyte" },
  { experience:     8000, name: "Iron Apprentice" },
  { experience:    10000, name: "Bronze Apprentice" },
  { experience:    12000, name: "Silver Apprentice" },
  { experience:    14000, name: "Gold Apprentice" },
  { experience:    16000, name: "Platinum Apprentice" },
  { experience:    19000, name: "Iron Disciple" },
  { experience:    21000, name: "Bronze Disciple" },
  { experience:    23000, name: "Silver Disciple" },
  { experience:    25000, name: "Gold Disciple" },
  { experience:    27000, name: "Platinum Disciple" },
  { experience:    29000, name: "Iron Fighter" },
  { experience:    32000, name: "Bronze Fighter" },
  { experience:    34000, name: "Silver Fighter" },
  { experience:    36000, name: "Gold Fighter" },
  { experience:    38000, name: "Platinum Fighter" },
  { experience:    41000, name: "Iron Battler" },
  { experience:    44000, name: "Bronze Battler" },
  { experience:    47000, name: "Silver Battler" },
  { experience:    50000, name: "Gold Battler" },
  { experience:    53000, name: "Platinum Battler" },
  { experience:    56000, name: "Iron Combatant" },
  { experience:    59000, name: "Bronze Combatant" },
  { experience:    62000, name: "Silver Combatant" },
  { experience:    65000, name: "Gold Combatant" },
  { experience:    68000, name: "Platinum Combatant" },
  { experience:    71000, name: "Iron Duelist" },
  { experience:    74000, name: "Bronze Duelist" },
  { experience:    77000, name: "Silver Duelist" },
  { experience:    80000, name: "Gold Duelist" },
  { experience:    84000, name: "Platinum Duelist" },
  { experience:    88000, name: "Iron Mercenary" },
  { experience:    92000, name: "Bronze Mercenary" },
  { experience:    96000, name: "Silver Mercenary" },
  { experience:   100000, name: "Gold Mercenary" },
  { experience:   104000, name: "Platinum Mercenary" },
  { experience:   108000, name: "Iron Warrior" },
  { experience:   112000, name: "Bronze Warrior" },
  { experience:   116000, name: "Silver Warrior" },
  { experience:   120000, name: "Gold Warrior" },
  { experience:   125000, name: "Platinum Warrior" },
  { experience:   130000, name: "Iron Knight" },
  { experience:   135000, name: "Bronze Knight" },
  { experience:   140000, name: "Silver Knight" },
  { experience:   145000, name: "Gold Knight" },
  { experience:   150000, name: "Platinum Knight" },
  { experience:   155000, name: "Iron Champion" },
  { experience:   160000, name: "Bronze Champion" },
  { experience:   165000, name: "Silver Champion" },
  { experience:   170000, name: "Gold Champion" },
  { experience:   177000, name: "Platinum Champion" },
  { experience:   184000, name: "Iron Conqueror" },
  { experience:   191000, name: "Bronze Conqueror" },
  { experience:   198000, name: "Silver Conqueror" },
  { experience:   205000, name: "Gold Conqueror" },
  { experience:   212000, name: "Platinum Conqueror" },
  { experience:   219000, name: "Iron Hero" },
  { experience:   226000, name: "Bronze Hero" },
  { experience:   233000, name: "Silver Hero" },
  { experience:   240000, name: "Gold Hero" },
  { experience:   250000, name: "Platinum Hero" },
  { experience:   260000, name: "Iron Master" },
  { experience:   270000, name: "Bronze Master" },
  { experience:   280000, name: "Silver Master" },
  { experience:   290000, name: "Gold Master" },
  { experience:   300000, name: "Platinum Master" },
  { experience:   320000, name: "Iron Edgemaster" },
  { experience:   340000, name: "Bronze Edgemaster" },
  { experience:   360000, name: "Silver Edgemaster" },
  { experience:   380000, name: "Gold Edgemaster" },
  { experience:   400000, name: "Platinum Edgemaster" },
  { experience:   500000, name: "Grand Edgemaster of the Basilisk" },
  { experience:   600000, name: "Grand Edgemaster of the Gorgon" },
  { experience:   700000, name: "Grand Edgemaster of the Gargoyle" },
  { experience:   800000, name: "Grand Edgemaster of the Ogre" },
  { experience:   900000, name: "Grand Edgemaster of the Minotaur" },
  { experience:  1000000, name: "Grand Edgemaster of the Cerberus" },
  { experience:  1200000, name: "Grand Edgemaster of the Hydra" },
  { experience:  1400000, name: "Grand Edgemaster of the Furies" },
  { experience:  1600000, name: "Grand Edgemaster of the Kraken" },
  { experience:  1800000, name: "Grand Edgemaster of the Fenrir" },
  { experience:  2000000, name: "Grand Edgemaster of the Gryphon" },
  { experience:  2300000, name: "Grand Edgemaster of the Pegasus" },
  { experience:  2600000, name: "Grand Edgemaster of the Wyvern" },
  { experience:  2900000, name: "Grand Edgemaster of the Manticore" },
  { experience:  3200000, name: "Grand Edgemaster of the Chimera" },
  { experience:  3500000, name: "Grand Edgemaster of the Cyclops" },
  { experience:  4000000, name: "Glorious Edgemaster of the Siren" },
  { experience:  4500000, name: "Glorious Edgemaster of the Efreet" },
  { experience:  5000000, name: "Glorious Edgemaster of the Balron" },
  { experience:  5500000, name: "Legendary Edgemaster of the Unicorn" },
  { experience:  6000000, name: "Legendary Edgemaster of the Dragon" },
  { experience:  7000000, name: "Legendary Edgemaster of the Phoenix" },
  { experience: 99999900, name: "Ultimate Edgemaster" },
];

export const classes = classList.reduce((items: Resource, item, index) => {
  items[index] = item.name;

  return items;
}, {});

export const chapters = [
  { index: 0x0, name: "Chapter 1: Regulus" },
  { index: 0x1, name: "Chapter 2: Thuban" },
  { index: 0x2, name: "Chapter 3: Benetnasch" },
  { index: 0x3, name: "Chapter 4: Mizar" },
  { index: 0x4, name: "Chapter 5: Altair" },
  { index: 0x5, name: "Chapter 6: Aldebaran" },
  { index: 0x6, name: "Chapter 7: Rigel" },
  { index: 0x7, name: "Chapter 8: Merak" },
  { index: 0x8, name: "Chapter 9: Algol" },
  { index: 0x9, name: "Chapter 10: Antares" },
  { index: 0xa, name: "Subchapter 1: Schedar" },
  { index: 0xb, name: "Subchapter 2: Alioth" },
  { index: 0xc, name: "Subchapter 3: Pollux" },
  { index: 0xd, name: "Subchapter 4: Procyon" },
  { index: 0xe, name: "Extra Chapter 1: Castor" },
  { index: 0xf, name: "Extra Chapter 2: Cepheus" },
];

// prettier-ignore
export const missions = [
  { index: 0x00, chapter: 0x0, name: "Proving Grounds"        , adjMissions: [0x01,     ,     ,     ], linkedMissions: [0x01] },
  { index: 0x01, chapter: 0x0, name: "Bulwark Ruins"          , adjMissions: [0x02, 0x00,     ,     ], linkedMissions: [0x02] },
  { index: 0x02, chapter: 0x0, name: "Warrior's Trial Grounds", adjMissions: [0x03, 0x01,     ,     ], linkedMissions: [0x03] },
  { index: 0x03, chapter: 0x1, name: "Thuban Ferry"           , adjMissions: [0x04, 0x02,     ,     ], linkedMissions: [0x04] },
  { index: 0x04, chapter: 0x1, name: "Village of Arche"       , adjMissions: [0x05, 0x03,     ,     ], linkedMissions: [0x05] },
  { index: 0x05, chapter: 0x1, name: "Minkar Mine"            , adjMissions: [0x06, 0x04,     ,     ], linkedMissions: [0x06] },
  { index: 0x06, chapter: 0x2, name: "Carnival"               , adjMissions: [0x07, 0x05, 0x08,     ], linkedMissions: [0x07, 0x08] },
  { index: 0x07, chapter: 0x2, name: "Talitha Gambling Den"   , adjMissions: [0x09, 0x06,     , 0x0f], linkedMissions: [0x09] },
  { index: 0x08, chapter: 0x2, name: "Diphda Temple"          , adjMissions: [0x09,     , 0x27, 0x06], linkedMissions: [0x09, 0x27] },
  { index: 0x09, chapter: 0x2, name: "Benetnasch Harbor"      , adjMissions: [0x0a, 0x07, 0x08,     ], linkedMissions: [0x0a] },
  { index: 0x0a, chapter: 0x3, name: "Al Gieba Ruins"         , adjMissions: [0x0b, 0x09,     ,     ], linkedMissions: [0x0b] },
  { index: 0x0b, chapter: 0x3, name: "Windmill"               , adjMissions: [0x0d, 0x0a,     , 0x0c], linkedMissions: [0x0c, 0x0d] },
  { index: 0x0c, chapter: 0x3, name: "Merope Monastery"       , adjMissions: [    ,     , 0x0b, 0x28], linkedMissions: [0x28] },
  { index: 0x0d, chapter: 0x3, name: "Deserted Village"       , adjMissions: [0x0e, 0x0b,     ,     ], linkedMissions: [0x0e] },
  { index: 0x0e, chapter: 0x3, name: "Charon's Pass"          , adjMissions: [0x11, 0x0d,     ,     ], linkedMissions: [0x0f] },
  { index: 0x0f, chapter: 0x4, name: "Nereid Gorge"           , adjMissions: [    , 0x10, 0x07,     ], linkedMissions: [0x10] },
  { index: 0x10, chapter: 0x4, name: "Paradise of Altair"     , adjMissions: [0x0f,     ,     ,     ], linkedMissions: [0x11] },
  { index: 0x11, chapter: 0x5, name: "Castle of the Dead"     , adjMissions: [0x12, 0x0e,     ,     ], linkedMissions: [0x12] },
  { index: 0x12, chapter: 0x5, name: "City of Nashira"        , adjMissions: [0x13, 0x11,     ,     ], linkedMissions: [0x13] },
  { index: 0x13, chapter: 0x5, name: "Seginus Temple"         , adjMissions: [0x15, 0x12,     , 0x14], linkedMissions: [0x14, 0x15] },
  { index: 0x14, chapter: 0x5, name: "Crytomeria Ridge"       , adjMissions: [    ,     , 0x13, 0x20], linkedMissions: [] },
  { index: 0x15, chapter: 0x5, name: "Siam Ruins"             , adjMissions: [0x1a, 0x13, 0x16,     ], linkedMissions: [0x16, 0x1a] },
  { index: 0x16, chapter: 0x5, name: "Underground Juno"       , adjMissions: [    ,     , 0x17, 0x15], linkedMissions: [0x17] },
  { index: 0x17, chapter: 0x6, name: "Underground Prison"     , adjMissions: [    , 0x18,     , 0x16], linkedMissions: [0x18] },
  { index: 0x18, chapter: 0x6, name: "Rigel, Spiritual City"  , adjMissions: [0x17, 0x19,     ,     ], linkedMissions: [0x19] },
  { index: 0x19, chapter: 0x6, name: "Forbidden Grounds"      , adjMissions: [0x18,     ,     ,     ], linkedMissions: [0x1a] },
  { index: 0x1a, chapter: 0x7, name: "Sirius, City in the Sky", adjMissions: [0x1c, 0x15,     , 0x1b], linkedMissions: [0x1b, 0x1c] },
  { index: 0x1b, chapter: 0x7, name: "Crystal Mine"           , adjMissions: [0x1c,     , 0x1a, 0x2c], linkedMissions: [0x2c] },
  { index: 0x1c, chapter: 0x7, name: "Dubhe Arena"            , adjMissions: [0x1d, 0x1a,     , 0x1b], linkedMissions: [0x1d] },
  { index: 0x1d, chapter: 0x7, name: "Io's Vase"              , adjMissions: [0x1f, 0x1c, 0x1e,     ], linkedMissions: [0x1f] },
  { index: 0x1e, chapter: 0x7, name: "Phantom Cave"           , adjMissions: [    ,     , 0x30, 0x1d], linkedMissions: [0x1d] },
  { index: 0x1f, chapter: 0x7, name: "Grand Shrine of Merak"  , adjMissions: [0x24, 0x1d,     ,     ], linkedMissions: [0x20] },
  { index: 0x20, chapter: 0x8, name: "Corridor of the Sky"    , adjMissions: [    ,     , 0x14, 0x21], linkedMissions: [0x21] },
  { index: 0x21, chapter: 0x8, name: "Ancient Amphitheater"   , adjMissions: [0x22,     , 0x20, 0x23], linkedMissions: [0x22, 0x123] },
  { index: 0x22, chapter: 0x8, name: "Reclusive Palace"       , adjMissions: [    , 0x21,     ,     ], linkedMissions: [0x24] },
  { index: 0x23, chapter: 0x8, name: "Northern Algol"         , adjMissions: [    ,     , 0x21, 0x34], linkedMissions: [0x134] },
  { index: 0x24, chapter: 0x9, name: "Midnight Coliseum"      , adjMissions: [0x25, 0x1f,     ,     ], linkedMissions: [0x25] },
  { index: 0x25, chapter: 0x9, name: "Court of the Dead"      , adjMissions: [0x26, 0x24,     ,     ], linkedMissions: [0x26] },
  { index: 0x26, chapter: 0x9, name: "Tartaros"               , adjMissions: [    , 0x25,     ,     ], linkedMissions: [] },
  { index: 0x27, chapter: 0xa, name: "Stone Temple"           , adjMissions: [    ,     ,     , 0x08], linkedMissions: [] },
  { index: 0x28, chapter: 0xb, name: "Celbarai Fortress"      , adjMissions: [0x2a,     , 0x0c, 0x29], linkedMissions: [0x29, 0x2a] },
  { index: 0x29, chapter: 0xb, name: "Ceres Stronghold"       , adjMissions: [0x2b,     , 0x28,     ], linkedMissions: [0x2b] },
  { index: 0x2a, chapter: 0xb, name: "Ancient Library"        , adjMissions: [    , 0x28,     , 0x2b], linkedMissions: [0x2b] },
  { index: 0x2b, chapter: 0xb, name: "Temple in the Clouds"   , adjMissions: [    , 0x29, 0x2a,     ], linkedMissions: [] },
  { index: 0x2c, chapter: 0xc, name: "Eternal Palace"         , adjMissions: [    ,     , 0x1b, 0x2d], linkedMissions: [0x2d] },
  { index: 0x2d, chapter: 0xc, name: "Castle of the Damned"   , adjMissions: [0x2e,     , 0x2c,     ], linkedMissions: [0x12e] },
  { index: 0x2e, chapter: 0xc, name: "Hero's Trail"           , adjMissions: [    , 0x2d,     ,     ], linkedMissions: [0x12f] },
  { index: 0x2f, chapter: 0xd, name: "Muliphein's Crypt"      , adjMissions: [0x31,     , 0x33, 0x30], linkedMissions: [0x30, 0x31, 0x33] },
  { index: 0x30, chapter: 0xd, name: "Tower of Happiness"     , adjMissions: [    , 0x2f, 0x31, 0x1e], linkedMissions: [0x11e] },
  { index: 0x31, chapter: 0xd, name: "Mount Procyon"          , adjMissions: [0x32, 0x2f,     , 0x30], linkedMissions: [0x32] },
  { index: 0x32, chapter: 0xd, name: "Lynx Arbor"             , adjMissions: [    , 0x31, 0x37,     ], linkedMissions: [0x37] },
  { index: 0x33, chapter: 0xd, name: "Ruchba's Mandible"      , adjMissions: [    ,     ,     , 0x2f], linkedMissions: [] },
  { index: 0x34, chapter: 0xe, name: "Castor's Eye"           , adjMissions: [    ,     , 0x23, 0x35], linkedMissions: [0x35] },
  { index: 0x35, chapter: 0xe, name: "Gateway to Hell"        , adjMissions: [    ,     , 0x34, 0x36], linkedMissions: [0x36] },
  { index: 0x36, chapter: 0xe, name: "Swordsmen's Grave"      , adjMissions: [0x35,     ,     ,     ], linkedMissions: [] },
  { index: 0x37, chapter: 0xf, name: "Cor Caroli"             , adjMissions: [    , 0x38,     , 0x32], linkedMissions: [0x38] },
  { index: 0x38, chapter: 0xf, name: "Er Rai"                 , adjMissions: [0x37, 0x39,     ,     ], linkedMissions: [0x39] },
  { index: 0x39, chapter: 0xf, name: "Hero's Tomb"            , adjMissions: [0x38,     ,     ,     ], linkedMissions: [] },
];
