import type { GameJson } from "$lib/types";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa_japan: {
        0x0: [0x4c, 0x4e, 0x54, 0x47], // "LNTG"
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      name: "Checksum",
      offset: 0x368,
      type: "checksum",
      dataType: "uint32",
      control: {
        offsetStart: 0x0,
        offsetEnd: 0x368,
      },
    },
    {
      type: "tabs",
      items: [
        {
          name: "General",
          flex: true,
          items: [
            {
              name: "Save Count",
              offset: 0x4,
              type: "variable",
              dataType: "uint32",
              hidden: true,
            },
            {
              name: "Unlocked Characters",
              type: "bitflags",
              flags: [
                { offset: 0x19, bit: 0, label: "Sonic" },
                { offset: 0x19, bit: 2, label: "Tails" },
                { offset: 0x19, bit: 3, label: "Knuckles" },
                { offset: 0x19, bit: 1, label: "Cream" },
                { offset: 0x19, bit: 4, label: "Amy" },
              ],
            },
            {
              name: "Unlocked Menus",
              type: "bitflags",
              flags: [
                { offset: 0x3d, bit: 0, label: "Sound Test" },
                { offset: 0x3d, bit: 1, label: "Time Attack Boss" },
                { offset: 0x3d, bit: 2, label: "Secret Hint" },
              ],
            },
          ],
        },
        {
          name: "Story",
          items: [
            {
              length: 0x1,
              type: "container",
              instanceType: "tabs",
              instances: 7,
              resource: "zones",
              vertical: true,
              prependSubinstance: [
                {
                  name: "General",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      noMargin: true,
                      items: [
                        {
                          name: "Progression",
                          offset: 0x1a,
                          type: "variable",
                          dataType: "uint8",
                          resource: "progressions",
                        },
                        {
                          name: "Location",
                          offset: 0x1b,
                          type: "variable",
                          dataType: "uint8",
                          resource: "zones",
                        },
                        {
                          name: "Introduction Seen",
                          offset: 0x62,
                          type: "variable",
                          dataType: "bit",
                          bit: 0,
                          hidden: true,
                        },
                      ],
                    },
                    {
                      name: "Chaos Emeralds",
                      type: "bitflags",
                      flags: [
                        { offset: 0x3c, bit: 0, label: "Red" },
                        { offset: 0x3c, bit: 1, label: "Blue" },
                        { offset: 0x3c, bit: 2, label: "Yellow" },
                        { offset: 0x3c, bit: 3, label: "Green" },
                        { offset: 0x3c, bit: 4, label: "White" },
                        { offset: 0x3c, bit: 5, label: "Cyan" },
                        { offset: 0x3c, bit: 6, label: "Purple" },
                      ],
                    },
                  ],
                },
              ],
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "acts-%index%",
                      name: "Act 1",
                      type: "bitflags",
                      flags: [
                        { offset: 0x33, bit: 0, label: "Clear", separator: true },
                        { offset: 0x3e, bit: 0, label: "Bronze Medal" },
                        { offset: 0x3e, bit: 1, label: "Silver Medal" },
                        { offset: 0x3e, bit: 2, label: "Gold Medal" },
                      ],
                    },
                    {
                      id: "acts-%index%",
                      name: "Act 2",
                      type: "bitflags",
                      flags: [
                        { offset: 0x33, bit: 1, label: "Clear", separator: true },
                        { offset: 0x3f, bit: 0, label: "Bronze Medal" },
                        { offset: 0x3f, bit: 1, label: "Silver Medal" },
                        { offset: 0x3f, bit: 2, label: "Gold Medal" },
                      ],
                    },
                    {
                      id: "acts-%index%",
                      name: "Act 3",
                      type: "bitflags",
                      flags: [
                        { offset: 0x33, bit: 2, label: "Clear", separator: true },
                        { offset: 0x40, bit: 0, label: "Bronze Medal" },
                        { offset: 0x40, bit: 1, label: "Silver Medal" },
                        { offset: 0x40, bit: 2, label: "Gold Medal" },
                      ],
                    },
                    {
                      id: "acts-%index%",
                      name: "Boss",
                      type: "bitflags",
                      flags: [
                        { offset: 0x33, bit: 3, label: "Clear", separator: true },
                        { offset: 0x41, bit: 0, label: "Bronze Medal" },
                        { offset: 0x41, bit: 1, label: "Silver Medal" },
                        { offset: 0x41, bit: 2, label: "Gold Medal" },
                      ],
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Chao",
                      type: "bitflags",
                      overrideShift: {
                        parent: 1,
                        shift: 0x2,
                      },
                      flags: [
                        { offset: 0x1e, bit: 0, label: "Chao 1" },
                        { offset: 0x1e, bit: 1, label: "Chao 2" },
                        { offset: 0x1e, bit: 2, label: "Chao 3" },
                        { offset: 0x1e, bit: 3, label: "Chao 4" },
                        { offset: 0x1e, bit: 4, label: "Chao 5" },
                        { offset: 0x1e, bit: 5, label: "Chao 6" },
                        { offset: 0x1e, bit: 6, label: "Chao 7" },
                        { offset: 0x1e, bit: 7, label: "Chao 8" },
                        { offset: 0x1f, bit: 0, label: "Chao 9" },
                        { offset: 0x1f, bit: 1, label: "Chao 10" },
                      ],
                    },
                    {
                      name: "Special Keys",
                      offset: 0x2c,
                      type: "variable",
                      dataType: "uint8",
                      max: 9,
                    },
                  ],
                },
              ],
              appendSubinstance: [
                {
                  name: "Final Zone",
                  items: [
                    {
                      id: "hiddenEvents",
                      name: "Boss",
                      type: "bitflags",
                      flags: [
                        { offset: 0x3a, bit: 3, label: "Clear", separator: true },
                        { offset: 0x62, bit: 4, label: "Clear", hidden: true },
                        { offset: 0x5d, bit: 0, label: "Bronze Medal" },
                        { offset: 0x5d, bit: 1, label: "Silver Medal" },
                        { offset: 0x5d, bit: 2, label: "Gold Medal" },
                      ],
                    },
                  ],
                },
                {
                  name: "Extra Zone",
                  items: [
                    {
                      id: "hiddenEvents",
                      name: "Boss",
                      type: "bitflags",
                      flags: [
                        { offset: 0x3b, bit: 3, label: "Clear", separator: true },
                        { offset: 0x62, bit: 5, label: "Clear", hidden: true },
                        { offset: 0x61, bit: 0, label: "Bronze Medal" },
                        { offset: 0x61, bit: 1, label: "Silver Medal" },
                        { offset: 0x61, bit: 2, label: "Gold Medal" },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "VS",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Name",
                  offset: 0xc,
                  length: 0xc,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint16",
                  fallback: 0x4d,
                  resource: "letters",
                  test: true,
                },
                {
                  name: "ID",
                  offset: 0x8,
                  type: "variable",
                  dataType: "uint32",
                  hidden: true,
                },
                {
                  name: "Total Wins",
                  offset: 0x64,
                  type: "variable",
                  dataType: "uint8",
                  max: 99,
                },
                {
                  name: "Total Losses",
                  offset: 0x66,
                  type: "variable",
                  dataType: "uint8",
                  max: 99,
                },
                {
                  name: "Total Draws",
                  offset: 0x65,
                  type: "variable",
                  dataType: "uint8",
                  max: 99,
                },
              ],
            },
            {
              length: 0x14,
              type: "container",
              instanceType: "section",
              instances: 10,
              flex: true,
              noMargin: true,
              items: [
                {
                  id: "timeAttackName",
                  name: "Name",
                  offset: 0x70,
                  length: 0xc,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint16",
                  fallback: 0x4d,
                  resource: "letters",
                },
                {
                  name: "ID",
                  offset: 0x6c,
                  type: "variable",
                  dataType: "uint32",
                  hidden: true,
                },
                {
                  name: "Enabled",
                  offset: 0x68,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  id: "vsResult-0",
                  name: "Wins",
                  offset: 0x69,
                  type: "variable",
                  dataType: "uint8",
                  max: 99,
                },
                {
                  id: "vsResult-2",
                  name: "Losses",
                  offset: 0x6b,
                  type: "variable",
                  dataType: "uint8",
                  max: 99,
                },
                {
                  id: "vsResult-1",
                  name: "Draws",
                  offset: 0x6a,
                  type: "variable",
                  dataType: "uint8",
                  max: 99,
                },
              ],
            },
          ],
        },
        {
          name: "Time Attack",
          items: [
            {
              length: 0x50,
              type: "container",
              instanceType: "tabs",
              instances: 7,
              resource: "zones",
              vertical: true,
              items: [
                {
                  length: 0x14,
                  type: "container",
                  instanceType: "tabs",
                  instances: 4,
                  resource: "acts",
                  vertical: true,
                  items: [
                    {
                      length: 0x4,
                      type: "container",
                      instanceType: "section",
                      instances: 5,
                      flex: true,
                      items: [
                        {
                          name: "%o Place",
                          offset: 0x130,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                        },
                        {
                          name: "Partner",
                          offset: 0x131,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                        },
                        {
                          name: "Time",
                          type: "group",
                          mode: "chrono",
                          items: [
                            {
                              id: "time",
                              offset: 0x132,
                              type: "variable",
                              dataType: "uint16",
                              operations: [
                                { "*": 16.666666667 },
                                {
                                  convert: {
                                    from: "milliseconds",
                                    to: "minutes",
                                  },
                                },
                                { round: 0 },
                              ],
                              max: 9,
                            },
                            {
                              id: "time",
                              offset: 0x132,
                              type: "variable",
                              dataType: "uint16",
                              operations: [
                                { "*": 16.666666667 },
                                {
                                  convert: {
                                    from: "milliseconds",
                                    to: "seconds",
                                  },
                                },
                                { round: 0 },
                              ],
                              leadingZeros: 1,
                              max: 59,
                            },
                            {
                              id: "time",
                              offset: 0x132,
                              type: "variable",
                              dataType: "uint16",
                              operations: [
                                { "*": 16.666666667 },
                                {
                                  convert: {
                                    from: "milliseconds",
                                    to: "milliseconds",
                                  },
                                },
                                { round: 0 },
                              ],
                              leadingZeros: 2,
                              max: 990,
                              step: 100,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Options",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Level",
                  offset: 0x364,
                  type: "variable",
                  dataType: "uint8",
                  resource: "levels",
                },
                {
                  name: "Time Up",
                  offset: 0x365,
                  type: "variable",
                  dataType: "uint8",
                  resource: "optionBooleanReversed",
                },
                {
                  name: "Language",
                  offset: 0x366,
                  type: "variable",
                  dataType: "uint8",
                  resource: "languages",
                },
              ],
            },
            {
              name: "Button Config",
              type: "section",
              flex: true,
              items: [
                {
                  name: "A",
                  offset: 0x360,
                  type: "variable",
                  dataType: "uint8",
                  resource: "buttons",
                },
                {
                  name: "B",
                  offset: 0x361,
                  type: "variable",
                  dataType: "uint8",
                  resource: "buttons",
                },
                {
                  name: "R",
                  offset: 0x362,
                  type: "variable",
                  dataType: "uint8",
                  resource: "buttons",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    acts: {
      0x0: "Act 1",
      0x1: "Act 2",
      0x2: "Act 3",
      0x3: "Boss",
    },
    buttons: {
      0x1: "Jump",
      0x2: "Attack",
      0x4: "Partner",
    },
    characters: {
      0x0: "Sonic",
      0x1: "Cream",
      0x2: "Tails",
      0x3: "Knuckles",
      0x4: "Amy",
      0xff: "-",
    },
    languages: {
      0x0: "Japanese",
      0x1: "English",
      0x2: "German",
      0x3: "French",
      0x4: "Spanish",
      0x5: "Italian",
    },
    letters: {
      0x0: "ア",
      0x1: "イ",
      0x2: "ウ",
      0x3: "エ",
      0x4: "オ",
      0x5: "マ",
      0x6: "ミ",
      0x7: "ム",
      0x8: "メ",
      0x9: "モ",
      0xa: "ﾞ",
      0xb: "カ",
      0xc: "キ",
      0xd: "ク",
      0xe: "ケ",
      0xf: "コ",
      0x10: "ヤ",
      0x12: "ユ",
      0x14: "ヨ",
      0x15: "゜",
      0x16: "サ",
      0x17: "シ",
      0x18: "ス",
      0x19: "セ",
      0x1a: "ソ",
      0x1b: "ラ",
      0x1c: "リ",
      0x1d: "ル",
      0x1e: "レ",
      0x1f: "ロ",
      0x20: "。",
      0x21: "タ",
      0x22: "チ",
      0x23: "ツ",
      0x24: "テ",
      0x25: "ト",
      0x26: "ワ",
      0x28: "ヲ",
      0x2a: "ン",
      0x2b: "、",
      0x2c: "ナ",
      0x2d: "ニ",
      0x2e: "ヌ",
      0x2f: "ネ",
      0x30: "ノ",
      0x31: "ァ",
      0x32: "ィ",
      0x33: "ゥ",
      0x34: "ェ",
      0x35: "ォ",
      0x36: "ッ",
      0x37: "ハ",
      0x38: "ヒ",
      0x39: "フ",
      0x3a: "ヘ",
      0x3b: "ホ",
      0x3c: "ャ",
      0x3e: "ュ",
      0x40: "ョ",
      0x41: "ヮ",
      0x42: "𓄼",
      0x43: "・",
      0x44: "★",
      0x45: "♀",
      0x46: "♂",
      0x47: "♪",
      0x48: "…",
      0x49: "「",
      0x4a: "」",
      0x4d: " ",
      0x4e: "!",
      0x4f: '"',
      0x50: "#",
      0x51: "$",
      0x52: "%",
      0x53: "&",
      0x54: "'",
      0x55: "(",
      0x56: ")",
      0x57: "*",
      0x58: "+",
      0x59: ",",
      0x5a: "-",
      0x5b: ".",
      0x5c: "/",
      0x5d: ":",
      0x5e: ";",
      0x5f: "<",
      0x60: "=",
      0x61: ">",
      0x62: "?",
      0x63: "0",
      0x64: "1",
      0x65: "2",
      0x66: "3",
      0x67: "4",
      0x68: "5",
      0x69: "6",
      0x6a: "7",
      0x6b: "8",
      0x6c: "9",
      0x6e: "@",
      0x6f: "A",
      0x70: "B",
      0x71: "C",
      0x72: "D",
      0x73: "E",
      0x74: "F",
      0x75: "G",
      0x76: "H",
      0x77: "I",
      0x78: "J",
      0x79: "K",
      0x7a: "L",
      0x7b: "M",
      0x7c: "N",
      0x7d: "O",
      0x7e: "P",
      0x7f: "Q",
      0x80: "R",
      0x81: "S",
      0x82: "T",
      0x83: "U",
      0x84: "V",
      0x85: "W",
      0x86: "X",
      0x87: "Y",
      0x88: "Z",
      0x89: "[",
      0x8a: "¥",
      0x8b: "]",
      0x8c: "^",
      0x8d: "_",
      0x8f: "‘",
      0x90: "a",
      0x91: "b",
      0x92: "c",
      0x93: "d",
      0x94: "e",
      0x95: "f",
      0x96: "g",
      0x97: "h",
      0x98: "i",
      0x99: "j",
      0x9a: "k",
      0x9b: "l",
      0x9c: "m",
      0x9d: "n",
      0x9e: "o",
      0x9f: "p",
      0xa0: "q",
      0xa1: "r",
      0xa2: "s",
      0xa3: "t",
      0xa4: "u",
      0xa5: "v",
      0xa6: "w",
      0xa7: "x",
      0xa8: "y",
      0xa9: "z",
      0xaa: "{",
      0xab: "|",
      0xac: "}",
      0xad: "~",
      0xb0: "À",
      0xb1: "Á",
      0xb2: "Â",
      0xb3: "Ã",
      0xb4: "Ä",
      0xb5: "Å",
      0xb6: "Æ",
      0xb7: "Ç",
      0xb8: "È",
      0xb9: "É",
      0xba: "Ê",
      0xbb: "Ë",
      0xbc: "Ì",
      0xbd: "Í",
      0xbe: "Î",
      0xbf: "Ï",
      0xc0: "Đ",
      0xc1: "Ñ",
      0xc2: "Ò",
      0xc3: "Ó",
      0xc4: "Ô",
      0xc5: "Õ",
      0xc6: "Ö",
      0xc7: "¿",
      0xc8: "Ø",
      0xc9: "Ù",
      0xca: "Ú",
      0xcb: "Û",
      0xcc: "Ü",
      0xcd: "Ý",
      0xce: "Þ",
      0xcf: "β",
      0xd1: "à",
      0xd2: "á",
      0xd3: "â",
      0xd4: "ã",
      0xd5: "ä",
      0xd6: "å",
      0xd7: "æ",
      0xd8: "ç",
      0xd9: "è",
      0xda: "é",
      0xdb: "ê",
      0xdc: "ë",
      0xdd: "ì",
      0xde: "í",
      0xdf: "î",
      0xe0: "ï",
      0xe1: "đ",
      0xe2: "ñ",
      0xe3: "ò",
      0xe4: "ó",
      0xe5: "ô",
      0xe6: "õ",
      0xe7: "ö",
      0xe8: "¡",
      0xe9: "ø",
      0xea: "ù",
      0xeb: "ú",
      0xec: "û",
      0xed: "ü",
      0xee: "ý",
      0xef: "þ",
      0xf0: "ÿ",
      0xffff: "",
    },
    levels: {
      0x0: "Normal",
      0x1: "Easy",
    },
    optionBooleanReversed: {
      0x0: "On",
      0x1: "Off",
    },
    progressions: {
      0x1: "Zone 1: Route 99",
      0x2: "Zone 2: Sunset Hill",
      0x3: "Zone 3: Ocean Base",
      0x4: "Zone 4: Toy Kingdom",
      0x5: "Zone 5: Twinkle Snow",
      0x6: "Zone 6: Cyber Track",
      0x7: "Zone 7: Chaos Angel",
      0x8: "Final Zone",
      0x9: "Clear",
    },
    zones: {
      0x0: "Zone 1: Route 99",
      0x1: "Zone 2: Sunset Hill",
      0x2: "Zone 3: Ocean Base",
      0x3: "Zone 4: Toy Kingdom",
      0x4: "Zone 5: Twinkle Snow",
      0x5: "Zone 6: Cyber Track",
      0x6: "Zone 7: Chaos Angel",
    },
  },
  resourcesOrder: {
    characters: [0xff],
  },
};

export default template;
