import type { GameJson, Resource } from "$lib/types";

import { getDateOffset } from "./utils";
import {
  jobs,
  monsters,
  moveAbilities,
  reactionAbilities,
  supportAbilities,
  unitTypes,
} from "./utils/jobs";
import {
  accessories,
  accessoriesGroups,
  bodies,
  bodiesGroups,
  hands,
  handsGroups,
  heads,
  headsGroups,
  inventory,
  locationList,
  locations,
  persons,
  propositionList,
  propositions,
  treasures,
  unexploredLands,
} from "./utils/resource";

const template: GameJson = {
  validator: {
    regions: {
      usa: {
        0x0: [
          0x42, 0x41, 0x53, 0x43, 0x55, 0x53, 0x2d, 0x39, 0x34, 0x32, 0x32,
          0x31, 0x46, 0x46, 0x54,
        ], // "BASCUS-94221FFT"
      },
      japan: {
        0x0: [
          0x42, 0x49, 0x53, 0x4c, 0x50, 0x53, 0x2d, 0x30, 0x30, 0x37, 0x37,
          0x30, 0x46, 0x46, 0x54,
        ], // "BISLPS-00770FFT"
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      id: "slots",
      instanceId: "slots",
      length: 0x2000,
      type: "container",
      instanceType: "tabs",
      instances: 15,
      enumeration: "Slot %d",
      onTabChange: "onSlotChange(%d)",
      items: [
        {
          type: "section",
          flex: true,
          hidden: true,
          items: [
            {
              name: "Checksum",
              offset: 0x118,
              type: "checksum",
              dataType: "uint64",
              control: {
                offsetStart: 0x0,
                offsetEnd: 0x0,
              },
            },
          ],
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "name",
                              name: "Name",
                              offset: 0x101,
                              length: 0xe,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0xfa,
                              endCode: 0xfe,
                              resource: "letters",
                              test: true,
                            },
                            {
                              name: "Birthday",
                              type: "group",
                              items: [
                                {
                                  offset: 0x1a00,
                                  type: "variable",
                                  dataType: "uint32",
                                  resource: "months",
                                },
                                {
                                  offset: 0x1a04,
                                  type: "variable",
                                  dataType: "uint32",
                                  min: 1,
                                  max: 31,
                                },
                              ],
                            },
                            {
                              name: "Playtime",
                              type: "group",
                              mode: "time",
                              items: [
                                {
                                  offset: 0x120,
                                  type: "variable",
                                  dataType: "uint32",
                                  operations: [
                                    {
                                      convert: { from: "seconds", to: "hours" },
                                    },
                                  ],
                                  max: 999,
                                },
                                {
                                  offset: 0x120,
                                  type: "variable",
                                  dataType: "uint32",
                                  operations: [
                                    {
                                      convert: {
                                        from: "seconds",
                                        to: "minutes",
                                      },
                                    },
                                  ],
                                  leadingZeros: 1,
                                  max: 59,
                                },
                                {
                                  offset: 0x120,
                                  type: "variable",
                                  dataType: "uint32",
                                  operations: [
                                    {
                                      convert: {
                                        from: "seconds",
                                        to: "seconds",
                                      },
                                    },
                                  ],
                                  leadingZeros: 1,
                                  max: 59,
                                },
                              ],
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Current Date",
                              type: "group",
                              items: [
                                {
                                  id: "currentDate-0",
                                  offset: 0x193c,
                                  type: "variable",
                                  dataType: "uint32",
                                  resource: "months",
                                },
                                {
                                  id: "currentDate-3",
                                  offset: 0x1940,
                                  type: "variable",
                                  dataType: "uint32",
                                  min: 1,
                                  max: 31,
                                },
                              ],
                            },
                            {
                              id: "location",
                              name: "Location",
                              offset: 0x1948,
                              type: "variable",
                              dataType: "uint8",
                              resource: "locations",
                              autocomplete: true,
                            },
                            {
                              name: "War Funds",
                              offset: 0x1934,
                              type: "variable",
                              dataType: "uint32",
                              max: 99999999,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          hidden: true,
                          items: [
                            {
                              name: "Level (Save Preview)",
                              offset: 0x113,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Job (Save Preview)",
                              offset: 0x112,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Current Date (Save Preview)",
                              type: "group",
                              hidden: true,
                              items: [
                                {
                                  offset: 0x114,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "months",
                                },
                                {
                                  offset: 0x115,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                              ],
                            },
                            {
                              name: "Location (Save Preview)",
                              offset: 0x116,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "World Map",
                      items: [
                        {
                          name: "Deep Dungeon Progression",
                          offset: 0x1a18,
                          type: "variable",
                          dataType: "uint32",
                          hidden: true,
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Places",
                              type: "bitflags",
                              flags: locationList.map((location) => ({
                                offset:
                                  0x1ab4 + Math.floor(location.index / 0x8),
                                bit: location.index % 8,
                                label: location.name,
                              })),
                            },
                            {
                              name: "Cleared Places",
                              type: "bitflags",
                              hidden: true,
                              flags: locationList.map((location) => ({
                                offset:
                                  0x1ac0 +
                                  Math.floor((7 + location.index) / 0x8),
                                bit: (7 + location.index) % 8,
                                label: location.name,
                              })),
                            },
                            {
                              name: "Roads",
                              type: "bitflags",
                              flags: [
                                { offset: 0x1ab9, bit: 4, label: "Fort Zeakden - Igros Castle" },
                                { offset: 0x1ab9, bit: 5, label: "Igros Castle - Mandalia Plains" },
                                { offset: 0x1ab9, bit: 6, label: "Mandalia Plains - Thieves Fort" },
                                { offset: 0x1ab9, bit: 7, label: "Mandalia Plains - Magic City Gariland" },
                                { offset: 0x1aba, bit: 0, label: "Magic City Gariland - Lenalia Plateau" },
                                { offset: 0x1aba, bit: 1, label: "Lenalia Plateau - Fovoham Plains" },
                                { offset: 0x1aba, bit: 2, label: "Fovoham Plains - Fort Zeakden" },
                                { offset: 0x1aba, bit: 3, label: "Fovoham Plains - Riovanes Castle" },
                                { offset: 0x1aba, bit: 4, label: "Riovanes Castle - Bervenia Volcano" },
                                { offset: 0x1aba, bit: 5, label: "Bervenia Volcano - Zeklaus Desert" },
                                { offset: 0x1aba, bit: 6, label: "Zeklaus Desert - Dorter Trade City" },
                                { offset: 0x1aba, bit: 7, label: "Dorter Trade City - Sweegy Woods" },
                                { offset: 0x1abb, bit: 0, label: "Sweegy Woods - Magic City Gariland" },
                                { offset: 0x1abb, bit: 1, label: "Riovanes Castle - Yuguo Woods" },
                                { offset: 0x1abb, bit: 2, label: "Yuguo Woods - Yardow Fort City" },
                                { offset: 0x1abb, bit: 3, label: "Yardow Fort City - Grog Hill" },
                                { offset: 0x1abb, bit: 4, label: "Grog Hill - Lesalia Imperial Capital" },
                                { offset: 0x1abb, bit: 5, label: "Lesalia Imperial Capital - Goland Coal City" },
                                { offset: 0x1abb, bit: 6, label: "Goland Coal City - Zeklaus Desert" },
                                { offset: 0x1abb, bit: 7, label: "Orbonne Monastery - Dorter Trade City" },
                                { offset: 0x1abc, bit: 0, label: "Dorter Trade City - Araguay Woods" },
                                { offset: 0x1abc, bit: 1, label: "Araguay Woods - Zirekile Falls" },
                                { offset: 0x1abc, bit: 2, label: "Zirekile Falls - Bethla Garrison" },
                                { offset: 0x1abc, bit: 3, label: "Bethla Garrison - Bed Desert" },
                                { offset: 0x1abc, bit: 4, label: "Bed Desert - Bervenia Free City" },
                                { offset: 0x1abc, bit: 5, label: "Bervenia Free City - Doguola Pass" },
                                { offset: 0x1abc, bit: 6, label: "Doguola Pass - Grog Hill" },
                                { offset: 0x1abc, bit: 7, label: "Bervenia Free City - Finath River" },
                                { offset: 0x1abd, bit: 0, label: "Finath River - Zeltennia Castle" },
                                { offset: 0x1abd, bit: 1, label: "Zeltennia Castle - Nelveska Temple" },
                                { offset: 0x1abd, bit: 2, label: "Zeltennia Castle - Zarghidas Trade City" },
                                { offset: 0x1abd, bit: 3, label: "Zarghidas Trade City - Germinas Peak" },
                                { offset: 0x1abd, bit: 4, label: "Germinas Peak - Poeskas Lake" },
                                { offset: 0x1abd, bit: 5, label: "Poeskas Lake - Limberry Castle" },
                                { offset: 0x1abd, bit: 6, label: "Limberry Castle - Dolbodar Swamp" },
                                { offset: 0x1abd, bit: 7, label: "Dolbodar Swamp - Bethlas Garrison" },
                                { offset: 0x1abe, bit: 0, label: "Zirekile Falls - Zaland Fort City" },
                                { offset: 0x1abe, bit: 1, label: "Zaland Fort City - Bariaus Hill" },
                                { offset: 0x1abe, bit: 2, label: "Bariaus Hill - Lionel Castle" },
                                { offset: 0x1abe, bit: 3, label: "Lionel Castle - Bariaus Valley" },
                                { offset: 0x1abe, bit: 4, label: "Bariaus Valley - Warjilis Trade City" },
                                { offset: 0x1abe, bit: 5, label: "Warjilis Trade City - Deep Dungeon" },
                                { offset: 0x1abe, bit: 6, label: "Bariaus Valley - Golgorand Execution Site" },
                                { offset: 0x1abe, bit: 7, label: "Lionel Castle - Zigolis Swamp" },
                                { offset: 0x1abf, bit: 0, label: "Zigolis Swamp - Goug Machine City" },
                                { offset: 0x1abf, bit: 1, label: "Goug Machine City - Murond Holy Place" },
                                { offset: 0x1abf, bit: 2, label: "Murond Holy Place - Magic City Gariland" },
                                { offset: 0x1abf, bit: 3, label: "Warjilis Trade City - Goug Machine City" },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Formation",
              items: [
                {
                  id: "formation-%index%",
                  instanceId: "units",
                  length: 0xe0,
                  type: "container",
                  instanceType: "tabs",
                  instances: 20,
                  resource: "unitNames",
                  vertical: true,
                  onTabChange: "onUnitChange(%d,'%itemId%')",
                  items: [
                    {
                      type: "tabs",
                      items: [
                        {
                          name: "Status",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Registered Number",
                                  offset: 0x485,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  id: "slot-%parent%-unitName-%index%",
                                  name: "Name",
                                  offset: 0x542,
                                  length: 0xe,
                                  type: "variable",
                                  dataType: "string",
                                  letterDataType: "uint8",
                                  fallback: 0xfa,
                                  endCode: 0xfe,
                                  resource: "letters",
                                },
                                {
                                  id: "slot-%parent%-unitType-%index%",
                                  name: "Type",
                                  offset: 0x484,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "unitTypes",
                                  autocomplete: true,
                                },
                                {
                                  id: "unitJob-%index%",
                                  name: "Job",
                                  offset: 0x486,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "jobs",
                                  size: "lg",
                                  autocomplete: true,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  id: "unitLevel-%index%",
                                  name: "Level",
                                  offset: 0x49a,
                                  type: "variable",
                                  dataType: "uint8",
                                  min: 1,
                                  max: 99,
                                },
                                {
                                  name: "Experience",
                                  offset: 0x499,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 99,
                                },
                                {
                                  name: "Gender",
                                  offset: 0x488,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: { bitStart: 5, bitLength: 3 },
                                  hidden: true,
                                },
                                {
                                  name: "Guest",
                                  offset: 0x488,
                                  type: "variable",
                                  dataType: "lower4",
                                  hidden: true,
                                },
                                {
                                  name: "Status",
                                  offset: 0x554,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "unitStatus",
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Birthday",
                                  type: "group",
                                  items: [
                                    {
                                      id: "birthday-months",
                                      offset: 0x489,
                                      type: "variable",
                                      dataType: "uint16",
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 9,
                                      },
                                      resource: "months",
                                    },
                                    {
                                      id: "birthday-days",
                                      offset: 0x489,
                                      type: "variable",
                                      dataType: "uint16",
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 9,
                                      },
                                      min: 1,
                                      max: 31,
                                    },
                                  ],
                                },
                                {
                                  name: "Zodiac Sign",
                                  offset: 0x48a,
                                  type: "variable",
                                  dataType: "upper4",
                                  resource: "signs",
                                  autocomplete: true,
                                },
                                {
                                  name: "Brave",
                                  offset: 0x49b,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 100,
                                },
                                {
                                  name: "Faith",
                                  offset: 0x49c,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 100,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              noMargin: true,
                              items: [
                                {
                                  name: "Base HP",
                                  offset: 0x49d,
                                  type: "variable",
                                  dataType: "uint24",
                                  operations: [{ "/": 1638400 }, { round: 2 }],
                                  step: 0.01,
                                  max: 10.23,
                                },
                                {
                                  name: "Base MP",
                                  offset: 0x4a0,
                                  type: "variable",
                                  dataType: "uint24",
                                  operations: [{ "/": 1638400 }, { round: 2 }],
                                  step: 0.01,
                                  max: 10.23,
                                },
                                {
                                  name: "Base Speed",
                                  offset: 0x4a3,
                                  type: "variable",
                                  dataType: "uint24",
                                  operations: [{ "/": 1638400 }, { round: 2 }],
                                  step: 0.01,
                                  max: 10.23,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Base Physical AT",
                                  offset: 0x4a6,
                                  type: "variable",
                                  dataType: "uint24",
                                  operations: [{ "/": 1638400 }, { round: 2 }],
                                  step: 0.01,
                                  max: 10.23,
                                },
                                {
                                  name: "Base Magic AT",
                                  offset: 0x4a9,
                                  type: "variable",
                                  dataType: "uint24",
                                  operations: [{ "/": 1683400 }, { round: 2 }],
                                  step: 0.01,
                                  max: 9.96,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Unknown 487",
                                  offset: 0x487,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 488",
                                  offset: 0x488,
                                  type: "variable",
                                  dataType: "bit",
                                  bit: 4,
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4ac",
                                  offset: 0x4ac,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4ad",
                                  offset: 0x4ad,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4ae",
                                  offset: 0x4ae,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4e8",
                                  offset: 0x4e8,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4e9",
                                  offset: 0x4e9,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4ea",
                                  offset: 0x4ea,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4eb",
                                  offset: 0x4eb,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4ec",
                                  offset: 0x4ec,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4ed",
                                  offset: 0x4ed,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4ee",
                                  offset: 0x4ee,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4ef",
                                  offset: 0x4ef,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4f0",
                                  offset: 0x4f0,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 4f1",
                                  offset: 0x4f1,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 551",
                                  offset: 0x551,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 552",
                                  offset: 0x552,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 553",
                                  offset: 0x553,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 555",
                                  offset: 0x555,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 556",
                                  offset: 0x556,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 557",
                                  offset: 0x557,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 558",
                                  offset: 0x558,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 559",
                                  offset: 0x559,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 55a",
                                  offset: 0x55a,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 55b",
                                  offset: 0x55b,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 55c",
                                  offset: 0x55c,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 55d",
                                  offset: 0x55d,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 55e",
                                  offset: 0x55e,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 55f",
                                  offset: 0x55f,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 560",
                                  offset: 0x560,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 561",
                                  offset: 0x561,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 562",
                                  offset: 0x562,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Unknown 563",
                                  offset: 0x563,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Equipment",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  id: "hand",
                                  name: "Right Hand",
                                  offset: 0x495,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "hands",
                                  autocomplete: true,
                                },
                                {
                                  id: "hand",
                                  name: "Left Hand",
                                  offset: 0x497,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "hands",
                                  autocomplete: true,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              hidden: true,
                              items: [
                                {
                                  name: "Right Hand (Weapon)",
                                  offset: 0x495,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Right Hand (Shield)",
                                  offset: 0x496,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },

                                {
                                  name: "Left Hand (Weapon)",
                                  offset: 0x497,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  name: "Left Hand (Shield)",
                                  offset: 0x498,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Head",
                                  offset: 0x492,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "heads",
                                  autocomplete: true,
                                },
                                {
                                  name: "Body",
                                  offset: 0x493,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "bodies",
                                  autocomplete: true,
                                },
                                {
                                  name: "Accessory",
                                  offset: 0x494,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "accessories",
                                  autocomplete: true,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Action Ability",
                                  offset: 0x48b,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "actionAbilities",
                                  autocomplete: true,
                                },
                                {
                                  name: "Reaction Ability",
                                  offset: 0x48c,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "reactionAbilities",
                                  autocomplete: true,
                                },
                                {
                                  name: "Support Ability",
                                  offset: 0x48e,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "supportAbilities",
                                  autocomplete: true,
                                },
                                {
                                  name: "Move Ability",
                                  offset: 0x490,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "moveAbilities",
                                  autocomplete: true,
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Abilities",
                          items: [
                            {
                              type: "component",
                              component: "Abilities",
                              props: {
                                slotIndex: "slots",
                                unitIndex: "units",
                              },
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Inventory",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: inventory.map((type) => ({
                    name: type.name,
                    items: type.subtypes.map((subtype) => ({
                      name: subtype.name,
                      type: "section",
                      flex: true,
                      items: subtype.items.map((item) => ({
                        name: item.name,
                        offset: 0x1605 + item.index,
                        type: "variable",
                        dataType: "uint8",
                        max: 99,
                      })),
                    })),
                  })),
                },
              ],
            },
            {
              name: "Propositions",
              items: [
                {
                  id: "propositionsTabs-%index%",
                  length: 0x9,
                  type: "container",
                  instanceType: "tabs",
                  instances: 8,
                  resource: "propositionNames",
                  vertical: true,
                  prependSubinstance: [
                    {
                      name: "General",
                      items: [
                        {
                          id: "propositionsSlots-%index%",
                          name: "Propositions",
                          offset: 0x438,
                          type: "variable",
                          dataType: "uint8",
                          max: 8,
                        },
                      ],
                    },
                  ],
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "slot-%parent%-proposition-%index%",
                          name: "Proposition",
                          offset: 0x43a,
                          type: "variable",
                          dataType: "uint8",
                          resource: "propositions",
                          size: "lg",
                          autocomplete: true,
                        },
                        {
                          name: "Progression",
                          offset: 0x439,
                          type: "variable",
                          dataType: "uint8",
                          resource: "propositionProgressions",
                        },
                        {
                          name: "Days",
                          type: "group",
                          mode: "fraction",
                          items: [
                            {
                              offset: 0x43b,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              offset: 0x43c,
                              type: "variable",
                              dataType: "uint8",
                            },
                          ],
                        },
                        {
                          name: "Place",
                          offset: 0x43d,
                          type: "variable",
                          dataType: "uint8",
                          resource: "locations",
                          autocomplete: true,
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Units Sent",
                          offset: 0x43e,
                          type: "variable",
                          dataType: "uint8",
                          max: 3,
                        },
                        {
                          id: "propositionUnit-1",
                          name: "Unit 1",
                          offset: 0x43f,
                          type: "variable",
                          dataType: "uint8",
                          resource: "unitNames",
                          autocomplete: true,
                        },
                        {
                          id: "propositionUnit-2",
                          name: "Unit 2",
                          offset: 0x440,
                          type: "variable",
                          dataType: "uint8",
                          resource: "unitNames",
                          autocomplete: true,
                        },
                        {
                          id: "propositionUnit-3",
                          name: "Unit 3",
                          offset: 0x441,
                          type: "variable",
                          dataType: "uint8",
                          resource: "unitNames",
                          autocomplete: true,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Brave Story",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      flex: true,
                      items: [
                        {
                          name: "Injured",
                          offset: 0x1a08,
                          type: "variable",
                          dataType: "uint32",
                          max: 9999,
                        },
                        {
                          name: "Casualties",
                          offset: 0x1a0c,
                          type: "variable",
                          dataType: "uint32",
                          max: 9999,
                        },
                      ],
                    },
                    {
                      name: "Record",
                      items: [
                        {
                          type: "bitflags",
                          flags: [
                            { offset: 0x1aab, bit: 4, label: "Cadets" },
                            { offset: 0x1aab, bit: 5, label: "Death of father Balbanes" },
                            { offset: 0x1aab, bit: 6, label: "First meeting with Algus" },
                            { offset: 0x1aab, bit: 7, label: "Reunion with Dycedarg" },
                            { offset: 0x1aac, bit: 0, label: "At Igros Castle" },
                            { offset: 0x1aac, bit: 1, label: "After Gustav!" },
                            { offset: 0x1aac, bit: 2, label: "Rescue of Marquis Elmdor" },
                            { offset: 0x1aac, bit: 3, label: "Master of Gallione" },
                            { offset: 0x1aac, bit: 4, label: "Lady of the Death Corps" },
                            { offset: 0x1aac, bit: 5, label: "Attack by the Death Corps!" },
                            { offset: 0x1aac, bit: 6, label: "Delita's Anger" },
                            { offset: 0x1aac, bit: 7, label: "Reed pipe" },
                            { offset: 0x1aad, bit: 0, label: "One rock and a small ripple" },
                            { offset: 0x1aad, bit: 1, label: "And I escaped..." },
                            { offset: 0x1aad, bit: 2, label: "Prayer of Queen Ovelia" },
                            { offset: 0x1aad, bit: 3, label: "Ovelia chase" },
                            { offset: 0x1aad, bit: 4, label: "Reunion with Delita" },
                            { offset: 0x1aad, bit: 5, label: "Machinist" },
                            { offset: 0x1aad, bit: 6, label: "Worries of Ovelia" },
                            { offset: 0x1aad, bit: 7, label: "Dycedarg's plans" },
                            { offset: 0x1aae, bit: 0, label: "Cardinal Draclau and the Holy Stone" },
                            { offset: 0x1aae, bit: 1, label: "Those who seek the Holy Stone" },
                            { offset: 0x1aae, bit: 2, label: "Besrodio rescue" },
                            { offset: 0x1aae, bit: 3, label: "Delita's advice" },
                            { offset: 0x1aae, bit: 4, label: "Cardinal's anger" },
                            { offset: 0x1aae, bit: 5, label: "Those who use, those who get used" },
                            { offset: 0x1aae, bit: 6, label: "The Lion War Outbreak" },
                            { offset: 0x1aae, bit: 7, label: "T.G. Cid" },
                            { offset: 0x1aaf, bit: 0, label: "First meeting with Olan" },
                            { offset: 0x1aaf, bit: 1, label: "Reunion with Zalbag" },
                            { offset: 0x1aaf, bit: 2, label: 'As a "Heretic"' },
                            { offset: 0x1aaf, bit: 3, label: "Confessions of Simon" },
                            { offset: 0x1aaf, bit: 4, label: "Velius" },
                            { offset: 0x1aaf, bit: 5, label: "Ovelia and Delita" },
                            { offset: 0x1aaf, bit: 6, label: "Son of T.G. Cid" },
                            { offset: 0x1aaf, bit: 7, label: "Divine Rafa" },
                            { offset: 0x1ab0, bit: 0, label: "Ambitions of Prince Barinten" },
                            { offset: 0x1ab0, bit: 1, label: "Escaping Alma" },
                            { offset: 0x1ab0, bit: 2, label: "Scars of a tragedy" },
                            { offset: 0x1ab0, bit: 3, label: "The other power" },
                            { offset: 0x1ab0, bit: 4, label: "The lying heart" },
                            { offset: 0x1ab0, bit: 5, label: "Those who squirm in darkness" },
                            { offset: 0x1ab0, bit: 6, label: "A man with the Holy Stone" },
                            { offset: 0x1ab0, bit: 7, label: "Delita's thoughts" },
                            { offset: 0x1ab1, bit: 0, label: "Unstoppable cog" },
                            { offset: 0x1ab1, bit: 1, label: "Seized T.G. Cid" },
                            { offset: 0x1ab1, bit: 2, label: "Assassination of Prince Larg!" },
                            { offset: 0x1ab1, bit: 3, label: "Rescue of Cid" },
                            { offset: 0x1ab1, bit: 4, label: "Prince Goltana's final moments" },
                            { offset: 0x1ab1, bit: 5, label: "Ambitions of Dycedarg" },
                            { offset: 0x1ab1, bit: 6, label: "Men of odd appearance" },
                            { offset: 0x1ab1, bit: 7, label: "The mystery of Lucavi" },
                            { offset: 0x1ab2, bit: 0, label: "Delita's betrayal" },
                            { offset: 0x1ab2, bit: 1, label: "Mosfungus" },
                            { offset: 0x1ab2, bit: 2, label: "Funeral's final moments" },
                            { offset: 0x1ab2, bit: 3, label: "Requiem" },
                            { offset: 0x1ab2, bit: 4, label: "Steel Ball found!" },
                            { offset: 0x1ab2, bit: 5, label: "The Steel Giant starts!" },
                            { offset: 0x1ab2, bit: 6, label: "Celestial Globe found!?" },
                            { offset: 0x1ab2, bit: 7, label: "Summon Cloud!" },
                            { offset: 0x1ab3, bit: 0, label: "Reis's curse" },
                            { offset: 0x1ab3, bit: 1, label: "Entrance to the other world" },
                            { offset: 0x1ab3, bit: 2, label: "Reunion and beyond..." },
                            { offset: 0x1ab3, bit: 3, label: "Things obtained" },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Person",
                      flex: true,
                      items: persons.map((person) => ({
                        name: person.name,
                        offset: 0x1b10 + Math.floor(person.index / 0x2),
                        type: "variable",
                        dataType: person.index % 2 === 0 ? "lower4" : "upper4",
                        max: person.max,
                      })),
                    },
                    {
                      name: "Job",
                      items: propositionList.map((job) => ({
                        type: "section",
                        flex: true,
                        noMargin: true,
                        items: [
                          {
                            id: `braveStory-job-${job.index}`,
                            name: job.jobName,
                            offset: 0x1ae0 + Math.floor(job.index / 0x2),
                            type: "variable",
                            dataType: "bit",
                            bit: job.index % 2 === 0 ? 2 : 6,
                            resource: "booleanCleared",
                          },
                          {
                            name: "Start",
                            type: "group",
                            items: [
                              {
                                id: `start-job-${job.index}-months`,
                                offset:
                                  0x16b + getDateOffset(job.index, "months"),
                                type: "variable",
                                dataType: "uint16",
                                binary: {
                                  bitStart: (5 + job.index * 9) % 8,
                                  bitLength: 4,
                                },
                                resource: "months",
                              },
                              {
                                id: `start-job-${job.index}-days`,
                                offset:
                                  0x16b + getDateOffset(job.index, "days"),
                                type: "variable",
                                dataType: "uint16",
                                binary: {
                                  bitStart: (job.index * 9) % 8,
                                  bitLength: 5,
                                },
                                min: 1,
                                max: 31,
                              },
                            ],
                          },
                        ],
                      })),
                    },
                    {
                      name: "Unexplored Land",
                      items: unexploredLands.map((land) => ({
                        type: "section",
                        flex: true,
                        noMargin: true,
                        items: [
                          {
                            id: `braveStory-land-${land.index}`,
                            name: land.name,
                            offset: 0x1ade + Math.floor(land.index / 0x8),
                            type: "variable",
                            dataType: "bit",
                            bit: land.index % 8,
                            resource: "booleanDiscovered",
                          },
                          {
                            name: "Start",
                            type: "group",
                            items: [
                              {
                                id: `start-land-${land.index}-months`,
                                offset:
                                  0x159 + getDateOffset(land.index, "months"),
                                type: "variable",
                                dataType: "uint16",
                                binary: {
                                  bitStart: (5 + land.index * 9) % 8,
                                  bitLength: 4,
                                },
                                resource: "months",
                              },
                              {
                                id: `start-land-${land.index}-days`,
                                offset:
                                  0x159 + getDateOffset(land.index, "days"),
                                type: "variable",
                                dataType: "uint16",
                                binary: {
                                  bitStart: (land.index * 9) % 8,
                                  bitLength: 5,
                                },
                                min: 1,
                                max: 31,
                              },
                            ],
                          },
                        ],
                      })),
                    },
                    {
                      name: "Treasure",
                      items: treasures.map((treasure) => ({
                        type: "section",
                        flex: true,
                        noMargin: true,
                        items: [
                          {
                            id: `braveStory-treasure-${treasure.index}`,
                            name: treasure.name,
                            offset:
                              0x1ad8 + Math.floor((1 + treasure.index) / 0x8),
                            type: "variable",
                            dataType: "bit",
                            bit: (1 + treasure.index) % 8,
                            resource: "booleanObtained",
                          },
                          {
                            name: "Start",
                            type: "group",
                            items: [
                              {
                                id: `start-treasure-${treasure.index}-months`,
                                offset:
                                  0x124 +
                                  getDateOffset(treasure.index, "months"),
                                type: "variable",
                                dataType: "uint16",
                                binary: {
                                  bitStart: (5 + treasure.index * 9) % 8,
                                  bitLength: 4,
                                },
                                resource: "months",
                              },
                              {
                                id: `start-treasure-${treasure.index}-days`,
                                offset:
                                  0x124 + getDateOffset(treasure.index, "days"),
                                type: "variable",
                                dataType: "uint16",
                                binary: {
                                  bitStart: (treasure.index * 9) % 8,
                                  bitLength: 5,
                                },
                                min: 1,
                                max: 31,
                              },
                            ],
                          },
                        ],
                      })),
                    },
                  ],
                },
              ],
            },
            {
              name: "Option",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Cursor movement",
                      offset: 0x1c84,
                      type: "variable",
                      dataType: "bit",
                      bit: 0,
                      resource: "cursorMovements",
                    },
                    {
                      name: "Cursor repeat speed",
                      offset: 0x1c84,
                      type: "variable",
                      dataType: "uint8",
                      binary: { bitStart: 3, bitLength: 2 },
                      resource: "speeds1",
                    },
                    {
                      name: "Cursor speed on mult. heights",
                      offset: 0x1c84,
                      type: "variable",
                      dataType: "uint8",
                      binary: { bitStart: 6, bitLength: 2 },
                      resource: "speeds2",
                    },
                    {
                      name: "Finger cursor repeat speed",
                      offset: 0x1c85,
                      type: "variable",
                      dataType: "uint8",
                      binary: { bitStart: 1, bitLength: 3 },
                      resource: "speeds3",
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Message display speed",
                      offset: 0x1c85,
                      type: "variable",
                      dataType: "uint8",
                      binary: { bitStart: 4, bitLength: 2 },
                      resource: "speeds1",
                    },
                    {
                      name: "Navigation message",
                      offset: 0x1c85,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      resource: "optionBoolean",
                    },
                    {
                      name: "Show Ability name",
                      offset: 0x1c86,
                      type: "variable",
                      dataType: "bit",
                      bit: 1,
                      resource: "optionBoolean",
                    },
                    {
                      name: "Show effect message",
                      offset: 0x1c86,
                      type: "variable",
                      dataType: "bit",
                      bit: 3,
                      resource: "optionBoolean",
                    },
                    {
                      name: "Show Exp and Jp gained",
                      offset: 0x1c87,
                      type: "variable",
                      dataType: "bit",
                      bit: 1,
                      resource: "optionBoolean",
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Target flashing",
                      offset: 0x1c87,
                      type: "variable",
                      dataType: "bit",
                      bit: 3,
                      resource: "optionBoolean",
                    },
                    {
                      name: "Show unequippable item by Job",
                      offset: 0x1c86,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      resource: "optionBoolean",
                    },
                    {
                      name: "Max equip at Job change",
                      offset: 0x1c87,
                      type: "variable",
                      dataType: "bit",
                      bit: 5,
                      resource: "optionBoolean",
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Sound",
                      offset: 0x1c86,
                      type: "variable",
                      dataType: "uint8",
                      binary: { bitStart: 5, bitLength: 2 },
                      resource: "sounds",
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    accessories: {
      0x0: "Empty",
      ...accessories,
      0xff: "-",
    },
    actionAbilities: {
      0x0: "-",
      0x1: "Attack",
      0x2: "Defend",
      0x3: "Equip Change",
      0x5: "Basic Skill",
      0x6: "Item",
      0x7: "Battle Skill",
      0x8: "Charge",
      0x9: "Punch Art",
      0xa: "White Magic",
      0xb: "Black Magic",
      0xc: "Time Magic",
      0xd: "Summon Magic",
      0xe: "Steal",
      0xf: "Talk Skill",
      0x10: "Yin Yang Magic",
      0x11: "Elemental",
      0x12: "Jump",
      0x13: "Draw Out",
      0x14: "Throw",
      0x15: "Math Skill",
      0x16: "Sing",
      0x17: "Dance",
      0x18: "Mimic",
      0x19: "Guts",
      0x1a: "Guts",
      0x1b: "Guts",
      0x1c: "Guts",
    },
    bodies: {
      0x0: "Empty",
      ...bodies,
      0xff: "-",
    },
    booleanCleared: {
      0x0: "-",
      0x1: "Cleared",
    },
    booleanDiscovered: {
      0x0: "-",
      0x1: "Discovered",
    },
    booleanObtained: {
      0x0: "-",
      0x1: "Obtained",
    },
    cursorMovements: {
      0x0: "A type",
      0x1: "B type",
    },
    empty: {
      0x0: "-",
    },
    hands: {
      0x0: "Empty",
      ...hands,
      0xff: "-",
    },
    heads: {
      0x0: "Empty",
      ...heads,
      0xff: "-",
    },
    jobs: {
      0x0: "-",
      ...jobs,
    },
    letters: [...Array(2).keys()].map((index) => ({
      0x0: "0",
      0x1: "1",
      0x2: "2",
      0x3: "3",
      0x4: "4",
      0x5: "5",
      0x6: "6",
      0x7: "7",
      0x8: "8",
      0x9: "9",
      0xa: "A",
      0xb: "B",
      0xc: "C",
      0xd: "D",
      0xe: "E",
      0xf: "F",
      0x10: "G",
      0x11: "H",
      0x12: "I",
      0x13: "J",
      0x14: "K",
      0x15: "L",
      0x16: "M",
      0x17: "N",
      0x18: "O",
      0x19: "P",
      0x1a: "Q",
      0x1b: "R",
      0x1c: "S",
      0x1d: "T",
      0x1e: "U",
      0x1f: "V",
      0x20: "W",
      0x21: "X",
      0x22: "Y",
      0x23: "Z",
      0x24: "a",
      0x25: "b",
      0x26: "c",
      0x27: "d",
      0x28: "e",
      0x29: "f",
      0x2a: "g",
      0x2b: "h",
      0x2c: "i",
      0x2d: "j",
      0x2e: "k",
      0x2f: "l",
      0x30: "m",
      0x31: "n",
      0x32: "o",
      0x33: "p",
      0x34: "q",
      0x35: "r",
      0x36: "s",
      0x37: "t",
      0x38: "u",
      0x39: "v",
      0x3a: "w",
      0x3b: "x",
      0x3c: "y",
      0x3d: "z",
      // USA
      ...(index === 0 &&
        ({
          0x3e: "!",
          0x40: "?",
          0x42: "+",
          0x44: "/",
          0x46: ":",
          0x5f: ".",
          0x8b: "・",
          0x8d: "(",
          0x8e: ")",
          0x91: '"',
          0x93: "'",
          0xfa: " ",
        } as Resource)),
      // Japan
      ...((index === 1 && {
        0x3e: "ぁ",
        0x3f: "あ",
        0x40: "ぃ",
        0x41: "い",
        0x42: "ぅ",
        0x43: "う",
        0x44: "ぇ",
        0x45: "え",
        0x46: "ぉ",
        0x47: "お",
        0x48: "か",
        0x49: "が",
        0x4a: "き",
        0x4b: "ぎ",
        0x4c: "く",
        0x4d: "ぐ",
        0x4e: "け",
        0x4f: "げ",
        0x50: "こ",
        0x51: "ご",
        0x52: "さ",
        0x53: "ざ",
        0x54: "し",
        0x55: "じ",
        0x56: "す",
        0x57: "ず",
        0x58: "せ",
        0x59: "ぜ",
        0x5a: "そ",
        0x5b: "ぞ",
        0x5c: "た",
        0x5d: "だ",
        0x5e: "ち",
        0x60: "っ",
        0x61: "つ",
        0x62: "づ",
        0x63: "て",
        0x64: "で",
        0x65: "と",
        0x66: "ど",
        0x67: "な",
        0x68: "に",
        0x69: "ぬ",
        0x6a: "ね",
        0x6b: "の",
        0x6c: "は",
        0x6d: "ば",
        0x6e: "ぱ",
        0x6f: "ひ",
        0x70: "び",
        0x71: "ぴ",
        0x72: "ふ",
        0x73: "ぶ",
        0x74: "ぷ",
        0x75: "へ",
        0x76: "べ",
        0x77: "ぺ",
        0x78: "ほ",
        0x79: "ぼ",
        0x7a: "ぽ",
        0x7b: "ま",
        0x7c: "み",
        0x7d: "む",
        0x7e: "め",
        0x7f: "も",
        0x80: "ゃ",
        0x81: "や",
        0x82: "ゅ",
        0x83: "ゆ",
        0x84: "ょ",
        0x85: "よ",
        0x86: "ら",
        0x87: "り",
        0x88: "る",
        0x89: "れ",
        0x8a: "ろ",
        0x8c: "わ",
        0x8f: "を",
        0x90: "ん",
        0x91: "ァ",
        0x92: "ア",
        0x93: "ィ",
        0x94: "イ",
        0x95: "ゥ",
        0x96: "ウ",
        0x97: "ェ",
        0x98: "エ",
        0x99: "ォ",
        0x9a: "オ",
        0x9b: "カ",
        0x9c: "ガ",
        0x9d: "キ",
        0x9e: "ギ",
        0x9f: "ク",
        0xa0: "グ",
        0xa1: "ケ",
        0xa2: "ゲ",
        0xa3: "コ",
        0xa4: "ゴ",
        0xa5: "サ",
        0xa6: "ザ",
        0xa7: "シ",
        0xa8: "ジ",
        0xa9: "ス",
        0xaa: "ズ",
        0xab: "セ",
        0xac: "ゼ",
        0xad: "ソ",
        0xae: "ゾ",
        0xaf: "タ",
        0xb0: "ダ",
        0xb1: "チ",
        0xb3: "ッ",
        0xb4: "ツ",
        0xb6: "テ",
        0xb7: "デ",
        0xb8: "ト",
        0xb9: "ド",
        0xba: "ナ",
        0xbb: "ニ",
        0xbc: "ヌ",
        0xbd: "ネ",
        0xbe: "ノ",
        0xbf: "ハ",
        0xc0: "バ",
        0xc1: "パ",
        0xc2: "ヒ",
        0xc3: "ビ",
        0xc4: "ピ",
        0xc5: "フ",
        0xc6: "ブ",
        0xc7: "プ",
        0xc8: "ヘ",
        0xc9: "ベ",
        0xca: "ペ",
        0xcb: "ホ",
        0xcc: "ボ",
        0xcd: "ポ",
        0xce: "マ",
        0xcf: "ミ",
        0xfa: " ",
        0xd100: "ム",
        0xd101: "メ",
        0xd102: "モ",
        0xd103: "ャ",
        0xd104: "ヤ",
        0xd105: "ュ",
        0xd106: "ユ",
        0xd107: "ョ",
        0xd108: "ヨ",
        0xd109: "ラ",
        0xd10a: "リ",
        0xd10b: "ル",
        0xd10c: "レ",
        0xd10d: "ロ",
        0xd10e: "ヮ",
        0xd10f: "ワ",
        0xd110: "↪",
        0xd112: "ヲ",
        0xd113: "ン",
        0xd114: "ヴ",
        0xd115: "ヵ",
        0xd116: "ヶ",
        0xd117: "ー",
        0xd118: "「",
        0xd119: "、",
        0xd11a: "!",
        0xd11b: "…",
        0xd11c: "。",
        0xd11e: "+",
        0xd11f: "X",
        0xd9b9: "◯",
        0xd9bc: "・",
        0xd9bd: ":",
        0xd9be: "(",
        0xd9bf: ")",
        0xd9c0: "“",
        0xd9c1: "”",
        0xd9c2: "『",
        0xd9c3: "』",
        0xd9c4: "」",
        0xd9c5: "~",
        0xd9c6: "/",
        0xd9c7: "△",
        0xd9c8: "□",
        0xd9c9: "?",
        0xd9ca: "♥",
        0xd9cb: "Ⅰ",
        0xd9cc: "Ⅱ",
        0xd9cd: "Ⅲ",
        0xd9ce: "Ⅳ",
        0xd9cf: "Ⅴ",
        0xda00: "♈",
        0xda01: "♉",
        0xda02: "♊",
        0xda03: "♋",
        0xda04: "♌",
        0xda05: "♍",
        0xda06: "♎",
        0xda07: "♏",
        0xda08: "♐",
        0xda09: "♑",
        0xda0a: "♒",
        0xda0b: "♓",
        0xda0c: "⛎︎",
      }) as Resource),
    })),
    locations,
    monsters,
    months: {
      0x1: "January",
      0x2: "February",
      0x3: "March",
      0x4: "April",
      0x5: "May",
      0x6: "June",
      0x7: "July",
      0x8: "August",
      0x9: "September",
      0xa: "October",
      0xb: "November",
      0xc: "December",
    },
    moveAbilities: {
      0x0: "-",
      ...moveAbilities,
    },
    optionBoolean: {
      0x0: "On",
      0x1: "Off",
    },
    propositionNames: "getPropositionNames()",
    propositionProgressions: {
      0x0: "-",
      0x1: "In Progress",
      0x3: "Called Back",
      0x5: "Report Ready",
    },
    propositions,
    reactionAbilities: {
      0x0: "-",

      ...reactionAbilities,
    },
    signs: {
      0x0: "Aries",
      0x1: "Taurus",
      0x2: "Gemini",
      0x3: "Cancer",
      0x4: "Leo",
      0x5: "Virgo",
      0x6: "Libra",
      0x7: "Scorpio",
      0x8: "Sagittarius",
      0x9: "Capricorn",
      0xa: "Aquarius",
      0xb: "Pisces",
      0xc: "Serpentarius",
    },
    sounds: {
      0x0: "Mono",
      0x1: "Stereo",
      0x2: "Wide",
    },
    speeds1: {
      0x0: "Fast",
      0x1: "Regular",
      0x2: "Slow",
    },
    speeds2: {
      0x0: "Fast",
      0x1: "Regular",
      0x2: "Slow",
      0x3: "Stop",
    },
    speeds3: {
      0x0: "Fastest",
      0x1: "Faster",
      0x2: "Fast",
      0x3: "Regular",
      0x4: "Slow",
      0x5: "Slower",
      0x6: "Slowest",
    },
    supportAbilities: {
      0x0: "-",
      ...supportAbilities,
    },
    unitNames: "getUnitNames()",
    unitStatus: {
      0x0: "-",
      0x1: "Leaving Temporary",
    },
    unitTypes: {
      0x0: "-",
      ...unitTypes,
    },
  },
  resourcesGroups: {
    accessories: accessoriesGroups,
    bodies: bodiesGroups,
    hands: handsGroups,
    heads: headsGroups,
    jobs: [
      {
        name: "Main",
        options: [
          0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f, 0x50, 0x51, 0x52, 0x53, 0x54,
          0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d,
        ],
      },
      {
        name: "Miscellaneous",
        options: [
          0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xc, 0xd, 0xe,
          0xf, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a,
          0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25,
          0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30,
          0x31, 0x32, 0x33, 0x34, 0x3c, 0x3e, 0x40, 0x41, 0x43, 0x45, 0x48,
          0x49,
        ],
      },
    ],
    unitTypes: [
      {
        name: "Party",
        options: [
          0x1, 0x2, 0x3, 0xd, 0xf, 0x16, 0x19, 0x1a, 0x1e, 0x1f, 0x22, 0x29,
          0x2a, 0x2f, 0x32, 0x34,
        ],
      },
      {
        name: "Guests",
        options: [
          0x4, 0x5, 0x6, 0x7, 0x8, 0xc, 0x11, 0x15, 0x17, 0x1c, 0x2c, 0x30,
        ],
      },
      {
        name: "Fighters",
        options: [0x80, 0x81, 0x82],
      },
      {
        name: "Lucavi",
        options: [0x3c, 0x3e, 0x40, 0x41, 0x43, 0x45],
      },
      {
        name: "Miscellaneous",
        options: [
          0x9, 0xa, 0xb, 0xe, 0x10, 0x13, 0x18, 0x1b, 0x1d, 0x20, 0x21, 0x23,
          0x24, 0x25, 0x26, 0x27, 0x28, 0x2b, 0x2d, 0x2e, 0x31, 0x33,
        ],
      },
      {
        name: "Unused",
        options: [0x12, 0x14, 0x3a, 0x3b, 0x48, 0x49],
      },
    ],
  },
  resourcesOrder: {
    accessories: [0xff],
    bodies: [0xff],
    hands: [0xff],
    heads: [0xff],
  },
};

export default template;
