export const gummiBlocks = [
  {
    name: "Cockpits",
    sections: [
      {
        blocks: [
          { index: 0x00, name: "Cure-G", max: 1 },
          { index: 0x01, name: "Curaga-G", max: 1 },
        ],
      },
      {
        blocks: [
          { index: 0x02, name: "Life-G", max: 1 },
          { index: 0x03, name: "Full-Life-G", max: 1 },
        ],
      },
    ],
  },
  {
    name: "Engines",
    sections: [
      {
        blocks: [
          { index: 0x04, name: "Fire-G", max: 6 },
          { index: 0x05, name: "Fira-G", max: 6 },
          { index: 0x06, name: "Firaga-G", max: 4 },
        ],
      },
      {
        blocks: [
          { index: 0x07, name: "Flare-G", max: 4 },
          { index: 0x08, name: "Holy-G", max: 2 },
        ],
      },
    ],
  },
  {
    name: "Armors",
    sections: [
      {
        blocks: [
          { index: 0x09, name: "Protect-G", max: 99 },
          { index: 0x0a, name: "Protect-G", max: 99 },
          { index: 0x0b, name: "Protect-G", max: 99 },
          { index: 0x0c, name: "Protect-G", max: 30 },
          { index: 0x0d, name: "Protect-G", max: 30 },
          { index: 0x0e, name: "Protect-G", max: 10 },
          { index: 0x0f, name: "Protect-G", max: 10 },
          { index: 0x10, name: "Protect-G", max: 10 },
        ],
      },
      {
        blocks: [
          { index: 0x11, name: "Shell-G", max: 99 },
          { index: 0x12, name: "Shell-G", max: 99 },
          { index: 0x13, name: "Shell-G", max: 99 },
          { index: 0x14, name: "Shell-G", max: 20 },
          { index: 0x15, name: "Shell-G", max: 20 },
          { index: 0x16, name: "Shell-G", max: 8 },
          { index: 0x17, name: "Shell-G", max: 8 },
          { index: 0x18, name: "Shell-G", max: 8 },
        ],
      },
      {
        blocks: [
          { index: 0x19, name: "Dispel-G", max: 99 },
          { index: 0x1a, name: "Dispel-G", max: 99 },
          { index: 0x1b, name: "Dispel-G", max: 99 },
          { index: 0x1c, name: "Dispel-G", max: 10 },
          { index: 0x1d, name: "Dispel-G", max: 10 },
          { index: 0x1e, name: "Dispel-G", max: 6 },
          { index: 0x1f, name: "Dispel-G", max: 6 },
          { index: 0x20, name: "Dispel-G", max: 6 },
        ],
      },
    ],
  },
  {
    name: "Wings",
    sections: [
      {
        blocks: [
          { index: 0x21, name: "Aerora-G ►", max: 30 },
          { index: 0x22, name: "Aerora-G ◄", max: 30 },
        ],
      },
      {
        blocks: [
          { index: 0x23, name: "Aeroga-G ►", max: 20 },
          { index: 0x24, name: "Aeroga-G ◄", max: 20 },
        ],
      },
      {
        blocks: [
          { index: 0x25, name: "Tornado-G ►", max: 10 },
          { index: 0x26, name: "Tornado-G ◄", max: 10 },
        ],
      },
      {
        blocks: [
          { index: 0x27, name: "Float-G ►", max: 10 },
          { index: 0x28, name: "Float-G ◄", max: 10 },
        ],
      },
      {
        blocks: [
          { index: 0x29, name: "Aero-G ►", max: 99 },
          { index: 0x2a, name: "Aero-G ◄", max: 99 },
          { index: 0x2b, name: "Aero-G □", max: 99 },
        ],
      },
    ],
  },
  {
    name: "Specials",
    sections: [
      {
        blocks: [
          { index: 0x2c, name: "Drain-G ►", max: 4 },
          { index: 0x2d, name: "Drain-G ◄", max: 4 },
        ],
      },
      {
        blocks: [
          { index: 0x2e, name: "Osmose-G ►", max: 2 },
          { index: 0x2f, name: "Osmose-G ◄", max: 2 },
        ],
      },
      {
        blocks: [
          { index: 0x30, name: "Transform-G", max: 1 },
          { index: 0x31, name: "Warp-G", max: 1 },
        ],
      },
      {
        blocks: [
          { index: 0x32, name: "Scan-G ▽", max: 2 },
          { index: 0x33, name: "Scan-G ◯", max: 2 },
        ],
      },
      {
        blocks: [
          { index: 0x34, name: "Haste-G", max: 2 },
          { index: 0x35, name: "Haste2-G", max: 2 },
        ],
      },
      {
        blocks: [
          { index: 0x36, name: "Shield-G", max: 1 },
          { index: 0x37, name: "Shield2-G", max: 1 },
        ],
      },
      {
        blocks: [
          { index: 0x38, name: "Esuna-G ◯", max: 6 },
          { index: 0x39, name: "Esuna-G ⬜", max: 10 },
        ],
      },
    ],
  },
  {
    name: "Weapons",
    sections: [
      {
        blocks: [
          { index: 0x3a, name: "Thunder-G", max: 10 },
          { index: 0x3b, name: "Thundara-G", max: 8 },
          { index: 0x3c, name: "Thundaga-G", max: 6 },
        ],
      },
      {
        blocks: [
          { index: 0x3d, name: "Comet-G", max: 8 },
          { index: 0x3e, name: "Meteor-G", max: 6 },
          { index: 0x3f, name: "Ultima-G", max: 4 },
        ],
      },
    ],
  },
  {
    name: "Upgrades",
    sections: [
      {
        blocks: [
          { index: 0x40, name: "Spray", max: 1 },
          { index: 0x41, name: "Palette", max: 1 },
        ],
      },
      {
        blocks: [
          { index: 0x42, name: "SYS.UP1", max: 1 },
          { index: 0x43, name: "SYS.UP2", max: 1 },
        ],
      },
      {
        blocks: [
          { index: 0x44, name: "COM.LV1", max: 1 },
          { index: 0x45, name: "COM.LV2", max: 1 },
          { index: 0x46, name: "COM.LV3", max: 1 },
        ],
      },
    ],
  },
  {
    name: "Blueprints",
    sections: [
      {
        blocks: [
          { index: 0x47, name: "Kingdom", max: 1 },
          { index: 0x48, name: "Hyperion", max: 1 },
          { index: 0x49, name: "Geppetto", max: 1 },
          { index: 0x4a, name: "Cid", max: 1 },
          { index: 0x4b, name: "Leon", max: 1 },
          { index: 0x4c, name: "Yuffie", max: 1 },
          { index: 0x4d, name: "Aerith", max: 1 },
          { index: 0x4e, name: "Cactuar", max: 1 },
          { index: 0x4f, name: "Chocobo", max: 1 },
        ],
      },
      {
        blocks: [
          { index: 0x50, name: "Cindy", max: 1 },
          { index: 0x51, name: "Shiva", max: 1 },
          { index: 0x52, name: "Lamia", max: 1 },
          { index: 0x53, name: "Sandy", max: 1 },
          { index: 0x54, name: "Sylph", max: 1 },
          { index: 0x55, name: "Carbuncle", max: 1 },
          { index: 0x56, name: "Mindy", max: 1 },
          { index: 0x57, name: "Goblin", max: 1 },
          { index: 0x58, name: "Bomb", max: 1 },
          { index: 0x59, name: "Remora", max: 1 },
          { index: 0x5a, name: "Ahriman", max: 1 },
          { index: 0x5b, name: "Imp", max: 1 },
          { index: 0x5c, name: "Siren", max: 1 },
          { index: 0x5d, name: "Stingray", max: 1 },
          { index: 0x5e, name: "Catoblepas", max: 1 },
          { index: 0x5f, name: "Adamant", max: 1 },
          { index: 0x60, name: "Serpent", max: 1 },
          { index: 0x61, name: "Ifrit", max: 1 },
          { index: 0x62, name: "Odin", max: 1 },
          { index: 0x63, name: "Atomos", max: 1 },
          { index: 0x64, name: "Golem", max: 1 },
          { index: 0x65, name: "Diablos", max: 1 },
          { index: 0x66, name: "Deathguise", max: 1 },
          { index: 0x67, name: "Typhoon", max: 1 },
          { index: 0x68, name: "Alexander", max: 1 },
          { index: 0x69, name: "Leviathan", max: 1 },
          { index: 0x6a, name: "Ramuh", max: 1 },
          { index: 0x6b, name: "Omega", max: 1 },
        ],
      },
    ],
  },
];

export const miniGames = [
  {
    name: "Jungle Slider",
    type: "time",
    categories: [
      {
        name: "Green Serpent",
        ranks: [
          { index: 0x7dc, name: "1st Place" },
          { index: 0x7e0, name: "2nd Place" },
          { index: 0x7e4, name: "3rd Place" },
          { index: 0x7e8, name: "4th Place" },
          { index: 0x7ec, name: "5th Place" },
        ],
      },
      {
        name: "Splash Tunnel",
        ranks: [
          { index: 0x7f0, name: "1st Place" },
          { index: 0x7f4, name: "2nd Place" },
          { index: 0x7f8, name: "3rd Place" },
          { index: 0x7fc, name: "4th Place" },
          { index: 0x800, name: "5th Place" },
        ],
      },
      {
        name: "Jade Spiral",
        ranks: [
          { index: 0x804, name: "1st Place" },
          { index: 0x808, name: "2nd Place" },
          { index: 0x80c, name: "3rd Place" },
          { index: 0x810, name: "4th Place" },
          { index: 0x814, name: "5th Place" },
        ],
      },
      {
        name: "Panic Fall",
        ranks: [
          { index: 0x818, name: "1st Place" },
          { index: 0x81c, name: "2nd Place" },
          { index: 0x820, name: "3rd Place" },
          { index: 0x824, name: "4th Place" },
          { index: 0x828, name: "5th Place" },
        ],
      },
      {
        name: "Shadow Cavern",
        ranks: [
          { index: 0x82c, name: "1st Place" },
          { index: 0x830, name: "2nd Place" },
          { index: 0x834, name: "3rd Place" },
          { index: 0x838, name: "4th Place" },
          { index: 0x83c, name: "5th Place" },
        ],
      },
    ],
  },
  {
    name: "Vine Jump",
    type: "time",
    categories: [
      {
        name: "Jump Course",
        ranks: [
          { index: 0x840, name: "1st Place" },
          { index: 0x844, name: "2nd Place" },
          { index: 0x848, name: "3rd Place" },
          { index: 0x84c, name: "4th Place" },
          { index: 0x850, name: "5th Place" },
        ],
      },
      {
        name: "Trap Course",
        ranks: [
          { index: 0x854, name: "1st Place" },
          { index: 0x858, name: "2nd Place" },
          { index: 0x85c, name: "3rd Place" },
          { index: 0x860, name: "4th Place" },
          { index: 0x864, name: "5th Place" },
        ],
      },
      {
        name: "Acrobatic Course",
        ranks: [
          { index: 0x868, name: "1st Place" },
          { index: 0x86c, name: "2nd Place" },
          { index: 0x870, name: "3rd Place" },
          { index: 0x874, name: "4th Place" },
          { index: 0x878, name: "5th Place" },
        ],
      },
      {
        name: "Expert Course",
        ranks: [
          { index: 0x87c, name: "1st Place" },
          { index: 0x880, name: "2nd Place" },
          { index: 0x884, name: "3rd Place" },
          { index: 0x888, name: "4th Place" },
          { index: 0x88c, name: "5th Place" },
        ],
      },
    ],
  },
  {
    name: "Pooh's Hunny Hunt",
    type: "score",
    categories: [
      {
        name: "",
        ranks: [
          { index: 0x890, name: "1st Place" },
          { index: 0x894, name: "2nd Place" },
          { index: 0x898, name: "3rd Place" },
          { index: 0x89c, name: "4th Place" },
          { index: 0x8a0, name: "5th Place" },
        ],
      },
    ],
  },
  {
    name: "Block Tigger",
    type: "score",
    categories: [
      {
        name: "",
        ranks: [
          { index: 0x8a4, name: "1st Place" },
          { index: 0x8a8, name: "2nd Place" },
          { index: 0x8ac, name: "3rd Place" },
          { index: 0x8b0, name: "4th Place" },
          { index: 0x8b4, name: "5th Place" },
        ],
      },
    ],
  },
  {
    name: "Pooh's Swing",
    type: "score",
    categories: [
      {
        name: "",
        ranks: [
          { index: 0x8b8, name: "1st Place" },
          { index: 0x8bc, name: "2nd Place" },
          { index: 0x8c0, name: "3rd Place" },
          { index: 0x8c4, name: "4th Place" },
          { index: 0x8c8, name: "5th Place" },
        ],
      },
    ],
  },
  {
    name: "Tigger's Giant Pot",
    type: "time",
    categories: [
      {
        name: "",
        ranks: [
          { index: 0x8cc, name: "1st Place" },
          { index: 0x8d0, name: "2nd Place" },
          { index: 0x8d4, name: "3rd Place" },
          { index: 0x8d8, name: "4th Place" },
          { index: 0x8dc, name: "5th Place" },
        ],
      },
    ],
  },
  {
    name: "Pooh's Muddy Path",
    type: "time",
    categories: [
      {
        name: "",
        ranks: [
          { index: 0x8e0, name: "1st Place" },
          { index: 0x8e4, name: "2nd Place" },
          { index: 0x8e8, name: "3rd Place" },
          { index: 0x8ec, name: "4th Place" },
          { index: 0x8f0, name: "5th Place" },
        ],
      },
    ],
  },
  {
    name: "Olympus Coliseum",
    type: "time",
    categories: [
      {
        name: "Training",
        ranks: [
          { index: 0x014, name: "Easy" },
          { index: 0x018, name: "Advanced" },
        ],
      },
      {
        name: "Phil Cup",
        ranks: [
          { index: 0x000, name: "1st Place" },
          { index: 0x020, name: "2nd Place" },
          { index: 0x024, name: "3rd Place" },
          { index: 0x028, name: "4th Place" },
          { index: 0x02c, name: "5th Place" },
        ],
      },
      {
        name: "Pegasus Cup",
        ranks: [
          { index: 0x004, name: "1st Place" },
          { index: 0x030, name: "2nd Place" },
          { index: 0x034, name: "3rd Place" },
          { index: 0x038, name: "4th Place" },
          { index: 0x03c, name: "5th Place" },
        ],
      },
      {
        name: "Hercules Cup",
        ranks: [
          { index: 0x008, name: "1st Place" },
          { index: 0x040, name: "2nd Place" },
          { index: 0x044, name: "3rd Place" },
          { index: 0x048, name: "4th Place" },
          { index: 0x04c, name: "5th Place" },
        ],
      },
      {
        name: "Hades Cup",
        ranks: [
          { index: 0x00c, name: "1st Place" },
          { index: 0x050, name: "2nd Place" },
          { index: 0x054, name: "3rd Place" },
          { index: 0x058, name: "4th Place" },
          { index: 0x05c, name: "5th Place" },
        ],
      },
    ],
  },
];

// prettier-ignore
export const abilityList = [
  { index: 0x01, name: "High Jump" },
  { index: 0x02, name: "Mermaid Kick" },
  { index: 0x03, name: "Glide" },
  { index: 0x04, name: "Superglide" },
  { index: 0x05, name: "Treasure Magnet" },
  { index: 0x06, name: "Combo Plus" },
  { index: 0x07, name: "Air Combo Plus" },
  { index: 0x08, name: "Critical Plus" },
  { index: 0x09, name: "Second Wind" },
  { index: 0x0a, name: "Scan" },
  { index: 0x0b, name: "Sonic Blade" },
  { index: 0x0c, name: "Ars Arcanum" },
  { index: 0x0d, name: "Strike Raid" },
  { index: 0x0e, name: "Ragnarok" },
  { index: 0x0f, name: "Trinity Limit" },
  { index: 0x10, name: "Cheer" },
  { index: 0x11, name: "Vortex" },
  { index: 0x12, name: "Aerial Sweep" },
  { index: 0x13, name: "Counterattack" },
  { index: 0x14, name: "Blitz" },
  { index: 0x15, name: "Guard" },
  { index: 0x16, name: "Dodge Roll" },
  { index: 0x17, name: "MP Haste" },
  { index: 0x18, name: "MP Rage" },
  { index: 0x19, name: "Second Chance" },
  { index: 0x1a, name: "Berserk" },
  { index: 0x1b, name: "Jackpot" },
  { index: 0x1c, name: "Lucky Strike" },
  { index: 0x1d, name: "Charge" },
  { index: 0x1e, name: "Rocket" },
  { index: 0x1f, name: "Tornado" },
  { index: 0x20, name: "MP Gift" },
  { index: 0x21, name: "Raging Boar" },
  { index: 0x22, name: "Asp’s Bite" },
  { index: 0x23, name: "Healing Herb" },
  { index: 0x24, name: "Wind Armor" },
  { index: 0x25, name: "Crescent" },
  { index: 0x26, name: "Sandstorm" },
  { index: 0x27, name: "Applause!" },
  { index: 0x28, name: "Blazing Fury" },
  { index: 0x29, name: "Icy Terror" },
  { index: 0x2a, name: "Bolts of Sorrow" },
  { index: 0x2b, name: "Ghostly Scream" },
  { index: 0x2c, name: "Hummingbird" },
  { index: 0x2d, name: "Time-Out" },
  { index: 0x2e, name: "Storm’s Eye" },
  { index: 0x2f, name: "Ferocious Lunge" },
  { index: 0x30, name: "Furious Bellow" },
  { index: 0x31, name: "Spiral Wave" },
  { index: 0x32, name: "Thunder Potion" },
  { index: 0x33, name: "Cure Potion" },
  { index: 0x34, name: "Aero Potion" },
  { index: 0x35, name: "Slapshot"       , finalMix: true },
  { index: 0x36, name: "Sliding Dash"   , finalMix: true },
  { index: 0x37, name: "Hurricane Blast", finalMix: true },
  { index: 0x38, name: "Ripple Drive"   , finalMix: true },
  { index: 0x39, name: "Stun Impact"    , finalMix: true },
  { index: 0x3a, name: "Gravity Break"  , finalMix: true },
  { index: 0x3b, name: "Zantetsuken"    , finalMix: true },
  { index: 0x3c, name: "Tech Boost"     , finalMix: true },
  { index: 0x3d, name: "Encounter Plus" , finalMix: true },
  { index: 0x3e, name: "Leaf Bracer"    , finalMix: true },
  { index: 0x3f, name: "Evolution"      , finalMix: true },
  { index: 0x40, name: "EXP Zero"       , hd15Remix: true },
  { index: 0x41, name: "Combo Master"   , hd15Remix: true },
];

export const itemTypes = [
  {
    index: 0x0,
    name: "Recovery Items",
    subtypes: ["", ""],
  },
  {
    index: 0x10,
    name: "Boosting Items",
    subtypes: [""],
  },
  {
    index: 0x20,
    name: "Rare Enemy Drop Items",
    subtypes: [""],
  },
  {
    index: 0x30,
    name: "Synthesis Items",
    subtypes: [""],
  },
  {
    index: 0x40,
    name: "Key Items",
    subtypes: ["Ansem Reports", "Miscellaneous"],
  },
  {
    index: 0x50,
    name: "Weapons",
    subtypes: ["Sora", "Donald", "Goofy", "Miscellaneous"],
  },
  {
    index: 0x60,
    name: "Accessories",
    subtypes: [""],
  },
];

// prettier-ignore
export const inventory = [
  { index: 0x01, type: 0x00, order:   0, name: "Potion" },
  { index: 0x02, type: 0x00, order:   1, name: "Hi-Potion" },
  { index: 0x03, type: 0x00, order:   2, name: "Ether" },
  { index: 0x04, type: 0x00, order:   3, name: "Elixir" },
  // { index: 0x05, type: 0x00, order:   4, name: "???" }, // Unused
  { index: 0x06, type: 0x00, order:   5, name: "Mega-Potion" },
  { index: 0x07, type: 0x00, order:   6, name: "Mega-Ether" },
  { index: 0x08, type: 0x00, order:   7, name: "Megalixir" },
  { index: 0x09, type: 0x30, order:  33, name: "Fury Stone"      , finalMix: true },
  { index: 0x0a, type: 0x30, order:  36, name: "Power Stone"     , finalMix: true },
  { index: 0x0b, type: 0x30, order:  38, name: "Energy Stone"    , finalMix: true },
  { index: 0x0c, type: 0x30, order:  41, name: "Blazing Stone"   , finalMix: true },
  { index: 0x0d, type: 0x30, order:  44, name: "Frost Stone"     , finalMix: true },
  { index: 0x0e, type: 0x30, order:  47, name: "Lightning Stone" , finalMix: true },
  { index: 0x0f, type: 0x30, order:  49, name: "Dazzling Stone"  , finalMix: true },
  { index: 0x10, type: 0x30, order:  56, name: "Stormy Stone"    , finalMix: true },
  { index: 0x11, type: 0x60, order: 191, name: "Protect Chain" },
  { index: 0x12, type: 0x60, order: 192, name: "Protera Chain" },
  { index: 0x13, type: 0x60, order: 193, name: "Protega Chain" },
  { index: 0x14, type: 0x60, order: 194, name: "Fire Ring" },
  { index: 0x15, type: 0x60, order: 195, name: "Fira Ring" },
  { index: 0x16, type: 0x60, order: 196, name: "Firaga Ring" },
  { index: 0x17, type: 0x60, order: 198, name: "Blizzard Ring" },
  { index: 0x18, type: 0x60, order: 199, name: "Blizzara Ring" },
  { index: 0x19, type: 0x60, order: 200, name: "Blizzaga Ring" },
  { index: 0x1a, type: 0x60, order: 202, name: "Thunder Ring" },
  { index: 0x1b, type: 0x60, order: 203, name: "Thundara Ring" },
  { index: 0x1c, type: 0x60, order: 204, name: "Thundaga Ring" },
  { index: 0x1d, type: 0x60, order: 211, name: "Ability Stud" },
  { index: 0x1e, type: 0x60, order: 212, name: "Guard Earring" },
  { index: 0x1f, type: 0x60, order: 213, name: "Master Earring" },
  { index: 0x20, type: 0x60, order: 206, name: "Chaos Ring" },
  { index: 0x21, type: 0x60, order: 207, name: "Dark Ring" },
  { index: 0x22, type: 0x60, order: 208, name: "Element Ring" },
  { index: 0x23, type: 0x60, order: 209, name: "Three Stars" },
  { index: 0x24, type: 0x60, order: 214, name: "Power Chain" },
  { index: 0x25, type: 0x60, order: 215, name: "Golem Chain" },
  { index: 0x26, type: 0x60, order: 216, name: "Titan Chain" },
  { index: 0x27, type: 0x60, order: 217, name: "Energy Bangle" },
  { index: 0x28, type: 0x60, order: 218, name: "Angel Bangle" },
  { index: 0x29, type: 0x60, order: 219, name: "Gaia Bangle" },
  { index: 0x2a, type: 0x60, order: 220, name: "Magic Armlet" },
  { index: 0x2b, type: 0x60, order: 221, name: "Rune Armlet" },
  { index: 0x2c, type: 0x60, order: 222, name: "Atlas Armlet" },
  { index: 0x2d, type: 0x60, order: 233, name: "Heartguard" },
  { index: 0x2e, type: 0x60, order: 234, name: "Ribbon" },
  { index: 0x2f, type: 0x60, order: 235, name: "Crystal Crown" },
  { index: 0x30, type: 0x60, order: 225, name: "Brave Warrior" },
  { index: 0x31, type: 0x60, order: 226, name: "Ifrit's Horn" },
  { index: 0x32, type: 0x60, order: 227, name: "Inferno Band" },
  { index: 0x33, type: 0x60, order: 228, name: "White Fang" },
  { index: 0x34, type: 0x60, order: 229, name: "Ray of Light" },
  { index: 0x35, type: 0x60, order: 230, name: "Holy Circlet" },
  { index: 0x36, type: 0x60, order: 231, name: "Raven's Claw" },
  { index: 0x37, type: 0x60, order: 232, name: "Omega Arts" },
  { index: 0x38, type: 0x60, order: 241, name: "EXP Earring"     , finalMix: true },
  // { index: 0x39, type: 0x60, order: 245, name: "???" }, // Unused
  { index: 0x3a, type: 0x60, order: 242, name: "EXP Ring"        , finalMix: true },
  { index: 0x3b, type: 0x60, order: 243, name: "EXP Bracelet"    , finalMix: true },
  { index: 0x3c, type: 0x60, order: 244, name: "EXP Necklace"    , finalMix: true },
  { index: 0x3d, type: 0x60, order: 197, name: "Firagun Band"    , finalMix: true },
  { index: 0x3e, type: 0x60, order: 201, name: "Blizzagun Band"  , finalMix: true },
  { index: 0x3f, type: 0x60, order: 205, name: "Thundagun Band"  , finalMix: true },
  { index: 0x40, type: 0x60, order: 238, name: "Ifrit Belt"      , finalMix: true },
  { index: 0x41, type: 0x60, order: 239, name: "Shiva Belt"      , finalMix: true },
  { index: 0x42, type: 0x60, order: 240, name: "Ramuh Belt"      , finalMix: true },
  { index: 0x43, type: 0x60, order: 223, name: "Moogle Badge"    , finalMix: true },
  { index: 0x44, type: 0x60, order: 224, name: "Cosmic Arts"     , finalMix: true },
  { index: 0x45, type: 0x60, order: 236, name: "Royal Crown"     , finalMix: true },
  { index: 0x46, type: 0x60, order: 237, name: "Prime Cap"       , finalMix: true },
  { index: 0x47, type: 0x60, order: 210, name: "Obsidian Ring"   , finalMix: true },
  // { index: 0x48, type: 0x60, order: 246, name: "???" }, // Unused
  // { index: 0x49, type: 0x60, order: 247, name: "???" }, // Unused
  // { index: 0x4a, type: 0x60, order: 248, name: "???" }, // Unused
  // { index: 0x4b, type: 0x60, order: 249, name: "???" }, // Unused
  // { index: 0x4c, type: 0x60, order: 250, name: "???" }, // Unused
  // { index: 0x4d, type: 0x60, order: 251, name: "???" }, // Unused
  // { index: 0x4e, type: 0x60, order: 252, name: "???" }, // Unused
  // { index: 0x4f, type: 0x60, order: 253, name: "???" }, // Unused
  // { index: 0x50, type: 0x60, order: 254, name: "???" }, // Unused
  { index: 0x51, type: 0x50, order: 130, name: "Kingdom Key" },
  { index: 0x52, type: 0x50, order: 131, name: "Dream Sword" },
  { index: 0x53, type: 0x50, order: 132, name: "Dream Shield" },
  { index: 0x54, type: 0x50, order: 133, name: "Dream Rod" },
  { index: 0x55, type: 0x50, order: 134, name: "Wooden Sword" },
  { index: 0x56, type: 0x50, order: 135, name: "Jungle King" },
  { index: 0x57, type: 0x50, order: 136, name: "Three Wishes" },
  { index: 0x58, type: 0x50, order: 139, name: "Fairy Harp" },
  { index: 0x59, type: 0x50, order: 138, name: "Pumpkinhead" },
  { index: 0x5a, type: 0x50, order: 137, name: "Crabclaw" },
  { index: 0x5b, type: 0x50, order: 146, name: "Divine Rose" },
  { index: 0x5c, type: 0x50, order: 141, name: "Spellbinder" },
  { index: 0x5d, type: 0x50, order: 143, name: "Olympia" },
  { index: 0x5e, type: 0x50, order: 144, name: "Lionheart" },
  { index: 0x5f, type: 0x50, order: 142, name: "Metal Chocobo" },
  { index: 0x60, type: 0x50, order: 147, name: "Oathkeeper" },
  { index: 0x61, type: 0x50, order: 148, name: "Oblivion" },
  { index: 0x62, type: 0x50, order: 145, name: "Lady Luck" },
  { index: 0x63, type: 0x50, order: 140, name: "Wishing Star" },
  { index: 0x64, type: 0x50, order: 151, name: "Ultima Weapon" },
  { index: 0x65, type: 0x50, order: 149, name: "Diamond Dust"    , finalMix: true },
  { index: 0x66, type: 0x50, order: 150, name: "One-Winged Angel", finalMix: true },
  { index: 0x67, type: 0x51, order: 152, name: "Mage's Staff" },
  { index: 0x68, type: 0x51, order: 153, name: "Morning Star" },
  { index: 0x69, type: 0x51, order: 154, name: "Shooting Star" },
  { index: 0x6a, type: 0x51, order: 155, name: "Magus Staff" },
  { index: 0x6b, type: 0x51, order: 156, name: "Wisdom Staff" },
  { index: 0x6c, type: 0x51, order: 157, name: "Warhammer" },
  { index: 0x6d, type: 0x51, order: 158, name: "Silver Mallet" },
  { index: 0x6e, type: 0x51, order: 159, name: "Grand Mallet" },
  { index: 0x6f, type: 0x51, order: 160, name: "Lord Fortune" },
  { index: 0x70, type: 0x51, order: 161, name: "Violetta" },
  { index: 0x71, type: 0x51, order: 163, name: "Dream Rod" },
  { index: 0x72, type: 0x51, order: 166, name: "Save the Queen" },
  { index: 0x73, type: 0x51, order: 162, name: "Wizard’s Relic" },
  { index: 0x74, type: 0x51, order: 164, name: "Meteor Strike"   , finalMix: true },
  { index: 0x75, type: 0x51, order: 165, name: "Fantasista"      , finalMix: true },
  // { index: 0x76, type: 0x51, order: 167, name: "???" }, // Unused
  { index: 0x77, type: 0x52, order: 168, name: "Knight’s Shield" },
  { index: 0x78, type: 0x52, order: 169, name: "Mythril Shield" },
  { index: 0x79, type: 0x52, order: 170, name: "Onyx Shield" },
  { index: 0x7a, type: 0x52, order: 173, name: "Stout Shield" },
  { index: 0x7b, type: 0x52, order: 174, name: "Golem Shield" },
  { index: 0x7c, type: 0x52, order: 175, name: "Adamant Shield" },
  { index: 0x7d, type: 0x52, order: 171, name: "Smasher" },
  { index: 0x7e, type: 0x52, order: 172, name: "Gigas Fist" },
  { index: 0x7f, type: 0x52, order: 177, name: "Genji Shield" },
  { index: 0x80, type: 0x52, order: 176, name: "Herc’s Shield" },
  { index: 0x81, type: 0x52, order: 179, name: "Dream Shield" },
  { index: 0x82, type: 0x52, order: 182, name: "Save the King" },
  { index: 0x83, type: 0x52, order: 178, name: "Defender" },
  { index: 0x84, type: 0x52, order: 180, name: "Mighty Shield"   , finalMix: true },
  { index: 0x85, type: 0x52, order: 181, name: "Seven Elements"  , finalMix: true },
  // { index: 0x86, type: 0x52, order: 183, name: "???" }, // Unused
  { index: 0x87, type: 0x53, order: 184, name: "Spear (Tarzan)" },
  { index: 0x88, type: 0x53, order: 185, name: "No Weapon (Pooh)" },
  { index: 0x89, type: 0x53, order: 186, name: "Sword (Aladdin)" },
  { index: 0x8a, type: 0x53, order: 187, name: "No Weapon (Ariel)" },
  { index: 0x8b, type: 0x53, order: 188, name: "No Weapon (Jack)" },
  { index: 0x8c, type: 0x53, order: 189, name: "Dagger (Peter Pan)" },
  { index: 0x8d, type: 0x53, order: 190, name: "Claws (Beast)" },
  { index: 0x8e, type: 0x01, order:   8, name: "Tent" },
  { index: 0x8f, type: 0x01, order:   9, name: "Camping Set" },
  { index: 0x90, type: 0x01, order:  10, name: "Cottage" },
  // { index: 0x91, type: 0x01, order:  11, name: "???" }, // Unused
  // { index: 0x92, type: 0x01, order:  12, name: "???" }, // Unused
  // { index: 0x93, type: 0x01, order:  13, name: "???" }, // Unused
  // { index: 0x94, type: 0x01, order:  14, name: "???" }, // Unused
  { index: 0x95, type: 0x40, order:  72, name: "Ansem Report 11" , finalMix: true },
  { index: 0x96, type: 0x40, order:  73, name: "Ansem Report 12" , finalMix: true },
  { index: 0x97, type: 0x40, order:  74, name: "Ansem Report 13" , finalMix: true },
  { index: 0x98, type: 0x10, order:  15, name: "Power Up" },
  { index: 0x99, type: 0x10, order:  16, name: "Defense Up" },
  { index: 0x9a, type: 0x10, order:  17, name: "AP Up" },
  { index: 0x9b, type: 0x30, order:  54, name: "Serenity Power"  , finalMix: true },
  { index: 0x9c, type: 0x30, order:  61, name: "Dark Matter"     , finalMix: true },
  { index: 0x9d, type: 0x30, order:  59, name: "Mythril Stone"   , finalMix: true },
  { index: 0x9e, type: 0x20, order:  18, name: "Fire Arts" },
  { index: 0x9f, type: 0x20, order:  19, name: "Blizzard Arts" },
  { index: 0xa0, type: 0x20, order:  20, name: "Thunder Arts" },
  { index: 0xa1, type: 0x20, order:  21, name: "Cure Arts" },
  { index: 0xa2, type: 0x20, order:  22, name: "Gravity Arts" },
  { index: 0xa3, type: 0x20, order:  23, name: "Stop Arts" },
  { index: 0xa4, type: 0x20, order:  24, name: "Aero Arts" },
  { index: 0xa5, type: 0x20, order:  25, name: "Shiitake Rank" },
  { index: 0xa6, type: 0x20, order:  26, name: "Matsutake Rank" },
  { index: 0xa7, type: 0x20, order:  27, name: "Mystery Mold" },
  { index: 0xa8, type: 0x40, order:  62, name: "Ansem Report 1" },
  { index: 0xa9, type: 0x40, order:  63, name: "Ansem Report 2" },
  { index: 0xaa, type: 0x40, order:  64, name: "Ansem Report 3" },
  { index: 0xab, type: 0x40, order:  65, name: "Ansem Report 4" },
  { index: 0xac, type: 0x40, order:  66, name: "Ansem Report 5" },
  { index: 0xad, type: 0x40, order:  67, name: "Ansem Report 6" },
  { index: 0xae, type: 0x40, order:  68, name: "Ansem Report 7" },
  { index: 0xaf, type: 0x40, order:  69, name: "Ansem Report 8" },
  { index: 0xb0, type: 0x40, order:  70, name: "Ansem Report 9" },
  { index: 0xb1, type: 0x40, order:  71, name: "Ansem Report 10" },
  { index: 0xb2, type: 0x41, order:  95, name: "Khama vol. 8" },
  { index: 0xb3, type: 0x41, order:  96, name: "Salegg vol. 6" },
  { index: 0xb4, type: 0x41, order:  97, name: "Azal vol. 3" },
  { index: 0xb5, type: 0x41, order:  98, name: "Mava vol. 3" },
  { index: 0xb6, type: 0x41, order:  99, name: "Mava vol. 6" },
  { index: 0xb7, type: 0x41, order: 100, name: "Theon vol. 6" },
  { index: 0xb8, type: 0x41, order: 101, name: "Nahara vol. 5" },
  { index: 0xb9, type: 0x41, order: 102, name: "Hafet vol. 4" },
  { index: 0xba, type: 0x41, order:  86, name: "Empty Bottle" },
  { index: 0xbb, type: 0x41, order:  85, name: "Old Book" },
  { index: 0xbc, type: 0x41, order: 103, name: "Emblem Piece" },
  { index: 0xbd, type: 0x41, order: 104, name: "Emblem Piece" },
  { index: 0xbe, type: 0x41, order: 105, name: "Emblem Piece" },
  { index: 0xbf, type: 0x41, order: 106, name: "Emblem Piece" },
  { index: 0xc0, type: 0x41, order:  87, name: "Log" },
  { index: 0xc1, type: 0x41, order:  88, name: "Cloth" },
  { index: 0xc2, type: 0x41, order:  89, name: "Rope" },
  { index: 0xc3, type: 0x41, order:  90, name: "Seagull Egg" },
  { index: 0xc4, type: 0x41, order:  91, name: "Fish" },
  { index: 0xc5, type: 0x41, order:  92, name: "Mushroom" },
  { index: 0xc6, type: 0x41, order:  93, name: "Coconut" },
  { index: 0xc7, type: 0x41, order:  94, name: "Drinking Water" },
  { index: 0xc8, type: 0x41, order:  79, name: "Navi-G Piece" },
  { index: 0xc9, type: 0x41, order:  80, name: "Navi-G Piece" },
  { index: 0xca, type: 0x41, order:  81, name: "Navi-Gummi" },
  { index: 0xcb, type: 0x41, order:  82, name: "Navi-G Piece" },
  { index: 0xcc, type: 0x41, order:  83, name: "Navi-G Piece" },
  { index: 0xcd, type: 0x41, order:  84, name: "Navi-G Gummi" },
  { index: 0xce, type: 0x41, order:  75, name: "Watergleam" },
  { index: 0xcf, type: 0x41, order:  76, name: "Naturespark" },
  { index: 0xd0, type: 0x41, order:  77, name: "Fireglow" },
  { index: 0xd1, type: 0x41, order:  78, name: "Earthshine" },
  { index: 0xd2, type: 0x41, order: 107, name: "Crystal Trident" },
  { index: 0xd3, type: 0x41, order: 108, name: "Postcard" },
  { index: 0xd4, type: 0x41, order: 109, name: "Torn Page" },
  { index: 0xd5, type: 0x41, order: 110, name: "Torn Page" },
  { index: 0xd6, type: 0x41, order: 111, name: "Torn Page" },
  { index: 0xd7, type: 0x41, order: 112, name: "Torn Page" },
  { index: 0xd8, type: 0x41, order: 113, name: "Torn Page" },
  { index: 0xd9, type: 0x41, order: 114, name: "Slide 1" },
  { index: 0xda, type: 0x41, order: 115, name: "Slide 2" },
  { index: 0xdb, type: 0x41, order: 116, name: "Slide 3" },
  { index: 0xdc, type: 0x41, order: 117, name: "Slide 4" },
  { index: 0xdd, type: 0x41, order: 118, name: "Slide 5" },
  { index: 0xde, type: 0x41, order: 119, name: "Slide 6" },
  { index: 0xdf, type: 0x41, order: 120, name: "Footprints" },
  { index: 0xe0, type: 0x41, order: 121, name: "Claw Marks" },
  { index: 0xe1, type: 0x41, order: 122, name: "Stench" },
  { index: 0xe2, type: 0x41, order: 123, name: "Antenna" },
  { index: 0xe3, type: 0x41, order: 124, name: "Forget-Me-Not" },
  { index: 0xe4, type: 0x41, order: 125, name: "Jack-in-the-Box" },
  { index: 0xe5, type: 0x41, order: 126, name: "Entry Pass" },
  { index: 0xe6, type: 0x41, order: 127, name: "Hero License" },
  { index: 0xe7, type: 0x41, order: 128, name: "Pretty Stone" },
  // { index: 0xe8, type: 0x41, order: 129, name: "???" }, // Unused
  { index: 0xe9, type: 0x30, order:  28, name: "Lucid Shard" },
  { index: 0xea, type: 0x30, order:  29, name: "Lucid Gem" },
  { index: 0xeb, type: 0x30, order:  30, name: "Lucid Crystal" },
  { index: 0xec, type: 0x30, order:  31, name: "Spirit Shard" },
  { index: 0xed, type: 0x30, order:  32, name: "Spirit Gem" },
  { index: 0xee, type: 0x30, order:  34, name: "Power Shard" },
  { index: 0xef, type: 0x30, order:  35, name: "Power Gem" },
  { index: 0xf0, type: 0x30, order:  37, name: "Power Crystal" },
  { index: 0xf1, type: 0x30, order:  39, name: "Blaze Shard" },
  { index: 0xf2, type: 0x30, order:  40, name: "Blaze Gem" },
  { index: 0xf3, type: 0x30, order:  42, name: "Frost Shard" },
  { index: 0xf4, type: 0x30, order:  43, name: "Frost Gem" },
  { index: 0xf5, type: 0x30, order:  45, name: "Thunder Shard" },
  { index: 0xf6, type: 0x30, order:  46, name: "Thunder Gem" },
  { index: 0xf7, type: 0x30, order:  48, name: "Shiny Crystal" },
  { index: 0xf8, type: 0x30, order:  50, name: "Bright Shard" },
  { index: 0xf9, type: 0x30, order:  51, name: "Bright Gem" },
  { index: 0xfa, type: 0x30, order:  52, name: "Bright Crystal" },
  { index: 0xfb, type: 0x30, order:  53, name: "Mystery Goo" },
  { index: 0xfc, type: 0x30, order:  55, name: "Gale" },
  { index: 0xfd, type: 0x30, order:  57, name: "Mythril Shard" },
  { index: 0xfe, type: 0x30, order:  58, name: "Mythril" },
  { index: 0xff, type: 0x30, order:  60, name: "Orichalcum" },
];

export const accessoriesOrder: number[] = [0x0];
export const itemsOrder: number[] = [0x0];
export const weaponsOrder: number[] = [0x0];

inventory
  .sort((a, b) => a.order - b.order)
  .forEach((item) => {
    switch (item.type >> 0x4) {
      case 0x0:
        itemsOrder.push(item.index);
      case 0x5:
        weaponsOrder.push(item.index);
      case 0x6:
        accessoriesOrder.push(item.index);
    }
  });

// prettier-ignore
export const heartlessList = [
  { index: 0x002, name: "Shadow" },
  { index: 0x054, name: "Gigas Shadow"              , finalMix: true },
  { index: 0x000, name: "Soldier" },
  { index: 0x052, name: "Stealth Soldier"           , finalMix: true },
  { index: 0x008, name: "Large Body" },
  { index: 0x014, name: "Red Nocturne" },
  { index: 0x016, name: "Blue Rhapsody" },
  { index: 0x018, name: "Yellow Opera" },
  { index: 0x01a, name: "Green Requiem" },
  { index: 0x058, name: "Black Ballade"             , finalMix: true },
  { index: 0x004, name: "Powerwild" },
  { index: 0x006, name: "Bouncywild" },
  { index: 0x056, name: "Sniperwild"                , finalMix: true },
  { index: 0x01e, name: "Air Soldier" },
  { index: 0x010, name: "Bandit" },
  { index: 0x00a, name: "Fat Bandit" },
  { index: 0x020, name: "Pot Spider" },
  { index: 0x022, name: "Barrel Spider" },
  { index: 0x024, name: "Pot Scorpion"              , finalMix: true },
  { index: 0x02c, name: "Search Ghost" },
  { index: 0x05e, name: "Grand Ghost"               , finalMix: true },
  { index: 0x00c, name: "Sea Neon" },
  { index: 0x00e, name: "Sheltering Zone" },
  { index: 0x030, name: "Screwdiver" },
  { index: 0x02e, name: "Aquatank" },
  { index: 0x026, name: "Wight Knight" },
  { index: 0x02a, name: "Gargoyle" },
  { index: 0x032, name: "Chimera"                   , finalMix: true },
  { index: 0x012, name: "Pirate" },
  { index: 0x028, name: "Air Pirate" },
  { index: 0x034, name: "Battleship" },
  { index: 0x05a, name: "Jet Balloon"               , finalMix: true },
  { index: 0x036, name: "Darkball" },
  { index: 0x040, name: "Defender" },
  { index: 0x03c, name: "Wyvern" },
  { index: 0x01c, name: "Wizard" },
  { index: 0x03a, name: "Behemoth" },
  { index: 0x060, name: "Destroyed Behemoth"        , finalMix: true },
  { index: 0x062, name: "Arch Behemoth"             , finalMix: true },
  { index: 0x038, name: "Invisible" },
  { index: 0x03e, name: "Angel Star" },
  { index: 0x050, name: "Neoshadow"                 , finalMix: true },
  { index: 0x042, name: "White Mushroom" },
  { index: 0x044, name: "Black Fungus" },
  { index: 0x046, name: "Rare Truffle" },
  { index: 0x04e, name: "Pink Agaricus"             , finalMix: true },
  { index: 0xf1e, name: "Darkside"          , bit: 2 },
  { index: 0xf1e, name: "Guard Armor"       , bit: 1 },
  { index: 0xf21, name: "Red Armor"         , bit: 1, finalMix: true },
  { index: 0xf1e, name: "Opposite Armor"    , bit: 0 },
  { index: 0xf1f, name: "Trickmaster"       , bit: 7 },
  { index: 0xf1f, name: "Stealth Sneak"     , bit: 6 },
  { index: 0x064, name: "Sneak Army"                , finalMix: true },
  { index: 0xf1f, name: "Pot Centipede"     , bit: 5 },
  { index: 0xf1f, name: "Parasite Cage"     , bit: 4 },
  { index: 0xf20, name: "Kurt Zisa"         , bit: 7, japanExclude: true },
  { index: 0xf1f, name: "Phantom"           , bit: 3 },
];
