export const enemies = [
  { index: 0x0, name: "01 Bat", drops: [true, false] },
  { index: 0x1, name: "02 Tiny Slime", drops: [true, false] },
  { index: 0x2, name: "03 Slime", drops: [true, true] },
  { index: 0x3, name: "04 Medusa Head", drops: [false, true] },
  { index: 0x4, name: "05 Zombie", drops: [false, true] },
  { index: 0x5, name: "06 Skeleton", drops: [true, true] },
  { index: 0x6, name: "07 Fleaman", drops: [true, true] },
  { index: 0x7, name: "08 Bone Soldier", drops: [true, true] },
  { index: 0x8, name: "09 Armor Knight", drops: [true, true] },
  { index: 0x9, name: "10 Giant Bat", drops: [false, false] },
  { index: 0xa, name: "11 Ghost", drops: [false, false] },
  { index: 0xb, name: "12 Bone Pillar", drops: [true, true] },
  { index: 0xc, name: "13 Large Ghost", drops: [true, true] },
  { index: 0xd, name: "14 White Dragon", drops: [true, true] },
  { index: 0xe, name: "15 Rock Armor", drops: [true, true] },
  { index: 0xf, name: "16 White Dragon Lv2", drops: [true, true] },
  { index: 0x10, name: "17 Lizard Man", drops: [true, true] },
  { index: 0x11, name: "18 Living Armor", drops: [false, false] },
  { index: 0x12, name: "19 Ectoplasm", drops: [true, true] },
  { index: 0x13, name: "20 Skeleton Blaze", drops: [true, true] },
  { index: 0x14, name: "21 Big Skeleton", drops: [true, true] },
  { index: 0x15, name: "22 Flying Bone", drops: [true, true] },
  { index: 0x16, name: "23 Peeping Eye", drops: [true, true] },
  { index: 0x17, name: "24 Skeleton Flail", drops: [true, true] },
  { index: 0x18, name: "25 Skeleton Spear", drops: [true, true] },
  { index: 0x19, name: "26 Red Skeleton", drops: [false, false] },
  { index: 0x1a, name: "27 Skeleton Rib", drops: [true, true] },
  { index: 0x1b, name: "28 Bone Thrower", drops: [true, true] },
  { index: 0x1c, name: "29 Skeleton Ape", drops: [true, true] },
  { index: 0x1d, name: "30 Gate Guarder", drops: [false, false] },
  { index: 0x1e, name: "31 Golem", drops: [false, false] },
  { index: 0x1f, name: "32 Skull Knight", drops: [false, false] },
  { index: 0x20, name: "33 Tiny Devil", drops: [true, true] },
  { index: 0x21, name: "34 Scarecrow", drops: [true, true] },
  { index: 0x22, name: "35 Skeleton Spider", drops: [true, true] },
  { index: 0x23, name: "36 Man-eater", drops: [true, true] },
  { index: 0x24, name: "37 Axe Armor", drops: [true, true] },
  { index: 0x25, name: "38 Witch", drops: [true, true] },
  { index: 0x26, name: "39 Siren", drops: [false, true] },
  { index: 0x27, name: "40 Bomber Armor", drops: [true, true] },
  { index: 0x28, name: "41 Minotaur", drops: [false, false] },
  { index: 0x29, name: "42 Balloon", drops: [true, true] },
  { index: 0x2a, name: "43 Big Balloon", drops: [true, true] },
  { index: 0x2b, name: "44 Bone Archer", drops: [true, true] },
  { index: 0x2c, name: "45 Ruler Sword", drops: [true, true] },
  { index: 0x2d, name: "46 Disc Armor", drops: [true, true] },
  { index: 0x2e, name: "47 Devil", drops: [false, false] },
  { index: 0x2f, name: "48 Merman", drops: [true, true] },
  { index: 0x30, name: "49 Fishman", drops: [true, true] },
  { index: 0x31, name: "50 Arabaki", drops: [true, true] },
  { index: 0x32, name: "51 Ruler Sword Lv2", drops: [true, true] },
  { index: 0x33, name: "52 Feather Demon", drops: [true, true] },
  { index: 0x34, name: "53 Guardian Armor", drops: [false, false] },
  { index: 0x35, name: "54 Boomerang Armor", drops: [false, false] },
  { index: 0x36, name: "55 Giant Merman", drops: [false, false] },
  { index: 0x37, name: "56 Max Slimer", drops: [false, false] },
  { index: 0x38, name: "57 Fleaman Armor", drops: [true, true] },
  { index: 0x39, name: "58 Gold Medusa", drops: [false, true] },
  { index: 0x3a, name: "59 Mimic", drops: [true, true] },
  { index: 0x3b, name: "60 White Dragon Lv3", drops: [true, true] },
  { index: 0x3c, name: "61 Skeleton Mirror", drops: [true, true] },
  { index: 0x3d, name: "62 0", drops: [true, true] },
  { index: 0x3e, name: "63 Harpy", drops: [true, true] },
  { index: 0x3f, name: "64 Axe Armor Lv2", drops: [true, true] },
  { index: 0x40, name: "65 Specter", drops: [true, true] },
  { index: 0x41, name: "66 Bronze Guarder", drops: [false, false] },
  { index: 0x42, name: "67 Peeping Big", drops: [false, false] },
  { index: 0x43, name: "68 Legion (saint)", drops: [false, false] },
  { index: 0x44, name: "69 Shadow", drops: [false, false] },
  { index: 0x45, name: "70 Melty Zombie", drops: [true, true] },
  { index: 0x46, name: "71 Bone Liquid", drops: [true, true] },
  { index: 0x47, name: "72 Ruler Sword Lv3", drops: [true, true] },
  { index: 0x48, name: "73 Poison Lizard", drops: [true, true] },
  { index: 0x49, name: "74 Pazuzu", drops: [false, false] },
  { index: 0x4a, name: "75 Spriggan", drops: [true, true] },
  { index: 0x4b, name: "76 Gorgon", drops: [true, true] },
  { index: 0x4c, name: "77 Blaze Master", drops: [true, true] },
  { index: 0x4d, name: "78 Arthro Skeleton", drops: [true, true] },
  { index: 0x4e, name: "79 Rare Ghost", drops: [true, true] },
  { index: 0x4f, name: "80 Skeleton Glass", drops: [true, true] },
  { index: 0x50, name: "81 Victory Armor", drops: [true, true] },
  { index: 0x51, name: "82 Hammer-Hammer", drops: [true, true] },
  { index: 0x52, name: "83 Disc Armor Lv2", drops: [true, true] },
  { index: 0x53, name: "84 Minotaur Lv2", drops: [false, false] },
  { index: 0x54, name: "85 Legion (corpse)", drops: [false, false] },
  { index: 0x55, name: "86 Talos", drops: [false, false] },
  { index: 0x56, name: "87 Death", drops: [false, false] },
  { index: 0x57, name: "88 Death", drops: [false, false] },
  { index: 0x58, name: "89 Pixie", drops: [true, true] },
  { index: 0x59, name: "90 Sylph", drops: [true, true] },
  { index: 0x5a, name: "91 Master Lizard", drops: [true, true] },
  { index: 0x5b, name: "92 Owl", drops: [true, true] },
  { index: 0x5c, name: "93 Clear Bone", drops: [true, true] },
  { index: 0x5d, name: "94 Jp Bonepillar", drops: [true, true] },
  { index: 0x5e, name: "95 Simon Wraith", drops: [true, true] },
  { index: 0x5f, name: "96 Pike Master", drops: [true, true] },
  { index: 0x60, name: "97 Cyclops", drops: [false, false] },
  { index: 0x61, name: "98 Maxim", drops: [false, false] },
  { index: 0x62, name: "99 Dracula Wraith", drops: [false, false] },
  { index: 0x63, name: "100 Dracula Wraith", drops: [false, false] },
];
