import type { Resource, ResourceGroups } from "$lib/types";

export const characters = [
  { index: 0x00, name: "Max" },
  { index: 0x01, name: "Mae" },
  { index: 0x02, name: "Pelle" },
  { index: 0x03, name: "Ken" },
  { index: 0x04, name: "Vankar" },
  { index: 0x05, name: "Earnest" },
  { index: 0x06, name: "Arthur" },
  { index: 0x07, name: "Gort" },
  { index: 0x08, name: "Luke" },
  { index: 0x09, name: "Guntz" },
  { index: 0x0a, name: "Anri" },
  { index: 0x0b, name: "Alef" },
  { index: 0x0c, name: "Tao" },
  { index: 0x0d, name: "Domingo" },
  { index: 0x0e, name: "Lowe" },
  { index: 0x0f, name: "Khris" },
  { index: 0x10, name: "Torasu" },
  { index: 0x11, name: "Gong" },
  { index: 0x12, name: "Diane" },
  { index: 0x13, name: "Hans" },
  { index: 0x14, name: "Lyle" },
  { index: 0x15, name: "Amon" },
  { index: 0x16, name: "Balbaroy" },
  { index: 0x17, name: "Kokichi" },
  { index: 0x18, name: "Bleu" },
  { index: 0x19, name: "Adam" },
  { index: 0x1a, name: "Zylo" },
  { index: 0x1b, name: "Musashi" },
  { index: 0x1c, name: "Hanzou" },
  { index: 0x1d, name: "Jogurt" },
];

const itemTypes = [
  { index: 0x0, name: "Recovery Items" },
  { index: 0x1, name: "Booster Items" },
  { index: 0x2, name: "Key Items" },
  { index: 0x3, name: "Swords" },
  { index: 0x4, name: "Lances" },
  { index: 0x5, name: "Axes" },
  { index: 0x6, name: "Staves" },
  { index: 0x7, name: "Arrows" },
  { index: 0x8, name: "Rings" },
  { index: 0x9, name: "Miscellaneous" },
];

export const itemList = [
  { index: 0x00, type: 0x0, name: "Medical Herb" },
  { index: 0x01, type: 0x0, name: "Healing Seed" },
  { index: 0x02, type: 0x0, name: "Antidote" },
  { index: 0x03, type: 0x0, name: "Shower of Cure" },
  { index: 0x04, type: 0x0, name: "Angel Wing" },
  { index: 0x05, type: 0x1, name: "Power Potion" },
  { index: 0x06, type: 0x1, name: "Defense Potion" },
  { index: 0x07, type: 0x1, name: "Legs of Haste" },
  { index: 0x08, type: 0x1, name: "Turbo Pepper" },
  { index: 0x09, type: 0x1, name: "Bread of Life" },
  { index: 0x0a, type: 0x8, name: "Power Ring" },
  { index: 0x0b, type: 0x8, name: "Shield Ring" },
  { index: 0x0c, type: 0x8, name: "Speed Ring" },
  { index: 0x0d, type: 0x8, name: "Mobility Ring" },
  { index: 0x0e, type: 0x8, name: "White Ring" },
  { index: 0x0f, type: 0x8, name: "Black Ring" },
  { index: 0x10, type: 0x8, name: "Evil Ring" },
  { index: 0x11, type: 0x9, name: "Bikini" },
  { index: 0x12, type: 0x2, name: "Orb of Light" },
  { index: 0x13, type: 0x2, name: "Moon Stone" },
  { index: 0x14, type: 0x2, name: "Lunar Dew" },
  { index: 0x15, type: 0x9, name: "Haute Couture" },
  { index: 0x16, type: 0x2, name: "Domingo Egg" },
  { index: 0x17, type: 0x9, name: "Kenji" },
  { index: 0x18, type: 0x9, name: "Teppou" },
  { index: 0x19, type: 0x9, name: "Kaku chan" },
  { index: 0x1a, type: 0x9, name: "Youji" },
  { index: 0x1b, type: 0x5, name: "Great Axe" },
  { index: 0x1c, type: 0x9, name: "Kindan NoHako" },
  { index: 0x1d, type: 0x3, name: "Short Sword" },
  { index: 0x1e, type: 0x3, name: "Middle Sword" },
  { index: 0x1f, type: 0x3, name: "Long Sword" },
  { index: 0x20, type: 0x3, name: "Steel Sword" },
  { index: 0x21, type: 0x3, name: "Broad Sword" },
  { index: 0x22, type: 0x3, name: "Doom Blade" },
  { index: 0x23, type: 0x3, name: "Katana" },
  { index: 0x24, type: 0x7, name: "Elven Arrow" },
  { index: 0x25, type: 0x3, name: "Sword of Darkness" },
  { index: 0x26, type: 0x3, name: "Sword of Light" },
  { index: 0x27, type: 0x3, name: "Chaos Breaker" },
  { index: 0x28, type: 0x4, name: "Bronze Lance" },
  { index: 0x29, type: 0x4, name: "Steel Lance" },
  { index: 0x2a, type: 0x4, name: "Chrome Lance" },
  { index: 0x2b, type: 0x4, name: "Devil Lance" },
  { index: 0x2c, type: 0x4, name: "Halberd" },
  { index: 0x2d, type: 0x4, name: "Spear" },
  { index: 0x2e, type: 0x4, name: "Power Spear" },
  { index: 0x2f, type: 0x4, name: "Valkyrie" },
  { index: 0x30, type: 0x5, name: "Hand Axe" },
  { index: 0x31, type: 0x5, name: "Middle Axe" },
  { index: 0x32, type: 0x5, name: "Battle Axe" },
  { index: 0x33, type: 0x5, name: "Heat Axe" },
  { index: 0x34, type: 0x5, name: "Atlas" },
  { index: 0x35, type: 0x6, name: "Wooden Staff" },
  { index: 0x36, type: 0x6, name: "Guardian Staff" },
  { index: 0x37, type: 0x6, name: "Holy Staff" },
  { index: 0x38, type: 0x6, name: "Power Staff" },
  { index: 0x39, type: 0x6, name: "Demon Rod" },
  { index: 0x3a, type: 0x8, name: "Yogurt Ring" },
  { index: 0x3b, type: 0x7, name: "Wooden Arrow" },
  { index: 0x3c, type: 0x7, name: "Steel Arrow" },
  { index: 0x3d, type: 0x7, name: "Assault Shell" },
  { index: 0x3e, type: 0x7, name: "Buster Shot" },
];

export const items: Resource = {};

export const itemsGroups: ResourceGroups = itemTypes.map((type) => ({
  name: type.name,
  options: [],
}));

itemList.forEach((item, index) => {
  items[index] = item.name;
  itemsGroups[item.type].options.push(index);
});
