import type { GameJson } from "$lib/types";

import { photoFragment } from "./utils/fragment";

const template: GameJson = {
  validator: {
    regions: {
      europe_france_germany_italy_spain: {
        0x10: [
          0x48, 0x41, 0x4c, 0x5f, 0x53, 0x4e, 0x41, 0x50, 0x5f, 0x56, 0x31,
        ], // "HAL_SNAP_V1"
      },
      usa_australia: {
        0x10: [
          0x48, 0x41, 0x4c, 0x5f, 0x53, 0x4e, 0x41, 0x50, 0x5f, 0x56, 0x31,
        ], // "HAL_SNAP_V1"
      },
      japan: {
        0x10: [
          0x48, 0x41, 0x4c, 0x5f, 0x53, 0x4e, 0x41, 0x50, 0x5f, 0x56, 0x31,
        ], // "HAL_SNAP_V1"
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    hint: "If you're having trouble loading a save file from an <b>Everdrive</b> cartridge, please see the FAQ.",
    error: "Not a valid save file.",
  },
  items: [
    {
      type: "section",
      flex: true,
      hidden: true,
      items: [
        {
          id: "checksum-0",
          name: "Checksum 1",
          offset: 0x0,
          type: "checksum",
          dataType: "uint32",
          bigEndian: true,
          control: {
            offsetStart: 0x10,
            offsetEnd: 0x1f2a4,
          },
        },
        {
          id: "checksum-1",
          name: "Checksum 2",
          offset: 0x4,
          type: "checksum",
          dataType: "uint32",
          bigEndian: true,
          control: {
            offsetStart: 0x10,
            offsetEnd: 0x1f2a4,
          },
        },
        {
          id: "checksum-2",
          name: "Checksum 3",
          offset: 0x8,
          type: "checksum",
          dataType: "uint32",
          bigEndian: true,
          control: {
            offsetStart: 0x10,
            offsetEnd: 0x1f2a4,
          },
        },
        {
          id: "checksum-3",
          name: "Checksum 4",
          offset: 0xc,
          type: "checksum",
          dataType: "uint32",
          bigEndian: true,
          control: {
            offsetStart: 0x10,
            offsetEnd: 0x1f2a4,
          },
        },
      ],
    },
    {
      type: "tabs",
      items: [
        {
          name: "General",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  id: "name",
                  name: "Name",
                  offset: 0x54,
                  length: 0x7,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  endCode: 0x0,
                  resource: "letters",
                  test: true,
                },
                {
                  id: "japan-unshift",
                  name: "Next course to be unlocked",
                  offset: 0x50,
                  type: "variable",
                  dataType: "uint32",
                  resource: "courses",
                  bigEndian: true,
                  hidden: true,
                },
                {
                  name: "Courses",
                  offset: 0x64,
                  type: "variable",
                  dataType: "uint8",
                  binary: {
                    bitStart: 5,
                    bitLength: 3,
                  },
                  resource: "courses",
                  hidden: true,
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  id: "unlockedCourses",
                  name: "Unlocked Courses",
                  type: "bitflags",
                  flags: [
                    { offset: 0x64, bit: 3, label: "Beach", disabled: true },
                    { offset: 0x64, bit: 5, label: "Tunnel" },
                    { offset: 0x64, bit: 5, label: "Volcano" },
                    { offset: 0x64, bit: 5, label: "River" },
                    { offset: 0x64, bit: 5, label: "Cave" },
                    { offset: 0x64, bit: 5, label: "Valley" },
                    { offset: 0x64, bit: 5, label: "Rainbow Cloud" },
                  ],
                },
                {
                  name: "Unlocked Items",
                  type: "bitflags",
                  flags: [
                    { offset: 0x66, bit: 7, label: "Pokémon Food" },
                    { offset: 0x66, bit: 6, label: "Pester Ball" },
                    { offset: 0x66, bit: 2, label: "Dash Engine" },
                    { offset: 0x66, bit: 5, label: "Poké Flute" },
                  ],
                },
                {
                  name: "Unlocked Menus",
                  type: "bitflags",
                  flags: [
                    { offset: 0x66, bit: 0, label: "PKMN Report" },
                    { offset: 0x66, bit: 2, label: "PKMN Signs" },
                    { offset: 0x67, bit: 3, label: "Challenge Score" },
                  ],
                },
              ],
            },
            {
              type: "section",
              flex: true,
              hidden: true,
              items: [
                {
                  id: "japan-unshift",
                  name: "Offset to PKMN Scores",
                  offset: 0x20,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  hex: true,
                  hidden: true,
                },
                {
                  id: "japan-unshift",
                  name: "Offset to Photos (Pokémons)",
                  offset: 0x24,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  hex: true,
                  hidden: true,
                },
                {
                  id: "japan-unshift",
                  name: "Offset to Photos (Shown to Prof. Oak)",
                  offset: 0x28,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  hex: true,
                  hidden: true,
                },
                {
                  id: "japan-unshift",
                  name: "Offset to PKMN Album",
                  offset: 0x2c,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  hex: true,
                  hidden: true,
                },
              ],
            },
          ],
        },
        {
          name: "Pokémons",
          items: [
            {
              length: 0x3a0,
              type: "container",
              instanceType: "tabs",
              instances: 63,
              resource: "pokemons",
              vertical: true,
              items: [photoFragment("pokemon")],
            },
          ],
        },
        {
          name: "Signs",
          items: [
            {
              length: 0x3a0,
              type: "container",
              instanceType: "tabs",
              instances: 6,
              resource: "signs",
              vertical: true,
              items: [photoFragment("sign")],
            },
          ],
        },
        {
          name: "Album",
          items: [
            {
              id: "album",
              length: 0x3e0,
              type: "container",
              instanceType: "tabs",
              instances: 60,
              enumeration: "Photo %d",
              vertical: true,
              items: [photoFragment("album")],
            },
          ],
        },
        {
          name: "Challenge Scores",
          flex: true,
          items: [
            {
              id: "japan-unshift",
              name: "Beach",
              offset: 0x34,
              type: "variable",
              dataType: "uint32",
              bigEndian: true,
              max: 99999999,
            },
            {
              id: "japan-unshift",
              name: "Tunnel",
              offset: 0x38,
              type: "variable",
              dataType: "uint32",
              bigEndian: true,
              max: 99999999,
            },
            {
              id: "japan-unshift",
              name: "Volcano",
              offset: 0x3c,
              type: "variable",
              dataType: "uint32",
              bigEndian: true,
              max: 99999999,
            },
            {
              id: "japan-unshift",
              name: "River",
              offset: 0x40,
              type: "variable",
              dataType: "uint32",
              bigEndian: true,
              max: 99999999,
            },
            {
              id: "japan-unshift",
              name: "Cave",
              offset: 0x44,
              type: "variable",
              dataType: "uint32",
              bigEndian: true,
              max: 99999999,
            },
            {
              id: "japan-unshift",
              name: "Valley",
              offset: 0x48,
              type: "variable",
              dataType: "uint32",
              bigEndian: true,
              max: 99999999,
            },
            {
              id: "japan-unshift",
              name: "Rainbow Cloud",
              offset: 0x4c,
              type: "variable",
              dataType: "uint32",
              bigEndian: true,
              max: 99999999,
            },
          ],
        },
        {
          name: "Options",
          items: [
            {
              name: "Screen",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Position X",
                  offset: 0x64,
                  type: "variable",
                  dataType: "uint16",
                  bigEndian: true,
                  binary: {
                    bitStart: 6,
                    bitLength: 5,
                  },
                  min: 0,
                  max: 24,
                },
                {
                  name: "Position Y",
                  offset: 0x65,
                  type: "variable",
                  dataType: "uint8",
                  binary: {
                    bitStart: 1,
                    bitLength: 5,
                  },
                  min: 13,
                  max: 22,
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Sound",
                  offset: 0x67,
                  type: "variable",
                  dataType: "bit",
                  bit: 6,
                  resource: "sounds",
                },
                {
                  name: "Z Button Setup",
                  offset: 0x67,
                  type: "variable",
                  dataType: "bit",
                  bit: 2,
                  resource: "zButtons",
                },
                {
                  name: "Control Stick Setup",
                  offset: 0x67,
                  type: "variable",
                  dataType: "bit",
                  bit: 1,
                  resource: "controlSticks",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    controlSticks: {
      0x0: "Reverse",
      0x1: "Normal",
    },
    courses: {
      0x0: "Beach",
      0x1: "Tunnel",
      0x2: "Volcano",
      0x3: "River",
      0x4: "Cave",
      0x5: "Valley",
      0x6: "Rainbow Cloud",
    },
    letters: [
      // Europe
      {
        0x20: " ",
        0x21: "!",
        0x22: '"',
        0x23: "#",
        0x24: "$",
        0x25: "%",
        0x26: "&",
        0x27: "'",
        0x28: "(",
        0x29: ")",
        0x2a: "*",
        0x2b: "+",
        0x2c: ",",
        0x2d: "-",
        0x2e: ".",
        0x2f: "/",
        0x30: "0",
        0x31: "1",
        0x32: "2",
        0x33: "3",
        0x34: "4",
        0x35: "5",
        0x36: "6",
        0x37: "7",
        0x38: "8",
        0x39: "9",
        0x3a: ":",
        0x3b: ";",
        0x3c: "<",
        0x3d: "=",
        0x3e: ">",
        0x3f: "?",
        0x40: "@",
        0x41: "A",
        0x42: "B",
        0x43: "C",
        0x44: "D",
        0x45: "E",
        0x46: "F",
        0x47: "G",
        0x48: "H",
        0x49: "I",
        0x4a: "J",
        0x4b: "K",
        0x4c: "L",
        0x4d: "M",
        0x4e: "N",
        0x4f: "O",
        0x50: "P",
        0x51: "Q",
        0x52: "R",
        0x53: "S",
        0x54: "T",
        0x55: "U",
        0x56: "V",
        0x57: "W",
        0x58: "X",
        0x59: "Y",
        0x5a: "Z",
        0x5b: "[",
        0x5d: "]",
        0x5f: "_",
        0x61: "a",
        0x62: "b",
        0x63: "c",
        0x64: "d",
        0x65: "e",
        0x66: "f",
        0x67: "g",
        0x68: "h",
        0x69: "i",
        0x6a: "j",
        0x6b: "k",
        0x6c: "l",
        0x6d: "m",
        0x6e: "n",
        0x6f: "o",
        0x70: "p",
        0x71: "q",
        0x72: "r",
        0x73: "s",
        0x74: "t",
        0x75: "u",
        0x76: "v",
        0x77: "w",
        0x78: "x",
        0x79: "y",
        0x7a: "z",
        0x7e: "~",
        0x9a: "¥",
        0x9b: "⒨",
        0x9c: "⒫",
        0x9d: "♀",
        0x9e: "♂",
        0xa1: "¡",
        0xaa: "ª",
        0xba: "º",
        0xbf: "¿",
        0xc0: "À",
        0xc1: "Á",
        0xc2: "Â",
        0xc4: "Ä",
        0xc7: "Ç",
        0xc8: "È",
        0xc9: "É",
        0xcc: "Ì",
        0xcd: "Í",
        0xd1: "Ñ",
        0xd2: "Ò",
        0xd3: "Ó",
        0xd4: "Ô",
        0xd6: "Ö",
        0xd9: "Ù",
        0xda: "Ú",
        0xdc: "Ü",
        0xdf: "ß",
        0xe0: "à",
        0xe1: "á",
        0xe2: "â",
        0xe4: "ä",
        0xe7: "ç",
        0xe8: "è",
        0xe9: "é",
        0xea: "ê",
        0xeb: "ë",
        0xec: "ì",
        0xed: "í",
        0xee: "î",
        0xef: "ï",
        0xf1: "ñ",
        0xf2: "ò",
        0xf3: "ó",
        0xf4: "ô",
        0xf6: "ö",
        0xf9: "ù",
        0xfa: "ú",
        0xfc: "ü",
      },
      // USA
      {
        0xa1a1: " ",
        0xa1a4: ",",
        0xa1a5: ".",
        0xa1a7: ":",
        0xa1a8: ";",
        0xa1a9: "?",
        0xa1aa: "!",
        0xa1b2: "_",
        0xa1bc: "-",
        0xa1bf: "/",
        0xa1c1: "~",
        0xa1c7: "'",
        0xa1c9: '"',
        0xa1ca: "(",
        0xa1cb: ")",
        0xa1ce: "[",
        0xa1cf: "]",
        0xa1dc: "+",
        0xa1e1: "=",
        0xa1e3: "<",
        0xa1e4: ">",
        0xa1e9: "♂",
        0xa1ea: "♀",
        0xa1f0: "$",
        0xa1f3: "%",
        0xa1f4: "#",
        0xa1f5: "&",
        0xa1f6: "*",
        0xa1f7: "@",
        0xa2f7: "⒫",
        0xa2f8: "⒨",
        0xa2f9: "¥",
        0xa3b0: "0",
        0xa3b1: "1",
        0xa3b2: "2",
        0xa3b3: "3",
        0xa3b4: "4",
        0xa3b5: "5",
        0xa3b6: "6",
        0xa3b7: "7",
        0xa3b8: "8",
        0xa3b9: "9",
        0xa3c1: "A",
        0xa3c2: "B",
        0xa3c3: "C",
        0xa3c4: "D",
        0xa3c5: "E",
        0xa3c6: "F",
        0xa3c7: "G",
        0xa3c8: "H",
        0xa3c9: "I",
        0xa3ca: "J",
        0xa3cb: "K",
        0xa3cc: "L",
        0xa3cd: "M",
        0xa3ce: "N",
        0xa3cf: "O",
        0xa3d0: "P",
        0xa3d1: "Q",
        0xa3d2: "R",
        0xa3d3: "S",
        0xa3d4: "T",
        0xa3d5: "U",
        0xa3d6: "V",
        0xa3d7: "W",
        0xa3d8: "X",
        0xa3d9: "Y",
        0xa3da: "Z",
        0xa3e1: "a",
        0xa3e2: "b",
        0xa3e3: "c",
        0xa3e4: "d",
        0xa3e5: "e",
        0xa3e6: "f",
        0xa3e7: "g",
        0xa3e8: "h",
        0xa3e9: "i",
        0xa3ea: "j",
        0xa3eb: "k",
        0xa3ec: "l",
        0xa3ed: "m",
        0xa3ee: "n",
        0xa3ef: "o",
        0xa3f0: "p",
        0xa3f1: "q",
        0xa3f2: "r",
        0xa3f3: "s",
        0xa3f4: "t",
        0xa3f5: "u",
        0xa3f6: "v",
        0xa3f7: "w",
        0xa3f8: "x",
        0xa3f9: "y",
        0xa3fa: "z",
        0xa6c5: "é",
      },
      // Japan
      {
        0xa1a1: " ",
        0xa1a2: "、",
        0xa1a3: "。",
        0xa1a9: "?",
        0xa1aa: "!",
        0xa1c1: "~",
        0xa1dd: "ー",
        0xa3b0: "0",
        0xa3b1: "1",
        0xa3b2: "2",
        0xa3b3: "3",
        0xa3b4: "4",
        0xa3b5: "5",
        0xa3b6: "6",
        0xa3b7: "7",
        0xa3b8: "8",
        0xa3b9: "9",
        0xa1bc: "-",
        0xa3c1: "A",
        0xa3c2: "B",
        0xa3c3: "C",
        0xa3c4: "D",
        0xa3c5: "E",
        0xa3c6: "F",
        0xa3c7: "G",
        0xa3c8: "H",
        0xa3c9: "I",
        0xa3ca: "J",
        0xa3cb: "K",
        0xa3cc: "L",
        0xa3cd: "M",
        0xa3ce: "N",
        0xa3cf: "O",
        0xa3d0: "P",
        0xa3d1: "Q",
        0xa3d2: "R",
        0xa3d3: "S",
        0xa3d4: "T",
        0xa3d5: "U",
        0xa3d6: "V",
        0xa3d7: "W",
        0xa3d8: "X",
        0xa3d9: "Y",
        0xa3da: "Z",
        0xa3e1: "a",
        0xa3e2: "b",
        0xa3e3: "c",
        0xa3e4: "d",
        0xa3e5: "e",
        0xa3e6: "f",
        0xa3e7: "g",
        0xa3e8: "h",
        0xa3e9: "i",
        0xa3ea: "j",
        0xa3eb: "k",
        0xa3ec: "l",
        0xa3ed: "m",
        0xa3ee: "n",
        0xa3ef: "o",
        0xa3f0: "p",
        0xa3f1: "q",
        0xa3f2: "r",
        0xa3f3: "s",
        0xa3f4: "t",
        0xa3f5: "u",
        0xa3f6: "v",
        0xa3f7: "w",
        0xa3f8: "x",
        0xa3f9: "y",
        0xa3fa: "z",
        0xa4a1: "ぁ",
        0xa4a2: "あ",
        0xa4a3: "ぃ",
        0xa4a4: "い",
        0xa4a5: "ぅ",
        0xa4a6: "う",
        0xa4a7: "ぇ",
        0xa4a8: "え",
        0xa4a9: "ぉ",
        0xa4aa: "お",
        0xa4ab: "か",
        0xa4ac: "が",
        0xa4ad: "き",
        0xa4ae: "ぎ",
        0xa4af: "く",
        0xa4b0: "ぐ",
        0xa4b1: "け",
        0xa4b2: "げ",
        0xa4b3: "こ",
        0xa4b4: "ご",
        0xa4b5: "さ",
        0xa4b6: "ざ",
        0xa4b7: "し",
        0xa4b8: "じ",
        0xa4b9: "す",
        0xa4ba: "ず",
        0xa4bb: "せ",
        0xa4bc: "ぜ",
        0xa4bd: "そ",
        0xa4be: "ぞ",
        0xa4bf: "た",
        0xa4c0: "だ",
        0xa4c1: "ち",
        0xa4c2: "ぢ",
        0xa4c3: "っ",
        0xa4c4: "つ",
        0xa4c5: "づ",
        0xa4c6: "て",
        0xa4c7: "で",
        0xa4c8: "と",
        0xa4c9: "ど",
        0xa4ca: "な",
        0xa4cb: "に",
        0xa4cc: "ぬ",
        0xa4cd: "ね",
        0xa4ce: "の",
        0xa4cf: "は",
        0xa4d0: "ば",
        0xa4d1: "ぱ",
        0xa4d2: "ひ",
        0xa4d3: "び",
        0xa4d4: "ぴ",
        0xa4d5: "ふ",
        0xa4d6: "ぶ",
        0xa4d7: "ぷ",
        0xa4d8: "へ",
        0xa4d9: "べ",
        0xa4da: "ぺ",
        0xa4db: "ほ",
        0xa4dc: "ぼ",
        0xa4dd: "ぽ",
        0xa4de: "ま",
        0xa4df: "み",
        0xa4e0: "む",
        0xa4e1: "め",
        0xa4e2: "も",
        0xa4e3: "ゃ",
        0xa4e4: "や",
        0xa4e5: "ゅ",
        0xa4e6: "ゆ",
        0xa4e7: "ょ",
        0xa4e8: "よ",
        0xa4e9: "ら",
        0xa4ea: "り",
        0xa4eb: "る",
        0xa4ec: "れ",
        0xa4ed: "ろ",
        0xa4ef: "わ",
        0xa4f2: "を",
        0xa4f3: "ん",
        0xa5a1: "ァ",
        0xa5a2: "ア",
        0xa5a3: "ィ",
        0xa5a4: "イ",
        0xa5a5: "ゥ",
        0xa5a6: "ウ",
        0xa5a7: "ェ",
        0xa5a8: "エ",
        0xa5a9: "ォ",
        0xa5aa: "オ",
        0xa5ab: "カ",
        0xa5ac: "ガ",
        0xa5ad: "キ",
        0xa5ae: "ギ",
        0xa5af: "ク",
        0xa5b0: "グ",
        0xa5b1: "ケ",
        0xa5b2: "ゲ",
        0xa5b3: "コ",
        0xa5b4: "ゴ",
        0xa5b5: "サ",
        0xa5b6: "ザ",
        0xa5b7: "シ",
        0xa5b8: "ジ",
        0xa5b9: "ス",
        0xa5ba: "ズ",
        0xa5bb: "セ",
        0xa5bc: "ゼ",
        0xa5bd: "ソ",
        0xa5be: "ゾ",
        0xa5bf: "タ",
        0xa5c0: "ダ",
        0xa5c1: "チ",
        0xa5c2: "ヂ",
        0xa5c3: "ッ",
        0xa5c4: "ツ",
        0xa5c5: "ヅ",
        0xa5c6: "テ",
        0xa5c7: "デ",
        0xa5c8: "ト",
        0xa5c9: "ド",
        0xa5ca: "ナ",
        0xa5cb: "ニ",
        0xa5cc: "ヌ",
        0xa5cd: "ネ",
        0xa5ce: "ノ",
        0xa5cf: "ハ",
        0xa5d0: "バ",
        0xa5d1: "パ",
        0xa5d2: "ヒ",
        0xa5d3: "ビ",
        0xa5d4: "ピ",
        0xa5d5: "フ",
        0xa5d6: "ブ",
        0xa5d7: "プ",
        0xa5d8: "ヘ",
        0xa5d9: "ベ",
        0xa5da: "ペ",
        0xa5db: "ホ",
        0xa5dc: "ボ",
        0xa5dd: "ポ",
        0xa5de: "マ",
        0xa5df: "ミ",
        0xa5e0: "ム",
        0xa5e1: "メ",
        0xa5e2: "モ",
        0xa5e3: "ャ",
        0xa5e4: "ヤ",
        0xa5e5: "ュ",
        0xa5e6: "ユ",
        0xa5e7: "ョ",
        0xa5e8: "ヨ",
        0xa5e9: "ラ",
        0xa5ea: "リ",
        0xa5eb: "ル",
        0xa5ec: "レ",
        0xa5ed: "ロ",
        0xa5ef: "ワ",
        0xa5f2: "ヲ",
        0xa5f3: "ン",
      },
    ],
    photoCourses: {
      0x0: "Beach",
      0x2: "Tunnel",
      0x4: "Volcano",
      0x6: "River",
      0x8: "Cave",
      0xa: "Valley",
      0xc: "Rainbow Cloud",
      0xff: "-",
    },
    photoStatus: {
      0x0: "Empty",
      0x1: "Taken",
    },
    pokemons: {
      0x0: "001 Bulbasaur",
      0x1: "004 Charmander",
      0x2: "005 Charmeleon",
      0x3: "006 Charizard",
      0x4: "007 Squirtle",
      0x5: "011 Metapod",
      0x6: "012 Butterfree",
      0x7: "014 Kakuna",
      0x8: "016 Pidgey",
      0x9: "025 Pikachu",
      0xa: "027 Sandshrew",
      0xb: "028 Sandslash",
      0xc: "037 Vulpix",
      0xd: "039 Jigglypuff",
      0xe: "041 Zubat",
      0xf: "045 Vileplume",
      0x10: "050 Diglett",
      0x11: "051 Dugtrio",
      0x12: "052 Meowth",
      0x13: "054 Psyduck",
      0x14: "056 Mankey",
      0x15: "058 Growlithe",
      0x16: "059 Arcanine",
      0x17: "060 Poliwag",
      0x18: "070 Weepinbell",
      0x19: "071 Victreebel",
      0x1a: "074 Geodude",
      0x1b: "075 Graveler",
      0x1c: "078 Rapidash",
      0x1d: "079 Slowpoke",
      0x1e: "080 Slowbro",
      0x1f: "081 Magnemite",
      0x20: "082 Magneton",
      0x21: "084 Doduo",
      0x22: "088 Grimer",
      0x23: "089 Muk",
      0x24: "090 Shellder",
      0x25: "091 Cloyster",
      0x26: "093 Haunter",
      0x27: "101 Electrode",
      0x28: "109 Koffing",
      0x29: "113 Chansey",
      0x2a: "115 Kangaskhan",
      0x2b: "118 Goldeen",
      0x2c: "120 Staryu",
      0x2d: "121 Starmie",
      0x2e: "123 Scyther",
      0x2f: "124 Jynx",
      0x30: "125 Electabuzz",
      0x31: "126 Magmar",
      0x32: "129 Magikarp",
      0x33: "130 Gyarados",
      0x34: "131 Lapras",
      0x35: "132 Ditto",
      0x36: "133 Eevee",
      0x37: "137 Porygon",
      0x38: "143 Snorlax",
      0x39: "144 Articuno",
      0x3a: "145 Zapdos",
      0x3b: "146 Moltres",
      0x3c: "147 Dratini",
      0x3d: "149 Dragonite",
      0x3e: "151 Mew",
    },
    signs: {
      0x0: "Kingler Rock",
      0x1: "Pinsir Shadow",
      0x2: "Koffing Smoke",
      0x3: "Cubone Tree",
      0x4: "Mewtwo",
      0x5: "Mt. Dugtrio",
    },
    sounds: {
      0x0: "Stereo",
      0x1: "Mono",
    },
    zButtons: {
      0x0: "Hold",
      0x1: "Switch",
    },
  },
};

export default template;
