import type { Resource } from "$lib/types";

export const characters = {
  0x0: "Synbios",
  0x1: "Dantares",
  0x2: "Masqurin",
  0x3: "Grace",
  0x4: "Hayward",
  0x5: "Obright",
  0x6: "Irene",
  0x7: "Julian",
  0x8: "Cybel",
  0x9: "Eldar",
  0xa: "Kahn",
  0xb: "Noon",
  0xc: "Justin",
  0xd: "Horst",
  0xe: "Penn",
  0xf: "Ratchet",
  0x10: "Frank",
  0x11: "Hagane",
  0x12: "Murasame",
  0x13: "Fynnding",
  0x14: "Medion",
  0x15: "Campbell",
  0x16: "Syntesis",
  0x17: "Uryudo",
  0x18: "Waltz",
  0x19: "Rock",
  0x1a: "Bernard",
  0x1b: "Zero",
  0x1c: "Hazuki",
  0x1d: "David",
  0x1e: "Hedva",
  0x1f: "Gracia",
  0x20: "Donhort",
  0x21: "Hera",
  0x22: "Robby",
  0x23: "Arthur",
  0x24: "Garosh",
  0x25: "Jade",
  0x26: "Penko",
  0x27: "Pappets",
  0x28: "Kate",
  0x29: "Rogan",
  0x2a: "Edmund",
  0x2b: "Isabella",
  0x2c: "Brigit",
  0x2d: "Cyclops",
  0x2e: "Rollie",
  0x2f: "Thousand",
  0x30: "Leon",
  0x31: "Honesty",
  0x32: "Produn",
  0x33: "Harold",
  0x34: "Pendolf",
  0x35: "Spiriel",
  0x36: "Jubei",
  0x37: "Primula",
  0x38: "Marky",
  0x39: "Turk",
  0x3a: "Unoma",
};

export const classes = {
  0x0: "Swordsman",
  0x1: "Knight",
  0x2: "Warrior",
  0x3: "Priest",
  0x4: "Magician",
  0x5: "Archer",
  0x6: "Monk",
  0x7: "Birdsoldier",
  0x8: "Ranger",
  0x9: "Penguin",
  0xa: "Steam Soldier",
  0xb: "Werewolf",
  0xc: "Ninja Tyro",
  0xd: "Kunoichi",
  0xe: "Elven Ranger",
  0xf: "Shaman",
  0x10: "Mecha Bot",
  0x11: "Metal Driver",
  0x12: "Penguin",
  0x13: "Trainer",
  0x14: "Child",
  0x15: "Officer",
  0x16: "Royal Youth",
  0x17: "Dragon Child",
  0x18: "Unicorn Filly",
  0x19: "Dragon",
  0x1a: "Lion Soldier",
  0x1b: "Pegasus",
  0x1c: "Penguin",
  0x1d: "Samurai Tyro",
  0x1e: "Sprite",
  0x1f: "Harridan",
  0x20: "Hero",
  0x21: "Cavalier",
  0x22: "Gladiator",
  0x23: "Cleric",
  0x24: "Wizard",
  0x25: "Sniper",
  0x26: "Master Monk",
  0x27: "Birdknight",
  0x28: "Bow Knight",
  0x29: "Dynamo",
  0x2a: "Steam Knight",
  0x2b: "Wolf Baron",
  0x2c: "Ninja",
  0x2d: "Ninja",
  0x2e: "Striker",
  0x2f: "Summoner",
  0x30: "Mecha Soldier",
  0x31: "Gunner",
  0x32: "Diva",
  0x33: "Beast Tamer",
  0x34: "Godchild",
  0x35: "Commander",
  0x36: "Princess",
  0x37: "Dragonman",
  0x38: "Unicorn",
  0x39: "White Dragon",
  0x3a: "Lion Warrior",
  0x3b: "Pegasus Knight",
  0x3c: "Scholar",
  0x3d: "Samurai",
  0x3e: "Fairy",
  0x3f: "Witch",
  0x40: "Ogre Rider",
  0x41: "Master",
  0x42: "Rider",
  0x43: "Monk",
  // 0x44: "1-228", // Unused
  // 0x45: "1-229", // Unused
  // 0x46: "1-230", // Unused
  // 0x47: "1-231", // Unused
  0x48: "Champion",
  0x49: "Paladin",
  0x4a: "High Wizard",
  0x4b: "Bishop",
  0x4c: "Bow Master",
  0x4d: "Baron",
  0x4e: "Fist Master",
  0x4f: "Wing Lord",
  0x50: "Saint",
  0x51: "Buster Knight",
  0x52: "Emperor",
  0x53: "Steam Baron",
  0x54: "Berserker",
  0x55: "Master Ninja",
  0x56: "Commando",
  0x57: "Sorceress",
  0x58: "Innovator",
  0x59: "Mecha God",
  0x5a: "Magic Knight",
  0x5b: "Buster",
  0x5c: "Queen",
  0x5d: "Beast Master",
  0x5e: "General",
  0x5f: "Light Princess",
  0x60: "Dragon Master",
  0x61: "Unicorn Queen",
  0x62: "Sacred Dragon",
  0x63: "Lion King",
  0x64: "Pegasus Lord",
  0x65: "Professor",
  0x66: "Taisho",
  0x67: "Light Fairy",
  0x68: "Enchantress",
  0x69: "Mad Rider",
  0x6a: "Hermit",
};

export const itemsDetails = [
  { index: 0x1, name: "Bronze Knife", type: 0xa },
  { index: 0x2, name: "Steel Knife", type: 0xa },
  { index: 0x3, name: "Hunter Knife", type: 0xa },
  { index: 0x4, name: "Steel Sword", type: 0xb },
  { index: 0x5, name: "Broad Sword", type: 0xb },
  { index: 0x6, name: "Bastard Sword", type: 0xb },
  { index: 0x7, name: "Great Sword", type: 0xb },
  { index: 0x8, name: "Epee", type: 0xc },
  { index: 0x9, name: "Foil", type: 0xc },
  { index: 0xa, name: "Rapier", type: 0xc },
  { index: 0xb, name: "Iron Blade", type: 0xd },
  { index: 0xc, name: "Battle Blade", type: 0xd },
  { index: 0xd, name: "Steel Blade", type: 0xd },
  { index: 0xe, name: "Small Katana", type: 0xe },
  { index: 0xf, name: "Ninja Katana", type: 0xe },
  { index: 0x10, name: "Steel Ninjato", type: 0xe },
  { index: 0x11, name: "Bronze Lance", type: 0x14 },
  { index: 0x12, name: "Iron Lance", type: 0x14 },
  { index: 0x13, name: "Heavy Lance", type: 0x14 },
  { index: 0x14, name: "Steel Lance", type: 0x14 },
  { index: 0x15, name: "Spear", type: 0x15 },
  { index: 0x16, name: "Power Spear", type: 0x15 },
  { index: 0x17, name: "Battle Spear", type: 0x15 },
  { index: 0x18, name: "Halberd", type: 0x16 },
  { index: 0x19, name: "Heavy Halberd", type: 0x16 },
  { index: 0x1a, name: "Poleaxe", type: 0x16 },
  { index: 0x1b, name: "Small Axe", type: 0x1e },
  { index: 0x1c, name: "Power Axe", type: 0x1e },
  { index: 0x1d, name: "Battle Axe", type: 0x1e },
  { index: 0x1e, name: "Great Axe", type: 0x1e },
  { index: 0x1f, name: "Tomahawk", type: 0x1f },
  { index: 0x20, name: "Power Hatchet", type: 0x1f },
  { index: 0x21, name: "Battle Hatchet", type: 0x1f },
  { index: 0x22, name: "Mace", type: 0x20 },
  { index: 0x23, name: "Flail", type: 0x20 },
  { index: 0x24, name: "Battle Mace", type: 0x20 },
  { index: 0x25, name: "Bronze Claw", type: 0x32 },
  { index: 0x26, name: "Iron Claw", type: 0x32 },
  { index: 0x27, name: "Steel Claw", type: 0x32 },
  { index: 0x28, name: "Battle Claw", type: 0x32 },
  { index: 0x29, name: "Leather Glove", type: 0x33 },
  { index: 0x2a, name: "Iron Glove", type: 0x33 },
  { index: 0x2b, name: "Steel Glove", type: 0x33 },
  { index: 0x2c, name: "Cestus", type: 0x34 },
  { index: 0x2d, name: "Iron Cestus", type: 0x34 },
  { index: 0x2e, name: "Steel Cestus", type: 0x34 },
  { index: 0x2f, name: "Wooden Rod", type: 0x3c },
  { index: 0x30, name: "Bronze Rod", type: 0x3c },
  { index: 0x31, name: "Talisman Rod", type: 0x3c },
  { index: 0x32, name: "Small Wand", type: 0x3d },
  { index: 0x33, name: "Magic Wand", type: 0x3d },
  { index: 0x34, name: "Anger Wand", type: 0x3d },
  { index: 0x35, name: "Power Ankh", type: 0x3e },
  { index: 0x36, name: "Saint Ankh", type: 0x3e },
  { index: 0x37, name: "Mystery Ankh", type: 0x3e },
  { index: 0x38, name: "Wooden Arrow", type: 0x46 },
  { index: 0x39, name: "Steel Arrow", type: 0x46 },
  { index: 0x3a, name: "Robin Arrow", type: 0x46 },
  { index: 0x3b, name: "King Arrow", type: 0x46 },
  { index: 0x3c, name: "Light Quarrel", type: 0x47 },
  { index: 0x3d, name: "Middle Quarrel", type: 0x47 },
  { index: 0x3e, name: "Heavy Quarrel", type: 0x47 },
  { index: 0x3f, name: "Assault Shell", type: 0x48 },
  { index: 0x40, name: "Great Shell", type: 0x48 },
  { index: 0x41, name: "Buster Shot", type: 0x48 },
  { index: 0x42, name: "Scimitar", type: 0xb },
  { index: 0x43, name: "Chaos Ring", type: 0x81 },
  { index: 0x44, name: "Power Ring", type: 0x81 },
  { index: 0x45, name: "Protect Ring", type: 0x81 },
  { index: 0x46, name: "Magic Ring", type: 0x81 },
  { index: 0x47, name: "Gale Ring", type: 0x81 },
  { index: 0x48, name: "Attack Ring", type: 0x81 },
  { index: 0x49, name: "Master Ring", type: 0x81 },
  { index: 0x4a, name: "Silver Ring", type: 0x81 },
  { index: 0x4b, name: "Life Ring", type: 0x81 },
  { index: 0x4c, name: "Running Ring", type: 0x81 },
  { index: 0x4d, name: "White Ring", type: 0x81 },
  { index: 0x4e, name: "Black Ring", type: 0x81 },
  { index: 0x4f, name: "Evil Ring", type: 0x81 },
  { index: 0x50, name: "Artemis Pin", type: 0x81 },
  { index: 0x51, name: "Apollo Pin", type: 0x81 },
  { index: 0x52, name: "Battle Bracer", type: 0x7a },
  { index: 0x53, name: "Protect Bracer", type: 0x7a },
  { index: 0x54, name: "Medical Herb", type: 0x1 },
  { index: 0x55, name: "Healing Drop", type: 0x1 },
  { index: 0x56, name: "Potion", type: 0x1 },
  { index: 0x57, name: "Healing Rain", type: 0x1 },
  { index: 0x58, name: "Goddess Tear", type: 0x1 },
  { index: 0x59, name: "Light of Hope", type: 0x1 },
  { index: 0x5a, name: "Antidote Herb", type: 0x1 },
  { index: 0x5b, name: "Fairy Powder", type: 0x1 },
  { index: 0x5c, name: "Angel Wing", type: 0x1 },
  { index: 0x5d, name: "Power Wine", type: 0x1 },
  { index: 0x5e, name: "Protect Milk", type: 0x1 },
  { index: 0x5f, name: "Quick Chicken", type: 0x1 },
  { index: 0x60, name: "Running Pepper", type: 0x1 },
  { index: 0x61, name: "Lucky Cookie", type: 0x1 },
  { index: 0x62, name: "Health Bread", type: 0x1 },
  { index: 0x63, name: "Bright Honey", type: 0x1 },
  { index: 0x64, name: "Brave Apple", type: 0x1 },
  { index: 0x65, name: "Large Mithril", type: 0x1 },
  { index: 0x66, name: "Small Mithril", type: 0x1 },
  { index: 0x67, name: "Dark Matter", type: 0x1 },
  { index: 0x68, name: "Platina Circlet", type: 0x7b },
  { index: 0x69, name: "Royal Tiara", type: 0x7b },
  { index: 0x6a, name: "Swift Boots", type: 0x81 },
  { index: 0x6b, name: "Shadow Helm", type: 0x7c },
  { index: 0x6c, name: "Dark Helmet", type: 0x7c },
  { index: 0x6d, name: "Loincloth", type: 0x81 },
  { index: 0x6e, name: "Power Undies", type: 0x81 },
  { index: 0x6f, name: "Mithril Dirk", type: 0xa },
  { index: 0x70, name: "Butterfly Knife", type: 0xa },
  { index: 0x71, name: "Assassin Knife", type: 0xa },
  { index: 0x72, name: "Thief Knife", type: 0xa },
  { index: 0x73, name: "Joker Knife", type: 0xa },
  { index: 0x74, name: "Counter Sword", type: 0xb },
  { index: 0x75, name: "Shiva Sword", type: 0xb },
  { index: 0x76, name: "Leviathan", type: 0xb },
  { index: 0x77, name: "Dark Sword", type: 0xb },
  { index: 0x78, name: "Phoenix Sword", type: 0xb },
  { index: 0x79, name: "Justice Sword", type: 0xb },
  { index: 0x7a, name: "Mist Rapier", type: 0xc },
  { index: 0x7b, name: "Magic Rapier", type: 0xc },
  { index: 0x7c, name: "Shiny Rapier", type: 0xc },
  { index: 0x7d, name: "Final Rapier", type: 0xc },
  { index: 0x7e, name: "Luster Blade", type: 0xd },
  { index: 0x7f, name: "Rune Blade", type: 0xd },
  { index: 0x80, name: "Photon Blade", type: 0xd },
  { index: 0x81, name: "Venom Blade", type: 0xd },
  { index: 0x82, name: "Force Blade", type: 0xd },
  { index: 0x83, name: "Gale Lance", type: 0x14 },
  { index: 0x84, name: "Holy Lance", type: 0x14 },
  { index: 0x85, name: "Dragon Lance", type: 0x14 },
  { index: 0x86, name: "Gungnir", type: 0x14 },
  { index: 0x87, name: "Silver Spear", type: 0x15 },
  { index: 0x88, name: "Counter Spear", type: 0x15 },
  { index: 0x89, name: "Rune Spear", type: 0x15 },
  { index: 0x8a, name: "Beast Spear", type: 0x15 },
  { index: 0x8b, name: "Comet Spear", type: 0x15 },
  { index: 0x8c, name: "Holy Halberd", type: 0x16 },
  { index: 0x8d, name: "Lord Halberd", type: 0x16 },
  { index: 0x8e, name: "Ark Halberd", type: 0x16 },
  { index: 0x8f, name: "Dark Halberd", type: 0x16 },
  { index: 0x90, name: "Heat Axe", type: 0x1e },
  { index: 0x91, name: "Giant Axe", type: 0x1e },
  { index: 0x92, name: "Dragon Axe", type: 0x1e },
  { index: 0x93, name: "Gaia Axe", type: 0x1e },
  { index: 0x94, name: "Evil Axe", type: 0x1e },
  { index: 0x95, name: "Rune Tomahawk", type: 0x1f },
  { index: 0x96, name: "Killer Hatchet", type: 0x1f },
  { index: 0x97, name: "Sky Tomahawk", type: 0x1f },
  { index: 0x98, name: "Ultra Tomahawk", type: 0x1f },
  { index: 0x99, name: "Saint Mace", type: 0x20 },
  { index: 0x9a, name: "Revenge Mace", type: 0x20 },
  { index: 0x9b, name: "Thor Hammer", type: 0x20 },
  { index: 0x9c, name: "Macho Mace", type: 0x20 },
  { index: 0x9d, name: "Mithril Claw", type: 0x32 },
  { index: 0x9e, name: "Tiger Claw", type: 0x32 },
  { index: 0x9f, name: "Berserk Claw", type: 0x32 },
  { index: 0xa0, name: "Digitalis Claw", type: 0x32 },
  { index: 0xa1, name: "Spiked Glove", type: 0x33 },
  { index: 0xa2, name: "Muscle Glove", type: 0x33 },
  { index: 0xa3, name: "Spark Glove", type: 0x33 },
  { index: 0xa4, name: "Magna Glove", type: 0x33 },
  { index: 0xa5, name: "Pretty Glove", type: 0x33 },
  { index: 0xa6, name: "Giant Cestus", type: 0x34 },
  { index: 0xa7, name: "Mist Cestus", type: 0x34 },
  { index: 0xa8, name: "Wire Cestus", type: 0x34 },
  { index: 0xa9, name: "Dragon Cestus", type: 0x34 },
  { index: 0xaa, name: "Torture Rod", type: 0x3c },
  { index: 0xab, name: "Sleepy Rod", type: 0x3c },
  { index: 0xac, name: "Alchemy Rod", type: 0x3c },
  { index: 0xad, name: "Crystal Rod", type: 0x3c },
  { index: 0xae, name: "Demon Rod", type: 0x3c },
  { index: 0xaf, name: "Jester Wand", type: 0x3d },
  { index: 0xb0, name: "Charm Wand", type: 0x3d },
  { index: 0xb1, name: "Witch Wand", type: 0x3d },
  { index: 0xb2, name: "Pyra's Wand", type: 0x3d },
  { index: 0xb3, name: "Wendigo Wand", type: 0x3d },
  { index: 0xb4, name: "Druid Ankh", type: 0x3e },
  { index: 0xb5, name: "Silence Ankh", type: 0x3e },
  { index: 0xb6, name: "Blessed Ankh", type: 0x3e },
  { index: 0xb7, name: "Holy Ankh", type: 0x3e },
  { index: 0xb8, name: "Moonlight Arrow", type: 0x46 },
  { index: 0xb9, name: "Dragon Arrow", type: 0x46 },
  { index: 0xba, name: "Breaker Arrow", type: 0x46 },
  { index: 0xbb, name: "Cantarella", type: 0x46 },
  { index: 0xbc, name: "Moogie Arrow", type: 0x46 },
  { index: 0xbd, name: "Mithril Quarrel", type: 0x47 },
  { index: 0xbe, name: "Flame Quarrel", type: 0x47 },
  { index: 0xbf, name: "Sonic Quarrel", type: 0x47 },
  { index: 0xc0, name: "Needle Quarrel", type: 0x47 },
  { index: 0xc1, name: "Magnum Shell", type: 0x48 },
  { index: 0xc2, name: "Storm Shot", type: 0x48 },
  { index: 0xc3, name: "Meteor Shot", type: 0x48 },
  { index: 0xc4, name: "Cold Blood", type: 0x81 },
  { index: 0xc5, name: "Wind Cutter", type: 0xe },
  { index: 0xc6, name: "Bone Eater", type: 0xe },
  { index: 0xc7, name: "Rumbling Sea", type: 0xe },
  { index: 0xc8, name: "Kusanagi", type: 0xe },
  { index: 0xc9, name: "Muramasa", type: 0xe },
  { index: 0xca, name: "Cross Shuriken", type: 0x4a },
  { index: 0xcb, name: "Fox Shuriken", type: 0x4a },
  { index: 0xcc, name: "Shaken", type: 0x4a },
  { index: 0xcd, name: "Spark Shuriken", type: 0x4a },
  { index: 0xce, name: "Octagon Star", type: 0x4a },
  { index: 0xcf, name: "Wind Shuriken", type: 0x4a },
  { index: 0xd0, name: "Metal Wing", type: 0xf },
  { index: 0xd1, name: "Silver Wing", type: 0xf },
  { index: 0xd2, name: "Battle Wing", type: 0xf },
  { index: 0xd3, name: "Sylph Wing", type: 0xf },
  { index: 0xd4, name: "Sonic Wing", type: 0xf },
  { index: 0xd5, name: "Cosmic Wing", type: 0xf },
  { index: 0xd6, name: "Zero Wing", type: 0xf },
  { index: 0xd7, name: "Stealth Wing", type: 0xf },
  { index: 0xd8, name: "Light Anchor", type: 0x21 },
  { index: 0xd9, name: "Heavy Anchor", type: 0x21 },
  { index: 0xda, name: "Power Anchor", type: 0x21 },
  { index: 0xdb, name: "Spin Anchor", type: 0x21 },
  { index: 0xdc, name: "Crash Anchor", type: 0x21 },
  { index: 0xdd, name: "Gravity Anchor", type: 0x21 },
  { index: 0xde, name: "Cut Flowers", type: 0x1 },
  { index: 0xdf, name: "Chicken Feed", type: 0x1 },
  { index: 0xe0, name: "Volcanon Wand", type: 0x3d },
  { index: 0xe1, name: "Large Egg", type: 0x1 },
  { index: 0xe2, name: "Ship Key", type: 0x1 },
  { index: 0xe3, name: "Statue Gem", type: 0x1 },
  { index: 0xe4, name: "Mitra Ankh", type: 0x3e },
  { index: 0xe5, name: "Saraband Key", type: 0x1 },
  { index: 0xe6, name: "Divine Cane", type: 0x3d },
  { index: 0xe7, name: "Hell Rod", type: 0x3c },
  { index: 0xe8, name: "Penko Beak", type: 0x50 },
  { index: 0xe9, name: "Gateway Map", type: 0x1 },
  { index: 0xea, name: "Cave Ruins Map", type: 0x1 },
  { index: 0xeb, name: "Mountain Map", type: 0x1 },
  { index: 0xec, name: "Dark Ruins Map", type: 0x1 },
  { index: 0xed, name: "Mine Map", type: 0x1 },
  { index: 0xee, name: "Armoury Map", type: 0x1 },
  { index: 0xef, name: "Elbesem Orb", type: 0x81 },
  { index: 0xf0, name: "Barrand Key", type: 0x1 },
  { index: 0xf1, name: "Robot Eye", type: 0x1 },
  { index: 0xf2, name: "Secret Key", type: 0x1 },
  { index: 0xf3, name: "Freeze Orb", type: 0x1 },
  { index: 0xf4, name: "God Rapier", type: 0xc },
  { index: 0xf5, name: "Thunder Wand", type: 0x3d },
  { index: 0xf6, name: "Dragon Rod", type: 0x3c },
  { index: 0xf7, name: "Earth Rod", type: 0x3c },
  { index: 0xf8, name: "Chain Whip", type: 0x5a },
  { index: 0xf9, name: "Queen Whip", type: 0x5a },
  { index: 0xfa, name: "Love Whip", type: 0x5a },
  { index: 0xfb, name: "Jester Whip", type: 0x5a },
  { index: 0xfc, name: "Silver Beak", type: 0x50 },
  { index: 0xfd, name: "Golden Beak", type: 0x50 },
  { index: 0xfe, name: "Penguin Beak", type: 0x50 },
  { index: 0x100, name: "Staff of Besem", type: 0x3f },
  { index: 0x101, name: "Unicorn Horn", type: 0x51 },
  { index: 0x102, name: "Unicorn Horn", type: 0x51 },
  { index: 0x103, name: "Dragon Talon", type: 0x52 },
  { index: 0x104, name: "Dragon Talon", type: 0x52 },
  { index: 0x105, name: "Reaper Knife", type: 0xa },
  { index: 0x106, name: "Lord Sword", type: 0xb },
  { index: 0x107, name: "Nebula Rapier", type: 0xc },
  { index: 0x108, name: "Varion Blade", type: 0xd },
  { index: 0x109, name: "Masamune", type: 0xe },
  { index: 0x10a, name: "Full Metal Wing", type: 0xf },
  { index: 0x10b, name: "Bozon Lance", type: 0x14 },
  { index: 0x10c, name: "Mercurius", type: 0x15 },
  { index: 0x10d, name: "Buster Halberd", type: 0x16 },
  { index: 0x10e, name: "Apollo Axe", type: 0x1e },
  { index: 0x10f, name: "Flame Hatchet", type: 0x1f },
  { index: 0x110, name: "Geo Hammer", type: 0x20 },
  { index: 0x111, name: "Plasma Anchor", type: 0x21 },
  { index: 0x112, name: "Gehenna Claw", type: 0x32 },
  { index: 0x113, name: "Cocytus Glove", type: 0x33 },
  { index: 0x114, name: "Aura Cestus", type: 0x34 },
  { index: 0x115, name: "Rod of Will", type: 0x3c },
  { index: 0x116, name: "Eternal Wand", type: 0x3d },
  { index: 0x117, name: "Golgotha Ankh", type: 0x3e },
  { index: 0x118, name: "Sagittarius", type: 0x46 },
  { index: 0x119, name: "Doppler Quarrel", type: 0x47 },
  { index: 0x11a, name: "Hot Rod Shell", type: 0x48 },
  { index: 0x11b, name: "Dark Shuriken", type: 0x4a },
  { index: 0x11c, name: "Rainbow Beak", type: 0x50 },
  { index: 0x11d, name: "Silk Whip", type: 0x5a },
  { index: 0x11e, name: "Orichalcum", type: 0x1 },
  { index: 0x11f, name: "Shining Sword", type: 0xb },
  { index: 0x120, name: "Ark Rapier", type: 0xc },
  { index: 0x121, name: "Dragonman Claw", type: 0x32 },
  { index: 0x122, name: "Chaos Blade", type: 0xd },
  { index: 0x123, name: "Raphael Ankh", type: 0x3e },
  { index: 0x124, name: "Abyss Wand", type: 0x3d },
  { index: 0x125, name: "Murasame", type: 0xe },
  { index: 0x126, name: "Divine Wind Fan", type: 0x1 },
  { index: 0x127, name: "Halberod", type: 0x16 },
  { index: 0x128, name: "Delicious Meat", type: 0x1 },
  { index: 0x129, name: "Chaos Mobius", type: 0x1 },
  { index: 0x12a, name: "Staff of Besem", type: 0x3f },
];

export const items = itemsDetails.reduce((items: Resource, item) => {
  items[item.index] = item.name;

  return items;
}, {});

export const locations = {
  0x0: "Opening Movie (OPMOVIE)",
  0x1: "Sleepy Wise Man (DREAM)",
  0x2: "COMPLETE (COMPLETE)",
  0x3: "Ending (ENDING)",
  0x4: "Flagship Deck (BTL301)",
  0x5: "Port of Destonia (BTL302)",
  0x6: "Destonia Castle Pass (BTL303)",
  0x7: "Destonia Castle Gate (BTL304)",
  0x8: "Great Cavern (BTL305)",
  0x9: "Dragon Graveyard (BTL306)",
  0xa: "Barrier Fortress Valley (BTL307)",
  0xb: "Barrier Fortress (BTL308)",
  0xc: "Guarder Archipelago (BTL309)",
  0xd: "Northern Great Lighthouse (BTL310)",
  0xe: "Baersol Coast (BTL311)",
  0xf: "North Baersol Plains (BTL312)",
  0x10: "Baersol Ruins (BTL313)",
  0x11: "North of the Great Wall (BTL314)",
  0x12: "River of a Thousand Miles (BTL315)",
  0x13: "Holy River (BTL316)",
  0x14: "Holy River Mountain Pass (BTL317)",
  0x15: "Maya After Dark (BTL318)",
  0x16: "Ark Hill - First Trial (BTL319)",
  0x17: "Ark Hill - Second Trial (BTL320)",
  0x18: "Outside Bowlet Cabin (BTL321)",
  0x19: "Bowlet Mountain Pass (BTL322)",
  0x1a: "Dormant Confluence (BTL323)",
  0x1b: "Dormant Cave (BTL324)",
  0x1c: "Dormant Volcano (BTL325)",
  0x1d: "Frozen Sea (BTL326)",
  0x1e: "Remotest Gate (BTL327)",
  0x1f: "Bulzome Temple Shrines (BTL328)",
  0x20: "Bulzome Temple (BTL329)",
  0x21: "Ruins of the Wise L1 (BTL330)",
  0x22: "Ruins of the Wise L2 (BTL331)",
  0x23: "Ruins of the Wise L4 (BTL332)",
  0x24: "Ruins of the Wise L6 (BTL333)",
  0x25: "Ruins of the Wise L8 (BTL334)",
  0x26: "Ruins of the Wise L9 (BTL335)",
  0x27: "Ruins of the Wise L10 (BTL336)",
  0x28: "Ruins of the Wise L3 (BTL337)",
  0x29: "Ruins of the Wise L5 (BTL338)",
  0x2a: "Ruins of the Wise L7 (BTL339)",
  0x2b: "Opening (HNSNOP)",
  0x2c: "Flagship Church (FNKA01)",
  0x2d: "Flagship HQ (FNKA_J)",
  0x2e: "Flagship Dragon Room (FNK1_J)",
  0x2f: "Flagship Event (HNEND2)",
  0x30: "Port of Destonia (D_PORT)",
  0x31: "Destonia Port Battle (HARBOR)",
  0x32: "Destonia Harbour (D_SAN)",
  0x33: "Destonia Refinery (D_FACT)",
  0x34: "Destonia Indoors (DST_I)",
  0x35: "Destonia HQ (DST_J)",
  0x36: "Destonia Church (DST_C)",
  0x37: "Destonia Plains (FED83)",
  0x38: "Foothill Village (FUTTO)",
  0x39: "Foothill Indoors (FUTTIN)",
  0x3a: "Foothill Church (FUTT_C)",
  0x3b: "Foothill HQ (FUTT_J)",
  0x3c: "Guarder (GUILD)",
  0x3d: "Guarder Indoors (GLRM01)",
  0x3e: "Oasis (GL_BAR)",
  0x3f: "Guarder Church (GL_C)",
  0x40: "Guarder HQ (GL_J)",
  0x41: "Baersol (BEER)",
  0x42: "Baersol Indoors (BEERIN)",
  0x43: "Baersol Manor (BUBBLE)",
  0x44: "Baersol Church (BEER_C)",
  0x45: "Baersol HQ (BEER_J)",
  0x46: "Guarder Island (FED89)",
  0x47: "West Aspia Plains (BTL19)",
  0x48: "Aspia Ramparts (ATBTL2)",
  0x49: "Aspia (S3C4OP)",
  0x4a: "Aspia (ASBRK3)",
  0x4b: "Aspia Castle Drawbridge (Z_AS)",
  0x4c: "Aspia Castle (ASCASL)",
  0x4d: "Aspia Roof (AS_OKU)",
  0x4e: "Aspia Indoors (A_RM01)",
  0x4f: "Aspia Indoors 2 (A_RM02)",
  0x50: "Aspia Meeting Room (AS_MEE)",
  0x51: "Aspia HQ (ASPI_H)",
  0x52: "Aspia Church (ASPI_C)",
  0x53: "North of the Great Wall (BTL24)",
  0x54: "Aural Village (OHRAL)",
  0x55: "Aural Indoors (OH_RM)",
  0x56: "Aural Cave (OHCAVE)",
  0x57: "Aural Church (OHRA_C)",
  0x58: "Aural HQ (OHRA_J)",
  0x59: "Maya Plains (FED97)",
  0x5a: "Bowlet Cabin (HOWLET)",
  0x5b: "Bowlet Cabin (HOWIN)",
  0x5c: "Bowlet HQ (HOW_J)",
  0x5d: "Maya Village (MAYA2)",
  0x5e: "Maya Indoors (MAYAIN)",
  0x5f: "Maya Elder's House (SONCHO)",
  0x60: "Sega Room (SC3000)",
  0x61: "Maya Church (MAYA_C)",
  0x62: "Maya HQ (MAYA_J)",
  0x63: "Maya Village (MAYA)",
  0x64: "Elder's House Roof (MAYAE1)",
  0x65: "Elder's House Roof 2 (MAYAE2)",
  0x66: "Dormant Village (DLMANT)",
  0x67: "Dormant Hot Spring (DLMAN2)",
  0x68: "Dormant Indoors (DLROOM)",
  0x69: "Dormant Church (DLMA_C)",
  0x6a: "Dormant {11}{0d} HQ (DLMA_J)",
  0x6b: "Dormant {11}{01} HQ (DLMA2J)",
  0x6c: "Flagship (FEDA5)",
  0x6d: "North Flagship Deck (HNKO00)",
  0x6e: "North Flagship Indoors (FNKA6)",
  0x6f: "North Flagship Dragon Room (FNK6_J)",
  0x70: "Remotest (LEMONC)",
  0x71: "Remotest Indoors (LEMIN1)",
  0x72: "Remotest Indoors 2 (LEMIN2)",
  0x73: "Remotest Church (LEMO_C)",
  0x74: "Remotest {11}{01} HQ (LEMO1J)",
  0x75: "Remotest {11}{15} HQ (LEMO2J)",
  0x76: "Remotest {11}{0d} HQ (LEMO3J)",
  0x77: "Remotest Great Temple (LECHA)",
  0x78: "Remotest Indoors 3 (LEMIN3)",
  0x79: "Remotest Indoors 4 (LEMIN4)",
  0x7a: "Remotest Great Temple 2 (LECHA2)",
  0x7b: "Remotest Church 2 (LEMO2C)",
  0x7c: "Ending (FEDEND)",
  0x7d: "Destonia Valley (IWAOKA)",
  0x7e: "Destonia Castle (DESUTO)",
  0x7f: "Destonia Castle Indoors (DESUO2)",
  0x80: "Great Cavern (DIDO00)",
  0x81: "Dragon Graveyard (DORA)",
  0x82: "Barrier Plains (BTL87)",
  0x83: "Barrier Fortress (BARRIE)",
  0x84: "Guarder Island (BTL89)",
  0x85: "Great Lighthouse Bridge (DAIDAI)",
  0x86: "Great Lighthouse (TODI00)",
  0x87: "Baersol Plains (BTL91)",
  0x88: "North Baersol Plains (BTL92)",
  0x89: "Baersol Ruins (BORO)",
  0x8a: "Northern Great Wall (SIGERU)",
  0x8b: "South Aural Plains (BTL95)",
  0x8c: "Maya Plains (BTL96)",
  0x8d: "Ark Hill Desert (BTLAHL)",
  0x8e: "Ark Hill Mountain Road (AHIRU)",
  0x8f: "Ark Hill Mountain Road 2 (AHIRU2)",
  0x90: "Ark Hill Temple (SNDN00)",
  0x91: "Bowlet Mountain Pass (SNRK00)",
  0x92: "South Dormant Plains (BTLA3)",
  0x93: "South Dormant Cave (SINKO)",
  0x94: "Volcanic Mountain Range (BTLA5)",
  0x95: "Frozen Sea (REMOTE)",
  0x96: "Remotest Gate (LEMON)",
  0x97: "West Shrine (NISI)",
  0x98: "East Shrine (HIGASI)",
  0x99: "Bulzome Temple (KUNIEI)",
  0x9a: "Bulzome Temple 2 (KANPO)",
  0x9b: "Bulzome Temple (JASN00)",
  0x9c: "Training Cave (SD_30)",
  0x9d: "Destonia Ruins (ZEEE)",
  0x9e: "Foothill Ruins (ZOKU)",
  0x9f: "Dormant Ruins (DEKA)",
  0xa0: "Baersol Ruins (TM_OC)",
  0xa1: "Darkness Ruins (YAMIDA)",
  0xa2: "Mine Ruins (TROCCO)",
  0xa3: "Special Battle (SPECIAL)",
  0xa4: "Epilogue (EPILOG)",
  0xa5: "Polygon Character Test (KANSHOU)",
  0xa6: "Measurement Test (TESMAP)",
  0xa7: "Store Test (SHOP_T)",
  0xa8: "Ryuta Test (TESTRYUTA)",
};

export const specialAttacks = {
  0x0: "-",
  0x1: "Critical Hit",
  0x2: "Counter",
  0x3: "Slow",
  0x4: "Sleep",
  0x5: "Confuse",
  0x6: "Illusion",
  0x7: "Dispel",
  0x8: "Paralyze",
  0x9: "Poison",
  0xa: "Poison",
  0xb: "Charm",
  0xc: "Cold",
  0xd: "Critical Hit",
  0xe: "Penetrate Armour",
  0xf: "Berserk",
  0x10: "Blood Sucker",
  0x11: "Regret Hit",
  // 0x12: "Not Set", // Unused
  // 0x13: "Not Set", // Unused
  0x14: "Shadow Edge",
  0x15: "Twin Slash",
  0x16: "Laser Edge",
  0x17: "Rainbow Edge",
  0x18: "Flash Kill",
  0x19: "Sonic Wave",
  0x1a: "Twin Wave",
  0x1b: "Mirage Dance",
  0x1c: "Thunder Shock",
  0x1d: "Heat Wave",
  0x1e: "Soul Eater",
  0x1f: "Dazzle Edge",
  0x20: "Triangle",
  0x21: "Pentagram",
  0x22: "Centurion",
  0x23: "Mist Feint",
  0x24: "Rune Magic",
  0x25: "Alchemy",
  0x26: "Das Ende",
  0x27: "After Burner",
  0x28: "Ice Breaker",
  0x29: "Dimension",
  0x2a: "Melt Armour",
  0x2b: "Light Cross",
  0x2c: "Light Sphere",
  0x2d: "Poison Blade",
  0x2e: "Force Edge",
  0x2f: "Lance Charge",
  0x30: "Super Charge",
  0x31: "Mega Charge",
  0x32: "Dragon Breath",
  0x33: "Death Charge",
  0x34: "Side Winder",
  0x35: "Energy Fall",
  0x36: "Thunder Fall",
  0x37: "Flash Gazer",
  0x38: "Meteor",
  0x39: "Tornado",
  0x3a: "Cross Break",
  0x3b: "Air Dance",
  0x3c: "Lord Rush",
  0x3d: "Lightning",
  0x3e: "Death Gate",
  0x3f: "Full Swing",
  0x40: "Power Wheel",
  0x41: "Mega Wheel",
  0x42: "Ragnarok",
  0x43: "Giga Wheel",
  0x44: "Death Wheel",
  0x45: "Power Throw",
  0x46: "Boomerang",
  0x47: "Vortex",
  0x48: "Fatal Strike",
  0x49: "Mist Storm",
  0x4a: "Power Crash",
  0x4b: "Stun Bomb",
  0x4c: "Earthquake",
  0x4d: "Thunder Storm",
  0x4e: "Pressure Bomb",
  0x4f: "Dragon Claw",
  0x50: "Sky Claw",
  0x51: "Sky Dragon",
  0x52: "Storm Fang",
  0x53: "Venom Fang",
  0x54: "Brutal Shock",
  0x55: "Bullet Heel",
  0x56: "Vortex Kick",
  0x57: "Sky Dance",
  0x58: "Heavenly Fire",
  0x59: "Jewel Palm",
  0x5a: "Fist O' Fury",
  0x5b: "Thunder Drop",
  0x5c: "Conquer King",
  0x5d: "Mirage Fist",
  0x5e: "Backstep Fist",
  0x5f: "Double Palm",
  0x60: "Stun Palm",
  0x61: "Panic Palm",
  0x62: "Ninth Gate",
  0x63: "Meta Dream",
  0x64: "Midas Strike",
  0x65: "Demon Breath",
  0x66: "Soul Shot",
  0x67: "Fairy Soul",
  0x68: "Soul Blast",
  0x69: "Fata Morgana",
  0x6a: "Fairy Lover",
  0x6b: "Stone Circle",
  0x6c: "Seal of Sin",
  0x6d: "Judgement",
  0x6e: "Apocalypse",
  0x6f: "Fool Prayer",
  0x70: "Holy Silence",
  0x71: "Apostle Descent",
  0x72: "Ice Arrow",
  0x73: "Hypno Arrow",
  0x74: "Drain Arrow",
  0x75: "Lunatic",
  0x76: "Dragon Snipe",
  0x77: "Spell Virus",
  0x78: "Poison Arrow",
  0x79: "Goddess Charm",
  0x7a: "Double Bolt",
  0x7b: "Sniper Bolt",
  0x7c: "Vulcan Bolt",
  0x7d: "Saint Flame",
  0x7e: "Hell Wind",
  0x7f: "Stun Needle",
  0x80: "Dazzle Shot",
  0x81: "Armour Shot",
  0x82: "Explode",
  0x83: "Desert Storm",
  0x84: "Planet Dance",
  0x85: "Schwarchshilt",
  0x86: "Butterfly Dance",
  0x87: "Izuna Drop",
  0x88: "Fine Mist",
  0x89: "Kamaitachi",
  0x8a: "Oni Hyakusoku",
  0x8b: "Umi Zato",
  0x8c: "Destruction",
  0x8d: "Road to Hades",
  0x8e: "Shadow Loom",
  0x8f: "Dark Raven",
  0x90: "Demon Circle",
  0x91: "Thunder Array",
  0x92: "Chaos Cauldron",
  0x93: "Evil Wind",
  0x94: "Twister",
  0x95: "Cross Slash",
  0x96: "Bloody Spin",
  0x97: "Hyper Boom",
  0x98: "Hell Dive",
  0x99: "Zero Count",
  0x9a: "Rocket Punch",
  0x9b: "Boost Punch",
  0x9c: "Nova Shot",
  0x9d: "Drill Smash",
  0x9e: "Hammer Throw",
  0x9f: "Gestalt",
  0xa0: "Penguin Kick",
  0xa1: "Penguin Butt",
  0xa2: "Volcano",
  0xa3: "Power Slash",
  0xa4: "Sky High",
  0xa5: "Eagle Dive",
  0xa6: "Power Feint",
  0xa7: "Double Feint",
  0xa8: "Danse Macabre",
  0xa9: "Wolf Fang",
  0xaa: "Wolf Rush",
  0xab: "Cork Screw",
  0xac: "Wild Blow",
  0xad: "Soul Spark",
  0xae: "Death Drive",
  0xaf: "Light Sphere",
  0xb0: "Star Bomb",
  0xb1: "Road Rush",
  0xb2: "Flame Tail",
  0xb3: "Melt Armour",
  0xb4: "Dominion Ray",
  0xb5: "Thunder Blow",
  0xb6: "Photon Rage",
  0xb7: "Dragon Breath",
  0xb8: "Air Fang",
  0xb9: "Wild Rush",
  0xba: "Soul Smash",
  0xbb: "Soul Gun",
  0xbc: "Maniac Beat",
  0xbd: "Mad Spin",
  0xbe: "Carousel",
  0xbf: "Slave Dance",
  0xc0: "Balloon Bomb",
  0xc1: "Penguin Flash",
  0xc2: "Penko Carnival",
  0xc3: "Plasma Shell",
  0xc4: "Tail Bomb",
  0xc5: "Breath Geyser",
  0xc6: "Fire Breath",
  0xc7: "Acid Breath",
  0xc8: "Panic",
  0xc9: "Bee Strike",
  0xca: "Queen Bee",
  0xcb: "Tail Bomb",
  0xcc: "Breath Geyser",
  0xcd: "Gigaton Press",
  0xce: "Unicorn Buck",
  0xcf: "Unicorn Ray",
  0xd0: "Stampede",
  0xd1: "Crescent Moon",
  0xd2: "Full Moon Blade",
  0xd3: "Instant Kill",
  0xd4: "Leprecannon",
  0xd5: "Dragon Fang",
  0xd6: "Dragon Rush",
  0xd7: "Dragon Soul",
  0xd8: "Vacuum Wave",
  0xd9: "Pendolf Vacuum",
  0xda: "Rocket Anchor",
  0xdb: "Burst Anchor",
  0xdc: "Godly Claw",
  0xdd: "Claw Wave",
  0xde: "Heavenly Light",
  0xdf: "Thunder Breath",
  0xe0: "Virgo",
  0xe1: "Blood Sucker",
  0xe2: "Gold Rush",
  0xe3: "Helical Spin",
  0xe4: "Elemental Flare",
  0xe5: "Frost Blade",
  0xe6: "Metal Jacket",
  0xe7: "Mega Reaper",
  0xe8: "Salamander",
  0xe9: "Gorgon Buster",
  0xea: "Corona Wheel",
  0xeb: "Heat Cyclone",
  0xec: "Geo Spark",
  0xed: "Soul Grapple",
  0xee: "Reincarnation",
  0xef: "Phase Inversion",
  0xf0: "Dragon Wave",
  0xf1: "Ruled Heaven",
  0xf2: "Tachyon Shot",
  0xf3: "Thorn Crown",
  0xf4: "Stardust",
  0xf5: "Prism Ray",
  0xf6: "Muzzle Blast",
  0xf7: "Dark Demon",
  0xf8: "Expander",
  0xf9: "Beast Bash",
  0xfa: "Mirage Round",
  0xfb: "Absolute Zero",
  0xfc: "Blizzard Breath",
  0xfd: "Hell Napalm",
};

export const spells = {
  0x0: "-",
  0x1: "Blaze",
  0x2: "Freeze",
  0x3: "Spark",
  0x4: "Tornado",
  0x5: "Soul Steal",
  0x6: "Inferno",
  0x7: "Support",
  0x8: "Slow",
  0x9: "Shining",
  0xa: "Resist",
  0xb: "Attack",
  0xc: "Dispel",
  0xd: "Confuse",
  0xe: "Sleep",
  0xf: "Charm",
  0x10: "Drain",
  0x11: "Heal",
  0x12: "Aura",
  0x13: "Chant",
  0x14: "Antidote",
  0x15: "Egress",
  0x26: "Phoenix",
  0x27: "Wendigo",
  0x28: "Tiamat",
  0x29: "Thanatos",
  0x34: "Thor",
  0x35: "Zephyrus",
  0x36: "Golem",
  0x37: "Hell Dragon",
  0x3b: "Fake Charm",
  0x3e: "Proserpina",
  0x3f: "Demon King",
  0x40: "Penko",
  0x41: "Penn",
  0x43: "Wind Storm",
  0x44: "Keppyoudo",
  0x46: "Blessing",
  0x47: "Chaos Gate",
};

export const itemTypes = {
  0x1: "Items",
  0xa: "Knifes",
  0xb: "Swords",
  0xc: "Rapiers",
  0xd: "Blades",
  0xe: "Katanas",
  0xf: "Wings",
  0x14: "Lances",
  0x15: "Spears",
  0x16: "Halberds",
  0x1e: "Axes",
  0x1f: "Tomahawks",
  0x20: "Maces",
  0x21: "Anchors",
  0x32: "Claws",
  0x33: "Gloves",
  0x34: "Cestus",
  0x3c: "Rods",
  0x3d: "Wands",
  0x3e: "Ankhs",
  0x3f: "Staffs",
  0x46: "Arrows",
  0x47: "Quarrels",
  0x48: "Shells",
  0x4a: "Shurikens",
  0x50: "Beaks",
  0x51: "Horns",
  0x52: "Talons",
  0x5a: "Whips",
  0x7a: "Bracers",
  0x7b: "Tiaras",
  0x7c: "Helmets",
  0x81: "Accessories",
};

export const weaponTypes = {
  0xa: "Knife",
  0xb: "Sword",
  0xc: "Rapier",
  0xd: "Blade",
  0xe: "Katana",
  0xf: "Wing",
  0x14: "Lance",
  0x15: "Spear",
  0x16: "Halberd",
  0x1e: "Axe",
  0x1f: "Tomahawk",
  0x20: "Mace",
  0x21: "Anchor",
  0x32: "Claw",
  0x33: "Glove",
  0x34: "Cestus",
  0x3c: "Rod",
  0x3d: "Wand",
  0x3e: "Ankh",
  0x3f: "Staff",
  0x46: "Arrow",
  0x47: "Quarrel",
  0x48: "Shell",
  0x4a: "Shuriken",
  0x50: "Beak",
  0x51: "Horn",
  0x52: "Talon",
  0x5a: "Whip",
};
