import { getMoveList } from "$lib/utils/pokemon/move";
import { getPokemonList } from "$lib/utils/pokemon/pokemon";

import type { Resource, ResourceGroups } from "$lib/types";

const itemTypes = [
  { index: 0x0, name: "Poké Balls" },
  { index: 0x1, name: "Medicine" },
  { index: 0x2, name: "Berries" },
  { index: 0x3, name: "Apricorns" },
  { index: 0x4, name: "Battle Items" },
  { index: 0x5, name: "Vitamins" },
  { index: 0x6, name: "Evolution Items" },
  { index: 0x7, name: "Held Items" },
  { index: 0x8, name: "Mails" },
  { index: 0x9, name: "Miscellaneous" },
  { index: 0xa, name: "Key Items" },
  { index: 0xb, name: "TMs" },
  { index: 0xc, name: "HMs" },
];

// prettier-ignore
export const itemList = [
  { index: 0x1, name: "Master Ball", location: 0x1, type: 0x0, order: 11 },
  { index: 0x2, name: "Ultra Ball", location: 0x1, type: 0x0, order: 2 },
  { index: 0x3, name: "Brightpowder", location: 0x0, type: 0x7, order: 85 },
  { index: 0x4, name: "Great Ball", location: 0x1, type: 0x0, order: 1 },
  { index: 0x5, name: "Poké Ball", location: 0x1, type: 0x0, order: 0 },
  // { index: 0x6, name: "Teru-Sama" },
  { index: 0x7, name: "Bicycle", location: 0x2, type: 0xa, order: 143 },
  { index: 0x8, name: "Moon Stone", location: 0x0, type: 0x6, order: 75 },
  { index: 0x9, name: "Antidote", location: 0x0, type: 0x1, order: 24 },
  { index: 0xa, name: "Burn Heal", location: 0x0, type: 0x1, order: 26 },
  { index: 0xb, name: "Ice Heal", location: 0x0, type: 0x1, order: 27 },
  { index: 0xc, name: "Awakening", location: 0x0, type: 0x1, order: 25 },
  { index: 0xd, name: "Parlyz Heal", location: 0x0, type: 0x1, order: 28 },
  { index: 0xe, name: "Full Restore", location: 0x0, type: 0x1, order: 16 },
  { index: 0xf, name: "Max Potion", location: 0x0, type: 0x1, order: 15 },
  { index: 0x10, name: "Hyper Potion", location: 0x0, type: 0x1, order: 14 },
  { index: 0x11, name: "Super Potion", location: 0x0, type: 0x1, order: 13 },
  { index: 0x12, name: "Potion", location: 0x0, type: 0x1, order: 12 },
  { index: 0x13, name: "Escape Rope", location: 0x0, type: 0x9, order: 125 },
  { index: 0x14, name: "Repel", location: 0x0, type: 0x9, order: 126 },
  { index: 0x15, name: "Max Elixer", location: 0x0, type: 0x1, order: 20 },
  { index: 0x16, name: "Fire Stone", location: 0x0, type: 0x6, order: 71 },
  { index: 0x17, name: "Thunder Stone", location: 0x0, type: 0x6, order: 74 },
  { index: 0x18, name: "Water Stone", location: 0x0, type: 0x6, order: 72 },
  // { index: 0x19, name: "Teru-Sama" },
  { index: 0x1a, name: "HP Up", location: 0x0, type: 0x5, order: 64 },
  { index: 0x1b, name: "Protein", location: 0x0, type: 0x5, order: 66 },
  { index: 0x1c, name: "Iron", location: 0x0, type: 0x5, order: 67 },
  { index: 0x1d, name: "Carbos", location: 0x0, type: 0x5, order: 68 },
  { index: 0x1e, name: "Lucky Punch", location: 0x0, type: 0x7, order: 96 },
  { index: 0x1f, name: "Calcium", location: 0x0, type: 0x5, order: 69 },
  { index: 0x20, name: "Rare Candy", location: 0x0, type: 0x5, order: 70 },
  { index: 0x21, name: "X Accuracy", location: 0x0, type: 0x4, order: 61 },
  { index: 0x22, name: "Leaf Stone", location: 0x0, type: 0x6, order: 73 },
  { index: 0x23, name: "Metal Powder", location: 0x0, type: 0x7, order: 98 },
  { index: 0x24, name: "Nugget", location: 0x0, type: 0x9, order: 136 },
  { index: 0x25, name: "Poké Doll", location: 0x0, type: 0x9, order: 129 },
  { index: 0x26, name: "Full Heal", location: 0x0, type: 0x1, order: 29 },
  { index: 0x27, name: "Revive", location: 0x0, type: 0x1, order: 21 },
  { index: 0x28, name: "Max Revive", location: 0x0, type: 0x1, order: 22 },
  { index: 0x29, name: "Guard Spec.", location: 0x0, type: 0x4, order: 63 },
  { index: 0x2a, name: "Super Repel", location: 0x0, type: 0x9, order: 127 },
  { index: 0x2b, name: "Max Repel", location: 0x0, type: 0x9, order: 128 },
  { index: 0x2c, name: "Dire Hit", location: 0x0, type: 0x4, order: 62 },
  // { index: 0x2d, name: "Teru-Sama" },
  { index: 0x2e, name: "Fresh Water", location: 0x0, type: 0x1, order: 31 },
  { index: 0x2f, name: "Soda Pop", location: 0x0, type: 0x1, order: 32 },
  { index: 0x30, name: "Lemonade", location: 0x0, type: 0x1, order: 33 },
  { index: 0x31, name: "X Attack", location: 0x0, type: 0x4, order: 57 },
  // { index: 0x32, name: "Teru-Sama" },
  { index: 0x33, name: "X Defend", location: 0x0, type: 0x4, order: 58 },
  { index: 0x34, name: "X Speed", location: 0x0, type: 0x4, order: 59 },
  { index: 0x35, name: "X Special", location: 0x0, type: 0x4, order: 60 },
  { index: 0x36, name: "Coin Case", location: 0x2, type: 0xa, order: 151 },
  { index: 0x37, name: "Item Finder", location: 0x2, type: 0xa, order: 154 },
  // { index: 0x38, name: "Teru-Sama" },
  { index: 0x39, name: "Exp. Share", location: 0x0, type: 0x7, order: 90 },
  { index: 0x3a, name: "Old Rod", location: 0x2, type: 0xa, order: 144 },
  { index: 0x3b, name: "Good Rod", location: 0x2, type: 0xa, order: 145 },
  { index: 0x3c, name: "Silver Leaf", location: 0x0, type: 0x9, order: 138 },
  { index: 0x3d, name: "Super Rod", location: 0x2, type: 0xa, order: 146 },
  { index: 0x3e, name: "PP Up", location: 0x0, type: 0x5, order: 65 },
  { index: 0x3f, name: "Ether", location: 0x0, type: 0x1, order: 17 },
  { index: 0x40, name: "Max Ether", location: 0x0, type: 0x1, order: 18 },
  { index: 0x41, name: "Elixer", location: 0x0, type: 0x1, order: 19 },
  { index: 0x42, name: "Red Scale", location: 0x2, type: 0xa, order: 160 },
  { index: 0x43, name: "Secret Potion", location: 0x2, type: 0xa, order: 162 },
  { index: 0x44, name: "S.S. Ticket", location: 0x2, type: 0xa, order: 161 },
  { index: 0x45, name: "Mystery Egg", location: 0x2, type: 0xa, order: 157 },
  { index: 0x46, name: "Clear Bell", location: 0x2, type: 0xa, order: 150, crystal: true },
  { index: 0x47, name: "Silver Wing", location: 0x2, type: 0xa, order: 163 },
  { index: 0x48, name: "Moomoo Milk", location: 0x0, type: 0x1, order: 34 },
  { index: 0x49, name: "Quick Claw", location: 0x0, type: 0x7, order: 105 },
  { index: 0x4a, name: "Poisoncure Berry", location: 0x0, type: 0x2, order: 49 },
  { index: 0x4b, name: "Gold Leaf", location: 0x0, type: 0x9, order: 135 },
  { index: 0x4c, name: "Soft Sand", location: 0x0, type: 0x7, order: 110 },
  { index: 0x4d, name: "Sharp Beak", location: 0x0, type: 0x7, order: 107 },
  { index: 0x4e, name: "Paralyzecure Berry", location: 0x0, type: 0x2, order: 48 },
  { index: 0x4f, name: "Burnt Berry", location: 0x0, type: 0x2, order: 42 },
  { index: 0x50, name: "Ice Berry", location: 0x0, type: 0x2, order: 44 },
  { index: 0x51, name: "Poison Barb", location: 0x0, type: 0x7, order: 103 },
  { index: 0x52, name: "King's Rock", location: 0x0, type: 0x6, order: 79 },
  { index: 0x53, name: "Bitter Berry", location: 0x0, type: 0x2, order: 41 },
  { index: 0x54, name: "Mint Berry", location: 0x0, type: 0x2, order: 45 },
  { index: 0x55, name: "Red Apricorn", location: 0x0, type: 0x3, order: 54 },
  { index: 0x56, name: "Tiny Mushroom", location: 0x0, type: 0x9, order: 142 },
  { index: 0x57, name: "Big Mushroom", location: 0x0, type: 0x9, order: 132 },
  { index: 0x58, name: "Silver Powder", location: 0x0, type: 0x7, order: 108 },
  { index: 0x59, name: "Blue Apricorn", location: 0x0, type: 0x3, order: 51 },
  // { index: 0x5a, name: "Teru-Sama" },
  { index: 0x5b, name: "Amulet Coin", location: 0x0, type: 0x7, order: 81 },
  { index: 0x5c, name: "Yellow Apricorn", location: 0x0, type: 0x3, order: 56 },
  { index: 0x5d, name: "Green Apricorn", location: 0x0, type: 0x3, order: 52 },
  { index: 0x5e, name: "Cleanse Tag", location: 0x0, type: 0x7, order: 87 },
  { index: 0x5f, name: "Mystic Water", location: 0x0, type: 0x7, order: 100 },
  { index: 0x60, name: "Twisted Spoon", location: 0x0, type: 0x7, order: 114 },
  { index: 0x61, name: "White Apricorn", location: 0x0, type: 0x3, order: 55 },
  { index: 0x62, name: "Blackbelt", location: 0x0, type: 0x7, order: 84 },
  { index: 0x63, name: "Black Apricorn", location: 0x0, type: 0x3, order: 50 },
  // { index: 0x64, name: "Teru-Sama" },
  { index: 0x65, name: "Pink Apricorn", location: 0x0, type: 0x3, order: 53 },
  { index: 0x66, name: "Black Glasses", location: 0x0, type: 0x7, order: 83 },
  { index: 0x67, name: "Slowpoke Tail", location: 0x0, type: 0x9, order: 139 },
  { index: 0x68, name: "Pink Bow", location: 0x0, type: 0x7, order: 102 },
  { index: 0x69, name: "Stick", location: 0x0, type: 0x7, order: 112 },
  { index: 0x6a, name: "Smoke Ball", location: 0x0, type: 0x7, order: 109 },
  { index: 0x6b, name: "Never-Melt Ice", location: 0x0, type: 0x7, order: 101 },
  { index: 0x6c, name: "Magnet", location: 0x0, type: 0x7, order: 97 },
  { index: 0x6d, name: "Miracle Berry", location: 0x0, type: 0x2, order: 46 },
  { index: 0x6e, name: "Pearl", location: 0x0, type: 0x9, order: 137 },
  { index: 0x6f, name: "Big Pearl", location: 0x0, type: 0x9, order: 133 },
  { index: 0x70, name: "Everstone", location: 0x0, type: 0x7, order: 89 },
  { index: 0x71, name: "Spell Tag", location: 0x0, type: 0x7, order: 111 },
  { index: 0x72, name: "Rage Candy Bar", location: 0x0, type: 0x1, order: 35 },
  { index: 0x73, name: "GS Ball", location: 0x2, type: 0xa, order: 153, crystal: true },
  { index: 0x74, name: "Blue Card", location: 0x2, type: 0xa, order: 148, crystal: true },
  { index: 0x75, name: "Miracle Seed", location: 0x0, type: 0x7, order: 99 },
  { index: 0x76, name: "Thick Club", location: 0x0, type: 0x7, order: 113 },
  { index: 0x77, name: "Focus Band", location: 0x0, type: 0x7, order: 91 },
  // { index: 0x78, name: "Teru-Sama" },
  { index: 0x79, name: "Energypowder", location: 0x0, type: 0x1, order: 36 },
  { index: 0x7a, name: "Energy Root", location: 0x0, type: 0x1, order: 37 },
  { index: 0x7b, name: "Heal Powder", location: 0x0, type: 0x1, order: 38 },
  { index: 0x7c, name: "Revival Herb", location: 0x0, type: 0x1, order: 39 },
  { index: 0x7d, name: "Hard Stone", location: 0x0, type: 0x7, order: 92 },
  { index: 0x7e, name: "Lucky Egg", location: 0x0, type: 0x7, order: 95 },
  { index: 0x7f, name: "Card Key", location: 0x2, type: 0xa, order: 149 },
  { index: 0x80, name: "Machine Part", location: 0x2, type: 0xa, order: 156 },
  { index: 0x81, name: "Egg Ticket", location: 0x2, type: 0xa, order: 152, crystal: true },
  { index: 0x82, name: "Lost Item", location: 0x2, type: 0xa, order: 155 },
  { index: 0x83, name: "Stardust", location: 0x0, type: 0x9, order: 141 },
  { index: 0x84, name: "Star Piece", location: 0x0, type: 0x9, order: 140 },
  { index: 0x85, name: "Basement Key", location: 0x2, type: 0xa, order: 147 },
  { index: 0x86, name: "Pass", location: 0x2, type: 0xa, order: 158 },
  // { index: 0x87, name: "Teru-Sama" },
  // { index: 0x88, name: "Teru-Sama" },
  // { index: 0x89, name: "Teru-Sama" },
  { index: 0x8a, name: "Charcoal", location: 0x0, type: 0x7, order: 86 },
  { index: 0x8b, name: "Berry Juice", location: 0x0, type: 0x1, order: 30 },
  { index: 0x8c, name: "Scope Lens", location: 0x0, type: 0x7, order: 106 },
  // { index: 0x8d, name: "Teru-Sama" },
  // { index: 0x8e, name: "Teru-Sama" },
  { index: 0x8f, name: "Metal Coat", location: 0x0, type: 0x6, order: 80 },
  { index: 0x90, name: "Dragon Fang", location: 0x0, type: 0x7, order: 88 },
  // { index: 0x91, name: "Teru-Sama" },
  { index: 0x92, name: "Leftovers", location: 0x0, type: 0x7, order: 93 },
  // { index: 0x93, name: "Teru-Sama" },
  // { index: 0x94, name: "Teru-Sama" },
  // { index: 0x95, name: "Teru-Sama" },
  { index: 0x96, name: "Mystery Berry", location: 0x0, type: 0x2, order: 47 },
  { index: 0x97, name: "Dragon Scale", location: 0x0, type: 0x6, order: 78 },
  { index: 0x98, name: "Berserk Gene", location: 0x0, type: 0x7, order: 82 },
  // { index: 0x99, name: "Teru-Sama" },
  // { index: 0x9a, name: "Teru-Sama" },
  // { index: 0x9b, name: "Teru-Sama" },
  { index: 0x9c, name: "Sacred Ash", location: 0x0, type: 0x1, order: 23 },
  { index: 0x9d, name: "Heavy Ball", location: 0x1, type: 0x0, order: 5 },
  { index: 0x9e, name: "Flower Mail", location: 0x0, type: 0x8, order: 117 },
  { index: 0x9f, name: "Level Ball", location: 0x1, type: 0x0, order: 6 },
  { index: 0xa0, name: "Lure Ball", location: 0x1, type: 0x0, order: 8 },
  { index: 0xa1, name: "Fast Ball", location: 0x1, type: 0x0, order: 3 },
  // { index: 0xa2, name: "Teru-Sama" },
  { index: 0xa3, name: "Light Ball", location: 0x0, type: 0x7, order: 94 },
  { index: 0xa4, name: "Friend Ball", location: 0x1, type: 0x0, order: 4 },
  { index: 0xa5, name: "Moon Ball", location: 0x1, type: 0x0, order: 9 },
  { index: 0xa6, name: "Love Ball", location: 0x1, type: 0x0, order: 7 },
  { index: 0xa7, name: "Normal Box", location: 0x0, type: 0x9, order: 130 },
  { index: 0xa8, name: "Gorgeous Box", location: 0x0, type: 0x9, order: 131 },
  { index: 0xa9, name: "Sun Stone", location: 0x0, type: 0x6, order: 76 },
  { index: 0xaa, name: "Polkadot Bow", location: 0x0, type: 0x7, order: 104 },
  // { index: 0xab, name: "Teru-Sama" },
  { index: 0xac, name: "Up-Grade", location: 0x0, type: 0x6, order: 77 },
  { index: 0xad, name: "Berry", location: 0x0, type: 0x2, order: 40 },
  { index: 0xae, name: "Gold Berry", location: 0x0, type: 0x2, order: 43 },
  { index: 0xaf, name: "Squirt Bottle", location: 0x2, type: 0xa, order: 164 },
  // { index: 0xb0, name: "Teru-Sama" },
  { index: 0xb1, name: "Park Ball", location: 0x1, type: 0x0, order: 10 },
  { index: 0xb2, name: "Rainbow Wing", location: 0x2, type: 0xa, order: 159 },
  // { index: 0xb3, name: "Teru-Sama" },
  { index: 0xb4, name: "Brick Piece", location: 0x0, type: 0x9, order: 134 },
  { index: 0xb5, name: "Surf Mail", location: 0x0, type: 0x8, order: 124 },
  { index: 0xb6, name: "Light-Blue Mail", location: 0x0, type: 0x8, order: 118 },
  { index: 0xb7, name: "Portrait Mail", location: 0x0, type: 0x8, order: 123 },
  { index: 0xb8, name: "Lovely Mail", location: 0x0, type: 0x8, order: 119 },
  { index: 0xb9, name: "Eon Mail", location: 0x0, type: 0x8, order: 116 },
  { index: 0xba, name: "Morph Mail", location: 0x0, type: 0x8, order: 121 },
  { index: 0xbb, name: "Blue Sky Mail", location: 0x0, type: 0x8, order: 115 },
  { index: 0xbc, name: "Music Mail", location: 0x0, type: 0x8, order: 122 },
  { index: 0xbd, name: "Mirage Mail", location: 0x0, type: 0x8, order: 120 },
  // { index: 0xbe, name: "Teru-Sama" },
  { index: 0xbf, name: "TM01 Dynamic Punch", location: 0x3, type: 0xb, order: 165 },
  { index: 0xc0, name: "TM02 Headbutt", location: 0x3, type: 0xb, order: 166 },
  { index: 0xc1, name: "TM03 Curse", location: 0x3, type: 0xb, order: 167 },
  { index: 0xc2, name: "TM04 Rollout", location: 0x3, type: 0xb, order: 168 },
  // { index: 0xc3, name: "Teru-Sama" },
  { index: 0xc4, name: "TM05 Roar", location: 0x3, type: 0xb, order: 169 },
  { index: 0xc5, name: "TM06 Toxic", location: 0x3, type: 0xb, order: 170 },
  { index: 0xc6, name: "TM07 Zap Cannon", location: 0x3, type: 0xb, order: 171 },
  { index: 0xc7, name: "TM08 Rock Smash", location: 0x3, type: 0xb, order: 172 },
  { index: 0xc8, name: "TM09 Psych Up", location: 0x3, type: 0xb, order: 173 },
  { index: 0xc9, name: "TM10 Hidden Power", location: 0x3, type: 0xb, order: 174 },
  { index: 0xca, name: "TM11 Sunny Day", location: 0x3, type: 0xb, order: 175 },
  { index: 0xcb, name: "TM12 Sweet Scent", location: 0x3, type: 0xb, order: 176 },
  { index: 0xcc, name: "TM13 Snore", location: 0x3, type: 0xb, order: 177 },
  { index: 0xcd, name: "TM14 Blizzard", location: 0x3, type: 0xb, order: 178 },
  { index: 0xce, name: "TM15 Hyper Beam", location: 0x3, type: 0xb, order: 179 },
  { index: 0xcf, name: "TM16 Icy Wind", location: 0x3, type: 0xb, order: 180 },
  { index: 0xd0, name: "TM17 Protect", location: 0x3, type: 0xb, order: 181 },
  { index: 0xd1, name: "TM18 Rain Dance", location: 0x3, type: 0xb, order: 182 },
  { index: 0xd2, name: "TM19 Giga Drain", location: 0x3, type: 0xb, order: 183 },
  { index: 0xd3, name: "TM20 Endure", location: 0x3, type: 0xb, order: 184 },
  { index: 0xd4, name: "TM21 Frustration", location: 0x3, type: 0xb, order: 185 },
  { index: 0xd5, name: "TM22 Solar Beam", location: 0x3, type: 0xb, order: 186 },
  { index: 0xd6, name: "TM23 Iron Tail", location: 0x3, type: 0xb, order: 187 },
  { index: 0xd7, name: "TM24 Dragon Breath", location: 0x3, type: 0xb, order: 188 },
  { index: 0xd8, name: "TM25 Thunder", location: 0x3, type: 0xb, order: 189 },
  { index: 0xd9, name: "TM26 Earthquake", location: 0x3, type: 0xb, order: 190 },
  { index: 0xda, name: "TM27 Return", location: 0x3, type: 0xb, order: 191 },
  { index: 0xdb, name: "TM28 Dig", location: 0x3, type: 0xb, order: 192 },
  // { index: 0xdc, name: "Teru-Sama" },
  { index: 0xdd, name: "TM29 Psychic", location: 0x3, type: 0xb, order: 193 },
  { index: 0xde, name: "TM30 Shadow Ball", location: 0x3, type: 0xb, order: 194 },
  { index: 0xdf, name: "TM31 Mud-Slap", location: 0x3, type: 0xb, order: 195 },
  { index: 0xe0, name: "TM32 Double Team", location: 0x3, type: 0xb, order: 196 },
  { index: 0xe1, name: "TM33 Ice Punch", location: 0x3, type: 0xb, order: 197 },
  { index: 0xe2, name: "TM34 Swagger", location: 0x3, type: 0xb, order: 198 },
  { index: 0xe3, name: "TM35 Sleep Talk", location: 0x3, type: 0xb, order: 199 },
  { index: 0xe4, name: "TM36 Sludge Bomb", location: 0x3, type: 0xb, order: 200 },
  { index: 0xe5, name: "TM37 Sandstorm", location: 0x3, type: 0xb, order: 201 },
  { index: 0xe6, name: "TM38 Fire Blast", location: 0x3, type: 0xb, order: 202 },
  { index: 0xe7, name: "TM39 Swift", location: 0x3, type: 0xb, order: 203 },
  { index: 0xe8, name: "TM40 Defense Curl", location: 0x3, type: 0xb, order: 204 },
  { index: 0xe9, name: "TM41 Thunder Punch", location: 0x3, type: 0xb, order: 205 },
  { index: 0xea, name: "TM42 Dream Eater", location: 0x3, type: 0xb, order: 206 },
  { index: 0xeb, name: "TM43 Detect", location: 0x3, type: 0xb, order: 207 },
  { index: 0xec, name: "TM44 Rest", location: 0x3, type: 0xb, order: 208 },
  { index: 0xed, name: "TM45 Attract", location: 0x3, type: 0xb, order: 209 },
  { index: 0xee, name: "TM46 Thief", location: 0x3, type: 0xb, order: 210 },
  { index: 0xef, name: "TM47 Steel Wing", location: 0x3, type: 0xb, order: 211 },
  { index: 0xf0, name: "TM48 Fire Punch", location: 0x3, type: 0xb, order: 212 },
  { index: 0xf1, name: "TM49 Fury Cutter", location: 0x3, type: 0xb, order: 213 },
  { index: 0xf2, name: "TM50 Nightmare", location: 0x3, type: 0xb, order: 214 },
  { index: 0xf3, name: "HM01 Cut", location: 0x3, type: 0xc, order: 215 },
  { index: 0xf4, name: "HM02 Fly", location: 0x3, type: 0xc, order: 216 },
  { index: 0xf5, name: "HM03 Surf", location: 0x3, type: 0xc, order: 217 },
  { index: 0xf6, name: "HM04 Strength", location: 0x3, type: 0xc, order: 218 },
  { index: 0xf7, name: "HM05 Flash", location: 0x3, type: 0xc, order: 219 },
  { index: 0xf8, name: "HM06 Whirlpool", location: 0x3, type: 0xc, order: 220 },
  { index: 0xf9, name: "HM07 Waterfall", location: 0x3, type: 0xc, order: 221 },
  // { index: 0xfa, name: "Teru-Sama" },
  // { index: 0xfb, name: "Teru-Sama" },
  // { index: 0xfc, name: "Teru-Sama" },
  // { index: 0xfd, name: "Teru-Sama" },
  // { index: 0xfe, name: "Teru-Sama" },
];

export const bagItems: Resource = {};
export const items: Resource = {};
export const keyItems: Resource = {};
export const mails: Resource = {};
export const pokeballs: Resource = {};

export const bagItemsOrder: number[] = [0x0];
export const itemsOrder: number[] = [0x0];
export const keyItemsOrder: number[] = [0x0];
export const pokeballsOrder: number[] = [0x0];

export const bagItemsGroups: ResourceGroups = itemTypes.map((type) => ({
  name: type.name,
  options: [],
}));
export const itemsGroups: ResourceGroups = itemTypes.map((type) => ({
  name: type.name,
  options: [],
}));

itemList
  .sort((a, b) => a.order - b.order)
  .forEach((item) => {
    items[item.index] = item.name;
    itemsOrder.push(item.index);
    itemsGroups[item.type].options.push(item.index);

    if (item.type === 0x8) {
      mails[item.index] = item.name;
    }

    switch (item.location) {
      case 0x0:
        bagItems[item.index] = item.name;
        bagItemsOrder.push(item.index);
        bagItemsGroups[item.type].options.push(item.index);
        break;
      case 0x1:
        pokeballs[item.index] = item.name;
        pokeballsOrder.push(item.index);
        break;
      case 0x2:
        keyItems[item.index] = item.name;
        keyItemsOrder.push(item.index);
        break;
    }
  });

export const moveList = getMoveList(2);

export const moves = moveList.reduce((moves: Resource, move) => {
  moves[move.index] = move.name;

  return moves;
}, {});

const pokemonNames = getPokemonList(2);

export const pokemonList = [
  { index: 0x1, name: pokemonNames[0], genderThreshold: 2 },
  { index: 0x2, name: pokemonNames[1], genderThreshold: 2 },
  { index: 0x3, name: pokemonNames[2], genderThreshold: 2 },
  { index: 0x4, name: pokemonNames[3], genderThreshold: 2 },
  { index: 0x5, name: pokemonNames[4], genderThreshold: 2 },
  { index: 0x6, name: pokemonNames[5], genderThreshold: 2 },
  { index: 0x7, name: pokemonNames[6], genderThreshold: 2 },
  { index: 0x8, name: pokemonNames[7], genderThreshold: 2 },
  { index: 0x9, name: pokemonNames[8], genderThreshold: 2 },
  { index: 0xa, name: pokemonNames[9], genderThreshold: 8 },
  { index: 0xb, name: pokemonNames[10], genderThreshold: 8 },
  { index: 0xc, name: pokemonNames[11], genderThreshold: 8 },
  { index: 0xd, name: pokemonNames[12], genderThreshold: 8 },
  { index: 0xe, name: pokemonNames[13], genderThreshold: 8 },
  { index: 0xf, name: pokemonNames[14], genderThreshold: 8 },
  { index: 0x10, name: pokemonNames[15], genderThreshold: 8 },
  { index: 0x11, name: pokemonNames[16], genderThreshold: 8 },
  { index: 0x12, name: pokemonNames[17], genderThreshold: 8 },
  { index: 0x13, name: pokemonNames[18], genderThreshold: 8 },
  { index: 0x14, name: pokemonNames[19], genderThreshold: 8 },
  { index: 0x15, name: pokemonNames[20], genderThreshold: 8 },
  { index: 0x16, name: pokemonNames[21], genderThreshold: 8 },
  { index: 0x17, name: pokemonNames[22], genderThreshold: 8 },
  { index: 0x18, name: pokemonNames[23], genderThreshold: 8 },
  { index: 0x19, name: pokemonNames[24], genderThreshold: 8 },
  { index: 0x1a, name: pokemonNames[25], genderThreshold: 8 },
  { index: 0x1b, name: pokemonNames[26], genderThreshold: 8 },
  { index: 0x1c, name: pokemonNames[27], genderThreshold: 8 },
  { index: 0x1d, name: pokemonNames[28], genderThreshold: 16 },
  { index: 0x1e, name: pokemonNames[29], genderThreshold: 16 },
  { index: 0x1f, name: pokemonNames[30], genderThreshold: 16 },
  { index: 0x20, name: pokemonNames[31], genderThreshold: 0 },
  { index: 0x21, name: pokemonNames[32], genderThreshold: 0 },
  { index: 0x22, name: pokemonNames[33], genderThreshold: 0 },
  { index: 0x23, name: pokemonNames[34], genderThreshold: 12 },
  { index: 0x24, name: pokemonNames[35], genderThreshold: 12 },
  { index: 0x25, name: pokemonNames[36], genderThreshold: 12 },
  { index: 0x26, name: pokemonNames[37], genderThreshold: 12 },
  { index: 0x27, name: pokemonNames[38], genderThreshold: 12 },
  { index: 0x28, name: pokemonNames[39], genderThreshold: 12 },
  { index: 0x29, name: pokemonNames[40], genderThreshold: 8 },
  { index: 0x2a, name: pokemonNames[41], genderThreshold: 8 },
  { index: 0x2b, name: pokemonNames[42], genderThreshold: 8 },
  { index: 0x2c, name: pokemonNames[43], genderThreshold: 8 },
  { index: 0x2d, name: pokemonNames[44], genderThreshold: 8 },
  { index: 0x2e, name: pokemonNames[45], genderThreshold: 8 },
  { index: 0x2f, name: pokemonNames[46], genderThreshold: 8 },
  { index: 0x30, name: pokemonNames[47], genderThreshold: 8 },
  { index: 0x31, name: pokemonNames[48], genderThreshold: 8 },
  { index: 0x32, name: pokemonNames[49], genderThreshold: 8 },
  { index: 0x33, name: pokemonNames[50], genderThreshold: 8 },
  { index: 0x34, name: pokemonNames[51], genderThreshold: 8 },
  { index: 0x35, name: pokemonNames[52], genderThreshold: 8 },
  { index: 0x36, name: pokemonNames[53], genderThreshold: 8 },
  { index: 0x37, name: pokemonNames[54], genderThreshold: 8 },
  { index: 0x38, name: pokemonNames[55], genderThreshold: 8 },
  { index: 0x39, name: pokemonNames[56], genderThreshold: 8 },
  { index: 0x3a, name: pokemonNames[57], genderThreshold: 4 },
  { index: 0x3b, name: pokemonNames[58], genderThreshold: 4 },
  { index: 0x3c, name: pokemonNames[59], genderThreshold: 8 },
  { index: 0x3d, name: pokemonNames[60], genderThreshold: 8 },
  { index: 0x3e, name: pokemonNames[61], genderThreshold: 8 },
  { index: 0x3f, name: pokemonNames[62], genderThreshold: 4 },
  { index: 0x40, name: pokemonNames[63], genderThreshold: 4 },
  { index: 0x41, name: pokemonNames[64], genderThreshold: 4 },
  { index: 0x42, name: pokemonNames[65], genderThreshold: 4 },
  { index: 0x43, name: pokemonNames[66], genderThreshold: 4 },
  { index: 0x44, name: pokemonNames[67], genderThreshold: 4 },
  { index: 0x45, name: pokemonNames[68], genderThreshold: 8 },
  { index: 0x46, name: pokemonNames[69], genderThreshold: 8 },
  { index: 0x47, name: pokemonNames[70], genderThreshold: 8 },
  { index: 0x48, name: pokemonNames[71], genderThreshold: 8 },
  { index: 0x49, name: pokemonNames[72], genderThreshold: 8 },
  { index: 0x4a, name: pokemonNames[73], genderThreshold: 8 },
  { index: 0x4b, name: pokemonNames[74], genderThreshold: 8 },
  { index: 0x4c, name: pokemonNames[75], genderThreshold: 8 },
  { index: 0x4d, name: pokemonNames[76], genderThreshold: 8 },
  { index: 0x4e, name: pokemonNames[77], genderThreshold: 8 },
  { index: 0x4f, name: pokemonNames[78], genderThreshold: 8 },
  { index: 0x50, name: pokemonNames[79], genderThreshold: 8 },
  { index: 0x51, name: pokemonNames[80], genderThreshold: -1 },
  { index: 0x52, name: pokemonNames[81], genderThreshold: -1 },
  { index: 0x53, name: pokemonNames[82], genderThreshold: 8 },
  { index: 0x54, name: pokemonNames[83], genderThreshold: 8 },
  { index: 0x55, name: pokemonNames[84], genderThreshold: 8 },
  { index: 0x56, name: pokemonNames[85], genderThreshold: 8 },
  { index: 0x57, name: pokemonNames[86], genderThreshold: 8 },
  { index: 0x58, name: pokemonNames[87], genderThreshold: 8 },
  { index: 0x59, name: pokemonNames[88], genderThreshold: 8 },
  { index: 0x5a, name: pokemonNames[89], genderThreshold: 8 },
  { index: 0x5b, name: pokemonNames[90], genderThreshold: 8 },
  { index: 0x5c, name: pokemonNames[91], genderThreshold: 8 },
  { index: 0x5d, name: pokemonNames[92], genderThreshold: 8 },
  { index: 0x5e, name: pokemonNames[93], genderThreshold: 8 },
  { index: 0x5f, name: pokemonNames[94], genderThreshold: 8 },
  { index: 0x60, name: pokemonNames[95], genderThreshold: 8 },
  { index: 0x61, name: pokemonNames[96], genderThreshold: 8 },
  { index: 0x62, name: pokemonNames[97], genderThreshold: 8 },
  { index: 0x63, name: pokemonNames[98], genderThreshold: 8 },
  { index: 0x64, name: pokemonNames[99], genderThreshold: -1 },
  { index: 0x65, name: pokemonNames[100], genderThreshold: -1 },
  { index: 0x66, name: pokemonNames[101], genderThreshold: 8 },
  { index: 0x67, name: pokemonNames[102], genderThreshold: 8 },
  { index: 0x68, name: pokemonNames[103], genderThreshold: 8 },
  { index: 0x69, name: pokemonNames[104], genderThreshold: 8 },
  { index: 0x6a, name: pokemonNames[105], genderThreshold: 0 },
  { index: 0x6b, name: pokemonNames[106], genderThreshold: 0 },
  { index: 0x6c, name: pokemonNames[107], genderThreshold: 8 },
  { index: 0x6d, name: pokemonNames[108], genderThreshold: 8 },
  { index: 0x6e, name: pokemonNames[109], genderThreshold: 8 },
  { index: 0x6f, name: pokemonNames[110], genderThreshold: 8 },
  { index: 0x70, name: pokemonNames[111], genderThreshold: 8 },
  { index: 0x71, name: pokemonNames[112], genderThreshold: 16 },
  { index: 0x72, name: pokemonNames[113], genderThreshold: 8 },
  { index: 0x73, name: pokemonNames[114], genderThreshold: 16 },
  { index: 0x74, name: pokemonNames[115], genderThreshold: 8 },
  { index: 0x75, name: pokemonNames[116], genderThreshold: 8 },
  { index: 0x76, name: pokemonNames[117], genderThreshold: 8 },
  { index: 0x77, name: pokemonNames[118], genderThreshold: 8 },
  { index: 0x78, name: pokemonNames[119], genderThreshold: -1 },
  { index: 0x79, name: pokemonNames[120], genderThreshold: -1 },
  { index: 0x7a, name: pokemonNames[121], genderThreshold: 8 },
  { index: 0x7b, name: pokemonNames[122], genderThreshold: 8 },
  { index: 0x7c, name: pokemonNames[123], genderThreshold: 16 },
  { index: 0x7d, name: pokemonNames[124], genderThreshold: 4 },
  { index: 0x7e, name: pokemonNames[125], genderThreshold: 4 },
  { index: 0x7f, name: pokemonNames[126], genderThreshold: 8 },
  { index: 0x80, name: pokemonNames[127], genderThreshold: 0 },
  { index: 0x81, name: pokemonNames[128], genderThreshold: 8 },
  { index: 0x82, name: pokemonNames[129], genderThreshold: 8 },
  { index: 0x83, name: pokemonNames[130], genderThreshold: 8 },
  { index: 0x84, name: pokemonNames[131], genderThreshold: -1 },
  { index: 0x85, name: pokemonNames[132], genderThreshold: 2 },
  { index: 0x86, name: pokemonNames[133], genderThreshold: 2 },
  { index: 0x87, name: pokemonNames[134], genderThreshold: 2 },
  { index: 0x88, name: pokemonNames[135], genderThreshold: 2 },
  { index: 0x89, name: pokemonNames[136], genderThreshold: -1 },
  { index: 0x8a, name: pokemonNames[137], genderThreshold: 2 },
  { index: 0x8b, name: pokemonNames[138], genderThreshold: 2 },
  { index: 0x8c, name: pokemonNames[139], genderThreshold: 2 },
  { index: 0x8d, name: pokemonNames[140], genderThreshold: 2 },
  { index: 0x8e, name: pokemonNames[141], genderThreshold: 2 },
  { index: 0x8f, name: pokemonNames[142], genderThreshold: 2 },
  { index: 0x90, name: pokemonNames[143], genderThreshold: -1 },
  { index: 0x91, name: pokemonNames[144], genderThreshold: -1 },
  { index: 0x92, name: pokemonNames[145], genderThreshold: -1 },
  { index: 0x93, name: pokemonNames[146], genderThreshold: 8 },
  { index: 0x94, name: pokemonNames[147], genderThreshold: 8 },
  { index: 0x95, name: pokemonNames[148], genderThreshold: 8 },
  { index: 0x96, name: pokemonNames[149], genderThreshold: -1 },
  { index: 0x97, name: pokemonNames[150], genderThreshold: -1 },
  { index: 0x98, name: pokemonNames[151], genderThreshold: 2 },
  { index: 0x99, name: pokemonNames[152], genderThreshold: 2 },
  { index: 0x9a, name: pokemonNames[153], genderThreshold: 2 },
  { index: 0x9b, name: pokemonNames[154], genderThreshold: 2 },
  { index: 0x9c, name: pokemonNames[155], genderThreshold: 2 },
  { index: 0x9d, name: pokemonNames[156], genderThreshold: 2 },
  { index: 0x9e, name: pokemonNames[157], genderThreshold: 2 },
  { index: 0x9f, name: pokemonNames[158], genderThreshold: 2 },
  { index: 0xa0, name: pokemonNames[159], genderThreshold: 2 },
  { index: 0xa1, name: pokemonNames[160], genderThreshold: 8 },
  { index: 0xa2, name: pokemonNames[161], genderThreshold: 8 },
  { index: 0xa3, name: pokemonNames[162], genderThreshold: 8 },
  { index: 0xa4, name: pokemonNames[163], genderThreshold: 8 },
  { index: 0xa5, name: pokemonNames[164], genderThreshold: 8 },
  { index: 0xa6, name: pokemonNames[165], genderThreshold: 8 },
  { index: 0xa7, name: pokemonNames[166], genderThreshold: 8 },
  { index: 0xa8, name: pokemonNames[167], genderThreshold: 8 },
  { index: 0xa9, name: pokemonNames[168], genderThreshold: 8 },
  { index: 0xaa, name: pokemonNames[169], genderThreshold: 8 },
  { index: 0xab, name: pokemonNames[170], genderThreshold: 8 },
  { index: 0xac, name: pokemonNames[171], genderThreshold: 8 },
  { index: 0xad, name: pokemonNames[172], genderThreshold: 12 },
  { index: 0xae, name: pokemonNames[173], genderThreshold: 12 },
  { index: 0xaf, name: pokemonNames[174], genderThreshold: 2 },
  { index: 0xb0, name: pokemonNames[175], genderThreshold: 2 },
  { index: 0xb1, name: pokemonNames[176], genderThreshold: 8 },
  { index: 0xb2, name: pokemonNames[177], genderThreshold: 8 },
  { index: 0xb3, name: pokemonNames[178], genderThreshold: 8 },
  { index: 0xb4, name: pokemonNames[179], genderThreshold: 8 },
  { index: 0xb5, name: pokemonNames[180], genderThreshold: 8 },
  { index: 0xb6, name: pokemonNames[181], genderThreshold: 8 },
  { index: 0xb7, name: pokemonNames[182], genderThreshold: 8 },
  { index: 0xb8, name: pokemonNames[183], genderThreshold: 8 },
  { index: 0xb9, name: pokemonNames[184], genderThreshold: 8 },
  { index: 0xba, name: pokemonNames[185], genderThreshold: 8 },
  { index: 0xbb, name: pokemonNames[186], genderThreshold: 8 },
  { index: 0xbc, name: pokemonNames[187], genderThreshold: 8 },
  { index: 0xbd, name: pokemonNames[188], genderThreshold: 8 },
  { index: 0xbe, name: pokemonNames[189], genderThreshold: 8 },
  { index: 0xbf, name: pokemonNames[190], genderThreshold: 8 },
  { index: 0xc0, name: pokemonNames[191], genderThreshold: 8 },
  { index: 0xc1, name: pokemonNames[192], genderThreshold: 8 },
  { index: 0xc2, name: pokemonNames[193], genderThreshold: 8 },
  { index: 0xc3, name: pokemonNames[194], genderThreshold: 8 },
  { index: 0xc4, name: pokemonNames[195], genderThreshold: 2 },
  { index: 0xc5, name: pokemonNames[196], genderThreshold: 2 },
  { index: 0xc6, name: pokemonNames[197], genderThreshold: 8 },
  { index: 0xc7, name: pokemonNames[198], genderThreshold: 8 },
  { index: 0xc8, name: pokemonNames[199], genderThreshold: 8 },
  { index: 0xc9, name: pokemonNames[200], genderThreshold: -1 },
  { index: 0xca, name: pokemonNames[201], genderThreshold: 8 },
  { index: 0xcb, name: pokemonNames[202], genderThreshold: 8 },
  { index: 0xcc, name: pokemonNames[203], genderThreshold: 8 },
  { index: 0xcd, name: pokemonNames[204], genderThreshold: 8 },
  { index: 0xce, name: pokemonNames[205], genderThreshold: 8 },
  { index: 0xcf, name: pokemonNames[206], genderThreshold: 8 },
  { index: 0xd0, name: pokemonNames[207], genderThreshold: 8 },
  { index: 0xd1, name: pokemonNames[208], genderThreshold: 12 },
  { index: 0xd2, name: pokemonNames[209], genderThreshold: 12 },
  { index: 0xd3, name: pokemonNames[210], genderThreshold: 8 },
  { index: 0xd4, name: pokemonNames[211], genderThreshold: 8 },
  { index: 0xd5, name: pokemonNames[212], genderThreshold: 8 },
  { index: 0xd6, name: pokemonNames[213], genderThreshold: 8 },
  { index: 0xd7, name: pokemonNames[214], genderThreshold: 8 },
  { index: 0xd8, name: pokemonNames[215], genderThreshold: 8 },
  { index: 0xd9, name: pokemonNames[216], genderThreshold: 8 },
  { index: 0xda, name: pokemonNames[217], genderThreshold: 8 },
  { index: 0xdb, name: pokemonNames[218], genderThreshold: 8 },
  { index: 0xdc, name: pokemonNames[219], genderThreshold: 8 },
  { index: 0xdd, name: pokemonNames[220], genderThreshold: 8 },
  { index: 0xde, name: pokemonNames[221], genderThreshold: 12 },
  { index: 0xdf, name: pokemonNames[222], genderThreshold: 8 },
  { index: 0xe0, name: pokemonNames[223], genderThreshold: 8 },
  { index: 0xe1, name: pokemonNames[224], genderThreshold: 8 },
  { index: 0xe2, name: pokemonNames[225], genderThreshold: 8 },
  { index: 0xe3, name: pokemonNames[226], genderThreshold: 8 },
  { index: 0xe4, name: pokemonNames[227], genderThreshold: 8 },
  { index: 0xe5, name: pokemonNames[228], genderThreshold: 8 },
  { index: 0xe6, name: pokemonNames[229], genderThreshold: 8 },
  { index: 0xe7, name: pokemonNames[230], genderThreshold: 8 },
  { index: 0xe8, name: pokemonNames[231], genderThreshold: 8 },
  { index: 0xe9, name: pokemonNames[232], genderThreshold: -1 },
  { index: 0xea, name: pokemonNames[233], genderThreshold: 8 },
  { index: 0xeb, name: pokemonNames[234], genderThreshold: 8 },
  { index: 0xec, name: pokemonNames[235], genderThreshold: 0 },
  { index: 0xed, name: pokemonNames[236], genderThreshold: 0 },
  { index: 0xee, name: pokemonNames[237], genderThreshold: 16 },
  { index: 0xef, name: pokemonNames[238], genderThreshold: 4 },
  { index: 0xf0, name: pokemonNames[239], genderThreshold: 4 },
  { index: 0xf1, name: pokemonNames[240], genderThreshold: 16 },
  { index: 0xf2, name: pokemonNames[241], genderThreshold: 16 },
  { index: 0xf3, name: pokemonNames[242], genderThreshold: -1 },
  { index: 0xf4, name: pokemonNames[243], genderThreshold: -1 },
  { index: 0xf5, name: pokemonNames[244], genderThreshold: -1 },
  { index: 0xf6, name: pokemonNames[245], genderThreshold: 8 },
  { index: 0xf7, name: pokemonNames[246], genderThreshold: 8 },
  { index: 0xf8, name: pokemonNames[247], genderThreshold: 8 },
  { index: 0xf9, name: pokemonNames[248], genderThreshold: -1 },
  { index: 0xfa, name: pokemonNames[249], genderThreshold: -1 },
  { index: 0xfb, name: pokemonNames[250], genderThreshold: -1 },
];

export const pokemons: Resource = {};

pokemonList.forEach((pokemon) => {
  pokemons[pokemon.index] = pokemon.name;
});
