import type { GameJson } from "$lib/types";

const template: GameJson = {
  validator: {
    regions: {
      europe_usarev1_france_germany: {},
      usa_japan: {},
      canada: {},
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      type: "section",
      flex: true,
      hidden: true,
      items: [
        {
          name: "Last Save Slot",
          offset: 0x19e7,
          type: "variable",
          dataType: "uint8",
          hidden: true,
        },
        {
          name: "Last Save Slot",
          offset: 0x19e8,
          type: "variable",
          dataType: "uint8",
          hidden: true,
        },
      ],
    },
    {
      length: 0x4c,
      type: "container",
      instanceType: "tabs",
      instances: 3,
      enumeration: "Slot %d",
      disableSubinstanceIf: {
        offset: 0x1905,
        type: "variable",
        dataType: "uint8",
        operator: "=",
        value: 0x0,
      },
      items: [
        {
          name: "Checksum",
          offset: 0x1903,
          type: "checksum",
          dataType: "uint16",
          control: {
            offsetStart: 0x1905,
            offsetEnd: 0x1929,
          },
        },
        {
          type: "tabs",
          vertical: true,
          items: [
            {
              name: "General",
              flex: true,
              items: [
                {
                  name: "Completion Rate",
                  offset: 0x1905,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "*": 1.59 }, { roundFloor: 0 }],
                  suffix: "%",
                  disabled: true,
                },
                {
                  name: "Completed Doors",
                  offset: 0x1905,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                  test: true,
                },
                {
                  name: "Completed Levels",
                  offset: 0x1906,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "Level Animation",
                  offset: 0x191e,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "???",
                  offset: 0x191f,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  id: "currentLevel",
                  name: "Current Level",
                  offset: 0x1921,
                  type: "variable",
                  dataType: "uint24",
                  bigEndian: true,
                  resource: "levels",
                  autocomplete: true,
                },
                {
                  name: "???",
                  offset: 0x1924,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "???",
                  offset: 0x1925,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "???",
                  offset: 0x1926,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "???",
                  offset: 0x1927,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
              ],
            },
            {
              name: "Level 1",
              flex: true,
              items: [
                {
                  id: "levels-6",
                  name: "Levels",
                  type: "bitflags",
                  flags: [
                    { offset: 0x190d, bit: 0, label: "Door 1-1" },
                    { offset: 0x190d, bit: 1, label: "Door 1-2" },
                    { offset: 0x190d, bit: 2, label: "Door 1-3" },
                    { offset: 0x190d, bit: 3, label: "Door 1-4", separator: true },
                    { offset: 0x191d, bit: 7, label: "Level Completed" },
                  ],
                },
                {
                  id: "levels-14",
                  name: "Switches",
                  type: "bitflags",
                  flags: [
                    { offset: 0x1915, bit: 0, label: "Switch 1-1", disabled: true },
                    { offset: 0x1915, bit: 1, label: "Switch 1-2", disabled: true },
                    { offset: 0x1915, bit: 2, label: "Switch 1-3", disabled: true },
                    { offset: 0x1915, bit: 3, label: "Switch 1-4", disabled: true },
                  ],
                },
              ],
            },
            {
              name: "Level 2",
              flex: true,
              items: [
                {
                  id: "levels-5",
                  name: "Levels",
                  type: "bitflags",
                  flags: [
                    { offset: 0x190c, bit: 0, label: "Door 2-1" },
                    { offset: 0x190c, bit: 1, label: "Door 2-2" },
                    { offset: 0x190c, bit: 2, label: "Door 2-3" },
                    { offset: 0x190c, bit: 3, label: "Door 2-4" },
                    { offset: 0x190c, bit: 4, label: "Door 2-5", separator: true },
                    { offset: 0x191c, bit: 7, label: "Level Completed" },
                  ],
                },
                {
                  id: "levels-13",
                  name: "Switches",
                  type: "bitflags",
                  flags: [
                    { offset: 0x1914, bit: 0, label: "Switch 2-1", disabled: true },
                    { offset: 0x1914, bit: 1, label: "Switch 2-2", disabled: true },
                    { offset: 0x1914, bit: 2, label: "Switch 2-3", disabled: true },
                    { offset: 0x1914, bit: 3, label: "Switch 2-4", disabled: true },
                    { offset: 0x1914, bit: 4, label: "Switch 2-5", disabled: true },
                  ],
                },
              ],
            },
            {
              name: "Level 3",
              flex: true,
              items: [
                {
                  id: "levels-4",
                  name: "Levels",
                  type: "bitflags",
                  flags: [
                    { offset: 0x190b, bit: 0, label: "Door 3-1" },
                    { offset: 0x190b, bit: 1, label: "Door 3-2" },
                    { offset: 0x190b, bit: 2, label: "Door 3-3" },
                    { offset: 0x190b, bit: 3, label: "Door 3-4" },
                    { offset: 0x190b, bit: 4, label: "Door 3-5" },
                    { offset: 0x190b, bit: 5, label: "Door 3-6", separator: true },
                    { offset: 0x191b, bit: 7, label: "Level Completed" },
                  ],
                },
                {
                  id: "levels-12",
                  name: "Switches",
                  type: "bitflags",
                  flags: [
                    { offset: 0x1913, bit: 0, label: "Switch 3-1" },
                    { offset: 0x1913, bit: 1, label: "Switch 3-2", disabled: true },
                    { offset: 0x1913, bit: 2, label: "Switch 3-3", disabled: true },
                    { offset: 0x1913, bit: 3, label: "Switch 3-4", disabled: true },
                    { offset: 0x1913, bit: 4, label: "Switch 3-5", disabled: true },
                    { offset: 0x1913, bit: 5, label: "Switch 3-6" },
                  ],
                },
              ],
            },
            {
              name: "Level 4",
              flex: true,
              items: [
                {
                  id: "levels-3",
                  name: "Levels",
                  type: "bitflags",
                  flags: [
                    { offset: 0x190a, bit: 0, label: "Door 4-1" },
                    { offset: 0x190a, bit: 1, label: "Door 4-2" },
                    { offset: 0x190a, bit: 2, label: "Door 4-3" },
                    { offset: 0x190a, bit: 3, label: "Door 4-4" },
                    { offset: 0x190a, bit: 4, label: "Door 4-5" },
                    { offset: 0x190a, bit: 5, label: "Door 4-6", separator: true },
                    { offset: 0x191a, bit: 7, label: "Level Completed" },
                  ],
                },
                {
                  id: "levels-11",
                  name: "Switches",
                  type: "bitflags",
                  flags: [
                    { offset: 0x1912, bit: 0, label: "Switch 4-1" },
                    { offset: 0x1912, bit: 1, label: "Switch 4-2", disabled: true },
                    { offset: 0x1912, bit: 2, label: "Switch 4-3" },
                    { offset: 0x1912, bit: 3, label: "Switch 4-4", disabled: true },
                    { offset: 0x1912, bit: 4, label: "Switch 4-5", disabled: true },
                    { offset: 0x1912, bit: 5, label: "Switch 4-6" },
                  ],
                },
              ],
            },
            {
              name: "Level 5",
              flex: true,
              items: [
                {
                  id: "levels-2",
                  name: "Levels",
                  type: "bitflags",
                  flags: [
                    { offset: 0x1909, bit: 0, label: "Door 5-1" },
                    { offset: 0x1909, bit: 1, label: "Door 5-2" },
                    { offset: 0x1909, bit: 2, label: "Door 5-3" },
                    { offset: 0x1909, bit: 3, label: "Door 5-4" },
                    { offset: 0x1909, bit: 4, label: "Door 5-5" },
                    { offset: 0x1909, bit: 5, label: "Door 5-6", separator: true },
                    { offset: 0x1919, bit: 7, label: "Level Completed" },
                  ],
                },
                {
                  id: "levels-10",
                  name: "Switches",
                  type: "bitflags",
                  flags: [
                    { offset: 0x1911, bit: 0, label: "Switch 5-1" },
                    { offset: 0x1911, bit: 1, label: "Switch 5-2", disabled: true },
                    { offset: 0x1911, bit: 2, label: "Switch 5-3", disabled: true },
                    { offset: 0x1911, bit: 3, label: "Switch 5-4" },
                    { offset: 0x1911, bit: 4, label: "Switch 5-5" },
                    { offset: 0x1911, bit: 5, label: "Switch 5-6" },
                  ],
                },
              ],
            },
            {
              name: "Level 6",
              flex: true,
              items: [
                {
                  id: "levels-1",
                  name: "Levels",
                  type: "bitflags",
                  flags: [
                    { offset: 0x1908, bit: 0, label: "Door 6-1" },
                    { offset: 0x1908, bit: 1, label: "Door 6-2" },
                    { offset: 0x1908, bit: 2, label: "Door 6-3" },
                    { offset: 0x1908, bit: 3, label: "Door 6-4" },
                    { offset: 0x1908, bit: 4, label: "Door 6-5" },
                    { offset: 0x1908, bit: 5, label: "Door 6-6", separator: true },
                    { offset: 0x1918, bit: 7, label: "Level Completed" },
                  ],
                },
                {
                  id: "levels-9",
                  name: "Switches",
                  type: "bitflags",
                  flags: [
                    { offset: 0x1910, bit: 0, label: "Switch 6-1" },
                    { offset: 0x1910, bit: 1, label: "Switch 6-2" },
                    { offset: 0x1910, bit: 2, label: "Switch 6-3" },
                    { offset: 0x1910, bit: 3, label: "Switch 6-4" },
                    { offset: 0x1910, bit: 4, label: "Switch 6-5" },
                    { offset: 0x1910, bit: 5, label: "Switch 6-6" },
                  ],
                },
              ],
            },
            {
              name: "Level 7",
              flex: true,
              items: [
                {
                  id: "levels-0",
                  name: "Levels",
                  type: "bitflags",
                  flags: [
                    { offset: 0x1907, bit: 0, label: "Door 7-1" },
                    { offset: 0x1907, bit: 1, label: "Door 7-2" },
                    { offset: 0x1907, bit: 2, label: "Door 7-3" },
                    { offset: 0x1907, bit: 3, label: "Door 7-4" },
                    { offset: 0x1907, bit: 4, label: "Door 7-5" },
                    { offset: 0x1907, bit: 5, label: "Door 7-6", separator: true },
                    { offset: 0x1917, bit: 7, label: "Level Completed" },
                  ],
                },
                {
                  id: "levels-8",
                  name: "Switches",
                  type: "bitflags",
                  flags: [
                    { offset: 0x190f, bit: 0, label: "Switch 7-1" },
                    { offset: 0x190f, bit: 1, label: "Switch 7-2", disabled: true },
                    { offset: 0x190f, bit: 2, label: "Switch 7-3", disabled: true },
                    { offset: 0x190f, bit: 3, label: "Switch 7-4", disabled: true },
                    { offset: 0x190f, bit: 4, label: "Switch 7-5", disabled: true },
                    { offset: 0x190f, bit: 5, label: "Switch 7-6" },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    levels: {
      0x266: "Door 1-1",
      0x2f8: "Door 1-2",
      0x342: "Door 1-3",
      0x385: "Door 1-4",
      0x1010b: "Door 2-2",
      0x10116: "Door 2-4",
      0x101b9: "Level 2",
      0x10374: "Door 2-1",
      0x10417: "Door 2-3",
      0x104f3: "Door 2-5",
      0x20180: "Door 3-6",
      0x20185: "Door 3-5",
      0x20277: "Door 3-3",
      0x20281: "Door 3-4",
      0x202b7: "Level 3",
      0x20377: "Door 3-1",
      0x20380: "Door 3-2",
      0x30077: "Level 4",
      0x30147: "Door 4-3",
      0x30266: "Door 4-6",
      0x30375: "Door 4-1",
      0x303a0: "Door 4-2",
      0x30476: "Door 4-4",
      0x30523: "Door 4-5",
      0x40038: "Door 5-1",
      0x40095: "Door 5-2",
      0x400aa: "Door 5-3",
      0x402b5: "Level 5",
      0x40430: "Door 5-4",
      0x40514: "Door 5-5",
      0x40585: "Door 5-6",
      0x502ab: "Door 6-6",
      0x502b9: "Level 6",
      0x50388: "Door 6-1",
      0x503c2: "Door 6-2",
      0x50435: "Door 6-3",
      0x504a3: "Door 6-4",
      0x50541: "Door 6-5",
      0x601da: "Door 7-6",
      0x60252: "Door 7-1",
      0x602a4: "Door 7-2",
      0x602d9: "Level 7",
      0x600f9: "Final Boss",
      0x60306: "Door 7-3",
      0x60353: "Door 7-4",
      0x603a1: "Door 7-5",
    },
  },
  resourcesGroups: {
    levels: [
      {
        name: "Level 1",
        options: [0x266, 0x2f8, 0x342, 0x385],
      },
      {
        name: "Level 2",
        options: [0x101b9, 0x10374, 0x1010b, 0x10417, 0x10116, 0x104f3],
      },
      {
        name: "Level 3",
        options: [
          0x202b7, 0x20377, 0x20380, 0x20277, 0x20281, 0x20185, 0x20180,
        ],
      },
      {
        name: "Level 4",
        options: [
          0x30077, 0x30375, 0x303a0, 0x30147, 0x30476, 0x30523, 0x30266,
        ],
      },
      {
        name: "Level 5",
        options: [
          0x402b5, 0x40038, 0x40095, 0x400aa, 0x40430, 0x40514, 0x40585,
        ],
      },
      {
        name: "Level 6",
        options: [
          0x502b9, 0x50388, 0x503c2, 0x50435, 0x504a3, 0x50541, 0x502ab,
        ],
      },
      {
        name: "Level 7",
        options: [
          0x602d9, 0x60252, 0x602a4, 0x60306, 0x60353, 0x603a1, 0x601da,
          0x600f9,
        ],
      },
    ],
  },
  resourcesOrder: {
    levels: [
      0x266, 0x2f8, 0x342, 0x385, 0x101b9, 0x10374, 0x1010b, 0x10417, 0x10116,
      0x104f3, 0x202b7, 0x20377, 0x20380, 0x20277, 0x20281, 0x20185, 0x20180,
      0x30077, 0x30375, 0x303a0, 0x30147, 0x30476, 0x30523, 0x30266, 0x402b5,
      0x40038, 0x40095, 0x400aa, 0x40430, 0x40514, 0x40585, 0x502b9, 0x50388,
      0x503c2, 0x50435, 0x504a3, 0x50541, 0x502ab, 0x602d9, 0x60252, 0x602a4,
      0x60306, 0x60353, 0x603a1, 0x601da, 0x600f9,
    ],
  },
};

export default template;
