import type { Resource, ResourceGroups } from "$lib/types";

export const itemQuantites: {
  [key: string]: {
    shift: number;
    valuesMax: number[];
  };
} = {
  rupees: {
    shift: 0xe,
    valuesMax: [200, 1000, 5000],
  },
};

const areas = [
  { index: 0x0, name: "Great Sea" },
  { index: 0x1, name: "Pirate Ship" },
  { index: 0x2, name: "Forsaken Fortress" },
  { index: 0x3, name: "Dragon Roost Cavern" },
  { index: 0x4, name: "Forbidden Woods" },
  { index: 0x5, name: "Tower of the Gods" },
  { index: 0x6, name: "Hyrule Castle" },
  { index: 0x7, name: "Earth Temple" },
  { index: 0x8, name: "Wind Temple" },
  { index: 0x9, name: "Ganon's Tower" },
];

// prettier-ignore
export const locationList = [
  { id: "sea"    , area: 0x0, room: 0x01, spawn: 0x00, name: "Forsaken Fortress" },
  { id: "sea"    , area: 0x0, room: 0x02, spawn: 0x00, name: "Star Island" },
  { id: "sea"    , area: 0x0, room: 0x03, spawn: 0x00, name: "Northern Fairy Island" },
  { id: "sea"    , area: 0x0, room: 0x04, spawn: 0x00, name: "Gale Isle" },
  { id: "sea"    , area: 0x0, room: 0x05, spawn: 0x00, name: "Crescent Moon Island" },
  { id: "sea"    , area: 0x0, room: 0x06, spawn: 0x00, name: "Seven-Star Isles" },
  { id: "sea"    , area: 0x0, room: 0x07, spawn: 0x00, name: "Overlook Island" },
  { id: "sea"    , area: 0x0, room: 0x08, spawn: 0x00, name: "Four-Eye Reef" },
  { id: "sea"    , area: 0x0, room: 0x09, spawn: 0x00, name: "Mother & Child Isles" },
  { id: "sea"    , area: 0x0, room: 0x09, spawn: 0x01, name: "Fairy Queen Fountain" },
  { id: "sea"    , area: 0x0, room: 0x0a, spawn: 0x00, name: "Spectacle Island" },
  { id: "sea"    , area: 0x0, room: 0x0b, spawn: 0x00, name: "Windfall Island" },
  { id: "sea"    , area: 0x0, room: 0x0c, spawn: 0x00, name: "Pawprint Isle" },
  { id: "sea"    , area: 0x0, room: 0x0d, spawn: 0x00, name: "Dragon Roost Island" },
  { id: "sea"    , area: 0x0, room: 0x0e, spawn: 0x00, name: "Flight Control Platform" },
  { id: "sea"    , area: 0x0, room: 0x0f, spawn: 0x00, name: "Western Fairy Island" },
  { id: "sea"    , area: 0x0, room: 0x10, spawn: 0x00, name: "Rock Spire Isle" },
  { id: "sea"    , area: 0x0, room: 0x11, spawn: 0x00, name: "Tingle Island" },
  { id: "sea"    , area: 0x0, room: 0x12, spawn: 0x00, name: "Northern Triangle Isle" },
  { id: "sea"    , area: 0x0, room: 0x13, spawn: 0x00, name: "Eastern Fairy Island" },
  { id: "sea"    , area: 0x0, room: 0x14, spawn: 0x00, name: "Fire Mountain" },
  { id: "sea"    , area: 0x0, room: 0x15, spawn: 0x00, name: "Star Belt Archipelago" },
  { id: "sea"    , area: 0x0, room: 0x16, spawn: 0x00, name: "Three-Eye Reef" },
  { id: "sea"    , area: 0x0, room: 0x17, spawn: 0x00, name: "Greatfish Isle" },
  { id: "sea"    , area: 0x0, room: 0x18, spawn: 0x00, name: "Cyclops Reef" },
  { id: "sea"    , area: 0x0, room: 0x19, spawn: 0x00, name: "Six-Eye Reef" },
  { id: "sea"    , area: 0x0, room: 0x1a, spawn: 0x00, name: "Tower of the Gods" },
  { id: "sea"    , area: 0x0, room: 0x1b, spawn: 0x00, name: "Eastern Triangle Island" },
  { id: "sea"    , area: 0x0, room: 0x1c, spawn: 0x00, name: "Thorned Fairy Island" },
  { id: "sea"    , area: 0x0, room: 0x1d, spawn: 0x00, name: "Needle Rock Isle" },
  { id: "sea"    , area: 0x0, room: 0x1e, spawn: 0x00, name: "Islet of Steel" },
  { id: "sea"    , area: 0x0, room: 0x1f, spawn: 0x00, name: "Stone Watcher Island" },
  { id: "sea"    , area: 0x0, room: 0x20, spawn: 0x00, name: "Southern Triangle Island" },
  { id: "sea"    , area: 0x0, room: 0x21, spawn: 0x00, name: "Private Oasis" },
  { id: "sea"    , area: 0x0, room: 0x22, spawn: 0x00, name: "Bomb Island" },
  { id: "sea"    , area: 0x0, room: 0x23, spawn: 0x00, name: "Bird's Peak Rock" },
  { id: "sea"    , area: 0x0, room: 0x24, spawn: 0x00, name: "Diamond Steppe Island" },
  { id: "sea"    , area: 0x0, room: 0x25, spawn: 0x00, name: "Five-Eye Reef" },
  { id: "sea"    , area: 0x0, room: 0x26, spawn: 0x00, name: "Shark Island" },
  { id: "sea"    , area: 0x0, room: 0x27, spawn: 0x00, name: "Southern Fairy Island" },
  { id: "sea"    , area: 0x0, room: 0x28, spawn: 0x00, name: "Ice Ring Isle" },
  { id: "sea"    , area: 0x0, room: 0x29, spawn: 0x00, name: "Forest Haven" },
  { id: "sea"    , area: 0x0, room: 0x2a, spawn: 0x00, name: "Cliff Plateau Isles" },
  { id: "sea"    , area: 0x0, room: 0x2b, spawn: 0x00, name: "Horseshoe Island" },
  { id: "sea"    , area: 0x0, room: 0x2c, spawn: 0x00, name: "Outset Island" },
  { id: "sea"    , area: 0x0, room: 0x2d, spawn: 0x00, name: "Headstone Island" },
  { id: "sea"    , area: 0x0, room: 0x2e, spawn: 0x00, name: "Two-Eye Reef" },
  { id: "sea"    , area: 0x0, room: 0x2f, spawn: 0x00, name: "Angular Isles" },
  { id: "sea"    , area: 0x0, room: 0x30, spawn: 0x00, name: "Boating Course" },
  { id: "sea"    , area: 0x0, room: 0x31, spawn: 0x00, name: "Five-Star Isles" },
  { id: "A_umikz", area: 0x1, room: 0x00, spawn: 0x00, name: "Pirate Ship (Exterior)" },
  { id: "Asoko"  , area: 0x1, room: 0x00, spawn: 0x00, name: "Pirate Ship (Interior)" },
  { id: "MajyuE" , area: 0x2, room: 0x00, spawn: 0x00, name: "Forsaken Fortress" },
  { id: "M2tower", area: 0x2, room: 0x00, spawn: 0x14, name: "Forsaken Fortress Tower" },
  { id: "M_NewD2", area: 0x3, room: 0x00, spawn: 0x00, name: "Dragon Roost Cavern" },
  { id: "M_DragB", area: 0x3, room: 0x00, spawn: 0x00, name: "Dragon Roost Cavern (Gohma)" },
  { id: "kindan" , area: 0x4, room: 0x00, spawn: 0x00, name: "Forbidden Woods" },
  { id: "kinBOSS", area: 0x4, room: 0x00, spawn: 0x00, name: "Forbidden Woods (Kalle Demos)" },
  { id: "Siren"  , area: 0x5, room: 0x00, spawn: 0x00, name: "Tower of the Gods" },
  { id: "SirenB" , area: 0x5, room: 0x00, spawn: 0x00, name: "Tower of the Gods (Godhan)" },
  { id: "ADMumi" , area: 0x5, room: 0x00, spawn: 0x64, name: "Tower of the Gods (Bell)" },
  { id: "Hyrule" , area: 0x6, room: 0x00, spawn: 0x00, name: "Hyrule Castle" },
  { id: "Hyroom" , area: 0x6, room: 0x00, spawn: 0x00, name: "Hyrule Castle (Interior)" },
  { id: "kenroom", area: 0x6, room: 0x00, spawn: 0x00, name: "Hyrule Castle (Master Sword)" },
  { id: "M_Dai"  , area: 0x7, room: 0x00, spawn: 0x00, name: "Earth Temple" },
  { id: "M_DaiB" , area: 0x7, room: 0x00, spawn: 0x00, name: "Earth Temple (Jalhalla)" },
  { id: "kaze"   , area: 0x8, room: 0x00, spawn: 0x00, name: "Wind Temple" },
  { id: "kazeB"  , area: 0x8, room: 0x00, spawn: 0x00, name: "Wind Temple (Molgera)" },
  { id: "GanonA" , area: 0x9, room: 0x00, spawn: 0x00, name: "Ganon's Tower (Entrance)" },
  { id: "Xboss0" , area: 0x9, room: 0x00, spawn: 0x00, name: "Ganon's Tower (Gohma)" },
  { id: "Xboss1" , area: 0x9, room: 0x00, spawn: 0x00, name: "Ganon's Tower (Kalle Demos)" },
  { id: "Xboss2" , area: 0x9, room: 0x00, spawn: 0x00, name: "Ganon's Tower (Jalhalla)" },
  { id: "Xboss3" , area: 0x9, room: 0x00, spawn: 0x00, name: "Ganon's Tower (Molgera)" },
  { id: "GanonM" , area: 0x9, room: 0x00, spawn: 0x04, name: "Ganon's Tower (near Puppet Ganon)" },
];

export const locations: Resource = {};
export const locationsGroups: ResourceGroups = [];

areas.forEach((area) => {
  locationsGroups.push({ name: area.name, options: [] });
});

locationList.forEach((location, index) => {
  locations[index] = location.name;
  locationsGroups[location.area].options.push(index);
});

export const treasureCharts = [
  { index: 0x18, type: 0x0, name: "Triforce Chart 1" },
  { index: 0x19, type: 0x0, name: "Triforce Chart 2" },
  { index: 0x1a, type: 0x0, name: "Triforce Chart 3" },
  { index: 0x1b, type: 0x0, name: "Triforce Chart 4" },
  { index: 0x1c, type: 0x0, name: "Triforce Chart 5" },
  { index: 0x1d, type: 0x0, name: "Triforce Chart 6" },
  { index: 0x1e, type: 0x0, name: "Triforce Chart 7" },
  { index: 0x1f, type: 0x0, name: "Triforce Chart 8" },
  { index: 0x0f, type: 0x1, name: "Treasure Chart 1" },
  { index: 0x08, type: 0x1, name: "Treasure Chart 2" },
  { index: 0x06, type: 0x1, name: "Treasure Chart 3" },
  { index: 0x05, type: 0x1, name: "Treasure Chart 4" },
  { index: 0x14, type: 0x1, name: "Treasure Chart 5" },
  { index: 0x0c, type: 0x1, name: "Treasure Chart 6" },
  { index: 0x2a, type: 0x1, name: "Treasure Chart 7" },
  { index: 0x32, type: 0x1, name: "Treasure Chart 8" },
  { index: 0x3c, type: 0x1, name: "Treasure Chart 9" },
  { index: 0x38, type: 0x1, name: "Treasure Chart 10" },
  { index: 0x10, type: 0x1, name: "Treasure Chart 11" },
  { index: 0x0d, type: 0x1, name: "Treasure Chart 12" },
  { index: 0x37, type: 0x1, name: "Treasure Chart 13" },
  { index: 0x39, type: 0x1, name: "Treasure Chart 14" },
  { index: 0x11, type: 0x1, name: "Treasure Chart 15" },
  { index: 0x03, type: 0x1, name: "Treasure Chart 16" },
  { index: 0x3f, type: 0x1, name: "Treasure Chart 17" },
  { index: 0x02, type: 0x1, name: "Treasure Chart 18" },
  { index: 0x35, type: 0x1, name: "Treasure Chart 19" },
  { index: 0x13, type: 0x1, name: "Treasure Chart 20" },
  { index: 0x28, type: 0x1, name: "Treasure Chart 21" },
  { index: 0x3d, type: 0x1, name: "Treasure Chart 22" },
  { index: 0x15, type: 0x1, name: "Treasure Chart 23" },
  { index: 0x0b, type: 0x1, name: "Treasure Chart 24" },
  { index: 0x30, type: 0x1, name: "Treasure Chart 25" },
  { index: 0x33, type: 0x1, name: "Treasure Chart 26" },
  { index: 0x29, type: 0x1, name: "Treasure Chart 27" },
  { index: 0x04, type: 0x1, name: "Treasure Chart 28" },
  { index: 0x00, type: 0x1, name: "Treasure Chart 29" },
  { index: 0x12, type: 0x1, name: "Treasure Chart 30" },
  { index: 0x16, type: 0x1, name: "Treasure Chart 31" },
  { index: 0x36, type: 0x1, name: "Treasure Chart 32" },
  { index: 0x17, type: 0x1, name: "Treasure Chart 33" },
  { index: 0x01, type: 0x1, name: "Treasure Chart 34" },
  { index: 0x0e, type: 0x1, name: "Treasure Chart 35" },
  { index: 0x3e, type: 0x1, name: "Treasure Chart 36" },
  { index: 0x31, type: 0x1, name: "Treasure Chart 37" },
  { index: 0x09, type: 0x1, name: "Treasure Chart 38" },
  { index: 0x0a, type: 0x1, name: "Treasure Chart 39" },
  { index: 0x07, type: 0x1, name: "Treasure Chart 40" },
  { index: 0x34, type: 0x1, name: "Treasure Chart 41" },
  { index: 0x3b, type: 0x2, name: "Ghost Ship Chart" },
  { index: 0x3a, type: 0x2, name: "Tingle's Chart" },
  { index: 0x2b, type: 0x2, name: "IN-credible Chart" },
  { index: 0x2c, type: 0x2, name: "Octo Chart" },
  { index: 0x2d, type: 0x2, name: "Great Fairy Chart" },
  { index: 0x2e, type: 0x2, name: "Island Hearts Chart" },
  { index: 0x2f, type: 0x2, name: "Sea Hearts Chart" },
  { index: 0x20, type: 0x2, name: "Secret Cave Chart" },
  { index: 0x21, type: 0x2, name: "Light Ring Chart" },
  { index: 0x22, type: 0x2, name: "Platform Chart" },
  { index: 0x23, type: 0x2, name: "Beedle's Chart" },
  { index: 0x24, type: 0x2, name: "Submarine Chart" },
];

export const worldMapLocations = [
  "A1: Forsaken Fortress",
  "A2: Star Island",
  "A3: Northern Fairy Island",
  "A4: Gale Isle",
  "A5: Crescent Moon Island",
  "A6: Seven-Star Isles",
  "A7: Overlook Island",
  "B1: Four-Eye Reef",
  "B2: Mother & Child Isles",
  "B3: Spectacle Island",
  "B4: Windfall Island",
  "B5: Pawprint Isle",
  "B6: Dragon Roost Island",
  "B7: Flight Control Platform",
  "C1: Western Fairy Island",
  "C2: Rock Spire Isle",
  "C3: Tingle Island",
  "C4: Northern Triangle Isle",
  "C5: Eastern Fairy Island",
  "C6: Fire Mountain",
  "C7: Star Belt Archipelago",
  "D1: Three-Eye Reef",
  "D2: Greatfish Isle",
  "D3: Cyclops Reef",
  "D4: Six-Eye Reef",
  "D5: Tower of the Gods",
  "D6: Eastern Triangle Island",
  "D7: Thorned Fairy Island",
  "E1: Needle Rock Isle",
  "E2: Islet of Steel",
  "E3: Stone Watcher Island",
  "E4: Southern Triangle Island",
  "E5: Private Oasis",
  "E6: Bomb Island",
  "E7: Bird's Peak Rock",
  "F1: Diamond Steppe Island",
  "F2: Five-Eye Reef",
  "F3: Shark Island",
  "F4: Southern Fairy Island",
  "F5: Ice Ring Isle",
  "F6: Forest Haven",
  "F7: Cliff Plateau Isles",
  "G1: Horseshoe Island",
  "G2: Outset Island",
  "G3: Headstone Island",
  "G4: Two-Eye Reef",
  "G5: Angular Isles",
  "G6: Boating Course",
  "G7: Five-Star Isles",
];
