import type { GameJson } from "$lib/types";

import {
  accessories,
  items,
  itemsGroups,
  materias,
  materiasGroups,
  missionList,
} from "./utils/resource";

const template: GameJson = {
  validator: {
    fileNames: [/^((?!SYSTEM).)*$/],
    regions: {
      world: {
        0x516: [
          0x46, 0x61, 0x69, 0x72, 0x2e, 0x46, 0x61, 0x69, 0x72, 0x53, 0x61,
          0x76, 0x65, 0x47, 0x61, 0x6d, 0x65,
        ], // "Fair.FairSaveGame"
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    hint: "Designed to work with v1.0.3.\nOther versions may work, but may corrupt the save.\nPlease make a backup before editing.",
    error: "Not a valid save file.",
  },
  items: [
    {
      name: "Checksum",
      offset: 0x564,
      type: "checksum",
      dataType: "uint32",
      control: {
        offsetStart: 0x0,
        offsetEnd: 0x0,
      },
    },
    {
      id: "slots",
      length: 0x8c86,
      type: "container",
      instanceType: "tabs",
      instances: 0,
      resource: "slots",
      onTabChange: "onSlotChange(%d)",
      items: [
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Difficulty",
                              dataViewAltKey: "save",
                              offset: 0x8ad4,
                              type: "variable",
                              dataType: "uint8",
                              resource: "difficulties",
                            },
                            {
                              name: "Progression",
                              dataViewAltKey: "save",
                              offset: 0xde1,
                              type: "variable",
                              dataType: "uint8",
                              resource: "progressions",
                            },
                            {
                              name: "Portrait",
                              dataViewAltKey: "save",
                              offset: 0x9b7,
                              type: "variable",
                              dataType: "uint8",
                              resource: "portraits",
                            },
                            {
                              name: "Location",
                              dataViewAltKey: "save",
                              offset: 0x93c,
                              type: "variable",
                              dataType: "uint32",
                              hidden: true,
                            },
                            {
                              name: "Pending Mission",
                              dataViewAltKey: "save",
                              offset: 0x974,
                              type: "variable",
                              dataType: "uint16",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Materia Slots",
                              dataViewAltKey: "save",
                              offset: 0x97d,
                              type: "variable",
                              dataType: "uint8",
                              max: 6,
                            },
                            {
                              name: "Materia Fusion",
                              dataViewAltKey: "save",
                              offset: 0x97e,
                              type: "variable",
                              dataType: "uint8",
                              resource: "booleanUnlocked",
                            },
                            {
                              name: "Accessory Slots",
                              dataViewAltKey: "save",
                              offset: 0x97f,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Gil",
                              dataViewAltKey: "save",
                              offset: 0x8ab1,
                              type: "variable",
                              dataType: "uint32",
                              max: 999999999,
                              test: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "DMW Emotion",
                      items: [
                        {
                          name: "Limit",
                          dataViewAltKey: "save",
                          offset: 0x8a7b,
                          type: "variable",
                          dataType: "uint8",
                          resource: "dmwLimits",
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Sephiroth",
                              dataViewAltKey: "save",
                              offset: 0x8a91,
                              type: "variable",
                              dataType: "uint8",
                              max: 25,
                              step: 5,
                            },
                            {
                              name: "Angeal",
                              dataViewAltKey: "save",
                              offset: 0x8a92,
                              type: "variable",
                              dataType: "uint8",
                              max: 25,
                              step: 5,
                            },
                            {
                              name: "Tseng",
                              dataViewAltKey: "save",
                              offset: 0x8a93,
                              type: "variable",
                              dataType: "uint8",
                              max: 25,
                              step: 5,
                            },
                            {
                              name: "Cloud",
                              dataViewAltKey: "save",
                              offset: 0x8a94,
                              type: "variable",
                              dataType: "uint8",
                              max: 25,
                              step: 5,
                            },
                            {
                              name: "Aerith",
                              dataViewAltKey: "save",
                              offset: 0x8a95,
                              type: "variable",
                              dataType: "uint8",
                              max: 25,
                              step: 5,
                            },
                            {
                              name: "Cissnei",
                              dataViewAltKey: "save",
                              offset: 0x8a96,
                              type: "variable",
                              dataType: "uint8",
                              max: 25,
                              step: 5,
                            },
                            {
                              name: "Genesis",
                              dataViewAltKey: "save",
                              offset: 0x8a97,
                              type: "variable",
                              dataType: "uint8",
                              max: 25,
                              step: 5,
                            },
                            {
                              name: "Summons",
                              dataViewAltKey: "save",
                              offset: 0x8a98,
                              type: "variable",
                              dataType: "uint8",
                              max: 25,
                              step: 5,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Status",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Level",
                      dataViewAltKey: "save",
                      offset: 0x8a37,
                      type: "variable",
                      dataType: "uint8",
                      min: 1,
                      max: 99,
                    },
                    {
                      name: "Experience",
                      dataViewAltKey: "save",
                      offset: 0x8a05,
                      type: "variable",
                      dataType: "uint32",
                      max: 999999999,
                    },
                    {
                      name: "???",
                      dataViewAltKey: "save",
                      offset: 0x8a09,
                      type: "variable",
                      dataType: "uint32",
                      hidden: true,
                    },
                    {
                      name: "SP",
                      dataViewAltKey: "save",
                      offset: 0x8a0d,
                      type: "variable",
                      dataType: "uint32",
                      max: 99999999,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "HP",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          dataViewAltKey: "save",
                          offset: 0x8a11,
                          type: "variable",
                          dataType: "uint32",
                          min: 1,
                          max: 99999,
                        },
                        {
                          id: "baseStats-4",
                          dataViewAltKey: "save",
                          offset: 0x8a15,
                          type: "variable",
                          dataType: "uint32",
                          min: 1,
                          max: 99999,
                        },
                      ],
                    },
                    {
                      name: "MP",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          dataViewAltKey: "save",
                          offset: 0x8a1d,
                          type: "variable",
                          dataType: "uint32",
                          max: 9999,
                        },
                        {
                          id: "baseStats-4",
                          dataViewAltKey: "save",
                          offset: 0x8a21,
                          type: "variable",
                          dataType: "uint32",
                          max: 9999,
                        },
                      ],
                    },
                    {
                      name: "AP",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          dataViewAltKey: "save",
                          offset: 0x8a29,
                          type: "variable",
                          dataType: "uint32",
                          max: 9999,
                        },
                        {
                          id: "baseStats-4",
                          dataViewAltKey: "save",
                          offset: 0x8a2d,
                          type: "variable",
                          dataType: "uint32",
                          max: 9999,
                        },
                      ],
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "baseStats-6",
                      name: "Attack",
                      dataViewAltKey: "save",
                      offset: 0x8a38,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      id: "baseStats-6",
                      name: "Vitality",
                      dataViewAltKey: "save",
                      offset: 0x8a39,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      id: "baseStats-6",
                      name: "Magic",
                      dataViewAltKey: "save",
                      offset: 0x8a3a,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      id: "baseStats-6",
                      name: "Spirit",
                      dataViewAltKey: "save",
                      offset: 0x8a3b,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      id: "baseStats-6",
                      name: "Luck",
                      dataViewAltKey: "save",
                      offset: 0x8a3c,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      name: "???",
                      dataViewAltKey: "save",
                      offset: 0x8a3d,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      name: "Base Max HP",
                      dataViewAltKey: "save",
                      offset: 0x8a19,
                      type: "variable",
                      dataType: "uint32",
                      hidden: true,
                    },

                    {
                      name: "Base Max MP",
                      dataViewAltKey: "save",
                      offset: 0x8a25,
                      type: "variable",
                      dataType: "uint32",
                      hidden: true,
                    },

                    {
                      name: "Base Max AP",
                      dataViewAltKey: "save",
                      offset: 0x8a31,
                      type: "variable",
                      dataType: "uint32",
                      hidden: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      name: "Base Attack",
                      dataViewAltKey: "save",
                      offset: 0x8a3e,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Base Vitality",
                      dataViewAltKey: "save",
                      offset: 0x8a3f,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Base Magic",
                      dataViewAltKey: "save",
                      offset: 0x8a40,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Base Spirit",
                      dataViewAltKey: "save",
                      offset: 0x8a41,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Base Luck",
                      dataViewAltKey: "save",
                      offset: 0x8a42,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "???",
                      dataViewAltKey: "save",
                      offset: 0x8a43,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
              ],
            },
            {
              name: "Equipment",
              items: [
                {
                  length: 0x14,
                  type: "container",
                  instanceType: "tabs",
                  instances: 5,
                  enumeration: "Set %s",
                  vertical: true,
                  flex: true,
                  prependSubinstance: [
                    {
                      name: "Equipped",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Materia 1",
                              dataViewAltKey: "save",
                              offset: 0x8a5b,
                              type: "variable",
                              dataType: "uint16",
                              resource: "equippableMateriaNames",
                              autocomplete: true,
                            },
                            {
                              name: "Materia 2",
                              dataViewAltKey: "save",
                              offset: 0x8a5d,
                              type: "variable",
                              dataType: "uint16",
                              resource: "equippableMateriaNames",
                              autocomplete: true,
                            },
                            {
                              name: "Materia 3",
                              dataViewAltKey: "save",
                              offset: 0x8a5f,
                              type: "variable",
                              dataType: "uint16",
                              resource: "equippableMateriaNames",
                              autocomplete: true,
                            },
                            {
                              name: "Materia 4",
                              dataViewAltKey: "save",
                              offset: 0x8a61,
                              type: "variable",
                              dataType: "uint16",
                              resource: "equippableMateriaNames",
                              autocomplete: true,
                            },
                            {
                              name: "Materia 5",
                              dataViewAltKey: "save",
                              offset: 0x8a63,
                              type: "variable",
                              dataType: "uint16",
                              resource: "equippableMateriaNames",
                              autocomplete: true,
                            },
                            {
                              name: "Materia 6",
                              dataViewAltKey: "save",
                              offset: 0x8a65,
                              type: "variable",
                              dataType: "uint16",
                              resource: "equippableMateriaNames",
                              autocomplete: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Accessory 1",
                              dataViewAltKey: "save",
                              offset: 0x8a73,
                              type: "variable",
                              dataType: "uint16",
                              resource: "accessories",
                              autocomplete: true,
                            },
                            {
                              name: "Accessory 2",
                              dataViewAltKey: "save",
                              offset: 0x8a75,
                              type: "variable",
                              dataType: "uint16",
                              resource: "accessories",
                              autocomplete: true,
                            },
                            {
                              name: "Accessory 3",
                              dataViewAltKey: "save",
                              offset: 0x8a77,
                              type: "variable",
                              dataType: "uint16",
                              resource: "accessories",
                              autocomplete: true,
                            },
                            {
                              name: "Accessory 4",
                              dataViewAltKey: "save",
                              offset: 0x8a79,
                              type: "variable",
                              dataType: "uint16",
                              resource: "accessories",
                              autocomplete: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Materia 1",
                          dataViewAltKey: "save",
                          offset: 0x8bbd,
                          type: "variable",
                          dataType: "uint16",
                          resource: "equippableMateriaNames",
                          autocomplete: true,
                        },
                        {
                          name: "Materia 2",
                          dataViewAltKey: "save",
                          offset: 0x8bbf,
                          type: "variable",
                          dataType: "uint16",
                          resource: "equippableMateriaNames",
                          autocomplete: true,
                        },
                        {
                          name: "Materia 3",
                          dataViewAltKey: "save",
                          offset: 0x8bc1,
                          type: "variable",
                          dataType: "uint16",
                          resource: "equippableMateriaNames",
                          autocomplete: true,
                        },
                        {
                          name: "Materia 4",
                          dataViewAltKey: "save",
                          offset: 0x8bc3,
                          type: "variable",
                          dataType: "uint16",
                          resource: "equippableMateriaNames",
                          autocomplete: true,
                        },
                        {
                          name: "Materia 5",
                          dataViewAltKey: "save",
                          offset: 0x8bc5,
                          type: "variable",
                          dataType: "uint16",
                          resource: "equippableMateriaNames",
                          autocomplete: true,
                        },
                        {
                          name: "Materia 6",
                          dataViewAltKey: "save",
                          offset: 0x8bc7,
                          type: "variable",
                          dataType: "uint16",
                          resource: "equippableMateriaNames",
                          autocomplete: true,
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Accessory 1",
                          dataViewAltKey: "save",
                          offset: 0x8bc9,
                          type: "variable",
                          dataType: "uint16",
                          resource: "accessories",
                          autocomplete: true,
                        },
                        {
                          name: "Accessory 2",
                          dataViewAltKey: "save",
                          offset: 0x8bcb,
                          type: "variable",
                          dataType: "uint16",
                          resource: "accessories",
                          autocomplete: true,
                        },
                        {
                          name: "Accessory 3",
                          dataViewAltKey: "save",
                          offset: 0x8bcd,
                          type: "variable",
                          dataType: "uint16",
                          resource: "accessories",
                          autocomplete: true,
                        },
                        {
                          name: "Accessory 4",
                          dataViewAltKey: "save",
                          offset: 0x8bcf,
                          type: "variable",
                          dataType: "uint16",
                          resource: "accessories",
                          autocomplete: true,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Materia",
              items: [
                {
                  id: "materia",
                  length: 0xf,
                  type: "container",
                  instanceType: "tabs",
                  instances: 999,
                  resource: "inventoryMateriaNames",
                  vertical: true,
                  flex: true,
                  items: [
                    {
                      id: "materia-%parent%-%index%",
                      name: "Materia",
                      dataViewAltKey: "save",
                      offset: 0x14ef,
                      type: "variable",
                      dataType: "uint16",
                      resource: "materias",
                      autocomplete: true,
                    },
                    {
                      name: "Quantity",
                      dataViewAltKey: "save",
                      offset: 0x14f1,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Acquisition",
                      dataViewAltKey: "save",
                      offset: 0x14f2,
                      type: "variable",
                      dataType: "uint16",
                      hidden: true,
                    },
                    {
                      name: "Is New",
                      dataViewAltKey: "save",
                      offset: 0x14f4,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Subtype",
                      dataViewAltKey: "save",
                      offset: 0x14f5,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "???",
                      dataViewAltKey: "save",
                      offset: 0x14f6,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "???",
                      dataViewAltKey: "save",
                      offset: 0x14f7,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Level",
                      dataViewAltKey: "save",
                      offset: 0x14f8,
                      type: "variable",
                      dataType: "uint8",
                      min: 1,
                      max: 5,
                    },
                    {
                      name: "Is Equipped",
                      dataViewAltKey: "save",
                      offset: 0x14f9,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Bonus Type",
                      dataViewAltKey: "save",
                      offset: 0x14fa,
                      type: "variable",
                      dataType: "uint16",
                      resource: "materiaBonusTypes",
                    },
                    {
                      id: "materiaBonusValue",
                      name: "Bonus Value",
                      dataViewAltKey: "save",
                      offset: 0x14fc,
                      type: "variable",
                      dataType: "uint16",
                    },
                  ],
                },
              ],
            },
            {
              name: "Inventory",
              items: [
                {
                  length: 0x7,
                  type: "container",
                  instanceType: "section",
                  instances: 256,
                  flex: true,
                  items: [
                    {
                      id: "item",
                      name: "Item %d",
                      dataViewAltKey: "save",
                      offset: 0xdef,
                      type: "variable",
                      dataType: "uint16",
                      resource: "items",
                      autocomplete: true,
                    },
                    {
                      id: "quantity",
                      name: "Quantity",
                      dataViewAltKey: "save",
                      offset: 0xdf1,
                      type: "variable",
                      dataType: "uint8",
                      min: 1,
                      max: 99,
                    },
                    {
                      name: "Acquisition",
                      dataViewAltKey: "save",
                      offset: 0xdf3,
                      type: "variable",
                      dataType: "uint16",
                      hidden: true,
                    },
                    {
                      name: "Is New",
                      dataViewAltKey: "save",
                      offset: 0xdf5,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
              ],
            },
            {
              name: "Missions",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: missionList.map((category) => ({
                    name: category.name,
                    items: category.subcategories.map((subcategory) => ({
                      name: subcategory.name,
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Unlocked",
                          dataViewAltKey: "save",
                          type: "bitflags",
                          flags: subcategory.missions.map((mission) => ({
                            offset: 0x108 + mission.index * 0x3,
                            bit: 0,
                            label: mission.name,
                          })),
                        },
                        {
                          name: "Cleared",
                          dataViewAltKey: "save",
                          type: "bitflags",
                          flags: subcategory.missions.map((mission) => ({
                            offset: 0x108 + mission.index * 0x3 + 0x2,
                            bit: 0,
                            label: mission.name,
                          })),
                        },
                      ],
                    })),
                  })),
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    accessories: {
      0x0: "-",
      ...accessories,
    },
    booleanUnlocked: {
      0x0: "-",
      0x1: "Unlocked",
    },
    difficulties: {
      0x0: "Normal",
      0x1: "Hard",
    },
    dmwLimits: {
      0x0: "Low",
      0x1: "Normal",
      0x2: "High",
      0x3: "Sky High",
      0x4: "Heavenly",
    },
    equippableMateriaNames: "getInventoryMateriaNames(true)",
    inventoryMateriaNames: "getInventoryMateriaNames()",
    items: {
      0x0: "-",
      ...items,
    },
    materiaBonusTypes: {
      0x0: "HP",
      0x1: "MP",
      0x2: "AP",
      0x3: "ATK",
      0x4: "VIT",
      0x5: "MAG",
      0x6: "SPR",
      0x7: "LCK",
    },
    materias: {
      0x0: "-",
      ...materias,
    },
    portraits: {
      0x0: "2nd Class",
      0x1: "1st Class",
      0x2: "1st Class (Haircut)",
    },
    progressions: {
      0x0: "-",
      0x1: "Cleared",
    },
    slots: "getSlotNames()",
  },
  resourcesGroups: {
    items: itemsGroups,
    materias: materiasGroups,
  },
  resourcesOrder: {
    materias: [
      0x0, 0x4009, 0x400a, 0x400b, 0x400c, 0x400d, 0x4000, 0x4001, 0x4002,
      0x4003, 0x4004, 0x4005, 0x4006, 0x4007, 0x4008, 0x400e, 0x400f, 0x4010,
      0x4011, 0x4012, 0x4013, 0x4014, 0x4015, 0x4016, 0x4017, 0x4018, 0x4019,
      0x401a, 0x401b, 0x401c, 0x401d, 0x401e, 0x401f, 0x4020, 0x4021, 0x4022,
      0x4023, 0x4024, 0x4025, 0x4026, 0x4027, 0x4028, 0x4029, 0x402a, 0x402b,
      0x402c, 0x402d, 0x402e, 0x402f, 0x4030, 0x4031, 0x4032, 0x4033, 0x4034,
      0x4035, 0x4036, 0x4037, 0x4038, 0x4039, 0x403a, 0x403b, 0x403c, 0x403d,
      0x403e, 0x403f, 0x4040, 0x4041, 0x4042, 0x4043, 0x4044, 0x4045, 0x4046,
      0x4047, 0x4048, 0x4049, 0x404a, 0x404b, 0x404c, 0x404d, 0x404e, 0x404f,
      0x4050, 0x4051, 0x4052, 0x4053, 0x4054, 0x4055, 0x4057, 0x4056, 0x4058,
      0x4059, 0x405a, 0x405b, 0x405c, 0x405d, 0x405e, 0x405f, 0x4060, 0x4061,
      0x4062, 0x4063, 0x4064, 0x4065, 0x4066, 0x4067, 0x4068, 0x4069, 0x406a,
      0x406b, 0x406c, 0x406d, 0x406e, 0x406f, 0x4070, 0x4071, 0x4072, 0x4073,
      0x4074, 0x4075, 0x4076, 0x4077, 0x4078, 0x4079, 0x407a, 0x407b, 0x407c,
      0x407d, 0x407e, 0x407f, 0x4080, 0x4081, 0x4082, 0x4083, 0x4084, 0x4085,
      0x4086, 0x4087, 0x4088, 0x4089, 0x408a, 0x408b, 0x408c, 0x408d, 0x408e,
    ],
  },
};

export default template;
