import type { GameJson } from "$lib/types";

import {
  BATTLE_BACKGROUND_SETS_POINTER,
  MONSTER_GROUPS_POINTER,
} from "./utils/constants";

const template: GameJson = {
  validator: {
    regions: {
      europe: {
        $and: [
          {
            0x7fc0: [
              0x4d, 0x59, 0x53, 0x54, 0x49, 0x43, 0x20, 0x51, 0x55, 0x45, 0x53,
              0x54, 0x20, 0x4c, 0x45, 0x47, 0x45, 0x4e, 0x44,
            ], // "MYSTIC QUEST LEGEND"
          },
          {
            0x7fd9: [0x2],
          },
        ],
      },
      usa: {
        $and: [
          {
            0x7fc0: [
              0x46, 0x46, 0x20, 0x4d, 0x59, 0x53, 0x54, 0x49, 0x43, 0x20, 0x51,
              0x55, 0x45, 0x53, 0x54,
            ], // "FF MYSTIC QUEST"
          },
          {
            0x7fd9: [0x1],
          },
          {
            0x7fdb: [0x0],
          },
        ],
      },
      usarev1: {
        $and: [
          {
            0x7fc0: [
              0x46, 0x46, 0x20, 0x4d, 0x59, 0x53, 0x54, 0x49, 0x43, 0x20, 0x51,
              0x55, 0x45, 0x53, 0x54,
            ], // "FF MYSTIC QUEST"
          },
          {
            0x7fd9: [0x1],
          },
          {
            0x7fdb: [0x1],
          },
        ],
      },
      japan: {
        $and: [
          {
            0x7fc0: [
              0x46, 0x46, 0x20, 0x4d, 0x59, 0x53, 0x54, 0x49, 0x43, 0x20, 0x51,
              0x55, 0x45, 0x53, 0x54,
            ], // "FF MYSTIC QUEST"
          },
          {
            0x7fd9: [0x0],
          },
        ],
      },
      france: {
        $and: [
          {
            0x7fc0: [
              0x4d, 0x59, 0x53, 0x54, 0x49, 0x43, 0x20, 0x51, 0x55, 0x45, 0x53,
              0x54, 0x20, 0x4c, 0x45, 0x47, 0x45, 0x4e, 0x44,
            ], // "MYSTIC QUEST LEGEND"
          },
          {
            0x7fd9: [0x6],
          },
        ],
      },
      germany: {
        $and: [
          {
            0x7fc0: [
              0x4d, 0x59, 0x53, 0x54, 0x49, 0x43, 0x20, 0x51, 0x55, 0x45, 0x53,
              0x54, 0x20, 0x4c, 0x45, 0x47, 0x45, 0x4e, 0x44,
            ], // "MYSTIC QUEST LEGEND"
          },
          {
            0x7fd9: [0x9],
          },
        ],
      },
    },
    text: "Drag 'n' drop here or click to add a rom file.",
    error: "Not a valid rom file.",
  },
  items: [
    {
      type: "tabs",
      items: [
        {
          name: "Party",
          items: [
            {
              id: "party",
              pointer: 0x2ee,
              pointerDataType: "uint16",
              length: 0x50,
              type: "container",
              instanceType: "tabs",
              instances: 9,
              resource: "characterNames",
              vertical: true,
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "pName",
                      name: "Name",
                      offset: 0x0,
                      length: 0x8,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      fallback: 0x3,
                      resource: "letters",
                    },
                    {
                      name: "Level",
                      offset: 0x10,
                      type: "variable",
                      dataType: "uint8",
                      min: 1,
                      max: 41,
                    },
                    {
                      name: "Experience",
                      offset: 0x11,
                      type: "variable",
                      dataType: "uint24",
                      max: 9999999,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "HP",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          offset: 0x14,
                          type: "variable",
                          dataType: "uint16",
                          max: 1640,
                        },
                        {
                          offset: 0x16,
                          type: "variable",
                          dataType: "uint16",
                          min: 1,
                          max: 1640,
                        },
                      ],
                    },
                    {
                      name: "White Magic",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          offset: 0x18,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          offset: 0x1b,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                      ],
                    },
                    {
                      name: "Black Magic",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          offset: 0x19,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          offset: 0x1c,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                      ],
                    },
                    {
                      name: "Sorcery",
                      type: "group",
                      mode: "fraction",
                      items: [
                        {
                          offset: 0x1a,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                        {
                          offset: 0x1d,
                          type: "variable",
                          dataType: "uint8",
                          max: 99,
                        },
                      ],
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      id: "pStats",
                      name: "Attack",
                      offset: 0x4c,
                      type: "variable",
                      dataType: "uint8",
                      max: 200,
                    },
                    {
                      id: "pStats",
                      name: "Defense",
                      offset: 0x4d,
                      type: "variable",
                      dataType: "uint8",
                      max: 200,
                    },
                    {
                      id: "pStats",
                      name: "Speed",
                      offset: 0x4e,
                      type: "variable",
                      dataType: "uint8",
                      max: 200,
                    },
                    {
                      id: "pStats",
                      name: "Magic",
                      offset: 0x4f,
                      type: "variable",
                      dataType: "uint8",
                      max: 200,
                    },
                    {
                      name: "Accuracy",
                      offset: 0x40,
                      type: "variable",
                      dataType: "uint8",
                      max: 200,
                    },
                    {
                      name: "Evade",
                      offset: 0x41,
                      type: "variable",
                      dataType: "uint8",
                      disabled: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Equipped Weapon",
                      offset: 0x31,
                      type: "variable",
                      dataType: "uint8",
                      resource: "weapons",
                      autocomplete: true,
                    },
                    {
                      name: "Ammo Quantity",
                      offset: 0x30,
                      type: "variable",
                      dataType: "uint8",
                      max: 99,
                    },
                  ],
                },
                {
                  name: "Condition",
                  type: "bitflags",
                  flags: [
                    { offset: 0x21, bit: 0, label: "Silence" },
                    { offset: 0x21, bit: 1, label: "Blind" },
                    { offset: 0x21, bit: 2, label: "Poison" },
                    { offset: 0x21, bit: 7, label: "Fatal" },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Weapons",
                      type: "bitflags",
                      flags: [
                        { offset: 0x32, bit: 7, label: "Steel Sword" },
                        { offset: 0x32, bit: 6, label: "Knight Sword" },
                        { offset: 0x32, bit: 5, label: "Excalibur" },
                        { offset: 0x32, bit: 4, label: "Axe" },
                        { offset: 0x32, bit: 3, label: "Battle Axe" },
                        { offset: 0x32, bit: 2, label: "Giant's Axe" },
                        { offset: 0x32, bit: 1, label: "Cat Claw" },
                        { offset: 0x32, bit: 0, label: "Charm Claw" },
                        { offset: 0x33, bit: 7, label: "Dragon Claw" },
                        { offset: 0x33, bit: 6, label: "Bomb" },
                        { offset: 0x33, bit: 5, label: "Jumbo Bomb" },
                        { offset: 0x33, bit: 4, label: "Mega Grenade" },
                      ],
                    },
                    {
                      name: "Armors",
                      type: "bitflags",
                      flags: [
                        { offset: 0x35, bit: 7, label: "Steel Helm" },
                        { offset: 0x35, bit: 6, label: "Moon Helm" },
                        { offset: 0x35, bit: 5, label: "Apollo Helm" },
                        { offset: 0x35, bit: 4, label: "Steel Armor" },
                        { offset: 0x35, bit: 3, label: "Noble Armor" },
                        { offset: 0x35, bit: 2, label: "Gaia's Armor" },
                        { offset: 0x36, bit: 5, label: "Steel Shield" },
                        { offset: 0x36, bit: 4, label: "Venus Shield" },
                        { offset: 0x36, bit: 3, label: "Aegis Shield" },
                        { offset: 0x36, bit: 1, label: "Charm" },
                        { offset: 0x36, bit: 0, label: "Magic Ring" },
                        { offset: 0x37, bit: 7, label: "Cupid Locket" },
                      ],
                    },
                    {
                      name: "Spells",
                      type: "bitflags",
                      flags: [
                        { offset: 0x38, bit: 7, label: "Exit" },
                        { offset: 0x38, bit: 6, label: "Cure" },
                        { offset: 0x38, bit: 5, label: "Heal" },
                        { offset: 0x38, bit: 4, label: "Life" },
                        { offset: 0x38, bit: 3, label: "Quack" },
                        { offset: 0x38, bit: 2, label: "Blizzard" },
                        { offset: 0x38, bit: 1, label: "Fire" },
                        { offset: 0x38, bit: 0, label: "Aero" },
                        { offset: 0x39, bit: 7, label: "Thunder" },
                        { offset: 0x39, bit: 6, label: "White" },
                        { offset: 0x39, bit: 5, label: "Meteor" },
                        { offset: 0x39, bit: 4, label: "Flare" },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Items",
          planned: true,
          items: [],
        },
        {
          name: "Monsters",
          items: [
            {
              type: "component",
              component: "Monsters",
            },
          ],
        },
        {
          name: "Monster Groups",
          items: [
            {
              id: "monsterGroups",
              pointer: MONSTER_GROUPS_POINTER,
              pointerDataType: "uint16",
              length: 0x4,
              type: "container",
              instanceType: "tabs",
              instances: 234,
              resource: "monsterGroupNames",
              vertical: true,
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      type: "section",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "mgMonster",
                              name: "Monster 1",
                              offset: 0x0,
                              type: "variable",
                              dataType: "uint8",
                              resource: "monsterNames",
                              autocomplete: true,
                            },
                            {
                              id: "mgSpecial",
                              name: "Special",
                              offset: 0x0,
                              type: "variable",
                              dataType: "bit",
                              bit: 7,
                              resource: "monsterGroupsSpecial",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "mgMonster",
                              name: "Monster 2",
                              offset: 0x1,
                              type: "variable",
                              dataType: "uint8",
                              resource: "monsterNames",
                              autocomplete: true,
                            },
                            {
                              id: "mgSpecial",
                              name: "Special",
                              offset: 0x1,
                              type: "variable",
                              dataType: "bit",
                              bit: 7,
                              resource: "monsterGroupsSpecial",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "mgMonster",
                              name: "Monster 3",
                              offset: 0x2,
                              type: "variable",
                              dataType: "uint8",
                              resource: "monsterNames",
                              autocomplete: true,
                            },
                            {
                              id: "mgSpecial",
                              name: "Special",
                              offset: 0x2,
                              type: "variable",
                              dataType: "bit",
                              bit: 7,
                              resource: "monsterGroupsSpecial",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      type: "section",
                      items: [
                        {
                          name: "Battle Configuration",
                          type: "bitflags",
                          flags: [
                            { offset: 0x3, bit: 0, label: "???", hidden: true },
                            { offset: 0x3, bit: 1, label: "???", hidden: true },
                            { offset: 0x3, bit: 4, label: "???", hidden: true },
                            { offset: 0x3, bit: 5, label: "Animate Flying Monsters" },
                            { offset: 0x3, bit: 6, label: "Can't Escape" },
                            { offset: 0x3, bit: 7, label: "???", hidden: true },
                          ],
                        },
                        {
                          name: "Battle Music",
                          type: "bitflags",
                          hidden: true,
                          flags: [
                            { offset: 0x3, bit: 2, label: "Boss Music" },
                            { offset: 0x3, bit: 3, label: "Final Boss Music" },
                          ],
                        },
                        {
                          id: "mgBattleMusic",
                          name: "Battle Music",
                          offset: 0x3,
                          type: "variable",
                          dataType: "uint8",
                          resource: "battleMusics",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Battle Backgrounds",
          items: [
            {
              pointer: BATTLE_BACKGROUND_SETS_POINTER,
              instanceId: "battleBackgrounds",
              length: 0x3,
              type: "container",
              instanceType: "tabs",
              instances: 36,
              enumeration: "Background %d",
              vertical: true,
              flex: true,
              items: [
                {
                  type: "component",
                  component: "BattleBackgroundCanvas",
                  props: { backgroundIndex: "battleBackgrounds" },
                },
                {
                  type: "section",
                  items: [
                    {
                      name: "Tilesets",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Top",
                          offset: 0x0,
                          type: "variable",
                          dataType: "uint8",
                          max: 25,
                        },
                        {
                          name: "Bottom",
                          offset: 0x1,
                          type: "variable",
                          dataType: "lower4",
                          max: 13,
                        },
                      ],
                    },
                    {
                      name: "Palettes",
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Primary",
                          offset: 0x2,
                          type: "variable",
                          dataType: "uint8",
                          max: 25,
                        },
                        {
                          name: "Secondary",
                          offset: 0x1,
                          type: "variable",
                          dataType: "upper4",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Map Viewer",
          items: [
            {
              instanceId: "mapViewer",
              length: 0x2,
              type: "container",
              instanceType: "tabs",
              instances: 255,
              enumeration: "Map %d",
              vertical: true,
              flex: true,
              items: [
                {
                  type: "component",
                  component: "MapViewer",
                  props: { roomIndex: "mapViewer" },
                },
              ],
            },
          ],
        },
        {
          name: "Debug",
          hidden: true,
          items: [
            {
              type: "component",
              component: "Debug",
            },
          ],
        },
      ],
    },
  ],
  resources: {
    battleMusics: {
      0x0: "Normal",
      0x4: "Boss",
      0x8: "Final Boss",
      0xc: "-",
    },
    letters: [
      // Europe
      {
        0x3: " ",
        0x6: "#",
        0x90: "0",
        0x91: "1",
        0x92: "2",
        0x93: "3",
        0x94: "4",
        0x95: "5",
        0x96: "6",
        0x97: "7",
        0x98: "8",
        0x99: "9",
        0x9a: "A",
        0x9b: "B",
        0x9c: "C",
        0x9d: "D",
        0x9e: "E",
        0x9f: "F",
        0xa0: "G",
        0xa1: "H",
        0xa2: "I",
        0xa3: "J",
        0xa4: "K",
        0xa5: "L",
        0xa6: "M",
        0xa7: "N",
        0xa8: "O",
        0xa9: "P",
        0xaa: "Q",
        0xab: "R",
        0xac: "S",
        0xad: "T",
        0xae: "U",
        0xaf: "V",
        0xb0: "W",
        0xb1: "X",
        0xb2: "Y",
        0xb3: "Z",
        0xb4: "a",
        0xb5: "b",
        0xb6: "c",
        0xb7: "d",
        0xb8: "e",
        0xb9: "f",
        0xba: "g",
        0xbb: "h",
        0xbc: "i",
        0xbd: "j",
        0xbe: "k",
        0xbf: "l",
        0xc0: "m",
        0xc1: "n",
        0xc2: "o",
        0xc3: "p",
        0xc4: "q",
        0xc5: "r",
        0xc6: "s",
        0xc7: "t",
        0xc8: "u",
        0xc9: "v",
        0xca: "w",
        0xcb: "x",
        0xcc: "y",
        0xcd: "z",
        0xce: "!",
        0xcf: "?",
        0xd0: ",",
        0xd1: "'",
        0xd2: ".",
        0xd6: ";",
        0xd7: ":",
        0xd8: "…",
        0xd9: "/",
        0xda: "-",
        0xdb: "&",
        0xdc: ">",
        0xdd: "%",
        0xff: " ",
      },
      // USA
      {
        0x3: " ",
        0x6: "#",
        0x90: "0",
        0x91: "1",
        0x92: "2",
        0x93: "3",
        0x94: "4",
        0x95: "5",
        0x96: "6",
        0x97: "7",
        0x98: "8",
        0x99: "9",
        0x9a: "A",
        0x9b: "B",
        0x9c: "C",
        0x9d: "D",
        0x9e: "E",
        0x9f: "F",
        0xa0: "G",
        0xa1: "H",
        0xa2: "I",
        0xa3: "J",
        0xa4: "K",
        0xa5: "L",
        0xa6: "M",
        0xa7: "N",
        0xa8: "O",
        0xa9: "P",
        0xaa: "Q",
        0xab: "R",
        0xac: "S",
        0xad: "T",
        0xae: "U",
        0xaf: "V",
        0xb0: "W",
        0xb1: "X",
        0xb2: "Y",
        0xb3: "Z",
        0xb4: "a",
        0xb5: "b",
        0xb6: "c",
        0xb7: "d",
        0xb8: "e",
        0xb9: "f",
        0xba: "g",
        0xbb: "h",
        0xbc: "i",
        0xbd: "j",
        0xbe: "k",
        0xbf: "l",
        0xc0: "m",
        0xc1: "n",
        0xc2: "o",
        0xc3: "p",
        0xc4: "q",
        0xc5: "r",
        0xc6: "s",
        0xc7: "t",
        0xc8: "u",
        0xc9: "v",
        0xca: "w",
        0xcb: "x",
        0xcc: "y",
        0xcd: "z",
        0xce: "!",
        0xcf: "?",
        0xd0: ",",
        0xd1: "'",
        0xd2: ".",
        0xd6: ";",
        0xd7: ":",
        0xd8: "…",
        0xd9: "/",
        0xda: "-",
        0xdb: "&",
        0xdc: ">",
        0xdd: "%",
        0xff: " ",
      },
      // USA Rev 1
      {
        0x3: " ",
        0x6: "#",
        0x90: "0",
        0x91: "1",
        0x92: "2",
        0x93: "3",
        0x94: "4",
        0x95: "5",
        0x96: "6",
        0x97: "7",
        0x98: "8",
        0x99: "9",
        0x9a: "A",
        0x9b: "B",
        0x9c: "C",
        0x9d: "D",
        0x9e: "E",
        0x9f: "F",
        0xa0: "G",
        0xa1: "H",
        0xa2: "I",
        0xa3: "J",
        0xa4: "K",
        0xa5: "L",
        0xa6: "M",
        0xa7: "N",
        0xa8: "O",
        0xa9: "P",
        0xaa: "Q",
        0xab: "R",
        0xac: "S",
        0xad: "T",
        0xae: "U",
        0xaf: "V",
        0xb0: "W",
        0xb1: "X",
        0xb2: "Y",
        0xb3: "Z",
        0xb4: "a",
        0xb5: "b",
        0xb6: "c",
        0xb7: "d",
        0xb8: "e",
        0xb9: "f",
        0xba: "g",
        0xbb: "h",
        0xbc: "i",
        0xbd: "j",
        0xbe: "k",
        0xbf: "l",
        0xc0: "m",
        0xc1: "n",
        0xc2: "o",
        0xc3: "p",
        0xc4: "q",
        0xc5: "r",
        0xc6: "s",
        0xc7: "t",
        0xc8: "u",
        0xc9: "v",
        0xca: "w",
        0xcb: "x",
        0xcc: "y",
        0xcd: "z",
        0xce: "!",
        0xcf: "?",
        0xd0: ",",
        0xd1: "'",
        0xd2: ".",
        0xd6: ";",
        0xd7: ":",
        0xd8: "…",
        0xd9: "/",
        0xda: "-",
        0xdb: "&",
        0xdc: ">",
        0xdd: "%",
        0xff: " ",
      },
      // Japan
      {
        0x3: " ",
        0x6: "#",
        0x4b: "が",
        0x4c: "ぎ",
        0x4d: "ぐ",
        0x4e: "げ",
        0x4f: "ご",
        0x50: "ざ",
        0x51: "じ",
        0x52: "ず",
        0x53: "ぜ",
        0x54: "ぞ",
        0x55: "だ",
        0x56: "ぢ",
        0x57: "づ",
        0x58: "で",
        0x59: "ど",
        0x5a: "ば",
        0x5b: "び",
        0x5c: "ぶ",
        0x5d: "べ",
        0x5e: "ぼ",
        0x5f: "ぱ",
        0x60: "ぴ",
        0x61: "ぷ",
        0x62: "ぺ",
        0x63: "ぽ",
        0x64: "ヴ",
        0x65: "ガ",
        0x66: "ギ",
        0x67: "グ",
        0x68: "ゲ",
        0x69: "ゴ",
        0x6a: "ザ",
        0x6b: "ジ",
        0x6c: "ズ",
        0x6d: "ゼ",
        0x6e: "ゾ",
        0x6f: "ダ",
        0x70: "ヂ",
        0x71: "ヅ",
        0x72: "デ",
        0x73: "ド",
        0x74: "バ",
        0x75: "ビ",
        0x76: "ブ",
        0x77: "ベ",
        0x78: "ボ",
        0x79: "パ",
        0x7a: "ピ",
        0x7b: "プ",
        0x7c: "ペ",
        0x7d: "ポ",
        0x80: "あ",
        0x81: "い",
        0x82: "う",
        0x83: "え",
        0x84: "お",
        0x85: "か",
        0x86: "き",
        0x87: "く",
        0x88: "け",
        0x89: "こ",
        0x8a: "さ",
        0x8b: "し",
        0x8c: "す",
        0x8d: "せ",
        0x8e: "そ",
        0x8f: "た",
        0x90: "ち",
        0x91: "つ",
        0x92: "て",
        0x93: "と",
        0x94: "な",
        0x95: "に",
        0x96: "ぬ",
        0x97: "ね",
        0x98: "の",
        0x99: "は",
        0x9a: "ひ",
        0x9b: "ふ",
        0x9c: "へ",
        0x9d: "ほ",
        0x9e: "ま",
        0x9f: "み",
        0xa0: "む",
        0xa1: "め",
        0xa2: "も",
        0xa3: "や",
        0xa4: "ゆ",
        0xa5: "よ",
        0xa6: "ら",
        0xa7: "り",
        0xa8: "る",
        0xa9: "れ",
        0xaa: "ろ",
        0xab: "わ",
        0xac: "を",
        0xad: "ん",
        0xae: "ゃ",
        0xaf: "ゅ",
        0xb0: "ょ",
        0xb1: "っ",
        0xb2: "ぁ",
        0xb3: "ぃ",
        0xb4: "ぅ",
        0xb5: "ぇ",
        0xb6: "ぉ",
        0xb7: "ー",
        0xb8: "ア",
        0xb9: "イ",
        0xba: "ウ",
        0xbb: "エ",
        0xbc: "オ",
        0xbd: "カ",
        0xbe: "キ",
        0xbf: "ク",
        0xc0: "ケ",
        0xc1: "コ",
        0xc2: "サ",
        0xc3: "シ",
        0xc4: "ス",
        0xc5: "セ",
        0xc6: "ソ",
        0xc7: "タ",
        0xc8: "チ",
        0xc9: "ツ",
        0xca: "テ",
        0xcb: "ト",
        0xcc: "ナ",
        0xcd: "ニ",
        0xce: "ヌ",
        0xcf: "ネ",
        0xd0: "ノ",
        0xd1: "ハ",
        0xd2: "ヒ",
        0xd3: "フ",
        0xd4: "ヘ",
        0xd5: "ホ",
        0xd6: "マ",
        0xd7: "ミ",
        0xd8: "ム",
        0xd9: "メ",
        0xda: "モ",
        0xdb: "ヤ",
        0xdc: "ユ",
        0xdd: "ヨ",
        0xde: "ラ",
        0xdf: "リ",
        0xe0: "ル",
        0xe1: "レ",
        0xe2: "ロ",
        0xe3: "ワ",
        0xe4: "ヲ",
        0xe5: "ン",
        0xe6: "ャ",
        0xe7: "ュ",
        0xe8: "ョ",
        0xe9: "ッ",
        0xea: "ァ",
        0xeb: "ィ",
        0xec: "ゥ",
        0xed: "ェ",
        0xee: "ォ",
        0xef: "-",
        0xf0: "0",
        0xf1: "1",
        0xf2: "2",
        0xf3: "3",
        0xf4: "4",
        0xf5: "5",
        0xf6: "6",
        0xf7: "7",
        0xf8: "8",
        0xf9: "9",
        0xfa: "!",
        0xfb: "?",
        0xfc: "…",
        0xff: " ",
      },
      // France
      {
        0x3: " ",
        0x6: "#",
        0x80: "A",
        0x81: "B",
        0x82: "C",
        0x83: "D",
        0x84: "E",
        0x85: "F",
        0x86: "G",
        0x87: "H",
        0x88: "I",
        0x89: "J",
        0x8a: "K",
        0x8b: "L",
        0x8c: "M",
        0x8d: "N",
        0x8e: "O",
        0x8f: "P",
        0x90: "Q",
        0x91: "R",
        0x92: "S",
        0x93: "T",
        0x94: "U",
        0x95: "V",
        0x96: "W",
        0x97: "X",
        0x98: "Y",
        0x99: "Z",
        0x9a: "-",
        0x9b: "%",
        0x9c: "&",
        0x9d: ",",
        0x9e: "'",
        0x9f: " ",
        0xa0: "a",
        0xa1: "b",
        0xa2: "c",
        0xa3: "d",
        0xa4: "e",
        0xa5: "f",
        0xa6: "g",
        0xa7: "h",
        0xa8: "i",
        0xa9: "j",
        0xaa: "k",
        0xab: "l",
        0xac: "m",
        0xad: "n",
        0xae: "o",
        0xaf: "p",
        0xb0: "q",
        0xb1: "r",
        0xb2: "s",
        0xb3: "t",
        0xb4: "u",
        0xb5: "v",
        0xb6: "w",
        0xb7: "x",
        0xb8: "y",
        0xb9: "z",
        0xbe: ".",
        0xbf: " ",
        0xc0: "Ç",
        0xc1: "à",
        0xc2: "â",
        0xc3: "ô",
        0xc4: "ç",
        0xc5: "è",
        0xc6: "é",
        0xc7: "ê",
        0xc8: "ë",
        0xc9: "î",
        0xca: "ï",
        0xcb: "ù",
        0xcc: "û",
        0xcd: "ü",
        0xf0: "0",
        0xf1: "1",
        0xf2: "2",
        0xf3: "3",
        0xf4: "4",
        0xf5: "5",
        0xf6: "6",
        0xf7: "7",
        0xf8: "8",
        0xf9: "9",
        0xfa: "!",
        0xfb: "?",
        0xff: " ",
      },
      // Germany
      {
        0x3: " ",
        0x6: "#",
        0x80: "A",
        0x81: "B",
        0x82: "C",
        0x83: "D",
        0x84: "E",
        0x85: "F",
        0x86: "G",
        0x87: "H",
        0x88: "I",
        0x89: "J",
        0x8a: "K",
        0x8b: "L",
        0x8c: "M",
        0x8d: "N",
        0x8e: "O",
        0x8f: "P",
        0x90: "Q",
        0x91: "R",
        0x92: "S",
        0x93: "T",
        0x94: "U",
        0x95: "V",
        0x96: "W",
        0x97: "X",
        0x98: "Y",
        0x99: "Z",
        0x9a: "-",
        0x9b: "%",
        0x9c: "&",
        0x9d: ",",
        0x9e: "'",
        0x9f: " ",
        0xa0: "a",
        0xa1: "b",
        0xa2: "c",
        0xa3: "d",
        0xa4: "e",
        0xa5: "f",
        0xa6: "g",
        0xa7: "h",
        0xa8: "i",
        0xa9: "j",
        0xaa: "k",
        0xab: "l",
        0xac: "m",
        0xad: "n",
        0xae: "o",
        0xaf: "p",
        0xb0: "q",
        0xb1: "r",
        0xb2: "s",
        0xb3: "t",
        0xb4: "u",
        0xb5: "v",
        0xb6: "w",
        0xb7: "x",
        0xb8: "y",
        0xb9: "z",
        0xbe: ".",
        0xbf: " ",
        0xc0: "Ä",
        0xc1: "Ö",
        0xc2: "Ü",
        0xc3: "ä",
        0xc4: "ö",
        0xc5: "ü",
        0xc6: "ẞ",
        0xf0: "0",
        0xf1: "1",
        0xf2: "2",
        0xf3: "3",
        0xf4: "4",
        0xf5: "5",
        0xf6: "6",
        0xf7: "7",
        0xf8: "8",
        0xf9: "9",
        0xfa: "!",
        0xfb: "?",
        0xff: " ",
      },
    ],
    characterNames: "getCharacterNames()",
    locationNames: "getLocationNames()",
    monsterNames: "getMonsterNames()",
    monsterGroupNames: "getMonsterGroupNames()",
    monsterGroupsSpecial: {
      0x0: "-",
      0x1: "Fly",
    },
    weapons: {
      0x20: "Steel Sword",
      0x21: "Knight Sword",
      0x22: "Excalibur",
      0x23: "Axe",
      0x24: "Battle Axe",
      0x25: "Giant's Axe",
      0x26: "Cat Claw",
      0x27: "Charm Claw",
      0x28: "Dragon Claw",
      0x29: "Bomb",
      0x2a: "Jumbo Bomb",
      0x2b: "Mega Grenade",
      0x2c: "Morning Star",
      0x2d: "Bow of Grace",
      0x2e: "Ninja Star",
      0xff: "-",
    },
  },
  resourcesOrder: {
    battleMusics: [0xc],
    monsterNames: [0xff],
  },
};

export default template;
