import type { Resource } from "$lib/types";

export type BackpackItem = {
  ItemId: number;
  Num: number;
};

export const itemTypes = [
  { index: 0x0, name: "Items" },
  { index: 0x1, name: "Swords" },
  { index: 0x2, name: "Polearms" },
  { index: 0x3, name: "Daggers" },
  { index: 0x4, name: "Axes" },
  { index: 0x5, name: "Bows" },
  { index: 0x6, name: "Staves" },
  { index: 0x7, name: "Shields" },
  { index: 0x8, name: "Headgear" },
  { index: 0x9, name: "Body Armor" },
  { index: 0xa, name: "Accessories" },
  { index: 0xb, name: "Materials" },
  { index: 0xc, name: "Valuables" },
  { index: 0xd, name: "Knowledge" },
];

export const inventory = [
  { index: 0x012e, type: 0xc, name: "Book of Scripture" },
  { index: 0x0770, type: 0x0, name: "Healing Grape" },
  { index: 0x0771, type: 0x0, name: "Healing Grape (M)" },
  { index: 0x0772, type: 0x0, name: "Healing Grape Bunch" },
  { index: 0x0773, type: 0x0, name: "Inspiriting Plum" },
  { index: 0x0774, type: 0x0, name: "Inspiriting Plum (M)" },
  { index: 0x0775, type: 0x0, name: "Inspiriting Plum Basket" },
  { index: 0x0776, type: 0x0, name: "Energizing Pomegranate" },
  { index: 0x0777, type: 0x0, name: "Energizing Pomegranate (M)" },
  { index: 0x0778, type: 0x0, name: "Energizing Pomegranate (L)" },
  { index: 0x0779, type: 0x0, name: "Refreshing Jam" },
  { index: 0x077a, type: 0x0, name: "Revitalizing Jam" },
  { index: 0x077b, type: 0x0, name: "Olive of Life" },
  { index: 0x077c, type: 0x0, name: "Olive of Life (M)" },
  { index: 0x077d, type: 0x0, name: "Olive of Life (L)" },
  { index: 0x077e, type: 0x0, name: "Herb of Healing" },
  { index: 0x077f, type: 0x0, name: "Herb of Clamor" },
  { index: 0x0780, type: 0x0, name: "Herb of Light" },
  { index: 0x0781, type: 0x0, name: "Herb of Clarity" },
  { index: 0x0782, type: 0x0, name: "Herb of Awakening" },
  { index: 0x0783, type: 0x0, name: "Herb of Valor" },
  { index: 0x0784, type: 0x0, name: "Herb of Revival" },
  { index: 0x0785, type: 0x0, name: "Empowering Lychee" },
  { index: 0x0786, type: 0x0, name: "Empowering Lychee (M)" },
  { index: 0x0787, type: 0x0, name: "Empowering Lychee (L)" },
  { index: 0x0788, type: 0x0, name: "Bottle of Poison Dust" },
  { index: 0x0789, type: 0x0, name: "Bottle of Blinding Dust" },
  { index: 0x078a, type: 0x0, name: "Bottle of Befuddling Dust" },
  { index: 0x078b, type: 0x0, name: "Bottle of Sleeping Dust" },
  { index: 0x078c, type: 0x0, name: "Fire Soulstone" },
  { index: 0x078d, type: 0x0, name: "Fire Soulstone (M)" },
  { index: 0x078e, type: 0x0, name: "Fire Soulstone (L)" },
  { index: 0x078f, type: 0x0, name: "Ice Soulstone" },
  { index: 0x0790, type: 0x0, name: "Ice Soulstone (M)" },
  { index: 0x0791, type: 0x0, name: "Ice Soulstone (L)" },
  { index: 0x0792, type: 0x0, name: "Thunder Soulstone" },
  { index: 0x0793, type: 0x0, name: "Thunder Soulstone (M)" },
  { index: 0x0794, type: 0x0, name: "Thunder Soulstone (L)" },
  { index: 0x0795, type: 0x0, name: "Wind Soulstone" },
  { index: 0x0796, type: 0x0, name: "Wind Soulstone (M)" },
  { index: 0x0797, type: 0x0, name: "Wind Soulstone (L)" },
  { index: 0x0798, type: 0x0, name: "Light Soulstone" },
  { index: 0x0799, type: 0x0, name: "Light Soulstone (M)" },
  { index: 0x079a, type: 0x0, name: "Light Soulstone (L)" },
  { index: 0x079b, type: 0x0, name: "Shadow Soulstone" },
  { index: 0x079c, type: 0x0, name: "Shadow Soulstone (M)" },
  { index: 0x079d, type: 0x0, name: "Shadow Soulstone (L)" },
  { index: 0x079e, type: 0x0, name: "Nourishing Nut" },
  { index: 0x079f, type: 0x0, name: "Nourishing Nut (M)" },
  { index: 0x07a0, type: 0x0, name: "Nourishing Nut (L)" },
  { index: 0x07a1, type: 0x0, name: "Invigorating Nut" },
  { index: 0x07a2, type: 0x0, name: "Invigorating Nut (M)" },
  { index: 0x07a3, type: 0x0, name: "Invigorating Nut (L)" },
  { index: 0x07a4, type: 0x0, name: "Fortifying Nut" },
  { index: 0x07a5, type: 0x0, name: "Fortifying Nut (M)" },
  { index: 0x07a6, type: 0x0, name: "Fortifying Nut (L)" },
  { index: 0x07a7, type: 0x0, name: "Tough Nut" },
  { index: 0x07a8, type: 0x0, name: "Tough Nut (M)" },
  { index: 0x07a9, type: 0x0, name: "Tough Nut (L)" },
  { index: 0x07aa, type: 0x0, name: "Magic Nut" },
  { index: 0x07ab, type: 0x0, name: "Magic Nut (M)" },
  { index: 0x07ac, type: 0x0, name: "Magic Nut (L)" },
  { index: 0x07ad, type: 0x0, name: "Resistant Nut" },
  { index: 0x07ae, type: 0x0, name: "Resistant Nut (M)" },
  { index: 0x07af, type: 0x0, name: "Resistant Nut (L)" },
  { index: 0x07b0, type: 0x0, name: "Sharp Nut" },
  { index: 0x07b1, type: 0x0, name: "Sharp Nut (M)" },
  { index: 0x07b2, type: 0x0, name: "Sharp Nut (L)" },
  { index: 0x07b3, type: 0x0, name: "Slippery Nut" },
  { index: 0x07b4, type: 0x0, name: "Slippery Nut (M)" },
  { index: 0x07b5, type: 0x0, name: "Slippery Nut (L)" },
  { index: 0x07b6, type: 0x0, name: "Critical Nut" },
  { index: 0x07b7, type: 0x0, name: "Critical Nut (M)" },
  { index: 0x07b8, type: 0x0, name: "Critical Nut (L)" },
  { index: 0x07b9, type: 0x0, name: "Light Nut" },
  { index: 0x07ba, type: 0x0, name: "Light Nut (M)" },
  { index: 0x07bb, type: 0x0, name: "Light Nut (L)" },
  { index: 0x07bc, type: 0x0, name: "Stylish Nut" },
  { index: 0x07bf, type: 0x1, name: "Makeshift Sword" },
  { index: 0x07c0, type: 0x1, name: "Desert Blade" },
  { index: 0x07c3, type: 0x2, name: "Makeshift Spear" },
  { index: 0x07c4, type: 0x2, name: "Desert Spear" },
  { index: 0x07c8, type: 0x8, name: "Gray Helm" },
  { index: 0x07cb, type: 0x9, name: "Desert Attire" },
  { index: 0x07e9, type: 0x3, name: "Makeshift Knife" },
  { index: 0x07ea, type: 0x4, name: "Makeshift Axe" },
  { index: 0x07eb, type: 0x5, name: "Makeshift Bow" },
  { index: 0x07ec, type: 0x6, name: "Makeshift Staff" },
  { index: 0x07ed, type: 0xc, name: "Dubious Silver Nugget" },
  { index: 0x07ee, type: 0xc, name: "Papp's Medicine" },
  { index: 0x07f1, type: 0xc, name: "Earnings" },
  { index: 0x07f2, type: 0xc, name: "Tip" },
  { index: 0x07f4, type: 0xc, name: "Mama's Dress" },
  { index: 0x07f5, type: 0xc, name: "Osvald's Notebook" },
  { index: 0x07f6, type: 0xc, name: "Labor Report" },
  { index: 0x07f7, type: 0xc, name: "Cold-Weather Wear" },
  { index: 0x07fa, type: 0x1, name: "Thief's Sword" },
  { index: 0x07fb, type: 0x1, name: "Long Sword" },
  { index: 0x07fc, type: 0x1, name: "Nameless Sword" },
  { index: 0x07fd, type: 0x1, name: "Broadsword" },
  { index: 0x07fe, type: 0x1, name: "Silver Sword" },
  { index: 0x07ff, type: 0x1, name: "Guard's Saber" },
  { index: 0x0800, type: 0x1, name: "Heavy Blade" },
  { index: 0x0801, type: 0x1, name: "Champion's Sword" },
  { index: 0x0802, type: 0x1, name: "Refined Sword" },
  { index: 0x0803, type: 0x1, name: "Magic Eater" },
  { index: 0x0804, type: 0x1, name: "Little Crow" },
  { index: 0x0805, type: 0x1, name: "Warrior's Sword" },
  { index: 0x0806, type: 0x1, name: "Great Blade" },
  { index: 0x0807, type: 0x1, name: "Stonesplitter" },
  { index: 0x0808, type: 0x1, name: "Hypno Sword" },
  { index: 0x0809, type: 0x1, name: "Enchanted Edge" },
  { index: 0x080a, type: 0x1, name: "Sanctum Sword" },
  { index: 0x080b, type: 0x1, name: "Aegis Sword" },
  { index: 0x080c, type: 0x1, name: "Giant's Blade" },
  { index: 0x080d, type: 0x1, name: "Ogre's Bane" },
  { index: 0x080e, type: 0x1, name: "Bastard Sword" },
  { index: 0x080f, type: 0x1, name: "Keepsake Sword" },
  { index: 0x0810, type: 0x1, name: "Starsplitter" },
  { index: 0x0811, type: 0x1, name: "Quartz Blade" },
  { index: 0x0812, type: 0x1, name: "Heretic's Greatsword" },
  { index: 0x0813, type: 0x1, name: "Skypiercer" },
  { index: 0x0814, type: 0x1, name: "Forbidden Blade" },
  { index: 0x0815, type: 0x1, name: "Battle-Tested Blade" },
  { index: 0x0817, type: 0x1, name: "Eclipse Edge" },
  { index: 0x0818, type: 0x1, name: "Serpent Slayer" },
  { index: 0x0819, type: 0x1, name: "Bloodsucker" },
  { index: 0x081a, type: 0x1, name: "Crescent Saber" },
  { index: 0x081b, type: 0x2, name: "Handmade Spear" },
  { index: 0x081c, type: 0x2, name: "Spear" },
  { index: 0x081d, type: 0x2, name: "Long Spear" },
  { index: 0x081e, type: 0x2, name: "Bone Spear" },
  { index: 0x081f, type: 0x2, name: "Sandstorm Spear" },
  { index: 0x0820, type: 0x2, name: "Fuscina" },
  { index: 0x0821, type: 0x2, name: "Steel Lance" },
  { index: 0x0822, type: 0x2, name: "Slashing Glaive" },
  { index: 0x0823, type: 0x2, name: "Soldier's Spear" },
  { index: 0x0824, type: 0x2, name: "Heavy Bone Spear" },
  { index: 0x0825, type: 0x2, name: "Paladin's Lance" },
  { index: 0x0826, type: 0x2, name: "Lightning Glaive" },
  { index: 0x0827, type: 0x2, name: "Obsidian Lance" },
  { index: 0x0828, type: 0x2, name: "Hyperion Spear" },
  { index: 0x0829, type: 0x2, name: "Monster Bone Spear" },
  { index: 0x082a, type: 0x2, name: "Gravity Lance" },
  { index: 0x082b, type: 0x2, name: "Crimson Spear" },
  { index: 0x082c, type: 0x2, name: "Rare Metal Glaive" },
  { index: 0x082d, type: 0x2, name: "Spear of Sleep" },
  { index: 0x082e, type: 0x2, name: "Scorched Bone Spear" },
  { index: 0x082f, type: 0x2, name: "Nightmare Glaive" },
  { index: 0x0830, type: 0x2, name: "Seraphim Spear" },
  { index: 0x0831, type: 0x2, name: "Sea God's Spear" },
  { index: 0x0832, type: 0x2, name: "Venom Lance" },
  { index: 0x0833, type: 0x2, name: "Spear of Strength" },
  { index: 0x0834, type: 0x2, name: "Forbidden Spear" },
  { index: 0x0835, type: 0x2, name: "Battle-Tested Spear" },
  { index: 0x0836, type: 0x2, name: "Thunder's Roar" },
  { index: 0x0837, type: 0x2, name: "Well-Worn Pole" },
  { index: 0x0839, type: 0x2, name: "Gluttonous Glaive" },
  { index: 0x083b, type: 0x3, name: "Thief's Dagger" },
  { index: 0x083c, type: 0x3, name: "Fruit Knife" },
  { index: 0x083d, type: 0x3, name: "Dagger" },
  { index: 0x083e, type: 0x3, name: "Bronze Knife" },
  { index: 0x083f, type: 0x3, name: "Kukri" },
  { index: 0x0840, type: 0x3, name: "Handbreaker" },
  { index: 0x0841, type: 0x3, name: "Falcon Knife" },
  { index: 0x0842, type: 0x3, name: "Crystal Dagger" },
  { index: 0x0843, type: 0x3, name: "Swordbreaker" },
  { index: 0x0844, type: 0x3, name: "Stinging Dagger" },
  { index: 0x0845, type: 0x3, name: "Champion Seeker" },
  { index: 0x0846, type: 0x3, name: "Stealthy Knife" },
  { index: 0x0847, type: 0x3, name: "Obsidian Dagger" },
  { index: 0x0848, type: 0x3, name: "Doombreaker" },
  { index: 0x0849, type: 0x3, name: "Assassin's Dagger" },
  { index: 0x084a, type: 0x3, name: "Diamond Dagger" },
  { index: 0x084b, type: 0x3, name: "Ornate Dagger" },
  { index: 0x084c, type: 0x3, name: "Dagger of Seclusion" },
  { index: 0x084d, type: 0x3, name: "Quartz Dagger" },
  { index: 0x084e, type: 0x3, name: "Wind Whisperer" },
  { index: 0x084f, type: 0x3, name: "Black Dagger" },
  { index: 0x0850, type: 0x3, name: "Tonfa" },
  { index: 0x0851, type: 0x3, name: "Mysterious Dagger" },
  { index: 0x0852, type: 0x3, name: "Bloodstained Knife" },
  { index: 0x0853, type: 0x3, name: "Ruinous Dagger" },
  { index: 0x0854, type: 0x3, name: "Forbidden Dagger" },
  { index: 0x0855, type: 0x3, name: "Battle-Tested Dagger" },
  { index: 0x0856, type: 0x3, name: "Marietta" },
  { index: 0x0857, type: 0x3, name: "Poison Dagger" },
  { index: 0x0859, type: 0x3, name: "Drifting Dagger" },
  { index: 0x085b, type: 0x4, name: "Demolition Axe" },
  { index: 0x085c, type: 0x4, name: "Small Axe" },
  { index: 0x085d, type: 0x4, name: "Handaxe" },
  { index: 0x085e, type: 0x4, name: "Woodcutter's Great Axe" },
  { index: 0x085f, type: 0x4, name: "Iron Axe" },
  { index: 0x0860, type: 0x4, name: "Guard's Great Axe" },
  { index: 0x0861, type: 0x4, name: "Battle Hatchet" },
  { index: 0x0862, type: 0x4, name: "Strong Axe" },
  { index: 0x0863, type: 0x4, name: "Bone Cleaver" },
  { index: 0x0864, type: 0x4, name: "Rock Cleaver" },
  { index: 0x0865, type: 0x4, name: "Grand Cleaver" },
  { index: 0x0866, type: 0x4, name: "Silver Hatchet" },
  { index: 0x0867, type: 0x4, name: "Guardian's Axe" },
  { index: 0x0868, type: 0x4, name: "Pirate's Axe" },
  { index: 0x0869, type: 0x4, name: "Platinum Hatchet" },
  { index: 0x086a, type: 0x4, name: "Cleaver of Destruction" },
  { index: 0x086b, type: 0x4, name: "Guillotine's Blade" },
  { index: 0x086c, type: 0x4, name: "Imperial Axe" },
  { index: 0x086d, type: 0x4, name: "Frontier Axe" },
  { index: 0x086e, type: 0x4, name: "Helmcleaver" },
  { index: 0x086f, type: 0x4, name: "Axe of the Conqueror" },
  { index: 0x0870, type: 0x4, name: "Frost Axe" },
  { index: 0x0871, type: 0x4, name: "Poisoned Hatchet" },
  { index: 0x0872, type: 0x4, name: "Quartz Axe" },
  { index: 0x0873, type: 0x4, name: "Dark Slasher" },
  { index: 0x0874, type: 0x4, name: "Double Tomahawk" },
  { index: 0x0875, type: 0x4, name: "Forbidden Axe" },
  { index: 0x0876, type: 0x4, name: "Battle-Tested Axe" },
  { index: 0x0877, type: 0x4, name: "Axe of Avarice" },
  { index: 0x087a, type: 0x4, name: "Reaper's Sickle" },
  { index: 0x087b, type: 0x4, name: "Stupefying Stone Axe" },
  { index: 0x087c, type: 0x5, name: "Bow" },
  { index: 0x087d, type: 0x5, name: "Handmade Bow" },
  { index: 0x087e, type: 0x5, name: "Shortbow" },
  { index: 0x087f, type: 0x5, name: "Beastling's Bow" },
  { index: 0x0880, type: 0x5, name: "Composite Bow" },
  { index: 0x0881, type: 0x5, name: "Traveler's Bow" },
  { index: 0x0882, type: 0x5, name: "Guard's Greatbow" },
  { index: 0x0883, type: 0x5, name: "Assault Bow" },
  { index: 0x0884, type: 0x5, name: "Sailor's Bow" },
  { index: 0x0885, type: 0x5, name: "Steel Bow" },
  { index: 0x0886, type: 0x5, name: "Soldier's Bow" },
  { index: 0x0887, type: 0x5, name: "Knight's Greatbow" },
  { index: 0x0888, type: 0x5, name: "Marksman's Bow" },
  { index: 0x0889, type: 0x5, name: "Sniper's Bow" },
  { index: 0x088a, type: 0x5, name: "Expert's Bow" },
  { index: 0x088b, type: 0x5, name: "Protector's Bow" },
  { index: 0x088c, type: 0x5, name: "Art of Archery" },
  { index: 0x088d, type: 0x5, name: "King of Beasts" },
  { index: 0x088e, type: 0x5, name: "Raging Beast" },
  { index: 0x088f, type: 0x5, name: "Master's Greatbow" },
  { index: 0x0890, type: 0x5, name: "Shadow Bow" },
  { index: 0x0891, type: 0x5, name: "Mirage Bow" },
  { index: 0x0892, type: 0x5, name: "Absolute Zero Bow" },
  { index: 0x0893, type: 0x5, name: "Tornado Bow" },
  { index: 0x0894, type: 0x5, name: "Mechanical Bow" },
  { index: 0x0895, type: 0x5, name: "Forbidden Bow" },
  { index: 0x0896, type: 0x5, name: "Battle-Tested Bow" },
  { index: 0x0897, type: 0x5, name: "Bow of Carnage" },
  { index: 0x0898, type: 0x5, name: "Leviathan Greatbow" },
  { index: 0x089a, type: 0x5, name: "Cupid's Bow" },
  { index: 0x089c, type: 0x6, name: "Stick" },
  { index: 0x089d, type: 0x6, name: "Staff of Judgment" },
  { index: 0x089e, type: 0x6, name: "Charm Rod" },
  { index: 0x089f, type: 0x6, name: "Wooden Staff" },
  { index: 0x08a0, type: 0x6, name: "Light Wand" },
  { index: 0x08a1, type: 0x6, name: "Mace" },
  { index: 0x08a2, type: 0x6, name: "Lapis Rod" },
  { index: 0x08a3, type: 0x6, name: "Mage Wand" },
  { index: 0x08a4, type: 0x6, name: "Magus Wand" },
  { index: 0x08a5, type: 0x6, name: "Flail" },
  { index: 0x08a6, type: 0x6, name: "Sapphire Rod" },
  { index: 0x08a7, type: 0x6, name: "Aegis Mace" },
  { index: 0x08a8, type: 0x6, name: "Fortune Wand" },
  { index: 0x08a9, type: 0x6, name: "Rod of Wisdom" },
  { index: 0x08aa, type: 0x6, name: "Quartz Rod" },
  { index: 0x08ab, type: 0x6, name: "Wisdom Wand" },
  { index: 0x08ac, type: 0x6, name: "Yggdrasil Staff" },
  { index: 0x08ad, type: 0x6, name: "Diamond Rod" },
  { index: 0x08ae, type: 0x6, name: "Ancient Staff" },
  { index: 0x08af, type: 0x6, name: "Thunder Mace" },
  { index: 0x08b0, type: 0x6, name: "Jade Staff" },
  { index: 0x08b1, type: 0x6, name: "Magic Breaker" },
  { index: 0x08b2, type: 0x6, name: "Hallowed Rod" },
  { index: 0x08b3, type: 0x6, name: "Abyssal Rod" },
  { index: 0x08b4, type: 0x6, name: "Giant's Club" },
  { index: 0x08b5, type: 0x6, name: "Forbidden Staff" },
  { index: 0x08b6, type: 0x6, name: "Battle-Tested Staff" },
  { index: 0x08b7, type: 0x6, name: "Staff of Carnage" },
  { index: 0x08b9, type: 0x6, name: "Great Sage's Staff" },
  { index: 0x08ba, type: 0x6, name: "Chef's Ladle" },
  { index: 0x08bc, type: 0x7, name: "Makeshift Shield" },
  { index: 0x08bd, type: 0x7, name: "Gray Shield" },
  { index: 0x08be, type: 0x7, name: "Small Shield" },
  { index: 0x08bf, type: 0x7, name: "Buckler" },
  { index: 0x08c0, type: 0x7, name: "Bronze Shield" },
  { index: 0x08c1, type: 0x7, name: "Leather Buckler" },
  { index: 0x08c2, type: 0x7, name: "Sturdy Shield" },
  { index: 0x08c3, type: 0x7, name: "Kite Shield" },
  { index: 0x08c4, type: 0x7, name: "Round Shield" },
  { index: 0x08c5, type: 0x7, name: "Guard's Shield" },
  { index: 0x08c6, type: 0x7, name: "Iron Shield" },
  { index: 0x08c7, type: 0x7, name: "Crested Greatshield" },
  { index: 0x08c8, type: 0x7, name: "Shell Buckler" },
  { index: 0x08c9, type: 0x7, name: "Silver Shield" },
  { index: 0x08ca, type: 0x7, name: "Spiked Shield" },
  { index: 0x08cb, type: 0x7, name: "Feather Shield" },
  { index: 0x08cc, type: 0x7, name: "Plate Buckler" },
  { index: 0x08cd, type: 0x7, name: "Forbidden Shield" },
  { index: 0x08ce, type: 0x7, name: "Battle-Tested Shield" },
  { index: 0x08cf, type: 0x7, name: "Heavy Greatshield" },
  { index: 0x08d0, type: 0x7, name: "Aegis Shield" },
  { index: 0x08d1, type: 0x7, name: "Platinum Shield" },
  { index: 0x08d2, type: 0x7, name: "Adamantine Buckler" },
  { index: 0x08d3, type: 0x7, name: "Swift Shield" },
  { index: 0x08d4, type: 0x8, name: "Leather Hat" },
  { index: 0x08d5, type: 0x8, name: "Ordinary Hat" },
  { index: 0x08d6, type: 0x8, name: "Leather Helm" },
  { index: 0x08d7, type: 0x8, name: "Festival Garland" },
  { index: 0x08d8, type: 0x8, name: "Fur Cap" },
  { index: 0x08d9, type: 0x8, name: "Hide Hood" },
  { index: 0x08da, type: 0x8, name: "Bronze Helm" },
  { index: 0x08db, type: 0x8, name: "Feathered Hat" },
  { index: 0x08dc, type: 0x8, name: "Guard's Helm" },
  { index: 0x08dd, type: 0x8, name: "Pointed Hat" },
  { index: 0x08de, type: 0x8, name: "Cassius" },
  { index: 0x08df, type: 0x8, name: "Headgear" },
  { index: 0x08e0, type: 0x8, name: "Silver Hairpiece" },
  { index: 0x08e1, type: 0x8, name: "Battle Bandana" },
  { index: 0x08e2, type: 0x8, name: "Hasty Helm" },
  { index: 0x08e3, type: 0x8, name: "Horned Helm" },
  { index: 0x08e4, type: 0x8, name: "Skull Helm" },
  { index: 0x08e5, type: 0x8, name: "Knight's Helm" },
  { index: 0x08e6, type: 0x8, name: "Fighter's Headband" },
  { index: 0x08e7, type: 0x8, name: "Starlight Hat" },
  { index: 0x08e8, type: 0x8, name: "Great Helm" },
  { index: 0x08e9, type: 0x8, name: "Platinum Helm" },
  { index: 0x08ea, type: 0x8, name: "Imperial Helm" },
  { index: 0x08eb, type: 0x8, name: "Forgotten Hat" },
  { index: 0x08ec, type: 0x8, name: "Gimmick Goggles" },
  { index: 0x08ed, type: 0x8, name: "Ancient Circlet" },
  { index: 0x08ee, type: 0x8, name: "Gelid Helm" },
  { index: 0x08ef, type: 0x8, name: "Guard's Hat" },
  { index: 0x08f0, type: 0x8, name: "Silent Bandana" },
  { index: 0x08f1, type: 0x8, name: "Antique Ceremonial Mask" },
  { index: 0x08f2, type: 0x8, name: "Dragon's Helm" },
  { index: 0x08f3, type: 0x8, name: "Dazzling Tiara" },
  { index: 0x08f4, type: 0x8, name: "Peddler's Feathered Cap" },
  { index: 0x08f5, type: 0x8, name: "Gaudy Hat" },
  { index: 0x08f6, type: 0x8, name: "Lighthouse Keeper's Bandana" },
  { index: 0x08f7, type: 0x8, name: "Mechanical Top Hat" },
  { index: 0x08f8, type: 0x8, name: "Pathfinder's Hat" },
  { index: 0x08f9, type: 0x8, name: "Cloth Hood" },
  { index: 0x08fa, type: 0x8, name: "Art of Disguise" },
  { index: 0x08fb, type: 0x8, name: "Black Cap" },
  { index: 0x08fc, type: 0x8, name: "Royal Guard's Helm" },
  { index: 0x08fd, type: 0x8, name: "Worker's Helmet" },
  { index: 0x08fe, type: 0x8, name: "Cloth Headband" },
  { index: 0x08ff, type: 0x8, name: "Soldier's Hat" },
  { index: 0x0900, type: 0x8, name: "Cursed Helm" },
  { index: 0x0901, type: 0x9, name: "Prisoner's Clothes" },
  { index: 0x0902, type: 0x9, name: "Apothecary's Attire" },
  { index: 0x0903, type: 0x9, name: "Frog Membrane" },
  { index: 0x0904, type: 0x9, name: "Tattered Dress" },
  { index: 0x0905, type: 0x9, name: "Robe" },
  { index: 0x0906, type: 0x9, name: "Black Attire" },
  { index: 0x0907, type: 0x9, name: "Villager's Clothes" },
  { index: 0x0908, type: 0x9, name: "Fur Armor" },
  { index: 0x0909, type: 0x9, name: "Copper Breastplate" },
  { index: 0x090a, type: 0x9, name: "Pilgrim's Robe" },
  { index: 0x090b, type: 0x9, name: "Hunting Attire" },
  { index: 0x090c, type: 0x9, name: "Traveler's Mantle" },
  { index: 0x090d, type: 0x9, name: "Fur Robe" },
  { index: 0x090e, type: 0x9, name: "Guard's Armor" },
  { index: 0x090f, type: 0x9, name: "Feather Mantle" },
  { index: 0x0910, type: 0x9, name: "Champion's Garb" },
  { index: 0x0911, type: 0x9, name: "Sailor's Vest" },
  { index: 0x0912, type: 0x9, name: "Iron Mail" },
  { index: 0x0913, type: 0x9, name: "Charm Robe" },
  { index: 0x0914, type: 0x9, name: "Nimble Mantle" },
  { index: 0x0915, type: 0x9, name: "Dojo Hakama" },
  { index: 0x0916, type: 0x9, name: "Elemental Robe" },
  { index: 0x0917, type: 0x9, name: "Falcon Coat" },
  { index: 0x0918, type: 0x9, name: "Acrobat's Mantle" },
  { index: 0x0919, type: 0x9, name: "Knight's Armor" },
  { index: 0x091a, type: 0x9, name: "Mage's Robe" },
  { index: 0x091b, type: 0x9, name: "Denim Work Clothes" },
  { index: 0x091c, type: 0x9, name: "Platinum Mail" },
  { index: 0x091d, type: 0x9, name: "Quick Cloak" },
  { index: 0x091e, type: 0x9, name: "Quartz Robe" },
  { index: 0x091f, type: 0x9, name: "Ornate Costume" },
  { index: 0x0920, type: 0x9, name: "Desert Plate" },
  { index: 0x0921, type: 0x9, name: "Simple Costume" },
  { index: 0x0922, type: 0x9, name: "Wind Robe" },
  { index: 0x0923, type: 0x9, name: "Bone Mail" },
  { index: 0x0924, type: 0x9, name: "Vest of Joy" },
  { index: 0x0925, type: 0x9, name: "Lightning Armor" },
  { index: 0x0926, type: 0x9, name: "Resplendent Costume" },
  { index: 0x0927, type: 0x9, name: "Dragon Mail" },
  { index: 0x0928, type: 0x9, name: "Antique Coat" },
  { index: 0x0929, type: 0x9, name: "Beastling Battle Armor" },
  { index: 0x092a, type: 0x9, name: "Imperial Armor" },
  { index: 0x092b, type: 0x9, name: "Dyed Clothes" },
  { index: 0x092c, type: 0x9, name: "Butler's Tailcoat" },
  { index: 0x092d, type: 0x9, name: "Conjurer's Raiment" },
  { index: 0x092e, type: 0x9, name: "Sublime Ornamental Armor" },
  { index: 0x092f, type: 0x9, name: "Quality Vest" },
  { index: 0x0930, type: 0x9, name: "Gorgeous Sari" },
  { index: 0x0931, type: 0x9, name: "White Wolf Scarf" },
  { index: 0x0932, type: 0x9, name: "Worker's Jacket" },
  { index: 0x0933, type: 0x9, name: "Royal Guard's Mail" },
  { index: 0x0934, type: 0x9, name: "Protector's Vestments" },
  { index: 0x0935, type: 0x9, name: "Blessed Vestments" },
  { index: 0x0936, type: 0x9, name: "Cursed Armor" },
  { index: 0x0937, type: 0xa, name: "Dragon's Scarf" },
  { index: 0x0938, type: 0xa, name: "Beastly Scarf" },
  { index: 0x0939, type: 0xa, name: "Spurning Ribbon" },
  { index: 0x093a, type: 0xa, name: "Alluring Ribbon" },
  { index: 0x093b, type: 0xa, name: "EXP Augmentor" },
  { index: 0x093c, type: 0xa, name: "JP Augmentor" },
  { index: 0x093d, type: 0xa, name: "Empowering Necklace" },
  { index: 0x093e, type: 0xa, name: "Stimulating Necklace" },
  { index: 0x093f, type: 0xa, name: "Protective Necklace" },
  { index: 0x0940, type: 0xa, name: "Unerring Necklace" },
  { index: 0x0941, type: 0xa, name: "Enlightening Necklace" },
  { index: 0x0942, type: 0xa, name: "Sprightly Necklace" },
  { index: 0x0943, type: 0xa, name: "Critical Necklace" },
  { index: 0x0944, type: 0xa, name: "Tattered Shoes" },
  { index: 0x0945, type: 0xa, name: "Empowering Bracelet" },
  { index: 0x0946, type: 0xa, name: "Stimulating Bracelet" },
  { index: 0x0947, type: 0xa, name: "Protective Bracelet" },
  { index: 0x0948, type: 0xa, name: "Unerring Bracelet" },
  { index: 0x0949, type: 0xa, name: "Enlightening Bracelet" },
  { index: 0x094a, type: 0xa, name: "Sprightly Bracelet" },
  { index: 0x094b, type: 0xa, name: "Critical Bracelet" },
  { index: 0x094c, type: 0xa, name: "Physical Belt" },
  { index: 0x094d, type: 0xa, name: "Mental Belt" },
  { index: 0x094e, type: 0xa, name: "Mighty Belt" },
  { index: 0x094f, type: 0xa, name: "Elemental Augmentor" },
  { index: 0x0950, type: 0xa, name: "Blazon of Protection" },
  { index: 0x0951, type: 0xa, name: "Empowering Ring" },
  { index: 0x0952, type: 0xa, name: "Stimulating Ring" },
  { index: 0x0953, type: 0xa, name: "Protective Ring" },
  { index: 0x0954, type: 0xa, name: "Unerring Ring" },
  { index: 0x0955, type: 0xa, name: "Enlightening Ring" },
  { index: 0x0956, type: 0xa, name: "Sprightly Ring" },
  { index: 0x0957, type: 0xa, name: "Critical Ring" },
  { index: 0x0958, type: 0xa, name: "Guardian Amulet" },
  { index: 0x0959, type: 0xa, name: "Elemental Ward" },
  { index: 0x095a, type: 0xa, name: "Empowering Earring" },
  { index: 0x095b, type: 0xa, name: "Stimulating Earring" },
  { index: 0x095c, type: 0xa, name: "Protective Earring" },
  { index: 0x095d, type: 0xa, name: "Unerring Earring" },
  { index: 0x095e, type: 0xa, name: "Enlightening Earring" },
  { index: 0x095f, type: 0xa, name: "Sprightly Earring" },
  { index: 0x0960, type: 0xa, name: "Critical Earring" },
  { index: 0x0961, type: 0xa, name: "Traveler's Charm" },
  { index: 0x0962, type: 0xa, name: "Silver Locket" },
  { index: 0x0963, type: 0xa, name: "Wargod's Talisman" },
  { index: 0x0964, type: 0xa, name: "Inferno Amulet" },
  { index: 0x0965, type: 0xa, name: "Blizzard Amulet" },
  { index: 0x0966, type: 0xa, name: "Tempest Amulet" },
  { index: 0x0967, type: 0xa, name: "Thunderstorm Amulet" },
  { index: 0x0968, type: 0xa, name: "Void Amulet" },
  { index: 0x0969, type: 0xa, name: "Gleaming Amulet" },
  { index: 0x096a, type: 0xa, name: "Fire Amulet" },
  { index: 0x096b, type: 0xa, name: "Ice Amulet" },
  { index: 0x096c, type: 0xa, name: "Wind Amulet" },
  { index: 0x096d, type: 0xa, name: "Lightning Amulet" },
  { index: 0x096e, type: 0xa, name: "Dark Amulet" },
  { index: 0x096f, type: 0xa, name: "Light Amulet" },
  { index: 0x0970, type: 0xa, name: "Antidote Stone" },
  { index: 0x0971, type: 0xa, name: "Wakeful Stone" },
  { index: 0x0972, type: 0xa, name: "Articulate Stone" },
  { index: 0x0973, type: 0xa, name: "Bright Stone" },
  { index: 0x0974, type: 0xa, name: "Calming Stone" },
  { index: 0x0975, type: 0xa, name: "Clarity Stone" },
  { index: 0x0976, type: 0xa, name: "Conscious Stone" },
  { index: 0x0977, type: 0xa, name: "Vivifying Stone" },
  { index: 0x0978, type: 0xa, name: "Cait Powder" },
  { index: 0x0979, type: 0xa, name: "Octopuff Pot" },
  { index: 0x097a, type: 0xa, name: "Melia's Amulet" },
  { index: 0x097b, type: 0xa, name: "Victory Ring" },
  { index: 0x097c, type: 0xa, name: "Enfeebling Amulet" },
  { index: 0x097d, type: 0xa, name: "Prosperity Charm" },
  { index: 0x097e, type: 0xa, name: "Charm of Compassion" },
  { index: 0x097f, type: 0xa, name: "Alpione's Amulet" },
  { index: 0x0980, type: 0xa, name: "Librarian's Amulet" },
  { index: 0x0981, type: 0xa, name: "Champion's Belt" },
  { index: 0x2710, type: 0x0, name: "Scorched Horseshoe" },
  { index: 0x2711, type: 0x0, name: "Stuffed Toy" },
  { index: 0x2712, type: 0x0, name: "Candy" },
  { index: 0x2713, type: 0x0, name: "Glass Marble" },
  { index: 0x2714, type: 0x0, name: "Handkerchief" },
  { index: 0x2715, type: 0x0, name: "Azuki Porridge" },
  { index: 0x2716, type: 0x0, name: "Thick Tome" },
  { index: 0x2717, type: 0x0, name: "Couple's Pendant" },
  { index: 0x2718, type: 0x0, name: "Tree Nut" },
  { index: 0x2719, type: 0x0, name: "Hairbrush" },
  { index: 0x271a, type: 0x0, name: "Light Coin Pouch" },
  { index: 0x271b, type: 0x0, name: "Forbidden Elixir" },
  { index: 0x271c, type: 0x0, name: "Chipped Dish" },
  { index: 0x271d, type: 0x0, name: "Crimson Rose" },
  { index: 0x271e, type: 0x0, name: "Bone" },
  { index: 0x271f, type: 0x0, name: "Silk Handkerchief" },
  { index: 0x2720, type: 0x0, name: "Poetry of the Soul" },
  { index: 0x2721, type: 0x0, name: "Rich Ale" },
  { index: 0x2722, type: 0x0, name: "Red Apple" },
  { index: 0x2723, type: 0x0, name: "Complex Tome" },
  { index: 0x2724, type: 0x0, name: "Scrap Iron" },
  { index: 0x2725, type: 0x0, name: "Cog" },
  { index: 0x2726, type: 0x0, name: "Heavy Book" },
  { index: 0x2727, type: 0x0, name: "Rare Cog" },
  { index: 0x2728, type: 0x0, name: "Stone" },
  { index: 0x2729, type: 0x0, name: "STuFfeD ToY" },
  { index: 0x272a, type: 0x0, name: "Small Silver Ore" },
  { index: 0x272b, type: 0x0, name: "Large Silver Ore" },
  { index: 0x272c, type: 0x0, name: "Herb-of-Grace Bud" },
  { index: 0x272d, type: 0x0, name: "Skystone" },
  { index: 0x272e, type: 0x0, name: "Aged Wine" },
  { index: 0x272f, type: 0x0, name: "Introduction to Trade" },
  { index: 0x2730, type: 0x0, name: "Gold Nugget" },
  { index: 0x2731, type: 0x0, name: "Handmade Rice Ball" },
  { index: 0x2732, type: 0x0, name: "Alrond's Promissory Note" },
  { index: 0x2733, type: 0x0, name: "Dumbbell" },
  { index: 0x2734, type: 0x0, name: "Thick Magic Tome" },
  { index: 0x2735, type: 0x0, name: "Sunken Gold Statue" },
  { index: 0x2745, type: 0xc, name: "Brothel Girl's Clothes" },
  { index: 0x274a, type: 0x1, name: "Knight's Sword" },
  { index: 0x274b, type: 0x3, name: "Sharp Stone" },
  { index: 0x274c, type: 0x4, name: "Woodcutter's Axe" },
  { index: 0x274d, type: 0x4, name: "Snake Fang" },
  { index: 0x274e, type: 0x7, name: "Resplendent Shield" },
  { index: 0x274f, type: 0x7, name: "Wooden Shield" },
  { index: 0x2750, type: 0x8, name: "Sanctum Knight's Helm" },
  { index: 0x2751, type: 0x8, name: "Black Hood" },
  { index: 0x2752, type: 0x9, name: "Sanctum Knight's Armor" },
  { index: 0x2753, type: 0x9, name: "Tough Waistcoat" },
  { index: 0x277b, type: 0x1, name: "Sword of the Sands" },
  { index: 0x277c, type: 0x2, name: "Distinguished Lance" },
  { index: 0x278b, type: 0xc, name: "Merchant License" },
  { index: 0x278c, type: 0xc, name: "Thief License" },
  { index: 0x278d, type: 0xc, name: "Warrior License" },
  { index: 0x278e, type: 0xc, name: "Hunter License" },
  { index: 0x278f, type: 0xc, name: "Cleric License" },
  { index: 0x2790, type: 0xc, name: "Dancer License" },
  { index: 0x2791, type: 0xc, name: "Scholar License" },
  { index: 0x2792, type: 0xc, name: "Apothecary License" },
  { index: 0x2793, type: 0xc, name: "Proof of the Armsmaster" },
  { index: 0x2794, type: 0xc, name: "Proof of the Arcanist" },
  { index: 0x2795, type: 0xc, name: "Proof of the Conjurer" },
  { index: 0x2796, type: 0xc, name: "Proof of the Inventor" },
  { index: 0x2797, type: 0xc, name: "Clockite" },
  { index: 0x2799, type: 0xc, name: "Horse Coin" },
  { index: 0x279a, type: 0xc, name: "Mask" },
  { index: 0x279c, type: 0xc, name: "Theater Ticket" },
  { index: 0x279d, type: 0xc, name: "Wooden Sword" },
  { index: 0x279f, type: 0xc, name: "Coffee Beans" },
  { index: 0x27a0, type: 0xc, name: "Special Wheat Flour" },
  { index: 0x27a1, type: 0xc, name: "Quality Paper" },
  { index: 0x27a2, type: 0xc, name: "Pocket Watch" },
  { index: 0x27a3, type: 0xc, name: "Silverwork" },
  { index: 0x27a7, type: 0xc, name: "Habit" },
  { index: 0x27a8, type: 0xc, name: "Mother's Garden Key" },
  { index: 0x27b3, type: 0x1, name: "Imitation Sword" },
  { index: 0x27b4, type: 0x2, name: "Imitation Spear" },
  { index: 0x27b5, type: 0x3, name: "Snakebite" },
  { index: 0x2872, type: 0x6, name: "Flamebringer's Staff" },
  { index: 0x2889, type: 0x3, name: "Needle Dagger" },
  { index: 0x288c, type: 0x0, name: "Lousy Rock" },
  { index: 0x288d, type: 0x0, name: "Lump of Silver" },
  { index: 0x288e, type: 0x9, name: "Old Armor" },
  { index: 0x288f, type: 0x5, name: "Tenacious Bow" },
  { index: 0x2890, type: 0x6, name: "Sinner's Staff" },
  { index: 0x2891, type: 0x6, name: "Pilgrim Rod" },
  { index: 0x2892, type: 0xa, name: "Ancient Necklace" },
  { index: 0x2893, type: 0xa, name: "Angel's Ring" },
  { index: 0x2894, type: 0x0, name: "Silver Ingot" },
  { index: 0x2895, type: 0x9, name: "Desert Armor" },
  { index: 0x2896, type: 0x1, name: "Guardian's Iceblade" },
  { index: 0x2897, type: 0x0, name: "Purse of Hope" },
  { index: 0x2898, type: 0x7, name: "Rabbit Shield" },
  { index: 0x2899, type: 0xa, name: "Falcon Ring" },
  { index: 0x289a, type: 0x2, name: "Fire Dragon's Glaive" },
  { index: 0x289b, type: 0x0, name: "Antique Coin" },
  { index: 0x289c, type: 0x0, name: "Inventor's Handbook, Volume I" },
  { index: 0x289e, type: 0x1, name: "Master Rod" },
  { index: 0x28d4, type: 0xc, name: "Cute Shoes" },
  { index: 0x28d6, type: 0xc, name: "Black Crystal" },
  { index: 0x28d9, type: 0xc, name: "Key to Freedom" },
  { index: 0x28da, type: 0xc, name: "Contract" },
  { index: 0x28dc, type: 0xc, name: "Crescent Moon Necklace" },
  { index: 0x28dd, type: 0xc, name: "The Grand Terry" },
  { index: 0x28de, type: 0xc, name: "Ship Alteration Ticket" },
  { index: 0x28df, type: 0xc, name: "Horse Tail Hair" },
  { index: 0x28e0, type: 0xc, name: "Wine Offering" },
  { index: 0x28e1, type: 0xc, name: "Sacred Wood" },
  { index: 0x28e2, type: 0xc, name: "Dancer's Mask" },
  { index: 0x28e3, type: 0xc, name: "Cloudy Mirror Fragment" },
  { index: 0x28e4, type: 0xc, name: "Folded Paper" },
  { index: 0x28e5, type: 0xc, name: "Cloudy Mirror" },
  { index: 0x28e7, type: 0xc, name: "Metalworking Tool" },
  { index: 0x28e8, type: 0xc, name: "Mirror" },
  { index: 0x28e9, type: 0xc, name: "Precision Lens" },
  { index: 0x28ea, type: 0xc, name: "Improved Telescope" },
  { index: 0x28eb, type: 0xc, name: "Tanzy's Journal" },
  { index: 0x28ec, type: 0xc, name: "Journal Fragment I" },
  { index: 0x28ed, type: 0xc, name: "Journal Fragment II" },
  { index: 0x28ee, type: 0xc, name: "Journal Fragment III" },
  { index: 0x28ef, type: 0xc, name: "Journal Fragment IV" },
  { index: 0x28f0, type: 0xc, name: "Journal Fragment V" },
  { index: 0x28f1, type: 0xc, name: "Journal Fragment VI" },
  { index: 0x28f2, type: 0xc, name: "Journal Fragment VII" },
  { index: 0x28f3, type: 0xc, name: "Journal Fragment VIII" },
  { index: 0x28f4, type: 0xc, name: "Journal Fragment IX" },
  { index: 0x28f5, type: 0xc, name: "Journal Fragment X" },
  { index: 0x28f6, type: 0xc, name: "Journal Fragment XI" },
  { index: 0x28f7, type: 0xc, name: "Journal Fragment XII" },
  { index: 0x28f8, type: 0xc, name: "Journal Fragment XIII" },
  { index: 0x28f9, type: 0xc, name: "Journal Fragment XIV" },
  { index: 0x28fa, type: 0xc, name: "Journal Fragment XV" },
  { index: 0x28fb, type: 0xc, name: "Journal Fragment XVI" },
  { index: 0x28fc, type: 0xc, name: "Journal Fragment XVII" },
  { index: 0x2901, type: 0xc, name: "White Flower" },
  { index: 0x2902, type: 0xc, name: "Wallet" },
  { index: 0x2903, type: 0xc, name: "Apothecary's Satchel" },
  { index: 0x2904, type: 0xc, name: "Friendship Jerky" },
  { index: 0x2905, type: 0xc, name: "Scalebark Leaf" },
  { index: 0x2906, type: 0xc, name: "Snowgrass" },
  { index: 0x2907, type: 0xc, name: "Bloodberry" },
  { index: 0x2908, type: 0xc, name: "1. Cait's Theme –Piano Version–" },
  { index: 0x2909, type: 0xc, name: "2. Cait's Theme –Guitar Version–" },
  { index: 0x290a, type: 0xc, name: "3. Cait's Theme –Violin Version–" },
  { index: 0x290b, type: 0xc, name: "7. Osvald, the Scholar" },
  { index: 0x290c, type: 0xc, name: "5. Castti, the Apothecary" },
  { index: 0x290d, type: 0xc, name: "6. Throné, the Thief" },
  { index: 0x290e, type: 0xc, name: "4. Ochette, the Hunter" },
  { index: 0x290f, type: 0xc, name: "8. Partitio, the Merchant" },
  { index: 0x2910, type: 0xc, name: "9. Agnea, the Dancer" },
  { index: 0x2911, type: 0xc, name: "10. Temenos, the Cleric" },
  { index: 0x2912, type: 0xc, name: "11. Hikari, the Warrior" },
  { index: 0x2913, type: 0xc, name: "12. Normal Battle I" },
  { index: 0x2914, type: 0xc, name: "13. Normal Battle II" },
  { index: 0x2915, type: 0xc, name: "14. Normal Battle III" },
  { index: 0x2916, type: 0xc, name: "15. Battle on the Sea" },
  { index: 0x2917, type: 0xc, name: "16. Critical Clash I" },
  { index: 0x2918, type: 0xc, name: "17. Critical Clash II" },
  { index: 0x2919, type: 0xc, name: "18. Miscreant's Melody" },
  { index: 0x291a, type: 0xc, name: "19. Soliloquy" },
  { index: 0x291b, type: 0xc, name: "20. Carefree Days" },
  { index: 0x291c, type: 0xc, name: "21. Unshakable Resolve" },
  { index: 0x291d, type: 0xc, name: "22. Bygone Days" },
  { index: 0x291e, type: 0xc, name: "23. At Your Back" },
  { index: 0x291f, type: 0xc, name: "24. Hope" },
  { index: 0x2920, type: 0xc, name: "25. Oresrush, Dried Up" },
  { index: 0x2921, type: 0xc, name: "26. Oresrush, Dried Up –Night–" },
  { index: 0x2922, type: 0xc, name: "27. The Journey Begins" },
  { index: 0x2923, type: 0xc, name: "28. All For You" },
  { index: 0x2924, type: 0xc, name: "29. Gil on the Keys" },
  { index: 0x2925, type: 0xc, name: "30. Scarlet Folk Song –By the Light of the Heart–" },
  { index: 0x2949, type: 0xb, name: "Grape Leaf" },
  { index: 0x294a, type: 0xb, name: "Plum Leaf" },
  { index: 0x294b, type: 0xb, name: "Pomegranate Leaf" },
  { index: 0x294c, type: 0xb, name: "Mighty Leaf" },
  { index: 0x294d, type: 0xb, name: "Fool's Leaf" },
  { index: 0x294e, type: 0xb, name: "Cleansing Leaf" },
  { index: 0x294f, type: 0xb, name: "Warding Leaf" },
  { index: 0x2950, type: 0xb, name: "Whimsical Leaf" },
  { index: 0x2951, type: 0xb, name: "Dual Leaf" },
  { index: 0x2952, type: 0xb, name: "Weeds" },
  { index: 0x2953, type: 0xb, name: "Blusterbloom" },
  { index: 0x2954, type: 0xb, name: "Lily of the Light" },
  { index: 0x2955, type: 0xb, name: "Darkdelion" },
  { index: 0x2956, type: 0xb, name: "Forget-Me-Do" },
  { index: 0x2957, type: 0xb, name: "Sticky Flower" },
  { index: 0x2958, type: 0xb, name: "Fumbling Flower" },
  { index: 0x2959, type: 0xb, name: "Dreamy Flower" },
  { index: 0x295a, type: 0xb, name: "Enfeebling Flower" },
  { index: 0x295b, type: 0xb, name: "Dual Flower" },
  { index: 0x295c, type: 0xb, name: "Weeds" },
  { index: 0x295d, type: 0xb, name: "Diffusing Serum" },
  { index: 0x295e, type: 0xb, name: "Strengthening Serum" },
  { index: 0x2964, type: 0xd, name: "Castle Merchant's Information" },
  { index: 0x2967, type: 0xd, name: "Underground Passage to the Cathedral" },
  { index: 0x2976, type: 0xd, name: "Bale's Weakness" },
  { index: 0x297a, type: 0xd, name: "Labor Report Whereabouts" },
  { index: 0x299d, type: 0xd, name: "An Eyewitness to Harvey" },
  { index: 0x299e, type: 0xd, name: "Library Rumor" },
  { index: 0x299f, type: 0xd, name: "Harvey's Whereabouts" },
  { index: 0x2a17, type: 0xd, name: "Weapons Deal Details" },
  { index: 0x2a18, type: 0xd, name: "Lucian's Notebook" },
  { index: 0x2a19, type: 0xd, name: "Prayer Handbook" },
  { index: 0x2a1a, type: 0xd, name: "Prayer Order" },
  { index: 0x2a1b, type: 0xd, name: "The Culprit's True Identity" },
  { index: 0x2a1f, type: 0xd, name: "Lingering Scent of Incense" },
  { index: 0x2a20, type: 0xd, name: "Shattered Cathedral Window" },
  { index: 0x2a21, type: 0xd, name: "Toppled Candlesticks" },
  { index: 0x2a36, type: 0xc, name: "Mother's Key" },
  { index: 0x2a37, type: 0xc, name: "Father's Key" },
  { index: 0x2a38, type: 0x1, name: "Conqueror's Sword" },
  { index: 0x2a39, type: 0x2, name: "Warlord's Spear" },
  { index: 0x2a3a, type: 0x3, name: "Dancer's Blade" },
  { index: 0x2a3b, type: 0x4, name: "Lionheart's Axe" },
  { index: 0x2a3c, type: 0x5, name: "Hunter's Bow" },
  { index: 0x2a3d, type: 0x6, name: "Spiritlord's Staff" },
  { index: 0x2a3e, type: 0xc, name: "Rusty Sword" },
  { index: 0x2a3f, type: 0xc, name: "Rusty Polearm" },
  { index: 0x2a40, type: 0xc, name: "Rusty Dagger" },
  { index: 0x2a41, type: 0xc, name: "Rusty Axe" },
  { index: 0x2a42, type: 0xc, name: "Rusty Bow" },
  { index: 0x2a43, type: 0xc, name: "Rusty Staff" },
  { index: 0x2a44, type: 0xc, name: "Mercantile Manuscript Archive Key" },
  { index: 0x2a45, type: 0xc, name: "Changeable Catapult Design" },
  { index: 0x2a46, type: 0xc, name: "Springy Boots Design" },
  { index: 0x2a47, type: 0xc, name: "Critical Scope Design" },
  { index: 0x2a48, type: 0xc, name: "Elemental Bomb Bottle Design" },
  { index: 0x2a49, type: 0xc, name: "Tin Horn Design" },
  { index: 0x2a4a, type: 0xc, name: "Hastening Hammer Design" },
  { index: 0x2a4b, type: 0xc, name: "Arkar's Coil Design" },
  { index: 0x2a4c, type: 0xc, name: "All-Purpose Tool Design" },
  { index: 0x2a4d, type: 0xc, name: "Rosa's Medicine" },
  { index: 0x2a4e, type: 0xc, name: "Aromatic Jerky" },
  { index: 0x2a4f, type: 0xc, name: "Mysterious Notebook" },
  { index: 0x2a50, type: 0xc, name: "Kaldena's Notebook" },
  { index: 0x2a52, type: 0xc, name: "Snowdrop Flower" },
  { index: 0x2a55, type: 0xc, name: "Oboro's Journal" },
  { index: 0x2a56, type: 0xc, name: "Grand Gala Invitation" },
  { index: 0x2abe, type: 0xc, name: "Escape Route Map" },
  { index: 0x2abf, type: 0xc, name: "Letter from the Snowhares" },
  { index: 0x2ac0, type: 0xc, name: "Lute" },
  { index: 0x2ac1, type: 0xc, name: "Paper Play" },
  { index: 0x2ac2, type: 0xc, name: "History Book" },
  { index: 0x2ac3, type: 0xd, name: "Hunting Request" },
  { index: 0x2ac4, type: 0xd, name: "Garbage Collector" },
  { index: 0x2ac5, type: 0xd, name: "Man in a Brown Coat" },
  { index: 0x2ac6, type: 0xd, name: "Dolcinaea and Gifts" },
  { index: 0x2ac7, type: 0xc, name: "Earrings" },
  { index: 0x2acb, type: 0xc, name: "Lychanthe Antipyretic" },
  { index: 0x2acc, type: 0xc, name: "Thieves' Gem" },
  { index: 0x2acd, type: 0xc, name: "Master Thief's Sapphire Stone" },
  { index: 0x2ace, type: 0xc, name: "High Priest's Amulet" },
  { index: 0x2acf, type: 0xc, name: "High Priest's Book of Scripture" },
  { index: 0x2ad2, type: 0xc, name: "Quicksand Monster's Liver" },
  { index: 0x2ad3, type: 0xc, name: "Sea Monster's Whisker" },
  { index: 0x2ad6, type: 0xc, name: "Sacred Flame Candle" },
  { index: 0x2adb, type: 0xc, name: "Dispatches from Beastling Island" },
  { index: 0x2adc, type: 0xc, name: "The Curious Legend of the Great Wall" },
  { index: 0x2add, type: 0xc, name: "From the Far Reaches of Hell" },
  { index: 0x2ae0, type: 0xc, name: "Keepsake Sword" },
  { index: 0x2ae1, type: 0xc, name: "Dragon Vase" },
  { index: 0x2ae2, type: 0xc, name: "Phoenix Fan" },
  { index: 0x2ae4, type: 0xc, name: "Miracle Stone" },
  { index: 0x2ae5, type: 0xc, name: "Nyx Royal Family Tree" },
  { index: 0x2ae6, type: 0xc, name: "Amulet of Affection" },
  { index: 0x2ae7, type: 0xc, name: "Pretty Pearl" },
  { index: 0x2ae8, type: 0xc, name: "Mysterious Box" },
  { index: 0x2aea, type: 0xc, name: "Bottle of White Powder" },
  { index: 0x2aeb, type: 0xc, name: "Message in a Bottle" },
  { index: 0x2aed, type: 0xc, name: "Azure Sun Sword" },
  { index: 0x2aee, type: 0xc, name: "Silver Quill" },
  { index: 0x2aef, type: 0xc, name: "Treasured Necklace" },
  { index: 0x2af3, type: 0xd, name: "Truth of the Game Parlor" },
  { index: 0x2af5, type: 0xd, name: "Nyx Family History" },
  { index: 0x2af6, type: 0xd, name: "Spicy Chicken Recipe" },
  { index: 0x2afa, type: 0xd, name: "Nikki's Special Joke" },
  { index: 0x2afc, type: 0xd, name: "Tricks to Growing Grapes" },
  { index: 0x2afd, type: 0xd, name: "Adventures of an Apprentice Cleric's Sequel" },
  { index: 0x2b00, type: 0xd, name: "Well Iris Uses" },
  { index: 0x2b01, type: 0xd, name: "Margello's Personality" },
  { index: 0x2b03, type: 0x1, name: "Firestarter" },
  { index: 0x2b04, type: 0x2, name: "Tornado Glaive" },
  { index: 0x2b05, type: 0x4, name: "Icy Axe" },
  { index: 0x2b06, type: 0x4, name: "Guardian's Great Axe" },
  { index: 0x2b07, type: 0x5, name: "Befuddling Greatbow" },
  { index: 0x2b08, type: 0x5, name: "Exorcising Bow" },
  { index: 0x2b09, type: 0x6, name: "Morning Star" },
  { index: 0x2b0a, type: 0x6, name: "Psychic Staff" },
  { index: 0x2b0b, type: 0x7, name: "Weathered Treasure Shield" },
  { index: 0x2b0c, type: 0x7, name: "Shield of Serenity" },
  { index: 0x2b0d, type: 0x7, name: "Sun Shield" },
  { index: 0x2b0e, type: 0x7, name: "Quartz Shield" },
  { index: 0x2b0f, type: 0xc, name: "Stocked Goods" },
  { index: 0x2b10, type: 0xc, name: "Crop Tapestry Pattern" },
  { index: 0x2b11, type: 0x2, name: "War Glaive" },
  { index: 0x2b12, type: 0xc, name: "Special Bait" },
  { index: 0x2b13, type: 0xc, name: "Delsta Devil" },
  { index: 0x2b14, type: 0x1, name: "Spirit Scimitar" },
  { index: 0x2b15, type: 0x1, name: "Iron Blade" },
  { index: 0x2b16, type: 0x2, name: "Lance" },
  { index: 0x2b17, type: 0x2, name: "Master Harpoon" },
  { index: 0x2b18, type: 0x4, name: "Beastling's Hatchet" },
  { index: 0x2b19, type: 0x4, name: "War Axe" },
  { index: 0x2b1a, type: 0x5, name: "Giant Bow" },
  { index: 0x2b1b, type: 0x6, name: "Stone Rod" },
  { index: 0x2b1c, type: 0xc, name: "Purebalm" },
  { index: 0x2b1d, type: 0xc, name: "Scalebark Leaf" },
  { index: 0x2b1e, type: 0xc, name: "Skybalm" },
  { index: 0x2b1f, type: 0xc, name: "Santanejo" },
  { index: 0x2b20, type: 0xc, name: "Snowdrop" },
  { index: 0x2b21, type: 0x6, name: "Oak Staff" },
  { index: 0x2b22, type: 0x6, name: "Conjurer's Staff" },
  { index: 0x2b23, type: 0x3, name: "Piercing Dagger" },
  { index: 0x2b24, type: 0x3, name: "Magus Knife" },
  { index: 0x2b25, type: 0x1, name: "Sword of Oaths" },
  { index: 0x2b26, type: 0x3, name: "Vengeful Knife" },
  { index: 0x2b27, type: 0x3, name: "Jade Dagger" },
  { index: 0x2b28, type: 0x5, name: "Floyd's Neo Bow" },
  { index: 0x2b29, type: 0x7, name: "Wise King's Shield" },
  { index: 0x2b2a, type: 0x7, name: "Bodyguard's Vantage" },
  { index: 0x2b2b, type: 0x7, name: "Shield of Strength" },
  { index: 0x2b2c, type: 0xa, name: "Mikka's Amulet" },
  { index: 0x2b2d, type: 0xa, name: "Laila's Amulet" },
  { index: 0x2b2e, type: 0xa, name: "Sisters' Amulet" },
  { index: 0x2b2f, type: 0xa, name: "Coat of Arms" },
  { index: 0x2b30, type: 0x0, name: "Jerky" },
  { index: 0x2b31, type: 0x0, name: "Quality Jerky" },
  { index: 0x2b32, type: 0x0, name: "Superior Jerky" },
  { index: 0x2b33, type: 0x0, name: "Snowy Stew" },
  { index: 0x2b34, type: 0x0, name: "Mountain Sausage" },
  { index: 0x2b35, type: 0x0, name: "Three-Star Terrine" },
  { index: 0x2b36, type: 0x0, name: "Island Skewer" },
  { index: 0x2b37, type: 0x0, name: "Seafood Paella" },
  { index: 0x2b38, type: 0x0, name: "Spicy Offal Stew" },
  { index: 0x2b39, type: 0x0, name: "Wild Steak" },
  { index: 0x2b3a, type: 0x0, name: "Breezy Beef Stew" },
  { index: 0x2b3b, type: 0x0, name: "Grilled Chicken" },
  { index: 0x2b3c, type: 0x0, name: "Beast Liver" },
  { index: 0x2b3d, type: 0x0, name: "Creamy Sauté" },
  { index: 0x2b3e, type: 0x0, name: "Salted Seafood" },
  { index: 0x2b3f, type: 0x0, name: "Bone" },
  { index: 0x2b40, type: 0x0, name: "Metal Medley" },
  { index: 0x2b41, type: 0x0, name: "Stone-Roasted Rice" },
  { index: 0x2b42, type: 0x0, name: "Salad" },
  { index: 0x2b43, type: 0x0, name: "Elemental Soup" },
  { index: 0x2b44, type: 0x0, name: "Spicy Jerky" },
  { index: 0x2b45, type: 0x0, name: "Rotten Meat" },
  { index: 0x2b46, type: 0x0, name: "Perfect Jerky" },
  { index: 0x2b47, type: 0x0, name: "Jewel Cake" },
  { index: 0x2b48, type: 0x0, name: "Octopath Bowl" },
  { index: 0x2b49, type: 0x0, name: "Aromatic Jerky" },
  { index: 0x2b4a, type: 0x0, name: "Old Cloth" },
  { index: 0x2b4b, type: 0x0, name: "Raspberry" },
  { index: 0x2b4c, type: 0x0, name: "Rare Stone" },
  { index: 0x2b4d, type: 0x0, name: "Vivid Jewel" },
  { index: 0x2b4e, type: 0x0, name: "Heavy Coin Pouch" },
  { index: 0x2b4f, type: 0x0, name: "Silver-Filled Pouch" },
  { index: 0x2b50, type: 0x0, name: "Antique Coin" },
  { index: 0x2b51, type: 0x0, name: "Silver-Rimmed Monocle" },
  { index: 0x2b52, type: 0x0, name: "Gold Pocket Watch" },
  { index: 0x2b53, type: 0x0, name: "Gold Ring" },
  { index: 0x2b54, type: 0x0, name: "Curious Antique" },
  { index: 0x2b55, type: 0x0, name: "Dazzling Artwork" },
  { index: 0x2b56, type: 0x0, name: "Silver Coin" },
  { index: 0x2b57, type: 0x0, name: "Wheat Bread" },
  { index: 0x2b58, type: 0x0, name: "Bewitching Perfume" },
  { index: 0x2b59, type: 0x0, name: "Empty Coin Pouch" },
  { index: 0x2b5a, type: 0x0, name: "Handmade Bouquet" },
  { index: 0x2b5b, type: 0x0, name: "Old Locket" },
  { index: 0x2b5c, type: 0x0, name: "Silver-Plated Knife" },
  { index: 0x2b5d, type: 0x0, name: "Homemade Cake" },
  { index: 0x2b5e, type: 0x2, name: "Memorial Harpoon" },
  { index: 0x2b5f, type: 0xa, name: "Rosary of Redemption" },
  { index: 0x2b60, type: 0xa, name: "Scarlet Stone of Protection" },
  { index: 0x2b64, type: 0x0, name: "Exotic Remedy" },
  { index: 0x2b65, type: 0x0, name: "Bottled Toxins" },
  { index: 0x2b66, type: 0x0, name: "Noxious Needle" },
  { index: 0x2b67, type: 0x1, name: "Evil Slayer" },
  { index: 0x2b68, type: 0x1, name: "Reaper's Blade" },
  { index: 0x2b69, type: 0x3, name: "Moonfang" },
  { index: 0x2b6a, type: 0x7, name: "Diamond Shield" },
  { index: 0x2b6b, type: 0xa, name: "Warding Necklace" },
  { index: 0x2b6c, type: 0xa, name: "Shadowsage Necklace" },
  { index: 0x2b6d, type: 0xa, name: "Foreign Ring" },
  { index: 0x2b6e, type: 0xc, name: "Rainbow Glass Bottle" },
  { index: 0x2b6f, type: 0xc, name: "Mythical Horn" },
  { index: 0x2b70, type: 0xc, name: "Tin Toy" },
  { index: 0x2b71, type: 0xc, name: "Scrap Metal" },
  { index: 0x2b72, type: 0xc, name: "Ancient Cog" },
  { index: 0x2b73, type: 0xc, name: "Natural Magnetite" },
  { index: 0x2b74, type: 0xa, name: "Jade Ring" },
  { index: 0x2b75, type: 0xc, name: "Ticket Stub" },
  { index: 0x2b76, type: 0x1, name: "Soulsucker" },
  { index: 0x2b77, type: 0x3, name: "Silver-Plated Knife" },
  { index: 0x2b78, type: 0x5, name: "Evening Mist" },
  { index: 0x2b79, type: 0x5, name: "Ancient Bow" },
  { index: 0x2b7a, type: 0x3, name: "Breaker's Blade" },
  { index: 0x2b7b, type: 0x4, name: "Royal Guard's Hatchet" },
  { index: 0x2b7c, type: 0x5, name: "Battle Bow" },
  { index: 0x2b7d, type: 0x6, name: "Sacred Flame Staff" },
  { index: 0x2b7e, type: 0x7, name: "Protector's Shield" },
  { index: 0x2b7f, type: 0x3, name: "Dagger in the Rough" },
  { index: 0x2b80, type: 0x6, name: "Rough-Hewn Rod" },
  { index: 0x2b81, type: 0x7, name: "Giant Shield" },
  { index: 0x2b82, type: 0xa, name: "Blessing in Disguise" },
  { index: 0x2b83, type: 0xa, name: "Gale Feather" },
  { index: 0x2b84, type: 0xa, name: "Eye of Calamity" },
  { index: 0x2b89, type: 0x1, name: "Divine Splendor" },
  { index: 0x2b8a, type: 0x1, name: "Clan Mei Sword" },
  { index: 0x2b8b, type: 0x1, name: "Rotted Sword" },
  { index: 0x2b8c, type: 0x2, name: "Clan Mei Spear" },
  { index: 0x2b8d, type: 0x3, name: "Mooneater" },
  { index: 0x2b8e, type: 0x4, name: "Hero's Axe" },
  { index: 0x2b8f, type: 0x4, name: "Contaminated Iron Ingot" },
  { index: 0x2b90, type: 0x4, name: "Rotted Axe" },
  { index: 0x2b91, type: 0x7, name: "Cursed Shield" },
  { index: 0x2b92, type: 0xa, name: "Hand-Sewn Gloves" },
  { index: 0x2b93, type: 0xa, name: "Divine Necklace" },
  { index: 0x2b94, type: 0xa, name: "Finisher's Claws" },
  { index: 0x2b95, type: 0xa, name: "Stone of Truth" },
  { index: 0x2b96, type: 0xa, name: "Fang of Ferocity" },
  { index: 0x2b97, type: 0xc, name: "Crescent Moon Necklace" },
  { index: 0x2b98, type: 0xa, name: "Moonshell Necklace" },
  { index: 0x2b99, type: 0xa, name: "Moonshell Bracelet" },
  { index: 0x2b9a, type: 0xc, name: "Cloudy Crystal Bracelet" },
  { index: 0x2b9e, type: 0xd, name: "Medicinal Herbs" },
  { index: 0x2b9f, type: 0xd, name: "Harry's Self-Deprecating Joke" },
  { index: 0x2ba0, type: 0xd, name: "Ned's Romantic Advice" },
  { index: 0x2ba5, type: 0xd, name: "A Killer's Motive" },
  { index: 0x2bd8, type: 0xc, name: "Fort Orochi Plans" },
  { index: 0x2bda, type: 0xc, name: "Deluxe Crepe" },
  { index: 0x2bdb, type: 0x2, name: "Vanguard's Javelin" },
  { index: 0x2bdc, type: 0x7, name: "Master's Shield" },
  { index: 0x2bdd, type: 0x7, name: "Tattered Sacred Shield" },
  { index: 0x2cc2, type: 0xd, name: "How to Decipher Unknown Languages" },
  { index: 0x2cc7, type: 0xc, name: "Unfinished Vessel" },
  { index: 0x2cc8, type: 0x0, name: "Almighty Soulstone" },
  { index: 0x2cc9, type: 0x0, name: "Ancient Sentinel Core" },
  { index: 0x2cca, type: 0x0, name: "Primeval Horn Elixir" },
  { index: 0x2ccb, type: 0x0, name: "Slumber Sage" },
  { index: 0x2ccc, type: 0x0, name: "Herb of Serenity" },
  { index: 0x2ccd, type: 0xc, name: "Worn Journal" },
  { index: 0x2cce, type: 0xc, name: "Aelmorite Reflector" },
  { index: 0x2ccf, type: 0x1, name: "Expert's Obsidian Edge" },
  { index: 0x2cd0, type: 0x2, name: "Matching Trident" },
  { index: 0x2cd1, type: 0x3, name: "Lockpick" },
  { index: 0x2cd2, type: 0x4, name: "Flayer's Admonishment" },
  { index: 0x2cd3, type: 0x5, name: "Engagement Bow" },
  { index: 0x2cd4, type: 0x6, name: "Sunshadow Staff" },
  { index: 0x2cd5, type: 0xc, name: "Sturdy Pickaxe" },
  { index: 0x2cd6, type: 0x0, name: "Shady Grape Bunch" },
  { index: 0x2cd7, type: 0x0, name: "Shady Inspiriting Plum" },
  { index: 0x2cd8, type: 0x0, name: "Shady Energizing Pomegranate" },
  { index: 0x2cd9, type: 0x0, name: "Reinforcing Jam" },
  { index: 0x2cda, type: 0x0, name: "Rejuvenating Jam" },
  { index: 0x2cdb, type: 0x0, name: "Almighty Olive" },
  { index: 0x2cdc, type: 0x0, name: "Herb Elixir" },
  { index: 0x2cdd, type: 0x0, name: "Bottled Nightmares" },
  { index: 0x2cde, type: 0x1, name: "Lost Tribe's Blade" },
  { index: 0x2ce4, type: 0x2, name: "Lost Tribe's Spear" },
  { index: 0x2cf3, type: 0x5, name: "Black Bow" },
  { index: 0x2cf9, type: 0x6, name: "Lost Tribe's Staff" },
  { index: 0x2cfa, type: 0x6, name: "Bellowing Baton" },
  { index: 0x2d06, type: 0x8, name: "Mermaid Circlet" },
  { index: 0x2d0a, type: 0x9, name: "Star's Gown" },
  { index: 0x2d11, type: 0xa, name: "Brooch of Joy" },
  { index: 0x2d12, type: 0xc, name: "Al's Bag" },
  { index: 0x2d13, type: 0x3, name: "Lost Tribe's Dagger" },
  { index: 0x2d14, type: 0x4, name: "Lost Tribe's Axe" },
  { index: 0x2d15, type: 0x5, name: "Lost Tribe's Bow" },
  { index: 0x2d16, type: 0xc, name: "Dancer's Journal" },
  { index: 0x2d19, type: 0xc, name: "Stolen Sword" },
  { index: 0x2d1b, type: 0x0, name: "Ruinous Relic" },
  { index: 0x2d1c, type: 0x0, name: "Ancient Cursed Talisman" },
  { index: 0x2d1d, type: 0x0, name: "Decaying Dragon's Essence" },
  { index: 0x2d1e, type: 0x0, name: "Wriggling Root" },
  { index: 0x2d1f, type: 0x0, name: "Grail of Life" },
  { index: 0x2d20, type: 0x0, name: "Gold Dust" },
  { index: 0x2d21, type: 0x3, name: "Sharp Stone" },
];

export const accessories: Resource = {};
export const axes: Resource = {};
export const bodyarmors: Resource = {};
export const bows: Resource = {};
export const daggers: Resource = {};
export const headgears: Resource = {};
export const polearms: Resource = {};
export const shields: Resource = {};
export const staves: Resource = {};
export const swords: Resource = {};

inventory.forEach((item) => {
  switch (item.type) {
    case 0x1:
      swords[item.index] = item.name;
      break;
    case 0x2:
      polearms[item.index] = item.name;
      break;
    case 0x3:
      daggers[item.index] = item.name;
      break;
    case 0x4:
      axes[item.index] = item.name;
      break;
    case 0x5:
      bows[item.index] = item.name;
      break;
    case 0x6:
      staves[item.index] = item.name;
      break;
    case 0x7:
      shields[item.index] = item.name;
      break;
    case 0x8:
      headgears[item.index] = item.name;
      break;
    case 0x9:
      bodyarmors[item.index] = item.name;
      break;
    case 0xa:
      accessories[item.index] = item.name;
      break;
  }
});

export const characterExSkills: string[][] = [
  ["Shinjumonjigiri", "Ultimate Stance"], // Hikari
  ["Indomitable Beast", "Provoke Beasts"], // Ochette
  ["Remedy", "Drastic Measures"], // Castti
  ["Share SP", "Negotiate Schedule"], // Partitio
  ["Prayer for Plenty", "Heavenly Shine"], // Temenos
  ["Teach", "One True Magic"], // Osvald
  ["Veil of Darkness", "Disguise"], // Throné
  ["Windy Refrain", "Song of Hope"], // Agnea
];

export const jobSkills: {
  jobIndex: number;
  jobSkills: { index: number; name: string }[];
  supportSkills: { index: number; name: string }[];
}[] = [
  {
    jobIndex: 0x0,
    jobSkills: [
      { index: 0x0, name: "Arrow of Fortune" },
      { index: 0x1, name: "Rest" },
      { index: 0x2, name: "Collect" },
      { index: 0x3, name: "Ember" },
      { index: 0x4, name: "Donate BP" },
      { index: 0x5, name: "Sidestep" },
      { index: 0x6, name: "Hired Help" },
      { index: 0x7, name: "Bifelgan's Bounty" },
    ],
    supportSkills: [
      { index: 0x8, name: "Grows on Trees" },
      { index: 0x9, name: "Boost-Start" },
      { index: 0xa, name: "Hang Tough" },
      { index: 0xb, name: "Full Power" },
    ],
  },
  {
    jobIndex: 0x1,
    jobSkills: [
      { index: 0x0, name: "Steal" },
      { index: 0x1, name: "Darkest Night" },
      { index: 0x2, name: "HP Thief" },
      { index: 0x3, name: "Surprise Attack" },
      { index: 0x4, name: "Swift Step" },
      { index: 0x5, name: "Armor Corrosive" },
      { index: 0x6, name: "Shackle Foe" },
      { index: 0x7, name: "Aeber's Reckoning" },
    ],
    supportSkills: [
      { index: 0x8, name: "Incidental Attack" },
      { index: 0x9, name: "Fleetfoot" },
      { index: 0xa, name: "Ensnare" },
      { index: 0xb, name: "Life in the Shadows" },
    ],
  },
  {
    jobIndex: 0x2,
    jobSkills: [
      { index: 0x0, name: "Aggressive Slash" },
      { index: 0x1, name: "Piercing Thrust" },
      { index: 0x2, name: "Abide" },
      { index: 0x3, name: "Enervating Slash" },
      { index: 0x4, name: "Stout Wall" },
      { index: 0x5, name: "Incite" },
      { index: 0x6, name: "Vengeful Blade" },
      { index: 0x7, name: "Brand's Blade" },
    ],
    supportSkills: [
      { index: 0x8, name: "Bolstering Break" },
      { index: 0x9, name: "Summon Strength" },
      { index: 0xa, name: "Latent Power Plus" },
      { index: 0xb, name: "Deal More Damage" },
    ],
  },
  {
    jobIndex: 0x3,
    jobSkills: [
      { index: 0x0, name: "Precise Shot" },
      { index: 0x1, name: "Thunderbird" },
      { index: 0x2, name: "Cleaving Blow" },
      { index: 0x3, name: "Mercy Strike" },
      { index: 0x4, name: "Take Aim" },
      { index: 0x5, name: "Leghold Trap" },
      { index: 0x6, name: "Abating Orb" },
      { index: 0x7, name: "Draefendi's Bow" },
    ],
    supportSkills: [
      { index: 0x8, name: "Heighten Senses" },
      { index: 0x9, name: "Eagle Eye" },
      { index: 0xa, name: "More Rare Monsters" },
      { index: 0xb, name: "Salt the Wound" },
    ],
  },
  {
    jobIndex: 0x4,
    jobSkills: [
      { index: 0x0, name: "Heal Wounds" },
      { index: 0x1, name: "Holy Light" },
      { index: 0x2, name: "Prayer to the Flame" },
      { index: 0x3, name: "Mystical Staff" },
      { index: 0x4, name: "Luminescence" },
      { index: 0x5, name: "Sacred Shield" },
      { index: 0x6, name: "Revive" },
      { index: 0x7, name: "Aelfric's Blessing" },
    ],
    supportSkills: [
      { index: 0x8, name: "Resilience" },
      { index: 0x9, name: "Inner Strength" },
      { index: 0xa, name: "Evil Ward" },
      { index: 0xb, name: "Rise Again" },
    ],
  },
  {
    jobIndex: 0x5,
    jobSkills: [
      { index: 0x0, name: "Lion Dance" },
      { index: 0x1, name: "Ruinous Kick" },
      { index: 0x2, name: "Peacock Strut" },
      { index: 0x3, name: "Sweeping Gale" },
      { index: 0x4, name: "Stimulate" },
      { index: 0x5, name: "Dagger Dance" },
      { index: 0x6, name: "Bewildering Grace" },
      { index: 0x7, name: "Sealticge's Seduction" },
    ],
    supportSkills: [
      { index: 0x8, name: "The Show Goes On" },
      { index: 0x9, name: "Ever Evasive" },
      { index: 0xa, name: "Hard Worker" },
      { index: 0xb, name: "Invigorate and Inspire" },
    ],
  },
  {
    jobIndex: 0x6,
    jobSkills: [
      { index: 0x0, name: "Fireball" },
      { index: 0x1, name: "Icewind" },
      { index: 0x2, name: "Lightning Bolt" },
      { index: 0x3, name: "Analyze" },
      { index: 0x4, name: "Stroke of Genius" },
      { index: 0x5, name: "Elemental Barrage" },
      { index: 0x6, name: "Advanced Magic" },
      { index: 0x7, name: "Alephan's Wisdom" },
    ],
    supportSkills: [
      { index: 0x8, name: "Evasive Maneuvers" },
      { index: 0x9, name: "Elemental Augmentation" },
      { index: 0xa, name: "Extra Experience" },
      { index: 0xb, name: "Advanced Magic Master" },
    ],
  },
  {
    jobIndex: 0x7,
    jobSkills: [
      { index: 0x0, name: "Healing Touch" },
      { index: 0x1, name: "Icicle" },
      { index: 0x2, name: "Rehabilitate" },
      { index: 0x3, name: "Sweeping Cleave" },
      { index: 0x4, name: "Poison Axe" },
      { index: 0x5, name: "Replenish Health" },
      { index: 0x6, name: "Weak to Poison" },
      { index: 0x7, name: "Dohter's Charity" },
    ],
    supportSkills: [
      { index: 0x8, name: "Vigorous Victor" },
      { index: 0x9, name: "Hale and Hearty" },
      { index: 0xa, name: "Inspiriting Break" },
      { index: 0xb, name: "Preventative Measures" },
    ],
  },
  {
    jobIndex: 0x8,
    jobSkills: [
      { index: 0x0, name: "Sixfold Strike" },
      { index: 0x1, name: "Bulwark" },
      { index: 0x2, name: "Conqueror's Sword: Cosmic Roar" },
      { index: 0x3, name: "Warlord's Spear: Giant Swing" },
      { index: 0x4, name: "Dancer's Blade: Mischievous Step" },
      { index: 0x5, name: "Lionheart's Axe: On the Hunt" },
      { index: 0x6, name: "Hunter's Bow: Flurry of Arrows" },
      { index: 0x7, name: "Spiritlord's Staff: Deliverance" },
    ],
    supportSkills: [
      { index: 0x8, name: "Master of Offense" },
      { index: 0x9, name: "Peak Performance" },
      { index: 0xa, name: "Invigorating Break" },
      { index: 0xb, name: "Arms Refinement" },
    ],
  },
  {
    jobIndex: 0x9,
    jobSkills: [
      { index: 0x0, name: "Malice" },
      { index: 0x1, name: "Blessing" },
      { index: 0x2, name: "Hex" },
      { index: 0x3, name: "Seal of Diffusion" },
      { index: 0x4, name: "Seal of Inversion" },
      { index: 0x5, name: "Seal of Immortality" },
      { index: 0x6, name: "Reflective Barrier" },
      { index: 0x7, name: "Seal of Eternity" },
    ],
    supportSkills: [
      { index: 0x8, name: "SP Recovery" },
      { index: 0x9, name: "Lasting Memory" },
      { index: 0xa, name: "Price of Power" },
      { index: 0xb, name: "Of Equal Might" },
    ],
  },
  {
    jobIndex: 0xa,
    jobSkills: [
      { index: 0x0, name: "Conjure Flames" },
      { index: 0x1, name: "Conjure Ice" },
      { index: 0x2, name: "Conjure Lightning" },
      { index: 0x3, name: "Conjure Gusts" },
      { index: 0x4, name: "Prayer for Rain" },
      { index: 0x5, name: "Dance of Immunity" },
      { index: 0x6, name: "Rite of the Sun" },
      { index: 0x7, name: "BP Boost" },
    ],
    supportSkills: [
      { index: 0x8, name: "Purification" },
      { index: 0x9, name: "SP Saver" },
      { index: 0xa, name: "Divine Wrath" },
      { index: 0xb, name: "BP Regeneration" },
    ],
  },
  {
    jobIndex: 0xb,
    jobSkills: [
      { index: 0x0, name: "Changeable Catapult" },
      { index: 0x1, name: "Springy Boots" },
      { index: 0x2, name: "Critical Scope" },
      { index: 0x3, name: "Elemental Bomb Bottle" },
      { index: 0x4, name: "Tin Horn" },
      { index: 0x5, name: "Hastening Hammer" },
      { index: 0x6, name: "Arkar's Coil" },
      { index: 0x7, name: "All-Purpose Tool" },
    ],
    supportSkills: [
      { index: 0x8, name: "A Step Ahead" },
      { index: 0x9, name: "Upgraded Accessories" },
      { index: 0xa, name: "BP in Adversity" },
      { index: 0xb, name: "Fruits of Labor" },
    ],
  },
];

export const jobs: Resource = {
  0x0: "Merchant",
  0x1: "Thief",
  0x2: "Warrior",
  0x3: "Hunter",
  0x4: "Cleric",
  0x5: "Dancer",
  0x6: "Scholar",
  0x7: "Apothecary",
  0x8: "Armsmaster",
  0x9: "Arcanist",
  0xa: "Conjurer",
  0xb: "Inventor",
  0xc: "???",
  0xd: "???",
  0xe: "???",
  0xf: "???",
  0x10: "???",
  0x11: "???",
  0x12: "???",
  0x13: "???",
  0x14: "???",
};
