import type { GameJson } from "$lib/types";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa_japan: {
        $or: [
          { 0x74: [0xe5, 0xe5, 0xe5, 0xe5] },
          { 0x174: [0xe5, 0xe5, 0xe5, 0xe5] },
        ],
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      name: "Checksum",
      offset: 0xfe,
      type: "checksum",
      dataType: "uint16",
      control: {
        offsetStart: 0x0,
        offsetEnd: 0x100,
      },
    },
    {
      type: "tabs",
      items: [
        {
          name: "General",
          flex: true,
          items: [
            {
              name: "Save Count",
              offset: 0x0,
              type: "variable",
              dataType: "uint16",
              disabled: true,
              test: true,
            },
            {
              name: "Opponents Defeated",
              offset: 0x2,
              type: "variable",
              dataType: "uint16",
              max: 9999,
            },
            {
              name: "Opponents Defeated?",
              offset: 0x70,
              type: "variable",
              dataType: "uint32",
              hidden: true,
            },
          ],
        },
        {
          name: "Pending Game",
          flex: true,
          disableTabIf: {
            offset: 0x6b,
            type: "variable",
            dataType: "uint8",
            operator: "=",
            value: 0xff,
          },
          items: [
            {
              name: "Score (Placeholder)",
              offset: 0x63,
              length: 0x8,
              type: "variable",
              dataType: "string",
              letterDataType: "uint8",
              hidden: true,
            },
            {
              id: "score",
              name: "Score",
              offset: 0x63,
              type: "variable",
              dataType: "uint8",
              max: 99999999,
            },
            {
              name: "Stage",
              offset: 0x6b,
              type: "variable",
              dataType: "uint8",
              operations: [{ "+": 1 }],
              min: 1,
              max: 6,
            },
            {
              name: "Continues",
              offset: 0x6c,
              type: "variable",
              dataType: "uint8",
              min: 1,
              max: 9,
            },
            {
              name: "Player",
              offset: 0x6e,
              type: "variable",
              dataType: "uint8",
              min: 1,
              max: 9,
            },
            {
              name: "Character",
              offset: 0x6d,
              type: "variable",
              dataType: "uint8",
              resource: "characters",
              autocomplete: true,
            },
          ],
        },
        {
          name: "Records",
          items: [
            {
              name: "1st Place",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Score (Placeholder)",
                  offset: 0x4,
                  length: 0x8,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  hidden: true,
                },
                {
                  id: "score",
                  name: "Score",
                  offset: 0x4,
                  type: "variable",
                  dataType: "uint8",
                  max: 99999999,
                },
                {
                  name: "Name",
                  offset: 0xc,
                  length: 0x6,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  fallback: 0x20,
                  resource: "letters",
                },
                {
                  name: "Character",
                  offset: 0x12,
                  type: "variable",
                  dataType: "uint8",
                  resource: "characters",
                  autocomplete: true,
                },
                {
                  name: "Character Color",
                  offset: 0x13,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
              ],
            },
            {
              name: "2nd Place",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Score (Placeholder)",
                  offset: 0x14,
                  length: 0x8,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  hidden: true,
                },
                {
                  id: "score",
                  name: "Score",
                  offset: 0x14,
                  type: "variable",
                  dataType: "uint8",
                  max: 99999999,
                },
                {
                  name: "Name",
                  offset: 0x1c,
                  length: 0x6,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  fallback: 0x20,
                  resource: "letters",
                },
                {
                  name: "Character",
                  offset: 0x22,
                  type: "variable",
                  dataType: "uint8",
                  resource: "characters",
                  autocomplete: true,
                },
                {
                  name: "Character Color",
                  offset: 0x23,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
              ],
            },
            {
              name: "3rd Place",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Score (Placeholder)",
                  offset: 0x24,
                  length: 0x8,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  hidden: true,
                },
                {
                  id: "score",
                  name: "Score",
                  offset: 0x24,
                  type: "variable",
                  dataType: "uint8",
                  max: 99999999,
                },
                {
                  name: "Name",
                  offset: 0x2c,
                  length: 0x6,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  fallback: 0x20,
                  resource: "letters",
                },
                {
                  name: "Character",
                  offset: 0x32,
                  type: "variable",
                  dataType: "uint8",
                  resource: "characters",
                  autocomplete: true,
                },
                {
                  name: "Character Color",
                  offset: 0x33,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
              ],
            },
            {
              name: "4th Place",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Score (Placeholder)",
                  offset: 0x34,
                  length: 0x8,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  hidden: true,
                },
                {
                  id: "score",
                  name: "Score",
                  offset: 0x34,
                  type: "variable",
                  dataType: "uint8",
                  max: 99999999,
                },
                {
                  name: "Name",
                  offset: 0x3c,
                  length: 0x6,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  fallback: 0x20,
                  resource: "letters",
                },
                {
                  name: "Character",
                  offset: 0x42,
                  type: "variable",
                  dataType: "uint8",
                  resource: "characters",
                  autocomplete: true,
                },
                {
                  name: "Character Color",
                  offset: 0x43,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
              ],
            },
            {
              name: "5th Place",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Score (Placeholder)",
                  offset: 0x44,
                  length: 0x8,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  hidden: true,
                },
                {
                  id: "score",
                  name: "Score",
                  offset: 0x44,
                  type: "variable",
                  dataType: "uint8",
                  max: 99999999,
                },
                {
                  name: "Name",
                  offset: 0x4c,
                  length: 0x6,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  fallback: 0x20,
                  resource: "letters",
                  test: true,
                },
                {
                  name: "Character",
                  offset: 0x52,
                  type: "variable",
                  dataType: "uint8",
                  resource: "characters",
                  autocomplete: true,
                },
                {
                  name: "Character Color",
                  offset: 0x53,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
              ],
            },
          ],
        },
        {
          name: "Options",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Difficulty",
                  offset: 0x54,
                  type: "variable",
                  dataType: "uint8",
                  resource: "difficulties",
                },
                {
                  name: "Extend",
                  offset: 0x55,
                  type: "variable",
                  dataType: "uint8",
                  resource: "extends",
                },
              ],
            },
            {
              name: "Button Config.",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Button A",
                  offset: 0x59,
                  type: "variable",
                  dataType: "uint8",
                  resource: "actions",
                },
                {
                  name: "Button B",
                  offset: 0x5a,
                  type: "variable",
                  dataType: "uint8",
                  resource: "actions",
                },
                {
                  name: "Button L",
                  offset: 0x5b,
                  type: "variable",
                  dataType: "uint8",
                  resource: "actions",
                },
                {
                  name: "Button R",
                  offset: 0x5c,
                  type: "variable",
                  dataType: "uint8",
                  resource: "actions",
                },
              ],
            },
            {
              name: "Extra Options",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Player",
                  offset: 0x56,
                  type: "variable",
                  dataType: "uint8",
                  min: 1,
                  max: 9,
                },
                {
                  name: "Stage Select",
                  offset: 0x57,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 6,
                },
                {
                  name: "Rapid Punch",
                  offset: 0x5d,
                  type: "variable",
                  dataType: "uint8",
                  resource: "optionBoolean",
                },
              ],
            },
            {
              name: "Color Change",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Cody",
                  offset: 0x5f,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
                {
                  name: "Guy",
                  offset: 0x5e,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
                {
                  name: "Haggar",
                  offset: 0x60,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
                {
                  name: "α Cody",
                  offset: 0x62,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
                {
                  name: "α Guy",
                  offset: 0x61,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    actions: {
      0x0: "Jump",
      0x1: "Attack",
      0x2: "-",
      0x3: "Ex Joy",
    },
    characters: {
      0x0: "Guy",
      0x2: "Cody",
      0x4: "Haggar",
      0x6: "α Guy",
      0x8: "α Cody",
    },
    difficulties: {
      0x0: "Very Easy",
      0x1: "Easy",
      0x2: "Normal",
      0x3: "Hard",
      0x4: "Very Hard",
    },
    extends: {
      0x0: "100000",
      0x1: "200000",
      0x2: "200000 Evr",
      0x3: "None",
    },
    letters: {
      0x41: "A",
      0x42: "B",
      0x43: "C",
      0x44: "D",
      0x45: "E",
      0x46: "F",
      0x47: "G",
      0x48: "H",
      0x49: "I",
      0x4a: "J",
      0x4b: "K",
      0x4c: "L",
      0x4d: "M",
      0x4e: "N",
      0x4f: "O",
      0x50: "P",
      0x51: "Q",
      0x52: "R",
      0x53: "S",
      0x54: "T",
      0x55: "U",
      0x56: "V",
      0x57: "W",
      0x58: "X",
      0x59: "Y",
      0x5a: "Z",
    },
    optionBoolean: {
      0x0: "Off",
      0x1: "On",
    },
  },
};

export default template;
