import type { Resource, ResourceGroups } from "$lib/types";

export const itemSubtypes = [
  { index: 0x0, name: "Knives" },
  { index: 0x1, name: "Ninja Swords" },
  { index: 0x2, name: "Swords" },
  { index: 0x3, name: "Knight Swords" },
  { index: 0x4, name: "Katanas" },
  { index: 0x5, name: "Axes" },
  { index: 0x6, name: "Rods" },
  { index: 0x7, name: "Staves" },
  { index: 0x8, name: "Hammers" },
  { index: 0x9, name: "Guns" },
  { index: 0xa, name: "Crossbows" },
  { index: 0xb, name: "Bows" },
  { index: 0xc, name: "Musical Instruments" },
  { index: 0xd, name: "Dictionaries" },
  { index: 0xe, name: "Spears" },
  { index: 0xf, name: "Sticks" },
  { index: 0x10, name: "Women's Bags" },
  { index: 0x11, name: "Cloths" },
  { index: 0x12, name: "Shurikens" },
  { index: 0x13, name: "Bombs" },
  { index: 0x14, name: "Shields" },
  { index: 0x15, name: "Helmets" },
  { index: 0x16, name: "Hats" },
  { index: 0x17, name: "Women's Ribbons" },
  { index: 0x18, name: "Armors" },
  { index: 0x19, name: "Clothes" },
  { index: 0x1a, name: "Robes" },
  { index: 0x1b, name: "Shoes" },
  { index: 0x1c, name: "Gauntlets" },
  { index: 0x1d, name: "Rings" },
  { index: 0x1e, name: "Armlets" },
  { index: 0x1f, name: "Cloaks" },
  { index: 0x20, name: "Women's Perfumes" },
  { index: 0x21, name: "Items" },
];

export const inventoryList = [
  {
    name: "Weapons",
    items: [
      { index: 0x0, name: "Dagger", subtype: 0x0 },
      { index: 0x1, name: "Mythril Knife", subtype: 0x0 },
      { index: 0x2, name: "Blind Knife", subtype: 0x0 },
      { index: 0x3, name: "Mage Masher", subtype: 0x0 },
      { index: 0x4, name: "Platina Dagger", subtype: 0x0 },
      { index: 0x5, name: "Main Gauche", subtype: 0x0 },
      { index: 0x6, name: "Orichalcum", subtype: 0x0 },
      { index: 0x7, name: "Assassin Dagger", subtype: 0x0 },
      { index: 0x8, name: "Air Knife", subtype: 0x0 },
      { index: 0x9, name: "Zorlin Shape", subtype: 0x0 },
      { index: 0xa, name: "Hidden Knife", subtype: 0x1 },
      { index: 0xb, name: "Ninja Knife", subtype: 0x1 },
      { index: 0xc, name: "Short Edge", subtype: 0x1 },
      { index: 0xd, name: "Ninja Edge", subtype: 0x1 },
      { index: 0xe, name: "Spell Edge", subtype: 0x1 },
      { index: 0xf, name: "Sasuke Knife", subtype: 0x1 },
      { index: 0x10, name: "Iga Knife", subtype: 0x1 },
      { index: 0x11, name: "Koga Knife", subtype: 0x1 },
      { index: 0x12, name: "Broad Sword", subtype: 0x2 },
      { index: 0x13, name: "Long Sword", subtype: 0x2 },
      { index: 0x14, name: "Iron Sword", subtype: 0x2 },
      { index: 0x15, name: "Mythril Sword", subtype: 0x2 },
      { index: 0x16, name: "Blood Sword", subtype: 0x2 },
      { index: 0x17, name: "Coral Sword", subtype: 0x2 },
      { index: 0x18, name: "Ancient Sword", subtype: 0x2 },
      { index: 0x19, name: "Sleep Sword", subtype: 0x2 },
      { index: 0x1a, name: "Platinum Sword", subtype: 0x2 },
      { index: 0x1b, name: "Diamond Sword", subtype: 0x2 },
      { index: 0x1c, name: "Ice Brand", subtype: 0x2 },
      { index: 0x1d, name: "Rune Blade", subtype: 0x2 },
      { index: 0x1e, name: "Nagrarock", subtype: 0x2 },
      { index: 0x1f, name: "Materia Blade", subtype: 0x2 },
      { index: 0x20, name: "Defender", subtype: 0x3 },
      { index: 0x21, name: "Save the Queen", subtype: 0x3 },
      { index: 0x22, name: "Excalibur", subtype: 0x3 },
      { index: 0x23, name: "Ragnarok", subtype: 0x3 },
      { index: 0x24, name: "Chaos Blade", subtype: 0x3 },
      { index: 0x25, name: "Asura Knife", subtype: 0x4 },
      { index: 0x26, name: "Koutetsu Knife", subtype: 0x4 },
      { index: 0x27, name: "Bizen Boat", subtype: 0x4 },
      { index: 0x28, name: "Murasame", subtype: 0x4 },
      { index: 0x29, name: "Heaven's Cloud", subtype: 0x4 },
      { index: 0x2a, name: "Kiyomori", subtype: 0x4 },
      { index: 0x2b, name: "Muramasa", subtype: 0x4 },
      { index: 0x2c, name: "Kikuichimoji", subtype: 0x4 },
      { index: 0x2d, name: "Masamune", subtype: 0x4 },
      { index: 0x2e, name: "Chirijiraden", subtype: 0x4 },
      { index: 0x2f, name: "Battle Axe", subtype: 0x5 },
      { index: 0x30, name: "Giant Axe", subtype: 0x5 },
      { index: 0x31, name: "Slasher", subtype: 0x5 },
      { index: 0x32, name: "Rod", subtype: 0x6 },
      { index: 0x33, name: "Thunder Rod", subtype: 0x6 },
      { index: 0x34, name: "Flame Rod", subtype: 0x6 },
      { index: 0x35, name: "Ice Rod", subtype: 0x6 },
      { index: 0x36, name: "Poison Rod", subtype: 0x6 },
      { index: 0x37, name: "Wizard Rod", subtype: 0x6 },
      { index: 0x38, name: "Dragon Rod", subtype: 0x6 },
      { index: 0x39, name: "Faith Rod", subtype: 0x6 },
      { index: 0x3a, name: "Oak Staff", subtype: 0x7 },
      { index: 0x3b, name: "White Staff", subtype: 0x7 },
      { index: 0x3c, name: "Healing Staff", subtype: 0x7 },
      { index: 0x3d, name: "Rainbow Staff", subtype: 0x7 },
      { index: 0x3e, name: "Wizard Staff", subtype: 0x7 },
      { index: 0x3f, name: "Gold Staff", subtype: 0x7 },
      { index: 0x40, name: "Mace of Zeus", subtype: 0x7 },
      { index: 0x41, name: "Sage Staff", subtype: 0x7 },
      { index: 0x42, name: "Flail", subtype: 0x8 },
      { index: 0x43, name: "Flame Whip", subtype: 0x8 },
      { index: 0x44, name: "Morning Star", subtype: 0x8 },
      { index: 0x45, name: "Scorpion Tail", subtype: 0x8 },
      { index: 0x46, name: "Romanda Gun", subtype: 0x9 },
      { index: 0x47, name: "Mythril Gun", subtype: 0x9 },
      { index: 0x48, name: "Stone Gun", subtype: 0x9 },
      { index: 0x49, name: "Blaze Gun", subtype: 0x9 },
      { index: 0x4a, name: "Glacier Gun", subtype: 0x9 },
      { index: 0x4b, name: "Blast Gun", subtype: 0x9 },
      { index: 0x4c, name: "Bow Gun", subtype: 0xa },
      { index: 0x4d, name: "Night Killer", subtype: 0xa },
      { index: 0x4e, name: "Cross Bow", subtype: 0xa },
      { index: 0x4f, name: "Poison Bow", subtype: 0xa },
      { index: 0x50, name: "Hunting Bow", subtype: 0xa },
      { index: 0x51, name: "Gastrafitis", subtype: 0xa },
      { index: 0x52, name: "Long Bow", subtype: 0xb },
      { index: 0x53, name: "Silver Bow", subtype: 0xb },
      { index: 0x54, name: "Ice Bow", subtype: 0xb },
      { index: 0x55, name: "Lightning Bow", subtype: 0xb },
      { index: 0x56, name: "Windslash Bow", subtype: 0xb },
      { index: 0x57, name: "Mythril Bow", subtype: 0xb },
      { index: 0x58, name: "Ultimus Bow", subtype: 0xb },
      { index: 0x59, name: "Yoichi Bow", subtype: 0xb },
      { index: 0x5a, name: "Perseus Bow", subtype: 0xb },
      { index: 0x5b, name: "Ramia Harp", subtype: 0xc },
      { index: 0x5c, name: "Bloody Strings", subtype: 0xc },
      { index: 0x5d, name: "Fairy Harp", subtype: 0xc },
      { index: 0x5e, name: "Battle Dict", subtype: 0xd },
      { index: 0x5f, name: "Monster Dict", subtype: 0xd },
      { index: 0x60, name: "Papyrus Plate", subtype: 0xd },
      { index: 0x61, name: "Madlemgen", subtype: 0xd },
      { index: 0x62, name: "Javelin", subtype: 0xe },
      { index: 0x63, name: "Spear", subtype: 0xe },
      { index: 0x64, name: "Mythril Spear", subtype: 0xe },
      { index: 0x65, name: "Partisan", subtype: 0xe },
      { index: 0x66, name: "Oberisk", subtype: 0xe },
      { index: 0x67, name: "Holy Lance", subtype: 0xe },
      { index: 0x68, name: "Dragon Whisker", subtype: 0xe },
      { index: 0x69, name: "Javelin", subtype: 0xe },
      { index: 0x6a, name: "Cypress Rod", subtype: 0xf },
      { index: 0x6b, name: "Battle Bamboo", subtype: 0xf },
      { index: 0x6c, name: "Musk Rod", subtype: 0xf },
      { index: 0x6d, name: "Iron Fan", subtype: 0xf },
      { index: 0x6e, name: "Gokuu Rod", subtype: 0xf },
      { index: 0x6f, name: "Ivory Rod", subtype: 0xf },
      { index: 0x70, name: "Octagon Rod", subtype: 0xf },
      { index: 0x71, name: "Whale Whisker", subtype: 0xf },
      { index: 0x72, name: "C Bag", subtype: 0x10 },
      { index: 0x73, name: "FS Bag", subtype: 0x10 },
      { index: 0x74, name: "P Bag", subtype: 0x10 },
      { index: 0x75, name: "H Bag", subtype: 0x10 },
      { index: 0x76, name: "Persia", subtype: 0x11 },
      { index: 0x77, name: "Cashmere", subtype: 0x11 },
      { index: 0x78, name: "Ryozan Silk", subtype: 0x11 },
      { index: 0x79, name: "Shuriken", subtype: 0x12 },
      { index: 0x7a, name: "Magic Shuriken", subtype: 0x12 },
      { index: 0x7b, name: "Yagyu Darkness", subtype: 0x12 },
      { index: 0x7c, name: "Fire Ball", subtype: 0x13 },
      { index: 0x7d, name: "Water Ball", subtype: 0x13 },
      { index: 0x7e, name: "Lightning Ball", subtype: 0x13 },
      { index: 0x7f, name: "Escutcheon", subtype: 0x14 },
      { index: 0x80, name: "Buckler", subtype: 0x14 },
      { index: 0x81, name: "Bronze Shield", subtype: 0x14 },
      { index: 0x82, name: "Round Shield", subtype: 0x14 },
      { index: 0x83, name: "Mythril Shield", subtype: 0x14 },
      { index: 0x84, name: "Gold Shield", subtype: 0x14 },
      { index: 0x85, name: "Ice Shield", subtype: 0x14 },
      { index: 0x86, name: "Flame Shield", subtype: 0x14 },
      { index: 0x87, name: "Aegis Shield", subtype: 0x14 },
      { index: 0x88, name: "Diamond Shield", subtype: 0x14 },
      { index: 0x89, name: "Platina Shield", subtype: 0x14 },
      { index: 0x8a, name: "Crystal Shield", subtype: 0x14 },
      { index: 0x8b, name: "Genji Shield", subtype: 0x14 },
      { index: 0x8c, name: "Kaiser Plate", subtype: 0x14 },
      { index: 0x8d, name: "Venetian Shield", subtype: 0x14 },
      { index: 0x8e, name: "Escutcheon", subtype: 0x14 },
    ],
  },
  {
    name: "Heads",
    items: [
      { index: 0x8f, name: "Leather Helmet", subtype: 0x15 },
      { index: 0x90, name: "Bronze Helmet", subtype: 0x15 },
      { index: 0x91, name: "Iron Helmet", subtype: 0x15 },
      { index: 0x92, name: "Barbuta", subtype: 0x15 },
      { index: 0x93, name: "Mythril Helmet", subtype: 0x15 },
      { index: 0x94, name: "Gold Helmet", subtype: 0x15 },
      { index: 0x95, name: "Cross Helmet", subtype: 0x15 },
      { index: 0x96, name: "Diamond Helmet", subtype: 0x15 },
      { index: 0x97, name: "Platina Helmet", subtype: 0x15 },
      { index: 0x98, name: "Circlet", subtype: 0x15 },
      { index: 0x99, name: "Crystal Helmet", subtype: 0x15 },
      { index: 0x9a, name: "Genji Helmet", subtype: 0x15 },
      { index: 0x9b, name: "Grand Helmet", subtype: 0x15 },
      { index: 0x9c, name: "Leather Hat", subtype: 0x16 },
      { index: 0x9d, name: "Feather Hat", subtype: 0x16 },
      { index: 0x9e, name: "Red Hood", subtype: 0x16 },
      { index: 0x9f, name: "Headgear", subtype: 0x16 },
      { index: 0xa0, name: "Triangle Hat", subtype: 0x16 },
      { index: 0xa1, name: "Green Beret", subtype: 0x16 },
      { index: 0xa2, name: "Twist Headband", subtype: 0x16 },
      { index: 0xa3, name: "Holy Miter", subtype: 0x16 },
      { index: 0xa4, name: "Black Hood", subtype: 0x16 },
      { index: 0xa5, name: "Golden Hairpin", subtype: 0x16 },
      { index: 0xa6, name: "Flash Hat", subtype: 0x16 },
      { index: 0xa7, name: "Thief Hat", subtype: 0x16 },
      { index: 0xa8, name: "Cachusha", subtype: 0x17 },
      { index: 0xa9, name: "Barette", subtype: 0x17 },
      { index: 0xaa, name: "Ribbon", subtype: 0x17 },
    ],
  },
  {
    name: "Armor",
    items: [
      { index: 0xab, name: "Leather Armor", subtype: 0x18 },
      { index: 0xac, name: "Linen Cuirass", subtype: 0x18 },
      { index: 0xad, name: "Bronze Armor", subtype: 0x18 },
      { index: 0xae, name: "Chain Mail", subtype: 0x18 },
      { index: 0xaf, name: "Mythril Armor", subtype: 0x18 },
      { index: 0xb0, name: "Plate Mail", subtype: 0x18 },
      { index: 0xb1, name: "Gold Armor", subtype: 0x18 },
      { index: 0xb2, name: "Diamond Armor", subtype: 0x18 },
      { index: 0xb3, name: "Platina Armor", subtype: 0x18 },
      { index: 0xb4, name: "Carabini Mail", subtype: 0x18 },
      { index: 0xb5, name: "Crystal Mail", subtype: 0x18 },
      { index: 0xb6, name: "Genji Armor", subtype: 0x18 },
      { index: 0xb7, name: "Reflect Mail", subtype: 0x18 },
      { index: 0xb8, name: "Maximillian", subtype: 0x18 },
      { index: 0xb9, name: "Clothes", subtype: 0x19 },
      { index: 0xba, name: "Leather Outfit", subtype: 0x19 },
      { index: 0xbb, name: "Leather Vest", subtype: 0x19 },
      { index: 0xbc, name: "Chain Vest", subtype: 0x19 },
      { index: 0xbd, name: "Mythril Vest", subtype: 0x19 },
      { index: 0xbe, name: "Adaman Vest", subtype: 0x19 },
      { index: 0xbf, name: "Wizard Outfit", subtype: 0x19 },
      { index: 0xc0, name: "Brigandine", subtype: 0x19 },
      { index: 0xc1, name: "Judo Outfit", subtype: 0x19 },
      { index: 0xc2, name: "Power Sleeve", subtype: 0x19 },
      { index: 0xc3, name: "Earth Clothes", subtype: 0x19 },
      { index: 0xc4, name: "Secret Clothes", subtype: 0x19 },
      { index: 0xc5, name: "Black Costume", subtype: 0x19 },
      { index: 0xc6, name: "Rubber Costume", subtype: 0x19 },
      { index: 0xc7, name: "Linen Robe", subtype: 0x1a },
      { index: 0xc8, name: "Silk Robe", subtype: 0x1a },
      { index: 0xc9, name: "Wizard Robe", subtype: 0x1a },
      { index: 0xca, name: "Chameleon Robe", subtype: 0x1a },
      { index: 0xcb, name: "White Robe", subtype: 0x1a },
      { index: 0xcc, name: "Black Robe", subtype: 0x1a },
      { index: 0xcd, name: "Light Robe", subtype: 0x1a },
      { index: 0xce, name: "Robe of Lords", subtype: 0x1a },
    ],
  },
  {
    name: "Accessories",
    items: [
      { index: 0xcf, name: "Battle Boots", subtype: 0x1b },
      { index: 0xd0, name: "Spike Shoes", subtype: 0x1b },
      { index: 0xd1, name: "Germinas Boots", subtype: 0x1b },
      { index: 0xd2, name: "Rubber Shoes", subtype: 0x1b },
      { index: 0xd3, name: "Feather Boots", subtype: 0x1b },
      { index: 0xd4, name: "Sprint Shoes", subtype: 0x1b },
      { index: 0xd5, name: "Red Shoes", subtype: 0x1b },
      { index: 0xd6, name: "Power Wrist", subtype: 0x1c },
      { index: 0xd7, name: "Genji Gauntlet", subtype: 0x1c },
      { index: 0xd8, name: "Magic Gauntlet", subtype: 0x1c },
      { index: 0xd9, name: "Bracer", subtype: 0x1c },
      { index: 0xda, name: "Reflect Ring", subtype: 0x1d },
      { index: 0xdb, name: "Defense Ring", subtype: 0x1d },
      { index: 0xdc, name: "Magic Ring", subtype: 0x1d },
      { index: 0xdd, name: "Cursed Ring", subtype: 0x1d },
      { index: 0xde, name: "Angel Ring", subtype: 0x1d },
      { index: 0xdf, name: "Diamond Armlet", subtype: 0x1e },
      { index: 0xe0, name: "Jade Armlet", subtype: 0x1e },
      { index: 0xe1, name: "108 Gems", subtype: 0x1e },
      { index: 0xe2, name: "N-Kai Armlet", subtype: 0x1e },
      { index: 0xe3, name: "Defense Armlet", subtype: 0x1e },
      { index: 0xe4, name: "Small Mantle", subtype: 0x1f },
      { index: 0xe5, name: "Leather Mantle", subtype: 0x1f },
      { index: 0xe6, name: "Wizard Mantle", subtype: 0x1f },
      { index: 0xe7, name: "Elf Mantle", subtype: 0x1f },
      { index: 0xe8, name: "Dracula Mantle", subtype: 0x1f },
      { index: 0xe9, name: "Feather Mantle", subtype: 0x1f },
      { index: 0xea, name: "Vanish Mantle", subtype: 0x1f },
      { index: 0xeb, name: "Chantage", subtype: 0x20 },
      { index: 0xec, name: "Cherche", subtype: 0x20 },
      { index: 0xed, name: "Setiemson", subtype: 0x20 },
      { index: 0xee, name: "Salty Rage", subtype: 0x20 },
    ],
  },
  {
    name: "Items",
    items: [
      { index: 0xef, name: "Potion", subtype: 0x21 },
      { index: 0xf0, name: "Hi-Potion", subtype: 0x21 },
      { index: 0xf1, name: "X-Potion", subtype: 0x21 },
      { index: 0xf2, name: "Ether", subtype: 0x21 },
      { index: 0xf3, name: "Hi-Ether", subtype: 0x21 },
      { index: 0xf4, name: "Elixir", subtype: 0x21 },
      { index: 0xf5, name: "Antidote", subtype: 0x21 },
      { index: 0xf6, name: "Eye Drop", subtype: 0x21 },
      { index: 0xf7, name: "Echo Grass", subtype: 0x21 },
      { index: 0xf8, name: "Maiden's Kiss", subtype: 0x21 },
      { index: 0xf9, name: "Soft", subtype: 0x21 },
      { index: 0xfa, name: "Holy Water", subtype: 0x21 },
      { index: 0xfb, name: "Remedy", subtype: 0x21 },
      { index: 0xfc, name: "Phoenix Down", subtype: 0x21 },
    ],
  },
];

interface InventorySubtype {
  index: number;
  name: string;
  items: { index: number; name: string; subtype: number }[];
}

export const inventory: {
  name: string;
  subtypes: InventorySubtype[];
}[] = [];

export const hands: Resource = {};
export const heads: Resource = {};
export const bodies: Resource = {};
export const accessories: Resource = {};

export const handsGroups: ResourceGroups = [];
export const headsGroups: ResourceGroups = [];
export const bodiesGroups: ResourceGroups = [];
export const accessoriesGroups: ResourceGroups = [];

itemSubtypes.forEach((type) => {
  if (type.index <= 0x11 || type.index === 0x14) {
    handsGroups[type.index] = { name: type.name, options: [] };
  } else if (type.index >= 0x15 && type.index <= 0x17) {
    headsGroups[type.index] = { name: type.name, options: [] };
  } else if (type.index >= 0x18 && type.index <= 0x1a) {
    bodiesGroups[type.index] = { name: type.name, options: [] };
  } else if (type.index >= 0x1b && type.index <= 0x20) {
    accessoriesGroups[type.index] = { name: type.name, options: [] };
  }
});

inventoryList.forEach((type, index) => {
  const subtypes: InventorySubtype[] = [];

  type.items.forEach((item) => {
    let subtype = subtypes.find((subtype) => subtype.index === item.subtype);

    if (!subtype) {
      subtype = {
        index: item.subtype,
        name: itemSubtypes[item.subtype].name,
        items: [],
      };

      subtypes.push(subtype);
    }

    subtype.items.push(item);

    switch (index) {
      case 0: // Weapons
        if (item.subtype <= 0x11 || item.subtype === 0x14) {
          hands[item.index + 0x1] = item.name;
          handsGroups[item.subtype].options.push(item.index + 0x1);
        }
        break;
      case 1: // Heads
        if (item.subtype >= 0x15 && item.subtype <= 0x17) {
          heads[item.index + 0x1] = item.name;
          headsGroups[item.subtype].options.push(item.index + 0x1);
        }
        break;
      case 2: // Armor
        if (item.subtype >= 0x18 && item.subtype <= 0x1a) {
          bodies[item.index + 0x1] = item.name;
          bodiesGroups[item.subtype].options.push(item.index + 0x1);
        }
        break;
      case 3: // Accessories
        if (item.subtype >= 0x1b && item.subtype <= 0x20) {
          accessories[item.index + 0x1] = item.name;
          accessoriesGroups[item.subtype].options.push(item.index + 0x1);
        }
        break;
    }
  });

  inventory.push({ name: type.name, subtypes });
});

export const locationList = [
  { index: 0x0, name: "Lesalia Imperial Capital" },
  { index: 0x1, name: "Riovanes Castle" },
  { index: 0x2, name: "Igros Castle" },
  { index: 0x3, name: "Lionel Castle" },
  { index: 0x4, name: "Limberry Castle" },
  { index: 0x5, name: "Zeltennia Castle" },
  { index: 0x6, name: "Magic City Gariland" },
  { index: 0x7, name: "Yardow Fort City" },
  { index: 0x8, name: "Goland Coal City" },
  { index: 0x9, name: "Dorter Trade City" },
  { index: 0xa, name: "Zaland Fort City" },
  { index: 0xb, name: "Goug Machine City" },
  { index: 0xc, name: "Warjilis Trade City" },
  { index: 0xd, name: "Bervenia Free City" },
  { index: 0xe, name: "Zarghidas Trade City" },
  { index: 0xf, name: "Fort Zeakden" },
  { index: 0x10, name: "Murond Holy Place" },
  { index: 0x11, name: "Thieves Fort" },
  { index: 0x12, name: "Orbonne Monastery" },
  { index: 0x13, name: "Golgorand Execution Site" },
  { index: 0x14, name: "Murond Death City" },
  { index: 0x15, name: "Bethla Garrison" },
  { index: 0x16, name: "Deep Dungeon" },
  { index: 0x17, name: "Nelveska Temple" },
  { index: 0x18, name: "Mandalia Plains" },
  { index: 0x19, name: "Fovoham Plains" },
  { index: 0x1a, name: "Sweegy Woods" },
  { index: 0x1b, name: "Bervenia Volcano" },
  { index: 0x1c, name: "Zeklaus Desert" },
  { index: 0x1d, name: "Lenalia Plateau" },
  { index: 0x1e, name: "Zigolis Swamp" },
  { index: 0x1f, name: "Yuguo Woods" },
  { index: 0x20, name: "Araguay Woods" },
  { index: 0x21, name: "Grog Hill" },
  { index: 0x22, name: "Bed Desert" },
  { index: 0x23, name: "Zirekile Falls" },
  { index: 0x24, name: "Dolbodar Swamp" },
  { index: 0x25, name: "Bariaus Hill" },
  { index: 0x26, name: "Doguola Pass" },
  { index: 0x27, name: "Bariaus Valley" },
  { index: 0x28, name: "Finath River" },
  { index: 0x29, name: "Poeskas Lake" },
  { index: 0x2a, name: "Germinas Peak" },
];

export const locations: Resource = {};

locationList.forEach((location) => {
  locations[location.index] = location.name;
});

export const persons = [
  { index: 0x0, name: "Ramza", max: 6 },
  { index: 0x1, name: "Delita", max: 7 },
  { index: 0x2, name: "Ovelia", max: 6 },
  { index: 0x3, name: "Alma", max: 4 },
  { index: 0x4, name: "Zalbag", max: 3 },
  { index: 0x5, name: "Dycedarg", max: 4 },
  { index: 0x6, name: "Larg", max: 4 },
  { index: 0x7, name: "Goltana", max: 4 },
  { index: 0x8, name: "Orinas", max: 4 },
  { index: 0x9, name: "Ruvelia", max: 4 },
  { index: 0xa, name: "Omdoria", max: 3 },
  { index: 0xb, name: "Funeral", max: 3 },
  { index: 0xc, name: "Algus", max: 3 },
  { index: 0xd, name: "Gafgarion", max: 2 },
  { index: 0xe, name: "Agrias", max: 2 },
  { index: 0xf, name: "Orlandu", max: 3 },
  { index: 0x10, name: "Olan", max: 3 },
  { index: 0x11, name: "Zalmo", max: 2 },
  { index: 0x14, name: "Simon", max: 2 },
  { index: 0x16, name: "Beowulf", max: 2 },
  { index: 0x17, name: "Wiegraf", max: 4 },
  { index: 0x18, name: "Reis", max: 2 },
  { index: 0x19, name: "Balmafula", max: 2 },
  { index: 0x1a, name: "Draclau", max: 3 },
  { index: 0x1c, name: "Rafa", max: 2 },
  { index: 0x1d, name: "Malak", max: 3 },
  { index: 0x1e, name: "Elmdor", max: 3 },
  { index: 0x20, name: "Barinten", max: 2 },
  { index: 0x22, name: "Mustadio", max: 1 },
  { index: 0x23, name: "Besrodio", max: 3 },
  { index: 0x24, name: "Rudvich", max: 3 },
  { index: 0x25, name: "Celia", max: 2 },
  { index: 0x26, name: "Lede", max: 2 },
  { index: 0x27, name: "Ajora", max: 1 },
  { index: 0x28, name: "Vormav", max: 3 },
  { index: 0x29, name: "Rofel", max: 1 },
  { index: 0x2a, name: "Izlude", max: 3 },
  { index: 0x2b, name: "Kletian", max: 1 },
  { index: 0x2c, name: "Balk", max: 1 },
  { index: 0x2d, name: "Meliadoul", max: 2 },
  { index: 0x2e, name: "Cloud", max: 1 },
  { index: 0x2f, name: "Teta", max: 3 },
  { index: 0x30, name: "Balbanes", max: 2 },
  { index: 0x31, name: "Gustav", max: 2 },
  { index: 0x32, name: "Miluda", max: 2 },
  { index: 0x33, name: "Golagros", max: 3 },
  { index: 0x3d, name: "Daravon", max: 1 },
  { index: 0x3e, name: "Elidibs", max: 1 },
  { index: 0x3f, name: "Alazlam", max: 1 },
];

// prettier-ignore
export const propositionList = [
  { index: 0x0, name: "Destiny of the Company", jobName: "Highwind Salvage" },
  { index: 0x1, name: "Sunken Salvage Tour", jobName: "Salvage Tour Thoughts" },
  { index: 0x2, name: "Sailor Tour", jobName: "Sailor Tour Thoughts" },
  { index: 0x3, name: "Larner Channel Waves", jobName: "Enterprise Salvage" },
  { index: 0x4, name: "Attractive Workplace", jobName: "Attractive Workplace?" },
  { index: 0x5, name: "Salvage the Trade Ship!", jobName: "Hindenburg Salvage" },
  { index: 0x6, name: "Envoy ship, Falcon", jobName: "Falcon Salvage" },
  { index: 0x7, name: "Heir of Mesa", jobName: "Legend of Heroic King" },
  { index: 0x8, name: "Salvage the Trade Ship!", jobName: "Doga Salvage" },
  { index: 0x9, name: "Emissary of Lionel", jobName: "Envoy Ship of Lionel Castle" },
  { index: 0xa, name: "Zaland Embassy", jobName: "Luxurious ship salvage" },
  { index: 0xb, name: "Stolen Ancient Writings", jobName: "Lost Ancient Writings" },
  { index: 0xc, name: "Good Workplace and Job!", jobName: "Good Workplace and Job?" },
  { index: 0xd, name: "Sea of Gredia Island", jobName: "Salvage in Riovanes!" },
  { index: 0xe, name: "Stranded Trade Ship", jobName: "Vessel of Istanbul" },
  { index: 0xf, name: "Trade Ship Douing", jobName: "Douing Salvage" },
  { index: 0x10, name: "Mine Excavation Tour", jobName: "Mining Tour Thoughts" },
  { index: 0x11, name: "Miner's Tour", jobName: "Miner's Tour Thoughts" },
  { index: 0x12, name: "Will of Elder Topa", jobName: "Letter to the Family" },
  { index: 0x13, name: "Miner's Tour 2", jobName: "Miner's Tour Repeated!" },
  { index: 0x14, name: "Dream of a Miner", jobName: "Anything's possible!" },
  { index: 0x15, name: "Vacancy!", jobName: "Guide to Miners" },
  { index: 0x16, name: "Miners Wanted!", jobName: "Miner's Day Off" },
  { index: 0x17, name: "Girl at Gulg Volcano", jobName: "Girl of Flame!?" },
  { index: 0x18, name: "Hidden Trap at the Maze", jobName: "The First One Back" },
  { index: 0x19, name: "Himka Cliffs", jobName: "Behind the Cliff" },
  { index: 0x1a, name: "The Lord's Ore", jobName: "Meet with the Unknown" },
  { index: 0x1b, name: "One Activity", jobName: "One Activity" },
  { index: 0x1c, name: "Miners Wanted! 2", jobName: "Fight of the Miners" },
  { index: 0x1d, name: "Rolade Ore Company", jobName: "Ghost Staffs" },
  { index: 0x1e, name: "Testimony of Ex-miner", jobName: "Tears of an Ex-miner" },
  { index: 0x1f, name: "Death Canyon", jobName: "15 Black Knights" },
  { index: 0x20, name: "Discovery Race", jobName: "After the Discovery Race" },
  { index: 0x21, name: "Poeskas Lake Bottom", jobName: "Things at Lake bottom" },
  { index: 0x22, name: "Discovery Race 2", jobName: "After 2nd Discovery Race" },
  { index: 0x23, name: "Legendary Traces", jobName: "Thing at Myst. Frontier" },
  { index: 0x24, name: "Discovery Race 3", jobName: "After 3rd Discovery Race" },
  { index: 0x25, name: "Deep in Sweegy Woods", jobName: "Thing in Deep Forest" },
  { index: 0x26, name: "Ruins at Bed Desert", jobName: "Thing at Bed Desert" },
  { index: 0x27, name: "Adventurer Ramzen", jobName: "Thing at Zeklaus Desert" },
  { index: 0x28, name: "I saw it.", jobName: "Over Mountain Pass" },
  { index: 0x29, name: "Discovery Tour", jobName: "Discovery Tour Thoughts" },
  { index: 0x2a, name: "Storm of Zigolis!", jobName: "Thing in the Swamps" },
  { index: 0x2b, name: "Ominous Dungeon", jobName: "Maze of Ancient People" },
  { index: 0x2c, name: "Adventurer Wanted!", jobName: "Join the Adventurer Team!" },
  { index: 0x2d, name: "I saw it! I swear!", jobName: "Report! It is true!" },
  { index: 0x2e, name: "Concerns of a Merchant", jobName: "Merchants' Worries!" },
  { index: 0x2f, name: "Mountain of Rain", jobName: "In the Mist..." },
  { index: 0x30, name: "Defeat Golden Gotsko!", jobName: "Wyberns Annihilated!" },
  { index: 0x31, name: "Defeat Behemoth!", jobName: "Wild Kingdom" },
  { index: 0x32, name: "Trap of the Bandits", jobName: "Battle! Demon Lylis" },
  { index: 0x33, name: "Son, Pappal!", jobName: "Father and Child" },
  { index: 0x34, name: "Within the Darkness", jobName: "Whisper Grass in Dark" },
  { index: 0x35, name: "Defeat Whirlwind Karz!", jobName: "Battle! Whirlwind Karz!" },
  { index: 0x36, name: "Minimum's Melancholy", jobName: "Crime of Ct. Minimum!" },
  { index: 0x37, name: "Terror of Assault Cave", jobName: "Battle! Assault Cave!" },
  { index: 0x38, name: "Challenge of Zero", jobName: "That is not the Aim!" },
  { index: 0x39, name: "Phantom Thief Zero!", jobName: "Too Naive" },
  { index: 0x3a, name: "Thief Zero Returns!", jobName: "Pleasure of a Goddess" },
  { index: 0x3b, name: "Thief Zero Reborn!", jobName: "Women held in arms..." },
  { index: 0x3c, name: "Thief Zero's Last Stand", jobName: "Bye, Noble of Darkness!" },
  { index: 0x3d, name: "Legendary Monster", jobName: "At the Hilltop Mansion?" },
  { index: 0x3e, name: "Sullen Experiment", jobName: "Unfortunate Monsters" },
  { index: 0x3f, name: "Fiar's Request", jobName: "Fiar's Intentions!" },
  { index: 0x40, name: "Dream child", jobName: "Back then..." },
  { index: 0x41, name: "Protect the Little Life", jobName: "Rescue of Cornelia!" },
  { index: 0x42, name: "If wishes come true", jobName: "Return of Pappal!" },
  { index: 0x43, name: "My Little Carrot", jobName: "Ultimate Atavism" },
  { index: 0x44, name: "Secret Door", jobName: "Thoughts of a Doll" },
  { index: 0x45, name: "Orders of Coast Guard", jobName: "Letter from distant" },
  { index: 0x46, name: "Devil in the Dark", jobName: "Battle! Mud Man!" },
  { index: 0x47, name: "Mother", jobName: "Darkness of Eternal Way" },
  { index: 0x48, name: "My treasure", jobName: "Demon Golem" },
  { index: 0x49, name: "The Greatest Plan", jobName: "Final Resistance" },
  { index: 0x4a, name: "Secret Society", jobName: "Informant" },
  { index: 0x4b, name: "How much is Life worth?", jobName: "Most Precious Thing" },
  { index: 0x4c, name: "Letter to my Love", jobName: "Poet Gilbert's Thoughts" },
  { index: 0x4d, name: "Minimum's Melancholy", jobName: "Delighted Ct. Minimum!" },
  { index: 0x4e, name: "Road of Beasts", jobName: "Cannibalistic Plant" },
  { index: 0x4f, name: "True Romance", jobName: "Joyous Song for You" },
  { index: 0x50, name: "Shy Katedona", jobName: "The Talkative, Katedona" },
  { index: 0x51, name: "Master Math!", jobName: "Courage of Durman!" },
  { index: 0x52, name: "Sad Traveling Artist", jobName: "Regain Ability!" },
  { index: 0x53, name: "Minimum's Melancholy", jobName: "Delighted Ct. Minimum!" },
  { index: 0x54, name: "Machinist Contest", jobName: "Won Machinist Contest!" },
  { index: 0x55, name: "Traveling Artist Mameko", jobName: "Artist Mameko Leaves!" },
  { index: 0x56, name: "Chocobo Restaurant", jobName: "Chocobo Restaurant" },
  { index: 0x57, name: "Wandering Gambler", jobName: "Ship Casino, Black Jack" },
  { index: 0x58, name: "Wandering Gambler", jobName: "Storm of 777!" },
  { index: 0x59, name: "Ringing of the Bell", jobName: "Inside Lakam Trade Co." },
  { index: 0x5a, name: "Memories", jobName: "Cherish Memories" },
  { index: 0x5b, name: "Hard Lecture", jobName: "A Perfect Smile!" },
  { index: 0x5c, name: "Win the Yardow Fight!", jobName: "Won the Yardow Fight!" },
  { index: 0x5d, name: "Win the Zaland Fight!", jobName: "Won the Zaland Fight!" },
  { index: 0x5e, name: "Win the Magic Contest!", jobName: "Won the Magic Contest!" },
  { index: 0x5f, name: "Meister Contest", jobName: "Won the Meister Contest!" },
];

export const propositions = propositionList.reduce(
  (propositions: Resource, proposition) => {
    propositions[proposition.index] = proposition.name;

    return propositions;
  },
  {},
);

export const treasures = [
  { index: 0x0, name: "Four Gods Set" },
  { index: 0x1, name: "Statue of Lylis" },
  { index: 0x2, name: "Beetle Charm" },
  { index: 0x3, name: "Tobacco Pipe" },
  { index: 0x4, name: "Zeni-Sword" },
  { index: 0x5, name: "Black Cat" },
  { index: 0x6, name: "Malice Mask" },
  { index: 0x7, name: "Parade Helmet" },
  { index: 0x8, name: "Kid's Bread" },
  { index: 0x9, name: "Adult's Bread" },
  { index: 0xa, name: "Calcobrina" },
  { index: 0xb, name: "Yurgeivogue" },
  { index: 0xc, name: "Red Materia" },
  { index: 0xd, name: "Blue Materia" },
  { index: 0xe, name: "Black Materia" },
  { index: 0xf, name: "White Materia" },
  { index: 0x10, name: "Rat Tail" },
  { index: 0x11, name: "M-Fiction Novel" },
  { index: 0x12, name: "Diary of Nanai" },
  { index: 0x13, name: "Wyuvle" },
  { index: 0x14, name: "Book of Enavia" },
  { index: 0x15, name: "Magical Gun" },
  { index: 0x16, name: "M Machinegun" },
  { index: 0x17, name: "Magi-Sword" },
  { index: 0x18, name: "Minu Orb" },
  { index: 0x19, name: "Tarot of Ben" },
  { index: 0x1a, name: "Excalipar" },
  { index: 0x1b, name: "Parasite Tree" },
  { index: 0x1c, name: "Longibunne Spear" },
  { index: 0x1d, name: "Chocobo Cannon" },
  { index: 0x1e, name: "St. Elmo's Fire" },
  { index: 0x1f, name: "Germonik Scriptures" },
  { index: 0x20, name: "Treasure (Pre. 1)" },
  { index: 0x21, name: "Treasure (Pre. 2)" },
  { index: 0x22, name: "Aries" },
  { index: 0x23, name: "Taurus" },
  { index: 0x24, name: "Gemini" },
  { index: 0x25, name: "Cancer" },
  { index: 0x26, name: "Leo" },
  { index: 0x27, name: "Virgo" },
  { index: 0x28, name: "Libra" },
  { index: 0x29, name: "Scorpio" },
  { index: 0x2a, name: "Sagittarius" },
  { index: 0x2b, name: "Capricorn" },
  { index: 0x2c, name: "Aquarius" },
  { index: 0x2d, name: "Pisces" },
  { index: 0x2e, name: "Serpentarius" },
];

export const unexploredLands = [
  { index: 0x0, name: "Shrine of Chaos" },
  { index: 0x1, name: "Forbidden Land Eureka" },
  { index: 0x2, name: "Pandemonium" },
  { index: 0x3, name: "Mirage Tower" },
  { index: 0x4, name: "Floating Castle" },
  { index: 0x5, name: "Matoya Cave" },
  { index: 0x6, name: "Crystal Tower" },
  { index: 0x7, name: "Magic Continent" },
  { index: 0x8, name: "Castle of Trials" },
  { index: 0x9, name: "Tower of Babel" },
  { index: 0xa, name: "Ronkan Ruins" },
  { index: 0xb, name: "Falgabird" },
  { index: 0xc, name: "Magic Train" },
  { index: 0xd, name: "Touzas Village" },
  { index: 0xe, name: "Chocobo Forest" },
  { index: 0xf, name: "Semite Falls" },
];
