import type { Resource, ResourceGroups } from "$lib/types";

export const itemSubtypes = [
  { index: 0x00, name: "Knives" },
  { index: 0x01, name: "Ninja Swords" },
  { index: 0x02, name: "Swords" },
  { index: 0x03, name: "Knight Swords" },
  { index: 0x04, name: "Katanas" },
  { index: 0x05, name: "Axes" },
  { index: 0x06, name: "Rods" },
  { index: 0x07, name: "Staves" },
  { index: 0x08, name: "Hammers" },
  { index: 0x09, name: "Guns" },
  { index: 0x0a, name: "Crossbows" },
  { index: 0x0b, name: "Bows" },
  { index: 0x0c, name: "Musical Instruments" },
  { index: 0x0d, name: "Dictionaries" },
  { index: 0x0e, name: "Spears" },
  { index: 0x0f, name: "Sticks" },
  { index: 0x10, name: "Women's Bags" },
  { index: 0x11, name: "Cloths" },
  { index: 0x12, name: "Shurikens" },
  { index: 0x13, name: "Bombs" },
  { index: 0x14, name: "Shields" },
  { index: 0x15, name: "Helmets" },
  { index: 0x16, name: "Hats" },
  { index: 0x17, name: "Women's Ribbons" },
  { index: 0x18, name: "Armors" },
  { index: 0x19, name: "Clothes" },
  { index: 0x1a, name: "Robes" },
  { index: 0x1b, name: "Shoes" },
  { index: 0x1c, name: "Gauntlets" },
  { index: 0x1d, name: "Rings" },
  { index: 0x1e, name: "Armlets" },
  { index: 0x1f, name: "Cloaks" },
  { index: 0x20, name: "Women's Perfumes" },
  { index: 0x21, name: "Items" },
];

export const inventoryList = [
  {
    name: "Weapons",
    items: [
      { index: 0x00, subtype: 0x00, name: "Dagger" },
      { index: 0x01, subtype: 0x00, name: "Mythril Knife" },
      { index: 0x02, subtype: 0x00, name: "Blind Knife" },
      { index: 0x03, subtype: 0x00, name: "Mage Masher" },
      { index: 0x04, subtype: 0x00, name: "Platina Dagger" },
      { index: 0x05, subtype: 0x00, name: "Main Gauche" },
      { index: 0x06, subtype: 0x00, name: "Orichalcum" },
      { index: 0x07, subtype: 0x00, name: "Assassin Dagger" },
      { index: 0x08, subtype: 0x00, name: "Air Knife" },
      { index: 0x09, subtype: 0x00, name: "Zorlin Shape" },
      { index: 0x0a, subtype: 0x01, name: "Hidden Knife" },
      { index: 0x0b, subtype: 0x01, name: "Ninja Knife" },
      { index: 0x0c, subtype: 0x01, name: "Short Edge" },
      { index: 0x0d, subtype: 0x01, name: "Ninja Edge" },
      { index: 0x0e, subtype: 0x01, name: "Spell Edge" },
      { index: 0x0f, subtype: 0x01, name: "Sasuke Knife" },
      { index: 0x10, subtype: 0x01, name: "Iga Knife" },
      { index: 0x11, subtype: 0x01, name: "Koga Knife" },
      { index: 0x12, subtype: 0x02, name: "Broad Sword" },
      { index: 0x13, subtype: 0x02, name: "Long Sword" },
      { index: 0x14, subtype: 0x02, name: "Iron Sword" },
      { index: 0x15, subtype: 0x02, name: "Mythril Sword" },
      { index: 0x16, subtype: 0x02, name: "Blood Sword" },
      { index: 0x17, subtype: 0x02, name: "Coral Sword" },
      { index: 0x18, subtype: 0x02, name: "Ancient Sword" },
      { index: 0x19, subtype: 0x02, name: "Sleep Sword" },
      { index: 0x1a, subtype: 0x02, name: "Platinum Sword" },
      { index: 0x1b, subtype: 0x02, name: "Diamond Sword" },
      { index: 0x1c, subtype: 0x02, name: "Ice Brand" },
      { index: 0x1d, subtype: 0x02, name: "Rune Blade" },
      { index: 0x1e, subtype: 0x02, name: "Nagrarock" },
      { index: 0x1f, subtype: 0x02, name: "Materia Blade" },
      { index: 0x20, subtype: 0x03, name: "Defender" },
      { index: 0x21, subtype: 0x03, name: "Save the Queen" },
      { index: 0x22, subtype: 0x03, name: "Excalibur" },
      { index: 0x23, subtype: 0x03, name: "Ragnarok" },
      { index: 0x24, subtype: 0x03, name: "Chaos Blade" },
      { index: 0x25, subtype: 0x04, name: "Asura Knife" },
      { index: 0x26, subtype: 0x04, name: "Koutetsu Knife" },
      { index: 0x27, subtype: 0x04, name: "Bizen Boat" },
      { index: 0x28, subtype: 0x04, name: "Murasame" },
      { index: 0x29, subtype: 0x04, name: "Heaven's Cloud" },
      { index: 0x2a, subtype: 0x04, name: "Kiyomori" },
      { index: 0x2b, subtype: 0x04, name: "Muramasa" },
      { index: 0x2c, subtype: 0x04, name: "Kikuichimoji" },
      { index: 0x2d, subtype: 0x04, name: "Masamune" },
      { index: 0x2e, subtype: 0x04, name: "Chirijiraden" },
      { index: 0x2f, subtype: 0x05, name: "Battle Axe" },
      { index: 0x30, subtype: 0x05, name: "Giant Axe" },
      { index: 0x31, subtype: 0x05, name: "Slasher" },
      { index: 0x32, subtype: 0x06, name: "Rod" },
      { index: 0x33, subtype: 0x06, name: "Thunder Rod" },
      { index: 0x34, subtype: 0x06, name: "Flame Rod" },
      { index: 0x35, subtype: 0x06, name: "Ice Rod" },
      { index: 0x36, subtype: 0x06, name: "Poison Rod" },
      { index: 0x37, subtype: 0x06, name: "Wizard Rod" },
      { index: 0x38, subtype: 0x06, name: "Dragon Rod" },
      { index: 0x39, subtype: 0x06, name: "Faith Rod" },
      { index: 0x3a, subtype: 0x07, name: "Oak Staff" },
      { index: 0x3b, subtype: 0x07, name: "White Staff" },
      { index: 0x3c, subtype: 0x07, name: "Healing Staff" },
      { index: 0x3d, subtype: 0x07, name: "Rainbow Staff" },
      { index: 0x3e, subtype: 0x07, name: "Wizard Staff" },
      { index: 0x3f, subtype: 0x07, name: "Gold Staff" },
      { index: 0x40, subtype: 0x07, name: "Mace of Zeus" },
      { index: 0x41, subtype: 0x07, name: "Sage Staff" },
      { index: 0x42, subtype: 0x08, name: "Flail" },
      { index: 0x43, subtype: 0x08, name: "Flame Whip" },
      { index: 0x44, subtype: 0x08, name: "Morning Star" },
      { index: 0x45, subtype: 0x08, name: "Scorpion Tail" },
      { index: 0x46, subtype: 0x09, name: "Romanda Gun" },
      { index: 0x47, subtype: 0x09, name: "Mythril Gun" },
      { index: 0x48, subtype: 0x09, name: "Stone Gun" },
      { index: 0x49, subtype: 0x09, name: "Blaze Gun" },
      { index: 0x4a, subtype: 0x09, name: "Glacier Gun" },
      { index: 0x4b, subtype: 0x09, name: "Blast Gun" },
      { index: 0x4c, subtype: 0x0a, name: "Bow Gun" },
      { index: 0x4d, subtype: 0x0a, name: "Night Killer" },
      { index: 0x4e, subtype: 0x0a, name: "Cross Bow" },
      { index: 0x4f, subtype: 0x0a, name: "Poison Bow" },
      { index: 0x50, subtype: 0x0a, name: "Hunting Bow" },
      { index: 0x51, subtype: 0x0a, name: "Gastrafitis" },
      { index: 0x52, subtype: 0x0b, name: "Long Bow" },
      { index: 0x53, subtype: 0x0b, name: "Silver Bow" },
      { index: 0x54, subtype: 0x0b, name: "Ice Bow" },
      { index: 0x55, subtype: 0x0b, name: "Lightning Bow" },
      { index: 0x56, subtype: 0x0b, name: "Windslash Bow" },
      { index: 0x57, subtype: 0x0b, name: "Mythril Bow" },
      { index: 0x58, subtype: 0x0b, name: "Ultimus Bow" },
      { index: 0x59, subtype: 0x0b, name: "Yoichi Bow" },
      { index: 0x5a, subtype: 0x0b, name: "Perseus Bow" },
      { index: 0x5b, subtype: 0x0c, name: "Ramia Harp" },
      { index: 0x5c, subtype: 0x0c, name: "Bloody Strings" },
      { index: 0x5d, subtype: 0x0c, name: "Fairy Harp" },
      { index: 0x5e, subtype: 0x0d, name: "Battle Dict" },
      { index: 0x5f, subtype: 0x0d, name: "Monster Dict" },
      { index: 0x60, subtype: 0x0d, name: "Papyrus Plate" },
      { index: 0x61, subtype: 0x0d, name: "Madlemgen" },
      { index: 0x62, subtype: 0x0e, name: "Javelin" },
      { index: 0x63, subtype: 0x0e, name: "Spear" },
      { index: 0x64, subtype: 0x0e, name: "Mythril Spear" },
      { index: 0x65, subtype: 0x0e, name: "Partisan" },
      { index: 0x66, subtype: 0x0e, name: "Oberisk" },
      { index: 0x67, subtype: 0x0e, name: "Holy Lance" },
      { index: 0x68, subtype: 0x0e, name: "Dragon Whisker" },
      { index: 0x69, subtype: 0x0e, name: "Javelin" },
      { index: 0x6a, subtype: 0x0f, name: "Cypress Rod" },
      { index: 0x6b, subtype: 0x0f, name: "Battle Bamboo" },
      { index: 0x6c, subtype: 0x0f, name: "Musk Rod" },
      { index: 0x6d, subtype: 0x0f, name: "Iron Fan" },
      { index: 0x6e, subtype: 0x0f, name: "Gokuu Rod" },
      { index: 0x6f, subtype: 0x0f, name: "Ivory Rod" },
      { index: 0x70, subtype: 0x0f, name: "Octagon Rod" },
      { index: 0x71, subtype: 0x0f, name: "Whale Whisker" },
      { index: 0x72, subtype: 0x10, name: "C Bag" },
      { index: 0x73, subtype: 0x10, name: "FS Bag" },
      { index: 0x74, subtype: 0x10, name: "P Bag" },
      { index: 0x75, subtype: 0x10, name: "H Bag" },
      { index: 0x76, subtype: 0x11, name: "Persia" },
      { index: 0x77, subtype: 0x11, name: "Cashmere" },
      { index: 0x78, subtype: 0x11, name: "Ryozan Silk" },
      { index: 0x79, subtype: 0x12, name: "Shuriken" },
      { index: 0x7a, subtype: 0x12, name: "Magic Shuriken" },
      { index: 0x7b, subtype: 0x12, name: "Yagyu Darkness" },
      { index: 0x7c, subtype: 0x13, name: "Fire Ball" },
      { index: 0x7d, subtype: 0x13, name: "Water Ball" },
      { index: 0x7e, subtype: 0x13, name: "Lightning Ball" },
      { index: 0x7f, subtype: 0x14, name: "Escutcheon" },
      { index: 0x80, subtype: 0x14, name: "Buckler" },
      { index: 0x81, subtype: 0x14, name: "Bronze Shield" },
      { index: 0x82, subtype: 0x14, name: "Round Shield" },
      { index: 0x83, subtype: 0x14, name: "Mythril Shield" },
      { index: 0x84, subtype: 0x14, name: "Gold Shield" },
      { index: 0x85, subtype: 0x14, name: "Ice Shield" },
      { index: 0x86, subtype: 0x14, name: "Flame Shield" },
      { index: 0x87, subtype: 0x14, name: "Aegis Shield" },
      { index: 0x88, subtype: 0x14, name: "Diamond Shield" },
      { index: 0x89, subtype: 0x14, name: "Platina Shield" },
      { index: 0x8a, subtype: 0x14, name: "Crystal Shield" },
      { index: 0x8b, subtype: 0x14, name: "Genji Shield" },
      { index: 0x8c, subtype: 0x14, name: "Kaiser Plate" },
      { index: 0x8d, subtype: 0x14, name: "Venetian Shield" },
      { index: 0x8e, subtype: 0x14, name: "Escutcheon" },
    ],
  },
  {
    name: "Heads",
    items: [
      { index: 0x8f, subtype: 0x15, name: "Leather Helmet" },
      { index: 0x90, subtype: 0x15, name: "Bronze Helmet" },
      { index: 0x91, subtype: 0x15, name: "Iron Helmet" },
      { index: 0x92, subtype: 0x15, name: "Barbuta" },
      { index: 0x93, subtype: 0x15, name: "Mythril Helmet" },
      { index: 0x94, subtype: 0x15, name: "Gold Helmet" },
      { index: 0x95, subtype: 0x15, name: "Cross Helmet" },
      { index: 0x96, subtype: 0x15, name: "Diamond Helmet" },
      { index: 0x97, subtype: 0x15, name: "Platina Helmet" },
      { index: 0x98, subtype: 0x15, name: "Circlet" },
      { index: 0x99, subtype: 0x15, name: "Crystal Helmet" },
      { index: 0x9a, subtype: 0x15, name: "Genji Helmet" },
      { index: 0x9b, subtype: 0x15, name: "Grand Helmet" },
      { index: 0x9c, subtype: 0x16, name: "Leather Hat" },
      { index: 0x9d, subtype: 0x16, name: "Feather Hat" },
      { index: 0x9e, subtype: 0x16, name: "Red Hood" },
      { index: 0x9f, subtype: 0x16, name: "Headgear" },
      { index: 0xa0, subtype: 0x16, name: "Triangle Hat" },
      { index: 0xa1, subtype: 0x16, name: "Green Beret" },
      { index: 0xa2, subtype: 0x16, name: "Twist Headband" },
      { index: 0xa3, subtype: 0x16, name: "Holy Miter" },
      { index: 0xa4, subtype: 0x16, name: "Black Hood" },
      { index: 0xa5, subtype: 0x16, name: "Golden Hairpin" },
      { index: 0xa6, subtype: 0x16, name: "Flash Hat" },
      { index: 0xa7, subtype: 0x16, name: "Thief Hat" },
      { index: 0xa8, subtype: 0x17, name: "Cachusha" },
      { index: 0xa9, subtype: 0x17, name: "Barette" },
      { index: 0xaa, subtype: 0x17, name: "Ribbon" },
    ],
  },
  {
    name: "Armor",
    items: [
      { index: 0xab, subtype: 0x18, name: "Leather Armor" },
      { index: 0xac, subtype: 0x18, name: "Linen Cuirass" },
      { index: 0xad, subtype: 0x18, name: "Bronze Armor" },
      { index: 0xae, subtype: 0x18, name: "Chain Mail" },
      { index: 0xaf, subtype: 0x18, name: "Mythril Armor" },
      { index: 0xb0, subtype: 0x18, name: "Plate Mail" },
      { index: 0xb1, subtype: 0x18, name: "Gold Armor" },
      { index: 0xb2, subtype: 0x18, name: "Diamond Armor" },
      { index: 0xb3, subtype: 0x18, name: "Platina Armor" },
      { index: 0xb4, subtype: 0x18, name: "Carabini Mail" },
      { index: 0xb5, subtype: 0x18, name: "Crystal Mail" },
      { index: 0xb6, subtype: 0x18, name: "Genji Armor" },
      { index: 0xb7, subtype: 0x18, name: "Reflect Mail" },
      { index: 0xb8, subtype: 0x18, name: "Maximillian" },
      { index: 0xb9, subtype: 0x19, name: "Clothes" },
      { index: 0xba, subtype: 0x19, name: "Leather Outfit" },
      { index: 0xbb, subtype: 0x19, name: "Leather Vest" },
      { index: 0xbc, subtype: 0x19, name: "Chain Vest" },
      { index: 0xbd, subtype: 0x19, name: "Mythril Vest" },
      { index: 0xbe, subtype: 0x19, name: "Adaman Vest" },
      { index: 0xbf, subtype: 0x19, name: "Wizard Outfit" },
      { index: 0xc0, subtype: 0x19, name: "Brigandine" },
      { index: 0xc1, subtype: 0x19, name: "Judo Outfit" },
      { index: 0xc2, subtype: 0x19, name: "Power Sleeve" },
      { index: 0xc3, subtype: 0x19, name: "Earth Clothes" },
      { index: 0xc4, subtype: 0x19, name: "Secret Clothes" },
      { index: 0xc5, subtype: 0x19, name: "Black Costume" },
      { index: 0xc6, subtype: 0x19, name: "Rubber Costume" },
      { index: 0xc7, subtype: 0x1a, name: "Linen Robe" },
      { index: 0xc8, subtype: 0x1a, name: "Silk Robe" },
      { index: 0xc9, subtype: 0x1a, name: "Wizard Robe" },
      { index: 0xca, subtype: 0x1a, name: "Chameleon Robe" },
      { index: 0xcb, subtype: 0x1a, name: "White Robe" },
      { index: 0xcc, subtype: 0x1a, name: "Black Robe" },
      { index: 0xcd, subtype: 0x1a, name: "Light Robe" },
      { index: 0xce, subtype: 0x1a, name: "Robe of Lords" },
    ],
  },
  {
    name: "Accessories",
    items: [
      { index: 0xcf, subtype: 0x1b, name: "Battle Boots" },
      { index: 0xd0, subtype: 0x1b, name: "Spike Shoes" },
      { index: 0xd1, subtype: 0x1b, name: "Germinas Boots" },
      { index: 0xd2, subtype: 0x1b, name: "Rubber Shoes" },
      { index: 0xd3, subtype: 0x1b, name: "Feather Boots" },
      { index: 0xd4, subtype: 0x1b, name: "Sprint Shoes" },
      { index: 0xd5, subtype: 0x1b, name: "Red Shoes" },
      { index: 0xd6, subtype: 0x1c, name: "Power Wrist" },
      { index: 0xd7, subtype: 0x1c, name: "Genji Gauntlet" },
      { index: 0xd8, subtype: 0x1c, name: "Magic Gauntlet" },
      { index: 0xd9, subtype: 0x1c, name: "Bracer" },
      { index: 0xda, subtype: 0x1d, name: "Reflect Ring" },
      { index: 0xdb, subtype: 0x1d, name: "Defense Ring" },
      { index: 0xdc, subtype: 0x1d, name: "Magic Ring" },
      { index: 0xdd, subtype: 0x1d, name: "Cursed Ring" },
      { index: 0xde, subtype: 0x1d, name: "Angel Ring" },
      { index: 0xdf, subtype: 0x1e, name: "Diamond Armlet" },
      { index: 0xe0, subtype: 0x1e, name: "Jade Armlet" },
      { index: 0xe1, subtype: 0x1e, name: "108 Gems" },
      { index: 0xe2, subtype: 0x1e, name: "N-Kai Armlet" },
      { index: 0xe3, subtype: 0x1e, name: "Defense Armlet" },
      { index: 0xe4, subtype: 0x1f, name: "Small Mantle" },
      { index: 0xe5, subtype: 0x1f, name: "Leather Mantle" },
      { index: 0xe6, subtype: 0x1f, name: "Wizard Mantle" },
      { index: 0xe7, subtype: 0x1f, name: "Elf Mantle" },
      { index: 0xe8, subtype: 0x1f, name: "Dracula Mantle" },
      { index: 0xe9, subtype: 0x1f, name: "Feather Mantle" },
      { index: 0xea, subtype: 0x1f, name: "Vanish Mantle" },
      { index: 0xeb, subtype: 0x20, name: "Chantage" },
      { index: 0xec, subtype: 0x20, name: "Cherche" },
      { index: 0xed, subtype: 0x20, name: "Setiemson" },
      { index: 0xee, subtype: 0x20, name: "Salty Rage" },
    ],
  },
  {
    name: "Items",
    items: [
      { index: 0xef, subtype: 0x21, name: "Potion" },
      { index: 0xf0, subtype: 0x21, name: "Hi-Potion" },
      { index: 0xf1, subtype: 0x21, name: "X-Potion" },
      { index: 0xf2, subtype: 0x21, name: "Ether" },
      { index: 0xf3, subtype: 0x21, name: "Hi-Ether" },
      { index: 0xf4, subtype: 0x21, name: "Elixir" },
      { index: 0xf5, subtype: 0x21, name: "Antidote" },
      { index: 0xf6, subtype: 0x21, name: "Eye Drop" },
      { index: 0xf7, subtype: 0x21, name: "Echo Grass" },
      { index: 0xf8, subtype: 0x21, name: "Maiden's Kiss" },
      { index: 0xf9, subtype: 0x21, name: "Soft" },
      { index: 0xfa, subtype: 0x21, name: "Holy Water" },
      { index: 0xfb, subtype: 0x21, name: "Remedy" },
      { index: 0xfc, subtype: 0x21, name: "Phoenix Down" },
    ],
  },
];

interface InventorySubtype {
  index: number;
  name: string;
  items: { index: number; name: string; subtype: number }[];
}

export const inventory: {
  name: string;
  subtypes: InventorySubtype[];
}[] = [];

export const hands: Resource = {};
export const heads: Resource = {};
export const bodies: Resource = {};
export const accessories: Resource = {};

export const handsGroups: ResourceGroups = [];
export const headsGroups: ResourceGroups = [];
export const bodiesGroups: ResourceGroups = [];
export const accessoriesGroups: ResourceGroups = [];

itemSubtypes.forEach((type) => {
  if (type.index <= 0x11 || type.index === 0x14) {
    handsGroups[type.index] = { name: type.name, options: [] };
  } else if (type.index >= 0x15 && type.index <= 0x17) {
    headsGroups[type.index] = { name: type.name, options: [] };
  } else if (type.index >= 0x18 && type.index <= 0x1a) {
    bodiesGroups[type.index] = { name: type.name, options: [] };
  } else if (type.index >= 0x1b && type.index <= 0x20) {
    accessoriesGroups[type.index] = { name: type.name, options: [] };
  }
});

inventoryList.forEach((type, index) => {
  const subtypes: InventorySubtype[] = [];

  type.items.forEach((item) => {
    let subtype = subtypes.find((subtype) => subtype.index === item.subtype);

    if (!subtype) {
      subtype = {
        index: item.subtype,
        name: itemSubtypes[item.subtype].name,
        items: [],
      };

      subtypes.push(subtype);
    }

    subtype.items.push(item);

    switch (index) {
      case 0: // Weapons
        if (item.subtype <= 0x11 || item.subtype === 0x14) {
          hands[item.index + 0x1] = item.name;
          handsGroups[item.subtype].options.push(item.index + 0x1);
        }
        break;
      case 1: // Heads
        if (item.subtype >= 0x15 && item.subtype <= 0x17) {
          heads[item.index + 0x1] = item.name;
          headsGroups[item.subtype].options.push(item.index + 0x1);
        }
        break;
      case 2: // Armor
        if (item.subtype >= 0x18 && item.subtype <= 0x1a) {
          bodies[item.index + 0x1] = item.name;
          bodiesGroups[item.subtype].options.push(item.index + 0x1);
        }
        break;
      case 3: // Accessories
        if (item.subtype >= 0x1b && item.subtype <= 0x20) {
          accessories[item.index + 0x1] = item.name;
          accessoriesGroups[item.subtype].options.push(item.index + 0x1);
        }
        break;
    }
  });

  inventory.push({ name: type.name, subtypes });
});

export const locationList = [
  { index: 0x00, name: "Lesalia Imperial Capital" },
  { index: 0x01, name: "Riovanes Castle" },
  { index: 0x02, name: "Igros Castle" },
  { index: 0x03, name: "Lionel Castle" },
  { index: 0x04, name: "Limberry Castle" },
  { index: 0x05, name: "Zeltennia Castle" },
  { index: 0x06, name: "Magic City Gariland" },
  { index: 0x07, name: "Yardow Fort City" },
  { index: 0x08, name: "Goland Coal City" },
  { index: 0x09, name: "Dorter Trade City" },
  { index: 0x0a, name: "Zaland Fort City" },
  { index: 0x0b, name: "Goug Machine City" },
  { index: 0x0c, name: "Warjilis Trade City" },
  { index: 0x0d, name: "Bervenia Free City" },
  { index: 0x0e, name: "Zarghidas Trade City" },
  { index: 0x0f, name: "Fort Zeakden" },
  { index: 0x10, name: "Murond Holy Place" },
  { index: 0x11, name: "Thieves Fort" },
  { index: 0x12, name: "Orbonne Monastery" },
  { index: 0x13, name: "Golgorand Execution Site" },
  { index: 0x14, name: "Murond Death City" },
  { index: 0x15, name: "Bethla Garrison" },
  { index: 0x16, name: "Deep Dungeon" },
  { index: 0x17, name: "Nelveska Temple" },
  { index: 0x18, name: "Mandalia Plains" },
  { index: 0x19, name: "Fovoham Plains" },
  { index: 0x1a, name: "Sweegy Woods" },
  { index: 0x1b, name: "Bervenia Volcano" },
  { index: 0x1c, name: "Zeklaus Desert" },
  { index: 0x1d, name: "Lenalia Plateau" },
  { index: 0x1e, name: "Zigolis Swamp" },
  { index: 0x1f, name: "Yuguo Woods" },
  { index: 0x20, name: "Araguay Woods" },
  { index: 0x21, name: "Grog Hill" },
  { index: 0x22, name: "Bed Desert" },
  { index: 0x23, name: "Zirekile Falls" },
  { index: 0x24, name: "Dolbodar Swamp" },
  { index: 0x25, name: "Bariaus Hill" },
  { index: 0x26, name: "Doguola Pass" },
  { index: 0x27, name: "Bariaus Valley" },
  { index: 0x28, name: "Finath River" },
  { index: 0x29, name: "Poeskas Lake" },
  { index: 0x2a, name: "Germinas Peak" },
];

export const locations: Resource = {};

locationList.forEach((location) => {
  locations[location.index] = location.name;
});

// prettier-ignore
export const persons = [
  { index: 0x00, name: "Ramza"    , max: 6 },
  { index: 0x01, name: "Delita"   , max: 7 },
  { index: 0x02, name: "Ovelia"   , max: 6 },
  { index: 0x03, name: "Alma"     , max: 4 },
  { index: 0x04, name: "Zalbag"   , max: 3 },
  { index: 0x05, name: "Dycedarg" , max: 4 },
  { index: 0x06, name: "Larg"     , max: 4 },
  { index: 0x07, name: "Goltana"  , max: 4 },
  { index: 0x08, name: "Orinas"   , max: 4 },
  { index: 0x09, name: "Ruvelia"  , max: 4 },
  { index: 0x0a, name: "Omdoria"  , max: 3 },
  { index: 0x0b, name: "Funeral"  , max: 3 },
  { index: 0x0c, name: "Algus"    , max: 3 },
  { index: 0x0d, name: "Gafgarion", max: 2 },
  { index: 0x0e, name: "Agrias"   , max: 2 },
  { index: 0x0f, name: "Orlandu"  , max: 3 },
  { index: 0x10, name: "Olan"     , max: 3 },
  { index: 0x11, name: "Zalmo"    , max: 2 },
  { index: 0x14, name: "Simon"    , max: 2 },
  { index: 0x16, name: "Beowulf"  , max: 2 },
  { index: 0x17, name: "Wiegraf"  , max: 4 },
  { index: 0x18, name: "Reis"     , max: 2 },
  { index: 0x19, name: "Balmafula", max: 2 },
  { index: 0x1a, name: "Draclau"  , max: 3 },
  { index: 0x1c, name: "Rafa"     , max: 2 },
  { index: 0x1d, name: "Malak"    , max: 3 },
  { index: 0x1e, name: "Elmdor"   , max: 3 },
  { index: 0x20, name: "Barinten" , max: 2 },
  { index: 0x22, name: "Mustadio" , max: 1 },
  { index: 0x23, name: "Besrodio" , max: 3 },
  { index: 0x24, name: "Rudvich"  , max: 3 },
  { index: 0x25, name: "Celia"    , max: 2 },
  { index: 0x26, name: "Lede"     , max: 2 },
  { index: 0x27, name: "Ajora"    , max: 1 },
  { index: 0x28, name: "Vormav"   , max: 3 },
  { index: 0x29, name: "Rofel"    , max: 1 },
  { index: 0x2a, name: "Izlude"   , max: 3 },
  { index: 0x2b, name: "Kletian"  , max: 1 },
  { index: 0x2c, name: "Balk"     , max: 1 },
  { index: 0x2d, name: "Meliadoul", max: 2 },
  { index: 0x2e, name: "Cloud"    , max: 1 },
  { index: 0x2f, name: "Teta"     , max: 3 },
  { index: 0x30, name: "Balbanes" , max: 2 },
  { index: 0x31, name: "Gustav"   , max: 2 },
  { index: 0x32, name: "Miluda"   , max: 2 },
  { index: 0x33, name: "Golagros" , max: 3 },
  { index: 0x3d, name: "Daravon"  , max: 1 },
  { index: 0x3e, name: "Elidibs"  , max: 1 },
  { index: 0x3f, name: "Alazlam"  , max: 1 },
];

// prettier-ignore
export const propositionList = [
  { index: 0x00, name: "Destiny of the Company" , jobName: "Highwind Salvage" },
  { index: 0x01, name: "Sunken Salvage Tour"    , jobName: "Salvage Tour Thoughts" },
  { index: 0x02, name: "Sailor Tour"            , jobName: "Sailor Tour Thoughts" },
  { index: 0x03, name: "Larner Channel Waves"   , jobName: "Enterprise Salvage" },
  { index: 0x04, name: "Attractive Workplace"   , jobName: "Attractive Workplace?" },
  { index: 0x05, name: "Salvage the Trade Ship!", jobName: "Hindenburg Salvage" },
  { index: 0x06, name: "Envoy ship, Falcon"     , jobName: "Falcon Salvage" },
  { index: 0x07, name: "Heir of Mesa"           , jobName: "Legend of Heroic King" },
  { index: 0x08, name: "Salvage the Trade Ship!", jobName: "Doga Salvage" },
  { index: 0x09, name: "Emissary of Lionel"     , jobName: "Envoy Ship of Lionel Castle" },
  { index: 0x0a, name: "Zaland Embassy"         , jobName: "Luxurious ship salvage" },
  { index: 0x0b, name: "Stolen Ancient Writings", jobName: "Lost Ancient Writings" },
  { index: 0x0c, name: "Good Workplace and Job!", jobName: "Good Workplace and Job?" },
  { index: 0x0d, name: "Sea of Gredia Island"   , jobName: "Salvage in Riovanes!" },
  { index: 0x0e, name: "Stranded Trade Ship"    , jobName: "Vessel of Istanbul" },
  { index: 0x0f, name: "Trade Ship Douing"      , jobName: "Douing Salvage" },
  { index: 0x10, name: "Mine Excavation Tour"   , jobName: "Mining Tour Thoughts" },
  { index: 0x11, name: "Miner's Tour"           , jobName: "Miner's Tour Thoughts" },
  { index: 0x12, name: "Will of Elder Topa"     , jobName: "Letter to the Family" },
  { index: 0x13, name: "Miner's Tour 2"         , jobName: "Miner's Tour Repeated!" },
  { index: 0x14, name: "Dream of a Miner"       , jobName: "Anything's possible!" },
  { index: 0x15, name: "Vacancy!"               , jobName: "Guide to Miners" },
  { index: 0x16, name: "Miners Wanted!"         , jobName: "Miner's Day Off" },
  { index: 0x17, name: "Girl at Gulg Volcano"   , jobName: "Girl of Flame!?" },
  { index: 0x18, name: "Hidden Trap at the Maze", jobName: "The First One Back" },
  { index: 0x19, name: "Himka Cliffs"           , jobName: "Behind the Cliff" },
  { index: 0x1a, name: "The Lord's Ore"         , jobName: "Meet with the Unknown" },
  { index: 0x1b, name: "One Activity"           , jobName: "One Activity" },
  { index: 0x1c, name: "Miners Wanted! 2"       , jobName: "Fight of the Miners" },
  { index: 0x1d, name: "Rolade Ore Company"     , jobName: "Ghost Staffs" },
  { index: 0x1e, name: "Testimony of Ex-miner"  , jobName: "Tears of an Ex-miner" },
  { index: 0x1f, name: "Death Canyon"           , jobName: "15 Black Knights" },
  { index: 0x20, name: "Discovery Race"         , jobName: "After the Discovery Race" },
  { index: 0x21, name: "Poeskas Lake Bottom"    , jobName: "Things at Lake bottom" },
  { index: 0x22, name: "Discovery Race 2"       , jobName: "After 2nd Discovery Race" },
  { index: 0x23, name: "Legendary Traces"       , jobName: "Thing at Myst. Frontier" },
  { index: 0x24, name: "Discovery Race 3"       , jobName: "After 3rd Discovery Race" },
  { index: 0x25, name: "Deep in Sweegy Woods"   , jobName: "Thing in Deep Forest" },
  { index: 0x26, name: "Ruins at Bed Desert"    , jobName: "Thing at Bed Desert" },
  { index: 0x27, name: "Adventurer Ramzen"      , jobName: "Thing at Zeklaus Desert" },
  { index: 0x28, name: "I saw it."              , jobName: "Over Mountain Pass" },
  { index: 0x29, name: "Discovery Tour"         , jobName: "Discovery Tour Thoughts" },
  { index: 0x2a, name: "Storm of Zigolis!"      , jobName: "Thing in the Swamps" },
  { index: 0x2b, name: "Ominous Dungeon"        , jobName: "Maze of Ancient People" },
  { index: 0x2c, name: "Adventurer Wanted!"     , jobName: "Join the Adventurer Team!" },
  { index: 0x2d, name: "I saw it! I swear!"     , jobName: "Report! It is true!" },
  { index: 0x2e, name: "Concerns of a Merchant" , jobName: "Merchants' Worries!" },
  { index: 0x2f, name: "Mountain of Rain"       , jobName: "In the Mist..." },
  { index: 0x30, name: "Defeat Golden Gotsko!"  , jobName: "Wyberns Annihilated!" },
  { index: 0x31, name: "Defeat Behemoth!"       , jobName: "Wild Kingdom" },
  { index: 0x32, name: "Trap of the Bandits"    , jobName: "Battle! Demon Lylis" },
  { index: 0x33, name: "Son, Pappal!"           , jobName: "Father and Child" },
  { index: 0x34, name: "Within the Darkness"    , jobName: "Whisper Grass in Dark" },
  { index: 0x35, name: "Defeat Whirlwind Karz!" , jobName: "Battle! Whirlwind Karz!" },
  { index: 0x36, name: "Minimum's Melancholy"   , jobName: "Crime of Ct. Minimum!" },
  { index: 0x37, name: "Terror of Assault Cave" , jobName: "Battle! Assault Cave!" },
  { index: 0x38, name: "Challenge of Zero"      , jobName: "That is not the Aim!" },
  { index: 0x39, name: "Phantom Thief Zero!"    , jobName: "Too Naive" },
  { index: 0x3a, name: "Thief Zero Returns!"    , jobName: "Pleasure of a Goddess" },
  { index: 0x3b, name: "Thief Zero Reborn!"     , jobName: "Women held in arms..." },
  { index: 0x3c, name: "Thief Zero's Last Stand", jobName: "Bye, Noble of Darkness!" },
  { index: 0x3d, name: "Legendary Monster"      , jobName: "At the Hilltop Mansion?" },
  { index: 0x3e, name: "Sullen Experiment"      , jobName: "Unfortunate Monsters" },
  { index: 0x3f, name: "Fiar's Request"         , jobName: "Fiar's Intentions!" },
  { index: 0x40, name: "Dream child"            , jobName: "Back then..." },
  { index: 0x41, name: "Protect the Little Life", jobName: "Rescue of Cornelia!" },
  { index: 0x42, name: "If wishes come true"    , jobName: "Return of Pappal!" },
  { index: 0x43, name: "My Little Carrot"       , jobName: "Ultimate Atavism" },
  { index: 0x44, name: "Secret Door"            , jobName: "Thoughts of a Doll" },
  { index: 0x45, name: "Orders of Coast Guard"  , jobName: "Letter from distant" },
  { index: 0x46, name: "Devil in the Dark"      , jobName: "Battle! Mud Man!" },
  { index: 0x47, name: "Mother"                 , jobName: "Darkness of Eternal Way" },
  { index: 0x48, name: "My treasure"            , jobName: "Demon Golem" },
  { index: 0x49, name: "The Greatest Plan"      , jobName: "Final Resistance" },
  { index: 0x4a, name: "Secret Society"         , jobName: "Informant" },
  { index: 0x4b, name: "How much is Life worth?", jobName: "Most Precious Thing" },
  { index: 0x4c, name: "Letter to my Love"      , jobName: "Poet Gilbert's Thoughts" },
  { index: 0x4d, name: "Minimum's Melancholy"   , jobName: "Delighted Ct. Minimum!" },
  { index: 0x4e, name: "Road of Beasts"         , jobName: "Cannibalistic Plant" },
  { index: 0x4f, name: "True Romance"           , jobName: "Joyous Song for You" },
  { index: 0x50, name: "Shy Katedona"           , jobName: "The Talkative, Katedona" },
  { index: 0x51, name: "Master Math!"           , jobName: "Courage of Durman!" },
  { index: 0x52, name: "Sad Traveling Artist"   , jobName: "Regain Ability!" },
  { index: 0x53, name: "Minimum's Melancholy"   , jobName: "Delighted Ct. Minimum!" },
  { index: 0x54, name: "Machinist Contest"      , jobName: "Won Machinist Contest!" },
  { index: 0x55, name: "Traveling Artist Mameko", jobName: "Artist Mameko Leaves!" },
  { index: 0x56, name: "Chocobo Restaurant"     , jobName: "Chocobo Restaurant" },
  { index: 0x57, name: "Wandering Gambler"      , jobName: "Ship Casino, Black Jack" },
  { index: 0x58, name: "Wandering Gambler"      , jobName: "Storm of 777!" },
  { index: 0x59, name: "Ringing of the Bell"    , jobName: "Inside Lakam Trade Co." },
  { index: 0x5a, name: "Memories"               , jobName: "Cherish Memories" },
  { index: 0x5b, name: "Hard Lecture"           , jobName: "A Perfect Smile!" },
  { index: 0x5c, name: "Win the Yardow Fight!"  , jobName: "Won the Yardow Fight!" },
  { index: 0x5d, name: "Win the Zaland Fight!"  , jobName: "Won the Zaland Fight!" },
  { index: 0x5e, name: "Win the Magic Contest!" , jobName: "Won the Magic Contest!" },
  { index: 0x5f, name: "Meister Contest"        , jobName: "Won the Meister Contest!" },
];

export const propositions = propositionList.reduce(
  (propositions: Resource, proposition) => {
    propositions[proposition.index] = proposition.name;

    return propositions;
  },
  {},
);

export const treasures = [
  { index: 0x00, name: "Four Gods Set" },
  { index: 0x01, name: "Statue of Lylis" },
  { index: 0x02, name: "Beetle Charm" },
  { index: 0x03, name: "Tobacco Pipe" },
  { index: 0x04, name: "Zeni-Sword" },
  { index: 0x05, name: "Black Cat" },
  { index: 0x06, name: "Malice Mask" },
  { index: 0x07, name: "Parade Helmet" },
  { index: 0x08, name: "Kid's Bread" },
  { index: 0x09, name: "Adult's Bread" },
  { index: 0x0a, name: "Calcobrina" },
  { index: 0x0b, name: "Yurgeivogue" },
  { index: 0x0c, name: "Red Materia" },
  { index: 0x0d, name: "Blue Materia" },
  { index: 0x0e, name: "Black Materia" },
  { index: 0x0f, name: "White Materia" },
  { index: 0x10, name: "Rat Tail" },
  { index: 0x11, name: "M-Fiction Novel" },
  { index: 0x12, name: "Diary of Nanai" },
  { index: 0x13, name: "Wyuvle" },
  { index: 0x14, name: "Book of Enavia" },
  { index: 0x15, name: "Magical Gun" },
  { index: 0x16, name: "M Machinegun" },
  { index: 0x17, name: "Magi-Sword" },
  { index: 0x18, name: "Minu Orb" },
  { index: 0x19, name: "Tarot of Ben" },
  { index: 0x1a, name: "Excalipar" },
  { index: 0x1b, name: "Parasite Tree" },
  { index: 0x1c, name: "Longibunne Spear" },
  { index: 0x1d, name: "Chocobo Cannon" },
  { index: 0x1e, name: "St. Elmo's Fire" },
  { index: 0x1f, name: "Germonik Scriptures" },
  { index: 0x20, name: "Treasure (Pre. 1)" },
  { index: 0x21, name: "Treasure (Pre. 2)" },
  { index: 0x22, name: "Aries" },
  { index: 0x23, name: "Taurus" },
  { index: 0x24, name: "Gemini" },
  { index: 0x25, name: "Cancer" },
  { index: 0x26, name: "Leo" },
  { index: 0x27, name: "Virgo" },
  { index: 0x28, name: "Libra" },
  { index: 0x29, name: "Scorpio" },
  { index: 0x2a, name: "Sagittarius" },
  { index: 0x2b, name: "Capricorn" },
  { index: 0x2c, name: "Aquarius" },
  { index: 0x2d, name: "Pisces" },
  { index: 0x2e, name: "Serpentarius" },
];

export const unexploredLands = [
  { index: 0x0, name: "Shrine of Chaos" },
  { index: 0x1, name: "Forbidden Land Eureka" },
  { index: 0x2, name: "Pandemonium" },
  { index: 0x3, name: "Mirage Tower" },
  { index: 0x4, name: "Floating Castle" },
  { index: 0x5, name: "Matoya Cave" },
  { index: 0x6, name: "Crystal Tower" },
  { index: 0x7, name: "Magic Continent" },
  { index: 0x8, name: "Castle of Trials" },
  { index: 0x9, name: "Tower of Babel" },
  { index: 0xa, name: "Ronkan Ruins" },
  { index: 0xb, name: "Falgabird" },
  { index: 0xc, name: "Magic Train" },
  { index: 0xd, name: "Touzas Village" },
  { index: 0xe, name: "Chocobo Forest" },
  { index: 0xf, name: "Semite Falls" },
];
