import type { Resource } from "$lib/types";

export const characters = {
  0x0: "Synbios",
  0x1: "Dantares",
  0x2: "Masqurin",
  0x3: "Grace",
  0x4: "Hayward",
  0x5: "Obright",
  0x6: "Irene",
  0x7: "Julian",
  0x8: "Cybel",
  0x9: "Eldar",
  0xa: "Kahn",
  0xb: "Noon",
  0xc: "Justin",
  0xd: "Horst",
  0xe: "Penn",
  0xf: "Ratchet",
  0x10: "Frank",
  0x11: "Hagane",
  0x12: "Murasame",
  0x13: "Fynnding",
  0x14: "Medion",
  0x15: "Campbell",
  0x16: "Syntesis",
  0x17: "Uryudo",
  0x18: "Waltz",
  0x19: "Rock",
  0x1a: "Bernard",
  0x1b: "Zero",
  0x1c: "Hazuki",
  0x1d: "David",
  0x1e: "Hedva",
  0x1f: "Julian",
  0x20: "Donhort",
  0x21: "Hera",
  0x22: "Robby",
  0x23: "Arthur",
  0x24: "Garosh",
  0x25: "Jade",
  0x26: "Penko",
  0x27: "Pappets",
};

export const classes = {
  0x0: "Swordsman",
  0x1: "Knight",
  0x2: "Warrior",
  0x3: "Priest",
  0x4: "Magician",
  0x5: "Archer",
  0x6: "Monk",
  0x7: "Birdsoldier",
  0x8: "Ranger",
  0x9: "Penguin",
  0xa: "Steam Soldier",
  0xb: "Werewolf",
  0xc: "Ninja Tyro",
  0xd: "Kunoichi",
  0xe: "Elven Ranger",
  0xf: "Shaman",
  0x10: "Mecha Bot",
  0x11: "Metal Driver",
  0x12: "Penguin",
  0x13: "Trainer",
  // 0x14: "Reserve", // Unused
  // 0x15: "Reserve", // Unused
  // 0x16: "Reserve", // Unused
  // 0x17: "Reserve", // Unused
  // 0x18: "Reserve", // Unused
  // 0x19: "Reserve", // Unused
  // 0x1a: "Reserve", // Unused
  // 0x1b: "Reserve", // Unused
  // 0x1c: "Reserve", // Unused
  // 0x1d: "Reserve", // Unused
  // 0x1e: "Reserve", // Unused
  // 0x1f: "Reserve", // Unused
  0x20: "Hero",
  0x21: "Cavalier",
  0x22: "Gladiator",
  0x23: "Cleric",
  0x24: "Wizard",
  0x25: "Sniper",
  0x26: "Master Monk",
  0x27: "Birdknight",
  0x28: "Bow Knight",
  0x29: "Dynamo",
  0x2a: "Steam Knight",
  0x2b: "Wolf Baron",
  0x2c: "Ninja",
  0x2d: "Ninja",
  0x2e: "Striker",
  0x2f: "Summoner",
  0x30: "Mecha Soldier",
  0x31: "Gunner",
  0x32: "Diva",
  0x33: "Beast Tamer",
  0x34: "Godchild",
  // 0x35: "Reserve", // Unused
  // 0x36: "Reserve", // Unused
  // 0x37: "Reserve", // Unused
  // 0x38: "Reserve", // Unused
  // 0x39: "Reserve", // Unused
  // 0x3a: "Reserve", // Unused
  // 0x3b: "Reserve", // Unused
  // 0x3c: "Reserve", // Unused
  // 0x3d: "Reserve", // Unused
  // 0x3e: "Reserve", // Unused
  // 0x3f: "Reserve", // Unused
  0x40: "Light Apostle",
  0x41: "Paladin",
  0x42: "Berserker",
  0x43: "Paladin",
  0x44: "Sorcerer",
  0x45: "Sumonner",
};

export const itemTypes = {
  0x1: "Items",
  0xa: "Knifes",
  0xb: "Swords",
  0xc: "Rapiers",
  0xd: "Blades",
  0xe: "Katanas",
  0xf: "Wings",
  0x14: "Lances",
  0x15: "Spears",
  0x16: "Halberds",
  0x1e: "Axes",
  0x1f: "Hatchets",
  0x20: "Maces",
  0x21: "Anchors",
  0x32: "Claws",
  0x33: "Gloves",
  0x34: "Cestus",
  0x3c: "Rods",
  0x3d: "Wands",
  0x3e: "Ankhs",
  0x46: "Arrows",
  0x47: "Quarrels",
  0x48: "Shells",
  0x4a: "Shurikens",
  0x50: "Beaks",
  0x5a: "Whips",
  0x7a: "Bracers",
  0x7b: "Tiaras",
  0x7c: "Helmets",
  0x81: "Accessories",
};

export const itemsDetails = [
  { index: 0x1, name: "Bronze Knife", type: 0xa },
  { index: 0x2, name: "Steel Knife", type: 0xa },
  { index: 0x3, name: "Hunter Knife", type: 0xa },
  { index: 0x4, name: "Steel Sword", type: 0xb },
  { index: 0x5, name: "Broad Sword", type: 0xb },
  { index: 0x6, name: "Bastard Sword", type: 0xb },
  { index: 0x7, name: "Great Sword", type: 0xb },
  { index: 0x8, name: "Epee", type: 0xc },
  { index: 0x9, name: "Foil", type: 0xc },
  { index: 0xa, name: "Rapier", type: 0xc },
  { index: 0xb, name: "Iron Blade", type: 0xd },
  { index: 0xc, name: "Battle Blade", type: 0xd },
  { index: 0xd, name: "Steel Blade", type: 0xd },
  { index: 0xe, name: "Small Katana", type: 0xe },
  { index: 0xf, name: "Ninja Katana", type: 0xe },
  { index: 0x10, name: "Steel Ninjato", type: 0xe },
  { index: 0x11, name: "Bronze Lance", type: 0x14 },
  { index: 0x12, name: "Iron Lance", type: 0x14 },
  { index: 0x13, name: "Heavy Lance", type: 0x14 },
  { index: 0x14, name: "Steel Lance", type: 0x14 },
  { index: 0x15, name: "Spear", type: 0x15 },
  { index: 0x16, name: "Power Spear", type: 0x15 },
  { index: 0x17, name: "Battle Spear", type: 0x15 },
  { index: 0x18, name: "Halberd", type: 0x16 },
  { index: 0x19, name: "Heavy Halberd", type: 0x16 },
  { index: 0x1a, name: "Poleaxe", type: 0x16 },
  { index: 0x1b, name: "Small Axe", type: 0x1e },
  { index: 0x1c, name: "Power Axe", type: 0x1e },
  { index: 0x1d, name: "Battle Axe", type: 0x1e },
  { index: 0x1e, name: "Great Axe", type: 0x1e },
  { index: 0x1f, name: "Tomahawk", type: 0x1f },
  { index: 0x20, name: "Power Hatchet", type: 0x1f },
  { index: 0x21, name: "Battle Hatchet", type: 0x1f },
  { index: 0x22, name: "Mace", type: 0x20 },
  { index: 0x23, name: "Flail", type: 0x20 },
  { index: 0x24, name: "Battle Mace", type: 0x20 },
  { index: 0x25, name: "Bronze Claw", type: 0x32 },
  { index: 0x26, name: "Iron Claw", type: 0x32 },
  { index: 0x27, name: "Steel Claw", type: 0x32 },
  { index: 0x28, name: "Battle Claw", type: 0x32 },
  { index: 0x29, name: "Leather Glove", type: 0x33 },
  { index: 0x2a, name: "Iron Glove", type: 0x33 },
  { index: 0x2b, name: "Steel Glove", type: 0x33 },
  { index: 0x2c, name: "Cestus", type: 0x34 },
  { index: 0x2d, name: "Iron Cestus", type: 0x34 },
  { index: 0x2e, name: "Steel Cestus", type: 0x34 },
  { index: 0x2f, name: "Wooden Rod", type: 0x3c },
  { index: 0x30, name: "Bronze Rod", type: 0x3c },
  { index: 0x31, name: "Talisman Rod", type: 0x3c },
  { index: 0x32, name: "Small Wand", type: 0x3d },
  { index: 0x33, name: "Magic Wand", type: 0x3d },
  { index: 0x34, name: "Anger Wand", type: 0x3d },
  { index: 0x35, name: "Power Ankh", type: 0x3e },
  { index: 0x36, name: "Saint Ankh", type: 0x3e },
  { index: 0x37, name: "Mystery Ankh", type: 0x3e },
  { index: 0x38, name: "Wooden Arrow", type: 0x46 },
  { index: 0x39, name: "Steel Arrow", type: 0x46 },
  { index: 0x3a, name: "Robin Arrow", type: 0x46 },
  { index: 0x3b, name: "King Arrow", type: 0x46 },
  { index: 0x3c, name: "Light Quarrel", type: 0x47 },
  { index: 0x3d, name: "Middle Quarrel", type: 0x47 },
  { index: 0x3e, name: "Heavy Quarrel", type: 0x47 },
  { index: 0x3f, name: "Assault Shell", type: 0x48 },
  { index: 0x40, name: "Great Shell", type: 0x48 },
  { index: 0x41, name: "Buster Shot", type: 0x48 },
  { index: 0x42, name: "Scimitar", type: 0xb },
  { index: 0x43, name: "Chaos Ring", type: 0x81 },
  { index: 0x44, name: "Power Ring", type: 0x81 },
  { index: 0x45, name: "Protect Ring", type: 0x81 },
  { index: 0x46, name: "Magic Ring", type: 0x81 },
  { index: 0x47, name: "Gale Ring", type: 0x81 },
  { index: 0x48, name: "Attack Ring", type: 0x81 },
  { index: 0x49, name: "Master Ring", type: 0x81 },
  { index: 0x4a, name: "Silver Ring", type: 0x81 },
  { index: 0x4b, name: "Life Ring", type: 0x81 },
  { index: 0x4c, name: "Running Ring", type: 0x81 },
  { index: 0x4d, name: "White Ring", type: 0x81 },
  { index: 0x4e, name: "Black Ring", type: 0x81 },
  { index: 0x4f, name: "Evil Ring", type: 0x81 },
  { index: 0x50, name: "Artemis Pin", type: 0x81 },
  { index: 0x51, name: "Apollo Pin", type: 0x81 },
  { index: 0x52, name: "Battle Bracer", type: 0x7a },
  { index: 0x53, name: "Protect Bracer", type: 0x7a },
  { index: 0x54, name: "Medical Herb", type: 0x1 },
  { index: 0x55, name: "Healing Drop", type: 0x1 },
  { index: 0x56, name: "Potion", type: 0x1 },
  { index: 0x57, name: "Healing Rain", type: 0x1 },
  { index: 0x58, name: "Goddess Tear", type: 0x1 },
  { index: 0x59, name: "Light of Hope", type: 0x1 },
  { index: 0x5a, name: "Antidote Herb", type: 0x1 },
  { index: 0x5b, name: "Fairy Powder", type: 0x1 },
  { index: 0x5c, name: "Angel Wing", type: 0x1 },
  { index: 0x5d, name: "Power Wine", type: 0x1 },
  { index: 0x5e, name: "Protect Milk", type: 0x1 },
  { index: 0x5f, name: "Quick Chicken", type: 0x1 },
  { index: 0x60, name: "Running Pepper", type: 0x1 },
  { index: 0x61, name: "Lucky Cookie", type: 0x1 },
  { index: 0x62, name: "Health Bread", type: 0x1 },
  { index: 0x63, name: "Bright Honey", type: 0x1 },
  { index: 0x64, name: "Brave Apple", type: 0x1 },
  { index: 0x65, name: "Large Mithril", type: 0x1 },
  { index: 0x66, name: "Small Mithril", type: 0x1 },
  { index: 0x67, name: "Dark Matter", type: 0x1 },
  { index: 0x68, name: "Platina Circlet", type: 0x7b },
  { index: 0x69, name: "Royal Tiara", type: 0x7b },
  { index: 0x6a, name: "Swift Boots", type: 0x81 },
  { index: 0x6b, name: "Shadow Helm", type: 0x7c },
  { index: 0x6c, name: "Dark Helmet", type: 0x7c },
  { index: 0x6d, name: "Loincloth", type: 0x81 },
  { index: 0x6e, name: "Power Undies", type: 0x81 },
  { index: 0x6f, name: "Mithril Dirk", type: 0xa },
  { index: 0x70, name: "Butterfly Knife", type: 0xa },
  { index: 0x71, name: "Assassin Knife", type: 0xa },
  { index: 0x72, name: "Thief Knife", type: 0xa },
  { index: 0x73, name: "Joker Knife", type: 0xa },
  { index: 0x74, name: "Counter Sword", type: 0xb },
  { index: 0x75, name: "Shiva Sword", type: 0xb },
  { index: 0x76, name: "Leviathan", type: 0xb },
  { index: 0x77, name: "Dark Sword", type: 0xb },
  { index: 0x78, name: "Phoenix Sword", type: 0xb },
  { index: 0x79, name: "Justice Sword", type: 0xb },
  { index: 0x7a, name: "Mist Rapier", type: 0xc },
  { index: 0x7b, name: "Magic Rapier", type: 0xc },
  { index: 0x7c, name: "Shiny Rapier", type: 0xc },
  { index: 0x7d, name: "Final Rapier", type: 0xc },
  { index: 0x7e, name: "Luster Blade", type: 0xd },
  { index: 0x7f, name: "Rune Blade", type: 0xd },
  { index: 0x80, name: "Photon Blade", type: 0xd },
  { index: 0x81, name: "Venom Blade", type: 0xd },
  { index: 0x82, name: "Force Blade", type: 0xd },
  { index: 0x83, name: "Gale Lance", type: 0x14 },
  { index: 0x84, name: "Holy Lance", type: 0x14 },
  { index: 0x85, name: "Dragon Lance", type: 0x14 },
  { index: 0x86, name: "Gungnir", type: 0x14 },
  { index: 0x87, name: "Silver Spear", type: 0x15 },
  { index: 0x88, name: "Counter Spear", type: 0x15 },
  { index: 0x89, name: "Rune Spear", type: 0x15 },
  { index: 0x8a, name: "Beast Spear", type: 0x15 },
  { index: 0x8b, name: "Comet Spear", type: 0x15 },
  { index: 0x8c, name: "Holy Halberd", type: 0x16 },
  { index: 0x8d, name: "Lord Halberd", type: 0x16 },
  { index: 0x8e, name: "Ark Halberd", type: 0x16 },
  { index: 0x8f, name: "Dark Halberd", type: 0x16 },
  { index: 0x90, name: "Heat Axe", type: 0x1e },
  { index: 0x91, name: "Giant Axe", type: 0x1e },
  { index: 0x92, name: "Dragon Axe", type: 0x1e },
  { index: 0x93, name: "Gaia Axe", type: 0x1e },
  { index: 0x94, name: "Evil Axe", type: 0x1e },
  { index: 0x95, name: "Rune Tomahawk", type: 0x1f },
  { index: 0x96, name: "Killer Hatchet", type: 0x1f },
  { index: 0x97, name: "Sky Tomahawk", type: 0x1f },
  { index: 0x98, name: "Ultra Tomahawk", type: 0x1f },
  { index: 0x99, name: "Saint Mace", type: 0x20 },
  { index: 0x9a, name: "Revenge Mace", type: 0x20 },
  { index: 0x9b, name: "Thor Hammer", type: 0x20 },
  { index: 0x9c, name: "Macho Mace", type: 0x20 },
  { index: 0x9d, name: "Mithril Claw", type: 0x32 },
  { index: 0x9e, name: "Tiger Claw", type: 0x32 },
  { index: 0x9f, name: "Berserk Claw", type: 0x32 },
  { index: 0xa0, name: "Digitalis Claw", type: 0x32 },
  { index: 0xa1, name: "Spiked Glove", type: 0x33 },
  { index: 0xa2, name: "Muscle Glove", type: 0x33 },
  { index: 0xa3, name: "Spark Glove", type: 0x33 },
  { index: 0xa4, name: "Magna Glove", type: 0x33 },
  { index: 0xa5, name: "Pretty Glove", type: 0x33 },
  { index: 0xa6, name: "Giant Cestus", type: 0x34 },
  { index: 0xa7, name: "Mist Cestus", type: 0x34 },
  { index: 0xa8, name: "Wire Cestus", type: 0x34 },
  { index: 0xa9, name: "Dragon Cestus", type: 0x34 },
  { index: 0xaa, name: "Torture Rod", type: 0x3c },
  { index: 0xab, name: "Sleepy Rod", type: 0x3c },
  { index: 0xac, name: "Alchemy Rod", type: 0x3c },
  { index: 0xad, name: "Crystal Rod", type: 0x3c },
  { index: 0xae, name: "Demon Rod", type: 0x3c },
  { index: 0xaf, name: "Jester Wand", type: 0x3d },
  { index: 0xb0, name: "Charm Wand", type: 0x3d },
  { index: 0xb1, name: "Witch Wand", type: 0x3d },
  { index: 0xb2, name: "Pyra's Wand", type: 0x3d },
  { index: 0xb3, name: "Wendigo Wand", type: 0x3d },
  { index: 0xb4, name: "Druid Ankh", type: 0x3e },
  { index: 0xb5, name: "Silence Ankh", type: 0x3e },
  { index: 0xb6, name: "Blessed Ankh", type: 0x3e },
  { index: 0xb7, name: "Holy Ankh", type: 0x3e },
  { index: 0xb8, name: "Moonlight Arrow", type: 0x46 },
  { index: 0xb9, name: "Dragon Arrow", type: 0x46 },
  { index: 0xba, name: "Breaker Arrow", type: 0x46 },
  { index: 0xbb, name: "Cantarella", type: 0x46 },
  { index: 0xbc, name: "Moogie Arrow", type: 0x46 },
  { index: 0xbd, name: "Mithril Quarrel", type: 0x47 },
  { index: 0xbe, name: "Flame Quarrel", type: 0x47 },
  { index: 0xbf, name: "Sonic Quarrel", type: 0x47 },
  { index: 0xc0, name: "Needle Quarrel", type: 0x47 },
  { index: 0xc1, name: "Magnum Shell", type: 0x48 },
  { index: 0xc2, name: "Storm Shot", type: 0x48 },
  { index: 0xc3, name: "Meteor Shot", type: 0x48 },
  { index: 0xc4, name: "Cold Blood", type: 0x81 },
  { index: 0xc5, name: "Wind Cutter", type: 0xe },
  { index: 0xc6, name: "Bone Eater", type: 0xe },
  { index: 0xc7, name: "Rumbling Sea", type: 0xe },
  { index: 0xc8, name: "Kusanagi", type: 0xe },
  { index: 0xc9, name: "Muramasa", type: 0xe },
  { index: 0xca, name: "Cross Shuriken", type: 0x4a },
  { index: 0xcb, name: "Fox Shuriken", type: 0x4a },
  { index: 0xcc, name: "Shaken", type: 0x4a },
  { index: 0xcd, name: "Spark Shuriken", type: 0x4a },
  { index: 0xce, name: "Octagon Star", type: 0x4a },
  { index: 0xcf, name: "Wind Shuriken", type: 0x4a },
  { index: 0xd0, name: "Metal Wing", type: 0xf },
  { index: 0xd1, name: "Silver Wing", type: 0xf },
  { index: 0xd2, name: "Battle Wing", type: 0xf },
  { index: 0xd3, name: "Sylph Wing", type: 0xf },
  { index: 0xd4, name: "Sonic Wing", type: 0xf },
  { index: 0xd5, name: "Cosmic Wing", type: 0xf },
  { index: 0xd6, name: "Zero Wing", type: 0xf },
  { index: 0xd7, name: "Stealth Wing", type: 0xf },
  { index: 0xd8, name: "Light Anchor", type: 0x21 },
  { index: 0xd9, name: "Heavy Anchor", type: 0x21 },
  { index: 0xda, name: "Power Anchor", type: 0x21 },
  { index: 0xdb, name: "Spin Anchor", type: 0x21 },
  { index: 0xdc, name: "Crash Anchor", type: 0x21 },
  { index: 0xdd, name: "Gravity Anchor", type: 0x21 },
  { index: 0xde, name: "Cut Flowers", type: 0x1 },
  { index: 0xdf, name: "Chicken Feed", type: 0x1 },
  { index: 0xe0, name: "Volcanon Wand", type: 0x3d },
  { index: 0xe1, name: "Large Egg", type: 0x1 },
  { index: 0xe2, name: "Ship Key", type: 0x1 },
  { index: 0xe3, name: "Statue Gem", type: 0x1 },
  { index: 0xe4, name: "Mitra Ankh", type: 0x3e },
  { index: 0xe5, name: "Saraband Key", type: 0x1 },
  { index: 0xe6, name: "Divine Cane", type: 0x3d },
  { index: 0xe7, name: "Hell Rod", type: 0x3c },
  { index: 0xe8, name: "Penko Beak", type: 0x50 },
  { index: 0xe9, name: "Lake Ruins Map", type: 0x1 },
  { index: 0xea, name: "River Map", type: 0x1 },
  { index: 0xeb, name: "Beach Map", type: 0x1 },
  { index: 0xec, name: "Treasury Map", type: 0x1 },
  { index: 0xed, name: "Border Map", type: 0x1 },
  { index: 0xee, name: "Subsurface Map", type: 0x1 },
  { index: 0xef, name: "Elbesem Orb", type: 0x81 },
  { index: 0xf0, name: "Barrand Key", type: 0x1 },
  { index: 0xf1, name: "Robot Eye", type: 0x1 },
  { index: 0xf2, name: "Secret Key", type: 0x1 },
  { index: 0xf3, name: "Freeze Orb", type: 0x1 },
  { index: 0xf4, name: "God Rapier", type: 0xc },
  { index: 0xf5, name: "Thunder Wand", type: 0x3d },
  { index: 0xf6, name: "Dragon Rod", type: 0x3c },
  { index: 0xf7, name: "Earth Rod", type: 0x3c },
  { index: 0xf8, name: "Chain Whip", type: 0x5a },
  { index: 0xf9, name: "Queen Whip", type: 0x5a },
  { index: 0xfa, name: "Love Whip", type: 0x5a },
  { index: 0xfb, name: "Jester Whip", type: 0x5a },
  { index: 0xfc, name: "Silver Beak", type: 0x50 },
  { index: 0xfd, name: "Golden Beak", type: 0x50 },
  { index: 0xfe, name: "Penguin Beak", type: 0x50 },
];

export const items = itemsDetails.reduce((items: Resource, item) => {
  items[item.index] = item.name;

  return items;
}, {});

export const locations = {
  0x0: "(Measurement Test) (TESMAP)",
  0x1: "(Store Test) (SHOP_T)",
  0x2: "Opening Movie (OPMOVIE)",
  0x3: "Logo Screen (LOGO)",
  0x4: "Sleepy Wise Man (DREAM)",
  0x5: "COMPLETE (COMPLETE)",
  0x6: "Ending (ENDING)",
  0x7: "Saraband Docks (BTL201)",
  0x8: "Balsamo East Plains (BTL202)",
  0x9: "Dusty West Plains (BTL203)",
  0xa: "Dusty Mountain Trail (BTL204)",
  0xb: "Railway Switching Point (BTL205)",
  0xc: "Anafect Docks (BTL206)",
  0xd: "North of Anafect (BTL207)",
  0xe: "Waterfall Cave (BTL208)",
  0xf: "Rhineside North Plain (BTL209)",
  0x10: "Suspension Bridge (BTL210)",
  0x11: "Stump Skywalk (BTL211)",
  0x12: "Stump Treetop (BTL212)",
  0x13: "Barrand West Plains (BTL213)",
  0x14: "Barrand Beach (BTL214)",
  0x15: "Elbesem Road (BTL215)",
  0x16: "Elbesem Plains (BTL216)",
  0x17: "Elbesem Temple Court (BTL217)",
  0x18: "Elbesem Temple (BTL218)",
  0x19: "Seagate (BTL219)",
  0x1a: "Seagate and Executor (BTL220)",
  0x1b: "Saraband Prison (BTL221)",
  0x1c: "Governor's Mansion (BTL222)",
  0x1d: "Headland (BTL223)",
  0x1e: "Swampland Cave (BTL224)",
  0x1f: "Swampland Marsh (BTL225)",
  0x20: "Aspinia Volcano (BTL226)",
  0x21: "Storich Underground Ruins (BTL227)",
  0x22: "Aspia Castle Wall (BTL228)",
  0x23: "Aspia Castle Gate (BTL229)",
  0x24: "Ruins 1st Floor (BTL230)",
  0x25: "Ruins 2nd Floor (BTL231)",
  0x26: "Ruins 3rd Floor (BTL232)",
  0x27: "Ruins 4th Floor (BTL233)",
  0x28: "Ruins 5th Floor (BTL234)",
  0x29: "Ruins 6th Floor (BTL235)",
  0x2a: "Ruins 7th Floor (BTL236)",
  0x2b: "Ruins Bottom Floor (BTL237)",
  0x2c: "? (BTL238)",
  0x2d: "? (BTL239)",
  0x2e: "Opening Title (OP201)",
  0x2f: "Saraband Docks (SNIOKI)",
  0x30: "Saraband West District (SAR_W0)",
  0x31: "Saraband West District (SAR_W)",
  0x32: "Saraband West District (SAR_W2)",
  0x33: "Saraband West HQ (S_WJI)",
  0x34: "Saraband Central District (SAR_C)",
  0x35: "Saraband East District (SAR_E)",
  0x36: "Saraband Church (SARCHR)",
  0x37: "Saraband Inn (SARBAR)",
  0x38: "Saraband Imperial HQ (S_WRM1)",
  0x39: "Saraband Indoors (S_WRM2)",
  0x3a: "Saraband Republic HQ (SERM21)",
  0x3b: "Saraband Indoors 2 (SERM22)",
  0x3c: "Saraband Indoors 3 (SERM23)",
  0x3d: "Saraband Pier (S_HASHI)",
  0x3e: "Balsamo (2BALSA)",
  0x3f: "Balsamo Chief's house (2BAL_1)",
  0x40: "Balsamo Duncan's House (2BAL_2)",
  0x41: "Balsamo Lodge (2BAL_3)",
  0x42: "Balsamo Indoors (2BAL_4)",
  0x43: "Balsamo Indoors 2 (2BAL_5)",
  0x44: "Balsamo Neurotic Girl's House (2BAL_6)",
  0x45: "Balsamo Republic HQ (2BAL_7)",
  0x46: "Balsamo Imperial HQ (2BAL_8)",
  0x47: "Balsamo Shops (2BAL_9)",
  0x48: "Balsamo Church (2BALCHR)",
  0x49: "Balsamo HQ (2BALJIN)",
  0x4a: "Balsamo East Plains (BTL42)",
  0x4b: "Dusty South Plains (BTL43)",
  0x4c: "Lake Ruins (ZOKU01)",
  0x4d: "Dusty Village (DUSTY)",
  0x4e: "Dusty Shiraf's House (DUIN1)",
  0x4f: "Dusty Indoors (DUIN2)",
  0x50: "Dusty Church (DUSCH)",
  0x51: "Dusty HQ (DUSJI)",
  0x52: "Dusty Mountain Trail (B4_DAS)",
  0x53: "Switching Point (FED45)",
  0x54: "Switching Point Battle (BTL45)",
  0x55: "Anafect Village (FUNE_T)",
  0x56: "Anafect (FTIN_A)",
  0x57: "Anafect Docks (HASBTL)",
  0x58: "Barrand Plains (BTL47)",
  0x59: "Waterfall Cave (TAID00)",
  0x5a: "Rhineside Plain (BTL49)",
  0x5b: "Rhineside Village (LINE)",
  0x5c: "Rhineside HQ (LINE_H)",
  0x5d: "Rhineside Church (LINE_C)",
  0x5e: "Rhineside Indoors (L_RM01)",
  0x5f: "Rhineside Republic HQ (L_HON)",
  0x60: "Anafect West Plains (OP202)",
  0x61: "Anafect Village (ANA)",
  0x62: "Anafect Church (ANACH)",
  0x63: "Anafect HQ (ANAJI)",
  0x64: "Edmund's Army Camp (TURIHA)",
  0x65: "Suspension Bridge (FED50)",
  0x66: "Ambushing Edmund's Army (TURI_EV)",
  0x67: "Suspension Bridge Meeting (TURI02)",
  0x68: "Stump Village Ground (STAMP)",
  0x69: "Stump Village Entrance (STAMPN)",
  0x6a: "Stump Above Canopy (STAMP2)",
  0x6b: "Stump Treetop (STAMP3)",
  0x6c: "Leader's Quarters (STAIN)",
  0x6d: "Stump HQ (STAJI)",
  0x6e: "Stump Church (STACH)",
  0x6f: "Elven Forest Skywalk (BTL51A)",
  0x70: "Elven Forest Skywalk (BTL51B)",
  0x71: "Elven Forest Skywalk (BTL52)",
  0x72: "Barrand Marshland (BTL53)",
  0x73: "Barrand (B_LAND)",
  0x74: "Barrand House (B_RM01)",
  0x75: "Barrand Mansion Upstairs (B_YAKA)",
  0x76: "Barrand Prison (B_ROYA)",
  0x77: "Barrand Church (BLANCH)",
  0x78: "Barrand HQ (BLANJI)",
  0x79: "Barrand Lighthouse (B_SANB)",
  0x7a: "Barrand Beach (BTL54)",
  0x7b: "Elbesem Road (MITI00)",
  0x7c: "Elbesem Plains (BTL56)",
  0x7d: "Elbesem Temple (ELBTL)",
  0x7e: "Elbesem Temple Treasury (ZOKU04)",
  0x7f: "Elbesem Temple Top Floor (ELINA)",
  0x80: "Elbesem Temple Bottom Floor (ELINB)",
  0x81: "Elbesem Village (ELBESM)",
  0x82: "Elbesem Tavern (ELB_IN)",
  0x83: "Elbesem Elder's House (ELB_IN2)",
  0x84: "Elbesem Church (ELBECH)",
  0x85: "Elbesem HQ (ELBEJI)",
  0x86: "Seagate (S_GATE)",
  0x87: "Seagate HQ (S_GATE2)",
  0x88: "Seagate Battle (HNSN00)",
  0x89: "Seagate and Executor (HNSN02)",
  0x8a: "Seagate Deck (S_DECK)",
  0x8b: "Executor Deck (HNSN01)",
  0x8c: "Saraband West District (5SAR_W)",
  0x8d: "Saraband HQ (5S_WJI)",
  0x8e: "Saraband Central District (5SAR_C)",
  0x8f: "Saraband East District (5SAR_E)",
  0x90: "Saraband Church (5SARCH)",
  0x91: "Saraband Inn (5SARBR)",
  0x92: "Saraband Republic HQ (5S_EJI)",
  0x93: "West Saraband Indoors (5S_WRM1)",
  0x94: "West Saraband Indoors 2 (5S_WRM2)",
  0x95: "East Saraband Republic Building (5S_RM1)",
  0x96: "East Saraband Indoors (5S_RM2)",
  0x97: "East Saraband Indoors 2 (5S_RM3)",
  0x98: "Governor's Mansion L1 (SO_1FA)",
  0x99: "Governor's Mansion L2 (SO_2FA)",
  0x9a: "Governor's Mansion Passage (SO_B1A)",
  0x9b: "Governor's Mansion Tavern (SOGEST)",
  0x9c: "Saraband Pier (5S_HASI)",
  0x9d: "Saraband Prison (S_ROYA)",
  0x9e: "Governor's Mansion Gardens (S_SOTO)",
  0x9f: "Governor's Mansion (GURABI)",
  0xa0: "Headland (BTL63)",
  0xa1: "Saraband at Headland (FED63)",
  0xa2: "Headland (UMI)",
  0xa3: "Airo Village (AIRO)",
  0xa4: "Airo Indoors (AIROIN)",
  0xa5: "Airo Church (AIROCH)",
  0xa6: "Airo HQ (AIROJI)",
  0xa7: "Swampland Cave (SWND)",
  0xa8: "Swampland Town (SWA_CT)",
  0xa9: "Swampland Indoors (SWA_RM)",
  0xaa: "Swampland Church (SWA_CH)",
  0xab: "Swampland HQ (SWA_JI)",
  0xac: "Swampland Castle (SUWAN)",
  0xad: "Swampland Swamp (BTL65)",
  0xae: "Aspinia Volcano (MGMA02)",
  0xaf: "Swampland Swamp 2 (BTL65B)",
  0xb0: "Storich Business District (ST2)",
  0xb1: "Storich Station L1 (ST2IN)",
  0xb2: "Storich Station L2 (ST2IN2)",
  0xb3: "Storich Village (ST2OLD)",
  0xb4: "Storich (STIN)",
  0xb5: "Storich Church (STCH)",
  0xb6: "Storich HQ (STJI)",
  0xb7: "Aspinia Volcano (BTL67)",
  0xb8: "Tank Pursuit (FED68)",
  0xb9: "Aspia Castle Wall (AT_BTL)",
  0xba: "Outside Tank (TANK00)",
  0xbb: "Inside Tank (SENNAI)",
  0xbc: "Storich Ruins (CHIKA)",
  0xbd: "Aspia Gate (ATBTL2)",
  0xbe: "Aspia (AS_BRK)",
  0xbf: "Ending (ENDIN1)",
  0xc0: "Ending 2 (ENDIN2)",
  0xc1: "Ending 3 (ENDIN3)",
  0xc2: "Epilogue (HNEND)",
  0xc3: "Ruins (TMAP01)",
  0xc4: "Unused Sewer Level (TEST01)",
  0xc5: "Sc3 Ch3 Ruins (TM_OC)",
  0xc6: "Barrand Ruins (AMIDA)",
  0xc7: "Border Ruins (T_KABE)",
  0xc8: "Storich Ruins (T_MIZU)",
  0xc9: "Ancient Dungeon Stairs (LVD_A)",
  0xca: "Ancient Dungeon Bottom Floor (LVD_B)",
  0xcb: "Town (AGEO3)",
  0xcc: "Town 2 (HOR)",
  0xcd: "Town 3 (MGC_I)",
};

export const specialAttacks = {
  0x0: "-",
  0x1: "Critical Hit",
  0x2: "Counter",
  0x3: "Slow",
  0x4: "Sleep",
  0x5: "Confuse",
  0x6: "Illusion",
  0x7: "Dispel",
  0x8: "Paralyze",
  0x9: "Poison",
  0xa: "Poison",
  0xb: "Charm",
  0xc: "Cold",
  0xd: "Critical Hit",
  0xe: "Penetrate Armour",
  0xf: "Berserk",
  0x10: "Blood Sucker",
  0x11: "Regret Hit",
  // 0x12: "Not Set", // Unused
  // 0x13: "Not Set", // Unused
  0x14: "Shadow Edge",
  0x15: "Twin Slash",
  0x16: "Laser Edge",
  0x17: "Rainbow Edge",
  0x18: "Flash Kill",
  0x19: "Sonic Wave",
  0x1a: "Twin Wave",
  0x1b: "Mirage Dance",
  0x1c: "Thunder Shock",
  0x1d: "Heat Wave",
  0x1e: "Soul Eater",
  0x1f: "Dazzle Edge",
  0x20: "Triangle",
  0x21: "Pentagram",
  0x22: "Centurion",
  0x23: "Mist Feint",
  0x24: "Rune Magic",
  0x25: "Alchemy",
  0x26: "Das Ende",
  0x27: "After Burner",
  0x28: "Ice Breaker",
  0x29: "Dimension",
  0x2a: "Melt Armour",
  0x2b: "Light Cross",
  0x2c: "Light Sphere",
  0x2d: "Poison Blade",
  0x2e: "Force Edge",
  0x2f: "Lance Charge",
  0x30: "Super Charge",
  0x31: "Mega Charge",
  0x32: "Dragon Breath",
  0x33: "Death Charge",
  0x34: "Side Winder",
  0x35: "Energy Fall",
  0x36: "Thunder Fall",
  0x37: "Flash Gazer",
  0x38: "Meteor",
  0x39: "Tornado",
  0x3a: "Cross Break",
  0x3b: "Air Dance",
  0x3c: "Lord Rush",
  0x3d: "Lightning",
  0x3e: "Death Gate",
  0x3f: "Full Swing",
  0x40: "Power Wheel",
  0x41: "Mega Wheel",
  0x42: "Ragnarok",
  0x43: "Giga Wheel",
  0x44: "Death Wheel",
  0x45: "Power Throw",
  0x46: "Boomerang",
  0x47: "Vortex",
  0x48: "Fatal Strike",
  0x49: "Mist Storm",
  0x4a: "Power Crash",
  0x4b: "Stun Bomb",
  0x4c: "Earthquake",
  0x4d: "Thunder Storm",
  0x4e: "Pressure Bomb",
  0x4f: "Dragon Claw",
  0x50: "Sky Claw",
  0x51: "Sky Dragon",
  0x52: "Storm Fang",
  0x53: "Venom Fang",
  0x54: "Brutal Shock",
  0x55: "Bullet Heel",
  0x56: "Vortex Kick",
  0x57: "Sky Dance",
  0x58: "Heavenly Fire",
  0x59: "Jewel Palm",
  0x5a: "Fist O' Fury",
  0x5b: "Thunder Drop",
  0x5c: "Conquer King",
  0x5d: "Mirage Fist",
  0x5e: "Backstep Fist",
  0x5f: "Double Palm",
  0x60: "Stun Palm",
  0x61: "Panic Palm",
  0x62: "Ninth Gate",
  0x63: "Meta Dream",
  0x64: "Midas Strike",
  0x65: "Demon Breath",
  0x66: "Soul Shot",
  0x67: "Fairy Soul",
  0x68: "Soul Blast",
  0x69: "Fata Morgana",
  0x6a: "Fairy Lover",
  0x6b: "Stone Circle",
  0x6c: "Seal of Sin",
  0x6d: "Judgement",
  0x6e: "Apocalypse",
  0x6f: "Fool Prayer",
  0x70: "Holy Silence",
  0x71: "Apostle Descent",
  0x72: "Ice Arrow",
  0x73: "Hypno Arrow",
  0x74: "Drain Arrow",
  0x75: "Lunatic",
  0x76: "Dragon Snipe",
  0x77: "Spell Virus",
  0x78: "Poison Arrow",
  0x79: "Goddess Charm",
  0x7a: "Double Bolt",
  0x7b: "Sniper Bolt",
  0x7c: "Vulcan Bolt",
  0x7d: "Saint Flame",
  0x7e: "Hell Wind",
  0x7f: "Stun Needle",
  0x80: "Dazzle Shot",
  0x81: "Armour Shot",
  0x82: "Explode",
  0x83: "Desert Storm",
  0x84: "Planet Dance",
  0x85: "Schwarchshilt",
  0x86: "Butterfly Dance",
  0x87: "Izuna Drop",
  0x88: "Fine Mist",
  0x89: "Kamaitachi",
  0x8a: "Oni Hyakusoku",
  0x8b: "Umi Zato",
  0x8c: "Destruction",
  0x8d: "Road to Hades",
  0x8e: "Shadow Loom",
  0x8f: "Dark Raven",
  0x90: "Demon Circle",
  0x91: "Thunder Array",
  0x92: "Chaos Cauldron",
  0x93: "Evil Wind",
  0x94: "Twister",
  0x95: "Cross Slash",
  0x96: "Bloody Spin",
  0x97: "Hyper Boom",
  0x98: "Hell Dive",
  0x99: "Zero Count",
  0x9a: "Rocket Punch",
  0x9b: "Boost Punch",
  0x9c: "Nova Shot",
  0x9d: "Drill Smash",
  0x9e: "Hammer Throw",
  0x9f: "Gestalt",
  0xa0: "Penguin Kick",
  0xa1: "Penguin Butt",
  0xa2: "Volcano",
  0xa3: "Power Slash",
  0xa4: "Sky High",
  0xa5: "Eagle Dive",
  0xa6: "Power Feint",
  0xa7: "Double Feint",
  0xa8: "Danse Macabre",
  0xa9: "Wolf Fang",
  0xaa: "Wolf Rush",
  0xab: "Cork Screw",
  0xac: "Wild Blow",
  0xad: "Soul Spark",
  0xae: "Death Drive",
  0xaf: "Light Sphere",
  0xb0: "Star Bomb",
  0xb1: "Road Rush",
  0xb2: "Flame Tail",
  0xb3: "Melt Armour",
  0xb4: "Dominion Ray",
  0xb5: "Thunder Blow",
  0xb6: "Photon Rage",
  0xb7: "Dragon Breath",
  0xb8: "Air Fang",
  0xb9: "Wild Rush",
  0xba: "Soul Smash",
  0xbb: "Soul Gun",
  0xbc: "Maniac Beat",
  0xbd: "Mad Spin",
  0xbe: "Carousel",
  0xbf: "Slave Dance",
  0xc0: "Balloon Bomb",
  0xc1: "Penguin Flash",
  0xc2: "Penko Carnival",
  0xc3: "Plasma Shell",
  0xc4: "Flame Prison",
  0xc5: "Frost Blade",
  0xc6: "Fire Breath",
  0xc7: "Acid Breath",
  0xc8: "Panic",
  0xc9: "Wind Breath",
  0xca: "Demon Breath",
};

export const spells = {
  0x0: "-",
  0x1: "Blaze",
  0x2: "Freeze",
  0x3: "Spark",
  0x4: "Tornado",
  0x5: "Soul Steal",
  0x6: "Inferno",
  0x7: "Support",
  0x8: "Slow",
  0x9: "Pacify",
  0xa: "Resist",
  0xb: "Attack",
  0xc: "Dispel",
  0xd: "Confuse",
  0xe: "Sleep",
  0xf: "Charm",
  0x10: "Tsunami",
  0x11: "Heal",
  0x12: "Aura",
  0x13: "Chant",
  0x14: "Antidote",
  0x15: "Egress",
  0x26: "Phoenix",
  0x27: "Wendigo",
  0x28: "Tiamat",
  0x29: "Thanatos",
  0x34: "Thor",
  0x35: "Zephyrus",
  0x36: "Golem",
  0x37: "Hell Dragon",
  0x3b: "Fake Charm",
};

export const weaponTypes = {
  0xa: "Knife",
  0xb: "Sword",
  0xc: "Rapier",
  0xd: "Blade",
  0xe: "Katana",
  0xf: "Wing",
  0x14: "Lance",
  0x15: "Spear",
  0x16: "Halberd",
  0x1e: "Axe",
  0x1f: "Hatchet",
  0x20: "Mace",
  0x21: "Anchor",
  0x32: "Claw",
  0x33: "Glove",
  0x34: "Cestus",
  0x3c: "Rod",
  0x3d: "Wand",
  0x3e: "Ankh",
  0x46: "Arrow",
  0x47: "Quarrel",
  0x48: "Shell",
  0x4a: "Shuriken",
  0x50: "Beak",
  0x5a: "Whip",
};
