import type { GameJson } from "$lib/types";

import { moves, pokemonList, pokemons, pokemonsOrder } from "./utils/resource";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa_france_italy_spain: {},
      japan: {},
      germany: {},
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      type: "section",
      flex: true,
      hidden: true,
      items: [
        {
          id: "checksum",
          name: "Checksum",
          offset: 0x3523,
          type: "checksum",
          dataType: "uint8",
          control: {
            offsetStart: 0x2598,
            offsetEnd: 0x3523,
          },
        },
        {
          id: "checksumBoxes",
          name: "Checksum Boxes 1-6",
          offset: 0x5a4c,
          type: "checksum",
          dataType: "uint8",
          control: {
            offsetStart: 0x4000,
            offsetEnd: 0x5a4c,
          },
        },
        {
          id: "checksumBoxes",
          name: "Checksum Boxes 6-12",
          offset: 0x7a4c,
          type: "checksum",
          dataType: "uint8",
          control: {
            offsetStart: 0x6000,
            offsetEnd: 0x7a4c,
          },
        },
      ],
    },
    {
      type: "tabs",
      onTabChange: "onMainTabChange(%d)",
      items: [
        {
          name: "General",
          items: [
            {
              type: "tabs",
              vertical: true,
              items: [
                {
                  name: "General",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "name-trainer",
                          name: "Trainer Name",
                          offset: 0x2598,
                          length: 0x7,
                          type: "variable",
                          dataType: "string",
                          letterDataType: "uint8",
                          fallback: 0x7f,
                          endCode: 0x50,
                          resource: "letters",
                          test: true,
                        },
                        {
                          name: "No ID",
                          offset: 0x2605,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                        },
                        {
                          id: "name-japanShift",
                          name: "Rival Name",
                          offset: 0x25f6,
                          length: 0x7,
                          type: "variable",
                          dataType: "string",
                          letterDataType: "uint8",
                          fallback: 0x7f,
                          endCode: 0x50,
                          resource: "letters",
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "badges",
                          name: "Badges",
                          offset: 0x2602,
                          type: "variable",
                          dataType: "uint8",
                          disabled: true,
                        },
                        {
                          id: "ownedPokemon-japanShift",
                          name: "Owned Pokémon",
                          offset: 0x25a3,
                          type: "variable",
                          dataType: "uint8",
                          disabled: true,
                        },
                        {
                          name: "Playtime",
                          type: "group",
                          mode: "time",
                          items: [
                            {
                              id: "playtime",
                              offset: 0x2ced,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              id: "playtime",
                              offset: 0x2cef,
                              type: "variable",
                              dataType: "uint8",
                              leadingZeros: 1,
                              max: 59,
                            },
                            {
                              id: "playtime",
                              offset: 0x2cf0,
                              type: "variable",
                              dataType: "uint8",
                              leadingZeros: 1,
                              max: 59,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "japanShift",
                          name: "Pokémon Dollar",
                          offset: 0x25f3,
                          type: "variable",
                          dataType: "uint24",
                          bigEndian: true,
                          binaryCodedDecimal: true,
                        },
                        {
                          name: "Casino Coins",
                          offset: 0x2850,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                          binaryCodedDecimal: true,
                        },
                      ],
                    },
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "yellowOnly",
                          name: "Pikachu's Friendship",
                          offset: 0x271c,
                          type: "variable",
                          dataType: "uint8",
                        },
                        {
                          id: "isYellowVersion",
                          name: "Is Yellow Version",
                          offset: 0x271d,
                          type: "variable",
                          dataType: "uint8",
                          hidden: true,
                        },
                        {
                          id: "currentBox",
                          name: "Current Box",
                          offset: 0x284c,
                          type: "variable",
                          dataType: "uint8",
                          binary: { bitStart: 0, bitLength: 7 },
                          operations: [{ "+": 1 }],
                          hidden: true,
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Badges",
                  flex: true,
                  items: [
                    {
                      type: "bitflags",
                      flags: [
                        { offset: 0x2602, bit: 0, label: "Boulder Badge" },
                        { offset: 0x2602, bit: 1, label: "Cascade Badge" },
                        { offset: 0x2602, bit: 2, label: "Thunder Badge" },
                        { offset: 0x2602, bit: 3, label: "Rainbow Badge" },
                        { offset: 0x2602, bit: 4, label: "Soul Badge" },
                        { offset: 0x2602, bit: 5, label: "Marsh Badge" },
                        { offset: 0x2602, bit: 6, label: "Volcano Badge" },
                        { offset: 0x2602, bit: 7, label: "Earth Badge" },
                      ],
                    },
                  ],
                },
                {
                  name: "Pokédex",
                  flex: true,
                  items: [
                    {
                      id: "japanShift",
                      name: "Seen",
                      type: "bitflags",
                      flags: pokemonList.map((pokemon, index) => ({
                        offset: Math.floor(0x25b6 + index / 0x8),
                        bit: index % 8,
                        label: pokemon.name,
                      })),
                    },
                    {
                      id: "japanShift",
                      name: "Owned",
                      type: "bitflags",
                      flags: pokemonList.map((pokemon, index) => ({
                        offset: Math.floor(0x25a3 + index / 0x8),
                        bit: index % 8,
                        label: pokemon.name,
                      })),
                    },
                  ],
                },
                {
                  name: "Visited Places",
                  flex: true,
                  items: [
                    {
                      type: "bitflags",
                      flags: [
                        { offset: 0x29b7, bit: 0, label: "Pallet Town" },
                        { offset: 0x29b7, bit: 1, label: "Viridian City" },
                        { offset: 0x29b7, bit: 2, label: "Pewter City" },
                        { offset: 0x29b7, bit: 3, label: "Cerulean City" },
                        { offset: 0x29b7, bit: 4, label: "Lavender Town" },
                        { offset: 0x29b7, bit: 5, label: "Vermilion City" },
                        { offset: 0x29b7, bit: 6, label: "Celadon City" },
                        { offset: 0x29b8, bit: 2, label: "Saffron City" },
                        { offset: 0x29b7, bit: 7, label: "Fuchsia City" },
                        { offset: 0x29b8, bit: 0, label: "Cinnabar Island" },
                        { offset: 0x29b8, bit: 1, label: "Indigo Plateau" },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Pokémon",
          items: [
            {
              id: "boxes",
              length: 0x462,
              type: "container",
              instanceType: "tabs",
              instances: 12,
              enumeration: "Box %d",
              onTabChange: "onBoxChange(%d)",
              prependSubinstance: [
                {
                  name: "Party",
                  items: [
                    {
                      id: "pokemonSlots-party",
                      name: "Slots",
                      offset: 0x2f2c,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      id: "pokemonTab-party",
                      length: 0x2c,
                      type: "container",
                      instanceType: "tabs",
                      instances: 6,
                      resource: "pokemonNames",
                      vertical: true,
                      onTabChange: "onPokemonChange(%d, '%itemId%')",
                      items: [
                        {
                          type: "tabs",
                          items: [
                            {
                              name: "Status",
                              items: [
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      id: "name-pokemonParty-%index%",
                                      name: "Name",
                                      offset: 0x307e,
                                      length: 0xa,
                                      type: "variable",
                                      dataType: "string",
                                      letterDataType: "uint8",
                                      fallback: 0x7f,
                                      endCode: 0x50,
                                      resource: "letters",
                                      overrideShift: { parent: 1, shift: 0xb },
                                    },
                                    {
                                      id: "pokemon-party-0-%index%",
                                      name: "Pokémon",
                                      offset: 0x2f2d,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "pokemons",
                                      autocomplete: true,
                                      overrideShift: { parent: 1, shift: 0x1 },
                                    },
                                    {
                                      id: "pokemonPreview-party-0-%index%",
                                      name: "Pokémon",
                                      offset: 0x2f34,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "pokemons",
                                      hidden: true,
                                    },
                                    {
                                      id: "pokemonUnset-33",
                                      name: "Level",
                                      offset: 0x2f55,
                                      type: "variable",
                                      dataType: "uint8",
                                      min: 1,
                                      max: 100,
                                    },
                                    {
                                      name: "Level (Preview)",
                                      offset: 0x2f37,
                                      type: "variable",
                                      dataType: "uint8",
                                      hidden: true,
                                    },
                                    {
                                      id: "pokemonUnset-14",
                                      name: "Experience",
                                      offset: 0x2f42,
                                      type: "variable",
                                      dataType: "uint24",
                                      bigEndian: true,
                                      max: 1250000,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Type 1",
                                      offset: 0x2f39,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "types",
                                      disabled: true,
                                    },
                                    {
                                      id: "type2",
                                      name: "Type 2",
                                      offset: 0x2f3a,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "types",
                                      disabled: true,
                                    },
                                    {
                                      id: "pokemonUnset-7",
                                      name: "Catch Rate",
                                      offset: 0x2f3b,
                                      type: "variable",
                                      dataType: "uint8",
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "HP",
                                      type: "group",
                                      mode: "fraction",
                                      items: [
                                        {
                                          id: "pokemonUnset-1",
                                          offset: 0x2f35,
                                          type: "variable",
                                          dataType: "uint16",
                                          bigEndian: true,
                                          // max: 999,
                                        },
                                        {
                                          id: "pokemonUnset-34",
                                          offset: 0x2f56,
                                          type: "variable",
                                          dataType: "uint16",
                                          bigEndian: true,
                                          min: 1,
                                          // max: 999,
                                        },
                                      ],
                                    },
                                    {
                                      id: "pokemonUnset-17",
                                      name: "HP EV",
                                      offset: 0x2f45,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  noMargin: true,
                                  items: [
                                    {
                                      id: "pokemonUnset-36",
                                      name: "Attack",
                                      offset: 0x2f58,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      // max: 99,
                                      hint: "This stat will be reset after leveling up or if the Pokémon is put in a box.",
                                    },
                                    {
                                      id: "pokemonUnset-38",
                                      name: "Defense",
                                      offset: 0x2f5a,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      // max: 99,
                                      hint: "This stat will be reset after leveling up or if the Pokémon is put in a box.",
                                    },
                                    {
                                      id: "pokemonUnset-40",
                                      name: "Speed",
                                      offset: 0x2f5c,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      // max: 99,
                                      hint: "This stat will be reset after leveling up or if the Pokémon is put in a box.",
                                    },
                                    {
                                      id: "pokemonUnset-42",
                                      name: "Special",
                                      offset: 0x2f5e,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      // max: 99,
                                      hint: "This stat will be reset after leveling up or if the Pokémon is put in a box.",
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  noMargin: true,
                                  items: [
                                    {
                                      id: "pokemonUnset-19",
                                      name: "Attack EV",
                                      offset: 0x2f47,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      hint: "This stat can be increased with vitamins.",
                                    },
                                    {
                                      id: "pokemonUnset-21",
                                      name: "Defense EV",
                                      offset: 0x2f49,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      hint: "This stat can be increased with vitamins.",
                                    },
                                    {
                                      id: "pokemonUnset-23",
                                      name: "Speed EV",
                                      offset: 0x2f4b,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      hint: "This stat can be increased with vitamins.",
                                    },
                                    {
                                      id: "pokemonUnset-25",
                                      name: "Special EV",
                                      offset: 0x2f4d,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      hint: "This stat can be increased with vitamins.",
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      id: "pokemonUnset-27",
                                      name: "Attack IV",
                                      offset: 0x2f4f,
                                      type: "variable",
                                      dataType: "upper4",
                                      hint: "This stat is generated when the Pokémon is obtained.",
                                    },
                                    {
                                      id: "pokemonUnset-27",
                                      name: "Defense IV",
                                      offset: 0x2f4f,
                                      type: "variable",
                                      dataType: "lower4",
                                      hint: "This stat is generated when the Pokémon is obtained.",
                                    },
                                    {
                                      id: "pokemonUnset-28",
                                      name: "Speed IV",
                                      offset: 0x2f50,
                                      type: "variable",
                                      dataType: "upper4",
                                      hint: "This stat is generated when the Pokémon is obtained.",
                                    },
                                    {
                                      id: "pokemonUnset-28",
                                      name: "Special IV",
                                      offset: 0x2f50,
                                      type: "variable",
                                      dataType: "lower4",
                                      hint: "This stat is generated when the Pokémon is obtained.",
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      id: "pokemonUnset-4",
                                      name: "Asleep Turns",
                                      offset: 0x2f38,
                                      type: "variable",
                                      dataType: "uint8",
                                      binary: { bitStart: 0, bitLength: 3 },
                                    },
                                    {
                                      id: "pokemonUnset-4",
                                      name: "Condition",
                                      type: "bitflags",
                                      flags: [
                                        { offset: 0x2f38, bit: 3, label: "Poisoned" }, // prettier-ignore
                                        { offset: 0x2f38, bit: 4, label: "Burned" }, // prettier-ignore
                                        { offset: 0x2f38, bit: 5, label: "Frozen" }, // prettier-ignore
                                        { offset: 0x2f38, bit: 6, label: "Paralyzed" }, // prettier-ignore
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              name: "Moves",
                              items: [
                                {
                                  length: 0x1,
                                  type: "container",
                                  instanceType: "section",
                                  instances: 4,
                                  flex: true,
                                  items: [
                                    {
                                      id: "move-pokemonUnset-8-%index%",
                                      name: "Move %d",
                                      offset: 0x2f3c,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "moves",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "PP",
                                      type: "group",
                                      mode: "fraction",
                                      items: [
                                        {
                                          id: "movePP-pokemonUnset-29-%index%",
                                          offset: 0x2f51,
                                          type: "variable",
                                          dataType: "uint8",
                                          binary: { bitStart: 0, bitLength: 6 },
                                          max: 63,
                                        },
                                        {
                                          id: "moveMaxPP-pokemonUnset-29-%index%",
                                          offset: 0x2f51,
                                          type: "variable",
                                          dataType: "uint8",
                                          binary: { bitStart: 6, bitLength: 2 },
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              name: "Original Trainer",
                              flex: true,
                              items: [
                                {
                                  id: "name-originalTrainerParty-%index%",
                                  name: "Name",
                                  offset: 0x303c,
                                  length: 0x7,
                                  type: "variable",
                                  dataType: "string",
                                  letterDataType: "uint8",
                                  fallback: 0x7f,
                                  endCode: 0x50,
                                  resource: "letters",
                                  overrideShift: { parent: 1, shift: 0xb },
                                },
                                {
                                  id: "pokemonUnset-12",
                                  name: "No ID",
                                  offset: 0x2f40,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
              items: [
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      id: "checksumBox-%index%",
                      name: "Checksum",
                      offset: 0x5a4d,
                      type: "checksum",
                      dataType: "uint8",
                      control: {
                        offsetStart: 0x4000,
                        offsetEnd: 0x4462,
                      },
                      overrideShift: { parent: 1, shift: 0x1 },
                    },
                    {
                      id: "pokemonSlots-box-%index%",
                      name: "Slots",
                      offset: 0x4000,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
                {
                  id: "pokemonTab-box-%index%",
                  length: 0x21,
                  type: "container",
                  instanceType: "tabs",
                  instances: 20,
                  resource: "pokemonNames",
                  vertical: true,
                  onTabChange: "onPokemonChange(%d, '%itemId%')",
                  items: [
                    {
                      type: "tabs",
                      items: [
                        {
                          name: "Status",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  id: "name-pokemonBox-%parent%-%index%",
                                  name: "Name",
                                  offset: 0x4386,
                                  length: 0xa,
                                  type: "variable",
                                  dataType: "string",
                                  letterDataType: "uint8",
                                  fallback: 0x7f,
                                  endCode: 0x50,
                                  resource: "letters",
                                  overrideShift: { parent: 1, shift: 0xb },
                                },
                                {
                                  id: "pokemon-box-%parent%-%index%",
                                  name: "Pokémon",
                                  offset: 0x4001,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "pokemons",
                                  autocomplete: true,
                                  overrideShift: { parent: 1, shift: 0x1 },
                                },
                                {
                                  id: "pokemonPreview-box-%parent%-%index%",
                                  name: "Pokémon",
                                  offset: 0x4016,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "pokemons",
                                  hidden: true,
                                },
                                {
                                  name: "Level (Preview)",
                                  offset: 0x4019,
                                  type: "variable",
                                  dataType: "uint8",
                                  hidden: true,
                                },
                                {
                                  id: "pokemonUnset-14",
                                  name: "Experience",
                                  offset: 0x4024,
                                  type: "variable",
                                  dataType: "uint24",
                                  bigEndian: true,
                                  max: 1250000,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Type 1",
                                  offset: 0x401b,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "types",
                                  disabled: true,
                                },
                                {
                                  id: "type2",
                                  name: "Type 2",
                                  offset: 0x401c,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "types",
                                  disabled: true,
                                },
                                {
                                  id: "pokemonUnset-7",
                                  name: "Catch Rate",
                                  offset: 0x401d,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  id: "pokemonUnset-1",
                                  name: "HP",
                                  offset: 0x4017,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                  min: 1,
                                  // max: 999,
                                },
                                {
                                  id: "pokemonUnset-17",
                                  name: "HP EV",
                                  offset: 0x4027,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              noMargin: true,
                              items: [
                                {
                                  id: "pokemonUnset-19",
                                  name: "Attack EV",
                                  offset: 0x4029,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                  hint: "This stat can be increased with vitamins.",
                                },
                                {
                                  id: "pokemonUnset-21",
                                  name: "Defense EV",
                                  offset: 0x402b,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                  hint: "This stat can be increased with vitamins.",
                                },
                                {
                                  id: "pokemonUnset-23",
                                  name: "Speed EV",
                                  offset: 0x402d,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                  hint: "This stat can be increased with vitamins.",
                                },
                                {
                                  id: "pokemonUnset-25",
                                  name: "Special EV",
                                  offset: 0x402f,
                                  type: "variable",
                                  dataType: "uint16",
                                  bigEndian: true,
                                  hint: "This stat can be increased with vitamins.",
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  id: "pokemonUnset-27",
                                  name: "Attack IV",
                                  offset: 0x4031,
                                  type: "variable",
                                  dataType: "upper4",
                                  hint: "This stat is generated when the Pokémon is obtained.",
                                },
                                {
                                  id: "pokemonUnset-27",
                                  name: "Defense IV",
                                  offset: 0x4031,
                                  type: "variable",
                                  dataType: "lower4",
                                  hint: "This stat is generated when the Pokémon is obtained.",
                                },
                                {
                                  id: "pokemonUnset-28",
                                  name: "Speed IV",
                                  offset: 0x4032,
                                  type: "variable",
                                  dataType: "upper4",
                                  hint: "This stat is generated when the Pokémon is obtained.",
                                },
                                {
                                  id: "pokemonUnset-28",
                                  name: "Special IV",
                                  offset: 0x4032,
                                  type: "variable",
                                  dataType: "lower4",
                                  hint: "This stat is generated when the Pokémon is obtained.",
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  id: "pokemonUnset-4",
                                  name: "Asleep Turns",
                                  offset: 0x401a,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: { bitStart: 0, bitLength: 3 },
                                },
                                {
                                  id: "pokemonUnset-4",
                                  name: "Condition",
                                  type: "bitflags",
                                  flags: [
                                    { offset: 0x401a, bit: 3, label: "Poisoned" }, // prettier-ignore
                                    { offset: 0x401a, bit: 4, label: "Burned" }, // prettier-ignore
                                    { offset: 0x401a, bit: 5, label: "Frozen" }, // prettier-ignore
                                    { offset: 0x401a, bit: 6, label: "Paralyzed" }, // prettier-ignore
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Moves",
                          items: [
                            {
                              length: 0x1,
                              type: "container",
                              instanceType: "section",
                              instances: 4,
                              flex: true,
                              items: [
                                {
                                  id: "move-pokemonUnset-8-%index%",
                                  name: "Move %d",
                                  offset: 0x401e,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "moves",
                                  autocomplete: true,
                                },
                                {
                                  name: "PP",
                                  type: "group",
                                  mode: "fraction",
                                  items: [
                                    {
                                      id: "movePP-pokemonUnset-29-%index%",
                                      offset: 0x4033,
                                      type: "variable",
                                      dataType: "uint8",
                                      binary: { bitStart: 0, bitLength: 6 },
                                      max: 63,
                                    },
                                    {
                                      id: "moveMaxPP-pokemonUnset-29-%index%",
                                      offset: 0x4033,
                                      type: "variable",
                                      dataType: "uint8",
                                      binary: { bitStart: 6, bitLength: 2 },
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Original Trainer",
                          flex: true,
                          items: [
                            {
                              id: "name-originalTrainerBox-%parent%-%index%",
                              name: "Name",
                              offset: 0x42aa,
                              length: 0x7,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0x7f,
                              endCode: 0x50,
                              resource: "letters",
                              overrideShift: { parent: 1, shift: 0xb },
                            },
                            {
                              id: "pokemonUnset-12",
                              name: "No ID",
                              offset: 0x4022,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Daycare",
          items: [
            {
              id: "pokemonTab-daycare",
              length: 0x2c,
              type: "container",
              instanceType: "section",
              instances: 1,
              items: [
                {
                  type: "tabs",
                  items: [
                    {
                      name: "Status",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "pokemonDeposited",
                              name: "Pokémon Deposited",
                              offset: 0x2cf4,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              id: "name-pokemonDaycare-0",
                              name: "Name",
                              offset: 0x2cf5,
                              length: 0xa,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              fallback: 0x7f,
                              endCode: 0x50,
                              resource: "letters",
                            },
                            {
                              id: "pokemon-daycare-0-0",
                              name: "Pokémon",
                              offset: 0x2d0b,
                              type: "variable",
                              dataType: "uint8",
                              resource: "pokemons",
                              autocomplete: true,
                            },
                            {
                              name: "Level (Preview)",
                              offset: 0x2d0e,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              id: "pokemonUnset-14",
                              name: "Experience",
                              offset: 0x2d19,
                              type: "variable",
                              dataType: "uint24",
                              bigEndian: true,
                              max: 1250000,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Type 1",
                              offset: 0x2d10,
                              type: "variable",
                              dataType: "uint8",
                              resource: "types",
                              disabled: true,
                            },
                            {
                              id: "type2",
                              name: "Type 2",
                              offset: 0x2d11,
                              type: "variable",
                              dataType: "uint8",
                              resource: "types",
                              disabled: true,
                            },
                            {
                              id: "pokemonUnset-7",
                              name: "Catch Rate",
                              offset: 0x2d12,
                              type: "variable",
                              dataType: "uint8",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "pokemonUnset-1",
                              name: "HP",
                              offset: 0x2d0c,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              min: 1,
                              // max: 999,
                            },
                            {
                              id: "pokemonUnset-17",
                              name: "HP EV",
                              offset: 0x2d1c,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          noMargin: true,
                          items: [
                            {
                              id: "pokemonUnset-19",
                              name: "Attack EV",
                              offset: 0x2d1e,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              hint: "This stat can be increased with vitamins.",
                            },
                            {
                              id: "pokemonUnset-21",
                              name: "Defense EV",
                              offset: 0x2d20,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              hint: "This stat can be increased with vitamins.",
                            },
                            {
                              id: "pokemonUnset-23",
                              name: "Speed EV",
                              offset: 0x2d22,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              hint: "This stat can be increased with vitamins.",
                            },
                            {
                              id: "pokemonUnset-25",
                              name: "Special EV",
                              offset: 0x2d24,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              hint: "This stat can be increased with vitamins.",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "pokemonUnset-27",
                              name: "Attack IV",
                              offset: 0x2d26,
                              type: "variable",
                              dataType: "upper4",
                              hint: "This stat is generated when the Pokémon is obtained.",
                            },
                            {
                              id: "pokemonUnset-27",
                              name: "Defense IV",
                              offset: 0x2d26,
                              type: "variable",
                              dataType: "lower4",
                              hint: "This stat is generated when the Pokémon is obtained.",
                            },
                            {
                              id: "pokemonUnset-28",
                              name: "Speed IV",
                              offset: 0x2d27,
                              type: "variable",
                              dataType: "upper4",
                              hint: "This stat is generated when the Pokémon is obtained.",
                            },
                            {
                              id: "pokemonUnset-28",
                              name: "Special IV",
                              offset: 0x2d27,
                              type: "variable",
                              dataType: "lower4",
                              hint: "This stat is generated when the Pokémon is obtained.",
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "pokemonUnset-4",
                              name: "Asleep Turns",
                              offset: 0x2d0f,
                              type: "variable",
                              dataType: "uint8",
                              binary: { bitStart: 0, bitLength: 3 },
                            },
                            {
                              id: "pokemonUnset-4",
                              name: "Condition",
                              type: "bitflags",
                              flags: [
                                { offset: 0x2d0f, bit: 3, label: "Poisoned" }, // prettier-ignore
                                { offset: 0x2d0f, bit: 4, label: "Burned" }, // prettier-ignore
                                { offset: 0x2d0f, bit: 5, label: "Frozen" }, // prettier-ignore
                                { offset: 0x2d0f, bit: 6, label: "Paralyzed" }, // prettier-ignore
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Moves",
                      items: [
                        {
                          length: 0x1,
                          type: "container",
                          instanceType: "section",
                          instances: 4,
                          flex: true,
                          items: [
                            {
                              id: "move-pokemonUnset-8-%index%",
                              name: "Move %d",
                              offset: 0x2d13,
                              type: "variable",
                              dataType: "uint8",
                              resource: "moves",
                              autocomplete: true,
                            },
                            {
                              name: "PP",
                              type: "group",
                              mode: "fraction",
                              items: [
                                {
                                  id: "movePP-pokemonUnset-29-%index%",
                                  offset: 0x2d28,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: { bitStart: 0, bitLength: 6 },
                                  max: 63,
                                },
                                {
                                  id: "moveMaxPP-pokemonUnset-29-%index%",
                                  offset: 0x2d28,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: { bitStart: 6, bitLength: 2 },
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Original Trainer",
                      flex: true,
                      items: [
                        {
                          id: "name-originalTrainerDaycare-0",
                          name: "Name",
                          offset: 0x2d00,
                          length: 0x7,
                          type: "variable",
                          dataType: "string",
                          letterDataType: "uint8",
                          fallback: 0x7f,
                          endCode: 0x50,
                          resource: "letters",
                          overrideShift: { parent: 1, shift: 0xb },
                        },
                        {
                          id: "pokemonUnset-12",
                          name: "No ID",
                          offset: 0x2d17,
                          type: "variable",
                          dataType: "uint16",
                          bigEndian: true,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Inventory",
          items: [
            {
              type: "tabs",
              items: [
                {
                  name: "Bag",
                  items: [
                    {
                      id: "itemSlots-japanShift",
                      name: "Slots",
                      offset: 0x25c9,
                      type: "variable",
                      dataType: "uint8",
                      max: 20,
                    },
                    {
                      id: "bagItems",
                      length: 0x2,
                      type: "container",
                      instanceType: "section",
                      instances: 20,
                      vertical: true,
                      flex: true,
                      items: [
                        {
                          id: "item-%index%-0",
                          name: "Item %d",
                          offset: 0x25ca,
                          type: "variable",
                          dataType: "uint8",
                          resource: "items",
                          autocomplete: true,
                        },
                        {
                          id: "item-%index%-1",
                          name: "Quantity",
                          offset: 0x25cb,
                          type: "variable",
                          dataType: "uint8",
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "Storage PC",
                  items: [
                    {
                      id: "itemSlots-pc",
                      name: "Slots",
                      offset: 0x27e6,
                      type: "variable",
                      dataType: "uint8",
                      max: 50,
                    },
                    {
                      length: 0x2,
                      type: "container",
                      instanceType: "section",
                      instances: 50,
                      vertical: true,
                      flex: true,
                      items: [
                        {
                          id: "item-%index%-0",
                          name: "Item %d",
                          offset: 0x27e7,
                          type: "variable",
                          dataType: "uint8",
                          resource: "items",
                          autocomplete: true,
                        },
                        {
                          id: "item-%index%-1",
                          name: "Quantity",
                          offset: 0x27e8,
                          type: "variable",
                          dataType: "uint8",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Hall of Fame",
          items: [
            {
              id: "pokemonTab-hallOfFame",
              length: 0x60,
              type: "container",
              instanceType: "tabs",
              instances: 50,
              enumeration: "Entry %d",
              vertical: true,
              prependSubinstance: [
                {
                  name: "General",
                  items: [
                    {
                      id: "pokemonSlots-hallOfFame",
                      name: "Indigo League Victories",
                      offset: 0x284e,
                      type: "variable",
                      dataType: "uint8",
                    },
                  ],
                },
              ],
              items: [
                {
                  id: "hallOfFameDetails",
                  length: 0x10,
                  type: "container",
                  instanceType: "section",
                  instances: 6,
                  flex: true,
                  items: [
                    {
                      id: "name-nameHallOfFame-%index%-2",
                      name: "Name",
                      offset: 0x59a,
                      length: 0xa,
                      type: "variable",
                      dataType: "string",
                      letterDataType: "uint8",
                      fallback: 0x7f,
                      endCode: 0x50,
                      resource: "letters",
                    },
                    {
                      id: "pokemonHallOfFame-%index%-0",
                      name: "Pokémon",
                      offset: 0x598,
                      type: "variable",
                      dataType: "uint8",
                      resource: "pokemons",
                      autocomplete: true,
                    },
                    {
                      id: "levelHallOfFame-%index%-1",
                      name: "Level",
                      offset: 0x599,
                      type: "variable",
                      dataType: "uint8",
                      min: 1,
                      max: 100,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Events",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Pokédex",
                  offset: 0x29f7,
                  type: "variable",
                  dataType: "bit",
                  bit: 5,
                  resource: "booleanObtained",
                },
                {
                  id: "yellowExclude",
                  name: "Trainer's Pokémon",
                  offset: 0x29c3,
                  type: "variable",
                  dataType: "uint8",
                  resource: "starters",
                },
                {
                  id: "yellowExclude",
                  name: "Rival's Pokémon",
                  offset: 0x29c1,
                  type: "variable",
                  dataType: "uint8",
                  resource: "starters",
                },
              ],
            },
            {
              type: "bitflags",
              hidden: true,
              flags: [
                { offset: 0x29f7, bit: 0, label: "???", hidden: true },
                { offset: 0x29f7, bit: 1, label: "???", hidden: true },
                { offset: 0x29f7, bit: 2, label: "???", hidden: true },
                { offset: 0x29f7, bit: 3, label: "???", hidden: true },
                { offset: 0x29f7, bit: 4, label: "???", hidden: true },
                { offset: 0x29f7, bit: 5, label: "Pokédex obtained" },
                { offset: 0x29f7, bit: 6, label: "???", hidden: true },
                { offset: 0x29f7, bit: 7, label: "???", hidden: true },
              ],
            },
          ],
        },
        {
          name: "Options",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Text Speed",
                  offset: 0x2601,
                  type: "variable",
                  dataType: "uint8",
                  binary: { bitStart: 1, bitLength: 2 },
                  resource: "textSpeeds",
                },
              ],
            },
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Battle Animation",
                  offset: 0x2601,
                  type: "variable",
                  dataType: "bit",
                  bit: 7,
                  resource: "battleAnimations",
                },
                {
                  name: "Battle Style",
                  offset: 0x2601,
                  type: "variable",
                  dataType: "bit",
                  bit: 6,
                  resource: "battleStyles",
                },
              ],
            },
            {
              id: "yellowOnly",
              type: "section",
              flex: true,
              items: [
                {
                  name: "Sound",
                  offset: 0x2601,
                  type: "variable",
                  dataType: "uint8",
                  binary: { bitStart: 4, bitLength: 2 },
                  resource: "sounds",
                },
                {
                  name: "Print",
                  offset: 0x2744,
                  type: "variable",
                  dataType: "uint8",
                  resource: "prints",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    battleAnimations: {
      0x0: "On",
      0x1: "Off",
    },
    battleStyles: {
      0x0: "Shift",
      0x1: "Set",
    },
    booleanObtained: {
      0x0: "-",
      0x1: "Obtained",
    },
    items: {
      0x0: "-",
      0x1: "Master Ball",
      0x2: "Ultra Ball",
      0x3: "Great Ball",
      0x4: "Poké Ball",
      0x5: "Town Map",
      0x6: "Bicycle",
      // 0x7: "Surf", // Unused
      0x8: "Safari Ball",
      // 0x9: "Pokédex", // Unused
      0xa: "Moon Stone",
      0xb: "Antidote",
      0xc: "Burn Heal",
      0xd: "Ice Heal",
      0xe: "Awakening",
      0xf: "Parlyz Heal",
      0x10: "Full Restore",
      0x11: "Max Potion",
      0x12: "Hyper Potion",
      0x13: "Super Potion",
      0x14: "Potion",
      // 0x15: "Boulder Badge", // Unused
      // 0x16: "Cascade Badge", // Unused
      // 0x17: "Thunder Badge", // Unused
      // 0x18: "Rainbow Badge", // Unused
      // 0x19: "Soul Badge", // Unused
      // 0x1a: "Marsh Badge", // Unused
      // 0x1b: "Volcano Badge", // Unused
      // 0x1c: "Earth Badge", // Unused
      0x1d: "Escape Rope",
      0x1e: "Repel",
      0x1f: "Old Amber",
      0x20: "Fire Stone",
      0x21: "Thunder Stone",
      0x22: "Water Stone",
      0x23: "HP Up",
      0x24: "Protein",
      0x25: "Iron",
      0x26: "Carbos",
      0x27: "Calcium",
      0x28: "Rare Candy",
      0x29: "Dome Fossil",
      0x2a: "Helix Fossil",
      0x2b: "Secret Key",
      // 0x2c: "?????", // Unused
      0x2d: "Bike Voucher",
      0x2e: "X Accuracy",
      0x2f: "Leaf Stone",
      0x30: "Card Key",
      0x31: "Nugget",
      // 0x32: "PP Up", // Unused
      0x33: "Poké Doll",
      0x34: "Full Heal",
      0x35: "Revive",
      0x36: "Max Revive",
      0x37: "Guard Spec.",
      0x38: "Super Repel",
      0x39: "Max Repel",
      0x3a: "Dire Hit",
      // 0x3b: "Coin", // Unused
      0x3c: "Fresh Water",
      0x3d: "Soda Pop",
      0x3e: "Lemonade",
      0x3f: "S.S. Ticket",
      0x40: "Gold Teeth",
      0x41: "X Attack",
      0x42: "X Defend",
      0x43: "X Speed",
      0x44: "X Special",
      0x45: "Coin Case",
      0x46: "Oak's Parcel",
      0x47: "Item Finder",
      0x48: "Silph Scope",
      0x49: "Poké Flute",
      0x4a: "Lift Key",
      0x4b: "Exp. All",
      0x4c: "Old Rod",
      0x4d: "Good Rod",
      0x4e: "Super Rod",
      0x4f: "PP Up",
      0x50: "Ether",
      0x51: "Max Ether",
      0x52: "Elixer",
      0x53: "Max Elixer",
      0xc4: "HM01 (Cut)",
      0xc5: "HM02 (Fly)",
      0xc6: "HM03 (Surf)",
      0xc7: "HM04 (Strength)",
      0xc8: "HM05 (Flash)",
      0xc9: "TM01 (Mega Punch)",
      0xca: "TM02 (Razor Wind)",
      0xcb: "TM03 (Swords Dance)",
      0xcc: "TM04 (Whirlwind)",
      0xcd: "TM05 (Mega Kick)",
      0xce: "TM06 (Toxic)",
      0xcf: "TM07 (Horn Drill)",
      0xd0: "TM08 (Body Slam)",
      0xd1: "TM09 (Take Down)",
      0xd2: "TM10 (Double-Edge)",
      0xd3: "TM11 (Bubble Beam)",
      0xd4: "TM12 (Water Gun)",
      0xd5: "TM13 (Ice Beam)",
      0xd6: "TM14 (Blizzard)",
      0xd7: "TM15 (Hyper Beam)",
      0xd8: "TM16 (Pay Day)",
      0xd9: "TM17 (Submission)",
      0xda: "TM18 (Counter)",
      0xdb: "TM19 (Seismic Toss)",
      0xdc: "TM20 (Rage)",
      0xdd: "TM21 (Mega Drain)",
      0xde: "TM22 (Solar Beam)",
      0xdf: "TM23 (Dragon Rage)",
      0xe0: "TM24 (Thunderbolt)",
      0xe1: "TM25 (Thunder)",
      0xe2: "TM26 (Earthquake)",
      0xe3: "TM27 (Fissure)",
      0xe4: "TM28 (Dig)",
      0xe5: "TM29 (Psychic)",
      0xe6: "TM30 (Teleport)",
      0xe7: "TM31 (Mimic)",
      0xe8: "TM32 (Double Team)",
      0xe9: "TM33 (Reflect)",
      0xea: "TM34 (Bide)",
      0xeb: "TM35 (Metronome)",
      0xec: "TM36 (Self-Destruct)",
      0xed: "TM37 (Egg Bomb)",
      0xee: "TM38 (Fire Blast)",
      0xef: "TM39 (Swift)",
      0xf0: "TM40 (Skull Bash)",
      0xf1: "TM41 (Soft-Boiled)",
      0xf2: "TM42 (Dream Eater)",
      0xf3: "TM43 (Sky Attack)",
      0xf4: "TM44 (Rest)",
      0xf5: "TM45 (Thunder Wave)",
      0xf6: "TM46 (Psywave)",
      0xf7: "TM47 (Explosion)",
      0xf8: "TM48 (Rock Slide)",
      0xf9: "TM49 (Tri Attack)",
      0xfa: "TM50 (Substitute)",
      // 0xfb: "TM51 (Cut)", // Unused
      // 0xfc: "TM52 (Fly)", // Unused
      // 0xfd: "TM53 (Surf)", // Unused
      // 0xfe: "TM54 (Strength)", // Unused
    },
    letters: [
      // Europe / USA / France / Italy / Spain
      {
        0x5d: "⒯",
        0x7f: " ",
        0x80: "A",
        0x81: "B",
        0x82: "C",
        0x83: "D",
        0x84: "E",
        0x85: "F",
        0x86: "G",
        0x87: "H",
        0x88: "I",
        0x89: "J",
        0x8a: "K",
        0x8b: "L",
        0x8c: "M",
        0x8d: "N",
        0x8e: "O",
        0x8f: "P",
        0x90: "Q",
        0x91: "R",
        0x92: "S",
        0x93: "T",
        0x94: "U",
        0x95: "V",
        0x96: "W",
        0x97: "X",
        0x98: "Y",
        0x99: "Z",
        0x9a: "(",
        0x9b: ")",
        0x9c: ":",
        0x9d: ";",
        0x9e: "[",
        0x9f: "]",
        0xa0: "a",
        0xa1: "b",
        0xa2: "c",
        0xa3: "d",
        0xa4: "e",
        0xa5: "f",
        0xa6: "g",
        0xa7: "h",
        0xa8: "i",
        0xa9: "j",
        0xaa: "k",
        0xab: "l",
        0xac: "m",
        0xad: "n",
        0xae: "o",
        0xaf: "p",
        0xb0: "q",
        0xb1: "r",
        0xb2: "s",
        0xb3: "t",
        0xb4: "u",
        0xb5: "v",
        0xb6: "w",
        0xb7: "x",
        0xb8: "y",
        0xb9: "z",
        0xe1: "⒫",
        0xe2: "⒨",
        0xe3: "-",
        0xe6: "?",
        0xe7: "!",
        0xef: "♂",
        0xf1: "×",
        0xf2: ".",
        0xf3: "/",
        0xf4: ",",
        0xf5: "♀",
      },
      // Japan
      {
        0x5: "ガ",
        0x6: "ギ",
        0x7: "グ",
        0x8: "ゲ",
        0x9: "ゴ",
        0xa: "ザ",
        0xb: "ジ",
        0xc: "ズ",
        0xd: "ゼ",
        0xe: "ゾ",
        0xf: "ダ",
        0x10: "ヂ",
        0x11: "ヅ",
        0x12: "デ",
        0x13: "ド",
        0x19: "バ",
        0x1a: "ビ",
        0x1b: "ブ",
        0x1c: "ボ",
        0x26: "が",
        0x27: "ぎ",
        0x28: "ぐ",
        0x29: "げ",
        0x2a: "ご",
        0x2b: "ざ",
        0x2c: "じ",
        0x2d: "ず",
        0x2e: "ぜ",
        0x2f: "ぞ",
        0x30: "だ",
        0x31: "ぢ",
        0x32: "づ",
        0x33: "で",
        0x34: "ど",
        0x3a: "ば",
        0x3b: "び",
        0x3c: "ぶ",
        0x3d: "べ",
        0x3e: "ぼ",
        0x40: "パ",
        0x41: "ピ",
        0x42: "プ",
        0x43: "ポ",
        0x44: "ぱ",
        0x45: "ぴ",
        0x46: "ぷ",
        0x47: "ぺ",
        0x48: "ぽ",
        0x80: "ア",
        0x81: "イ",
        0x82: "ウ",
        0x83: "エ",
        0x84: "オ",
        0x85: "カ",
        0x86: "キ",
        0x87: "ク",
        0x88: "ケ",
        0x89: "コ",
        0x8a: "サ",
        0x8b: "シ",
        0x8c: "ス",
        0x8d: "セ",
        0x8e: "ソ",
        0x8f: "タ",
        0x90: "チ",
        0x91: "ツ",
        0x92: "テ",
        0x93: "ト",
        0x94: "ナ",
        0x95: "ニ",
        0x96: "ヌ",
        0x97: "ネ",
        0x98: "ノ",
        0x99: "ハ",
        0x9a: "ヒ",
        0x9b: "フ",
        0x9c: "ホ",
        0x9d: "マ",
        0x9e: "ミ",
        0x9f: "ム",
        0xa0: "メ",
        0xa1: "モ",
        0xa2: "ヤ",
        0xa3: "ユ",
        0xa4: "ヨ",
        0xa5: "ラ",
        0xa6: "ル",
        0xa7: "レ",
        0xa8: "ロ",
        0xa9: "ワ",
        0xab: "ン",
        0xac: "ッ",
        0xad: "ャ",
        0xae: "ュ",
        0xaf: "ョ",
        0xb1: "あ",
        0xb2: "い",
        0xb3: "う",
        0xb4: "え",
        0xb5: "お",
        0xb6: "か",
        0xb7: "き",
        0xb8: "く",
        0xb9: "け",
        0xba: "こ",
        0xbb: "さ",
        0xbc: "し",
        0xbd: "す",
        0xbe: "せ",
        0xbf: "そ",
        0xc0: "た",
        0xc1: "ち",
        0xc2: "つ",
        0xc3: "て",
        0xc4: "と",
        0xc5: "な",
        0xc6: "に",
        0xc7: "ぬ",
        0xc8: "ね",
        0xc9: "の",
        0xca: "は",
        0xcb: "ひ",
        0xcc: "ふ",
        0xcd: "へ",
        0xce: "ほ",
        0xcf: "ま",
        0xd0: "み",
        0xd1: "む",
        0xd2: "め",
        0xd3: "も",
        0xd4: "や",
        0xd5: "ゆ",
        0xd6: "よ",
        0xd7: "ら",
        0xd8: "リ",
        0xd9: "る",
        0xda: "れ",
        0xdb: "ろ",
        0xdc: "わ",
        0xde: "ん",
        0xdf: "っ",
        0xe0: "ゃ",
        0xe1: "ゅ",
        0xe2: "ょ",
        0xe3: "ー",
      },
      // Germany
      {
        0x5d: "⒯",
        0x7f: " ",
        0x80: "A",
        0x81: "B",
        0x82: "C",
        0x83: "D",
        0x84: "E",
        0x85: "F",
        0x86: "G",
        0x87: "H",
        0x88: "I",
        0x89: "J",
        0x8a: "K",
        0x8b: "L",
        0x8c: "M",
        0x8d: "N",
        0x8e: "O",
        0x8f: "P",
        0x90: "Q",
        0x91: "R",
        0x92: "S",
        0x93: "T",
        0x94: "U",
        0x95: "V",
        0x96: "W",
        0x97: "X",
        0x98: "Y",
        0x99: "Z",
        0x9a: "(",
        0x9b: ")",
        0x9c: ":",
        0x9d: ";",
        0x9e: "[",
        0x9f: "]",
        0xa0: "a",
        0xa1: "b",
        0xa2: "c",
        0xa3: "d",
        0xa4: "e",
        0xa5: "f",
        0xa6: "g",
        0xa7: "h",
        0xa8: "i",
        0xa9: "j",
        0xaa: "k",
        0xab: "l",
        0xac: "m",
        0xad: "n",
        0xae: "o",
        0xaf: "p",
        0xb0: "q",
        0xb1: "r",
        0xb2: "s",
        0xb3: "t",
        0xb4: "u",
        0xb5: "v",
        0xb6: "w",
        0xb7: "x",
        0xb8: "y",
        0xb9: "z",
        0xc0: "Ä",
        0xc1: "Ö",
        0xc2: "Ü",
        0xc3: "ä",
        0xc4: "ö",
        0xc5: "ü",
        0xe1: "⒫",
        0xe2: "⒨",
        0xe3: "-",
        0xe6: "?",
        0xe7: "!",
        0xef: "♂",
        0xf1: "×",
        0xf2: ".",
        0xf3: "/",
        0xf4: ",",
        0xf5: "♀",
      },
    ],
    move0PPs: {
      0x0: "0",
      0x1: "0",
      0x2: "0",
      0x3: "0",
    },
    move5PPs: {
      0x0: "5",
      0x1: "6",
      0x2: "7",
      0x3: "8",
    },
    move10PPs: {
      0x0: "10",
      0x1: "12",
      0x2: "14",
      0x3: "16",
    },
    move15PPs: {
      0x0: "15",
      0x1: "18",
      0x2: "21",
      0x3: "24",
    },
    move20PPs: {
      0x0: "20",
      0x1: "24",
      0x2: "28",
      0x3: "32",
    },
    move25PPs: {
      0x0: "25",
      0x1: "30",
      0x2: "35",
      0x3: "40",
    },
    move30PPs: {
      0x0: "30",
      0x1: "36",
      0x2: "42",
      0x3: "48",
    },
    move35PPs: {
      0x0: "35",
      0x1: "42",
      0x2: "49",
      0x3: "56",
    },
    move40PPs: {
      0x0: "40",
      0x1: "47",
      0x2: "54",
      0x3: "61",
    },
    moves: {
      0x0: "-",
      ...moves,
    },
    pokemonNames: "getPokemonNames('party')",
    pokemons: {
      0xff: "-",
      ...pokemons,
    },
    prints: {
      0x0: "Lightest",
      0x20: "Lighter",
      0x40: "Normal",
      0x60: "Darker",
      0x7f: "Darkest",
    },
    sounds: {
      0x0: "Mono",
      0x1: "Earphone 1",
      0x2: "Earphone 2",
      0x3: "Earphone 3",
    },
    starters: {
      0x0: "-",
      0x99: "001 Bulbasaur",
      0xb0: "004 Charmander",
      0xb1: "007 Squirtle",
    },
    textSpeeds: {
      0x0: "Fast",
      0x1: "Medium",
      0x2: "Slow",
    },
    types: {
      0x0: "Normal",
      0x1: "Fighting",
      0x2: "Flying",
      0x3: "Poison",
      0x4: "Ground",
      0x5: "Rock",
      0x7: "Bug",
      0x8: "Ghost",
      0x14: "Fire",
      0x15: "Water",
      0x16: "Grass",
      0x17: "Electric",
      0x18: "Psychic",
      0x19: "Ice",
      0x1a: "Dragon",
      0xff: "-",
    },
  },
  resourcesGroups: {
    items: [
      {
        name: "Poké Balls",
        options: [0x1, 0x2, 0x3, 0x4, 0x8],
      },
      {
        name: "Medicine",
        options: [
          0x10, 0x11, 0x12, 0x13, 0x14, 0xb, 0xc, 0xd, 0xe, 0xf, 0x34, 0x35,
          0x36, 0x3c, 0x3d, 0x3e, 0x50, 0x51, 0x52, 0x53,
        ],
      },
      {
        name: "Battle Items",
        options: [0x2e, 0x37, 0x3a, 0x41, 0x42, 0x43, 0x44],
      },
      {
        name: "Vitamins",
        options: [0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x4f],
      },
      {
        name: "Evolution Stones",
        options: [0xa, 0x20, 0x21, 0x22, 0x2f],
      },
      {
        name: "Key Items",
        options: [
          0x5, 0x6, 0x1f, 0x29, 0x2a, 0x2b, 0x2d, 0x30, 0x3f, 0x40, 0x45, 0x46,
          0x47, 0x48, 0x49, 0x4a, 0x4c, 0x4d, 0x4e,
        ],
      },
      {
        name: "Miscellaneous",
        options: [0x1d, 0x1e, 0x31, 0x33, 0x38, 0x39, 0x4b],
      },
      {
        name: "HMs",
        options: [0xc4, 0xc5, 0xc6, 0xc7, 0xc8],
      },
      {
        name: "TMs",
        options: [
          0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3,
          0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde,
          0xdf, 0xe0, 0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9,
          0xea, 0xeb, 0xec, 0xed, 0xee, 0xef, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4,
          0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa,
        ],
      },
    ],
  },
  resourcesOrder: {
    items: [
      0x4, 0x3, 0x2, 0x1, 0x8, 0x14, 0x13, 0x12, 0x11, 0x10, 0x50, 0x51, 0x52,
      0x53, 0x35, 0x36, 0xb, 0xc, 0xd, 0xe, 0xf, 0x34, 0x3c, 0x3d, 0x3e, 0x41,
      0x42, 0x43, 0x44, 0x2e, 0x3a, 0x37, 0x23, 0x4f, 0x24, 0x25, 0x26, 0x27,
      0x28, 0xa, 0x20, 0x21, 0x22, 0x2f, 0x5, 0x6, 0x1f, 0x29, 0x2a, 0x2b, 0x2d,
      0x30, 0x3f, 0x40, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4c, 0x4d, 0x4e,
      0x1d, 0x1e, 0x38, 0x39, 0x31, 0x33, 0x4b, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8,
      0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4,
      0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf, 0xe0,
      0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb, 0xec,
      0xed, 0xee, 0xef, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8,
      0xf9, 0xfa,
    ],
    pokemons: [0xff, ...pokemonsOrder],
  },
};

export default template;
