import type { GameJson } from "$lib/types";

const template: GameJson = {
  validator: {
    regions: {
      europe: {
        0x0: [
          0x42, 0x45, 0x53, 0x43, 0x45, 0x53, 0x2d, 0x35, 0x30, 0x32, 0x34,
          0x31,
        ], // "BESCES-50241"
      },
      usa: {
        0x0: [
          0x42, 0x41, 0x53, 0x4c, 0x55, 0x53, 0x2d, 0x32, 0x30, 0x30, 0x36,
          0x39,
        ], // "BASLUS-20069"
      },
      japan: {
        0x0: [
          0x42, 0x49, 0x53, 0x4c, 0x50, 0x53, 0x2d, 0x32, 0x35, 0x30, 0x32,
          0x33,
        ], // "BISLPS-25023"
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      length: 0x400,
      type: "container",
      instanceType: "tabs",
      instances: 16,
      enumeration: "Slot %d",
      disableSubinstanceIf: {
        offset: 0x20,
        type: "variable",
        dataType: "uint8",
        operator: "=",
        value: 0x0,
      },
      items: [
        {
          type: "section",
          flex: true,
          hidden: true,
          items: [
            {
              name: "Checksum Salt",
              offset: 0x28,
              type: "variable",
              dataType: "uint32",
              hidden: true,
            },
            {
              name: "Checksum",
              offset: 0x2c,
              type: "checksum",
              dataType: "uint32",
              control: {
                offsetStart: 0x0,
                offsetEnd: 0x1e0,
              },
            },
          ],
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Playtime",
                      type: "group",
                      mode: "time",
                      items: [
                        {
                          id: "time",
                          offset: 0x70,
                          type: "variable",
                          dataType: "uint32",
                          operations: [
                            { "/": 50 },
                            {
                              convert: { from: "seconds", to: "hours" },
                            },
                          ],
                          max: 999,
                        },
                        {
                          id: "time",
                          offset: 0x70,
                          type: "variable",
                          dataType: "uint32",
                          operations: [
                            { "/": 50 },
                            {
                              convert: {
                                from: "seconds",
                                to: "minutes",
                              },
                            },
                          ],
                          leadingZeros: 1,
                          max: 59,
                          test: true,
                        },
                        {
                          id: "time",
                          offset: 0x70,
                          type: "variable",
                          dataType: "uint32",
                          operations: [
                            { "/": 50 },
                            {
                              convert: {
                                from: "seconds",
                                to: "seconds",
                              },
                            },
                          ],
                          leadingZeros: 1,
                          max: 59,
                          test: true,
                        },
                      ],
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Unlocked Stages",
                      type: "bitflags",
                      flags: [
                        { offset: 0x100, bit: 4, label: 'Bar - "Fate"' },
                        { offset: 0x100, bit: 5, label: "Central Square" },
                        { offset: 0x100, bit: 6, label: "Central Station" },
                        { offset: 0x100, bit: 7, label: "MSD Cargo Train" },
                        { offset: 0x101, bit: 0, label: "Air-Carrier" },
                        { offset: 0x101, bit: 1, label: "Mikado Bldg. - Hanging Garden" },
                        { offset: 0x101, bit: 2, label: "Crystal Dome" },
                        { offset: 0x101, bit: 3, label: "Mikado Bldg. - Robot Factory" },
                        { offset: 0x101, bit: 4, label: "Rocket Tower - Deck" },
                        { offset: 0x101, bit: 5, label: "Air-Carrier (over the Galeos)" },
                        { offset: 0x101, bit: 6, label: "Galeos - Control Room" },
                      ],
                    },
                    {
                      name: "Unlocked Characters",
                      type: "bitflags",
                      flags: [
                        { offset: 0x101, bit: 7, label: "Echidna" },
                        { offset: 0x102, bit: 0, label: "Dauragon (One-handed)" },
                        { offset: 0x102, bit: 1, label: "Dauragon (Two-handed)" },
                        { offset: 0x102, bit: 2, label: "Dauragon (Shirtless)" },
                        { offset: 0x102, bit: 3, label: "Dauragon (Tattoo)" },
                        { offset: 0x102, bit: 4, label: "Mugetsu" },
                        { offset: 0x102, bit: 5, label: "Mugetsu (Unmasked)" },
                        { offset: 0x102, bit: 6, label: "PD-4" },
                        { offset: 0x102, bit: 7, label: "Dominique" },
                        { offset: 0x103, bit: 0, label: "Kaldea" },
                        { offset: 0x103, bit: 1, label: "Wong" },
                        { offset: 0x103, bit: 2, label: "Leann" },
                      ],
                    },
                    {
                      name: "Unlocked Costumes",
                      type: "bitflags",
                      flags: [
                        { offset: 0x103, bit: 3, label: "Black-Hooded Sion" },
                        { offset: 0x103, bit: 4, label: "MSF Kou" },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Story Mode",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Clear Count",
                              offset: 0x84,
                              type: "variable",
                              dataType: "float32",
                              max: 99,
                            },
                            {
                              id: "location",
                              name: "Location",
                              offset: 0x80,
                              type: "variable",
                              dataType: "float32",
                              resource: "locations",
                              size: "lg",
                              autocomplete: true,
                            },
                            {
                              name: "Location (Save Preview)",
                              offset: 0xbc,
                              type: "variable",
                              dataType: "float32",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Last Charater Used",
                              offset: 0xb8,
                              type: "variable",
                              dataType: "float32",
                              resource: "mainCharacters",
                            },
                            {
                              id: "specialEventCharacter",
                              name: "Special Event Character",
                              offset: 0xb4,
                              type: "variable",
                              dataType: "float32",
                              resource: "mainCharacters",
                            },
                            {
                              id: "keldeo",
                              name: "Keldeo",
                              offset: 0x108,
                              type: "variable",
                              dataType: "bit",
                              bit: 0,
                              resource: "keldeo",
                            },
                            {
                              name: "Leann beaten",
                              offset: 0x10a,
                              type: "variable",
                              dataType: "bit",
                              bit: 7,
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Sion Barzahd",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Rank (Save Preview)",
                              offset: 0x121,
                              type: "variable",
                              dataType: "upper4",
                              resource: "ranks",
                              hidden: true,
                            },
                            {
                              name: "Bouncer Points",
                              offset: 0x148,
                              type: "variable",
                              dataType: "uint32",
                              max: 99999,
                            },
                            {
                              name: "Bouncer Points Spent",
                              offset: 0x14c,
                              type: "variable",
                              dataType: "uint32",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "characterStats-0-0",
                              name: "Life Up",
                              offset: 0x120,
                              type: "variable",
                              dataType: "lower4",
                              max: 7,
                            },
                            {
                              id: "characterStats-0-0",
                              name: "Power Up",
                              offset: 0x120,
                              type: "variable",
                              dataType: "upper4",
                              max: 7,
                            },
                            {
                              id: "characterStats-1-0",
                              name: "Defence Up",
                              offset: 0x121,
                              type: "variable",
                              dataType: "lower4",
                              max: 7,
                            },
                          ],
                        },
                        {
                          id: "characterSkills-0",
                          name: "Skills",
                          type: "bitflags",
                          flags: [
                            { offset: 0x126, bit: 0, label: "Buster Throw" },
                            { offset: 0x126, bit: 1, label: "Torpedo Kick" },
                            { offset: 0x126, bit: 2, label: "Ground Sweep" },
                            { offset: 0x126, bit: 3, label: "Floating Mine" },
                            { offset: 0x126, bit: 4, label: "Tornado Uppercut" },
                            { offset: 0x126, bit: 5, label: "Double Knuckle" },
                            { offset: 0x126, bit: 6, label: "Hurricane Blitz" },
                            { offset: 0x126, bit: 7, label: "???", hidden: true },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Volt Krueger",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Rank (Save Preview)",
                              offset: 0x123,
                              type: "variable",
                              dataType: "upper4",
                              resource: "ranks",
                              hidden: true,
                            },
                            {
                              name: "Bouncer Points",
                              offset: 0x150,
                              type: "variable",
                              dataType: "uint32",
                              max: 99999,
                            },
                            {
                              name: "Bouncer Points Spent",
                              offset: 0x154,
                              type: "variable",
                              dataType: "uint32",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "characterStats-0-1",
                              name: "Life Up",
                              offset: 0x122,
                              type: "variable",
                              dataType: "lower4",
                              max: 7,
                            },
                            {
                              id: "characterStats-0-1",
                              name: "Power Up",
                              offset: 0x122,
                              type: "variable",
                              dataType: "upper4",
                              max: 7,
                            },
                            {
                              id: "characterStats-1-1",
                              name: "Defence Up",
                              offset: 0x123,
                              type: "variable",
                              dataType: "lower4",
                              max: 7,
                            },
                          ],
                        },
                        {
                          id: "characterSkills-1",
                          name: "Skills",
                          type: "bitflags",
                          flags: [
                            { offset: 0x128, bit: 0, label: "Soulder Uppercut" },
                            { offset: 0x128, bit: 1, label: "Hammer Typhoon" },
                            { offset: 0x128, bit: 2, label: "Lift Up Slam" },
                            { offset: 0x128, bit: 3, label: "Power Bridge" },
                            { offset: 0x128, bit: 4, label: "Cannonball Strike" },
                            { offset: 0x128, bit: 5, label: "Earthshaker" },
                            { offset: 0x128, bit: 6, label: "Giant Swing" },
                            { offset: 0x128, bit: 7, label: "???", hidden: true },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Kou Leifoh",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Rank (Save Preview)",
                              offset: 0x125,
                              type: "variable",
                              dataType: "upper4",
                              resource: "ranks",
                              hidden: true,
                            },
                            {
                              name: "Bouncer Points",
                              offset: 0x158,
                              type: "variable",
                              dataType: "uint32",
                              max: 99999,
                            },
                            {
                              name: "Bouncer Points Spent",
                              offset: 0x15c,
                              type: "variable",
                              dataType: "uint32",
                              hidden: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "characterStats-0-2",
                              name: "Life Up",
                              offset: 0x124,
                              type: "variable",
                              dataType: "lower4",
                              max: 7,
                            },
                            {
                              id: "characterStats-0-2",
                              name: "Power Up",
                              offset: 0x124,
                              type: "variable",
                              dataType: "upper4",
                              max: 7,
                            },
                            {
                              id: "characterStats-1-2",
                              name: "Defence Up",
                              offset: 0x125,
                              type: "variable",
                              dataType: "lower4",
                              max: 7,
                            },
                          ],
                        },
                        {
                          id: "characterSkills-2",
                          name: "Skills",
                          type: "bitflags",
                          flags: [
                            { offset: 0x12a, bit: 0, label: "Heel Smash" },
                            { offset: 0x12a, bit: 1, label: "Circular Uppercut" },
                            { offset: 0x12a, bit: 2, label: "Double Spin Kick" },
                            { offset: 0x12a, bit: 3, label: "Mountain Storm" },
                            { offset: 0x12a, bit: 4, label: "Lightning Smash" },
                            { offset: 0x12a, bit: 5, label: "Tiger Spin Kick" },
                            { offset: 0x12a, bit: 6, label: "Tiger Frenzy" },
                            { offset: 0x12a, bit: 7, label: "Raging Tiger" },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Survival Mode",
              flex: true,
              items: [
                {
                  length: 0xc,
                  type: "container",
                  instanceType: "tabs",
                  instances: 10,
                  enumeration: "%o Place",
                  vertical: true,
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          id: "survival-0",
                          name: "Character",
                          offset: 0x160,
                          type: "variable",
                          dataType: "uint8",
                          resource: "characters",
                          autocomplete: true,
                        },
                        {
                          id: "survival-1",
                          name: "Rank",
                          offset: 0x161,
                          type: "variable",
                          dataType: "uint8",
                          resource: "ranks",
                        },
                        {
                          id: "survival-2",
                          name: "KOs",
                          offset: 0x162,
                          type: "variable",
                          dataType: "uint8",
                          max: 50,
                        },
                        {
                          name: "???",
                          offset: 0x166,
                          type: "variable",
                          dataType: "int16",
                          hidden: true,
                        },
                        {
                          name: "Time",
                          type: "group",
                          mode: "chrono",
                          items: [
                            {
                              id: "time",
                              offset: 0x168,
                              type: "variable",
                              dataType: "uint32",
                              operations: [
                                { "/": 50 },
                                {
                                  convert: { from: "seconds", to: "minutes" },
                                },
                              ],
                              max: 59,
                            },
                            {
                              id: "time",
                              offset: 0x168,
                              type: "variable",
                              dataType: "uint32",
                              operations: [
                                { "/": 50 },
                                {
                                  convert: {
                                    from: "seconds",
                                    to: "seconds",
                                  },
                                },
                              ],
                              leadingZeros: 1,
                              max: 59,
                            },
                            {
                              id: "time",
                              offset: 0x168,
                              type: "variable",
                              dataType: "uint32",
                              operations: [
                                { "/": 50 },
                                {
                                  convert: {
                                    from: "seconds",
                                    to: "milliseconds",
                                  },
                                },
                                { round: 0 },
                              ],
                              leadingZeros: 2,
                              max: 999,
                              step: 100,
                            },
                          ],
                        },
                        {
                          id: "survivalPlayer",
                          name: "Player",
                          offset: 0x163,
                          length: 3,
                          type: "variable",
                          dataType: "string",
                          letterDataType: "uint8",
                          fallback: 0x28,
                          resource: "letters",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Options",
              flex: true,
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Controller Settings",
                      items: [
                        {
                          length: 0x10,
                          type: "container",
                          instanceType: "tabs",
                          instances: 4,
                          enumeration: "Controller %d",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Vibration",
                                  offset: 0x3e,
                                  type: "variable",
                                  dataType: "bit",
                                  bit: 0,
                                  resource: "optionBoolean",
                                },
                                {
                                  name: "Sensivity",
                                  offset: 0x3e,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: {
                                    bitStart: 1,
                                    bitLength: 2,
                                  },
                                  resource: "sensitivities",
                                },
                              ],
                            },
                            {
                              name: "Button Configuration",
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Jump Attack",
                                  offset: 0x30,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "buttons",
                                },
                                {
                                  name: "High Attack",
                                  offset: 0x32,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "buttons",
                                },
                                {
                                  name: "Middle Attack",
                                  offset: 0x34,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "buttons",
                                },
                                {
                                  name: "Low Attack",
                                  offset: 0x36,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "buttons",
                                },
                                {
                                  name: "Guard",
                                  offset: 0x38,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "buttons",
                                },
                                {
                                  name: "Extra Skill",
                                  offset: 0x3c,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "buttons",
                                },
                                {
                                  name: "Gesture",
                                  offset: 0x3a,
                                  type: "variable",
                                  dataType: "uint16",
                                  resource: "buttons",
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Sound Settings",
                      flex: true,
                      items: [
                        {
                          name: "Sound Mode",
                          offset: 0x77,
                          type: "variable",
                          dataType: "bit",
                          bit: 0,
                          resource: "soundModes",
                        },
                        {
                          name: "5.1 Channel Dolby Digital",
                          offset: 0x77,
                          type: "variable",
                          dataType: "bit",
                          bit: 1,
                          resource: "optionBoolean",
                        },
                      ],
                    },
                    {
                      name: "Language Selection",
                      flex: true,
                      items: [
                        {
                          id: "subtitles",
                          name: "Subtitles",
                          offset: 0x74,
                          type: "variable",
                          dataType: "uint8",
                          binary: {
                            bitStart: 0,
                            bitLength: 3,
                          },
                          resource: "subtitles",
                        },
                        {
                          id: "dialogs",
                          name: "Dialogue",
                          offset: 0x74,
                          type: "variable",
                          dataType: "bit",
                          bit: 3,
                          resource: "dialogs",
                        },
                        {
                          id: "menus",
                          name: "Menus",
                          offset: 0x74,
                          type: "variable",
                          dataType: "uint8",
                          binary: {
                            bitStart: 4,
                            bitLength: 4,
                          },
                          resource: "menus",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    buttons: {
      0x1: "L2",
      0x2: "R2",
      0x4: "L1",
      0x8: "R1",
      0x10: "Triangle",
      0x20: "Circle",
      0x40: "Cross",
      0x80: "Square",
    },
    characters: {
      0x0: "Sion",
      0x1: "Volt",
      0x2: "Kou",
      0x3: "Echidna",
      0x4: "Dauragon (One-handed)",
      0x5: "Dauragon (Two-handed)",
      0x6: "Dauragon (Shirtless)",
      0x7: "Dauragon (Tattoo)",
      0x8: "Mugetsu",
      0x9: "Mugetsu (Unmasked)",
      0xa: "PD-4",
      0xb: "Dominique",
      0xc: "Kaldea",
      0xd: "Wong",
      0xe: "Leann",
    },
    dialogs: {
      0x0: "English",
      0x1: "Japanese",
    },
    keldeo: {
      0x0: "-",
      0x1: "Beaten by Sion",
    },
    letters: {
      0x0: "A",
      0x1: "B",
      0x2: "C",
      0x3: "D",
      0x4: "E",
      0x5: "F",
      0x6: "G",
      0x7: "H",
      0x8: "I",
      0x9: "J",
      0xa: "K",
      0xb: "L",
      0xc: "M",
      0xd: "N",
      0xe: "O",
      0xf: "P",
      0x10: "Q",
      0x11: "R",
      0x12: "S",
      0x13: "T",
      0x14: "U",
      0x15: "V",
      0x16: "W",
      0x17: "X",
      0x18: "Y",
      0x19: "Z",
      0x1a: "0",
      0x1b: "1",
      0x1c: "2",
      0x1d: "3",
      0x1e: "4",
      0x1f: "5",
      0x20: "6",
      0x21: "7",
      0x22: "8",
      0x23: "9",
      0x24: ".",
      0x25: "-",
      0x26: "!",
      0x27: "?",
      0x28: " ",
    },
    locations: {
      0: "-",
      8: 'Bar - "Fate"',
      20: "Central Square",
      28: "Central Station (1)",
      34: "Central Station (2)",
      42: "MSD Cargo Train (1)",
      48: "MSD Cargo Train (2)",
      73: "Emergency Exit",
      78: "Mikado Station No. 1",
      82: "Air-Carrier",
      86: "Mikado Bldg. - Hanging Garden (1)",
      92: "Mikado Bldg. - Hanging Garden (2)",
      106: "Crystal Dome",
      126: "Mikado Bldg. - 65F: Storeroom Area",
      129: "Mikado Bldg. - 65F: Hall",
      131: "Mikado Bldg. - 65F: Meeting Room",
      132: "Mikado Bldg. - 66F: Hall",
      142: "Mikado Bldg. - Laboratory Prep Room",
      146: "Mikado Bldg. - Executive Office Hallway",
      152: "Mikado Bldg. - Enhancement Surgery Area",
      154: "Mikado Bldg. - Bio-plant",
      156: "Mikado Bldg. - Robot Factory",
      161: "Mikado Bldg. - MFB Room",
      166: "Mikado Bldg. - 9F: Hall",
      180: "Mikado Bldg. - Executive Office",
      190: "Rocket Tower (1)",
      198: "Rocket Tower (2)",
      210: "Rocket Tower - Basement",
      216: "Rocket Tower - Deck",
      236: "Air-Carrier",
      248: "Galeos - Passageway",
      266: "Galeos - Control Room (1)",
      272: "Galeos - Control Room (2)",
      285: "Flashback - Wong's Training (Epilogue)",
      296: "Central Square (Epilogue)",
      999: "Game Cleared",
    },
    mainCharacters: {
      0x0: "Sion Barzahd",
      0x1: "Volt Krueger",
      0x2: "Kou Leifoh",
    },
    menus: [
      // Europe
      {
        0x0: "English",
        0x1: "German",
        0x2: "French",
        0x3: "Italian",
        0x4: "Spanish",
      },
      // USA
      {
        0x0: "English",
        0x1: "Japanese",
      },
      // Japan
      {
        0x0: "English",
        0x1: "Japanese",
      },
    ],
    optionBoolean: {
      0x0: "Off",
      0x1: "On",
    },
    ranks: {
      0x0: "G",
      0x1: "F",
      0x2: "E",
      0x3: "D",
      0x4: "C",
      0x5: "B",
      0x6: "A",
      0x7: "S",
    },
    sensitivities: {
      0x0: "High",
      0x1: "Medium",
      0x2: "Low",
    },
    soundModes: {
      0x0: "Stereo",
      0x1: "Monaural",
    },
    subtitles: [
      // Europe
      {
        0x0: "English",
        0x1: "German",
        0x2: "French",
        0x3: "Italian",
        0x4: "Spanish",
        0x5: "Off",
      },
      // USA
      {
        0x0: "English",
        0x1: "Japanese",
        0x2: "Off",
      },
      // Japan
      {
        0x0: "English",
        0x1: "Japanese",
        0x2: "Off",
      },
    ],
  },
  resourcesLabels: {
    locations: {
      8: "Part 1",
      126: "Sion's Special Event",
      152: "Volt's Special Event",
      161: "Kou's Special Event",
      180: "Part 2",
      266: "Endings",
      999: "Game Cleared",
    },
  },
};

export default template;
