import { bitToOffset } from "$lib/utils/bytes";

import type { GameJson } from "$lib/types";

import { characters, items, itemsGroups } from "./utils/resource";

const template: GameJson = {
  validator: {
    platforms: {
      megadrive: {
        europe_usa: {
          0x100: [
            0x59, 0x41, 0x53, 0x55, 0x48, 0x49, 0x52, 0x4f, 0x48, 0x49, 0x52,
            0x4f, 0x4b, 0x4f,
          ], // YASUHIROHIROKO
        },
        japan: {
          0x100: [
            0x59, 0x41, 0x53, 0x55, 0x48, 0x49, 0x52, 0x4f, 0x48, 0x49, 0x52,
            0x4f, 0x4b, 0x4f,
          ], // YASUHIROHIROKO
        },
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      id: "slots",
      length: 0x8fc,
      type: "container",
      instanceType: "tabs",
      instances: 3,
      enumeration: "Slot %d",
      onTabChange: "onSlotChange(%d)",
      items: [
        {
          name: "Checksum",
          offset: 0x9ce,
          type: "checksum",
          dataType: "uint8",
          control: {
            offsetStart: 0x118,
            offsetEnd: 0x9ce,
          },
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              flex: true,
              items: [
                {
                  id: "chapter",
                  name: "Chapter",
                  offset: 0x118,
                  type: "variable",
                  dataType: "uint8",
                  min: 1,
                  max: 8,
                  hint: "Changing this value will reset the current chapter.",
                },
                {
                  name: "Chapter Progression",
                  offset: 0x16a,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "Gold",
                  offset: 0x1a6,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  max: 999999,
                },
              ],
            },
            {
              name: "Party",
              items: [
                {
                  id: "party",
                  length: 0x28,
                  type: "container",
                  instanceType: "tabs",
                  instances: 30,
                  resource: "characterNames",
                  vertical: true,
                  items: [
                    {
                      type: "tabs",
                      items: [
                        {
                          name: "Status",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  id: "characterName-%parent%-%index%",
                                  name: "Name",
                                  offset: 0x1aa,
                                  length: 0x8,
                                  type: "variable",
                                  dataType: "string",
                                  letterDataType: "uint8",
                                  fallback: 0x20,
                                  endCode: 0x0,
                                  regex: "[ !#',\-.0-9?A-Za-z]",
                                  test: true,
                                },
                                {
                                  name: "Class",
                                  offset: 0x1b4,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "classes",
                                  autocomplete: true,
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Level",
                                  offset: 0x1b5,
                                  type: "variable",
                                  dataType: "uint8",
                                  min: 1,
                                  max: 99,
                                },
                                {
                                  name: "Experience",
                                  offset: 0x1bb,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 99,
                                },
                                {
                                  name: "HP",
                                  type: "group",
                                  mode: "fraction",
                                  linked: true,
                                  items: [
                                    {
                                      id: "current",
                                      offset: 0x1be,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                    },
                                    {
                                      offset: 0x1bc,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      max: 99,
                                    },
                                  ],
                                },
                                {
                                  name: "MP",
                                  type: "group",
                                  mode: "fraction",
                                  linked: true,
                                  items: [
                                    {
                                      id: "current",
                                      offset: 0x1c1,
                                      type: "variable",
                                      dataType: "uint8",
                                    },
                                    {
                                      offset: 0x1c0,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 99,
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Attack",
                                  offset: 0x1b6,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 99,
                                },
                                {
                                  name: "Defense",
                                  offset: 0x1b7,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 99,
                                },
                                {
                                  name: "Agility",
                                  offset: 0x1b8,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 99,
                                },
                                {
                                  name: "Move",
                                  offset: 0x1b9,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 9,
                                },
                                {
                                  name: "Critical",
                                  offset: 0x1ba,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 100,
                                  suffix: "%",
                                },
                              ],
                            },
                            {
                              name: "Condition",
                              type: "bitflags",
                              flags: [
                                { offset: 0x1c3, bit: 0, label: "Poisoned" },
                                { offset: 0x1c3, bit: 1, label: "Asleep" },
                                { offset: 0x1c3, bit: 2, label: "Cursed" },
                                { offset: 0x1c3, bit: 3, label: "???", hidden: true },
                                { offset: 0x1c3, bit: 4, label: "Confused" },
                                { offset: 0x1c3, bit: 5, label: "???", hidden: true },
                                { offset: 0x1c3, bit: 6, label: "Silenced" },
                                { offset: 0x1c3, bit: 7, label: "???", hidden: true },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Magic",
                          items: [
                            {
                              length: 0x1,
                              type: "container",
                              instanceType: "section",
                              instances: 4,
                              flex: true,
                              noMargin: true,
                              items: [
                                {
                                  id: "spell",
                                  name: "Spell %d",
                                  offset: 0x1c8,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: {
                                    bitStart: 0,
                                    bitLength: 6,
                                  },
                                  resource: "spells",
                                  autocomplete: true,
                                },
                                {
                                  id: "spellLevel",
                                  name: "Level",
                                  offset: 0x1c8,
                                  type: "variable",
                                  dataType: "uint8",
                                  binary: {
                                    bitStart: 6,
                                    bitLength: 2,
                                  },
                                  operations: [{ "+": 1 }],
                                  min: 1,
                                  max: 4,
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Items",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              noMargin: true,
                              items: [
                                {
                                  name: "Item 1",
                                  type: "group",
                                  items: [
                                    {
                                      id: "item",
                                      offset: 0x1c4,
                                      type: "variable",
                                      dataType: "uint8",
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 7,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      id: "itemStatus",
                                      offset: 0x1c4,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 7,
                                      resource: "booleanEquipped",
                                    },
                                  ],
                                },
                                {
                                  name: "Item 2",
                                  type: "group",
                                  items: [
                                    {
                                      id: "item",
                                      offset: 0x1c5,
                                      type: "variable",
                                      dataType: "uint8",
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 7,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      id: "itemStatus",
                                      offset: 0x1c5,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 7,
                                      resource: "booleanEquipped",
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Item 3",
                                  type: "group",
                                  items: [
                                    {
                                      id: "item",
                                      offset: 0x1c6,
                                      type: "variable",
                                      dataType: "uint8",
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 7,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      id: "itemStatus",
                                      offset: 0x1c6,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 7,
                                      resource: "booleanEquipped",
                                    },
                                  ],
                                },
                                {
                                  name: "Item 4",
                                  type: "group",
                                  items: [
                                    {
                                      id: "item",
                                      offset: 0x1c7,
                                      type: "variable",
                                      dataType: "uint8",
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 7,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      id: "itemStatus",
                                      offset: 0x1c7,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 7,
                                      resource: "booleanEquipped",
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Formation",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: characters.map((character) => ({
                    id: `formation-${character.index}`,
                    name: character.name,
                    offset: 0x1a5 - bitToOffset(character.index),
                    type: "variable",
                    dataType: "bit",
                    bit: character.index % 8,
                    resource: "formations",
                  })),
                },
                {
                  type: "section",
                  flex: true,
                  hidden: true,
                  items: [
                    {
                      name: "Character 1",
                      offset: 0x6a2,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 2",
                      offset: 0x6a3,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 3",
                      offset: 0x6a4,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 4",
                      offset: 0x6a5,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 5",
                      offset: 0x6a6,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 6",
                      offset: 0x6a7,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 7",
                      offset: 0x6a8,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 8",
                      offset: 0x6a9,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 9",
                      offset: 0x6aa,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 10",
                      offset: 0x6ab,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 11",
                      offset: 0x6ac,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                    {
                      name: "Character 12",
                      offset: 0x6ad,
                      type: "variable",
                      dataType: "uint8",
                      resource: "characterNames",
                      autocomplete: true,
                      hidden: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Characters",
                      type: "bitflags",
                      hidden: true,
                      flags: characters.map((character) => ({
                        offset: 0x1a5 - bitToOffset(character.index),
                        bit: character.index % 8,
                        label: character.name,
                      })),
                    },
                  ],
                },
              ],
            },
            {
              name: "Options",
              flex: true,
              items: [
                {
                  name: "Message Speed",
                  offset: 0x11d,
                  type: "variable",
                  dataType: "uint8",
                  operations: [{ "+": 1 }],
                  min: 1,
                  max: 4,
                },
                {
                  name: "Battle Message",
                  offset: 0x11e,
                  type: "variable",
                  dataType: "uint8",
                  resource: "optionBooleanReversed",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    booleanEquipped: {
      0x0: "-",
      0x1: "Equipped",
    },
    characterNames: "getCharacterNames()",
    classes: {
      0x0: "Swordsman",
      0x1: "Knight",
      0x2: "Warrior",
      0x3: "Steam Knight",
      0x4: "Mage",
      0x5: "Monk",
      0x6: "Healer",
      0x7: "Archer",
      0x8: "Assault Knight",
      0x9: "Birdman",
      0xa: "Wing Knight",
      0xb: "Dragon",
      0xc: "Robot",
      0xd: "Werewolf",
      0xe: "Samurai",
      0xf: "Ninja",
      0x10: "Hero",
      0x11: "Paladin",
      0x12: "Gladiator",
      0x13: "Steam Baron",
      0x14: "Wizard",
      0x15: "Master Monk",
      0x16: "Vicar",
      0x17: "Bow Master",
      0x18: "Strike Knight",
      0x19: "Sky Warrior",
      0x1a: "Sky Lord",
      0x1b: "Great Dragon",
      0x1c: "Cyborg",
      0x1d: "Wolf Baron",
      0x1e: "Yogurt",
      0x1f: "Magic Creature",
    },
    formations: {
      0x0: "-",
      0x1: "Reserve",
      0x2: "Main Squad",
    },
    items: {
      ...items,
      0x7f: "-",
    },
    letters: {
      0x20: " ",
      0x21: "!",
      0x2d: "-",
      0x3f: "?",
      0x66: "を",
      0x67: "ぁ",
      0x68: "ぃ",
      0x69: "ぅ",
      0x6a: "ぇ",
      0x6b: "ぉ",
      0x6c: "ゃ",
      0x6d: "ゅ",
      0x6e: "ょ",
      0x6f: "っ",
      0x71: "あ",
      0x72: "い",
      0x73: "う",
      0x74: "え",
      0x75: "お",
      0x76: "か",
      0x77: "き",
      0x78: "く",
      0x79: "け",
      0x7a: "こ",
      0x7b: "さ",
      0x7c: "し",
      0x7d: "す",
      0x7e: "せ",
      0x7f: "そ",
      0x80: "た",
      0x81: "ち",
      0x82: "つ",
      0x83: "て",
      0x84: "と",
      0x85: "な",
      0x86: "に",
      0x87: "ぬ",
      0x88: "ね",
      0x89: "の",
      0x8a: "は",
      0x8b: "ひ",
      0x8c: "ふ",
      0x8d: "へ",
      0x8e: "ほ",
      0x8f: "ま",
      0x90: "み",
      0x91: "む",
      0x92: "め",
      0x93: "も",
      0x94: "や",
      0x95: "ゆ",
      0x96: "よ",
      0x97: "ら",
      0x98: "り",
      0x99: "る",
      0x9a: "れ",
      0x9b: "ろ",
      0x9c: "わ",
      0x9d: "ん",
      0x9e76: "が",
      0x9e77: "ぎ",
      0x9e78: "ぐ",
      0x9e79: "げ",
      0x9e7a: "ご",
      0x9e7b: "ざ",
      0x9e7c: "じ",
      0x9e7d: "ず",
      0x9e7e: "ぜ",
      0x9e7f: "ぞ",
      0x9e80: "だ",
      0x9e81: "ぢ",
      0x9e82: "づ",
      0x9e83: "で",
      0x9e84: "ど",
      0x9e8a: "ば",
      0x9e8b: "び",
      0x9e8c: "ぶ",
      0x9e8d: "べ",
      0x9e8e: "ぼ",
      0x9eb6: "ガ",
      0x9eb7: "ギ",
      0x9eb8: "グ",
      0x9eb9: "ゲ",
      0x9eba: "ゴ",
      0x9ebb: "ザ",
      0x9ebc: "ジ",
      0x9ebd: "ズ",
      0x9ebe: "ゼ",
      0x9ebf: "ゾ",
      0x9ec0: "ダ",
      0x9ec1: "ヂ",
      0x9ec2: "ヅ",
      0x9ec3: "デ",
      0x9ec4: "ド",
      0x9eca: "バ",
      0x9ecb: "ビ",
      0x9ecc: "ブ",
      0x9ecd: "ベ",
      0x9ece: "ボ",
      0x9f8a: "ぱ",
      0x9f8b: "ぴ",
      0x9f8c: "ぷ",
      0x9f8d: "ぺ",
      0x9f8e: "ぽ",
      0x9fca: "パ",
      0x9fcb: "ピ",
      0x9fcc: "プ",
      0x9fcd: "ペ",
      0x9fce: "ポ",
      0xa1: "。",
      0xa4: "、",
      0xa6: "ヲ",
      0xa7: "ァ",
      0xa8: "ィ",
      0xa9: "ゥ",
      0xaa: "ェ",
      0xab: "ォ",
      0xac: "ャ",
      0xad: "ュ",
      0xae: "ョ",
      0xaf: "ッ",
      0xb1: "ア",
      0xb2: "イ",
      0xb3: "ウ",
      0xb4: "エ",
      0xb5: "オ",
      0xb6: "カ",
      0xb7: "キ",
      0xb8: "ク",
      0xb9: "ケ",
      0xba: "コ",
      0xbb: "サ",
      0xbc: "シ",
      0xbd: "ス",
      0xbe: "セ",
      0xbf: "ソ",
      0xc0: "タ",
      0xc1: "チ",
      0xc2: "ツ",
      0xc3: "テ",
      0xc4: "ト",
      0xc5: "ナ",
      0xc6: "ニ",
      0xc7: "ヌ",
      0xc8: "ネ",
      0xc9: "ノ",
      0xca: "ハ",
      0xcb: "ヒ",
      0xcc: "フ",
      0xcd: "ヘ",
      0xce: "ホ",
      0xcf: "マ",
      0xd0: "ミ",
      0xd1: "ム",
      0xd2: "メ",
      0xd3: "モ",
      0xd4: "ヤ",
      0xd5: "ユ",
      0xd6: "ヨ",
      0xd7: "ラ",
      0xd8: "リ",
      0xd9: "ル",
      0xda: "レ",
      0xdb: "ロ",
      0xdc: "ワ",
      0xdd: "ン",
    },
    optionBooleanReversed: {
      0x0: "On",
      0x1: "Off",
    },
    spells: {
      0x0: "Heal",
      0x1: "Aura",
      0x2: "Detox",
      0x3: "Quick",
      0x4: "Slow",
      0x5: "Boost",
      0x6: "Dispel",
      0x7: "Shield",
      0x8: "Muddle",
      0x9: "Blaze",
      0xa: "Freeze",
      0xb: "Bolt",
      0xc: "Desoul",
      0xd: "Egress",
      0xf: "Sleep",
      0x3f: "-",
    },
  },
  resourcesGroups: {
    items: itemsGroups,
  },
  resourcesOrder: {
    formations: [0x0, 0x2, 0x1],
    spells: [0x3f],
  },
};

export default template;
