import { bitToOffset } from "$lib/utils/bytes";

import type { GameJson } from "$lib/types";

import { missionFragment } from "./utils/fragment";
import {
  fieldTrainings,
  missionList,
  missions,
  nextMissions,
  rankings,
  rankingsLabels,
  warRoomMapList,
  warRoomMaps,
} from "./utils/resource";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa: {
        0xf000: [0x77, 0x61, 0x72, 0x73], // "wars"
      },
      japan: {
        0xf000: [0x77, 0x61, 0x72, 0x73], // "wars"
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      name: "Checksum",
      offset: 0x6,
      type: "checksum",
      dataType: "uint16",
      control: {
        offsetStart: 0x0,
        offsetEnd: 0x1000,
      },
    },
    {
      type: "tabs",
      items: [
        {
          name: "General",
          items: [
            {
              type: "section",
              flex: true,
              items: [
                {
                  name: "Save Count",
                  offset: 0x8,
                  type: "variable",
                  dataType: "uint32",
                  hidden: true,
                  test: true,
                },
                {
                  id: "name",
                  name: "Name",
                  offset: 0x372,
                  length: 0x8,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  fallback: 0x20,
                  endCode: 0x0,
                  regex: "[ !&,\-./0-9:?A-Za-z¡ªº¿À-ÄÇ-ÏÑ-ÔÖÙ-Üà-äç-ïñ-ôöù-üẞ]",
                  test: true,
                },
                {
                  name: "Progression",
                  offset: 0x38f,
                  type: "variable",
                  dataType: "uint8",
                  resource: "progressions",
                },
                {
                  name: "Points",
                  offset: 0x386,
                  type: "variable",
                  dataType: "uint32",
                  max: 9999,
                },
                {
                  id: "globalRank",
                  name: "Rank",
                  offset: 0x386,
                  type: "variable",
                  dataType: "uint32",
                  resource: "rankings",
                  autocomplete: true,
                },
              ],
            },
            {
              name: "Coins",
              offset: 0x382,
              type: "variable",
              dataType: "uint16",
              max: 999,
            },
            {
              type: "section",
              flex: true,
              hidden: true,
              items: [
                {
                  name: "Last Selected Menu",
                  offset: 0x38a,
                  type: "variable",
                  dataType: "uint16",
                  hidden: true,
                },
                {
                  name: "Animation Option",
                  offset: 0x38c,
                  type: "variable",
                  dataType: "uint16",
                  hidden: true,
                },
                {
                  name: "Battle Maps Entrance Count",
                  offset: 0x38e,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "Last Selected Field Training",
                  offset: 0x391,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
              ],
            },
            {
              type: "section",
              flex: true,
              hidden: true,
              items: [
                {
                  name: "Pending Field Training",
                  offset: 0x532,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "Pending Campaign",
                  offset: 0x533,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "Pending War Room",
                  offset: 0x534,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  name: "Pending Vs. Mode",
                  offset: 0x535,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
              ],
            },
          ],
        },
        {
          name: "Campaign",
          items: [
            {
              id: "campaign",
              type: "tabs",
              vertical: true,
              items: [
                {
                  name: "Campaign",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Points",
                          offset: 0x41e,
                          type: "variable",
                          dataType: "uint16",
                          max: 999,
                        },
                        {
                          id: "rank",
                          name: "Rank",
                          offset: 0x41e,
                          type: "variable",
                          dataType: "uint16",
                          resource: "ranks",
                        },
                      ],
                    },
                    ...missionList.map((mission) =>
                      missionFragment(mission, 0x422),
                    ),
                  ],
                },
                {
                  name: "Advance Campaign",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Points",
                          offset: 0x420,
                          type: "variable",
                          dataType: "uint16",
                          max: 999,
                        },
                        {
                          id: "rank",
                          name: "Rank",
                          offset: 0x420,
                          type: "variable",
                          dataType: "uint16",
                          resource: "ranks",
                        },
                      ],
                    },
                    ...missionList.map((mission) =>
                      missionFragment(mission, 0x4aa),
                    ),
                  ],
                },
                {
                  name: "Pending",
                  items: [
                    {
                      type: "section",
                      flex: true,
                      items: [
                        {
                          name: "Mode",
                          offset: 0x393,
                          type: "variable",
                          dataType: "uint8",
                          resource: "campaignModes",
                        },
                        {
                          id: "nextMission",
                          name: "Next Mission",
                          offset: 0x392,
                          type: "variable",
                          dataType: "uint8",
                          resource: "nextMissions",
                          autocomplete: true,
                        },
                      ],
                    },
                    {
                      length: 0x4,
                      type: "container",
                      instanceType: "section",
                      instances: 26,
                      flex: true,
                      noMargin: true,
                      items: [
                        {
                          id: "campaignMission",
                          name: "Mission %d",
                          offset: 0x396,
                          type: "variable",
                          dataType: "uint8",
                          resource: "missions",
                          autocomplete: true,
                        },
                        {
                          id: "missionInput-0",
                          name: "Days",
                          offset: 0x397,
                          type: "variable",
                          dataType: "uint16",
                          binary: {
                            bitStart: 0,
                            bitLength: 12,
                          },
                          min: 1,
                          max: 999,
                        },
                        {
                          id: "missionInput-1",
                          name: "Points",
                          offset: 0x398,
                          type: "variable",
                          dataType: "uint16",
                          binary: {
                            bitStart: 4,
                            bitLength: 12,
                          },
                          max: 999,
                        },
                        {
                          id: "rank-1",
                          name: "Rank",
                          offset: 0x398,
                          type: "variable",
                          dataType: "uint16",
                          binary: {
                            bitStart: 4,
                            bitLength: 12,
                          },
                          resource: "ranks",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "War Room",
          items: [
            {
              length: 0x28,
              type: "container",
              instanceType: "tabs",
              instances: 20,
              resource: "warRoomMaps",
              vertical: true,
              items: [
                {
                  length: 0x8,
                  type: "container",
                  instanceType: "section",
                  instances: 5,
                  enumeration: "%o Place",
                  flex: true,
                  items: [
                    {
                      id: "warRoomCo",
                      name: "CO",
                      offset: 0x52,
                      type: "variable",
                      dataType: "uint16",
                      resource: "cos",
                      autocomplete: true,
                    },
                    {
                      id: "missionInput-0",
                      name: "Days",
                      offset: 0x54,
                      type: "variable",
                      dataType: "uint16",
                      min: 1,
                      max: 999,
                    },
                    {
                      id: "missionInput-2",
                      name: "Points",
                      offset: 0x56,
                      type: "variable",
                      dataType: "uint16",
                      max: 999,
                    },
                    {
                      id: "rank-2",
                      name: "Rank",
                      offset: 0x56,
                      type: "variable",
                      dataType: "uint16",
                      resource: "ranks",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Field Training",
          items: fieldTrainings.map((mission, index) => ({
            type: "section",
            flex: true,
            noMargin: true,
            items: [
              {
                id: `fieldTraining-${index}`,
                name: mission,
                offset: 0x390,
                type: "variable",
                dataType: "uint8",
                resource: "booleanUnlocked",
              },
              {
                name: "Rank",
                offset: 0x536 + index,
                type: "variable",
                dataType: "uint8",
                resource: "fieldTrainingRanks",
              },
            ],
          })),
        },
        {
          name: "Battle Maps",
          items: [
            {
              type: "tabs",
              items: [
                {
                  name: "General",
                  flex: true,
                  items: [
                    {
                      type: "section",
                      items: [
                        {
                          name: "Campaign",
                          type: "bitflags",
                          flags: [
                            { offset: 0x567, bit: 0, label: "Advance Campaign" },
                          ],
                        },
                        {
                          name: "Map Cases",
                          type: "bitflags",
                          flags: [
                            { offset: 0x546, bit: 2, label: "Special Map" },
                            { offset: 0x546, bit: 3, label: "Vs. Map" },
                            { offset: 0x546, bit: 4, label: "Pre-Deployed" },
                            { offset: 0x546, bit: 5, label: "3P Maps" },
                            { offset: 0x546, bit: 6, label: "4P Maps" },
                            { offset: 0x546, bit: 7, label: "War Room" },
                          ],
                        },
                      ],
                    },
                    {
                      name: "COs",
                      type: "bitflags",
                      flags: [
                        { offset: 0x560, bit: 0, label: "Nell" },
                        { offset: 0x560, bit: 1, label: "Andy" },
                        { offset: 0x560, bit: 2, label: "Max" },
                        { offset: 0x560, bit: 3, label: "Olaf" },
                        { offset: 0x560, bit: 4, label: "Sami" },
                        { offset: 0x560, bit: 5, label: "Grit" },
                        { offset: 0x560, bit: 6, label: "Kanbei" },
                        { offset: 0x560, bit: 7, label: "Sonja" },
                        { offset: 0x561, bit: 0, label: "Eagle" },
                        { offset: 0x561, bit: 1, label: "Drake" },
                        { offset: 0x561, bit: 2, label: "Sturm (Campaign)", hidden: true },
                        { offset: 0x561, bit: 3, label: "Sturm" },
                      ],
                    },
                  ],
                },
                {
                  name: "Maps",
                  flex: true,
                  items: [
                    {
                      name: "Special",
                      type: "bitflags",
                      flags: [
                        { offset: 0x549, bit: 1, label: "Bean Island" },
                        { offset: 0x549, bit: 2, label: "Crater Isle" },
                        { offset: 0x549, bit: 3, label: "Triangles" },
                        { offset: 0x549, bit: 4, label: "Ball Islands" },
                        { offset: 0x549, bit: 5, label: "Coral Lagoon" },
                        { offset: 0x549, bit: 6, label: "Puzzle Trio" },
                        { offset: 0x549, bit: 7, label: "Fist Peninsula" },
                        { offset: 0x54a, bit: 0, label: "Deer Harbor" },
                        { offset: 0x54a, bit: 1, label: "Alara Range" },
                        { offset: 0x54a, bit: 2, label: "Lost River" },
                        { offset: 0x54a, bit: 3, label: "Volcano Isle" },
                        { offset: 0x54a, bit: 4, label: "Turtle Atoll" },
                        { offset: 0x54a, bit: 5, label: "Squash Island" },
                        { offset: 0x54a, bit: 6, label: "Cube Keys" },
                        { offset: 0x54a, bit: 7, label: "Mirror Islands" },
                        { offset: 0x54b, bit: 0, label: "Shark Strait" },
                        { offset: 0x54b, bit: 1, label: "Royal Channel" },
                      ],
                    },
                    {
                      name: "Vs. Maps",
                      type: "bitflags",
                      flags: [
                        { offset: 0x54b, bit: 2, label: "Little Island" },
                        { offset: 0x54b, bit: 3, label: "Sun Canal" },
                        { offset: 0x54b, bit: 4, label: "Beaker River" },
                        { offset: 0x54b, bit: 5, label: "Star Islands" },
                        { offset: 0x54b, bit: 6, label: "Eon Springs" },
                        { offset: 0x54b, bit: 7, label: "Portal Bridge" },
                        { offset: 0x54c, bit: 0, label: "Sabre Range" },
                        { offset: 0x54c, bit: 1, label: "Asphalt Maze" },
                        { offset: 0x54c, bit: 2, label: "Cog Isle" },
                        { offset: 0x54c, bit: 3, label: "Zero Wood" },
                        { offset: 0x54c, bit: 4, label: "Switchback" },
                        { offset: 0x54c, bit: 5, label: "Ruby Keys" },
                        { offset: 0x54c, bit: 6, label: "Rainy Haven" },
                        { offset: 0x54c, bit: 7, label: "Rail Strait" },
                        { offset: 0x54d, bit: 0, label: "Tribe Islands" },
                        { offset: 0x54d, bit: 1, label: "Vision Bridge" },
                        { offset: 0x54d, bit: 2, label: "Piston Dam" },
                        { offset: 0x54d, bit: 3, label: "Hat Harbor" },
                        { offset: 0x54d, bit: 4, label: "Swan Cove" },
                        { offset: 0x54d, bit: 5, label: "Go Islands" },
                      ],
                    },
                    {
                      name: "Pre-Deployed",
                      type: "bitflags",
                      flags: [
                        { offset: 0x54d, bit: 6, label: "Brace Range" },
                        { offset: 0x54d, bit: 7, label: "River Range" },
                        { offset: 0x54e, bit: 0, label: "Moon Isle" },
                        { offset: 0x54e, bit: 1, label: "Mint Plateau" },
                        { offset: 0x54e, bit: 2, label: "Jewel Canal" },
                        { offset: 0x54e, bit: 3, label: "Wrench Island" },
                        { offset: 0x54e, bit: 4, label: "Rapid Ferry" },
                        { offset: 0x54e, bit: 5, label: "Bundle City" },
                        { offset: 0x54e, bit: 6, label: "Scarab Road" },
                        { offset: 0x54e, bit: 7, label: "Pointing River" },
                        { offset: 0x54f, bit: 0, label: "Liaison Wood" },
                        { offset: 0x54f, bit: 1, label: "Delta Heights" },
                        { offset: 0x54f, bit: 2, label: "Poem Cape" },
                        { offset: 0x54f, bit: 3, label: "Blue Lake" },
                        { offset: 0x54f, bit: 4, label: "Coil Range" },
                        { offset: 0x54f, bit: 5, label: "Leaf Haven" },
                        { offset: 0x54f, bit: 6, label: "Battle Cube" },
                      ],
                    },
                    {
                      name: "3P Maps",
                      type: "bitflags",
                      flags: [
                        { offset: 0x54f, bit: 7, label: "Pyramid Cape" },
                        { offset: 0x550, bit: 0, label: "Bead Islands" },
                        { offset: 0x550, bit: 1, label: "Clover Keys" },
                        { offset: 0x550, bit: 2, label: "Keyhole Cove" },
                        { offset: 0x550, bit: 3, label: "Fork River" },
                        { offset: 0x550, bit: 4, label: "Mantis River" },
                        { offset: 0x550, bit: 5, label: "Channel City" },
                        { offset: 0x550, bit: 6, label: "Ink Canal" },
                        { offset: 0x550, bit: 7, label: "Shield Hills" },
                        { offset: 0x551, bit: 0, label: "Peril Maze" },
                        { offset: 0x551, bit: 1, label: "Gem Creek" },
                        { offset: 0x551, bit: 2, label: "Glass Heights" },
                        { offset: 0x551, bit: 3, label: "Devil's Inlet" },
                        { offset: 0x551, bit: 4, label: "Shear Port" },
                        { offset: 0x551, bit: 5, label: "Liar's Cove" },
                        { offset: 0x551, bit: 6, label: "Nail Canal" },
                        { offset: 0x551, bit: 7, label: "Atlas River" },
                        { offset: 0x552, bit: 0, label: "Eel Channels" },
                        { offset: 0x552, bit: 1, label: "Jab Peninsula" },
                        { offset: 0x552, bit: 2, label: "Thorn Islands" },
                      ],
                    },
                    {
                      name: "4P Maps",
                      type: "bitflags",
                      flags: [
                        { offset: 0x552, bit: 3, label: "Four Corners" },
                        { offset: 0x552, bit: 4, label: "Rocket Cape" },
                        { offset: 0x552, bit: 5, label: "Crop River" },
                        { offset: 0x552, bit: 6, label: "Tween Isle" },
                        { offset: 0x552, bit: 7, label: "Rival Islands" },
                        { offset: 0x553, bit: 0, label: "Loop Road" },
                        { offset: 0x553, bit: 1, label: "Plus Canal" },
                        { offset: 0x553, bit: 2, label: "Islas Five" },
                        { offset: 0x553, bit: 3, label: "Patriot Cove" },
                        { offset: 0x553, bit: 4, label: "Web River" },
                        { offset: 0x553, bit: 5, label: "Cap Narrows" },
                        { offset: 0x553, bit: 6, label: "Jay Islands" },
                        { offset: 0x553, bit: 7, label: "Chain Canal" },
                        { offset: 0x554, bit: 0, label: "Spring Lakes" },
                        { offset: 0x554, bit: 1, label: "Tatter River" },
                        { offset: 0x554, bit: 2, label: "Island X" },
                        { offset: 0x554, bit: 3, label: "Alakule" },
                        { offset: 0x554, bit: 4, label: "Traitor River" },
                        { offset: 0x554, bit: 5, label: "Fable Hills" },
                        { offset: 0x554, bit: 6, label: "South Cape" },
                        { offset: 0x554, bit: 7, label: "Glory Islands" },
                      ],
                    },
                    {
                      name: "War Room",
                      type: "bitflags",
                      flags: warRoomMapList.map((map, index) => ({
                        offset: 0x555 + bitToOffset(index),
                        bit: index % 8,
                        label: map,
                      })),
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    booleanUnlocked: {
      0x0: "-",
      0x1: "Unlocked",
    },
    campaignModes: {
      0x0: "Campaign",
      0x1: "Advance Campaign",
    },
    cos: {
      0x0: "Nell",
      0x1: "Andy",
      0x2: "Max",
      0x3: "Olaf",
      0x4: "Sami",
      0x5: "Grit",
      0x6: "Kanbei",
      0x7: "Sonja",
      0x8: "Eagle",
      0x9: "Drake",
      0xa: "Sturm (Campaign)",
      0xb: "Sturm (Vs. Mode)",
      0xff: "-",
    },
    fieldTrainingRanks: {
      0x0: "E",
      0x1: "D",
      0x2: "C",
      0x3: "B",
      0x4: "A",
      0xff: "-",
    },
    missionRanks: {
      0x0: "E",
      0x1: "D",
      0x2: "C",
      0x3: "B",
      0x4: "A",
      0x5: "S",
      0xff: "-",
    },
    missions: {
      ...missions,
      0xff: "-",
    },
    nextMissions,
    progressions: {
      0x0: "New Game",
      0x1: "Field Training Pending",
      0x2: "Field Training Clear",
      0x3: "Campaign Clear",
      0x4: "Advance Campagin Clear",
    },
    rankings,
    ranks: {
      0x0: "E",
      0x1: "D",
      0x2: "C",
      0x3: "B",
      0x4: "A",
      0x5: "S",
    },
    warRoomMaps,
  },
  resourcesLabels: {
    rankings: rankingsLabels,
  },
  resourcesOrder: {
    cos: [0xff],
    fieldTrainingRanks: [0xff],
    missionRanks: [0xff],
    missions: [0xff],
  },
};

export default template;
