import type { Resource, ResourceGroups } from "$lib/types";

// prettier-ignore
export const chapterList = [
  { index: 0x0, name: "Prologue: A Girl from the Plains",                                             characters: [0x1] },
  { index: 0x1, name: "Ch. 1: Footsteps of Fate",                                                     characters: [0x1] },
  { index: 0x2, name: "Ch. 2: Sword of Spirits",                                                      characters: [0x1] },
  { index: 0x3, name: "Ch. 3: Band of Mercenaries",                                                   characters: [0x1] },
  { index: 0x4, name: "Ch. 4: In Occupation's Shadow",                                                characters: [0x1] },
  { index: 0x5, name: "Ch. 5: Beyond the Borders",                                                    characters: [0x1] },
  { index: 0x6, name: "Ch. 6: Blood of Pride",                                                        characters: [0x1] },
  { index: 0x7, name: "Ch. 7: Siblings Abroad",                                                       characters: [0x1] },
  { index: 0x8, name: "Ch. 7x: The Black Shadow",                                                     characters: [0x1] },
  { index: 0x9, name: "Ch. 8: Vortex of Strategy",                                                    characters: [0x1] },
  { index: 0xa, name: "Ch. 9: A Grim Reunion",                                                        characters: [0x1] },
  { index: 0xb, name: "Ch. 10: The Distant Plains",                                                   characters: [0x1] },
  { index: 0xc, name: "Ch. 11: Taking Leave",                                                         characters: [0x2] },
  { index: 0xd, name: "Ch. 11: Another Journey",                                                      characters: [0x3] },
  { index: 0xe, name: "Ch. 12: Birds of a Feather",                                                   characters: [0x2, 0x3] },
  { index: 0xf, name: "Ch. 13: In Search of Truth",                                                   characters: [0x2, 0x3] },
  { index: 0x10, name: "Ch. 13x: The Peddler Merlinus",                                               characters: [0x2, 0x3] },
  { index: 0x11, name: "Ch. 14: False Friends",                                                       characters: [0x2, 0x3] },
  { index: 0x12, name: "Ch. 15: Talons Alight",                                                       characters: [0x3] },
  { index: 0x13, name: "Ch. 15: Noble Lady of Caelin",    nameAlt: "Ch. 16: Noble Lady of Caelin",    characters: [0x2, 0x3] },
  { index: 0x14, name: "Ch. 16: Whereabouts Unknown",     nameAlt: "Ch. 17: Whereabouts Unknown",     characters: [0x2, 0x3] },
  { index: 0x15, name: "Ch. 16x: The Port of Badon",      nameAlt: "Ch. 17x: The Port of Badon",      characters: [0x2, 0x3] },
  { index: 0x16, name: "Ch. 17: Pirate Ship",             nameAlt: "Ch. 18: Pirate Ship",             characters: [0x2, 0x3] },
  { index: 0x17, name: "Ch. 18: The Dread Isle",          nameAlt: "Ch. 19: The Dread Isle",          characters: [0x2, 0x3] },
  { index: 0x18, name: "Ch. 18x: Imprisoner of Magic",    nameAlt: "Ch. 19x: Prisoner of Magic",      characters: [0x2, 0x3] },
  { index: 0x19, name: "Ch. 19x pt 2: A Glimpse in Time", nameAlt: "Ch. 19x pt 2: A Glimpse in Time", characters: [0x3] },
  { index: 0x1a, name: "Ch. 19: Dragon's Gate",           nameAlt: "Ch. 20: Dragon's Gate",           characters: [0x2, 0x3] },
  { index: 0x1b, name: "Ch. 20: New Resolve",             nameAlt: "Ch. 21: New Resolve",             characters: [0x2, 0x3] },
  { index: 0x1c, name: "Ch. 21: Kinship's Bond",          nameAlt: "Ch. 22: Kinship's Bond",          characters: [0x2, 0x3] },
  { index: 0x1d, name: "Ch. 22: Living Legend",           nameAlt: "Ch. 23: Living Legend",           characters: [0x2, 0x3] },
  { index: 0x1e, name: "Ch. 22x: Genesis",                nameAlt: "Ch. 23x: Genesis",                characters: [0x2, 0x3] },
  { index: 0x1f, name: "Ch. 23: Four-Fanged Offense",     nameAlt: "Ch. 24: Four-Fanged Offense",     characters: [0x2, 0x3] }, // Linus / Lloyd
  { index: 0x20, name: "Ch. 23: Four-Fanged Offense",     nameAlt: "Ch. 24: Four-Fanged Offense",     characters: [0x2, 0x3] }, // Linus / Lloyd
  { index: 0x21, name: "Ch. 25: Crazed Beast",            nameAlt: "Ch. 25: Crazed Beast",            characters: [0x3] },
  { index: 0x22, name: "Ch. 24: Unfulfilled Heart",       nameAlt: "Ch. 26: Unfulfilled Heart",       characters: [0x2, 0x3] },
  { index: 0x23, name: "Ch. 25: Pale Flower of Darkness", nameAlt: "Ch. 27: Pale Flower of Darkness", characters: [0x2, 0x3] }, // Jerme / Kenneth
  { index: 0x24, name: "Ch. 25: Pale Flower of Darkness", nameAlt: "Ch. 27: Pale Flower of Darkness", characters: [0x2, 0x3] }, // Jerme / Kenneth
  { index: 0x25, name: "Ch. 26: Battle before Dawn",      nameAlt: "Ch. 28: Battle before Dawn",      characters: [0x2, 0x3] },
  { index: 0x26, name: "Ch. 26x: Night of Farewells",     nameAlt: "Ch. 28x: Night of Farewells",     characters: [0x2, 0x3] },
  { index: 0x27, name: "Ch. 27: Cog of Destiny",          nameAlt: "Ch. 29: Cog of Destiny",          characters: [0x2, 0x3] },
  { index: 0x28, name: "Ch. 28: Valorous Roland",         nameAlt: "Ch. 28: Valorous Roland",         characters: [0x2] },
  { index: 0x29, name: "Ch. 30: The Berserker",           nameAlt: "Ch. 30: The Berserker",           characters: [0x3] },
  { index: 0x2a, name: "Ch. 29: Sands of Time",           nameAlt: "Ch. 31: Sands of Time",           characters: [0x2, 0x3] },
  { index: 0x2b, name: "Ch. 29x: Battle Preparations",    nameAlt: "Ch. 31x: Battle Preparations",    characters: [0x2, 0x3] },
  { index: 0x2c, name: "Ch. 30: Victory or Death",        nameAlt: "Ch. 32: Victory or Death",        characters: [0x2, 0x3] },
  { index: 0x2d, name: "Ch. 32x: The Value of Life",      nameAlt: "Ch. 32x: The Value of Life",      characters: [0x3] },
  { index: 0x2e, name: "Final Chapter: Light (part 1)",                                               characters: [0x2, 0x3] },
  { index: 0x2f, name: "Final Chapter: Light (part 2)",                                               characters: [0x2, 0x3] },
];

const characterList = [
  { index: 0x0, name: "Eliwood" },
  { index: 0x1, name: "Hector" },
  { index: 0x2, name: "Lyn" },
  { index: 0x3, name: "Raven" },
  { index: 0x4, name: "Geitz" },
  { index: 0x5, name: "Guy" },
  { index: 0x6, name: "Karel" },
  { index: 0x7, name: "Dorcas" },
  { index: 0x8, name: "Bartre" },
  { index: 0x9, name: "Citizen" },
  { index: 0xa, name: "Oswin" },
  { index: 0xb, name: "Fargus" },
  { index: 0xc, name: "Wil" },
  { index: 0xd, name: "Rebecca" },
  { index: 0xe, name: "Louise" },
  { index: 0xf, name: "Lucius" },
  { index: 0x10, name: "Serra" },
  { index: 0x11, name: "Renaud" },
  { index: 0x12, name: "Erk" },
  { index: 0x13, name: "Nino" },
  { index: 0x14, name: "Pent" },
  { index: 0x15, name: "Canas" },
  { index: 0x16, name: "Kent" },
  { index: 0x17, name: "Sain" },
  { index: 0x18, name: "Lowen" },
  { index: 0x19, name: "Marcus" },
  { index: 0x1a, name: "Priscilla" },
  { index: 0x1b, name: "Rath" },
  { index: 0x1c, name: "Florina" },
  { index: 0x1d, name: "Fiora" },
  { index: 0x1e, name: "Farina" },
  { index: 0x1f, name: "Heath" },
  { index: 0x20, name: "Vaida" },
  { index: 0x21, name: "Hawkeye" },
  { index: 0x22, name: "Matthew" },
  { index: 0x23, name: "Jaffar" },
  { index: 0x24, name: "Ninian" },
  { index: 0x25, name: "Nils" },
  { index: 0x26, name: "Athos" },
  { index: 0x27, name: "Merlinus" },
  { index: 0x28, name: "Nils" },
  { index: 0x29, name: "Uther" },
  { index: 0x2a, name: "Vaida" },
  { index: 0x2b, name: "Wallace" },
  { index: 0x2c, name: "Lyn" },
  { index: 0x2d, name: "Wil" },
  { index: 0x2e, name: "Kent" },
  { index: 0x2f, name: "Sain" },
  { index: 0x30, name: "Florina" },
  { index: 0x31, name: "Rath" },
  { index: 0x32, name: "Dart" },
  { index: 0x33, name: "Isadora" },
  { index: 0x34, name: "Eleanora" },
  { index: 0x35, name: "Legault" },
  { index: 0x36, name: "Karla" },
  { index: 0x37, name: "Harken" },
  { index: 0x38, name: "Leila" },
  { index: 0x39, name: "Bramimond" },
  { index: 0x3a, name: "Kishuna" },
  { index: 0x3b, name: "Groznyi" },
  { index: 0x3c, name: "Wire" },
  { index: 0x3d, name: "Bandit" },
  { index: 0x3e, name: "Zagan" },
  { index: 0x3f, name: "Boies" },
  { index: 0x40, name: "Puzon" },
  { index: 0x41, name: "Bandit" },
  { index: 0x42, name: "Santals" },
  { index: 0x43, name: "Nergal" },
  { index: 0x44, name: "Erik" },
  { index: 0x45, name: "Sealen" },
];

export const characterEnum: Resource = {};
export const characters: Resource = {};

characterList.forEach((character) => {
  characterEnum[character.index] = character.name;
  characters[character.index + 0x1] = character.name;
});

export const lynChapters: Resource = {};
export const eliwoodChapters: Resource = {};
export const hectorChapters: Resource = {};

chapterList.forEach((chapter) => {
  if (chapter.characters.includes(0x1)) {
    lynChapters[chapter.index] = chapter.name;
  }

  if (chapter.characters.includes(0x2)) {
    eliwoodChapters[chapter.index] = chapter.name;
  }

  if (chapter.characters.includes(0x3)) {
    hectorChapters[chapter.index] = chapter.nameAlt || chapter.name;
  }
});

export const itemTypes = [
  { index: 0x0, name: "Swords" },
  { index: 0x1, name: "Lances" },
  { index: 0x2, name: "Axes" },
  { index: 0x3, name: "Bows" },
  { index: 0x4, name: "Nature" },
  { index: 0x5, name: "Light" },
  { index: 0x6, name: "Dark" },
  { index: 0x7, name: "Staves" },
  { index: 0x8, name: "Items" },
];

export const inventory = [
  { index: 0x1, name: "Iron sword", type: 0x0 },
  { index: 0x2, name: "Slim sword", type: 0x0 },
  { index: 0x3, name: "Steel sword", type: 0x0 },
  { index: 0x4, name: "Silver sword", type: 0x0 },
  { index: 0x5, name: "Iron blade", type: 0x0 },
  { index: 0x6, name: "Steel blade", type: 0x0 },
  { index: 0x7, name: "Silver blade", type: 0x0 },
  { index: 0x8, name: "Poison sword", type: 0x0 },
  { index: 0x9, name: "Rapier", type: 0x0 },
  { index: 0xa, name: "Mani Katti", type: 0x0 },
  { index: 0xb, name: "Brave sword", type: 0x0 },
  { index: 0xc, name: "Wo Dao", type: 0x0 },
  { index: 0xd, name: "Killing edge", type: 0x0 },
  { index: 0xe, name: "Armorslayer", type: 0x0 },
  { index: 0xf, name: "Wyrmslayer", type: 0x0 },
  { index: 0x10, name: "Light Brand", type: 0x0 },
  { index: 0x11, name: "Runesword", type: 0x0 },
  { index: 0x12, name: "Lancereaver", type: 0x0 },
  { index: 0x13, name: "Longsword", type: 0x0 },
  { index: 0x14, name: "Iron lance", type: 0x1 },
  { index: 0x15, name: "Slim lance", type: 0x1 },
  { index: 0x16, name: "Steel lance", type: 0x1 },
  { index: 0x17, name: "Silver lance", type: 0x1 },
  { index: 0x18, name: "Poison lance", type: 0x1 },
  { index: 0x19, name: "Brave lance", type: 0x1 },
  { index: 0x1a, name: "Killer lance", type: 0x1 },
  { index: 0x1b, name: "Horseslayer", type: 0x1 },
  { index: 0x1c, name: "Javelin", type: 0x1 },
  { index: 0x1d, name: "Spear", type: 0x1 },
  { index: 0x1e, name: "Axereaver", type: 0x1 },
  { index: 0x1f, name: "Iron axe", type: 0x2 },
  { index: 0x20, name: "Steel axe", type: 0x2 },
  { index: 0x21, name: "Silver axe", type: 0x2 },
  { index: 0x22, name: "Poison axe", type: 0x2 },
  { index: 0x23, name: "Brave axe", type: 0x2 },
  { index: 0x24, name: "Killer axe", type: 0x2 },
  { index: 0x25, name: "Halberd", type: 0x2 },
  { index: 0x26, name: "Hammer", type: 0x2 },
  { index: 0x27, name: "Devil axe", type: 0x2 },
  { index: 0x28, name: "Hand axe", type: 0x2 },
  { index: 0x29, name: "Tomahawk", type: 0x2 },
  { index: 0x2a, name: "Swordreaver", type: 0x2 },
  { index: 0x2b, name: "Swordslayer", type: 0x2 },
  { index: 0x2c, name: "Iron bow", type: 0x3 },
  { index: 0x2d, name: "Steel bow", type: 0x3 },
  { index: 0x2e, name: "Silver bow", type: 0x3 },
  { index: 0x2f, name: "Poison bow", type: 0x3 },
  { index: 0x30, name: "Killer bow", type: 0x3 },
  { index: 0x31, name: "Brave bow", type: 0x3 },
  { index: 0x32, name: "Short bow", type: 0x3 },
  { index: 0x33, name: "Longbow", type: 0x3 },
  { index: 0x34, name: "Ballista", type: 0x3 },
  { index: 0x35, name: "Iron ballista", type: 0x3 },
  { index: 0x36, name: "Killer ballista", type: 0x3 },
  { index: 0x37, name: "Fire", type: 0x4 },
  { index: 0x38, name: "Thunder", type: 0x4 },
  { index: 0x39, name: "Elfire", type: 0x4 },
  { index: 0x3a, name: "Bolting", type: 0x4 },
  { index: 0x3b, name: "Fimbulvetr", type: 0x4 },
  { index: 0x3c, name: "Forblaze", type: 0x4 },
  { index: 0x3d, name: "Excalibur", type: 0x4 },
  { index: 0x3e, name: "Lightning", type: 0x5 },
  { index: 0x3f, name: "Shine", type: 0x5 },
  { index: 0x40, name: "Divine", type: 0x5 },
  { index: 0x41, name: "Purge", type: 0x5 },
  { index: 0x42, name: "Aura", type: 0x5 },
  { index: 0x43, name: "Luce", type: 0x5 },
  { index: 0x44, name: "Flux", type: 0x6 },
  { index: 0x45, name: "Luna", type: 0x6 },
  { index: 0x46, name: "Nosferatu", type: 0x6 },
  { index: 0x47, name: "Eclipse", type: 0x6 },
  { index: 0x48, name: "Fenrir", type: 0x6 },
  { index: 0x49, name: "Gespenst", type: 0x6 },
  { index: 0x4a, name: "Heal", type: 0x7 },
  { index: 0x4b, name: "Mend", type: 0x7 },
  { index: 0x4c, name: "Recover", type: 0x7 },
  { index: 0x4d, name: "Physic", type: 0x7 },
  { index: 0x4e, name: "Fortify", type: 0x7 },
  { index: 0x4f, name: "Restore", type: 0x7 },
  { index: 0x50, name: "Silence", type: 0x7 },
  { index: 0x51, name: "Sleep", type: 0x7 },
  { index: 0x52, name: "Berserk", type: 0x7 },
  { index: 0x53, name: "Warp", type: 0x7 },
  { index: 0x54, name: "Rescue", type: 0x7 },
  { index: 0x55, name: "Torch", type: 0x7 },
  { index: 0x56, name: "Hammerne", type: 0x7 },
  { index: 0x57, name: "Unlock", type: 0x7 },
  { index: 0x58, name: "Barrier", type: 0x7 },
  { index: 0x59, name: "Dragon axe", type: 0x2 },
  { index: 0x5a, name: "Angelic robe", type: 0x8 },
  { index: 0x5b, name: "Energy ring", type: 0x8 },
  { index: 0x5c, name: "Secret book", type: 0x8 },
  { index: 0x5d, name: "Speedwings", type: 0x8 },
  { index: 0x5e, name: "Goddess icon", type: 0x8 },
  { index: 0x5f, name: "Dragonshield", type: 0x8 },
  { index: 0x60, name: "Talisman", type: 0x8 },
  { index: 0x61, name: "Boots", type: 0x8 },
  { index: 0x62, name: "Body ring", type: 0x8 },
  { index: 0x63, name: "Hero crest", type: 0x8 },
  { index: 0x64, name: "Knight crest", type: 0x8 },
  { index: 0x65, name: "Orion's bolt", type: 0x8 },
  { index: 0x66, name: "Elysian whip", type: 0x8 },
  { index: 0x67, name: "Guiding ring", type: 0x8 },
  { index: 0x68, name: "Chest key", type: 0x8 },
  { index: 0x69, name: "Door key", type: 0x8 },
  { index: 0x6a, name: "Lockpick", type: 0x8 },
  { index: 0x6b, name: "Vulnerary", type: 0x8 },
  { index: 0x6c, name: "Elixir", type: 0x8 },
  { index: 0x6d, name: "Pure water", type: 0x8 },
  { index: 0x6e, name: "Antitoxin", type: 0x8 },
  { index: 0x6f, name: "Torch", type: 0x8 },
  { index: 0x70, name: "Delphi shield", type: 0x8 },
  { index: 0x71, name: "Member card", type: 0x8 },
  { index: 0x72, name: "Silver card", type: 0x8 },
  { index: 0x73, name: "White gem", type: 0x8 },
  { index: 0x74, name: "Blue gem", type: 0x8 },
  { index: 0x75, name: "Red gem", type: 0x8 },
  { index: 0x76, name: "Gold", type: 0x8 },
  { index: 0x77, name: "Spear", type: 0x1 },
  { index: 0x78, name: "Chest key", type: 0x8 },
  { index: 0x79, name: "Mine", type: 0x8 },
  { index: 0x7a, name: "Light rune", type: 0x8 },
  { index: 0x7b, name: "Iron rune", type: 0x8 },
  { index: 0x7c, name: "Filla's Might", type: 0x8 },
  { index: 0x7d, name: "Nini's Grace", type: 0x8 },
  { index: 0x7e, name: "Thor's Ire", type: 0x8 },
  { index: 0x7f, name: "Set's Litany", type: 0x8 },
  { index: 0x80, name: "Emblem blade", type: 0x0 },
  { index: 0x81, name: "Emblem lance", type: 0x1 },
  { index: 0x82, name: "Emblem axe", type: 0x2 },
  { index: 0x83, name: "Emblem bow", type: 0x3 },
  { index: 0x84, name: "Durandal", type: 0x0 },
  { index: 0x85, name: "Armads", type: 0x2 },
  { index: 0x86, name: "Aureola", type: 0x5 },
  { index: 0x87, name: "Earth seal", type: 0x8 },
  { index: 0x88, name: "Afa's Drops", type: 0x8 },
  { index: 0x89, name: "Heaven seal", type: 0x8 },
  { index: 0x8a, name: "Emblem seal", type: 0x8 },
  { index: 0x8b, name: "Fell contract", type: 0x8 },
  { index: 0x8c, name: "Sol Katti", type: 0x0 },
  { index: 0x8d, name: "Wolf Beil", type: 0x2 },
  { index: 0x8e, name: "Ereshkigal", type: 0x6 },
  { index: 0x8f, name: "Flametongue", type: 0x8 },
  { index: 0x90, name: "Regal blade", type: 0x0 },
  { index: 0x91, name: "Rex Hasta", type: 0x1 },
  { index: 0x92, name: "Basilikos", type: 0x2 },
  { index: 0x93, name: "Rienfleche", type: 0x3 },
  { index: 0x94, name: "Heavy spear", type: 0x1 },
  { index: 0x95, name: "Short spear", type: 0x1 },
  { index: 0x96, name: "Ocean seal", type: 0x8 },
  { index: 0x97, name: "3,000 G", type: 0x8 },
  { index: 0x98, name: "5,000 G", type: 0x8 },
  { index: 0x99, name: "Wind sword", type: 0x0 },
];

export const items: Resource = {};

export const itemsGroups: ResourceGroups = itemTypes.map((type) => ({
  name: type.name,
  options: [],
}));

inventory.forEach((item) => {
  items[item.index] = item.name;
  itemsGroups[item.type].options.push(item.index);
});
