import type { Resource, ResourceGroups } from "$lib/types";

export const bestiary = [
  { id: "N3003", name: "001 Morte" },
  { id: "N3006", name: "002 Seama" },
  { id: "N3005", name: "003 Cannon Morte" },
  { id: "N3007", name: "004 Aello" },
  { id: "N3013", name: "005 Ghost" },
  { id: "N3015", name: "006 Dullahammer" },
  { id: "N3051", name: "007 Giant Rat" },
  { id: "N3004", name: "008 Bone Morte" },
  { id: "N3029", name: "009 Bat" },
  { id: "N3073", name: "010 Gieremund" },
  { id: "N3105", name: "011 Blood Grinder Knight" },
  { id: "N3080", name: "012 Sabnock" },
  { id: "N3066", name: "013 Moco Weed" },
  { id: "N3042", name: "014 Toad" },
  { id: "N3065", name: "015 Plume Parma" },
  { id: "N3011", name: "016 Barbatos" },
  { id: "N3091", name: "017 Carabosse" },
  { id: "N3034", name: "018 Simian" },
  { id: "N3075", name: "019 Zagan" },
  { id: "N3100", name: "020 Poltergeist" },
  { id: "N3104", name: "021 Ordog" },
  { id: "N3053", name: "022 Gagoyle" },
  { id: "N3079", name: "023 Killer Barber" },
  { id: "N3055", name: "024 Demon" },
  { id: "N3001", name: "025 Buer" },
  { id: "N3116", name: "026 Nyabon" },
  { id: "N3082", name: "027 Scythe Mite" },
  { id: "N3090", name: "028 Dullahammer Head" },
  { id: "N3084", name: "029 Buer Armor" },
  { id: "N2002", name: "030 Wolfman" },
  { id: "N3033", name: "031 Thunder Elemental" },
  { id: "N3017", name: "032 Carriage Morte" },
  { id: "N3063", name: "033 Dantalion" },
  { id: "N3103", name: "034 Rul'sha" },
  { id: "N3064", name: "035 Decarabia" },
  { id: "N3010", name: "036 Shovel Armor" },
  { id: "N3099", name: "037 Malediction" },
  { id: "N3008", name: "038 Celaeno" },
  { id: "N3111", name: "039 Shield Outsider" },
  { id: "N3114", name: "040 Puppy" },
  { id: "N3058", name: "041 Lili" },
  { id: "N3019", name: "042 Assassin" },
  { id: "N2009", name: "043 Dragon" },
  { id: "N3025", name: "044 Kunekune" },
  { id: "N3043", name: "045 Poison Toad" },
  { id: "N3092", name: "046 Sidhe" },
  { id: "N3024", name: "047 Bomber Morte" },
  { id: "N3070", name: "048 Mimic" },
  { id: "N3102", name: "049 Light Elemental" },
  { id: "N3009", name: "050 Ocypete" },
  { id: "N3087", name: "051 Cyhyraeth" },
  { id: "N3072", name: "052 Chair Mimic" },
  { id: "N3012", name: "053 Leraje" },
  { id: "N3052", name: "054 Bloodbringer" },
  { id: "N3085", name: "055 Lance Armor" },
  { id: "N3109", name: "056 Tamako-Death" },
  { id: "N3037", name: "057 Triwheel Buer" },
  { id: "N3077", name: "058 Gamigin" },
  { id: "N3093", name: "059 Titania" },
  { id: "N3110", name: "060 Axe Outsider" },
  { id: "N3098", name: "061 Scylla" },
  { id: "N3078", name: "062 Forneus" },
  { id: "N3022", name: "063 Deeseama" },
  { id: "N3044", name: "064 Water Leaper" },
  { id: "N3076", name: "065 Glashtyn" },
  { id: "N3089", name: "066 Seeker" },
  { id: "N3056", name: "067 Archdemon" },
  { id: "N3014", name: "068 Amy" },
  { id: "N3002", name: "069 Allocer" },
  { id: "N3112", name: "070 Vul'sha" },
  { id: "N2010", name: "071 Living Fossil" },
  { id: "N3115", name: "072 Rocky" },
  { id: "N3101", name: "073 Dark Elemental" },
  { id: "N3059", name: "074 Lamashtu" },
  { id: "N3113", name: "075 Macaron" },
  { id: "N3083", name: "076 Blood Bug" },
  { id: "N3032", name: "077 Fire Elemental" },
  { id: "N3119", name: "078 Volcano Morte" },
  { id: "N3123", name: "079 Hellhound" },
  { id: "N3086", name: "080 Zepar" },
  { id: "N3071", name: "081 Deathtrap" },
  { id: "N3035", name: "082 Gusion" },
  { id: "N3054", name: "083 Gaap" },
  { id: "N3074", name: "084 Haagenti" },
  { id: "N3117", name: "085 Kamikaze" },
  { id: "N3020", name: "086 Ninja" },
  { id: "N3067", name: "087 Giant Moco" },
  { id: "N3030", name: "088 Giant Bat" },
  { id: "N3045", name: "089 Giant Toad" },
  { id: "N3016", name: "090 Giant Cannon" },
  { id: "N3023", name: "091 Giant Morte" },
  { id: "N3028", name: "092 Giant Buer" },
  { id: "N3038", name: "093 Chariot Buer" },
  { id: "N3081", name: "094 Marbas" },
  { id: "N2003", name: "095 Silver Wolfman" },
  { id: "N2008", name: "096 Abyssal Guardian", isBoss: true },
  { id: "N3021", name: "097 Harrier" },
  { id: "N3031", name: "098 Ice Elemental" },
  { id: "N3088", name: "099 Tracer" },
  { id: "N3018", name: "100 Gusion Cannon" },
  { id: "N3120", name: "101 G Axe Outsider" },
  { id: "N3057", name: "102 Demon Lord" },
  { id: "N3121", name: "103 Eight Bit Zombie" },
  { id: "N3122", name: "104 Eight Bit Ghost" },
  { id: "N3124", name: "105 Eight Bit Skull" },
  { id: "N2015", name: "106 Eight Bit Overlord", isBoss: true },
  { id: "N3106", name: "107 Master Carpenter", isBoss: true },
  { id: "N3107", name: "108 Revenant", isBoss: true },
  { id: "N3108", name: "109 Millionaire's Bane", isBoss: true },
  { id: "N1001", name: "110 Vepar", isBoss: true },
  { id: "N1011", name: "111 Zangetsu", isBoss: true },
  { id: "N1003", name: "112 Craftwork", isBoss: true },
  { id: "N2004", name: "113 Andrealphus", isBoss: true },
  { id: "N1005", name: "114 Valac", isBoss: true },
  { id: "N2001", name: "115 Glutton Train", isBoss: true },
  { id: "N1006", name: "116 Bathin", isBoss: true },
  { id: "N1012", name: "117 Gebel", isBoss: true },
  { id: "N1002", name: "118 Bloodless", isBoss: true },
  { id: "N2014", name: "119 Alfred", isBoss: true },
  { id: "N2007", name: "120 Doppelganger", isBoss: true },
  { id: "N2006", name: "121 Orobas", isBoss: true },
  { id: "N1011_STRONG", name: "122 Zangetsu", isBoss: true },
  { id: "N1004", name: "123 Valefar", isBoss: true },
  { id: "N1008", name: "124 Gremory", isBoss: true },
  { id: "N1009_Enemy", name: "125 Dominique" },
  { id: "N1013_Bael", name: "126 Bael" },
  { id: "N2012", name: "127 Orlok Dracule", isBoss: true },
];

export const itemTypes = [
  { index: 0x0, location: 0x0, name: "Weapons", max: 99 },
  { index: 0x1, location: 0x1, name: "Bullets", max: 999 },
  { index: 0x2, location: 0x3, name: "Heads", max: 99 },
  { index: 0x3, location: 0x2, name: "Bodies", max: 99 },
  { index: 0x4, location: 0x4, name: "Accessories", max: 99 },
  { index: 0x5, location: 0x5, name: "Scarfs", max: 99 },
  { index: 0x6, location: 0x6, name: "Potions", max: 9 },
  { index: 0x7, location: 0x6, name: "Foods", max: 99 },
  { index: 0x8, location: 0x7, name: "Ingredients", max: 99 },
  { index: 0x9, location: 0x7, name: "Materials", max: 99 },
  { index: 0xa, location: 0x8, name: "Key Items", max: 1 },
  { index: 0xb, location: 0x9, name: "Books", max: 1 },
];

export const weaponTypes = [
  { index: 0x0, name: "Shoes" },
  { index: 0x1, name: "Daggers" },
  { index: 0x2, name: "Rapiers" },
  { index: 0x3, name: "Swords" },
  { index: 0x4, name: "Clubs" },
  { index: 0x5, name: "Greatswords" },
  { index: 0x6, name: "Katanas" },
  { index: 0x7, name: "Spears" },
  { index: 0x8, name: "Whips" },
  { index: 0x9, name: "Firearms" },
];

export const shardTypes = [
  { index: 0x0, location: 0xa, possessionIndex: 0x0, name: "Conjure" },
  { index: 0x1, location: 0xb, possessionIndex: 0x3, name: "Manipulative" },
  { index: 0x2, location: 0xc, possessionIndex: 0x1, name: "Directional" },
  { index: 0x3, location: 0xd, possessionIndex: 0x4, name: "Passive" },
  { index: 0x4, location: 0xe, possessionIndex: 0x2, name: "Familiar" },
  { index: 0x5, location: 0xf, possessionIndex: 0x5, name: "Skill" },
];

// prettier-ignore
export const itemList = [
  { id: "KungFuShoes"            , type: 0x0, subtype: 0x0, name: "Kung Fu Shoes" },
  { id: "BattleBoots"            , type: 0x0, subtype: 0x0, name: "Battle Boots" },
  { id: "KillerBoots"            , type: 0x0, subtype: 0x0, name: "Lethal Boots" },
  { id: "Toyshoes"               , type: 0x0, subtype: 0x0, name: "Toy Shoes" },
  { id: "Assaultsollette"        , type: 0x0, subtype: 0x0, name: "Steam Boots" },
  { id: "Rabbitboots"            , type: 0x0, subtype: 0x0, name: "Bunny Boots" },
  { id: "Dragonshoes"            , type: 0x0, subtype: 0x0, name: "Dragon Shoes" },
  { id: "Hermesshoes"            , type: 0x0, subtype: 0x0, name: "Hermes Shoes" },
  { id: "Decapitator"            , type: 0x0, subtype: 0x0, name: "Hell's Knells" },
  { id: "Knife"                  , type: 0x0, subtype: 0x1, name: "Knife" },
  { id: "Baselard"               , type: 0x0, subtype: 0x1, name: "Baselard" },
  { id: "Kukuri"                 , type: 0x0, subtype: 0x1, name: "Kukri" },
  { id: "PoisonKukri"            , type: 0x0, subtype: 0x1, name: "Poison Kukri" },
  { id: "Swordbreaker"           , type: 0x0, subtype: 0x1, name: "Swordbreaker" },
  { id: "ManGauche"              , type: 0x0, subtype: 0x1, name: "Main Gauche" },
  { id: "Calnwenan"              , type: 0x0, subtype: 0x1, name: "Carnwennan" },
  { id: "Mandaupasar"            , type: 0x0, subtype: 0x1, name: "Mandau Pasir" },
  { id: "Rapier"                 , type: 0x0, subtype: 0x2, name: "Rapier" },
  { id: "Epe"                    , type: 0x0, subtype: 0x2, name: "Epée" },
  { id: "Stinger"                , type: 0x0, subtype: 0x2, name: "Stinger" },
  { id: "Miserikorde"            , type: 0x0, subtype: 0x2, name: "Misericorde" },
  { id: "Cazilk"                 , type: 0x0, subtype: 0x2, name: "Kazikli" },
  { id: "Juwuse"                 , type: 0x0, subtype: 0x2, name: "Joyeuse" },
  { id: "ShortSword"             , type: 0x0, subtype: 0x3, name: "Short Sword" },
  { id: "LongSword"              , type: 0x0, subtype: 0x3, name: "Long Sword" },
  { id: "WolfBalt"               , type: 0x0, subtype: 0x3, name: "Ulfberht Sword" },
  { id: "invisible"              , type: 0x0, subtype: 0x3, name: "Invisible Blade" },
  { id: "Halper"                 , type: 0x0, subtype: 0x3, name: "Harpé" },
  { id: "Mulgres"                , type: 0x0, subtype: 0x3, name: "Murgleis" },
  { id: "Redumbrella"            , type: 0x0, subtype: 0x3, name: "Red Umbrella" },
  { id: "Burtgang"               , type: 0x0, subtype: 0x3, name: "Blutgang" },
  { id: "Flagarach"              , type: 0x0, subtype: 0x3, name: "Fragarach" },
  { id: "Hoffdo"                 , type: 0x0, subtype: 0x3, name: "Hofud" },
  { id: "Dineslave"              , type: 0x0, subtype: 0x3, name: "Dáinsleif" },
  { id: "Florenberg"             , type: 0x0, subtype: 0x3, name: "Florenberg" },
  { id: "Armas"                  , type: 0x0, subtype: 0x3, name: "Almace" },
  { id: "Caradoborg"             , type: 0x0, subtype: 0x3, name: "Caladbolg" },
  { id: "Liddyl"                 , type: 0x0, subtype: 0x3, name: "Ridill" },
  { id: "HuntedBrad"             , type: 0x0, subtype: 0x3, name: "Bandit Blade" },
  { id: "Broadsword"             , type: 0x0, subtype: 0x3, name: "Blue Rose" },
  { id: "SwordWhip"              , type: 0x0, subtype: 0x3, name: "Sword Whip" },
  { id: "BradBlingerLv1"         , type: 0x0, subtype: 0x3, name: "Bloodbringer" },
  { id: "ValkyrieSword"          , type: 0x0, subtype: 0x3, name: "Valkyrie Sword" },
  { id: "Mace"                   , type: 0x0, subtype: 0x4, name: "Mace" },
  { id: "Morgenstern"            , type: 0x0, subtype: 0x4, name: "Morgenstern" },
  { id: "McAutil"                , type: 0x0, subtype: 0x4, name: "Macuahuitl" },
  { id: "Yagurushi"              , type: 0x0, subtype: 0x4, name: "Yagrush" },
  { id: "Aimur"                  , type: 0x0, subtype: 0x4, name: "Ayamur" },
  { id: "Charwell"               , type: 0x0, subtype: 0x4, name: "Sharur" },
  { id: "Mistrutein"             , type: 0x0, subtype: 0x4, name: "Mistilteinn" },
  { id: "RemoteDart"             , type: 0x0, subtype: 0x3, name: "Flying Edge" },
  { id: "OracleBlade"            , type: 0x0, subtype: 0x3, name: "Oracle Blade" },
  { id: "WalalSoulimo"           , type: 0x0, subtype: 0x3, name: "Rhava Búral" },
  { id: "ValralAltar"            , type: 0x0, subtype: 0x3, name: "Rhava Velar" },
  { id: "Claymore"               , type: 0x0, subtype: 0x5, name: "Claymore" },
  { id: "Perex"                  , type: 0x0, subtype: 0x5, name: "Pelekus" },
  { id: "Flanders"               , type: 0x0, subtype: 0x5, name: "Flamberge" },
  { id: "OutsiderKnightSword"    , type: 0x0, subtype: 0x5, name: "Spiral Sword" },
  { id: "Valdish"                , type: 0x0, subtype: 0x5, name: "Berdiche" },
  { id: "SteamFlatWideEnd"       , type: 0x0, subtype: 0x5, name: "Carnot's Rebuke" },
  { id: "Gram"                   , type: 0x0, subtype: 0x5, name: "Gram" },
  { id: "Gambanttain"            , type: 0x0, subtype: 0x5, name: "Gambanteinn" },
  { id: "Lohengrin"              , type: 0x0, subtype: 0x5, name: "Lohengrin" },
  { id: "Sherdar"                , type: 0x0, subtype: 0x5, name: "Schedar" },
  { id: "LightningBolt"          , type: 0x0, subtype: 0x5, name: "Steel Lightning" },
  { id: "Karadanda"              , type: 0x0, subtype: 0x5, name: "Kaladanda" },
  { id: "Durandal"               , type: 0x0, subtype: 0x5, name: "Durandal" },
  { id: "DiesIle"                , type: 0x0, subtype: 0x5, name: "Dies Irae" },
  { id: "TurmericBasara"         , type: 0x0, subtype: 0x5, name: "Ukonvasara" },
  { id: "Exactor"                , type: 0x0, subtype: 0x5, name: "Eternal Blue" },
  { id: "Dull"                   , type: 0x0, subtype: 0x6, name: "Dull Blade" },
  { id: "Noda"                   , type: 0x0, subtype: 0x6, name: "Nodachi" },
  { id: "Tsurumaru"              , type: 0x0, subtype: 0x6, name: "Tsurumaru" },
  { id: "ShiroTorujiro"          , type: 0x0, subtype: 0x6, name: "Honebami" },
  { id: "Lightningoff"           , type: 0x0, subtype: 0x6, name: "Raikiri" },
  { id: "OgreWoodenSword"        , type: 0x0, subtype: 0x6, name: "Swordfish" },
  { id: "Tadanako"               , type: 0x0, subtype: 0x6, name: "Dojigiri" },
  { id: "Swordsman"              , type: 0x0, subtype: 0x6, name: "Zangetsuto" },
  { id: "MikazukiMaen"           , type: 0x0, subtype: 0x6, name: "Mikazuki" },
  { id: "Truesixteenthnight"     , type: 0x0, subtype: 0x6, name: "Grand Izayoi" },
  { id: "Spear"                  , type: 0x0, subtype: 0x7, name: "Spear" },
  { id: "Reims"                  , type: 0x0, subtype: 0x7, name: "Lance" },
  { id: "Partizan"               , type: 0x0, subtype: 0x7, name: "Partisan" },
  { id: "Excavator"              , type: 0x0, subtype: 0x7, name: "Shovel" },
  { id: "Triplet"                , type: 0x0, subtype: 0x7, name: "Sanjiegun" },
  { id: "ShingoGempo"            , type: 0x0, subtype: 0x7, name: "Gondo-Shizunori" },
  { id: "Coldgrindingsaw"        , type: 0x0, subtype: 0x7, name: "Leng Yan Ju" },
  { id: "Aradovar"               , type: 0x0, subtype: 0x7, name: "Areadbhar" },
  { id: "Nibbleheim"             , type: 0x0, subtype: 0x7, name: "Niflheim" },
  { id: "GunungNil"              , type: 0x0, subtype: 0x7, name: "Gungnir" },
  { id: "Gayalsals"              , type: 0x0, subtype: 0x7, name: "Gae Assail" },
  { id: "Awhip"                  , type: 0x0, subtype: 0x8, name: "Whip" },
  { id: "Ibarakaswhip"           , type: 0x0, subtype: 0x8, name: "Thorn Whip" },
  { id: "FireWhip"               , type: 0x0, subtype: 0x8, name: "Flame Whip" },
  { id: "BlackRockHell"          , type: 0x0, subtype: 0x8, name: "Black Cords" },
  { id: "Snakebyte"              , type: 0x0, subtype: 0x8, name: "Snakebite" },
  { id: "BeastKiller"            , type: 0x0, subtype: 0x8, name: "Beast Killer" },
  { id: "Albireo"                , type: 0x0, subtype: 0x8, name: "Albireo" },
  { id: "Andromeda"              , type: 0x0, subtype: 0x8, name: "Andromeda" },
  { id: "Musketon"               , type: 0x0, subtype: 0x9, name: "Musketoon" },
  { id: "Branderbus"             , type: 0x0, subtype: 0x9, name: "Blunderbuss" },
  { id: "Tanegasima"             , type: 0x0, subtype: 0x9, name: "Tanegashima" },
  { id: "Trador"                 , type: 0x0, subtype: 0x9, name: "Toradar" },
  { id: "Carvalin"               , type: 0x0, subtype: 0x9, name: "Culverin" },
  { id: "Betelgeuse"             , type: 0x0, subtype: 0x9, name: "Betelgeuse" },
  { id: "Ursula"                 , type: 0x0, subtype: 0x9, name: "Verethragna" },
  { id: "Adrastea"               , type: 0x0, subtype: 0x9, name: "Adrasteia" },
  { id: "SacredSword"            , type: 0x0, subtype: 0x5, name: "Dawn Blade" },
  { id: "SacredSword2"           , type: 0x0, subtype: 0x5, name: "Dawn Blade +1" },
  { id: "SacredSword3"           , type: 0x0, subtype: 0x5, name: "Dawn Blade +2" },
  { id: "CoolShoesOfMrNarita"    , type: 0x0, subtype: 0x0, name: "Blue Skies" },
  { id: "CoolShoesOfMrNarita2"   , type: 0x0, subtype: 0x0, name: "Blue Skies +1" },
  { id: "CoolShoesOfMrNarita3"   , type: 0x0, subtype: 0x0, name: "Blue Skies +2" },
  { id: "IceSlewShoes"           , type: 0x0, subtype: 0x0, name: "Boreal Rime Boots" },
  { id: "IceSlewShoes2"          , type: 0x0, subtype: 0x0, name: "Boreal Rime Boots +1" },
  { id: "IceSlewShoes3"          , type: 0x0, subtype: 0x0, name: "Boreal Rime Boots +2" },
  { id: "PoisonSpikeShoes"       , type: 0x0, subtype: 0x0, name: "Oleanders" },
  { id: "PoisonSpikeShoes2"      , type: 0x0, subtype: 0x0, name: "Oleanders +1" },
  { id: "PoisonSpikeShoes3"      , type: 0x0, subtype: 0x0, name: "Oleanders +2" },
  { id: "ShieldWeapon"           , type: 0x0, subtype: 0x3, name: "Shield Weapon" },
  { id: "ShieldWeapon2"          , type: 0x0, subtype: 0x3, name: "Shield Weapon +1" },
  { id: "ShieldWeapon3"          , type: 0x0, subtype: 0x3, name: "Shield Weapon +2" },
  { id: "LightSaber"             , type: 0x0, subtype: 0x3, name: "Encrypted Orchid" },
  { id: "LightSaber2"            , type: 0x0, subtype: 0x3, name: "Encrypted Orchid +1" },
  { id: "LightSaber3"            , type: 0x0, subtype: 0x3, name: "Encrypted Orchid +2" },
  { id: "JodoSwordLight"         , type: 0x0, subtype: 0x3, name: "Hikari" },
  { id: "JodoSwordLight2"        , type: 0x0, subtype: 0x3, name: "Hikari +1" },
  { id: "JodoSwordLight3"        , type: 0x0, subtype: 0x3, name: "Hikari +2" },
  { id: "SpearCutDownAside"      , type: 0x0, subtype: 0x3, name: "Moonwake" },
  { id: "SpearCutDownAside2"     , type: 0x0, subtype: 0x3, name: "Moonwake +1" },
  { id: "SpearCutDownAside3"     , type: 0x0, subtype: 0x3, name: "Moonwake +2" },
  { id: "XrossBrade"             , type: 0x0, subtype: 0x3, name: "Gold Cross" },
  { id: "XrossBrade2"            , type: 0x0, subtype: 0x3, name: "Gold Cross +1" },
  { id: "XrossBrade3"            , type: 0x0, subtype: 0x3, name: "Gold Cross +2" },
  { id: "BradeOfEU"              , type: 0x0, subtype: 0x3, name: "Eu's Sword" },
  { id: "BradeOfEU2"             , type: 0x0, subtype: 0x3, name: "Eu's Sword +1" },
  { id: "BradeOfEU3"             , type: 0x0, subtype: 0x3, name: "Eu's Sword +2" },
  { id: "CrystalSword"           , type: 0x0, subtype: 0x2, name: "Redbeast's Edge" },
  { id: "CrystalSword2"          , type: 0x0, subtype: 0x2, name: "Redbeast's Edge +1" },
  { id: "CrystalSword3"          , type: 0x0, subtype: 0x2, name: "Redbeast's Edge +2" },
  { id: "StickOfMagiGirl"        , type: 0x0, subtype: 0x4, name: "Prismatic Heart" },
  { id: "StickOfMagiGirl2"       , type: 0x0, subtype: 0x4, name: "Prismatic Heart +1" },
  { id: "StickOfMagiGirl3"       , type: 0x0, subtype: 0x4, name: "Prismatic Heart +2" },
  { id: "DeathBringer"           , type: 0x0, subtype: 0x5, name: "Deathbringer" },
  { id: "DeathBringer2"          , type: 0x0, subtype: 0x5, name: "Deathbringer +1" },
  { id: "DeathBringer3"          , type: 0x0, subtype: 0x5, name: "Deathbringer +2" },
  { id: "ChargeWideEnd"          , type: 0x0, subtype: 0x5, name: "Claw of Onmoraki" },
  { id: "ChargeWideEnd2"         , type: 0x0, subtype: 0x5, name: "Claw of Onmoraki +1" },
  { id: "ChargeWideEnd3"         , type: 0x0, subtype: 0x5, name: "Claw of Onmoraki +2" },
  { id: "DrillWideEnd"           , type: 0x0, subtype: 0x5, name: "Blood Grinder" },
  { id: "DrillWideEnd2"          , type: 0x0, subtype: 0x5, name: "Blood Grinder +1" },
  { id: "DrillWideEnd3"          , type: 0x0, subtype: 0x5, name: "Blood Grinder +2" },
  { id: "PetrifactionSword"      , type: 0x0, subtype: 0x5, name: "Silent Calamity" },
  { id: "PetrifactionSword2"     , type: 0x0, subtype: 0x5, name: "Silent Calamity +1" },
  { id: "PetrifactionSword3"     , type: 0x0, subtype: 0x5, name: "Silent Calamity +2" },
  { id: "IcePillarSpear"         , type: 0x0, subtype: 0x7, name: "Sculptor's Chisel" },
  { id: "IcePillarSpear2"        , type: 0x0, subtype: 0x7, name: "Sculptor's Chisel +1" },
  { id: "IcePillarSpear3"        , type: 0x0, subtype: 0x7, name: "Sculptor's Chisel +2" },
  { id: "LoveOfFairyDragon"      , type: 0x0, subtype: 0x7, name: "Black Dragon's Ode" },
  { id: "LoveOfFairyDragon2"     , type: 0x0, subtype: 0x7, name: "Black Dragon's Ode +1" },
  { id: "LoveOfFairyDragon3"     , type: 0x0, subtype: 0x7, name: "Black Dragon's Ode +2" },
  { id: "TrustMusket"            , type: 0x0, subtype: 0x9, name: "Renee's Requiem" },
  { id: "TrustMusket2"           , type: 0x0, subtype: 0x9, name: "Renee's Requiem +1" },
  { id: "TrustMusket3"           , type: 0x0, subtype: 0x9, name: "Renee's Requiem +2" },
  { id: "WhipsOfLightDarkness"   , type: 0x0, subtype: 0x8, name: "Ambivalence" },
  { id: "WhipsOfLightDarkness2"  , type: 0x0, subtype: 0x8, name: "Ambivalence +1" },
  { id: "WhipsOfLightDarkness3"  , type: 0x0, subtype: 0x8, name: "Ambivalence +2" },
  { id: "ClockSowrd"             , type: 0x0, subtype: 0x3, name: "Final Hour" },
  { id: "LoveOfPizza"            , type: 0x0, subtype: 0x3, name: "Sicilian Slicer" },
  { id: "KongSword"              , type: 0x0, subtype: 0x3, name: "Clockwork Blade" },
  { id: "SwordOfTheMushroom"     , type: 0x0, subtype: 0x3, name: "Vine Sword" },
  { id: "PowerSword"             , type: 0x0, subtype: 0x3, name: "Game Sack Strip" },
  { id: "SilverAndBlackSword"    , type: 0x0, subtype: 0x3, name: "Darkness Descends" },
  { id: "DungeonNightSword"      , type: 0x0, subtype: 0x3, name: "Dungeonite Sword" },
  { id: "EvilTheSword"           , type: 0x0, subtype: 0x3, name: "Dominus" },
  { id: "Scythe"                 , type: 0x0, subtype: 0x7, name: "Scythe" },
  { id: "Scythe1"                , type: 0x0, subtype: 0x7, name: "Scythe +1" },
  { id: "Scythe2"                , type: 0x0, subtype: 0x7, name: "Scythe +2" },
  { id: "Scythe3"                , type: 0x0, subtype: 0x7, name: "Scythe +3" },
  { id: "Scythe4"                , type: 0x0, subtype: 0x7, name: "Scythe +4" },
  { id: "MagicalScepter"         , type: 0x0, subtype: 0x9, name: "Miri Scepter" },
  { id: "MagicalScepter1"        , type: 0x0, subtype: 0x9, name: "Miri Scepter +1" },
  { id: "MagicalScepter2"        , type: 0x0, subtype: 0x9, name: "Miri Scepter +2" },
  { id: "MagicalScepter3"        , type: 0x0, subtype: 0x9, name: "Miri Scepter +3" },
  { id: "MagicalScepter4"        , type: 0x0, subtype: 0x9, name: "Miri Scepter +4" },
  { id: "PirateSword1"           , type: 0x0, subtype: 0x3, name: "Risky Blade" },
  { id: "PirateSword2"           , type: 0x0, subtype: 0x3, name: "Risky Blade +1" },
  { id: "PirateSword3"           , type: 0x0, subtype: 0x3, name: "Risky Blade +2" },
  { id: "PirateSword4"           , type: 0x0, subtype: 0x3, name: "Risky Blade +3" },
  { id: "PirateSword5"           , type: 0x0, subtype: 0x3, name: "Risky Blade +4" },
  { id: "PirateGun1"             , type: 0x0, subtype: 0x9, name: "Risky Pistol" },
  { id: "PirateGun2"             , type: 0x0, subtype: 0x9, name: "Risky Pistol +1" },
  { id: "PirateGun3"             , type: 0x0, subtype: 0x9, name: "Risky Pistol +2" },
  { id: "PirateGun4"             , type: 0x0, subtype: 0x9, name: "Risky Pistol +3" },
  { id: "PirateGun5"             , type: 0x0, subtype: 0x9, name: "Risky Pistol +4" },
  { id: "Wagasa"                 , type: 0x0, subtype: 0x3, name: "Japanesque Umbrella" },
  { id: "Wagasa1"                , type: 0x0, subtype: 0x3, name: "Japanesque Umbrella +1" },
  { id: "Wagasa2"                , type: 0x0, subtype: 0x3, name: "Japanesque Umbrella +2" },
  { id: "Wagasa3"                , type: 0x0, subtype: 0x3, name: "Japanesque Umbrella +3" },
  { id: "Wagasa4"                , type: 0x0, subtype: 0x3, name: "Japanesque Umbrella +4" },
  { id: "Softpoint"              , type: 0x1              , name: "SP Rounds" },
  { id: "Hollowpoint"            , type: 0x1              , name: "HP Rounds" },
  { id: "ArmorPiercing"          , type: 0x1              , name: "AP Rounds" },
  { id: "Firebullet"             , type: 0x1              , name: "Flame Rounds" },
  { id: "Icebullet"              , type: 0x1              , name: "Ice Rounds" },
  { id: "ThunderRounds"          , type: 0x1              , name: "Thunder Rounds" },
  { id: "SilverBullets"          , type: 0x1              , name: "Silver Bullets" },
  { id: "WeaponbaneRounds"       , type: 0x1              , name: "Weaponbane Rounds" },
  { id: "ShieldbaneRounds"       , type: 0x1              , name: "Shieldbane Rounds" },
  { id: "PoisonRounds"           , type: 0x1              , name: "Poison Rounds" },
  { id: "PetrifyingRounds"       , type: 0x1              , name: "Petrifying Rounds" },
  { id: "CurseRounds"            , type: 0x1              , name: "Curse Rounds" },
  { id: "Shotshell"              , type: 0x1              , name: "Scattershot" },
  { id: "CriticalBullet"         , type: 0x1              , name: "Critical Rounds" },
  { id: "DiamondBullets"         , type: 0x1              , name: "Diamond Bullets" },
  { id: "AriesHorns"             , type: 0x2              , name: "Aries' Horns" },
  { id: "Headband"               , type: 0x2              , name: "Hairband" },
  { id: "PirateTriangleCap"      , type: 0x2              , name: "Pirate Hat" },
  { id: "DurahanMaherm"          , type: 0x2              , name: "Dullahammer Helm" },
  { id: "Circlet"                , type: 0x2              , name: "Circlet" },
  { id: "Garbohat"               , type: 0x2              , name: "Garbo Hat" },
  { id: "Santacap"               , type: 0x2              , name: "Santa Hat" },
  { id: "Beastberet"             , type: 0x2              , name: "Beast Beret" },
  { id: "CatEars"                , type: 0x2              , name: "Cat Ears" },
  { id: "CowboyHat"              , type: 0x2              , name: "Cowboy Hat" },
  { id: "WolfHood"               , type: 0x2              , name: "Wolf Hood" },
  { id: "Circletoffire"          , type: 0x2              , name: "Flame Circlet" },
  { id: "Icecirclet"             , type: 0x2              , name: "Ice Circlet" },
  { id: "Thunderscirclet"        , type: 0x2              , name: "Thunder Circlet" },
  { id: "FeatherCrown"           , type: 0x2              , name: "Feather Crown" },
  { id: "BraveBeret"             , type: 0x2              , name: "Beret of Bravery" },
  { id: "Crowhat"                , type: 0x2              , name: "Crow Hat" },
  { id: "GadgetBand"             , type: 0x2              , name: "Gadget Band" },
  { id: "SilverTiara"            , type: 0x2              , name: "Silver Tiara" },
  { id: "Magushat"               , type: 0x2              , name: "Witch's Hat" },
  { id: "Cutebeastberet"         , type: 0x2              , name: "Cute Beast Beret" },
  { id: "BunnyEars"              , type: 0x2              , name: "Bunny Ears" },
  { id: "Dentistshat"            , type: 0x2              , name: "Diabolist's Cap" },
  { id: "Maidheadband"           , type: 0x2              , name: "Maid's Hairband" },
  { id: "Westernhat"             , type: 0x2              , name: "Gunslinger's Hat" },
  { id: "Ribbon"                 , type: 0x2              , name: "Ribbon" },
  { id: "Flightcapoftraveler"    , type: 0x2              , name: "Traveler's Hat" },
  { id: "HermitsBeret"           , type: 0x2              , name: "Hermit's Beret" },
  { id: "KitsuneMask"            , type: 0x2              , name: "Kitsune Mask" },
  { id: "DemonHorns"             , type: 0x2              , name: "Demon Horns" },
  { id: "ElderTiara"             , type: 0x2              , name: "Ancient Tiara" },
  { id: "Recyclehat"             , type: 0x2              , name: "Recycle Hat" },
  { id: "Pleiades"               , type: 0x2              , name: "Pleiades" },
  { id: "ValkyrieTiara"          , type: 0x2              , name: "Valkyrie Tiara" },
  { id: "HumptyDumpty"           , type: 0x2              , name: "Guardian Egg Helm" },
  { id: "LoveOfBenki"            , type: 0x2              , name: "Dumping Helmet" },
  { id: "Plan9FOSpace"           , type: 0x2              , name: "Space Helmet" },
  { id: "Mega64Head"             , type: 0x2              , name: "Mega64 Helmet" },
  { id: "MonarchCrown"           , type: 0x2              , name: "Crown of Creation" },
  { id: "AlluringHorns"          , type: 0x2              , name: "Vampiric Wig" },
  { id: "MagicalGirlHead"        , type: 0x2              , name: "Miri Wig" },
  { id: "ShantaeBandana"         , type: 0x2              , name: "Risky Bandana" },
  { id: "Kanzashi"               , type: 0x2              , name: "Japanesque Wig" },
  { id: "Tunic"                  , type: 0x3              , name: "Tunic" },
  { id: "Skinbreastplate"        , type: 0x3              , name: "Leather Chestguard" },
  { id: "Countrydress"           , type: 0x3              , name: "Country Dress" },
  { id: "Copperbreastplate"      , type: 0x3              , name: "Bronze Chestguard" },
  { id: "Chemisedress"           , type: 0x3              , name: "Chemise" },
  { id: "Scalearmor"             , type: 0x3              , name: "Scale Armor" },
  { id: "Ironbreastplate"        , type: 0x3              , name: "Iron Breastplate" },
  { id: "Brigandine"             , type: 0x3              , name: "Brigandine" },
  { id: "IronMansApron"          , type: 0x3              , name: "Apron" },
  { id: "KungFuBest"             , type: 0x3              , name: "Kung Fu Vest" },
  { id: "Teadress"               , type: 0x3              , name: "Tea Dress" },
  { id: "Chainmail"              , type: 0x3              , name: "Chainmail" },
  { id: "Beastleather"           , type: 0x3              , name: "Hound Vest" },
  { id: "Maturedress"            , type: 0x3              , name: "Mantua" },
  { id: "Shovelarmorsarmor"      , type: 0x3              , name: "Ex Shovel Armor" },
  { id: "LamellarArmor"          , type: 0x3              , name: "Lamellar Armor" },
  { id: "CrusadeArmor"           , type: 0x3              , name: "Crusader's Armor" },
  { id: "Steelbreastplate"       , type: 0x3              , name: "Steel Breastplate" },
  { id: "RidingHabit"            , type: 0x3              , name: "Riding Habit" },
  { id: "DuelBrest"              , type: 0x3              , name: "Duelist's Guard" },
  { id: "Silverbreastplate"      , type: 0x3              , name: "Silver Breastplate" },
  { id: "Assassinvest"           , type: 0x3              , name: "Assassin's Vest" },
  { id: "Featherrobe"            , type: 0x3              , name: "Feather Robe" },
  { id: "VoronezDress"           , type: 0x3              , name: "Polonaise" },
  { id: "Cureus"                 , type: 0x3              , name: "Knight's Cuirass" },
  { id: "Crystalscale"           , type: 0x3              , name: "Crystal Armor" },
  { id: "BreastplateofAguilar"   , type: 0x3              , name: "Aegis Plate" },
  { id: "DragonScale"            , type: 0x3              , name: "Dragon Armor" },
  { id: "Goldbreastplate"        , type: 0x3              , name: "Gold Breastplate" },
  { id: "SpikeBreast"            , type: 0x3              , name: "Spiked Breastplate" },
  { id: "Silkdress"              , type: 0x3              , name: "Silk Dress" },
  { id: "GloriousBreast"         , type: 0x3              , name: "Majestic Plate" },
  { id: "ShiningBreast"          , type: 0x3              , name: "Flame Mail" },
  { id: "Ashinbacostume"         , type: 0x3              , name: "Shinobi Garb" },
  { id: "Caracilis"              , type: 0x3              , name: "Kalasiris" },
  { id: "Crimsondress"           , type: 0x3              , name: "Scarlet Dress" },
  { id: "ImperialArmor"          , type: 0x3              , name: "Imperial Armor" },
  { id: "Shieldless"             , type: 0x3              , name: "Tatenashi" },
  { id: "Coronationdress"        , type: 0x3              , name: "Coronation Gown" },
  { id: "Valkyriedress"          , type: 0x3              , name: "Valkyrie Dress" },
  { id: "VampiricSkinsuit"       , type: 0x3              , name: "Vampiric Skinsuit" },
  { id: "VampiricSkinsuit1"      , type: 0x3              , name: "Vampiric Skinsuit +1" },
  { id: "VampiricSkinsuit2"      , type: 0x3              , name: "Vampiric Skinsuit +2" },
  { id: "VampiricSkinsuit3"      , type: 0x3              , name: "Vampiric Skinsuit +3" },
  { id: "VampiricSkinsuit4"      , type: 0x3              , name: "Vampiric Skinsuit +4" },
  { id: "VampiricSkinsuit5"      , type: 0x3              , name: "Vampiric Skinsuit +5" },
  { id: "MagicalGirlBody"        , type: 0x3              , name: "Miri Dress" },
  { id: "MagicalGirlBody1"       , type: 0x3              , name: "Miri Dress +1" },
  { id: "MagicalGirlBody2"       , type: 0x3              , name: "Miri Dress +2" },
  { id: "MagicalGirlBody3"       , type: 0x3              , name: "Miri Dress +3" },
  { id: "MagicalGirlBody4"       , type: 0x3              , name: "Miri Dress +4" },
  { id: "MagicalGirlBody5"       , type: 0x3              , name: "Miri Dress +5" },
  { id: "ShantaeOutfit1"         , type: 0x3              , name: "Half-Genie Outfit" },
  { id: "ShantaeOutfit2"         , type: 0x3              , name: "Half-Genie Outfit +1" },
  { id: "ShantaeOutfit3"         , type: 0x3              , name: "Half-Genie Outfit +2" },
  { id: "ShantaeOutfit4"         , type: 0x3              , name: "Half-Genie Outfit +3" },
  { id: "ShantaeOutfit5"         , type: 0x3              , name: "Half-Genie Outfit +4" },
  { id: "ShantaeOutfit6"         , type: 0x3              , name: "Half-Genie Outfit +5" },
  { id: "FestivalKimono"         , type: 0x3              , name: "Japanesque Robe" },
  { id: "FestivalKimono1"        , type: 0x3              , name: "Japanesque Robe +1" },
  { id: "FestivalKimono2"        , type: 0x3              , name: "Japanesque Robe +2" },
  { id: "FestivalKimono3"        , type: 0x3              , name: "Japanesque Robe +3" },
  { id: "FestivalKimono4"        , type: 0x3              , name: "Japanesque Robe +4" },
  { id: "FestivalKimono5"        , type: 0x3              , name: "Japanesque Robe +5" },
  { id: "Elfearcap"              , type: 0x4              , name: "Elf Ears" },
  { id: "Eyeglasses"             , type: 0x4              , name: "Eyeglasses" },
  { id: "Enlargedglasses"        , type: 0x4              , name: "Convex Glasses" },
  { id: "Horuseyes"              , type: 0x4              , name: "Eye of Horus" },
  { id: "sunglasses"             , type: 0x4              , name: "Sunglasses" },
  { id: "Bottleglasses"          , type: 0x4              , name: "Thick Glasses" },
  { id: "Measurementglasses"     , type: 0x4              , name: "Gauge Glasses" },
  { id: "Gebelsglasses"          , type: 0x4              , name: "Gebel's Glasses" },
  { id: "Stonemask"              , type: 0x4              , name: "Stone Mask" },
  { id: "Crowmask"               , type: 0x4              , name: "Crow Mask" },
  { id: "DanceMask"              , type: 0x4              , name: "Dance Mask" },
  { id: "Breathingforcedmask"    , type: 0x4              , name: "Hyperventilator" },
  { id: "NoseEyeglasses"         , type: 0x4              , name: "Nose Glasses" },
  { id: "Transformationmask"     , type: 0x4              , name: "Voice Changer" },
  { id: "OfudaTalisman"          , type: 0x4              , name: "Ofuda Talisman" },
  { id: "HeyI’mGrump"            , type: 0x4              , name: "Hey I'm Grump" },
  { id: "I’mNotSoGrump"          , type: 0x4              , name: "I'm Not So Grump" },
  { id: "AKindaFunnyMask"        , type: 0x4              , name: "A Kinda Funny Mask" },
  { id: "BigMustache"            , type: 0x4              , name: "Big Mustache" },
  { id: "PlagueDoctorFace"       , type: 0x4              , name: "Plague Doctor Face" },
  { id: "The-BazMask"            , type: 0x4              , name: "The-Baz Mask" },
  { id: "RustedRing"             , type: 0x4              , name: "Rusted Ring" },
  { id: "Ring"                   , type: 0x4              , name: "Ring" },
  { id: "Necklace"               , type: 0x4              , name: "Necklace" },
  { id: "Safering"               , type: 0x4              , name: "Safe Ring" },
  { id: "UnicornRing"            , type: 0x4              , name: "Unicorn Ring" },
  { id: "Flamering"              , type: 0x4              , name: "Flame Ring" },
  { id: "Icering"                , type: 0x4              , name: "Ice Ring" },
  { id: "Thunderring"            , type: 0x4              , name: "Thunder Ring" },
  { id: "Criticalring"           , type: 0x4              , name: "Critical Ring" },
  { id: "AssassinsRing"          , type: 0x4              , name: "Assassin's Ring" },
  { id: "LethalityRing"          , type: 0x4              , name: "Lethality Ring" },
  { id: "Walkerking"             , type: 0x4              , name: "Traverser's Ring" },
  { id: "Cursering"              , type: 0x4              , name: "Cursed Ring" },
  { id: "Striderbelt"            , type: 0x4              , name: "Strider Belt" },
  { id: "Silvermanring"          , type: 0x4              , name: "Silver Power Ring" },
  { id: "RoseRing"               , type: 0x4              , name: "Rose Ring" },
  { id: "SkullNecklace"          , type: 0x4              , name: "Skull Necklace" },
  { id: "Moonring"               , type: 0x4              , name: "Moon Belt" },
  { id: "WeightedRing"           , type: 0x4              , name: "Weighted Ring" },
  { id: "Speedstar"              , type: 0x4              , name: "Speed Belt" },
  { id: "CutpursesRing"          , type: 0x4              , name: "Cutpurse's Ring" },
  { id: "PlunderersRing"         , type: 0x4              , name: "Plunderer's Ring" },
  { id: "Goldmanring"            , type: 0x4              , name: "Gold Power Ring" },
  { id: "Riskring"               , type: 0x4              , name: "Risk Ring" },
  { id: "DemonNecklace"          , type: 0x4              , name: "Demon Necklace" },
  { id: "Adversityring"          , type: 0x4              , name: "Adversity Ring" },
  { id: "Blackbelt"              , type: 0x4              , name: "Black Belt" },
  { id: "Gamblersring"           , type: 0x4              , name: "Gambler's Ring" },
  { id: "WarlocksNecklace"       , type: 0x4              , name: "Warlock's Necklace" },
  { id: "RingofSolomon"          , type: 0x4              , name: "Solomon's Ring" },
  { id: "VampiricWings"          , type: 0x4              , name: "Vampiric Wings" },
  { id: "MagicalGirlAccessory"   , type: 0x4              , name: "Communicator" },
  { id: "ShantaeVest"            , type: 0x4              , name: "Half-Genie Vest" },
  { id: "ShantaeTiara"           , type: 0x4              , name: "Half-Genie Tiara" },
  { id: "FestivalMask"           , type: 0x4              , name: "Usagi Mask" },
  { id: "Sarashi"                , type: 0x4              , name: "Sarashi" },
  { id: "Muffler"                , type: 0x5              , name: "Scarf" },
  { id: "Turbinemuffler"         , type: 0x5              , name: "Tattered Scarf" },
  { id: "Batwing"                , type: 0x5              , name: "Bat Wings" },
  { id: "Outlinestyle"           , type: 0x5              , name: "Gunman's Scarf" },
  { id: "Made-to-order"          , type: 0x5              , name: "Order-made Scarf" },
  { id: "Usagimuffler"           , type: 0x5              , name: "Bunny Scarf" },
  { id: "FaerieScarf"            , type: 0x5              , name: "Faerie Scarf" },
  { id: "Sendomuffler"           , type: 0x5              , name: "Fangshi Scarf" },
  { id: "Firemuffler"            , type: 0x5              , name: "Flame Scarf" },
  { id: "TalismanScarf"          , type: 0x5              , name: "Talisman Scarf" },
  { id: "OvertheRainbow"         , type: 0x5              , name: "Over the Rainbow" },
  { id: "JourneyScarf"           , type: 0x5              , name: "Mystical Scard" },
  { id: "VampiricChoker"         , type: 0x5              , name: "Vampiric Choker" },
  { id: "Potion"                 , type: 0x6              , name: "Potion" },
  { id: "HighPotion"             , type: 0x6              , name: "High Potion" },
  { id: "ExPotion"               , type: 0x6              , name: "Ex Potion" },
  { id: "Ether"                  , type: 0x6              , name: "Ether" },
  { id: "HighEther"              , type: 0x6              , name: "High Ether" },
  { id: "ExEther"                , type: 0x6              , name: "Ex Ether" },
  { id: "Mithridate"             , type: 0x6              , name: "Mithridate" },
  { id: "HolyWater"              , type: 0x6              , name: "Holy Water" },
  { id: "Stonethaw"              , type: 0x6              , name: "Stonethaw" },
  { id: "Poison"                 , type: 0x6              , name: "Poison" },
  { id: "Waystone"               , type: 0x6              , name: "Waystone" },
  { id: "Panacea"                , type: 0x6              , name: "Panacea" },
  { id: "FaerieMedicine"         , type: 0x6              , name: "Faerie Medicine" },
  { id: "FaerieElixir"           , type: 0x6              , name: "Faerie Elixir" },
  { id: "FaerieAllheal"          , type: 0x6              , name: "Faerie Allheal" },
  { id: "FaeriePanacea"          , type: 0x6              , name: "Faerie Panacea" },
  { id: "RiceBall"               , type: 0x7              , name: "Rice Ball" },
  { id: "UniDon"                 , type: 0x7              , name: "Uni Rice Bowl" },
  { id: "AppleRisotto"           , type: 0x7              , name: "Apple Risotto" },
  { id: "EggonRice"              , type: 0x7              , name: "Egg on Rice" },
  { id: "Omurice"                , type: 0x7              , name: "Omurice" },
  { id: "ChickenCasserole"       , type: 0x7              , name: "Chicken Casserole" },
  { id: "Curry&Rice"             , type: 0x7              , name: "Curry & Rice" },
  { id: "BeefCurry"              , type: 0x7              , name: "Beef Curry" },
  { id: "PorkCurry"              , type: 0x7              , name: "Pork Curry" },
  { id: "ChickenCurry"           , type: 0x7              , name: "Chicken Curry" },
  { id: "SeafoodCurry"           , type: 0x7              , name: "Seafood Curry" },
  { id: "MacaroniGratin"         , type: 0x7              , name: "Macaroni Gratin" },
  { id: "ClassicSpaghetti"       , type: 0x7              , name: "Classic Spaghetti" },
  { id: "PastaCarbonara"         , type: 0x7              , name: "Pasta Carbonara" },
  { id: "PastaVongole"           , type: 0x7              , name: "Pasta Vongole" },
  { id: "SeaUrchinPasta"         , type: 0x7              , name: "Sea Urchin Pasta" },
  { id: "BerrySpaghetti"         , type: 0x7              , name: "Berry Spaghetti" },
  { id: "ShirukoSpaghetti"       , type: 0x7              , name: "Shiruko Spaghetti" },
  { id: "SaltRamen"              , type: 0x7              , name: "Salt Ramen" },
  { id: "SoyRamen"               , type: 0x7              , name: "Soy Ramen" },
  { id: "TonkotsuRamen"          , type: 0x7              , name: "Tonkotsu Ramen" },
  { id: "MisoRamen"              , type: 0x7              , name: "Miso Ramen" },
  { id: "CornChowder"            , type: 0x7              , name: "Corn Chowder" },
  { id: "Steak"                  , type: 0x7              , name: "Steak" },
  { id: "ExquisiteSteak"         , type: 0x7              , name: "Exquisite Steak" },
  { id: "Sukiyaki"               , type: 0x7              , name: "Sukiyaki" },
  { id: "ChickenSauté"           , type: 0x7              , name: "Chicken Sauté" },
  { id: "GarlicChicken"          , type: 0x7              , name: "Garlic Chicken" },
  { id: "Tonkatsu"               , type: 0x7              , name: "Pork Cutlet" },
  { id: "MisoCutlet"             , type: 0x7              , name: "Miso Cutlet" },
  { id: "GingerPork"             , type: 0x7              , name: "Ginger Pork" },
  { id: "MeatHotPot"             , type: 0x7              , name: "Meat Hot Pot" },
  { id: "FriedPotatoes"          , type: 0x7              , name: "Fried Potatoes" },
  { id: "Pizza"                  , type: 0x7              , name: "Pizza" },
  { id: "FriedFish"              , type: 0x7              , name: "Fried Fish" },
  { id: "FishAndChips"           , type: 0x7              , name: "Fish & Chips" },
  { id: "SimmeredForneus"        , type: 0x7              , name: "Simmered Forneus" },
  { id: "ForneusMeunière"        , type: 0x7              , name: "Forneus Meunière" },
  { id: "ForneusinGarlic"        , type: 0x7              , name: "Forneus in Garlic" },
  { id: "FishHotPot"             , type: 0x7              , name: "Fish Hot Pot" },
  { id: "Flan"                   , type: 0x7              , name: "Flan" },
  { id: "Manju"                  , type: 0x7              , name: "Manju" },
  { id: "ApplePie"               , type: 0x7              , name: "Apple Pie" },
  { id: "LemonPie"               , type: 0x7              , name: "Lemon Cream Pie" },
  { id: "StrawberryPie"          , type: 0x7              , name: "Strawberry Pie" },
  { id: "StrawberryCrepe"        , type: 0x7              , name: "Strawberry Crepe" },
  { id: "ChocolateCrepe"         , type: 0x7              , name: "Chocolate Crepe" },
  { id: "Cookies"                , type: 0x7              , name: "Cookies" },
  { id: "ChocolateCookies"       , type: 0x7              , name: "Chocolate Cookies" },
  { id: "CinnamonCookies"        , type: 0x7              , name: "Cinnamon Cookies" },
  { id: "SpongeCake"             , type: 0x7              , name: "Sponge Cake" },
  { id: "ChiffonCake"            , type: 0x7              , name: "Chiffon Cake" },
  { id: "CheeseCake"             , type: 0x7              , name: "Cheesecake" },
  { id: "ChocolateCake"          , type: 0x7              , name: "Chocolate Cake" },
  { id: "StrawberryCake"         , type: 0x7              , name: "Strawberry Cake" },
  { id: "ScrambledEggs"          , type: 0x7              , name: "Scrambled Eggs" },
  { id: "RolledOmelette"         , type: 0x7              , name: "Rolled Omelette" },
  { id: "FriedEgg"               , type: 0x7              , name: "Fried Egg" },
  { id: "EggSoufflé"             , type: 0x7              , name: "Egg Soufflé" },
  { id: "AppleJuice"             , type: 0x7              , name: "Apple Juice" },
  { id: "StrawberryAuLait"       , type: 0x7              , name: "Strawberry Au Lait" },
  { id: "Lemonade"               , type: 0x7              , name: "Lemonade" },
  { id: "Smoothie"               , type: 0x7              , name: "Smoothie" },
  { id: "FruitJuice"             , type: 0x7              , name: "Fruit Juice" },
  { id: "Nectar"                 , type: 0x7              , name: "Nectar" },
  { id: "DarkMatter"             , type: 0x7              , name: "Dark Matter" },
  { id: "MacaroniAndCheese"      , type: 0x7              , name: "Macaroni & Cheese" },
  { id: "Paddy"                  , type: 0x8              , name: "Rice" },
  { id: "Flour"                  , type: 0x8              , name: "Flour" },
  { id: "Egg"                    , type: 0x8              , name: "Egg" },
  { id: "DragonsEgg"             , type: 0x8              , name: "Dragon Egg" },
  { id: "Sugar"                  , type: 0x8              , name: "Sugar" },
  { id: "SoySauce"               , type: 0x8              , name: "Soy Sauce" },
  { id: "Miso"                   , type: 0x8              , name: "Miso" },
  { id: "Pepper"                 , type: 0x8              , name: "Black Pepper" },
  { id: "Ginger"                 , type: 0x8              , name: "Ginger" },
  { id: "Garlic"                 , type: 0x8              , name: "Garlic" },
  { id: "Cinnamon"               , type: 0x8              , name: "Cinnamon" },
  { id: "MocoOil"                , type: 0x8              , name: "Moco Oil" },
  { id: "Rennet"                 , type: 0x8              , name: "Rennet" },
  { id: "Milk"                   , type: 0x8              , name: "Milk" },
  { id: "MilkofZagan"            , type: 0x8              , name: "Beast Milk" },
  { id: "Corn"                   , type: 0x8              , name: "Corn" },
  { id: "Potato"                 , type: 0x8              , name: "Potato" },
  { id: "Tomato"                 , type: 0x8              , name: "Tomato" },
  { id: "MocoOnion"              , type: 0x8              , name: "Moco Leek" },
  { id: "DaturaLeaf"             , type: 0x8              , name: "Fey Leaf" },
  { id: "CerberaLeaf"            , type: 0x8              , name: "Fell Leaf" },
  { id: "Clam"                   , type: 0x8              , name: "Clam" },
  { id: "Uni"                    , type: 0x8              , name: "Sea Urchin" },
  { id: "RedBean"                , type: 0x8              , name: "Red Bean" },
  { id: "CacaoBean"              , type: 0x8              , name: "Cacao Bean" },
  { id: "ForneusFilet"           , type: 0x8              , name: "Forneus Filet" },
  { id: "DeeseamaFilet"          , type: 0x8              , name: "Aquatic Filet" },
  { id: "G-LabolasFilet"         , type: 0x8              , name: "G-Bone Steak" },
  { id: "YorktonMeat"            , type: 0x8              , name: "Plume Pork" },
  { id: "ZaganMeat"              , type: 0x8              , name: "Beast Beef" },
  { id: "HaagentiFilet"          , type: 0x8              , name: "Flying Beef" },
  { id: "Strawberry"             , type: 0x8              , name: "Strawberry" },
  { id: "Apple"                  , type: 0x8              , name: "Apple" },
  { id: "Lemon"                  , type: 0x8              , name: "Lemon" },
  { id: "Ambrosia"               , type: 0x8              , name: "Ambrosia" },
  { id: "BakingSoda"             , type: 0x8              , name: "Baking Soda" },
  { id: "Butter"                 , type: 0x8              , name: "Butter" },
  { id: "Cheese"                 , type: 0x8              , name: "Cheese" },
  { id: "Soda"                   , type: 0x8              , name: "Soda Water" },
  { id: "Consommé"               , type: 0x8              , name: "Consommé" },
  { id: "SaltBroth"              , type: 0x8              , name: "Salt Broth" },
  { id: "SoyBroth"               , type: 0x8              , name: "Soy Broth" },
  { id: "TonkotsuBroth"          , type: 0x8              , name: "Tonkotsu Broth" },
  { id: "MisoBroth"              , type: 0x8              , name: "Miso Broth" },
  { id: "HeavyCream"             , type: 0x8              , name: "Heavy Cream" },
  { id: "RedBeanPaste"           , type: 0x8              , name: "Red Bean Paste" },
  { id: "Cocoa"                  , type: 0x8              , name: "Cocoa" },
  { id: "ChineseNoodles"         , type: 0x8              , name: "Chinese Noodles" },
  { id: "Pasta"                  , type: 0x8              , name: "Pasta" },
  { id: "Bread"                  , type: 0x8              , name: "Bread" },
  { id: "PieDough"               , type: 0x8              , name: "Pie Dough" },
  { id: "PizzaDough"             , type: 0x8              , name: "Pizza Dough" },
  { id: "CrepeDough"             , type: 0x8              , name: "Crepe Dough" },
  { id: "CurryPowder"            , type: 0x8              , name: "Curry Powder" },
  { id: "CurrySauce"             , type: 0x8              , name: "Curry Sauce" },
  { id: "WhiteSauce"             , type: 0x8              , name: "White Sauce" },
  { id: "VongoleSauce"           , type: 0x8              , name: "Vongole Sauce" },
  { id: "SeedCorn"               , type: 0x8              , name: "Corn Seed" },
  { id: "SeedRice"               , type: 0x8              , name: "Rice Seed" },
  { id: "SeedPotato"             , type: 0x8              , name: "Potato Seed" },
  { id: "Alkhahest"              , type: 0x9              , name: "Alkahest" },
  { id: "Sulfur"                 , type: 0x9              , name: "Sulfur" },
  { id: "Saltpeter"              , type: 0x9              , name: "Saltpeter" },
  { id: "Mercury"                , type: 0x9              , name: "Mercury" },
  { id: "Sulfate"                , type: 0x9              , name: "Sulfate" },
  { id: "Gunpowder"              , type: 0x9              , name: "Gunpowder" },
  { id: "Ectoplasm"              , type: 0x9              , name: "Ectoplasm" },
  { id: "Bronze"                 , type: 0x9              , name: "Bronze" },
  { id: "Iron"                   , type: 0x9              , name: "Iron" },
  { id: "Obsidian"               , type: 0x9              , name: "Obsidian" },
  { id: "Steel"                  , type: 0x9              , name: "Steel" },
  { id: "Silver"                 , type: 0x9              , name: "Silver" },
  { id: "DamascusSteel"          , type: 0x9              , name: "Damascus" },
  { id: "Mithril"                , type: 0x9              , name: "Mithril" },
  { id: "Platinum"               , type: 0x9              , name: "Platinum" },
  { id: "Clystal"                , type: 0x9              , name: "Crystal" },
  { id: "Gold"                   , type: 0x9              , name: "Gold" },
  { id: "Hihiirokane"            , type: 0x9              , name: "Crimsonite" },
  { id: "Orichalcum"             , type: 0x9              , name: "Orichalcum" },
  { id: "Hemp"                   , type: 0x9              , name: "Cotton" },
  { id: "Cotton"                 , type: 0x9              , name: "Hemp" },
  { id: "Felt"                   , type: 0x9              , name: "Wool" },
  { id: "Silk"                   , type: 0x9              , name: "Silk" },
  { id: "Leather"                , type: 0x9              , name: "Cashmere" },
  { id: "Halite"                 , type: 0x9              , name: "Halite" },
  { id: "ElmLumber"              , type: 0x9              , name: "Elm" },
  { id: "OakLumber"              , type: 0x9              , name: "Oak" },
  { id: "WalnutLumber"           , type: 0x9              , name: "Walnut" },
  { id: "MahoganyLumber"         , type: 0x9              , name: "Mahogany" },
  { id: "CypressLumber"          , type: 0x9              , name: "Cypress" },
  { id: "Ruby"                   , type: 0x9              , name: "Ruby" },
  { id: "Sapphire"               , type: 0x9              , name: "Sapphire" },
  { id: "Emerald"                , type: 0x9              , name: "Emerald" },
  { id: "Diamond"                , type: 0x9              , name: "Diamond" },
  { id: "Bixbite"                , type: 0x9              , name: "Bixbite" },
  { id: "Alexandrite"            , type: 0x9              , name: "Alexandrite" },
  { id: "8BitCoin"               , type: 0x9              , name: "8-bit Coin" },
  { id: "16BitCoin"              , type: 0x9              , name: "16-bit Coin" },
  { id: "32BitCoin"              , type: 0x9              , name: "32-bit Coin" },
  { id: "Medal022"               , type: 0x9              , name: "8-bit Nightmare" },
  { id: "Recklesslimb"           , type: 0x9              , name: "Writhing Limb" },
  { id: "SharpRazor"             , type: 0x9              , name: "Sharp Razor" },
  { id: "DevilBookPaperStrip"    , type: 0x9              , name: "Tome Scrap" },
  { id: "deathBringerDebris"     , type: 0x9              , name: "Sword Fragment" },
  { id: "Mimicchairdebris"       , type: 0x9              , name: "Chair Remnants" },
  { id: "MonsterBirdTears"       , type: 0x9              , name: "Monster Bird Tear" },
  { id: "Cyhyraethtear"          , type: 0x9              , name: "Witch's Tears" },
  { id: "Lamastutear"            , type: 0x9              , name: "Queen's Tears" },
  { id: "Giantratteeth"          , type: 0x9              , name: "Rat Teeth" },
  { id: "Batfang"                , type: 0x9              , name: "Bat Fang" },
  { id: "DemonDogFang"           , type: 0x9              , name: "Demon Dog Fang" },
  { id: "Ivory"                  , type: 0x9              , name: "Monster Fang" },
  { id: "Devilsfang"             , type: 0x9              , name: "Sinister Fang" },
  { id: "Gusionfang"             , type: 0x9              , name: "Demon Fang" },
  { id: "Marbasfang"             , type: 0x9              , name: "Fiend Fang" },
  { id: "Gieremundfang"          , type: 0x9              , name: "Imbrued Fang" },
  { id: "Wolfclaw"               , type: 0x9              , name: "Lycan Claw" },
  { id: "Dragonclaw"             , type: 0x9              , name: "Dragon Talons" },
  { id: "Apenail"                , type: 0x9              , name: "Demon Claw" },
  { id: "Chicomecoatlhorn"       , type: 0x9              , name: "Monster Horn" },
  { id: "Gaaphorn"               , type: 0x9              , name: "Demon Horn" },
  { id: "Gamiginhoof"            , type: 0x9              , name: "Hellhorse Hoof" },
  { id: "Glashtynhoof"           , type: 0x9              , name: "Water Horse Hoof" },
  { id: "MeltedBone"             , type: 0x9              , name: "Melting Bone" },
  { id: "Dragonbone"             , type: 0x9              , name: "Dragon Bone" },
  { id: "Knightbone"             , type: 0x9              , name: "Demon Bone" },
  { id: "Bloodybone"             , type: 0x9              , name: "Imbrued Bone" },
  { id: "MeltingSkull"           , type: 0x9              , name: "Melting Skull" },
  { id: "Jeneralskull"           , type: 0x9              , name: "Sinister Skull" },
  { id: "Warriorskull"           , type: 0x9              , name: "Fiend Skull" },
  { id: "Bloodyskull"            , type: 0x9              , name: "Imbrued Skull" },
  { id: "Mimicshell"             , type: 0x9              , name: "Grotesque Shell" },
  { id: "Dethtrapshell"          , type: 0x9              , name: "Inhuman Carapace" },
  { id: "CannonDebris"           , type: 0x9              , name: "Cannon Scrap" },
  { id: "Gargoyledebris"         , type: 0x9              , name: "Gargoyle Stone" },
  { id: "Gamiginhair"            , type: 0x9              , name: "Hellhorse Mane" },
  { id: "Glashtynhair"           , type: 0x9              , name: "Water Horse Mane" },
  { id: "ManeLion"               , type: 0x9              , name: "Lion Mane" },
  { id: "Marbasmane"             , type: 0x9              , name: "Lion Lord's Mane" },
  { id: "MonsterBirdHair"        , type: 0x9              , name: "Monster Bird Hair" },
  { id: "ThunderbirdFeathers"    , type: 0x9              , name: "Thunderbird Plume" },
  { id: "WindFeathers"           , type: 0x9              , name: "Flight Feather" },
  { id: "Haagentifeather"        , type: 0x9              , name: "Bovine Plume" },
  { id: "BatFeather"             , type: 0x9              , name: "Small Webbing" },
  { id: "Toadwing"               , type: 0x9              , name: "Toad Webbing" },
  { id: "Gaapwing"               , type: 0x9              , name: "Demon Wing" },
  { id: "Giantrattail"           , type: 0x9              , name: "Rat Tail" },
  { id: "DevilRoyalTail"         , type: 0x9              , name: "Demon Tail" },
  { id: "Lilimtail"              , type: 0x9              , name: "Lili Tail" },
  { id: "Lamastutail"            , type: 0x9              , name: "Queen's Tail" },
  { id: "Lilimear"               , type: 0x9              , name: "Lili Ears" },
  { id: "Dineseawing"            , type: 0x9              , name: "Faerie Wing" },
  { id: "Tytaniawing"            , type: 0x9              , name: "Vespine Wing" },
  { id: "FairyPowder"            , type: 0x9              , name: "Faerie Dust" },
  { id: "TytaniaPoisonedNeedle"  , type: 0x9              , name: "Vespine Stinger" },
  { id: "Dragonscales"           , type: 0x9              , name: "Dragon Scale" },
  { id: "Abyssguardianbastard"   , type: 0x9              , name: "Dragon's Wrath" },
  { id: "DemonCloth"             , type: 0x9              , name: "Dreadful Rag" },
  { id: "Assasincloth"           , type: 0x9              , name: "Durable Rag" },
  { id: "Lerajecloth"            , type: 0x9              , name: "Sinister Rag" },
  { id: "Ninjacloth"             , type: 0x9              , name: "Eastern Fabric" },
  { id: "DemonDogSkin"           , type: 0x9              , name: "Houndskin" },
  { id: "MonkeyFur"              , type: 0x9              , name: "Monster Fur" },
  { id: "Buerfur"                , type: 0x9              , name: "Leonine Pelt" },
  { id: "Wolfmanfur"             , type: 0x9              , name: "Sinister Pelt" },
  { id: "Decarabialeather"       , type: 0x9              , name: "Durable Leather" },
  { id: "DevilBookLeather"       , type: 0x9              , name: "Strange Leather" },
  { id: "Decimaleather"          , type: 0x9              , name: "Slimy Leather" },
  { id: "Silverwolffur"          , type: 0x9              , name: "Demon Pelt" },
  { id: "Gusionfur"              , type: 0x9              , name: "Fiend Pelt" },
  { id: "Poisontoadeye"          , type: 0x9              , name: "Toad Eye" },
  { id: "Evileye"                , type: 0x9              , name: "Sinister Eye" },
  { id: "SeekerEye"              , type: 0x9              , name: "Demon Eye" },
  { id: "DevilRoyalEyeball"      , type: 0x9              , name: "Fiend Eye" },
  { id: "ToadHeart"              , type: 0x9              , name: "Toad Heart" },
  { id: "BelialHeart"            , type: 0x9              , name: "Sinister Heart" },
  { id: "EligosHeart"            , type: 0x9              , name: "Demon Heart" },
  { id: "AbyssguardianHeart"     , type: 0x9              , name: "Dragon Heart" },
  { id: "MurmurHeart"            , type: 0x9              , name: "Fiend Heart" },
  { id: "Toadfluid"              , type: 0x9              , name: "Monster Blood" },
  { id: "Misteriousfluid"        , type: 0x9              , name: "Aquatic Blood" },
  { id: "ShipMap"                , type: 0xa              , name: "Galleon Map" },
  { id: "Certificationboard"     , type: 0xa              , name: "Passplate" },
  { id: "IDphoto"                , type: 0xa              , name: "Identification" },
  { id: "SilverBromide"          , type: 0xa              , name: "Silver Bromide" },
  { id: "Keyofbacker1"           , type: 0xa              , name: "Carpenter's Key" },
  { id: "Keyofbacker2"           , type: 0xa              , name: "Warhorse's Key" },
  { id: "Keyofbacker3"           , type: 0xa              , name: "Millionaire's Key" },
  { id: "Keyofbacker4"           , type: 0xa              , name: "Celeste's Key" },
  { id: "Worldfashionfirstissue" , type: 0xa              , name: "Hair Apparent I" },
  { id: "WorldfashionNo02"       , type: 0xa              , name: "Hair Apparent II" },
  { id: "WorldfashionNo03"       , type: 0xa              , name: "Hair Apparent III" },
  { id: "WorldfashionNo04"       , type: 0xa              , name: "Hair Apparent IV" },
  { id: "WorldfashionNo05"       , type: 0xa              , name: "Hair Apparent V" },
  { id: "WorldfashionNo06"       , type: 0xa              , name: "Hair Apparent VI" },
  { id: "WorldfashionNo07"       , type: 0xa              , name: "Hair Apparent VII" },
  { id: "WorldfashionNo08"       , type: 0xa              , name: "Hair Apparent VIII" },
  { id: "WorldfashionNo09"       , type: 0xa              , name: "Hair Apparent IX" },
  { id: "WorldfashionNo10"       , type: 0xa              , name: "Hair Apparent X" },
  { id: "WorldfashionNo11"       , type: 0xa              , name: "Hair Apparent XI" },
  { id: "WorldfashionNo12"       , type: 0xa              , name: "Hair Apparent XII" },
  { id: "VillageKey"             , type: 0xa              , name: "Village Key" },
  { id: "ItemRecipe001"          , type: 0xa              , name: "Fine Healing Item/R" },
  { id: "ItemRecipe002"          , type: 0xa              , name: "Ultimate Healing Item/R" },
  { id: "ItemRecipe003"          , type: 0xa              , name: "Faerie Healing Item/R" },
  { id: "BalletRecipe001"        , type: 0xa              , name: "Elemental Ammunition/R" },
  { id: "BalletRecipe002"        , type: 0xa              , name: "Special Ammunition/R" },
  { id: "BalletRecipe003"        , type: 0xa              , name: "Potent Ammunition/R" },
  { id: "BalletRecipe004"        , type: 0xa              , name: "Ultimate Ammunition/R" },
  { id: "ArmsRecipe003"          , type: 0xa              , name: "Steel Equipment/R" },
  { id: "ArmsRecipe004"          , type: 0xa              , name: "Obsidian Equipment/R" },
  { id: "ArmsRecipe005"          , type: 0xa              , name: "Damascus Equipment/R" },
  { id: "ArmsRecipe007"          , type: 0xa              , name: "Gold Equipment/R" },
  { id: "ArmsRecipe009"          , type: 0xa              , name: "Crimsonite Equipment/R" },
  { id: "ArmsRecipe012"          , type: 0xa              , name: "Cashmere Equipment/R" },
  { id: "ArmsRecipe018"          , type: 0xa              , name: "Fine Equipment/R" },
  { id: "ArmsRecipe019"          , type: 0xa              , name: "Very Fine Equipment/R" },
  { id: "ArmsRecipe020"          , type: 0xa              , name: "Legendary Equipment/R" },
  { id: "DishRecipe002"          , type: 0xa              , name: "Ramen/R" },
  { id: "DishRecipe003"          , type: 0xa              , name: "Curry Dish/R" },
  { id: "DishRecipe004"          , type: 0xa              , name: "Pasta Dish/R" },
  { id: "DishRecipe005"          , type: 0xa              , name: "Meat Dish/R" },
  { id: "DishRecipe006"          , type: 0xa              , name: "Fish Dish/R" },
  { id: "DishRecipe007"          , type: 0xa              , name: "Sweets/R" },
  { id: "DishRecipe008"          , type: 0xa              , name: "Cookies/R" },
  { id: "DishRecipe010"          , type: 0xa              , name: "Cake/R" },
  { id: "DishRecipe011"          , type: 0xa              , name: "Drink/R" },
  { id: "DishRecipe014"          , type: 0xa              , name: "Ultimate Dish/R" },
  { id: "DishRecipe015"          , type: 0xa              , name: "Supreme Dish/R" },
  { id: "DiscountCard"           , type: 0xa              , name: "Discount Card" },
  { id: "Medal001"               , type: 0xa              , name: "Vepar Medal" },
  { id: "Medal002"               , type: 0xa              , name: "Zangetsu Medal" },
  { id: "Medal003"               , type: 0xa              , name: "Craftwork Medal" },
  { id: "Medal004"               , type: 0xa              , name: "Andrealphus Medal" },
  { id: "Medal005"               , type: 0xa              , name: "Glutton Train Medal" },
  { id: "Medal006"               , type: 0xa              , name: "Valac Medal" },
  { id: "Medal007"               , type: 0xa              , name: "Bathin Medal" },
  { id: "Medal008"               , type: 0xa              , name: "Abyssal Guardian Medal" },
  { id: "Medal009"               , type: 0xa              , name: "Gebel Medal" },
  { id: "Medal010"               , type: 0xa              , name: "Bloodless Medal" },
  { id: "Medal011"               , type: 0xa              , name: "Alfred Medal" },
  { id: "Medal023"               , type: 0xa              , name: "Doppelganger Medal" },
  { id: "Medal012"               , type: 0xa              , name: "Orobas Medal" },
  { id: "Medal013"               , type: 0xa              , name: "True Zangetsu Medal" },
  { id: "Medal014"               , type: 0xa              , name: "Valefar Medal" },
  { id: "Medal015"               , type: 0xa              , name: "Gremory Medal" },
  { id: "Medal016"               , type: 0xa              , name: "Dominique Medal" },
  { id: "Medal017"               , type: 0xa              , name: "Bael Medal" },
  { id: "Medal018"               , type: 0xa              , name: "O.D. Medal" },
  { id: "Medal020"               , type: 0xa              , name: "IGA Medal" },
  { id: "Medal021"               , type: 0xa              , name: "8-bit Medal" },
  { id: "Bookofstiffness"        , type: 0xb              , name: "Might Tome" },
  { id: "Abookofwisemen"         , type: 0xb              , name: "Sage's Tome" },
  { id: "GuardiansBook"          , type: 0xb              , name: "Sentinel Tome" },
  { id: "Bookoffaith"            , type: 0xb              , name: "Believer's Tome" },
  { id: "BookofFortune"          , type: 0xb              , name: "Fortune Tome" },
  { id: "Bookofwinter"           , type: 0xb              , name: "Coldstave Tome" },
  { id: "Heatresistantbook"      , type: 0xb              , name: "Heatstave Tome" },
  { id: "LightningProtectionBook", type: 0xb              , name: "Shockstave Tome" },
  { id: "Bookoflatency"          , type: 0xb              , name: "Empyreal Tome" },
  { id: "ShadingBook"            , type: 0xb              , name: "Obscurity Tome" },
  { id: "Bookoffossilstone"      , type: 0xb              , name: "Corporeity Tome" },
  { id: "Bookofdetoxification"   , type: 0xb              , name: "Immunity Tome" },
  { id: "TheBookofMonster"       , type: 0xb              , name: "Blessed Tome" },
  { id: "BookoftheMighty"        , type: 0xb              , name: "Prowess Tome" },
  { id: "Bookofthefollower"      , type: 0xb              , name: "Ancillary Tome" },
  { id: "BookofDevils"           , type: 0xb              , name: "Deadeye Tome" },
  { id: "Abookofthegale"         , type: 0xb              , name: "Tailwind Tome" },
  { id: "BookofTactics"          , type: 0xb              , name: "Tactician's Tome" },
  { id: "Bookofexercise"         , type: 0xb              , name: "Mastery Tome" },
  { id: "BookofFury"             , type: 0xb              , name: "Godsend Tome" },
  { id: "Bookofthechampion"      , type: 0xb              , name: "Tome of Conquest" },
];

export const accessories: Resource = { "-1": "-" };
export const bodies: Resource = { "-1": "-" };
export const bullets: Resource = { "-1": "-" };
export const heads: Resource = { "-1": "-" };
export const scarfs: Resource = { "-1": "-" };
export const weapons: Resource = { "-1": "-" };

export const weaponsGroups: ResourceGroups = weaponTypes.map((type) => ({
  name: type.name,
  options: [],
}));

itemList.forEach((item, index) => {
  if (item.type === 0x0) {
    weapons[index] = item.name;
    weaponsGroups[item.subtype!].options.push(index);
  } else {
    switch (item.type) {
      case 0x1:
        bullets[index] = item.name;
        break;
      case 0x2:
        heads[index] = item.name;
        break;
      case 0x3:
        bodies[index] = item.name;
        break;
      case 0x4:
        accessories[index] = item.name;
        break;
      case 0x5:
        scarfs[index] = item.name;
        break;
    }
  }
});

// prettier-ignore
export const shardList = [
  { id: "SwingTentacle"           , type: 0x0, name: "Thrashing Tentacle" },
  { id: "BloodSteel"              , type: 0x0, name: "Blood Steal" },
  { id: "DragonicRage"            , type: 0x0, name: "Draconic Rage" },
  { id: "Ceruleansplash"          , type: 0x0, name: "Cerulean Splash" },
  { id: "Raginggirl"              , type: 0x0, name: "Gale Crawler" },
  { id: "HEADFAIL"                , type: 0x0, name: "Head Flail" },
  { id: "SummonRat"               , type: 0x0, name: "Summon Rat" },
  { id: "SummonAme"               , type: 0x0, name: "Summon Ghost" },
  { id: "SummonButt"              , type: 0x0, name: "Summon Bat" },
  { id: "SummonApe"               , type: 0x0, name: "Summon Simian" },
  { id: "SummonGilemund"          , type: 0x0, name: "Summon Gieremund" },
  { id: "Shovelshooter"           , type: 0x0, name: "Summon Shovel Armor" },
  { id: "SamonSamHiggin"          , type: 0x0, name: "Summon Water Leaper" },
  { id: "SummonBuell"             , type: 0x0, name: "Summon Buer" },
  { id: "SummonBugs"              , type: 0x0, name: "Summon Insect" },
  { id: "SummonChair"             , type: 0x0, name: "Summon Chair" },
  { id: "SummonTracer"            , type: 0x0, name: "Summon Tracer" },
  { id: "HiddenDart"              , type: 0x0, name: "Shuriken" },
  { id: "RapidSpear"              , type: 0x0, name: "Throw Spear" },
  { id: "EntangleBind"            , type: 0x0, name: "Flytrap" },
  { id: "GratefulAssist"          , type: 0x0, name: "Welcome Company" },
  { id: "ThrowAxe"                , type: 0x0, name: "Throwing Axe" },
  { id: "AxStrike"                , type: 0x0, name: "Axe Strike" },
  { id: "Deadhowling"             , type: 0x0, name: "Death Cry" },
  { id: "Upbeatheat"              , type: 0x0, name: "Upbeat Heat" },
  { id: "Toxicstorm"              , type: 0x0, name: "Toxic Storm" },
  { id: "HellHound"               , type: 0x0, name: "Summon Hellhound" },
  { id: "Jackpot"                 , type: 0x0, name: "Jackpot" },
  { id: "LigaStreyma"             , type: 0x0, name: "Riga Storæma" },
  { id: "VaIsha"                  , type: 0x0, name: "Va Ischa" },
  { id: "VaSka"                   , type: 0x0, name: "Va Schia" },
  { id: "TepsSalenda"             , type: 0x0, name: "Teps Salrenda" },
  { id: "TissLeif"                , type: 0x0, name: "Tis Raiff" },
  { id: "NeverSatisfied"          , type: 0x0, name: "Insatiable" },
  { id: "Zombie8Bit"              , type: 0x0, name: "Summon 8-bit Zombie" },
  { id: "Ghost8Bit"               , type: 0x0, name: "Summon 8-bit Ghost" },
  { id: "Nightmare8Bit"           , type: 0x0, name: "8-bit Flame" },
  { id: "DREAMSTEAL"              , type: 0x0, name: "Dream Steal" },
  { id: "SummonBuChan"            , type: 0x0, name: "Summon Bu-chan" },
  { id: "SakuraRain"              , type: 0x0, name: "Sakura Storm" },
  { id: "Demoniccapture"          , type: 0x1, name: "Craftwork" },
  { id: "Accelerator"             , type: 0x1, name: "Accelerator" },
  { id: "AccelWorld"              , type: 0x1, name: "Standstill" },
  { id: "Beastguard"              , type: 0x1, name: "Beast Guardian" },
  { id: "WildScratch"             , type: 0x1, name: "Feral Claws" },
  { id: "Shadowtracer"            , type: 0x1, name: "Shadow Tracer" },
  { id: "ChangeBunny"             , type: 0x1, name: "Bunnymorphosis" },
  { id: "Healing"                 , type: 0x1, name: "Healing" },
  { id: "Sacredshade"             , type: 0x1, name: "Sacred Shade" },
  { id: "SummonYorkton"           , type: 0x2, name: "Summon Plume Parma" },
  { id: "Reflectionray"           , type: 0x2, name: "Reflector Ray" },
  { id: "Aquastream"              , type: 0x2, name: "Aqua Stream" },
  { id: "DimensionShift"          , type: 0x2, name: "Dimension Shift" },
  { id: "InfernoBrace"            , type: 0x2, name: "Inferno Breath" },
  { id: "Hammerknuckle"           , type: 0x2, name: "Hammer Knuckle" },
  { id: "GoldBarrett"             , type: 0x2, name: "Gold Bullet" },
  { id: "FireCannon"              , type: 0x2, name: "Flame Cannon" },
  { id: "BoonsLore"               , type: 0x2, name: "Bone Toss" },
  { id: "StraightArrow"           , type: 0x2, name: "True Arrow" },
  { id: "Releasetoade"            , type: 0x2, name: "Release Toad" },
  { id: "ChaseArrow"              , type: 0x2, name: "Chaser Arrow" },
  { id: "Aimingshield"            , type: 0x2, name: "Directed Shield" },
  { id: "HelleTicalGrinder"       , type: 0x2, name: "Heretical Grinder" },
  { id: "CurseDray"               , type: 0x2, name: "Lethargy" },
  { id: "Petrey"                  , type: 0x2, name: "Petra Ray" },
  { id: "Voidlay"                 , type: 0x2, name: "Void Ray" },
  { id: "PetraBless"              , type: 0x2, name: "Petra Breath" },
  { id: "Acidgouache"             , type: 0x2, name: "Acid Jet" },
  { id: "Venomsmog"               , type: 0x2, name: "Venom Mist" },
  { id: "CircleRipper"            , type: 0x2, name: "Circular Ripper" },
  { id: "ShootingDagger"          , type: 0x2, name: "Flying Dagger" },
  { id: "BaudRideBlast"           , type: 0x2, name: "Bolide Blast" },
  { id: "Tornadoslicer"           , type: 0x2, name: "Tornado Slicer" },
  { id: "FireThrower"             , type: 0x2, name: "Flamethrower" },
  { id: "Chiselbalage"            , type: 0x2, name: "Chisel Barrage" },
  { id: "RuinBeak"                , type: 0x2, name: "Ruinous Rood" },
  { id: "LigaDoin"                , type: 0x2, name: "Riga Dohin" },
  { id: "TepesOsius"              , type: 0x2, name: "Teps Oceus" },
  { id: "TissRosain"              , type: 0x2, name: "Tis Rozaïn" },
  { id: "FoldShiu"                , type: 0x2, name: "Fald Ciu" },
  { id: "FoldingTurb"             , type: 0x2, name: "Fald Taiab" },
  { id: "EightBitFire"            , type: 0x2, name: "8-bit Fire Ball" },
  { id: "Fireball"                , type: 0x2, name: "Half-Genie Fireball" },
  { id: "STREnhance"              , type: 0x3, name: "Augment STR" },
  { id: "CONEnhance"              , type: 0x3, name: "Augment CON" },
  { id: "INTEnhance"              , type: 0x3, name: "Augment INT" },
  { id: "MNDEnhance"              , type: 0x3, name: "Augment MND" },
  { id: "LUKEnhance"              , type: 0x3, name: "Augment LCK" },
  { id: "EnhancedGOLD"            , type: 0x3, name: "Augment Gold" },
  { id: "KickMastery"             , type: 0x3, name: "Kick Expertise" },
  { id: "KnifeMastery"            , type: 0x3, name: "Dagger Expertise" },
  { id: "SwordMastery"            , type: 0x3, name: "Sword Expertise" },
  { id: "SpearMastery"            , type: 0x3, name: "Spear Expertise" },
  { id: "WhipMastery"             , type: 0x3, name: "Whip Expertise" },
  { id: "GunMastery"              , type: 0x3, name: "Firearm Expertise" },
  { id: "GreatSwordMastery"       , type: 0x3, name: "Greatsword Expertise" },
  { id: "JapanSwordMastery"       , type: 0x3, name: "Katana Expertise" },
  { id: "CraftMastery"            , type: 0x3, name: "Alchemic Bounty" },
  { id: "Resistedge"              , type: 0x3, name: "Resist Slash" },
  { id: "Resistthrust"            , type: 0x3, name: "Resist Thrust" },
  { id: "ResistBrow"              , type: 0x3, name: "Resist Strike" },
  { id: "ResistFire"              , type: 0x3, name: "Resist Fire" },
  { id: "Resistice"               , type: 0x3, name: "Resist Ice" },
  { id: "ResistThunder"           , type: 0x3, name: "Resist Thunder" },
  { id: "ResistHorley"            , type: 0x3, name: "Resist Light" },
  { id: "Resistdark"              , type: 0x3, name: "Resist Darkness" },
  { id: "ResistPoison"            , type: 0x3, name: "Resist Poison" },
  { id: "Resistcurse"             , type: 0x3, name: "Resist Curses" },
  { id: "ResistPetri"             , type: 0x3, name: "Resist Petrification" },
  { id: "Resistmagic"             , type: 0x3, name: "Resist Magic" },
  { id: "Moneyispower"            , type: 0x3, name: "Money Is Power" },
  { id: "RedDowther"              , type: 0x3, name: "Red Remembrance" },
  { id: "LuckyDrop"               , type: 0x3, name: "Pickpocket" },
  { id: "Optimizer"               , type: 0x3, name: "Optimizer" },
  { id: "Wisdomwords"             , type: 0x3, name: "Words of Wisdom" },
  { id: "Regeneration"            , type: 0x3, name: "Regenerate" },
  { id: "Submariner"              , type: 0x3, name: "Amphibian Speed" },
  { id: "drain"                   , type: 0x3, name: "Drain" },
  { id: "DetectiveEye"            , type: 0x3, name: "Detective's Eye" },
  { id: "FamiliaSilverKnight"     , type: 0x4, name: "Silver Knight" },
  { id: "FamiliaCarabos"          , type: 0x4, name: "Carabosse" },
  { id: "FamiliaBuell"            , type: 0x4, name: "Buer" },
  { id: "FamiliaBradBringer"      , type: 0x4, name: "Bloodbringer" },
  { id: "FamiliaDantalion"        , type: 0x4, name: "Dantalion" },
  { id: "SummonDurahanMaHead"     , type: 0x4, name: "Dullahammer Head" },
  { id: "FamiliaBuChan"           , type: 0x4, name: "Bu-chan" },
  { id: "FamiliaArcher"           , type: 0x4, name: "Archer" },
  { id: "Shortcut"                , type: 0x5, name: "Shortcut" },
  { id: "Doublejump"              , type: 0x5, name: "Double Jump" },
  { id: "Deepsinker"              , type: 0x5, name: "Deep Sinker" },
  { id: "Invert"                  , type: 0x5, name: "Invert" },
  { id: "HighJump"                , type: 0x5, name: "High Jump" },
  { id: "SkilledSTREnhance"       , type: 0x5, name: "Augment STR" },
  { id: "SkilledCONEnhance"       , type: 0x5, name: "Augment CON" },
  { id: "SkilledINTEnhance"       , type: 0x5, name: "Augment INT" },
  { id: "SkilledMNDEnhance"       , type: 0x5, name: "Augment MND" },
  { id: "SkilledLUKEnhance"       , type: 0x5, name: "Augment LCK" },
  { id: "SkilledEnhancedGOLD"     , type: 0x5, name: "Augment Gold" },
  { id: "SkilledKickMastery"      , type: 0x5, name: "Kick Expertise" },
  { id: "SkilledKnifeMastery"     , type: 0x5, name: "Dagger Expertise" },
  { id: "SkilledSwordMastery"     , type: 0x5, name: "Sword Expertise" },
  { id: "SkilledSpearMastery"     , type: 0x5, name: "Spear Expertise" },
  { id: "SkilledWhipMastery"      , type: 0x5, name: "Whip Expertise" },
  { id: "SkilledGunMastery"       , type: 0x5, name: "Firearm Expertise" },
  { id: "SkilledGreatSwordMastery", type: 0x5, name: "Greatsword Expertise" },
  { id: "SkilledJapanSwordMastery", type: 0x5, name: "Katana Expertise" },
  { id: "SkilledCraftMastery"     , type: 0x5, name: "Alchemic Bounty" },
  { id: "SkilledResistedge"       , type: 0x5, name: "Resist Slash" },
  { id: "SkilledResistthrust"     , type: 0x5, name: "Resist Thrust" },
  { id: "SkilledResistBrow"       , type: 0x5, name: "Resist Strike" },
  { id: "SkilledResistFire"       , type: 0x5, name: "Resist Fire" },
  { id: "SkilledResistice"        , type: 0x5, name: "Resist Ice" },
  { id: "SkilledResistThunder"    , type: 0x5, name: "Resist Thunder" },
  { id: "SkilledResistHorley"     , type: 0x5, name: "Resist Light" },
  { id: "SkilledResistdark"       , type: 0x5, name: "Resist Darkness" },
  { id: "SkilledResistPoison"     , type: 0x5, name: "Resist Poison" },
  { id: "SkilledResistcurse"      , type: 0x5, name: "Resist Curses" },
  { id: "SkilledResistPetri"      , type: 0x5, name: "Resist Petrification" },
  { id: "SkilledResistmagic"      , type: 0x5, name: "Resist Magic" },
  { id: "SkilledMoneyispower"     , type: 0x5, name: "Money Is Power" },
  { id: "SkilledRedDowther"       , type: 0x5, name: "Red Remembrance" },
  { id: "SkilledLuckyDrop"        , type: 0x5, name: "Pickpocket" },
  { id: "Skilledoptimizer"        , type: 0x5, name: "Optimizer" },
  { id: "SkilledWisdomwords"      , type: 0x5, name: "Words of Wisdom" },
  { id: "SkilledRegeneration"     , type: 0x5, name: "Regenerate" },
  { id: "SkilledSubmariner"       , type: 0x5, name: "Amphibian Speed" },
  { id: "Skilleddrain"            , type: 0x5, name: "Drain" },
  { id: "SkilledDetectiveeye"     , type: 0x5, name: "Detective's Eye" },
];

export const conjureShards: Resource = { "-1": "-" };
export const directionalShards: Resource = { "-1": "-" };
export const familiarShards: Resource = { "-1": "-" };
export const manipulativeShards: Resource = { "-1": "-" };
export const passiveShards: Resource = { "-1": "-" };

shardList.forEach((item, index) => {
  switch (item.type) {
    case 0x0:
      conjureShards[index] = item.name;
      break;
    case 0x1:
      manipulativeShards[index] = item.name;
      break;
    case 0x2:
      directionalShards[index] = item.name;
      break;
    case 0x3:
      passiveShards[index] = item.name;
      break;
    case 0x4:
      familiarShards[index] = item.name;
      break;
  }
});

export const areas = [
  { index: 0x0, areaId: "ACT01_SIP", name: "Galleon Minerva" },
  { index: 0x1, areaId: "ACT02_VIL", name: "Arvantville" },
  { index: 0x2, areaId: "ACT03_ENT", name: "Entrance" },
  { index: 0x3, areaId: "ACT04_GDN", name: "Garden of Silence" },
  { index: 0x4, areaId: "ACT05_SAN", name: "Dian Cécht Cathedral" },
  { index: 0x5, areaId: "ACT06_KNG", name: "Hall of Termination" },
  { index: 0x6, areaId: "ACT07_LIB", name: "Livre Ex Machina" },
  { index: 0x7, areaId: "ACT08_TWR", name: "Towers of Twins Dragons" },
  { index: 0x8, areaId: "ACT09_TRN", name: "Bridge of Evil" },
  { index: 0x9, areaId: "ACT10_BIG", name: "Den of Behemoths" },
  { index: 0xa, areaId: "ACT11_UGD", name: "Forbidden Underground Waterway" },
  { index: 0xb, areaId: "ACT12_SND", name: "Hidden Desert" },
  { index: 0xc, areaId: "ACT13_ARC", name: "Underground Sorcery Lab" },
  { index: 0xd, areaId: "ACT14_TAR", name: "Secret Sorcery Lab" },
  { index: 0xe, areaId: "ACT15_JPN", name: "Oriental Sorcery Lab" },
  { index: 0xf, areaId: "ACT17_RVA", name: "Inferno Cave" },
  { index: 0x10, areaId: "ACT18_ICE", name: "Glacial Tomb" },
];

// prettier-ignore
export const locationList = [
  { roomId: "m01SIP_000" , area: 0x00, coordinates: { x: 3337, y: 0, z: 145 }, name: "Galleon Minerva (Introduction)" },
  { roomId: "m01SIP_1000", area: 0x00, coordinates: { x: 14498, y: 0, z: 175 }, name: "Galleon Minerva (Top)" },
  { roomId: "m01SIP_1001", area: 0x00, coordinates: { x: 14498, y: 0, z: -3425 }, name: "Galleon Minerva (Bottom)" },
  { roomId: "m01SIP_1002", area: 0x00, coordinates: { x: 19538, y: 0, z: 175 }, name: "Galleon Minerva (near Vepar)" },
  { roomId: "m02VIL_1000", area: 0x01, coordinates: { x: 30878, y: 0, z: 175 }, name: "Arvantville" },
  { roomId: "m03ENT_1000", area: 0x02, coordinates: { x: 63638, y: 0, z: 895 }, name: "Entrance" },
  { roomId: "m03ENT_1001", area: 0x02, coordinates: { x: 64897.99609375, y: 0, z: 4495 }, name: "Entrance (near Zangetsu)" },
  { roomId: "m05SAN_1000", area: 0x04, coordinates: { x: 48514, y: 0, z: 4495 }, name: "Dian Cécht Cathedral" },
  { roomId: "m05SAN_1001", area: 0x04, coordinates: { x: 67418, y: 0, z: 7375 }, name: "Dian Cécht Cathedral (near Craftwork)" },
  { roomId: "m05SAN_1002", area: 0x04, coordinates: { x: 72458, y: 0, z: 10975 }, name: "Dian Cécht Cathedral (near Bloodless)" },
  { roomId: "m04GDN_1000", area: 0x03, coordinates: { x: 95134, y: 0, z: 1615 }, name: "Garden of Silence" },
  { roomId: "m07LIB_1000", area: 0x06, coordinates: { x: 87578, y: 0, z: 5215 }, name: "Livre Ex Machina" },
  { roomId: "m07LIB_1001", area: 0x06, coordinates: { x: 90098, y: 0, z: 15295 }, name: "Livre Ex Machina (near Abyssal Guardian)" },
  { roomId: "m08TWR_1001", area: 0x07, coordinates: { x: 97658, y: 0, z: 5215 }, name: "Towers of Twins Dragons" },
  { roomId: "m08TWR_1000", area: 0x07, coordinates: { x: 108998, y: 0, z: 9535 }, name: "Towers of Twins Dragons (near Valac)" },
  { roomId: "m09TRN_1000", area: 0x08, coordinates: { x: 139238, y: 0, z: 1615 }, name: "Bridge of Evil" },
  { roomId: "m13ARC_1000", area: 0x0c, coordinates: { x: 127894, y: 0, z: -1265 }, name: "Underground Sorcery Lab" },
  { roomId: "m11UGD_1003", area: 0x0a, coordinates: { x: 51034, y: 0, z: -2705 }, name: "Forbidden Underground Waterway (West)" },
  { roomId: "m11UGD_1002", area: 0x0a, coordinates: { x: 72454, y: 0, z: -7744.99951171875 }, name: "Forbidden Underground Waterway (Middle-West)" },
  { roomId: "m11UGD_1001", area: 0x0a, coordinates: { x: 83794, y: 0, z: -7025 }, name: "Forbidden Underground Waterway (Middle-East)" },
  { roomId: "m11UGD_1000", area: 0x0a, coordinates: { x: 97658, y: 0, z: -3425 }, name: "Forbidden Underground Waterway (East)" },
  { roomId: "m12SND_1000", area: 0x0b, coordinates: { x: 96394, y: 0, z: -13505 }, name: "Hidden Desert" },
  { roomId: "m14TAR_1000", area: 0x0d, coordinates: { x: 44738, y: 0, z: -8465 }, name: "Secret Sorcery Lab" },
  { roomId: "m17RVA_1000", area: 0x0f, coordinates: { x: 61118, y: 0, z: -14225 }, name: "Inferno Cave" },
  { roomId: "m15JPN_1000", area: 0x0e, coordinates: { x: 47258, y: 0, z: 17455 }, name: "Oriental Sorcery Lab" },
  { roomId: "m06KNG_1001", area: 0x05, coordinates: { x: 80014, y: 0, z: 13855 }, name: "Hall of Termination" },
  { roomId: "m06KNG_1000", area: 0x05, coordinates: { x: 73714, y: 0, z: 17455 }, name: "Hall of Termination (near Gebel)" },
  { roomId: "m10BIG_1000", area: 0x09, coordinates: { x: 149318, y: 0, z: 5935 }, name: "Den of Behemoths" },
  { roomId: "m18ICE_1000", area: 0x10, coordinates: { x: 146798, y: 0, z: -5585 }, name: "Glacial Tomb" },
  { roomId: "m18ICE_1001", area: 0x10, coordinates: { x: 139238, y: 0, z: -7025 }, name: "Glacial Tomb (near Dominique)" },
];

export const locations: Resource = {};
export const locationsGroups: ResourceGroups = [];

areas.forEach((area) => {
  locationsGroups.push({ name: area.name, options: [] });
});

locationList.forEach((location, index) => {
  locations[index] = location.name;
  locationsGroups[location.area].options.push(index);
});

export const techniqueList = [
  { index: 0xe, name: "Assassinate", experience: 5000 },
  { index: 0xf, name: "Surprise Gift", experience: 8000 },
  { index: 0x2f, name: "Power Slash", experience: 5000 },
  { index: 0x1, name: "Force Blast", experience: 12000 },
  { index: 0x24, name: "Parry", experience: 5000 },
  { index: 0x10, name: "Back Steal", experience: 0 },
  { index: 0x26, name: "Sickle Moon", experience: 8000 },
  { index: 0x1b, name: "Trucidating Gyre", experience: 5000 },
  { index: 0x13, name: "Thousand Blossoms", experience: 50000 },
  { index: 0x14, name: "Lasting Wound", experience: 8000 },
  { index: 0x15, name: "Orbital Wheel", experience: 5000 },
  { index: 0x16, name: "Penetrate", experience: 8000 },
  { index: 0x17, name: "Lunging Serpent", experience: 0 },
  { index: 0x5, name: "Flashing Air Kick", experience: 5000 },
  { index: 0x18, name: "Hatchet Heel", experience: 8000 },
  { index: 0x1c, name: "Critical Swing", experience: 5000 },
  { index: 0x1f, name: "Jinrai", experience: 8000 },
  { index: 0x1e, name: "Helmsplitter", experience: 5000 },
  { index: 0x22, name: "Crimson Storm", experience: 8000 },
  { index: 0x21, name: "Crescent Stroke", experience: 5000 },
  { index: 0x25, name: "Eleventh Hour", experience: 5000 },
  { index: 0x20, name: "Sansetsuzan", experience: 5000 },
  { index: 0x23, name: "Rapid Fire", experience: 8000 },
];
