import type { GameJson } from "$lib/types";

import { items } from "./utils/resource";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa_japan: {
        0x0: [0x53, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x33, 0x31, 0x5f], // "SFORCE31_"
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    hint: "Scenarios 2 and 3 will be available later.",
    error: "Not a valid save file.",
  },
  items: [
    {
      id: "slots",
      length: 0x0,
      type: "container",
      instanceType: "tabs",
      instances: 0,
      enumeration: "Slot %d",
      items: [
        {
          id: "checksum",
          name: "Checksum",
          offset: 0x2a,
          type: "checksum",
          dataType: "uint16",
          bigEndian: true,
          control: {
            offsetStart: 0x2c,
            offsetEnd: 0x328c,
          },
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              flex: true,
              items: [
                {
                  name: "Filename",
                  offset: 0x10,
                  length: 0x7,
                  type: "variable",
                  dataType: "string",
                  letterDataType: "uint8",
                  fallback: 0x20,
                  resource: "letters",
                },
                {
                  name: "Play Time",
                  type: "group",
                  mode: "time",
                  items: [
                    {
                      offset: 0x34,
                      type: "variable",
                      dataType: "uint32",
                      operations: [
                        { "/": 60 },
                        { convert: { from: "seconds", to: "hours" } },
                      ],
                      max: 999,
                      bigEndian: true,
                    },
                    {
                      offset: 0x34,
                      type: "variable",
                      dataType: "uint32",
                      operations: [
                        { "/": 60 },
                        { convert: { from: "seconds", to: "minutes" } },
                      ],
                      max: 59,
                      leadingZeros: 1,
                      bigEndian: true,
                    },
                    {
                      offset: 0x34,
                      type: "variable",
                      dataType: "uint32",
                      operations: [
                        { "/": 60 },
                        { convert: { from: "seconds", to: "seconds" } },
                      ],
                      max: 59,
                      leadingZeros: 1,
                      bigEndian: true,
                    },
                  ],
                },
                {
                  name: "Gold",
                  offset: 0x3c,
                  type: "variable",
                  dataType: "uint32",
                  bigEndian: true,
                  max: 999999,
                },
                {
                  id: "location",
                  name: "Location",
                  offset: 0x41,
                  type: "variable",
                  dataType: "uint8",
                  resource: "locations",
                  size: "lg",
                  autocomplete: true,
                },
                {
                  name: "Linked to Location",
                  offset: 0x45,
                  type: "variable",
                  dataType: "uint8",
                  resource: "locations",
                  hidden: true,
                },
              ],
            },
            {
              name: "Party",
              items: [
                {
                  length: 0xb0,
                  type: "container",
                  instanceType: "tabs",
                  instances: 20,
                  resource: "characters",
                  vertical: true,
                  items: [
                    {
                      type: "tabs",
                      items: [
                        {
                          name: "Status",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Name",
                                  offset: 0x241c,
                                  length: 0x8,
                                  type: "variable",
                                  dataType: "string",
                                  letterDataType: "uint8",
                                  resource: "letters",
                                  test: true,
                                },
                                {
                                  name: "Class",
                                  offset: 0x2494,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "classes",
                                  autocomplete: true,
                                },
                                {
                                  name: "Gender",
                                  offset: 0x242b,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "genders",
                                },
                                {
                                  name: "Control Type",
                                  offset: 0x24b3,
                                  type: "variable",
                                  dataType: "uint8",
                                  resource: "controlTypes",
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Level",
                                  offset: 0x242f,
                                  type: "variable",
                                  dataType: "uint8",
                                  min: 1,
                                  max: 99,
                                },
                                {
                                  name: "Experience",
                                  offset: 0x24b1,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 99,
                                },
                                {
                                  name: "HP",
                                  type: "group",
                                  mode: "fraction",
                                  items: [
                                    {
                                      offset: 0x249e,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      max: 999,
                                    },
                                    {
                                      offset: 0x242c,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      min: 1,
                                      max: 999,
                                    },
                                  ],
                                },
                                {
                                  name: "MP",
                                  type: "group",
                                  mode: "fraction",
                                  items: [
                                    {
                                      offset: 0x24a0,
                                      type: "variable",
                                      dataType: "uint8",
                                    },
                                    {
                                      offset: 0x242e,
                                      type: "variable",
                                      dataType: "uint8",
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Attack",
                                  offset: 0x2430,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  name: "Defense",
                                  offset: 0x2431,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  name: "Agility",
                                  offset: 0x2432,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  name: "Speed",
                                  offset: 0x2433,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  name: "Luck",
                                  offset: 0x2434,
                                  type: "variable",
                                  dataType: "uint8",
                                },
                                {
                                  name: "Move",
                                  offset: 0x24a4,
                                  type: "variable",
                                  dataType: "uint8",
                                  max: 15,
                                },
                              ],
                            },
                            {
                              name: "Condition",
                              type: "section",
                              background: true,
                              items: [
                                {
                                  name: "Alive",
                                  offset: 0x24b5,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Asleep",
                                  offset: 0x24b6,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Confused",
                                  offset: 0x24b7,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Illusion",
                                  offset: 0x24b8,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Silenced",
                                  offset: 0x24b9,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Paralyzed",
                                  offset: 0x24ba,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Poisoned",
                                  offset: 0x24bb,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Charmed",
                                  offset: 0x24bc,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Cursed",
                                  offset: 0x24be,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Berserk",
                                  offset: 0x30,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                                {
                                  name: "Frozen",
                                  offset: 0x31,
                                  type: "variable",
                                  dataType: "boolean",
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Magic",
                          flex: true,
                          items: [
                            {
                              type: "section",
                              items: [
                                {
                                  name: "Spells",
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Spell 1",
                                      offset: 0x2440,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "spells",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Level",
                                      offset: 0x2441,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 4,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Spell 2",
                                      offset: 0x2442,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "spells",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Level",
                                      offset: 0x2443,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 4,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Spell 3",
                                      offset: 0x2444,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "spells",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Level",
                                      offset: 0x2445,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 4,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Spell 4",
                                      offset: 0x2446,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "spells",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Level",
                                      offset: 0x2447,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 4,
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              name: "Magic Resistance",
                              type: "section",
                              items: [
                                {
                                  name: "Fire",
                                  offset: 0x24aa,
                                  type: "variable",
                                  dataType: "int8",
                                },
                                {
                                  name: "Lightning",
                                  offset: 0x24ac,
                                  type: "variable",
                                  dataType: "int8",
                                },
                                {
                                  name: "Light",
                                  offset: 0x24ae,
                                  type: "variable",
                                  dataType: "int8",
                                },
                              ],
                            },
                            {
                              name: "&nbsp;",
                              type: "section",
                              items: [
                                {
                                  name: "Ice",
                                  offset: 0x24ab,
                                  type: "variable",
                                  dataType: "int8",
                                },
                                {
                                  name: "Wind",
                                  offset: 0x24ad,
                                  type: "variable",
                                  dataType: "int8",
                                },
                                {
                                  name: "Darkness",
                                  offset: 0x24af,
                                  type: "variable",
                                  dataType: "int8",
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Items",
                          items: [
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Weapon",
                                  type: "group",
                                  items: [
                                    {
                                      offset: 0x2448,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 14,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      offset: 0x2448,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 6,
                                      resource: "itemStates",
                                    },
                                  ],
                                },
                                {
                                  name: "Accessory",
                                  type: "group",
                                  items: [
                                    {
                                      offset: 0x244a,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 14,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      offset: 0x244a,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 6,
                                      resource: "itemStates",
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              noMargin: true,
                              items: [
                                {
                                  name: "Item 1",
                                  type: "group",
                                  items: [
                                    {
                                      offset: 0x244c,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 14,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      offset: 0x244c,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 6,
                                      resource: "itemStates",
                                    },
                                  ],
                                },
                                {
                                  name: "Item 2",
                                  type: "group",
                                  items: [
                                    {
                                      offset: 0x244e,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 14,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      offset: 0x244e,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 6,
                                      resource: "itemStates",
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              type: "section",
                              flex: true,
                              items: [
                                {
                                  name: "Item 3",
                                  type: "group",
                                  items: [
                                    {
                                      offset: 0x2450,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 14,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      offset: 0x2450,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 6,
                                      resource: "itemStates",
                                    },
                                  ],
                                },
                                {
                                  name: "Item 4",
                                  type: "group",
                                  items: [
                                    {
                                      offset: 0x2452,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                      binary: {
                                        bitStart: 0,
                                        bitLength: 14,
                                      },
                                      resource: "items",
                                      autocomplete: true,
                                    },
                                    {
                                      offset: 0x2452,
                                      type: "variable",
                                      dataType: "bit",
                                      bit: 6,
                                      resource: "itemStates",
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Weapons",
                          items: [
                            {
                              name: "Type 1",
                              type: "section",
                              items: [
                                {
                                  type: "section",
                                  flex: true,
                                  noMargin: true,
                                  items: [
                                    {
                                      name: "Type",
                                      offset: 0x247e,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "itemTypes",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Level",
                                      offset: 0x247f,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 3,
                                    },
                                    {
                                      name: "Experience",
                                      offset: 0x2480,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Special 1",
                                      offset: 0x2454,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Special 2",
                                      offset: 0x2455,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Special 3",
                                      offset: 0x2456,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              name: "Type 2",
                              type: "section",
                              items: [
                                {
                                  type: "section",
                                  flex: true,
                                  noMargin: true,
                                  items: [
                                    {
                                      name: "Type",
                                      offset: 0x2482,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "itemTypes",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Level",
                                      offset: 0x2483,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 3,
                                    },
                                    {
                                      name: "Experience",
                                      offset: 0x2484,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Special 1",
                                      offset: 0x2457,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Special 2",
                                      offset: 0x2458,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Special 3",
                                      offset: 0x2459,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              name: "Type 3",
                              type: "section",
                              items: [
                                {
                                  type: "section",
                                  flex: true,
                                  noMargin: true,
                                  items: [
                                    {
                                      name: "Type",
                                      offset: 0x2486,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "itemTypes",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Level",
                                      offset: 0x2487,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 3,
                                    },
                                    {
                                      name: "Experience",
                                      offset: 0x2488,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Special 1",
                                      offset: 0x245a,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Special 2",
                                      offset: 0x245b,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Special 3",
                                      offset: 0x245c,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              name: "Type 4",
                              type: "section",
                              items: [
                                {
                                  type: "section",
                                  flex: true,
                                  noMargin: true,
                                  items: [
                                    {
                                      name: "Type",
                                      offset: 0x248a,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "itemTypes",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Level",
                                      offset: 0x248b,
                                      type: "variable",
                                      dataType: "uint8",
                                      max: 3,
                                    },
                                    {
                                      name: "Experience",
                                      offset: 0x248c,
                                      type: "variable",
                                      dataType: "uint16",
                                      bigEndian: true,
                                    },
                                  ],
                                },
                                {
                                  type: "section",
                                  flex: true,
                                  items: [
                                    {
                                      name: "Special 1",
                                      offset: 0x245d,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Special 2",
                                      offset: 0x245e,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                    {
                                      name: "Special 3",
                                      offset: 0x245f,
                                      type: "variable",
                                      dataType: "uint8",
                                      resource: "specialAttacks",
                                      autocomplete: true,
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          id: "friendship",
                          name: "Friendship",
                          flex: true,
                          items: [
                            {
                              name: "Dummy",
                              offset: 0x5d0,
                              type: "variable",
                              dataType: "uint8",
                              max: 45,
                              overrideShift: {
                                parent: 1,
                                shift: 0x0,
                              },
                            },
                          ],
                        },
                        {
                          name: "Miscellaneous",
                          flex: true,
                          items: [
                            {
                              name: "Kills",
                              offset: 0x2496,
                              type: "variable",
                              dataType: "uint16",
                              bigEndian: true,
                              max: 1000,
                            },
                            {
                              name: "Loses",
                              offset: 0x2495,
                              type: "variable",
                              dataType: "uint8",
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Formation",
              flex: true,
              items: [
                {
                  name: "Synbios",
                  offset: 0x1d0,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Dantares",
                  offset: 0x1d0,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
                {
                  name: "Masqurin",
                  offset: 0x1d1,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Grace",
                  offset: 0x1d1,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
                {
                  name: "Hayward",
                  offset: 0x1d2,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Obright",
                  offset: 0x1d2,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
                {
                  name: "Irene",
                  offset: 0x1d3,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Julian",
                  offset: 0x1d3,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
                {
                  name: "Cybel",
                  offset: 0x1d4,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Eldar",
                  offset: 0x1d4,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
                {
                  name: "Kahn",
                  offset: 0x1d5,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Noon",
                  offset: 0x1d5,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
                {
                  name: "Justin",
                  offset: 0x1d6,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Horst",
                  offset: 0x1d6,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
                {
                  name: "Penn",
                  offset: 0x1d7,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Ratchet",
                  offset: 0x1d7,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
                {
                  name: "Frank",
                  offset: 0x1d8,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Hagane",
                  offset: 0x1d8,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
                {
                  name: "Murasame",
                  offset: 0x1d9,
                  type: "variable",
                  dataType: "lower4",
                  resource: "formations",
                },
                {
                  name: "Fynnding",
                  offset: 0x1d9,
                  type: "variable",
                  dataType: "upper4",
                  resource: "formations",
                },
              ],
            },
            {
              name: "Headquarters Inventory",
              flex: true,
              items: Object.entries(items).map(([offset, name]) => ({
                name,
                offset: 0x3d0 + parseInt(offset),
                type: "variable",
                dataType: "uint8",
                max: 99,
              })),
            },
            {
              name: "Stores",
              planned: true,
              items: [],
            },
            {
              name: "Events",
              planned: true,
              items: [
                {
                  type: "bitflags",
                  flags: [
                    { offset: 0x295, bit: 0, label: "Talk after Bulsome 4 talk" },
                    { offset: 0x2f9, bit: 3, label: "Balsamo Inn Chest" },
                    { offset: 0x310, bit: 5, label: "Balsamo House 1 5 Gold" },
                  ],
                },
              ],
            },
            {
              name: "Options",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Message Speed",
                      offset: 0x12c,
                      type: "variable",
                      dataType: "uint8",
                      resource: "messageSpeeds",
                    },
                    {
                      name: "Message Shadow",
                      offset: 0x128,
                      type: "variable",
                      dataType: "uint8",
                      resource: "optionBoolean",
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Window Color",
                      offset: 0x125,
                      type: "variable",
                      dataType: "uint8",
                      max: 23,
                    },
                    {
                      name: "Window Brightness",
                      offset: 0x126,
                      type: "variable",
                      dataType: "uint8",
                      max: 15,
                    },
                    {
                      name: "Window Transparency",
                      offset: 0x129,
                      type: "variable",
                      dataType: "uint8",
                      max: 15,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Sound",
                      offset: 0x12d,
                      type: "variable",
                      dataType: "uint8",
                      resource: "sounds",
                    },
                    {
                      name: "Voice",
                      offset: 0x12a,
                      type: "variable",
                      dataType: "uint8",
                      resource: "optionBoolean",
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Auto Camera Angle",
                      offset: 0x14b,
                      type: "variable",
                      dataType: "uint8",
                      resource: "optionBoolean",
                    },
                    {
                      name: "Auto Camera Angle",
                      offset: 0x1f4,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Battle Guide",
                      offset: 0x14d,
                      type: "variable",
                      dataType: "uint8",
                      resource: "optionBoolean",
                    },
                    {
                      name: "Battle Message",
                      offset: 0x12b,
                      type: "variable",
                      dataType: "uint8",
                      resource: "optionBoolean",
                    },
                  ],
                },
                {
                  name: "Battle Difficulty",
                  offset: 0x1f3,
                  type: "variable",
                  dataType: "uint8",
                  resource: "difficulties",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    characters: {
      0x0: "Synbios",
      0x1: "Dantares",
      0x2: "Masqurin",
      0x3: "Grace",
      0x4: "Hayward",
      0x5: "Obright",
      0x6: "Irene",
      0x7: "Julian",
      0x8: "Cybel",
      0x9: "Eldar",
      0xa: "Kahn",
      0xb: "Noon",
      0xc: "Justin",
      0xd: "Horst",
      0xe: "Penn",
      0xf: "Ratchet",
      0x10: "Frank",
      0x11: "Hagane",
      0x12: "Murasame",
      0x13: "Fynnding",
    },
    classes: {
      0x0: "Soldier",
      0x1: "Knight",
      0x2: "Warrior",
      0x3: "Priest",
      0x4: "Magician",
      0x5: "Archer",
      0x6: "Monk",
      0x7: "Birdsoldier",
      0x8: "Ranger",
      0x9: "Penguin",
      0x20: "Swordman",
      0x21: "Cavalier",
      0x22: "Gladiator",
      0x23: "Cleric",
      0x24: "Wizard",
      0x25: "Marksman",
      0x26: "Master Monk",
      0x27: "Birdknight",
      0x28: "Bow Knight",
      0x29: "Emperor Penn",
      0x2a: "Steam Knight",
      0x2b: "Werewolf",
      0x2c: "Ninja",
      0x40: "Swordmaster",
      0x41: "Paladin",
      0x42: "Berseker",
      0x43: "Holy Knight",
      0x44: "Sorcerer",
      0x45: "Sumonner",
    },
    controlTypes: {
      0x0: "Player",
      0x1: "Enemy",
      0x3: "Passive Enemy",
      0x4: "Uncontrolled Recruit",
      0x5: "Uncontrolled Friend",
      0x6: "Uncontroller Ally",
      0x9: "Object",
    },
    difficulties: {
      0x0: "Standard",
      0x10: "Hard",
      0x20: "Difficult",
      0x30: "Insane",
    },
    formations: {
      0x0: "-",
      0x1: "Main Squad",
      0x2: "Reserve",
    },
    genders: {
      0x1: "Male",
      0x2: "Female",
    },
    items: {
      0x0: "-",
      ...items,
    },
    itemStates: {
      0x0: "-",
      0x1: "Broken",
    },
    itemTypes: {
      0x0: "-",
      0xa: "Dagger",
      0xb: "Sword",
      0xc: "Rapier",
      0xd: "Blade",
      0xe: "Katana",
      0xf: "Wing",
      0x14: "Lance",
      0x15: "Spear",
      0x16: "Halberd",
      0x1e: "Axe",
      0x1f: "Tomahawk",
      0x20: "Mace",
      0x21: "Anchor",
      0x32: "Claw",
      0x33: "Glove",
      0x34: "Knuckle",
      0x3c: "Rod",
      0x3d: "Wand",
      0x3e: "Ankh",
      0x46: "Arrow",
      0x47: "Quarrel",
      0x48: "Shell",
      0x4a: "Shuriken",
      0x50: "Beak",
    },
    letters: {
      0x20: " ",
      0x21: "!",
      0x23: "#",
      0x26: "&",
      0x27: "'",
      0x2b: "+",
      0x2d: "-",
      0x30: "0",
      0x31: "1",
      0x32: "2",
      0x33: "3",
      0x34: "4",
      0x35: "5",
      0x36: "6",
      0x37: "7",
      0x38: "8",
      0x39: "9",
      0x3f: "?",
      0x41: "A",
      0x42: "B",
      0x43: "C",
      0x44: "D",
      0x45: "E",
      0x46: "F",
      0x47: "G",
      0x48: "H",
      0x49: "I",
      0x4a: "J",
      0x4b: "K",
      0x4c: "L",
      0x4d: "M",
      0x4e: "N",
      0x4f: "O",
      0x50: "P",
      0x51: "Q",
      0x52: "R",
      0x53: "S",
      0x54: "T",
      0x55: "U",
      0x56: "V",
      0x57: "W",
      0x58: "X",
      0x59: "Y",
      0x5a: "Z",
      0x61: "a",
      0x62: "b",
      0x63: "c",
      0x64: "d",
      0x65: "e",
      0x66: "f",
      0x67: "g",
      0x68: "h",
      0x69: "i",
      0x6a: "j",
      0x6b: "k",
      0x6c: "l",
      0x6d: "m",
      0x6e: "n",
      0x6f: "o",
      0x70: "p",
      0x71: "q",
      0x72: "r",
      0x73: "s",
      0x74: "t",
      0x75: "u",
      0x76: "v",
      0x77: "w",
      0x78: "x",
      0x79: "y",
      0x7a: "z",
      0x86: "を",
      0x87: "ぁ",
      0x88: "ぃ",
      0x89: "ぅ",
      0x8a: "ぇ",
      0x8b: "ぉ",
      0x8c: "ゃ",
      0x8d: "ゅ",
      0x8e: "ょ",
      0x8f: "っ",
      0x91: "あ",
      0x92: "い",
      0x93: "う",
      0x94: "え",
      0x95: "お",
      0x96: "か",
      0x97: "き",
      0x98: "く",
      0x99: "け",
      0x9a: "こ",
      0x9b: "さ",
      0x9c: "し",
      0x9d: "す",
      0x9e: "せ",
      0x9f: "そ",
      0xa1: ".",
      0xa4: ",",
      0xa6: "ヲ",
      0xa7: "ァ",
      0xa8: "ィ",
      0xa9: "ゥ",
      0xaa: "ェ",
      0xab: "ォ",
      0xac: "ャ",
      0xad: "ュ",
      0xae: "ョ",
      0xaf: "ッ",
      0xb0: "ー",
      0xb1: "ア",
      0xb2: "イ",
      0xb3: "ウ",
      0xb4: "エ",
      0xb5: "オ",
      0xb6: "カ",
      0xb7: "キ",
      0xb8: "ク",
      0xb9: "ケ",
      0xba: "コ",
      0xbb: "サ",
      0xbc: "シ",
      0xbd: "ス",
      0xbe: "セ",
      0xbf: "ソ",
      0xc0: "タ",
      0xc1: "チ",
      0xc2: "ツ",
      0xc3: "テ",
      0xc4: "ト",
      0xc5: "ナ",
      0xc6: "ニ",
      0xc7: "ヌ",
      0xc8: "ネ",
      0xc9: "ノ",
      0xca: "ハ",
      0xcb: "ヒ",
      0xcc: "フ",
      0xcd: "ヘ",
      0xce: "ホ",
      0xcf: "マ",
      0xd0: "ミ",
      0xd1: "ム",
      0xd2: "メ",
      0xd3: "モ",
      0xd4: "ヤ",
      0xd5: "ユ",
      0xd6: "ヨ",
      0xd7: "ラ",
      0xd8: "リ",
      0xd9: "ル",
      0xda: "レ",
      0xdb: "ロ",
      0xdc: "ワ",
      0xdd: "ン",
      0xde: '"',
      0xdf: "°",
      0xe0: "た",
      0xe1: "ち",
      0xe2: "つ",
      0xe3: "て",
      0xe4: "と",
      0xe5: "な",
      0xe6: "に",
      0xe7: "ぬ",
      0xe8: "ね",
      0xe9: "の",
      0xea: "は",
      0xeb: "ひ",
      0xec: "ふ",
      0xed: "へ",
      0xee: "ほ",
      0xef: "ま",
      0xf0: "み",
      0xf1: "む",
      0xf2: "め",
      0xf3: "も",
      0xf4: "や",
      0xf5: "ゆ",
      0xf6: "よ",
      0xf7: "ら",
      0xf8: "り",
      0xf9: "る",
      0xfa: "れ",
      0xfb: "ろ",
      0xfc: "わ",
      0xfd: "ん",
    },
    locations: {
      0x0: "(Measurement Test) (TESMAP)",
      0x1: "(Store Test) (SHOP_T)",
      0x2: "OP Movie (OPMOVIE)",
      0x3: "Logo Screen (LOGO)",
      0x4: "Sleepy Wise Man (DREAM)",
      0x5: "Ending (ENDING)",
      0x6: "Saraband Streets (BTL101)",
      0x7: "Saraband Bridge (BTL102)",
      0x8: "Balsamo East Plains (BTL103)",
      0x9: "Dwarf Valley (BTL104)",
      0xa: "Dwarf Hill (BTL105)",
      0xb: "Luggage Check (BTL106)",
      0xc: "North Plain Railroad (BTL107)",
      0xd: "Switching Point (BTL108)",
      0xe: "Battle Inside Train (BTL109)",
      0xf: "The Train's Roof (BTL110)",
      0x10: "Quonus Graveyard (BTL111)",
      0x11: "Vandal Mansion (BTL112)",
      0x12: "Border South W Plains (BTL113)",
      0x13: "Barrand North Plateau (BTL114)",
      0x14: "Suspension Bridge (BTL115)",
      0x15: "Aspinia West Plains (BTL116)",
      0x16: "Aspinia S Desert Area (BTL117)",
      0x17: "Volcano Hole (BTL118)",
      0x18: "Aspinia East Plains (BTL119)",
      0x19: "In Flagard Castle (BTL120)",
      0x1a: "Flagard N Ridge Road (BTL121)",
      0x1b: "Tower of Lookover (BTL122)",
      0x1c: "Great Wall (BTL123)",
      0x1d: "Malorie North Marsh (BTL124)",
      0x1e: "In Malorie Castle (BTL125)",
      0x1f: "Aspia Castle Wall (BTL126)",
      0x20: "Aspia Catacombs (BTL127)",
      0x21: "King's city Battle (BTL128)",
      0x22: "King's city Battle (BTL129)",
      0x23: "Unused Battles (BTL197)",
      0x24: "On Roof of FSS Train (BTL198)",
      0x25: "FSS Suspension Bridge (BTL199)",
      0x26: "Opening 1 (OP101)",
      0x27: "Opening 2 (OP102)",
      0x28: "Opening 3 (OP103)",
      0x29: "Saraband Centre (SARA02)",
      0x2a: "Saraband East (SARA03)",
      0x2b: "Saraband West (SARA04)",
      0x2c: "Saraband Church (CHUR01)",
      0x2d: "Saraband Bar (BAR01)",
      0x2e: "Saraband HQ (JIN01)",
      0x2f: "Saraband Indoor Shop (S_SHOP)",
      0x30: "Saraband Indoor 1 (S_RM01)",
      0x31: "Saraband Indoor 2 (S_RM02",
      0x32: "Saraband Indoor 3 (S_RM03)",
      0x33: "Saraband Centre (SARA10)",
      0x34: "Saraband East (SARA11)",
      0x35: "Saraband Indoor 1 (S_RM11)",
      0x36: "Saraband Pier (SARA06)",
      0x37: "Saraband East (SARA21)",
      0x38: "Saraband Indoor 2 (S_RM22)",
      0x39: "Saraband Indoor 3 (S_RM23)",
      0x3a: "Town of Balsamo (BALSA)",
      0x3b: "Balsamo Indoor 1 (BAL_1)",
      0x3c: "Balsamo Indoor 2 (BAL_2)",
      0x3d: "Balsamo Indoor 3 (BAL_3)",
      0x3e: "Balsamo Indoor 4 (BAL_4)",
      0x3f: "Balsamo Indoor 5 (BAL_5)",
      0x40: "Balsamo Indoor 6 (BAL_6)",
      0x41: "Balsamo Indoor 7 (BAL_7)",
      0x42: "Balsamo Indoor 8 (BAL_8)",
      0x43: "Balsamo Indoor 9 (BAL_9)",
      0x44: "Balsamo Church (BALCHR)",
      0x45: "Balsamo Headquarters (BAL_JIN)",
      0x46: "Switching Point (T_BTL108)",
      0x47: "Switching Point (T_BTL08B)",
      0x48: "Segale Valley Train (END200)",
      0x49: "Balsamo East Plains (BTL02)",
      0x4a: "Dwarf Valley (BTL03)",
      0x4b: "Dwarf Valley (BTL04)",
      0x4c: "North Plain Railroad (BTL06)",
      0x4d: "Border S W Plains (BTL12)",
      0x4e: "Barrand N Plateau (BTL13)",
      0x4f: "Aspinia West Plains (BTL19)",
      0x50: "Aspinia S Desert Area (BTL17)",
      0x51: "Aspinia East Plains (BTL019)",
      0x52: "Flagard N Ridge Road (BTL21)",
      0x53: "Malorie North Marsh (BTL24)",
      0x54: "Aspia Castle Wall (BTL26)",
      0x55: "Quonus Village (OBAKE)",
      0x56: "Quonus Village (OBAKEN)",
      0x57: "Quonus Indoor (OBA_IN)",
      0x58: "Quonus Village Church (OBA_CHUR)",
      0x59: "Quonus HQ (OBA_JIN)",
      0x5a: "Quonus Graveyard (BOCHI)",
      0x5b: "Quonus Graveyard (BOCHIM)",
      0x5c: "Quonus Mansion (YAKATA)",
      0x5d: "Quonus Mansion 2F (YAKA2)",
      0x5e: "Mansion Research (YAKA3)",
      0x5f: "Mansion Kitchen (YAKA4)",
      0x60: "Battle at Bridge (TURI01)",
      0x61: "Over the border (END300)",
      0x62: "Vagabond (BAKA)",
      0x63: "Vagabond (BAKA2)",
      0x64: "Vagabond Indoors (BAKAIN)",
      0x65: "Vagabond HQ (BAKA_H)",
      0x66: "Railhead Town (RAIL1)",
      0x67: "Railhead station (EKI)",
      0x68: "Railhead Terminal (HOME)",
      0x69: "Railhead Indoor 1 (HEYA1)",
      0x6a: "Railhead Indoor 2 (HEYA2)",
      0x6b: "Railhead HQ (RAIL_H)",
      0x6c: "Railhead Church (RAIL_C)",
      0x6d: "Train, 2nd cart (GDI4)",
      0x6e: "Train, 3rd cart (GDI5)",
      0x6f: "Train, 4th cart (GDI6)",
      0x70: "Train to Valley (TANIDA)",
      0x71: "Flagard (RINO)",
      0x72: "Flagard Indoors (RINOIN)",
      0x73: "Flagard Church (RINCHR)",
      0x74: "Flagard Headquarters (RINJIN)",
      0x75: "In Flagard Castle (FURAIN)",
      0x76: "In Flagard Castle (FURIN2)",
      0x77: "In Flagard Castle (FURIN3)",
      0x78: "In Flagard Castle (FURIN4)",
      0x79: "In Aspia Castle Wall (FED06)",
      0x7a: "Over the castle Moat (Z_AS)",
      0x7b: "Aspia Village (JOUSAI)",
      0x7c: "Aspia Castle (ASCASL)",
      0x7d: "Aspia Roof (AS_OKU)",
      0x7e: "Aspia Indoor 1 (A_RM01)",
      0x7f: "Aspia Indoor 2 (A_RM02)",
      0x80: "Aspia Headquarters (ASPI_H)",
      0x81: "Aspia Church (ASPI_C)",
      0x82: "Storich (STRI)",
      0x83: "Storich Indoor (STRIIN)",
      0x84: "Storich Headqurters (STRI_H)",
      0x85: "Storich Church (STRIC_C)",
      0x86: "Tower of Lookover (TOMT00)",
      0x87: "On Tower Top (TOUE00)",
      0x88: "Lookover Village (OBU)",
      0x89: "Lookover Indoor (OBROOM)",
      0x8a: "Lookover Headquarters (OBHONJ)",
      0x8b: "Lookover Church (OBCHUR)",
      0x8c: "Great Wall (CHOU00)",
      0x8d: "Malorie (MARY)",
      0x8e: "In Malorie Castle (MAROIN)",
      0x8f: "In Malorie Castle (MARO2)",
      0x90: "Battle of Malorie (MY_BTL)",
      0x91: "Malorie Indoor (MY_RM)",
      0x92: "Malorie Indoor (MY_RM2)",
      0x93: "Malorie Bar (MY_BAR)",
      0x94: "Malorie Headquaters (MARO_H)",
      0x95: "Malorie Church (MARO_C)",
      0x96: "Catacombs (INKA00)",
      0x97: "Dam (DAM)",
      0x98: "Ancient Shrine (BTL130)",
      0x99: "Ancient Shrine (BTL131)",
      0x9a: "Ancient Shrine (BTL132)",
      0x9b: "Ancient Shrine (BTL133)",
      0x9c: "Ancient Shrine (ZLV1)",
      0x9d: "Ancient Shrine (ZLV2)",
      0x9e: "Ancient Shrine (ZLV3)",
      0x9f: "Ancient Shrine (ZLV4)",
      0xa0: "COMPLETE (COMPLETE)",
      0xa1: "(Thief's Map 1) (SHIEF1)",
      0xa2: "(Thief's Map 2) (SHIEF2)",
      0xa3: "(Thief's Map 3) (SHIEF3)",
      0xa4: "(Thief's Map 4) (SHIEF4)",
      0xa5: "Tower Ruins (SHIEF5)",
      0xa6: "(Thief's Map 6) (ZOKU00)",
      0xa7: "Aboard Sailing Ship (HNSN00)",
      0xa8: "Fort (TORI00)",
      0xa9: "Inside Fort (TNKA00)",
      0xaa: "Picture above ground (NASU00)",
      0xab: "Tree (TREE00)",
      0xac: "Wave (SHIO00)",
    },
    messageSpeeds: {
      0x0: "Slow",
      0x1: "Normal",
      0x2: "Fast",
      0x3: "Fastest",
    },
    optionBoolean: {
      0x0: "Off",
      0x1: "On",
    },
    sounds: {
      0x0: "Mono",
      0x1: "Stereo",
    },
    spells: {
      0x0: "-",
      0x1: "Blaze",
      0x2: "Freeze",
      0x3: "Spark",
      0x4: "Tornado",
      0x5: "Soul Stl",
      0x6: "Inferno",
      0x7: "Support",
      0x8: "Slow",
      0x9: "Pacify",
      0xa: "Resist",
      0xb: "Attack",
      0xc: "Dispel",
      0xd: "Confuse",
      0xe: "Sleep",
      0xf: "Charm",
      0x10: "Tsunami",
      0x11: "Heal",
      0x12: "Aura",
      0x13: "Chant",
      0x14: "Antidote",
      0x15: "Return",
      0x26: "Phoenix",
      0x27: "Wendigo",
      0x28: "Tiamat",
      0x29: "Tanatos",
    },
    specialAttacks: {
      0x0: "-",
      0x1: "Critical Hit",
      0x2: "Counter",
      0x3: "Slow Attack",
      0x4: "Sleep Attack",
      0x5: "Confuse Atk",
      0x6: "Illusion Atk",
      0x7: "Dispel Atk",
      0x8: "Paralyze Atk",
      0x9: "Poison Atk",
      0xa: "Poison Atk",
      0xb: "Charm Attack",
      0xc: "Cold Attack",
      0xd: "Maximal Atk",
      0xe: "Armor Attack",
      0xf: "Beserk",
      0x10: "Blood Sucker",
      0x11: "Regret Hit",
      0x14: "Shadow Edge",
      0x15: "Twin Slash",
      0x16: "Laser Edge",
      0x17: "Rainbow Edge",
      0x18: "Silent Kill",
      0x19: "Sonic Wave",
      0x1a: "Twin Wave",
      0x1b: "Mirage Dance",
      0x1c: "ThunderShock",
      0x1d: "Heat Wave",
      0x1e: "Soul Eater",
      0x1f: "Dazzle Edge",
      0x20: "Triangle",
      0x21: "Pentagram",
      0x22: "Centurion",
      0x23: "Mist Feint",
      0x24: "Rune Magic",
      0x25: "Alchemy",
      0x26: "Demon Call",
      0x27: "After Burner",
      0x28: "Ice Breaker",
      0x29: "Dimension",
      0x2a: "Melt Armor",
      0x2b: "Light Cross",
      0x2c: "Light Fire",
      0x2d: "Poison Blade",
      0x2e: "Force Edge",
      0x2f: "Lance Charge",
      0x30: "Super Charge",
      0x31: "Mega Charge",
      0x32: "Dragon Brt",
      0x33: "Death Charge",
      0x34: "Side Winder",
      0x35: "Energy Fall",
      0x36: "Thunder Fall",
      0x37: "Flash Gazer",
      0x38: "Meteor",
      0x39: "Tornado",
      0x3a: "Cross Break",
      0x3b: "Air Dance",
      0x3c: "Road Rash",
      0x3d: "Lightning",
      0x3e: "Death Gate",
      0x3f: "Full Swing",
      0x40: "Power Wheel",
      0x41: "Mega Wheel",
      0x42: "Laguna Lock",
      0x43: "Giga Wheel",
      0x44: "Death Wheel",
      0x45: "Power Throw",
      0x46: "Boomer Throw",
      0x47: "Vortex",
      0x48: "Deadly Strike",
      0x49: "Mist Storm",
      0x4a: "Power Crash",
      0x4b: "Stun Bomb",
      0x4c: "Earthquake",
      0x4d: "ThunderStorm",
      0x4e: "Press Bomb",
      0x4f: "Dragon Claw",
      0x50: "Sky Claw",
      0x51: "Heaven Claw",
      0x52: "Storm Fang",
      0x53: "Venom Fang",
      0x54: "Brutal Shock",
      0x55: "Bullet Heel",
      0x56: "Vortex Kick",
      0x57: "Sky Dance",
      0x58: "HeavenlyFire",
      0x59: "Bruce Fist",
      0x5a: "First O' Fury",
      0x5b: "Thunder Drop",
      0x5c: "Conquer King",
      0x5d: "Buddha Fist",
      0x5e: "BackStepFist",
      0x5f: "Double Palm",
      0x60: "Stun Palm",
      0x61: "Panic Palm",
      0x62: "Nine Gate",
      0x63: "Meta Dream",
      0x64: "Change Gold",
      0x65: "Demon Breath",
      0x66: "Soul Shot",
      0x67: "Fairy Soul",
      0x68: "Soul Blast",
      0x69: "Fetamorgana",
      0x6a: "Shannon Sea",
      0x6b: "Stone Circle",
      0x6c: "Seal of Sin",
      0x6d: "Judgement",
      0x6e: "Apocalypse",
      0x6f: "Fool Prayer",
      0x70: "Holy Silence",
      0x71: "Apostle Fire",
      0x72: "Ice Arrow",
      0x73: "Mesmer Arrow",
      0x74: "Drain Arrow",
      0x75: "Lunatic",
      0x76: "Dragon Snipe",
      0x77: "Spell Virus",
      0x78: "Poison Arrow",
      0x79: "Charm Arrow",
      0x7a: "Double Bolt",
      0x7b: "Sniper Bolt",
      0x7c: "Vulcan Bolt",
      0x7d: "Saint Flame",
      0x7e: "Demon Wind",
      0x7f: "Stun Needle",
      0x80: "Dazzle Shot",
      0x81: "Armor Shot",
      0x82: "Explode",
      0x83: "Desert Storm",
      0x84: "Planet Dance",
      0x85: "Schwarchshilt",
      0x86: "Cocoon Dance",
      0x87: "Izuna Drop",
      0x88: "Fine Mist",
      0x89: "Kamaitachi",
      0x8a: "OniHyakusoku",
      0x8b: "Umi Zato",
      0x8c: "Death Club",
      0x8d: "Yellow Road",
      0x8e: "Shadow Loom",
      0x8f: "Dark Raven",
      0x90: "Demon Circle",
      0x91: "Battle Array",
      0x92: "Chaos Call",
      0x93: "Evil Wind",
      0x94: "Twister",
      0x95: "Cross Slash",
      0x96: "Bloody Spin",
      0x97: "Hyper Boom",
      0x98: "Hell Dive",
      0x99: "Zero Count",
      0x9a: "Rocket Punch",
      0x9b: "Boost Punch",
      0x9c: "Nova Shot",
      0x9d: "Drill Smash",
      0x9e: "Hammer Throw",
      0x9f: "Gestalt",
      0xa0: "Penn Kick",
      0xa1: "Penn Spit",
      0xa2: "Penn Dynamo",
      0xa3: "Power Slash",
      0xa4: "Sky High",
      0xa5: "Eagle Dive",
      0xa6: "Power Feint",
      0xa7: "Double Feint",
      0xa8: "DanseMacabre",
      0xa9: "Wolf Fang",
      0xaa: "Wolf Slash",
      0xab: "Cork Screw",
      0xac: "Wild Blow",
      0xad: "Soul Spark",
      0xae: "Death Drive",
      0xaf: "Light Sphere",
      0xb0: "Star Bomb",
      0xb1: "Road Rush",
      0xb2: "Flame Tail",
      0xb3: "Melt Armor",
      0xb4: "Dominion Ray",
      0xb5: "Thunder Blow",
      0xb6: "Photon Rage",
      0xb7: "Dragon Brt",
      0xb8: "Air Fang",
      0xb9: "Wild Rush",
      0xba: "Soul Smash",
      0xbb: "Soul Gun",
    },
  },
  resourcesGroups: {
    items: [
      {
        name: "Items",
        options: [
          0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e,
          0x5f, 0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0xde, 0xdf,
          0xe1, 0xe2, 0xe3, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee,
        ],
      },
      {
        name: "Daggers",
        options: [0x1, 0x2, 0x3, 0x6f, 0x70, 0x71, 0x72, 0x73],
      },
      {
        name: "Swords",
        options: [
          0x4, 0x5, 0x6, 0x7, 0x42, 0x43, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79,
          0xe8,
        ],
      },
      {
        name: "Rapiers",
        options: [0x8, 0x9, 0xa, 0x7a, 0x7b, 0x7c, 0x7d],
      },
      {
        name: "Blades",
        options: [0xb, 0xc, 0xd, 0x7e, 0x7f, 0x80, 0x81, 0x82],
      },
      {
        name: "Katanas",
        options: [0xe, 0xf, 0x10, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9],
      },
      {
        name: "Wings",
        options: [0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7],
      },
      {
        name: "Lances",
        options: [0x11, 0x12, 0x13, 0x14, 0x83, 0x84, 0x85, 0x86],
      },
      {
        name: "Spears",
        options: [0x15, 0x16, 0x17, 0x87, 0x88, 0x89, 0x8a, 0x8b],
      },
      {
        name: "Halberds",
        options: [0x18, 0x19, 0x1a, 0x8c, 0x8d, 0x8e, 0x8f],
      },
      {
        name: "Axes",
        options: [0x1b, 0x1c, 0x1d, 0x1e, 0x90, 0x91, 0x92, 0x93, 0x94],
      },
      {
        name: "Tomahawks",
        options: [0x1f, 0x20, 0x21, 0x95, 0x96, 0x97, 0x98],
      },
      {
        name: "Maces",
        options: [0x22, 0x23, 0x24, 0x99, 0x9a, 0x9b, 0x9c],
      },
      {
        name: "Anchors",
        options: [0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd],
      },
      {
        name: "Claws",
        options: [0x25, 0x26, 0x27, 0x28, 0x9d, 0x9e, 0x9f, 0xa0],
      },
      {
        name: "Gloves",
        options: [0x29, 0x2a, 0x2b, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5],
      },
      {
        name: "Knuckles",
        options: [0x2c, 0x2d, 0x2e, 0xa6, 0xa7, 0xa8, 0xa9],
      },
      {
        name: "Rods",
        options: [0x2f, 0x30, 0x31, 0xaa, 0xab, 0xac, 0xad, 0xae],
      },
      {
        name: "Wands",
        options: [
          0x32, 0x33, 0x34, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3, 0xe0, 0xe6, 0xe7,
        ],
      },
      {
        name: "Ankhs",
        options: [0x35, 0x36, 0x37, 0xb4, 0xb5, 0xb6, 0xb7, 0xe4],
      },
      {
        name: "Arrows",
        options: [0x38, 0x39, 0x3a, 0x3b, 0xb8, 0xb9, 0xba, 0xbb, 0xbc],
      },
      {
        name: "Quarrels",
        options: [0x3c, 0x3d, 0x3e, 0xbd, 0xbe, 0xbf, 0xc0],
      },
      {
        name: "Shells",
        options: [0x3f, 0x40, 0x41, 0xc1, 0xc2, 0xc3, 0xc4],
      },
      {
        name: "Shurikens",
        options: [0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf],
      },
      {
        name: "Beaks",
        options: [0xfe],
      },
      {
        name: "Bracers",
        options: [0x52, 0x53],
      },
      {
        name: "Tiaras",
        options: [0x68, 0x69],
      },
      {
        name: "Helmets",
        options: [0x6b, 0x6c],
      },
      {
        name: "Accessories",
        options: [
          0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e,
          0x4f, 0x50, 0x51, 0x6a, 0x6d, 0x6e, 0xe5, 0xef,
        ],
      },
      {
        name: "Unused",
        options: [
          0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa,
          0xfb, 0xfc, 0xfd,
        ],
      },
    ],
  },
};

export default template;
