import type { GameJson } from "$lib/types";

import { familiarFragment, itemFragment } from "./utils/fragment";
import { items, itemsGroups, itemsOrder } from "./utils/resource";

const template: GameJson = {
  validator: {
    regions: {
      europe_usa: {
        0x1ff0: [
          0x41, 0x7a, 0x75, 0x72, 0x65, 0x44, 0x72, 0x65, 0x61, 0x6d, 0x73,
          0x47, 0x42, 0x20,
        ], // "AzureDreamsGB "
      },
      japan: {
        0x1ff0: [
          0x41, 0x7a, 0x75, 0x72, 0x65, 0x44, 0x72, 0x65, 0x61, 0x6d, 0x73,
          0x47, 0x42, 0x20,
        ], // "AzureDreamsGB "
      },
    },
    text: "Drag 'n' drop here or click to add a save file.",
    error: "Not a valid save file.",
  },
  items: [
    {
      name: "Checksum System",
      offset: 0x1ffe,
      type: "checksum",
      dataType: "uint16",
      control: {
        offsetStart: 0xffe,
        offsetEnd: 0xfff,
      },
    },
    {
      id: "slots",
      length: 0x1000,
      type: "container",
      instanceType: "tabs",
      instances: 2,
      enumeration: "Slot %d",
      onTabChange: "onSlotChange(%d)",
      items: [
        {
          name: "Checksum",
          offset: 0xf0e,
          type: "checksum",
          dataType: "uint16",
          control: {
            offsetStart: 0x10,
            offsetEnd: 0xf0e,
          },
        },
        {
          type: "tabs",
          items: [
            {
              name: "General",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "General",
                      items: [
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              name: "Save Count",
                              offset: 0x95,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "ID No.",
                              offset: 0xffe,
                              type: "variable",
                              dataType: "uint8",
                              overrideShift: {
                                parent: 1,
                                shift: 0x0,
                              },
                              test: true,
                            },
                            {
                              name: "Playtime",
                              type: "group",
                              mode: "time",
                              items: [
                                {
                                  id: "savePreview-115",
                                  offset: 0x93,
                                  type: "variable",
                                  dataType: "uint16",
                                  max: 999,
                                },
                                {
                                  id: "savePreview-115",
                                  offset: 0x92,
                                  type: "variable",
                                  dataType: "uint8",
                                  leadingZeros: 1,
                                  max: 59,
                                },
                                {
                                  id: "savePreview-115",
                                  offset: 0x91,
                                  type: "variable",
                                  dataType: "uint8",
                                  leadingZeros: 1,
                                  max: 59,
                                },
                              ],
                            },
                            {
                              name: "Playtime (Milliseconds)",
                              offset: 0x90,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              id: "savePreview-131",
                              name: "Adventures",
                              offset: 0x9c,
                              type: "variable",
                              dataType: "uint8",
                            },
                            {
                              name: "Monsters",
                              offset: 0xa1,
                              type: "variable",
                              dataType: "uint8",
                              disabled: true,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          items: [
                            {
                              id: "savePreview-119",
                              name: "Floor",
                              offset: 0x99,
                              type: "variable",
                              dataType: "uint8",
                              resource: "floors",
                              autocomplete: true,
                            },
                            {
                              id: "savePreview-141",
                              name: "Funds",
                              offset: 0xa8,
                              type: "variable",
                              dataType: "uint24",
                              max: 9999999,
                            },
                          ],
                        },
                        {
                          type: "section",
                          flex: true,
                          hidden: true,
                          items: [
                            {
                              name: "Letters (Save Preview)",
                              offset: 0x10,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              id: "name",
                              name: "Name (Save Preview)",
                              offset: 0x11,
                              length: 0x8,
                              type: "variable",
                              dataType: "string",
                              letterDataType: "uint8",
                              endCode: 0x0,
                              hidden: true,
                            },
                            {
                              name: "Playtime (Save Preview)",
                              type: "group",
                              mode: "time",
                              hidden: true,
                              items: [
                                {
                                  offset: 0x20,
                                  type: "variable",
                                  dataType: "uint16",
                                  hidden: true,
                                },
                                {
                                  offset: 0x1f,
                                  type: "variable",
                                  dataType: "uint8",
                                  leadingZeros: 1,
                                  hidden: true,
                                },
                                {
                                  offset: 0x1e,
                                  type: "variable",
                                  dataType: "uint8",
                                  leadingZeros: 1,
                                  hidden: true,
                                },
                              ],
                            },
                            {
                              name: "Adventures (Save Preview)",
                              offset: 0x19,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Monsters (Save Preview)",
                              offset: 0x1a,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Floor (Save Preview)",
                              offset: 0x22,
                              type: "variable",
                              dataType: "uint8",
                              hidden: true,
                            },
                            {
                              name: "Funds (Save Preview)",
                              offset: 0x1b,
                              type: "variable",
                              dataType: "uint24",
                              hidden: true,
                            },
                          ],
                        },
                      ],
                    },
                    {
                      name: "Monster Book",
                      flex: true,
                      items: [
                        {
                          name: "Seen",
                          type: "bitflags",
                          flags: [
                            { offset: 0x66e, bit: 4, label: "000.Kewne" },
                            { offset: 0x651, bit: 0, label: "???", hidden: true },
                            { offset: 0x651, bit: 2, label: "001.Wump" },
                            { offset: 0x651, bit: 4, label: "???", hidden: true },
                            { offset: 0x651, bit: 6, label: "???", hidden: true },
                            { offset: 0x652, bit: 0, label: "002.Catawump" },
                            { offset: 0x652, bit: 2, label: "???", hidden: true },
                            { offset: 0x652, bit: 4, label: "003.Fireball" },
                            { offset: 0x652, bit: 6, label: "004.Genny" },
                            { offset: 0x653, bit: 0, label: "005.Mushrom" },
                            { offset: 0x653, bit: 2, label: "006.Troll" },
                            { offset: 0x653, bit: 4, label: "007.HamTroll" },
                            { offset: 0x653, bit: 6, label: "008.Frost" },
                            { offset: 0x654, bit: 0, label: "009.Noise" },
                            { offset: 0x654, bit: 2, label: "010.Balloon" },
                            { offset: 0x654, bit: 4, label: "011.Cyclone" },
                            { offset: 0x654, bit: 6, label: "012.Flame" },
                            { offset: 0x655, bit: 0, label: "013.Ifrit" },
                            { offset: 0x655, bit: 2, label: "014.Volcano" },
                            { offset: 0x655, bit: 4, label: "015.Blume" },
                            { offset: 0x655, bit: 6, label: "016.Analoeba" },
                            { offset: 0x656, bit: 0, label: "017.Submar" },
                            { offset: 0x656, bit: 2, label: "018.Daymare" },
                            { offset: 0x656, bit: 4, label: "019.Galelop" },
                            { offset: 0x656, bit: 6, label: "020.Cadavron" },
                            { offset: 0x657, bit: 0, label: "021.TomTroll" },
                            { offset: 0x657, bit: 2, label: "022.Griffin" },
                            { offset: 0x657, bit: 4, label: "023.Grineut" },
                            { offset: 0x657, bit: 6, label: "024.Kraken" },
                            { offset: 0x658, bit: 0, label: "025.Tundra" },
                            { offset: 0x658, bit: 2, label: "026.Nyuel" },
                            { offset: 0x658, bit: 4, label: "027.Batnyuel" },
                            { offset: 0x658, bit: 6, label: "028.Soilclaw" },
                            { offset: 0x659, bit: 0, label: "029.ShoTroll" },
                            { offset: 0x659, bit: 2, label: "030.Guardian" },
                            { offset: 0x659, bit: 4, label: "031.Barong" },
                            { offset: 0x659, bit: 6, label: "032.Arachne" },
                            { offset: 0x65a, bit: 0, label: "033.Ashra" },
                            { offset: 0x65a, bit: 2, label: "034.Garuda" },
                            { offset: 0x65a, bit: 4, label: "035.Souvenir" },
                            { offset: 0x65a, bit: 6, label: "???" },
                            { offset: 0x65b, bit: 0, label: "036.Viper" },
                            { offset: 0x65b, bit: 2, label: "037.Alloyer" },
                            { offset: 0x65b, bit: 4, label: "038.Metar" },
                            { offset: 0x65b, bit: 6, label: "039.Unicap" },
                            { offset: 0x65c, bit: 0, label: "040.Univern" },
                            { offset: 0x65c, bit: 2, label: "041.Zu" },
                            { offset: 0x65c, bit: 4, label: "042.Sizar" },
                            { offset: 0x65c, bit: 6, label: "043.Naprus" },
                            { offset: 0x65d, bit: 0, label: "044.Killer" },
                            { offset: 0x65d, bit: 2, label: "045.Saskatch" },
                            { offset: 0x65d, bit: 4, label: "046.Saber" },
                            { offset: 0x65d, bit: 6, label: "047.Mandara" },
                            { offset: 0x65e, bit: 0, label: "048.Octos" },
                            { offset: 0x65e, bit: 2, label: "049.Behemoth" },
                            { offset: 0x65e, bit: 4, label: "050.Gronmon" },
                            { offset: 0x65e, bit: 6, label: "051.Kid" },
                            { offset: 0x65f, bit: 0, label: "052.Dragon" },
                            { offset: 0x65f, bit: 2, label: "053.Glacier" },
                            { offset: 0x65f, bit: 4, label: "054.Golem" },
                            { offset: 0x65f, bit: 6, label: "055.Gance" },
                            { offset: 0x660, bit: 0, label: "056.S-Gance" },
                            { offset: 0x660, bit: 2, label: "057.Cyclops" },
                            { offset: 0x660, bit: 4, label: "058.Centaur" },
                            { offset: 0x660, bit: 6, label: "059.Lycanth" },
                            { offset: 0x661, bit: 0, label: "060.Hanuman" },
                            { offset: 0x661, bit: 2, label: "061.Naga" },
                            { offset: 0x661, bit: 4, label: "062.Cognita" },
                            { offset: 0x661, bit: 6, label: "063.Ogre" },
                            { offset: 0x662, bit: 0, label: "064.Spriggan" },
                            { offset: 0x662, bit: 2, label: "065.Ranklin" },
                            { offset: 0x662, bit: 4, label: "066.Cali" },
                            { offset: 0x662, bit: 6, label: "067.Moai" },
                            { offset: 0x663, bit: 0, label: "068.Daedalus" },
                            { offset: 0x663, bit: 2, label: "069.Dydra" },
                            { offset: 0x663, bit: 4, label: "070.Fencer" },
                            { offset: 0x663, bit: 6, label: "071.Mummy" },
                            { offset: 0x664, bit: 0, label: "072.Berserk" },
                            { offset: 0x664, bit: 2, label: "073.Baal" },
                            { offset: 0x664, bit: 4, label: "074.Amon" },
                            { offset: 0x664, bit: 6, label: "075.Belzeb" },
                            { offset: 0x665, bit: 0, label: "076.Succubus" },
                            { offset: 0x665, bit: 2, label: "077.Undine" },
                            { offset: 0x665, bit: 4, label: "078.Siren" },
                            { offset: 0x665, bit: 6, label: "079.Baram" },
                            { offset: 0x666, bit: 0, label: "080.Strass" },
                            { offset: 0x666, bit: 2, label: "081.Godhand" },
                            { offset: 0x666, bit: 4, label: "082.Chimera" },
                            { offset: 0x666, bit: 6, label: "083.Bomber" },
                            { offset: 0x667, bit: 0, label: "084.Paperis" },
                            { offset: 0x667, bit: 2, label: "085.Mad Crab" },
                            { offset: 0x667, bit: 4, label: "086.Sisa" },
                            { offset: 0x667, bit: 6, label: "087.Wraith" },
                            { offset: 0x668, bit: 0, label: "088.Phoenix" },
                            { offset: 0x668, bit: 2, label: "089.Cockatri" },
                            { offset: 0x668, bit: 4, label: "090.Sphinx" },
                            { offset: 0x668, bit: 6, label: "091.Nanoo" },
                            { offset: 0x669, bit: 0, label: "092.Pumpkinn" },
                            { offset: 0x669, bit: 2, label: "093.Matango" },
                            { offset: 0x669, bit: 4, label: "094.Mandrake" },
                            { offset: 0x669, bit: 6, label: "095.Medusa" },
                            { offset: 0x66a, bit: 0, label: "096.Eater" },
                            { offset: 0x66a, bit: 2, label: "097.Jabwock" },
                            { offset: 0x66a, bit: 4, label: "098.Salaman" },
                            { offset: 0x66a, bit: 6, label: "099.Serpent" },
                            { offset: 0x66b, bit: 0, label: "100.Basilisk" },
                            { offset: 0x66b, bit: 2, label: "101.Hydra" },
                            { offset: 0x66b, bit: 4, label: "102.Vevil" },
                            { offset: 0x66b, bit: 6, label: "103.Bahamut" },
                            { offset: 0x66c, bit: 0, label: "104.Leviath" },
                            { offset: 0x66c, bit: 2, label: "105.Yankash" },
                            { offset: 0x66c, bit: 4, label: "106.Blith" },
                            { offset: 0x66c, bit: 6, label: "107.Thord" },
                            { offset: 0x66d, bit: 0, label: "108.Arkis" },
                            { offset: 0x66d, bit: 2, label: "109.Barol" },
                            { offset: 0x66d, bit: 4, label: "110.Odin" },
                            { offset: 0x66d, bit: 6, label: "111.Dok" },
                            { offset: 0x66e, bit: 0, label: "112.Mephisto" },
                            { offset: 0x66e, bit: 2, label: "113.Maisoul" },
                            { offset: 0x66e, bit: 6, label: "114.HyKewne" },
                            { offset: 0x66f, bit: 0, label: "115.DarKewne" },
                            { offset: 0x66f, bit: 2, label: "116.Quack" },
                            { offset: 0x66f, bit: 4, label: "???", hidden: true },
                            { offset: 0x66f, bit: 6, label: "???", hidden: true },
                          ],
                        },
                        {
                          name: "Owned",
                          type: "bitflags",
                          flags: [
                            { offset: 0x66e, bit: 5, label: "000.Kewne" },
                            { offset: 0x651, bit: 1, label: "???", hidden: true },
                            { offset: 0x651, bit: 3, label: "001.Wump" },
                            { offset: 0x651, bit: 5, label: "???", hidden: true },
                            { offset: 0x651, bit: 7, label: "???", hidden: true },
                            { offset: 0x652, bit: 1, label: "002.Catawump" },
                            { offset: 0x652, bit: 3, label: "???", hidden: true },
                            { offset: 0x652, bit: 5, label: "003.Fireball" },
                            { offset: 0x652, bit: 7, label: "004.Genny" },
                            { offset: 0x653, bit: 1, label: "005.Mushrom" },
                            { offset: 0x653, bit: 3, label: "006.Troll" },
                            { offset: 0x653, bit: 5, label: "007.HamTroll" },
                            { offset: 0x653, bit: 7, label: "008.Frost" },
                            { offset: 0x654, bit: 1, label: "009.Noise" },
                            { offset: 0x654, bit: 3, label: "010.Balloon" },
                            { offset: 0x654, bit: 5, label: "011.Cyclone" },
                            { offset: 0x654, bit: 7, label: "012.Flame" },
                            { offset: 0x655, bit: 1, label: "013.Ifrit" },
                            { offset: 0x655, bit: 3, label: "014.Volcano" },
                            { offset: 0x655, bit: 5, label: "015.Blume" },
                            { offset: 0x655, bit: 7, label: "016.Analoeba" },
                            { offset: 0x656, bit: 1, label: "017.Submar" },
                            { offset: 0x656, bit: 3, label: "018.Daymare" },
                            { offset: 0x656, bit: 5, label: "019.Galelop" },
                            { offset: 0x656, bit: 7, label: "020.Cadavron" },
                            { offset: 0x657, bit: 1, label: "021.TomTroll" },
                            { offset: 0x657, bit: 3, label: "022.Griffin" },
                            { offset: 0x657, bit: 5, label: "023.Grineut" },
                            { offset: 0x657, bit: 7, label: "024.Kraken" },
                            { offset: 0x658, bit: 1, label: "025.Tundra" },
                            { offset: 0x658, bit: 3, label: "026.Nyuel" },
                            { offset: 0x658, bit: 5, label: "027.Batnyuel" },
                            { offset: 0x658, bit: 7, label: "028.Soilclaw" },
                            { offset: 0x659, bit: 1, label: "029.ShoTroll" },
                            { offset: 0x659, bit: 3, label: "030.Guardian" },
                            { offset: 0x659, bit: 5, label: "031.Barong" },
                            { offset: 0x659, bit: 7, label: "032.Arachne" },
                            { offset: 0x65a, bit: 1, label: "033.Ashra" },
                            { offset: 0x65a, bit: 3, label: "034.Garuda" },
                            { offset: 0x65a, bit: 5, label: "035.Souvenir" },
                            { offset: 0x65a, bit: 7, label: "???" },
                            { offset: 0x65b, bit: 1, label: "036.Viper" },
                            { offset: 0x65b, bit: 3, label: "037.Alloyer" },
                            { offset: 0x65b, bit: 5, label: "038.Metar" },
                            { offset: 0x65b, bit: 7, label: "039.Unicap" },
                            { offset: 0x65c, bit: 1, label: "040.Univern" },
                            { offset: 0x65c, bit: 3, label: "041.Zu" },
                            { offset: 0x65c, bit: 5, label: "042.Sizar" },
                            { offset: 0x65c, bit: 7, label: "043.Naprus" },
                            { offset: 0x65d, bit: 1, label: "044.Killer" },
                            { offset: 0x65d, bit: 3, label: "045.Saskatch" },
                            { offset: 0x65d, bit: 5, label: "046.Saber" },
                            { offset: 0x65d, bit: 7, label: "047.Mandara" },
                            { offset: 0x65e, bit: 1, label: "048.Octos" },
                            { offset: 0x65e, bit: 3, label: "049.Behemoth" },
                            { offset: 0x65e, bit: 5, label: "050.Gronmon" },
                            { offset: 0x65e, bit: 7, label: "051.Kid" },
                            { offset: 0x65f, bit: 1, label: "052.Dragon" },
                            { offset: 0x65f, bit: 3, label: "053.Glacier" },
                            { offset: 0x65f, bit: 5, label: "054.Golem" },
                            { offset: 0x65f, bit: 7, label: "055.Gance" },
                            { offset: 0x660, bit: 1, label: "056.S-Gance" },
                            { offset: 0x660, bit: 3, label: "057.Cyclops" },
                            { offset: 0x660, bit: 5, label: "058.Centaur" },
                            { offset: 0x660, bit: 7, label: "059.Lycanth" },
                            { offset: 0x661, bit: 1, label: "060.Hanuman" },
                            { offset: 0x661, bit: 3, label: "061.Naga" },
                            { offset: 0x661, bit: 5, label: "062.Cognita" },
                            { offset: 0x661, bit: 7, label: "063.Ogre" },
                            { offset: 0x662, bit: 1, label: "064.Spriggan" },
                            { offset: 0x662, bit: 3, label: "065.Ranklin" },
                            { offset: 0x662, bit: 5, label: "066.Cali" },
                            { offset: 0x662, bit: 7, label: "067.Moai" },
                            { offset: 0x663, bit: 1, label: "068.Daedalus" },
                            { offset: 0x663, bit: 3, label: "069.Dydra" },
                            { offset: 0x663, bit: 5, label: "070.Fencer" },
                            { offset: 0x663, bit: 7, label: "071.Mummy" },
                            { offset: 0x664, bit: 1, label: "072.Berserk" },
                            { offset: 0x664, bit: 3, label: "073.Baal" },
                            { offset: 0x664, bit: 5, label: "074.Amon" },
                            { offset: 0x664, bit: 7, label: "075.Belzeb" },
                            { offset: 0x665, bit: 1, label: "076.Succubus" },
                            { offset: 0x665, bit: 3, label: "077.Undine" },
                            { offset: 0x665, bit: 5, label: "078.Siren" },
                            { offset: 0x665, bit: 7, label: "079.Baram" },
                            { offset: 0x666, bit: 1, label: "080.Strass" },
                            { offset: 0x666, bit: 3, label: "081.Godhand" },
                            { offset: 0x666, bit: 5, label: "082.Chimera" },
                            { offset: 0x666, bit: 7, label: "083.Bomber" },
                            { offset: 0x667, bit: 1, label: "084.Paperis" },
                            { offset: 0x667, bit: 3, label: "085.Mad Crab" },
                            { offset: 0x667, bit: 5, label: "086.Sisa" },
                            { offset: 0x667, bit: 7, label: "087.Wraith" },
                            { offset: 0x668, bit: 1, label: "088.Phoenix" },
                            { offset: 0x668, bit: 3, label: "089.Cockatri" },
                            { offset: 0x668, bit: 5, label: "090.Sphinx" },
                            { offset: 0x668, bit: 7, label: "091.Nanoo" },
                            { offset: 0x669, bit: 1, label: "092.Pumpkinn" },
                            { offset: 0x669, bit: 3, label: "093.Matango" },
                            { offset: 0x669, bit: 5, label: "094.Mandrake" },
                            { offset: 0x669, bit: 7, label: "095.Medusa" },
                            { offset: 0x66a, bit: 1, label: "096.Eater" },
                            { offset: 0x66a, bit: 3, label: "097.Jabwock" },
                            { offset: 0x66a, bit: 5, label: "098.Salaman" },
                            { offset: 0x66a, bit: 7, label: "099.Serpent" },
                            { offset: 0x66b, bit: 1, label: "100.Basilisk" },
                            { offset: 0x66b, bit: 3, label: "101.Hydra" },
                            { offset: 0x66b, bit: 5, label: "102.Vevil" },
                            { offset: 0x66b, bit: 7, label: "103.Bahamut" },
                            { offset: 0x66c, bit: 1, label: "104.Leviath" },
                            { offset: 0x66c, bit: 3, label: "105.Yankash" },
                            { offset: 0x66c, bit: 5, label: "106.Blith" },
                            { offset: 0x66c, bit: 7, label: "107.Thord" },
                            { offset: 0x66d, bit: 1, label: "108.Arkis" },
                            { offset: 0x66d, bit: 3, label: "109.Barol" },
                            { offset: 0x66d, bit: 5, label: "110.Odin" },
                            { offset: 0x66d, bit: 7, label: "111.Dok" },
                            { offset: 0x66e, bit: 1, label: "112.Mephisto" },
                            { offset: 0x66e, bit: 3, label: "113.Maisoul" },
                            { offset: 0x66e, bit: 7, label: "114.HyKewne" },
                            { offset: 0x66f, bit: 1, label: "115.DarKewne" },
                            { offset: 0x66f, bit: 3, label: "116.Quack" },
                            { offset: 0x66f, bit: 5, label: "???", hidden: true },
                            { offset: 0x66f, bit: 7, label: "???", hidden: true },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Status",
              items: [familiarFragment("kou", 0x2f)],
            },
            {
              name: "Party",
              hidden: true,
              items: [
                {
                  name: "Slots",
                  offset: 0xa0,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  id: "party",
                  length: 0x60,
                  type: "container",
                  instanceType: "tabs",
                  instances: 5,
                  resource: "partyFamiliars",
                  vertical: true,
                  items: [familiarFragment("party", 0x6c2)],
                },
              ],
            },
            {
              name: "Monsters",
              items: [
                {
                  id: "monstersSlots-%index%",
                  name: "Slots",
                  offset: 0xa1,
                  type: "variable",
                  dataType: "uint8",
                  hidden: true,
                },
                {
                  id: "monstersTabs-%index%",
                  length: 0x40,
                  type: "container",
                  instanceType: "tabs",
                  instances: 20,
                  resource: "stableFamiliars",
                  vertical: true,
                  items: [familiarFragment("stable", 0xb1)],
                },
              ],
            },
            {
              name: "Inventory",
              items: [
                {
                  type: "tabs",
                  vertical: true,
                  items: [
                    {
                      name: "Items",
                      items: [
                        {
                          id: "itemSlots-items",
                          name: "Slots",
                          offset: 0xa2,
                          type: "variable",
                          dataType: "uint8",
                          max: 20,
                        },
                        {
                          length: 0x4,
                          type: "container",
                          instanceType: "section",
                          instances: 20,
                          noMargin: true,
                          items: [itemFragment("items", 0x5b1)],
                        },
                      ],
                    },
                    {
                      name: "Safe",
                      items: [
                        {
                          id: "itemSlots-safe",
                          name: "Slots",
                          offset: 0xa3,
                          type: "variable",
                          dataType: "uint8",
                          max: 20,
                        },
                        {
                          length: 0x4,
                          type: "container",
                          instanceType: "section",
                          instances: 20,
                          noMargin: true,
                          items: [itemFragment("safe", 0x601)],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "Events",
              items: [
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Blue Collar",
                      offset: 0x9e,
                      type: "variable",
                      dataType: "bit",
                      bit: 7,
                      resource: "booleanObtained",
                    },
                    {
                      id: "highestFloor",
                      name: "Highest Floor Reached",
                      offset: 0x9d,
                      type: "variable",
                      dataType: "uint8",
                      resource: "floors",
                      autocomplete: true,
                    },
                    {
                      name: "Last Floor Reached",
                      offset: 0x69a,
                      type: "variable",
                      dataType: "uint8",
                      resource: "floors",
                      hidden: true,
                    },
                    {
                      name: "Highest Floor Reached (Events)",
                      offset: 0x69b,
                      type: "variable",
                      dataType: "uint8",
                      resource: "floors",
                      hidden: true,
                    },
                    {
                      id: "houseSize",
                      name: "House Size",
                      offset: 0x694,
                      type: "variable",
                      dataType: "uint8",
                      binary: {
                        bitStart: 2,
                        bitLength: 2,
                      },
                      resource: "houseSizes",
                    },
                    {
                      name: "Beds",
                      offset: 0x9f,
                      type: "variable",
                      dataType: "uint8",
                      hidden: true,
                    },
                    {
                      name: "Money donated to Nico",
                      offset: 0x69e,
                      type: "variable",
                      dataType: "uint24",
                      max: 50000,
                    },
                    {
                      name: "Town",
                      offset: 0x694,
                      type: "variable",
                      dataType: "bit",
                      bit: 1,
                      resource: "booleanUpgraded",
                    },
                  ],
                },
                {
                  name: "Progressions",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Kou Relationships",
                      offset: 0x697,
                      type: "variable",
                      dataType: "uint8",
                      resource: "secondaryProgressions",
                      autocomplete: true,
                    },
                    {
                      name: "Selfi Relationship",
                      offset: 0x696,
                      type: "variable",
                      dataType: "uint8",
                      resource: "selfiProgressions",
                      autocomplete: true,
                    },
                    {
                      name: "The Three Bells",
                      offset: 0x695,
                      type: "variable",
                      dataType: "uint8",
                      resource: "bellsProgressions",
                      autocomplete: true,
                    },
                    {
                      name: "Ultimate Egg",
                      offset: 0x698,
                      type: "variable",
                      dataType: "uint8",
                      resource: "ultimateEggprogressions",
                      autocomplete: true,
                    },
                    {
                      name: "Monster of Legends",
                      offset: 0x699,
                      type: "variable",
                      dataType: "uint8",
                      resource: "monsterOfLegendsprogressions",
                      autocomplete: true,
                    },
                  ],
                },
                {
                  name: "Gosh Battles",
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Wins",
                      offset: 0xa6,
                      type: "variable",
                      dataType: "uint8",
                    },
                    {
                      name: "Losses",
                      offset: 0xa7,
                      type: "variable",
                      dataType: "uint8",
                    },
                  ],
                },
                {
                  type: "section",
                  flex: true,
                  items: [
                    {
                      name: "Monsbaiya",
                      type: "bitflags",
                      flags: [
                        { offset: 0x68b, bit: 7, label: "Vit Seed received from Wreath" },
                        { offset: 0x68b, bit: 6, label: "Barthe met", hidden: true },
                        { offset: 0x68b, bit: 0, label: "House extension in progress", separator: true },
                        { offset: 0x68c, bit: 3, label: "Talk with Nico after town upgrade", hidden: true },
                        { offset: 0x68c, bit: 4, label: "Talk with Nico before town upgrade", hidden: true },
                        { offset: 0x68c, bit: 2, label: "Town upgrade in progress", hidden: true },
                        { offset: 0x692, bit: 6, label: "Trigger B99 dream cutscene" },
                      ],
                    },
                    {
                      name: "Tower of Monstrosity",
                      type: "bitflags",
                      flags: [
                        { offset: 0x68f, bit: 7, label: "Gance met on 20F" },
                        { offset: 0x690, bit: 7, label: "Elevator to 21F unlocked" },
                        { offset: 0x68f, bit: 0, label: "Ghosh met on 24F" },
                        { offset: 0x68f, bit: 6, label: "Gance met on 29F" },
                        { offset: 0x690, bit: 6, label: "Elevator to 30F unlocked" },
                        { offset: 0x690, bit: 5, label: "Ultimate egg acquired" },
                        { offset: 0x68f, bit: 1, label: "The floor of the Sky reached", separator: true },
                        { offset: 0x690, bit: 4, label: "Elevator to B1 unlocked" },
                        { offset: 0x68f, bit: 5, label: "Dok met on B30" },
                        { offset: 0x690, bit: 3, label: "Elevator to B31 unlocked" },
                        { offset: 0x68f, bit: 4, label: "Mephisto met on B80" },
                        { offset: 0x690, bit: 2, label: "Elevator to B81 unlocked" },
                        { offset: 0x68f, bit: 3, label: "Monster of Legends met on B98" },
                        { offset: 0x690, bit: 1, label: "Elevator to B99 unlocked" },
                      ],
                    },
                    {
                      name: "Current Ascent",
                      type: "bitflags",
                      flags: [
                        { offset: 0x693, bit: 3, label: "Attley met" },
                        { offset: 0x693, bit: 4, label: "Marzin met" },
                        { offset: 0x693, bit: 5, label: "Skale met" },
                        { offset: 0x693, bit: 6, label: "Selfi met" },
                        { offset: 0x693, bit: 7, label: "Gosh met" },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  resources: {
    ais: {
      0x0: "Aggressive",
      0x1: "Attack Directly",
      0x2: "Provide Spell Backup",
      0x3: "Follow Silently",
      0x4: "Wait There",
    },
    bellsProgressions: {
      0x0: "-",
      0x1: "Talk with old man before 6F",
      0x2: "Talk with old man after 6F",
      0x3: "Sun Bell bring back to town",
      0x5: "Wind Bell bring back to town",
      0x7: "Lake Bell bring back to town",
      0x8: "All bells bring back to town",
      0x9: "Kid egg received from old man",
    },
    booleanObtained: {
      0x0: "-",
      0x1: "Obtained",
    },
    booleanUpgraded: {
      0x0: "-",
      0x1: "Upgraded",
    },
    classes: {
      0x0: "Fire",
      0x1: "Water",
      0x2: "Wind",
      0x3: "Neutral",
    },
    floors: "getFloorNames()",
    houseSizes: {
      0x0: "Small (4 beds)",
      0x1: "Medium (12 beds)",
      0x2: "Big (20 beds)",
    },
    itemFamiliar: {
      0x60: "Familiar",
    },
    items: {
      0x0: "-",
      ...items,
    },
    letters: {
      0x1: "0",
      0x2: "1",
      0x3: "2",
      0x4: "3",
      0x5: "4",
      0x6: "5",
      0x7: "6",
      0x8: "7",
      0x9: "8",
      0xa: "9",
      0xb: "A",
      0xc: "B",
      0xd: "C",
      0xe: "D",
      0xf: "E",
      0x10: "F",
      0x11: "G",
      0x12: "H",
      0x13: "I",
      0x14: "J",
      0x15: "K",
      0x16: "L",
      0x17: "M",
      0x18: "N",
      0x19: "O",
      0x1a: "P",
      0x1b: "Q",
      0x1c: "R",
      0x1d: "S",
      0x1e: "T",
      0x1f: "U",
      0x20: "V",
      0x21: "W",
      0x22: "X",
      0x23: "Y",
      0x24: "Z",
      0x3f: "あ",
      0x40: "い",
      0x41: "う",
      0x42: "え",
      0x43: "お",
      0x44: "か",
      0x45: "き",
      0x46: "く",
      0x47: "け",
      0x48: "こ",
      0x49: "さ",
      0x4a: "し",
      0x4b: "す",
      0x4c: "せ",
      0x4d: "そ",
      0x4e: "た",
      0x4f: "ち",
      0x50: "つ",
      0x51: "て",
      0x52: "と",
      0x53: "な",
      0x54: "に",
      0x55: "ぬ",
      0x56: "ね",
      0x57: "の",
      0x58: "は",
      0x59: "ひ",
      0x5a: "ふ",
      0x5b: "へ",
      0x5c: "ほ",
      0x5d: "ま",
      0x5e: "み",
      0x5f: "む",
      0x60: "め",
      0x61: "も",
      0x62: "や",
      0x63: "ゆ",
      0x64: "よ",
      0x65: "れ",
      0x66: "ん",
      0x67: "ら",
      0x68: "り",
      0x69: "る",
      0x6a: "わ",
      0x6b: "ろ",
      0x6c: "が",
      0x6d: "ぎ",
      0x6e: "ぐ",
      0x6f: "げ",
      0x70: "ご",
      0x71: "ざ",
      0x72: "じ",
      0x73: "ず",
      0x74: "ぜ",
      0x75: "ぞ",
      0x76: "だ",
      0x77: "ぢ",
      0x78: "づ",
      0x79: "で",
      0x7a: "ど",
      0x7b: "ば",
      0x7c: "び",
      0x7d: "ぶ",
      0x7e: "べ",
      0x7f: "ぼ",
      0x80: "ぱ",
      0x81: "ぴ",
      0x82: "ぷ",
      0x83: "ぺ",
      0x84: "ぽ",
      0x85: "ぁ",
      0x86: "ぃ",
      0x87: "ぅ",
      0x88: "ぇ",
      0x89: "ぉ",
      0x8a: "っ",
      0x8b: "ゃ",
      0x8c: "ゅ",
      0x8d: "ょ",
      0x8e: "を",
      0x8f: "ア",
      0x90: "イ",
      0x91: "ウ",
      0x92: "エ",
      0x93: "オ",
      0x94: "カ",
      0x95: "キ",
      0x96: "ク",
      0x97: "ケ",
      0x98: "コ",
      0x99: "サ",
      0x9a: "シ",
      0x9b: "ス",
      0x9c: "セ",
      0x9d: "ソ",
      0x9e: "タ",
      0x9f: "チ",
      0xa0: "ツ",
      0xa1: "テ",
      0xa2: "ト",
      0xa3: "ナ",
      0xa4: "ニ",
      0xa5: "ヌ",
      0xa6: "ネ",
      0xa7: "ノ",
      0xa8: "ハ",
      0xa9: "ヒ",
      0xaa: "フ",
      0xab: "ヘ",
      0xac: "ホ",
      0xad: "マ",
      0xae: "ミ",
      0xaf: "ム",
      0xb0: "メ",
      0xb1: "モ",
      0xb2: "ヤ",
      0xb3: "ユ",
      0xb4: "ヨ",
      0xb5: "ワ",
      0xb6: "ン",
      0xb7: "ラ",
      0xb8: "リ",
      0xb9: "ル",
      0xba: "レ",
      0xbb: "ロ",
      0xbc: "ガ",
      0xbd: "ギ",
      0xbe: "グ",
      0xbf: "ゲ",
      0xc0: "ゴ",
      0xc1: "ザ",
      0xc2: "ジ",
      0xc3: "ズ",
      0xc4: "ゼ",
      0xc5: "ゾ",
      0xc6: "ダ",
      0xc7: "ヂ",
      0xc8: "ヅ",
      0xc9: "デ",
      0xca: "ド",
      0xcb: "バ",
      0xcc: "ビ",
      0xcd: "ブ",
      0xce: "ベ",
      0xcf: "ボ",
      0xd0: "パ",
      0xd1: "ピ",
      0xd2: "プ",
      0xd3: "ペ",
      0xd4: "ポ",
      0xd5: "ァ",
      0xd6: "ィ",
      0xd7: "ゥ",
      0xd8: "ェ",
      0xd9: "ォ",
      0xda: "ッ",
      0xdb: "ャ",
      0xdc: "ュ",
      0xdd: "ョ",
      0xde: "ヲ",
      0xfb: "ー",
    },
    monsterOfLegendsprogressions: {
      0x0: "-",
      0x2: "Phoenix met on the floor of the Sky",
      0x3: "Basement tutorial seen",
      0x7: "Dok defeated on B30",
      0xb: "Mephisto defeated on B80",
      0xf: "Maisoul defeated on B98",
      0x10: "B99 reached",
    },
    optionBoolean: {
      0x0: "No",
      0x1: "Yes",
    },
    partyFamiliars: "getFamiliarNames('party')",
    secondaryProgressions: {
      0x0: "-",
      0x2: "Introduction seen",
      0x3: "Kewn met in Town",
      0x4: "Kewn tutorial seen",
      0x5: "Ghosh met on 2F",
      0x6: "Marzin met on 3F",
      0x7: "Skale met on 4F",
      0x8: "Attley met on 5F",
      0x9: "Selfi met on 1F",
      0xa: "Selfi met on 3F",
      0xb: "Skale met on 7F",
      0xc: "Marzin met on 6F",
      0xd: "Gosh met on 1F",
      0xe: "Selfi met on 5F",
      0xf: "Selfi met on 1F",
      0x10: "Selfi met on 5F",
      0x11: "Attley met on 11F",
      0x12: "Gosh met on 8F",
      0x13: "Marzin met on 7F",
      0x14: "Selfi met on 9F",
      0x15: "Marzin met on 15F",
      0x16: "Gosh met on 13F",
      0x17: "Attley met on 15F",
      0x18: "Selfi met on 10F",
      0x19: "Gosh met on 13F",
      0x1a: "Selfi met on 15F",
      0x1b: "Selfi met on 15F",
      0x1c: "Attley met on 7F",
    },
    selfiProgressions: {
      0x0: "-",
      0x2: "Attley met on F7",
      0x3: "Selfi met on F1",
      0x4: "Selfi met on F3",
      0x5: "Selfi met on F2",
      0x6: "Selfi met on F5",
      0x7: "Selfi met on F2",
    },
    specialPowers: {
      0x0: "-",
      0x1: "Double Speed",
      0x2: "Max Punch",
      0x3: "Soul Strike",
      0x4: "Riot!",
      0x5: "Counter",
      0x6: "Ice Wall",
      0x7: "Prime Mover",
      0x8: "Death Cry",
      0x9: "S-Destruct",
      0xa: "Attack Down",
      0xb: "Spell Seal",
      0xc: "Paralyze",
      0xd: "Confuse",
      0xe: "Brainwash",
      0xf: "Sleep",
      0x10: "Blind",
      0x11: "Poison",
      0x12: "Holler",
      0x13: "Shock",
      0x14: "Evil Eye",
      0x15: "Stuffed!",
      0x16: "Anorexia",
      0x17: "Un-Anorexia",
      0x18: "Blizzard",
      0x19: "Moon Howl",
      0x1a: "Threats",
      0x1b: "Change Kind",
      0x1c: "Beauty Sleep",
      0x1d: "MP Drain",
      0x1e: "Next Floor",
      0x1f: "Vanish!",
      0x20: "Collar!",
      0x21: "Burrow",
      0x22: "Seize",
      0x23: "Steal Item",
      0x24: "Arm",
      0x25: "Transform",
      0x26: "Item Modify",
      0x27: "Appe Titan",
      0x28: "Find Trap",
      0x29: "Scout",
      0x2a: "Master Hunt",
      0x2b: "Split Up",
      0x2c: "Anti Paral",
      0x2d: "Anti-Weak",
      0x2e: "Seize Not",
      0x2f: "Antihypno",
      0x30: "Nessun Dorma",
      0x31: "Tox Screen",
      0x32: "Blind Not",
      0x33: "Null Seal",
      0x34: "Steal Not",
      0x35: "Seize Not",
      0x36: "Howl-Proof",
      0x37: "Rust Not",
      0x38: "Die Hard",
      0x39: "Double Exp",
      0x3a: "Recover X2",
      0x3b: "Attack Up",
      0x3c: "Defense Up",
      0x3d: "Magic Up",
      0x3e: "Magic Up",
      0x3f: "Double HP",
      0x40: "Attack X2",
      0x41: "Defense X2",
      0x42: "MP Halver",
      0x43: "Block X2",
    },
    species: {
      0x0: "Wump (Fire)",
      0x1: "Wump (Water)",
      0x2: "Wump (Wind)",
      0x3: "Catawump (Fire)",
      0x4: "Catawump (Water)",
      0x5: "Catawump (Wind)",
      0x6: "Fireball",
      0x7: "Genny",
      0x8: "Mushrom",
      0x9: "Troll",
      0xa: "HamTroll",
      0xb: "Frost",
      0xc: "Noise",
      0xd: "Balloon",
      0xe: "Cyclone",
      0xf: "Flame",
      0x10: "Ifrit",
      0x11: "Volcano",
      0x12: "Blume",
      0x13: "Analoeba",
      0x14: "Submar",
      0x15: "Daymare",
      0x16: "Galelop",
      0x17: "Cadavron",
      0x18: "TomTroll",
      0x19: "Griffin",
      0x1a: "Grineut",
      0x1b: "Kraken",
      0x1c: "Tundra",
      0x1d: "Nyuel",
      0x1e: "Batnyuel",
      0x1f: "Soilclaw",
      0x20: "ShoTroll",
      0x21: "Guardian",
      0x22: "Barong",
      0x23: "Arachne",
      0x24: "Ashra",
      0x25: "Garuda",
      0x26: "Souvenir",
      0x27: "Catawump (Water)",
      0x28: "Viper",
      0x29: "Alloyer",
      0x2a: "Metar",
      0x2b: "Unicap",
      0x2c: "Univern",
      0x2d: "Zu",
      0x2e: "Sizar",
      0x2f: "Naprus",
      0x30: "Killer",
      0x31: "Saskatch",
      0x32: "Saber",
      0x33: "Mandara",
      0x34: "Octos",
      0x35: "Behemoth",
      0x36: "Gronmon",
      0x37: "Kid",
      0x38: "Dragon",
      0x39: "Glacier",
      0x3a: "Golem",
      0x3b: "Gance",
      0x3c: "S-Gance",
      0x3d: "Cyclops",
      0x3e: "Centaur",
      0x3f: "Lycanth",
      0x40: "Hanuman",
      0x41: "Naga",
      0x42: "Cognita",
      0x43: "Ogre",
      0x44: "Spriggan",
      0x45: "Ranklin",
      0x46: "Cali",
      0x47: "Moai",
      0x48: "Daedalus",
      0x49: "Dydra",
      0x4a: "Fencer",
      0x4b: "Mummy",
      0x4c: "Berserk",
      0x4d: "Baal",
      0x4e: "Amon",
      0x4f: "Belzeb",
      0x50: "Succubus",
      0x51: "Undine",
      0x52: "Siren",
      0x53: "Baram",
      0x54: "Strass",
      0x55: "Godhand",
      0x56: "Chimera",
      0x57: "Bomber",
      0x58: "Paperis",
      0x59: "MadCrab",
      0x5a: "Sisa",
      0x5b: "Wraith",
      0x5c: "Phoenix",
      0x5d: "Cockatri",
      0x5e: "Sphinx",
      0x5f: "Nanoo",
      0x60: "Pumpkinn",
      0x61: "Matango",
      0x62: "Mandrake",
      0x63: "Medusa",
      0x64: "Eater",
      0x65: "Jabwock",
      0x66: "Salaman",
      0x67: "Serpent",
      0x68: "Basilisk",
      0x69: "Hydra",
      0x6a: "Vevil",
      0x6b: "Bahamut",
      0x6c: "Leviath",
      0x6d: "Yankash",
      0x6e: "Blith",
      0x6f: "Thord",
      0x70: "Arkis",
      0x71: "Barol",
      0x72: "Odin",
      0x73: "Dok",
      0x74: "Mephisto",
      0x75: "Maisoul",
      0x76: "Kewne",
      0x77: "HyKewne",
      0x78: "DarKewne",
      0x79: "Quack",
      0x7a: "Wumpi",
    },
    stableFamiliars: "getFamiliarNames('stable')",
    status: {
      0x0: "-",
      0x1: "Egg",
      0x2: "In Party",
      0x3: "In Stable",
    },
    ultimateEggprogressions: {
      0x0: "-",
      0x1: "Introduction seen",
      0x2: "Beldo give Blue Collar on 10F",
      0x3: "Marzin met on 16F",
      0x4: "Skale met on 17F",
      0x9: "Gance defeated on 20F",
      0xa: "Ghosh met on 24F",
      0xb: "Ghosh met on 27F",
      0xf: "Gance defeated on 29F",
      0x10: "Beldo met on 30F",
      0x11: "Talk with Baldo on 30F",
      0x12: "Beldo defeated on 30F",
      0x13: "Ultimate egg acquired",
      0x1a: "Ultimate egg hatched",
      0x1d: "Phoenix met on the floor of the Sky",
      0x1e: "Phoenix egg received from Phoenix",
      0x1f: "Yankash egg received from Phoenix",
      0x20: "Phoenix absent",
      0x21: "Quack egg received from Phoenix",
    },
  },
  resourcesGroups: {
    items: itemsGroups,
  },
  resourcesOrder: {
    items: itemsOrder,
  },
};

export default template;
