import type { Resource, ResourceGroups } from "$lib/types";

const itemTypes = [
  { index: 0x0, name: "Poké Balls" },
  { index: 0x1, name: "Medicine" },
  { index: 0x2, name: "Berries" },
  { index: 0x3, name: "Apricorns" },
  { index: 0x4, name: "Battle Items" },
  { index: 0x5, name: "Vitamins" },
  { index: 0x6, name: "Evolution Items" },
  { index: 0x7, name: "Held Items" },
  { index: 0x8, name: "Mails" },
  { index: 0x9, name: "Miscellaneous" },
  { index: 0xa, name: "Key Items" },
  { index: 0xb, name: "TMs" },
  { index: 0xc, name: "HMs" },
];

// prettier-ignore
export const itemList = [
  { index: 0x1, name: "Master Ball", location: 0x1, type: 0x0, order: 11 },
  { index: 0x2, name: "Ultra Ball", location: 0x1, type: 0x0, order: 2 },
  { index: 0x3, name: "Brightpowder", location: 0x0, type: 0x7, order: 85 },
  { index: 0x4, name: "Great Ball", location: 0x1, type: 0x0, order: 1 },
  { index: 0x5, name: "Poké Ball", location: 0x1, type: 0x0, order: 0 },
  // { index: 0x6, name: "Teru-Sama" },
  { index: 0x7, name: "Bicycle", location: 0x2, type: 0xa, order: 143 },
  { index: 0x8, name: "Moon Stone", location: 0x0, type: 0x6, order: 75 },
  { index: 0x9, name: "Antidote", location: 0x0, type: 0x1, order: 24 },
  { index: 0xa, name: "Burn Heal", location: 0x0, type: 0x1, order: 26 },
  { index: 0xb, name: "Ice Heal", location: 0x0, type: 0x1, order: 27 },
  { index: 0xc, name: "Awakening", location: 0x0, type: 0x1, order: 25 },
  { index: 0xd, name: "Parlyz Heal", location: 0x0, type: 0x1, order: 28 },
  { index: 0xe, name: "Full Restore", location: 0x0, type: 0x1, order: 16 },
  { index: 0xf, name: "Max Potion", location: 0x0, type: 0x1, order: 15 },
  { index: 0x10, name: "Hyper Potion", location: 0x0, type: 0x1, order: 14 },
  { index: 0x11, name: "Super Potion", location: 0x0, type: 0x1, order: 13 },
  { index: 0x12, name: "Potion", location: 0x0, type: 0x1, order: 12 },
  { index: 0x13, name: "Escape Rope", location: 0x0, type: 0x9, order: 125 },
  { index: 0x14, name: "Repel", location: 0x0, type: 0x9, order: 126 },
  { index: 0x15, name: "Max Elixer", location: 0x0, type: 0x1, order: 20 },
  { index: 0x16, name: "Fire Stone", location: 0x0, type: 0x6, order: 71 },
  { index: 0x17, name: "Thunder Stone", location: 0x0, type: 0x6, order: 74 },
  { index: 0x18, name: "Water Stone", location: 0x0, type: 0x6, order: 72 },
  // { index: 0x19, name: "Teru-Sama" },
  { index: 0x1a, name: "HP Up", location: 0x0, type: 0x5, order: 64 },
  { index: 0x1b, name: "Protein", location: 0x0, type: 0x5, order: 66 },
  { index: 0x1c, name: "Iron", location: 0x0, type: 0x5, order: 67 },
  { index: 0x1d, name: "Carbos", location: 0x0, type: 0x5, order: 68 },
  { index: 0x1e, name: "Lucky Punch", location: 0x0, type: 0x7, order: 96 },
  { index: 0x1f, name: "Calcium", location: 0x0, type: 0x5, order: 69 },
  { index: 0x20, name: "Rare Candy", location: 0x0, type: 0x5, order: 70 },
  { index: 0x21, name: "X Accuracy", location: 0x0, type: 0x4, order: 61 },
  { index: 0x22, name: "Leaf Stone", location: 0x0, type: 0x6, order: 73 },
  { index: 0x23, name: "Metal Powder", location: 0x0, type: 0x7, order: 98 },
  { index: 0x24, name: "Nugget", location: 0x0, type: 0x9, order: 136 },
  { index: 0x25, name: "Poké Doll", location: 0x0, type: 0x9, order: 129 },
  { index: 0x26, name: "Full Heal", location: 0x0, type: 0x1, order: 29 },
  { index: 0x27, name: "Revive", location: 0x0, type: 0x1, order: 21 },
  { index: 0x28, name: "Max Revive", location: 0x0, type: 0x1, order: 22 },
  { index: 0x29, name: "Guard Spec.", location: 0x0, type: 0x4, order: 63 },
  { index: 0x2a, name: "Super Repel", location: 0x0, type: 0x9, order: 127 },
  { index: 0x2b, name: "Max Repel", location: 0x0, type: 0x9, order: 128 },
  { index: 0x2c, name: "Dire Hit", location: 0x0, type: 0x4, order: 62 },
  // { index: 0x2d, name: "Teru-Sama" },
  { index: 0x2e, name: "Fresh Water", location: 0x0, type: 0x1, order: 31 },
  { index: 0x2f, name: "Soda Pop", location: 0x0, type: 0x1, order: 32 },
  { index: 0x30, name: "Lemonade", location: 0x0, type: 0x1, order: 33 },
  { index: 0x31, name: "X Attack", location: 0x0, type: 0x4, order: 57 },
  // { index: 0x32, name: "Teru-Sama" },
  { index: 0x33, name: "X Defend", location: 0x0, type: 0x4, order: 58 },
  { index: 0x34, name: "X Speed", location: 0x0, type: 0x4, order: 59 },
  { index: 0x35, name: "X Special", location: 0x0, type: 0x4, order: 60 },
  { index: 0x36, name: "Coin Case", location: 0x2, type: 0xa, order: 151 },
  { index: 0x37, name: "Item Finder", location: 0x2, type: 0xa, order: 154 },
  // { index: 0x38, name: "Teru-Sama" },
  { index: 0x39, name: "Exp. Share", location: 0x0, type: 0x7, order: 90 },
  { index: 0x3a, name: "Old Rod", location: 0x2, type: 0xa, order: 144 },
  { index: 0x3b, name: "Good Rod", location: 0x2, type: 0xa, order: 145 },
  { index: 0x3c, name: "Silver Leaf", location: 0x0, type: 0x9, order: 138 },
  { index: 0x3d, name: "Super Rod", location: 0x2, type: 0xa, order: 146 },
  { index: 0x3e, name: "PP Up", location: 0x0, type: 0x5, order: 65 },
  { index: 0x3f, name: "Ether", location: 0x0, type: 0x1, order: 17 },
  { index: 0x40, name: "Max Ether", location: 0x0, type: 0x1, order: 18 },
  { index: 0x41, name: "Elixer", location: 0x0, type: 0x1, order: 19 },
  { index: 0x42, name: "Red Scale", location: 0x2, type: 0xa, order: 160 },
  { index: 0x43, name: "Secret Potion", location: 0x2, type: 0xa, order: 162 },
  { index: 0x44, name: "S.S. Ticket", location: 0x2, type: 0xa, order: 161 },
  { index: 0x45, name: "Mystery Egg", location: 0x2, type: 0xa, order: 157 },
  { index: 0x46, name: "Clear Bell", location: 0x2, type: 0xa, order: 150, crystal: true },
  { index: 0x47, name: "Silver Wing", location: 0x2, type: 0xa, order: 163 },
  { index: 0x48, name: "Moomoo Milk", location: 0x0, type: 0x1, order: 34 },
  { index: 0x49, name: "Quick Claw", location: 0x0, type: 0x7, order: 105 },
  { index: 0x4a, name: "Poisoncure Berry", location: 0x0, type: 0x2, order: 49 },
  { index: 0x4b, name: "Gold Leaf", location: 0x0, type: 0x9, order: 135 },
  { index: 0x4c, name: "Soft Sand", location: 0x0, type: 0x7, order: 110 },
  { index: 0x4d, name: "Sharp Beak", location: 0x0, type: 0x7, order: 107 },
  { index: 0x4e, name: "Paralyzecure Berry", location: 0x0, type: 0x2, order: 48 },
  { index: 0x4f, name: "Burnt Berry", location: 0x0, type: 0x2, order: 42 },
  { index: 0x50, name: "Ice Berry", location: 0x0, type: 0x2, order: 44 },
  { index: 0x51, name: "Poison Barb", location: 0x0, type: 0x7, order: 103 },
  { index: 0x52, name: "King's Rock", location: 0x0, type: 0x6, order: 79 },
  { index: 0x53, name: "Bitter Berry", location: 0x0, type: 0x2, order: 41 },
  { index: 0x54, name: "Mint Berry", location: 0x0, type: 0x2, order: 45 },
  { index: 0x55, name: "Red Apricorn", location: 0x0, type: 0x3, order: 54 },
  { index: 0x56, name: "Tiny Mushroom", location: 0x0, type: 0x9, order: 142 },
  { index: 0x57, name: "Big Mushroom", location: 0x0, type: 0x9, order: 132 },
  { index: 0x58, name: "Silver Powder", location: 0x0, type: 0x7, order: 108 },
  { index: 0x59, name: "Blue Apricorn", location: 0x0, type: 0x3, order: 51 },
  // { index: 0x5a, name: "Teru-Sama" },
  { index: 0x5b, name: "Amulet Coin", location: 0x0, type: 0x7, order: 81 },
  { index: 0x5c, name: "Yellow Apricorn", location: 0x0, type: 0x3, order: 56 },
  { index: 0x5d, name: "Green Apricorn", location: 0x0, type: 0x3, order: 52 },
  { index: 0x5e, name: "Cleanse Tag", location: 0x0, type: 0x7, order: 87 },
  { index: 0x5f, name: "Mystic Water", location: 0x0, type: 0x7, order: 100 },
  { index: 0x60, name: "Twisted Spoon", location: 0x0, type: 0x7, order: 114 },
  { index: 0x61, name: "White Apricorn", location: 0x0, type: 0x3, order: 55 },
  { index: 0x62, name: "Blackbelt", location: 0x0, type: 0x7, order: 84 },
  { index: 0x63, name: "Black Apricorn", location: 0x0, type: 0x3, order: 50 },
  // { index: 0x64, name: "Teru-Sama" },
  { index: 0x65, name: "Pink Apricorn", location: 0x0, type: 0x3, order: 53 },
  { index: 0x66, name: "Black Glasses", location: 0x0, type: 0x7, order: 83 },
  { index: 0x67, name: "Slowpoke Tail", location: 0x0, type: 0x9, order: 139 },
  { index: 0x68, name: "Pink Bow", location: 0x0, type: 0x7, order: 102 },
  { index: 0x69, name: "Stick", location: 0x0, type: 0x7, order: 112 },
  { index: 0x6a, name: "Smoke Ball", location: 0x0, type: 0x7, order: 109 },
  { index: 0x6b, name: "Never-Melt Ice", location: 0x0, type: 0x7, order: 101 },
  { index: 0x6c, name: "Magnet", location: 0x0, type: 0x7, order: 97 },
  { index: 0x6d, name: "Miracle Berry", location: 0x0, type: 0x2, order: 46 },
  { index: 0x6e, name: "Pearl", location: 0x0, type: 0x9, order: 137 },
  { index: 0x6f, name: "Big Pearl", location: 0x0, type: 0x9, order: 133 },
  { index: 0x70, name: "Everstone", location: 0x0, type: 0x7, order: 89 },
  { index: 0x71, name: "Spell Tag", location: 0x0, type: 0x7, order: 111 },
  { index: 0x72, name: "Rage Candy Bar", location: 0x0, type: 0x1, order: 35 },
  { index: 0x73, name: "GS Ball", location: 0x2, type: 0xa, order: 153, crystal: true },
  { index: 0x74, name: "Blue Card", location: 0x2, type: 0xa, order: 148, crystal: true },
  { index: 0x75, name: "Miracle Seed", location: 0x0, type: 0x7, order: 99 },
  { index: 0x76, name: "Thick Club", location: 0x0, type: 0x7, order: 113 },
  { index: 0x77, name: "Focus Band", location: 0x0, type: 0x7, order: 91 },
  // { index: 0x78, name: "Teru-Sama" },
  { index: 0x79, name: "Energypowder", location: 0x0, type: 0x1, order: 36 },
  { index: 0x7a, name: "Energy Root", location: 0x0, type: 0x1, order: 37 },
  { index: 0x7b, name: "Heal Powder", location: 0x0, type: 0x1, order: 38 },
  { index: 0x7c, name: "Revival Herb", location: 0x0, type: 0x1, order: 39 },
  { index: 0x7d, name: "Hard Stone", location: 0x0, type: 0x7, order: 92 },
  { index: 0x7e, name: "Lucky Egg", location: 0x0, type: 0x7, order: 95 },
  { index: 0x7f, name: "Card Key", location: 0x2, type: 0xa, order: 149 },
  { index: 0x80, name: "Machine Part", location: 0x2, type: 0xa, order: 156 },
  { index: 0x81, name: "Egg Ticket", location: 0x2, type: 0xa, order: 152, crystal: true },
  { index: 0x82, name: "Lost Item", location: 0x2, type: 0xa, order: 155 },
  { index: 0x83, name: "Stardust", location: 0x0, type: 0x9, order: 141 },
  { index: 0x84, name: "Star Piece", location: 0x0, type: 0x9, order: 140 },
  { index: 0x85, name: "Basement Key", location: 0x2, type: 0xa, order: 147 },
  { index: 0x86, name: "Pass", location: 0x2, type: 0xa, order: 158 },
  // { index: 0x87, name: "Teru-Sama" },
  // { index: 0x88, name: "Teru-Sama" },
  // { index: 0x89, name: "Teru-Sama" },
  { index: 0x8a, name: "Charcoal", location: 0x0, type: 0x7, order: 86 },
  { index: 0x8b, name: "Berry Juice", location: 0x0, type: 0x1, order: 30 },
  { index: 0x8c, name: "Scope Lens", location: 0x0, type: 0x7, order: 106 },
  // { index: 0x8d, name: "Teru-Sama" },
  // { index: 0x8e, name: "Teru-Sama" },
  { index: 0x8f, name: "Metal Coat", location: 0x0, type: 0x6, order: 80 },
  { index: 0x90, name: "Dragon Fang", location: 0x0, type: 0x7, order: 88 },
  // { index: 0x91, name: "Teru-Sama" },
  { index: 0x92, name: "Leftovers", location: 0x0, type: 0x7, order: 93 },
  // { index: 0x93, name: "Teru-Sama" },
  // { index: 0x94, name: "Teru-Sama" },
  // { index: 0x95, name: "Teru-Sama" },
  { index: 0x96, name: "Mystery Berry", location: 0x0, type: 0x2, order: 47 },
  { index: 0x97, name: "Dragon Scale", location: 0x0, type: 0x6, order: 78 },
  { index: 0x98, name: "Berserk Gene", location: 0x0, type: 0x7, order: 82 },
  // { index: 0x99, name: "Teru-Sama" },
  // { index: 0x9a, name: "Teru-Sama" },
  // { index: 0x9b, name: "Teru-Sama" },
  { index: 0x9c, name: "Sacred Ash", location: 0x0, type: 0x1, order: 23 },
  { index: 0x9d, name: "Heavy Ball", location: 0x1, type: 0x0, order: 5 },
  { index: 0x9e, name: "Flower Mail", location: 0x0, type: 0x8, order: 117 },
  { index: 0x9f, name: "Level Ball", location: 0x1, type: 0x0, order: 6 },
  { index: 0xa0, name: "Lure Ball", location: 0x1, type: 0x0, order: 8 },
  { index: 0xa1, name: "Fast Ball", location: 0x1, type: 0x0, order: 3 },
  // { index: 0xa2, name: "Teru-Sama" },
  { index: 0xa3, name: "Light Ball", location: 0x0, type: 0x7, order: 94 },
  { index: 0xa4, name: "Friend Ball", location: 0x1, type: 0x0, order: 4 },
  { index: 0xa5, name: "Moon Ball", location: 0x1, type: 0x0, order: 9 },
  { index: 0xa6, name: "Love Ball", location: 0x1, type: 0x0, order: 7 },
  { index: 0xa7, name: "Normal Box", location: 0x0, type: 0x9, order: 130 },
  { index: 0xa8, name: "Gorgeous Box", location: 0x0, type: 0x9, order: 131 },
  { index: 0xa9, name: "Sun Stone", location: 0x0, type: 0x6, order: 76 },
  { index: 0xaa, name: "Polkadot Bow", location: 0x0, type: 0x7, order: 104 },
  // { index: 0xab, name: "Teru-Sama" },
  { index: 0xac, name: "Up-Grade", location: 0x0, type: 0x6, order: 77 },
  { index: 0xad, name: "Berry", location: 0x0, type: 0x2, order: 40 },
  { index: 0xae, name: "Gold Berry", location: 0x0, type: 0x2, order: 43 },
  { index: 0xaf, name: "Squirt Bottle", location: 0x2, type: 0xa, order: 164 },
  // { index: 0xb0, name: "Teru-Sama" },
  { index: 0xb1, name: "Park Ball", location: 0x1, type: 0x0, order: 10 },
  { index: 0xb2, name: "Rainbow Wing", location: 0x2, type: 0xa, order: 159 },
  // { index: 0xb3, name: "Teru-Sama" },
  { index: 0xb4, name: "Brick Piece", location: 0x0, type: 0x9, order: 134 },
  { index: 0xb5, name: "Surf Mail", location: 0x0, type: 0x8, order: 124 },
  { index: 0xb6, name: "Light-Blue Mail", location: 0x0, type: 0x8, order: 118 },
  { index: 0xb7, name: "Portrait Mail", location: 0x0, type: 0x8, order: 123 },
  { index: 0xb8, name: "Lovely Mail", location: 0x0, type: 0x8, order: 119 },
  { index: 0xb9, name: "Eon Mail", location: 0x0, type: 0x8, order: 116 },
  { index: 0xba, name: "Morph Mail", location: 0x0, type: 0x8, order: 121 },
  { index: 0xbb, name: "Blue Sky Mail", location: 0x0, type: 0x8, order: 115 },
  { index: 0xbc, name: "Music Mail", location: 0x0, type: 0x8, order: 122 },
  { index: 0xbd, name: "Mirage Mail", location: 0x0, type: 0x8, order: 120 },
  // { index: 0xbe, name: "Teru-Sama" },
  { index: 0xbf, name: "TM01 Dynamic Punch", location: 0x3, type: 0xb, order: 165 },
  { index: 0xc0, name: "TM02 Headbutt", location: 0x3, type: 0xb, order: 166 },
  { index: 0xc1, name: "TM03 Curse", location: 0x3, type: 0xb, order: 167 },
  { index: 0xc2, name: "TM04 Rollout", location: 0x3, type: 0xb, order: 168 },
  // { index: 0xc3, name: "Teru-Sama" },
  { index: 0xc4, name: "TM05 Roar", location: 0x3, type: 0xb, order: 169 },
  { index: 0xc5, name: "TM06 Toxic", location: 0x3, type: 0xb, order: 170 },
  { index: 0xc6, name: "TM07 Zap Cannon", location: 0x3, type: 0xb, order: 171 },
  { index: 0xc7, name: "TM08 Rock Smash", location: 0x3, type: 0xb, order: 172 },
  { index: 0xc8, name: "TM09 Psych Up", location: 0x3, type: 0xb, order: 173 },
  { index: 0xc9, name: "TM10 Hidden Power", location: 0x3, type: 0xb, order: 174 },
  { index: 0xca, name: "TM11 Sunny Day", location: 0x3, type: 0xb, order: 175 },
  { index: 0xcb, name: "TM12 Sweet Scent", location: 0x3, type: 0xb, order: 176 },
  { index: 0xcc, name: "TM13 Snore", location: 0x3, type: 0xb, order: 177 },
  { index: 0xcd, name: "TM14 Blizzard", location: 0x3, type: 0xb, order: 178 },
  { index: 0xce, name: "TM15 Hyper Beam", location: 0x3, type: 0xb, order: 179 },
  { index: 0xcf, name: "TM16 Icy Wind", location: 0x3, type: 0xb, order: 180 },
  { index: 0xd0, name: "TM17 Protect", location: 0x3, type: 0xb, order: 181 },
  { index: 0xd1, name: "TM18 Rain Dance", location: 0x3, type: 0xb, order: 182 },
  { index: 0xd2, name: "TM19 Giga Drain", location: 0x3, type: 0xb, order: 183 },
  { index: 0xd3, name: "TM20 Endure", location: 0x3, type: 0xb, order: 184 },
  { index: 0xd4, name: "TM21 Frustration", location: 0x3, type: 0xb, order: 185 },
  { index: 0xd5, name: "TM22 Solar Beam", location: 0x3, type: 0xb, order: 186 },
  { index: 0xd6, name: "TM23 Iron Tail", location: 0x3, type: 0xb, order: 187 },
  { index: 0xd7, name: "TM24 Dragon Breath", location: 0x3, type: 0xb, order: 188 },
  { index: 0xd8, name: "TM25 Thunder", location: 0x3, type: 0xb, order: 189 },
  { index: 0xd9, name: "TM26 Earthquake", location: 0x3, type: 0xb, order: 190 },
  { index: 0xda, name: "TM27 Return", location: 0x3, type: 0xb, order: 191 },
  { index: 0xdb, name: "TM28 Dig", location: 0x3, type: 0xb, order: 192 },
  // { index: 0xdc, name: "Teru-Sama" },
  { index: 0xdd, name: "TM29 Psychic", location: 0x3, type: 0xb, order: 193 },
  { index: 0xde, name: "TM30 Shadow Ball", location: 0x3, type: 0xb, order: 194 },
  { index: 0xdf, name: "TM31 Mud-Slap", location: 0x3, type: 0xb, order: 195 },
  { index: 0xe0, name: "TM32 Double Team", location: 0x3, type: 0xb, order: 196 },
  { index: 0xe1, name: "TM33 Ice Punch", location: 0x3, type: 0xb, order: 197 },
  { index: 0xe2, name: "TM34 Swagger", location: 0x3, type: 0xb, order: 198 },
  { index: 0xe3, name: "TM35 Sleep Talk", location: 0x3, type: 0xb, order: 199 },
  { index: 0xe4, name: "TM36 Sludge Bomb", location: 0x3, type: 0xb, order: 200 },
  { index: 0xe5, name: "TM37 Sandstorm", location: 0x3, type: 0xb, order: 201 },
  { index: 0xe6, name: "TM38 Fire Blast", location: 0x3, type: 0xb, order: 202 },
  { index: 0xe7, name: "TM39 Swift", location: 0x3, type: 0xb, order: 203 },
  { index: 0xe8, name: "TM40 Defense Curl", location: 0x3, type: 0xb, order: 204 },
  { index: 0xe9, name: "TM41 Thunder Punch", location: 0x3, type: 0xb, order: 205 },
  { index: 0xea, name: "TM42 Dream Eater", location: 0x3, type: 0xb, order: 206 },
  { index: 0xeb, name: "TM43 Detect", location: 0x3, type: 0xb, order: 207 },
  { index: 0xec, name: "TM44 Rest", location: 0x3, type: 0xb, order: 208 },
  { index: 0xed, name: "TM45 Attract", location: 0x3, type: 0xb, order: 209 },
  { index: 0xee, name: "TM46 Thief", location: 0x3, type: 0xb, order: 210 },
  { index: 0xef, name: "TM47 Steel Wing", location: 0x3, type: 0xb, order: 211 },
  { index: 0xf0, name: "TM48 Fire Punch", location: 0x3, type: 0xb, order: 212 },
  { index: 0xf1, name: "TM49 Fury Cutter", location: 0x3, type: 0xb, order: 213 },
  { index: 0xf2, name: "TM50 Nightmare", location: 0x3, type: 0xb, order: 214 },
  { index: 0xf3, name: "HM01 Cut", location: 0x3, type: 0xc, order: 215 },
  { index: 0xf4, name: "HM02 Fly", location: 0x3, type: 0xc, order: 216 },
  { index: 0xf5, name: "HM03 Surf", location: 0x3, type: 0xc, order: 217 },
  { index: 0xf6, name: "HM04 Strength", location: 0x3, type: 0xc, order: 218 },
  { index: 0xf7, name: "HM05 Flash", location: 0x3, type: 0xc, order: 219 },
  { index: 0xf8, name: "HM06 Whirlpool", location: 0x3, type: 0xc, order: 220 },
  { index: 0xf9, name: "HM07 Waterfall", location: 0x3, type: 0xc, order: 221 },
  // { index: 0xfa, name: "Teru-Sama" },
  // { index: 0xfb, name: "Teru-Sama" },
  // { index: 0xfc, name: "Teru-Sama" },
  // { index: 0xfd, name: "Teru-Sama" },
  // { index: 0xfe, name: "Teru-Sama" },
];

export const bagItems: Resource = {};
export const items: Resource = {};
export const keyItems: Resource = {};
export const mails: Resource = {};
export const pokeballs: Resource = {};

export const bagItemsOrder: number[] = [0x0];
export const itemsOrder: number[] = [0x0];
export const keyItemsOrder: number[] = [0x0];
export const pokeballsOrder: number[] = [0x0];

export const bagItemsGroups: ResourceGroups = itemTypes.map((type) => ({
  name: type.name,
  options: [],
}));
export const itemsGroups: ResourceGroups = itemTypes.map((type) => ({
  name: type.name,
  options: [],
}));

itemList
  .sort((a, b) => a.order - b.order)
  .forEach((item) => {
    items[item.index] = item.name;
    itemsOrder.push(item.index);
    itemsGroups[item.type].options.push(item.index);

    if (item.type === 0x8) {
      mails[item.index] = item.name;
    }

    switch (item.location) {
      case 0x0:
        bagItems[item.index] = item.name;
        bagItemsOrder.push(item.index);
        bagItemsGroups[item.type].options.push(item.index);
        break;
      case 0x1:
        pokeballs[item.index] = item.name;
        pokeballsOrder.push(item.index);
        break;
      case 0x2:
        keyItems[item.index] = item.name;
        keyItemsOrder.push(item.index);
        break;
    }
  });

export const moveList = [
  { index: 0x1, name: "Pound", maxPP: 35 },
  { index: 0x2, name: "Karate Chop", maxPP: 25 },
  { index: 0x3, name: "Double Slap", maxPP: 10 },
  { index: 0x4, name: "Comet Punch", maxPP: 15 },
  { index: 0x5, name: "Mega Punch", maxPP: 20 },
  { index: 0x6, name: "Pay Day", maxPP: 20 },
  { index: 0x7, name: "Fire Punch", maxPP: 15 },
  { index: 0x8, name: "Ice Punch", maxPP: 15 },
  { index: 0x9, name: "Thunder Punch", maxPP: 15 },
  { index: 0xa, name: "Scratch", maxPP: 35 },
  { index: 0xb, name: "Vise Grip", maxPP: 30 },
  { index: 0xc, name: "Guillotine", maxPP: 5 },
  { index: 0xd, name: "Razor Wind", maxPP: 10 },
  { index: 0xe, name: "Swords Dance", maxPP: 30 },
  { index: 0xf, name: "Cut", maxPP: 30 },
  { index: 0x10, name: "Gust", maxPP: 35 },
  { index: 0x11, name: "Wing Attack", maxPP: 35 },
  { index: 0x12, name: "Whirlwind", maxPP: 20 },
  { index: 0x13, name: "Fly", maxPP: 15 },
  { index: 0x14, name: "Bind", maxPP: 20 },
  { index: 0x15, name: "Slam", maxPP: 20 },
  { index: 0x16, name: "Vine Whip", maxPP: 10 },
  { index: 0x17, name: "Stomp", maxPP: 20 },
  { index: 0x18, name: "Double Kick", maxPP: 30 },
  { index: 0x19, name: "Mega Kick", maxPP: 5 },
  { index: 0x1a, name: "Jump Kick", maxPP: 25 },
  { index: 0x1b, name: "Rolling Kick", maxPP: 15 },
  { index: 0x1c, name: "Sand Attack", maxPP: 15 },
  { index: 0x1d, name: "Headbutt", maxPP: 15 },
  { index: 0x1e, name: "Horn Attack", maxPP: 25 },
  { index: 0x1f, name: "Fury Attack", maxPP: 20 },
  { index: 0x20, name: "Horn Drill", maxPP: 5 },
  { index: 0x21, name: "Tackle", maxPP: 35 },
  { index: 0x22, name: "Body Slam", maxPP: 15 },
  { index: 0x23, name: "Wrap", maxPP: 20 },
  { index: 0x24, name: "Take Down", maxPP: 20 },
  { index: 0x25, name: "Thrash", maxPP: 20 },
  { index: 0x26, name: "Double-Edge", maxPP: 15 },
  { index: 0x27, name: "Tail Whip", maxPP: 30 },
  { index: 0x28, name: "Poison Sting", maxPP: 35 },
  { index: 0x29, name: "Twineedle", maxPP: 20 },
  { index: 0x2a, name: "Pin Missile", maxPP: 20 },
  { index: 0x2b, name: "Leer", maxPP: 30 },
  { index: 0x2c, name: "Bite", maxPP: 25 },
  { index: 0x2d, name: "Growl", maxPP: 40 },
  { index: 0x2e, name: "Roar", maxPP: 20 },
  { index: 0x2f, name: "Sing", maxPP: 15 },
  { index: 0x30, name: "Supersonic", maxPP: 20 },
  { index: 0x31, name: "Sonic Boom", maxPP: 20 },
  { index: 0x32, name: "Disable", maxPP: 20 },
  { index: 0x33, name: "Acid", maxPP: 30 },
  { index: 0x34, name: "Ember", maxPP: 25 },
  { index: 0x35, name: "Flamethrower", maxPP: 15 },
  { index: 0x36, name: "Mist", maxPP: 30 },
  { index: 0x37, name: "Water Gun", maxPP: 25 },
  { index: 0x38, name: "Hydro Pump", maxPP: 5 },
  { index: 0x39, name: "Surf", maxPP: 15 },
  { index: 0x3a, name: "Ice Beam", maxPP: 10 },
  { index: 0x3b, name: "Blizzard", maxPP: 5 },
  { index: 0x3c, name: "Psybeam", maxPP: 20 },
  { index: 0x3d, name: "Bubble Beam", maxPP: 20 },
  { index: 0x3e, name: "Aurora Beam", maxPP: 20 },
  { index: 0x3f, name: "Hyper Beam", maxPP: 5 },
  { index: 0x40, name: "Peck", maxPP: 35 },
  { index: 0x41, name: "Drill Peck", maxPP: 20 },
  { index: 0x42, name: "Submission", maxPP: 25 },
  { index: 0x43, name: "Low Kick", maxPP: 20 },
  { index: 0x44, name: "Counter", maxPP: 20 },
  { index: 0x45, name: "Seismic Toss", maxPP: 20 },
  { index: 0x46, name: "Strength", maxPP: 15 },
  { index: 0x47, name: "Absorb", maxPP: 20 },
  { index: 0x48, name: "Mega Drain", maxPP: 10 },
  { index: 0x49, name: "Leech Seed", maxPP: 10 },
  { index: 0x4a, name: "Growth", maxPP: 40 },
  { index: 0x4b, name: "Razor Leaf", maxPP: 25 },
  { index: 0x4c, name: "Solar Beam", maxPP: 10 },
  { index: 0x4d, name: "Poison Powder", maxPP: 35 },
  { index: 0x4e, name: "Stun Spore", maxPP: 30 },
  { index: 0x4f, name: "Sleep Powder", maxPP: 15 },
  { index: 0x50, name: "Petal Dance", maxPP: 20 },
  { index: 0x51, name: "String Shot", maxPP: 40 },
  { index: 0x52, name: "Dragon Rage", maxPP: 10 },
  { index: 0x53, name: "Fire Spin", maxPP: 15 },
  { index: 0x54, name: "Thunder Shock", maxPP: 30 },
  { index: 0x55, name: "Thunderbolt", maxPP: 15 },
  { index: 0x56, name: "Thunder Wave", maxPP: 20 },
  { index: 0x57, name: "Thunder", maxPP: 10 },
  { index: 0x58, name: "Rock Throw", maxPP: 15 },
  { index: 0x59, name: "Earthquake", maxPP: 10 },
  { index: 0x5a, name: "Fissure", maxPP: 5 },
  { index: 0x5b, name: "Dig", maxPP: 10 },
  { index: 0x5c, name: "Toxic", maxPP: 10 },
  { index: 0x5d, name: "Confusion", maxPP: 25 },
  { index: 0x5e, name: "Psychic", maxPP: 10 },
  { index: 0x5f, name: "Hypnosis", maxPP: 20 },
  { index: 0x60, name: "Meditate", maxPP: 40 },
  { index: 0x61, name: "Agility", maxPP: 30 },
  { index: 0x62, name: "Quick Attack", maxPP: 30 },
  { index: 0x63, name: "Rage", maxPP: 20 },
  { index: 0x64, name: "Teleport", maxPP: 20 },
  { index: 0x65, name: "Night Shade", maxPP: 15 },
  { index: 0x66, name: "Mimic", maxPP: 10 },
  { index: 0x67, name: "Screech", maxPP: 40 },
  { index: 0x68, name: "Double Team", maxPP: 15 },
  { index: 0x69, name: "Recover", maxPP: 20 },
  { index: 0x6a, name: "Harden", maxPP: 30 },
  { index: 0x6b, name: "Minimize", maxPP: 20 },
  { index: 0x6c, name: "Smokescreen", maxPP: 20 },
  { index: 0x6d, name: "Confuse Ray", maxPP: 10 },
  { index: 0x6e, name: "Withdraw", maxPP: 40 },
  { index: 0x6f, name: "Defense Curl", maxPP: 40 },
  { index: 0x70, name: "Barrier", maxPP: 30 },
  { index: 0x71, name: "Light Screen", maxPP: 30 },
  { index: 0x72, name: "Haze", maxPP: 30 },
  { index: 0x73, name: "Reflect", maxPP: 20 },
  { index: 0x74, name: "Focus Energy", maxPP: 30 },
  { index: 0x75, name: "Bide", maxPP: 10 },
  { index: 0x76, name: "Metronome", maxPP: 10 },
  { index: 0x77, name: "Mirror Move", maxPP: 20 },
  { index: 0x78, name: "Self-Destruct", maxPP: 5 },
  { index: 0x79, name: "Egg Bomb", maxPP: 10 },
  { index: 0x7a, name: "Lick", maxPP: 30 },
  { index: 0x7b, name: "Smog", maxPP: 20 },
  { index: 0x7c, name: "Sludge", maxPP: 20 },
  { index: 0x7d, name: "Bone Club", maxPP: 20 },
  { index: 0x7e, name: "Fire Blast", maxPP: 5 },
  { index: 0x7f, name: "Waterfall", maxPP: 15 },
  { index: 0x80, name: "Clamp", maxPP: 10 },
  { index: 0x81, name: "Swift", maxPP: 20 },
  { index: 0x82, name: "Skull Bash", maxPP: 15 },
  { index: 0x83, name: "Spike Cannon", maxPP: 15 },
  { index: 0x84, name: "Constrict", maxPP: 35 },
  { index: 0x85, name: "Amnesia", maxPP: 20 },
  { index: 0x86, name: "Kinesis", maxPP: 15 },
  { index: 0x87, name: "Soft-Boiled", maxPP: 10 },
  { index: 0x88, name: "High Jump Kick", maxPP: 20 },
  { index: 0x89, name: "Glare", maxPP: 30 },
  { index: 0x8a, name: "Dream Eater", maxPP: 15 },
  { index: 0x8b, name: "Poison Gas", maxPP: 40 },
  { index: 0x8c, name: "Barrage", maxPP: 20 },
  { index: 0x8d, name: "Leech Life", maxPP: 15 },
  { index: 0x8e, name: "Lovely Kiss", maxPP: 10 },
  { index: 0x8f, name: "Sky Attack", maxPP: 5 },
  { index: 0x90, name: "Transform", maxPP: 10 },
  { index: 0x91, name: "Bubble", maxPP: 30 },
  { index: 0x92, name: "Dizzy Punch", maxPP: 10 },
  { index: 0x93, name: "Spore", maxPP: 15 },
  { index: 0x94, name: "Flash", maxPP: 20 },
  { index: 0x95, name: "Psywave", maxPP: 15 },
  { index: 0x96, name: "Splash", maxPP: 40 },
  { index: 0x97, name: "Acid Armor", maxPP: 40 },
  { index: 0x98, name: "Crabhammer", maxPP: 10 },
  { index: 0x99, name: "Explosion", maxPP: 5 },
  { index: 0x9a, name: "Fury Swipes", maxPP: 15 },
  { index: 0x9b, name: "Bonemerang", maxPP: 10 },
  { index: 0x9c, name: "Rest", maxPP: 10 },
  { index: 0x9d, name: "Rock Slide", maxPP: 10 },
  { index: 0x9e, name: "Hyper Fang", maxPP: 15 },
  { index: 0x9f, name: "Sharpen", maxPP: 30 },
  { index: 0xa0, name: "Conversion", maxPP: 30 },
  { index: 0xa1, name: "Tri Attack", maxPP: 10 },
  { index: 0xa2, name: "Super Fang", maxPP: 10 },
  { index: 0xa3, name: "Slash", maxPP: 20 },
  { index: 0xa4, name: "Substitute", maxPP: 10 },
  { index: 0xa5, name: "Struggle", maxPP: 1 },
  { index: 0xa6, name: "Sketch", maxPP: 1 },
  { index: 0xa7, name: "Triple Kick", maxPP: 10 },
  { index: 0xa8, name: "Thief", maxPP: 10 },
  { index: 0xa9, name: "Spider Web", maxPP: 10 },
  { index: 0xaa, name: "Mind Reader", maxPP: 5 },
  { index: 0xab, name: "Nightmare", maxPP: 15 },
  { index: 0xac, name: "Flame Wheel", maxPP: 25 },
  { index: 0xad, name: "Snore", maxPP: 15 },
  { index: 0xae, name: "Curse", maxPP: 10 },
  { index: 0xaf, name: "Flail", maxPP: 15 },
  { index: 0xb0, name: "Conversion 2", maxPP: 30 },
  { index: 0xb1, name: "Aeroblast", maxPP: 5 },
  { index: 0xb2, name: "Cotton Spore", maxPP: 40 },
  { index: 0xb3, name: "Reversal", maxPP: 15 },
  { index: 0xb4, name: "Spite", maxPP: 10 },
  { index: 0xb5, name: "Powder Snow", maxPP: 25 },
  { index: 0xb6, name: "Protect", maxPP: 10 },
  { index: 0xb7, name: "Mach Punch", maxPP: 30 },
  { index: 0xb8, name: "Scary Face", maxPP: 10 },
  { index: 0xb9, name: "Faint Attack", maxPP: 20 },
  { index: 0xba, name: "Sweet Kiss", maxPP: 10 },
  { index: 0xbb, name: "Belly Drum", maxPP: 10 },
  { index: 0xbc, name: "Sludge Bomb", maxPP: 10 },
  { index: 0xbd, name: "Mud-Slap", maxPP: 10 },
  { index: 0xbe, name: "Octazooka", maxPP: 10 },
  { index: 0xbf, name: "Spikes", maxPP: 20 },
  { index: 0xc0, name: "Zap Cannon", maxPP: 5 },
  { index: 0xc1, name: "Foresight", maxPP: 40 },
  { index: 0xc2, name: "Destiny Bond", maxPP: 5 },
  { index: 0xc3, name: "Perish Song", maxPP: 5 },
  { index: 0xc4, name: "Icy Wind", maxPP: 15 },
  { index: 0xc5, name: "Detect", maxPP: 5 },
  { index: 0xc6, name: "Bone Rush", maxPP: 10 },
  { index: 0xc7, name: "Lock-On", maxPP: 5 },
  { index: 0xc8, name: "Outrage", maxPP: 15 },
  { index: 0xc9, name: "Sandstorm", maxPP: 10 },
  { index: 0xca, name: "Giga Drain", maxPP: 5 },
  { index: 0xcb, name: "Endure", maxPP: 10 },
  { index: 0xcc, name: "Charm", maxPP: 20 },
  { index: 0xcd, name: "Rollout", maxPP: 20 },
  { index: 0xce, name: "False Swipe", maxPP: 40 },
  { index: 0xcf, name: "Swagger", maxPP: 15 },
  { index: 0xd0, name: "Milk Drink", maxPP: 10 },
  { index: 0xd1, name: "Spark", maxPP: 20 },
  { index: 0xd2, name: "Fury Cutter", maxPP: 20 },
  { index: 0xd3, name: "Steel Wing", maxPP: 25 },
  { index: 0xd4, name: "Mean Look", maxPP: 5 },
  { index: 0xd5, name: "Attract", maxPP: 15 },
  { index: 0xd6, name: "Sleep Talk", maxPP: 10 },
  { index: 0xd7, name: "Heal Bell", maxPP: 5 },
  { index: 0xd8, name: "Return", maxPP: 20 },
  { index: 0xd9, name: "Present", maxPP: 15 },
  { index: 0xda, name: "Frustration", maxPP: 20 },
  { index: 0xdb, name: "Safeguard", maxPP: 25 },
  { index: 0xdc, name: "Pain Split", maxPP: 20 },
  { index: 0xdd, name: "Sacred Fire", maxPP: 5 },
  { index: 0xde, name: "Magnitude", maxPP: 30 },
  { index: 0xdf, name: "Dynamic Punch", maxPP: 5 },
  { index: 0xe0, name: "Megahorn", maxPP: 10 },
  { index: 0xe1, name: "Dragon Breath", maxPP: 20 },
  { index: 0xe2, name: "Baton Pass", maxPP: 40 },
  { index: 0xe3, name: "Encore", maxPP: 5 },
  { index: 0xe4, name: "Pursuit", maxPP: 20 },
  { index: 0xe5, name: "Rapid Spin", maxPP: 40 },
  { index: 0xe6, name: "Sweet Scent", maxPP: 20 },
  { index: 0xe7, name: "Iron Tail", maxPP: 15 },
  { index: 0xe8, name: "Metal Claw", maxPP: 35 },
  { index: 0xe9, name: "Vital Throw", maxPP: 10 },
  { index: 0xea, name: "Morning Sun", maxPP: 5 },
  { index: 0xeb, name: "Synthesis", maxPP: 5 },
  { index: 0xec, name: "Moonlight", maxPP: 5 },
  { index: 0xed, name: "Hidden Power", maxPP: 15 },
  { index: 0xee, name: "Cross Chop", maxPP: 5 },
  { index: 0xef, name: "Twister", maxPP: 20 },
  { index: 0xf0, name: "Rain Dance", maxPP: 5 },
  { index: 0xf1, name: "Sunny Day", maxPP: 5 },
  { index: 0xf2, name: "Crunch", maxPP: 15 },
  { index: 0xf3, name: "Mirror Coat", maxPP: 20 },
  { index: 0xf4, name: "Psych Up", maxPP: 10 },
  { index: 0xf5, name: "Extreme Speed", maxPP: 5 },
  { index: 0xf6, name: "Ancient Power", maxPP: 5 },
  { index: 0xf7, name: "Shadow Ball", maxPP: 15 },
  { index: 0xf8, name: "Future Sight", maxPP: 15 },
  { index: 0xf9, name: "Rock Smash", maxPP: 15 },
  { index: 0xfa, name: "Whirlpool", maxPP: 15 },
  { index: 0xfb, name: "Beat Up", maxPP: 10 },
];

export const moves = moveList.reduce((moves: Resource, move) => {
  moves[move.index] = move.name;

  return moves;
}, {});

export const pokemonList = [
  { index: 0x1, name: "001 Bulbasaur", genderThreshold: 2 },
  { index: 0x2, name: "002 Ivysaur", genderThreshold: 2 },
  { index: 0x3, name: "003 Venusaur", genderThreshold: 2 },
  { index: 0x4, name: "004 Charmander", genderThreshold: 2 },
  { index: 0x5, name: "005 Charmeleon", genderThreshold: 2 },
  { index: 0x6, name: "006 Charizard", genderThreshold: 2 },
  { index: 0x7, name: "007 Squirtle", genderThreshold: 2 },
  { index: 0x8, name: "008 Wartortle", genderThreshold: 2 },
  { index: 0x9, name: "009 Blastoise", genderThreshold: 2 },
  { index: 0xa, name: "010 Caterpie", genderThreshold: 8 },
  { index: 0xb, name: "011 Metapod", genderThreshold: 8 },
  { index: 0xc, name: "012 Butterfree", genderThreshold: 8 },
  { index: 0xd, name: "013 Weedle", genderThreshold: 8 },
  { index: 0xe, name: "014 Kakuna", genderThreshold: 8 },
  { index: 0xf, name: "015 Beedrill", genderThreshold: 8 },
  { index: 0x10, name: "016 Pidgey", genderThreshold: 8 },
  { index: 0x11, name: "017 Pidgeotto", genderThreshold: 8 },
  { index: 0x12, name: "018 Pidgeot", genderThreshold: 8 },
  { index: 0x13, name: "019 Rattata", genderThreshold: 8 },
  { index: 0x14, name: "020 Raticate", genderThreshold: 8 },
  { index: 0x15, name: "021 Spearow", genderThreshold: 8 },
  { index: 0x16, name: "022 Fearow", genderThreshold: 8 },
  { index: 0x17, name: "023 Ekans", genderThreshold: 8 },
  { index: 0x18, name: "024 Arbok", genderThreshold: 8 },
  { index: 0x19, name: "025 Pikachu", genderThreshold: 8 },
  { index: 0x1a, name: "026 Raichu", genderThreshold: 8 },
  { index: 0x1b, name: "027 Sandshrew", genderThreshold: 8 },
  { index: 0x1c, name: "028 Sandslash", genderThreshold: 8 },
  { index: 0x1d, name: "029 Nidoran♀", genderThreshold: 16 },
  { index: 0x1e, name: "030 Nidorina", genderThreshold: 16 },
  { index: 0x1f, name: "031 Nidoqueen", genderThreshold: 16 },
  { index: 0x20, name: "032 Nidoran♂", genderThreshold: 0 },
  { index: 0x21, name: "033 Nidorino", genderThreshold: 0 },
  { index: 0x22, name: "034 Nidoking", genderThreshold: 0 },
  { index: 0x23, name: "035 Clefairy", genderThreshold: 12 },
  { index: 0x24, name: "036 Clefable", genderThreshold: 12 },
  { index: 0x25, name: "037 Vulpix", genderThreshold: 12 },
  { index: 0x26, name: "038 Ninetales", genderThreshold: 12 },
  { index: 0x27, name: "039 Jigglypuff", genderThreshold: 12 },
  { index: 0x28, name: "040 Wigglytuff", genderThreshold: 12 },
  { index: 0x29, name: "041 Zubat", genderThreshold: 8 },
  { index: 0x2a, name: "042 Golbat", genderThreshold: 8 },
  { index: 0x2b, name: "043 Oddish", genderThreshold: 8 },
  { index: 0x2c, name: "044 Gloom", genderThreshold: 8 },
  { index: 0x2d, name: "045 Vileplume", genderThreshold: 8 },
  { index: 0x2e, name: "046 Paras", genderThreshold: 8 },
  { index: 0x2f, name: "047 Parasect", genderThreshold: 8 },
  { index: 0x30, name: "048 Venonat", genderThreshold: 8 },
  { index: 0x31, name: "049 Venomoth", genderThreshold: 8 },
  { index: 0x32, name: "050 Diglett", genderThreshold: 8 },
  { index: 0x33, name: "051 Dugtrio", genderThreshold: 8 },
  { index: 0x34, name: "052 Meowth", genderThreshold: 8 },
  { index: 0x35, name: "053 Persian", genderThreshold: 8 },
  { index: 0x36, name: "054 Psyduck", genderThreshold: 8 },
  { index: 0x37, name: "055 Golduck", genderThreshold: 8 },
  { index: 0x38, name: "056 Mankey", genderThreshold: 8 },
  { index: 0x39, name: "057 Primeape", genderThreshold: 8 },
  { index: 0x3a, name: "058 Growlithe", genderThreshold: 4 },
  { index: 0x3b, name: "059 Arcanine", genderThreshold: 4 },
  { index: 0x3c, name: "060 Poliwag", genderThreshold: 8 },
  { index: 0x3d, name: "061 Poliwhirl", genderThreshold: 8 },
  { index: 0x3e, name: "062 Poliwrath", genderThreshold: 8 },
  { index: 0x3f, name: "063 Abra", genderThreshold: 4 },
  { index: 0x40, name: "064 Kadabra", genderThreshold: 4 },
  { index: 0x41, name: "065 Alakazam", genderThreshold: 4 },
  { index: 0x42, name: "066 Machop", genderThreshold: 4 },
  { index: 0x43, name: "067 Machoke", genderThreshold: 4 },
  { index: 0x44, name: "068 Machamp", genderThreshold: 4 },
  { index: 0x45, name: "069 Bellsprout", genderThreshold: 8 },
  { index: 0x46, name: "070 Weepinbell", genderThreshold: 8 },
  { index: 0x47, name: "071 Victreebel", genderThreshold: 8 },
  { index: 0x48, name: "072 Tentacool", genderThreshold: 8 },
  { index: 0x49, name: "073 Tentacruel", genderThreshold: 8 },
  { index: 0x4a, name: "074 Geodude", genderThreshold: 8 },
  { index: 0x4b, name: "075 Graveler", genderThreshold: 8 },
  { index: 0x4c, name: "076 Golem", genderThreshold: 8 },
  { index: 0x4d, name: "077 Ponyta", genderThreshold: 8 },
  { index: 0x4e, name: "078 Rapidash", genderThreshold: 8 },
  { index: 0x4f, name: "079 Slowpoke", genderThreshold: 8 },
  { index: 0x50, name: "080 Slowbro", genderThreshold: 8 },
  { index: 0x51, name: "081 Magnemite", genderThreshold: -1 },
  { index: 0x52, name: "082 Magneton", genderThreshold: -1 },
  { index: 0x53, name: "083 Farfetch'd", genderThreshold: 8 },
  { index: 0x54, name: "084 Doduo", genderThreshold: 8 },
  { index: 0x55, name: "085 Dodrio", genderThreshold: 8 },
  { index: 0x56, name: "086 Seel", genderThreshold: 8 },
  { index: 0x57, name: "087 Dewgong", genderThreshold: 8 },
  { index: 0x58, name: "088 Grimer", genderThreshold: 8 },
  { index: 0x59, name: "089 Muk", genderThreshold: 8 },
  { index: 0x5a, name: "090 Shellder", genderThreshold: 8 },
  { index: 0x5b, name: "091 Cloyster", genderThreshold: 8 },
  { index: 0x5c, name: "092 Gastly", genderThreshold: 8 },
  { index: 0x5d, name: "093 Haunter", genderThreshold: 8 },
  { index: 0x5e, name: "094 Gengar", genderThreshold: 8 },
  { index: 0x5f, name: "095 Onix", genderThreshold: 8 },
  { index: 0x60, name: "096 Drowzee", genderThreshold: 8 },
  { index: 0x61, name: "097 Hypno", genderThreshold: 8 },
  { index: 0x62, name: "098 Krabby", genderThreshold: 8 },
  { index: 0x63, name: "099 Kingler", genderThreshold: 8 },
  { index: 0x64, name: "100 Voltorb", genderThreshold: -1 },
  { index: 0x65, name: "101 Electrode", genderThreshold: -1 },
  { index: 0x66, name: "102 Exeggcute", genderThreshold: 8 },
  { index: 0x67, name: "103 Exeggutor", genderThreshold: 8 },
  { index: 0x68, name: "104 Cubone", genderThreshold: 8 },
  { index: 0x69, name: "105 Marowak", genderThreshold: 8 },
  { index: 0x6a, name: "106 Hitmonlee", genderThreshold: 0 },
  { index: 0x6b, name: "107 Hitmonchan", genderThreshold: 0 },
  { index: 0x6c, name: "108 Lickitung", genderThreshold: 8 },
  { index: 0x6d, name: "109 Koffing", genderThreshold: 8 },
  { index: 0x6e, name: "110 Weezing", genderThreshold: 8 },
  { index: 0x6f, name: "111 Rhyhorn", genderThreshold: 8 },
  { index: 0x70, name: "112 Rhydon", genderThreshold: 8 },
  { index: 0x71, name: "113 Chansey", genderThreshold: 16 },
  { index: 0x72, name: "114 Tangela", genderThreshold: 8 },
  { index: 0x73, name: "115 Kangaskhan", genderThreshold: 16 },
  { index: 0x74, name: "116 Horsea", genderThreshold: 8 },
  { index: 0x75, name: "117 Seadra", genderThreshold: 8 },
  { index: 0x76, name: "118 Goldeen", genderThreshold: 8 },
  { index: 0x77, name: "119 Seaking", genderThreshold: 8 },
  { index: 0x78, name: "120 Staryu", genderThreshold: -1 },
  { index: 0x79, name: "121 Starmie", genderThreshold: -1 },
  { index: 0x7a, name: "122 Mr. Mime", genderThreshold: 8 },
  { index: 0x7b, name: "123 Scyther", genderThreshold: 8 },
  { index: 0x7c, name: "124 Jynx", genderThreshold: 16 },
  { index: 0x7d, name: "125 Electabuzz", genderThreshold: 4 },
  { index: 0x7e, name: "126 Magmar", genderThreshold: 4 },
  { index: 0x7f, name: "127 Pinsir", genderThreshold: 8 },
  { index: 0x80, name: "128 Tauros", genderThreshold: 0 },
  { index: 0x81, name: "129 Magikarp", genderThreshold: 8 },
  { index: 0x82, name: "130 Gyarados", genderThreshold: 8 },
  { index: 0x83, name: "131 Lapras", genderThreshold: 8 },
  { index: 0x84, name: "132 Ditto", genderThreshold: -1 },
  { index: 0x85, name: "133 Eevee", genderThreshold: 2 },
  { index: 0x86, name: "134 Vaporeon", genderThreshold: 2 },
  { index: 0x87, name: "135 Jolteon", genderThreshold: 2 },
  { index: 0x88, name: "136 Flareon", genderThreshold: 2 },
  { index: 0x89, name: "137 Porygon", genderThreshold: -1 },
  { index: 0x8a, name: "138 Omanyte", genderThreshold: 2 },
  { index: 0x8b, name: "139 Omastar", genderThreshold: 2 },
  { index: 0x8c, name: "140 Kabuto", genderThreshold: 2 },
  { index: 0x8d, name: "141 Kabutops", genderThreshold: 2 },
  { index: 0x8e, name: "142 Aerodactyl", genderThreshold: 2 },
  { index: 0x8f, name: "143 Snorlax", genderThreshold: 2 },
  { index: 0x90, name: "144 Articuno", genderThreshold: -1 },
  { index: 0x91, name: "145 Zapdos", genderThreshold: -1 },
  { index: 0x92, name: "146 Moltres", genderThreshold: -1 },
  { index: 0x93, name: "147 Dratini", genderThreshold: 8 },
  { index: 0x94, name: "148 Dragonair", genderThreshold: 8 },
  { index: 0x95, name: "149 Dragonite", genderThreshold: 8 },
  { index: 0x96, name: "150 Mewtwo", genderThreshold: -1 },
  { index: 0x97, name: "151 Mew", genderThreshold: -1 },
  { index: 0x98, name: "152 Chikorita", genderThreshold: 2 },
  { index: 0x99, name: "153 Bayleef", genderThreshold: 2 },
  { index: 0x9a, name: "154 Meganium", genderThreshold: 2 },
  { index: 0x9b, name: "155 Cyndaquil", genderThreshold: 2 },
  { index: 0x9c, name: "156 Quilava", genderThreshold: 2 },
  { index: 0x9d, name: "157 Typhlosion", genderThreshold: 2 },
  { index: 0x9e, name: "158 Totodile", genderThreshold: 2 },
  { index: 0x9f, name: "159 Croconaw", genderThreshold: 2 },
  { index: 0xa0, name: "160 Feraligatr", genderThreshold: 2 },
  { index: 0xa1, name: "161 Sentret", genderThreshold: 8 },
  { index: 0xa2, name: "162 Furret", genderThreshold: 8 },
  { index: 0xa3, name: "163 Hoothoot", genderThreshold: 8 },
  { index: 0xa4, name: "164 Noctowl", genderThreshold: 8 },
  { index: 0xa5, name: "165 Ledyba", genderThreshold: 8 },
  { index: 0xa6, name: "166 Ledian", genderThreshold: 8 },
  { index: 0xa7, name: "167 Spinarak", genderThreshold: 8 },
  { index: 0xa8, name: "168 Ariados", genderThreshold: 8 },
  { index: 0xa9, name: "169 Crobat", genderThreshold: 8 },
  { index: 0xaa, name: "170 Chinchou", genderThreshold: 8 },
  { index: 0xab, name: "171 Lanturn", genderThreshold: 8 },
  { index: 0xac, name: "172 Pichu", genderThreshold: 8 },
  { index: 0xad, name: "173 Cleffa", genderThreshold: 12 },
  { index: 0xae, name: "174 Igglybuff", genderThreshold: 12 },
  { index: 0xaf, name: "175 Togepi", genderThreshold: 2 },
  { index: 0xb0, name: "176 Togetic", genderThreshold: 2 },
  { index: 0xb1, name: "177 Natu", genderThreshold: 8 },
  { index: 0xb2, name: "178 Xatu", genderThreshold: 8 },
  { index: 0xb3, name: "179 Mareep", genderThreshold: 8 },
  { index: 0xb4, name: "180 Flaaffy", genderThreshold: 8 },
  { index: 0xb5, name: "181 Ampharos", genderThreshold: 8 },
  { index: 0xb6, name: "182 Bellossom", genderThreshold: 8 },
  { index: 0xb7, name: "183 Marill", genderThreshold: 8 },
  { index: 0xb8, name: "184 Azumarill", genderThreshold: 8 },
  { index: 0xb9, name: "185 Sudowoodo", genderThreshold: 8 },
  { index: 0xba, name: "186 Politoed", genderThreshold: 8 },
  { index: 0xbb, name: "187 Hoppip", genderThreshold: 8 },
  { index: 0xbc, name: "188 Skiploom", genderThreshold: 8 },
  { index: 0xbd, name: "189 Jumpluff", genderThreshold: 8 },
  { index: 0xbe, name: "190 Aipom", genderThreshold: 8 },
  { index: 0xbf, name: "191 Sunkern", genderThreshold: 8 },
  { index: 0xc0, name: "192 Sunflora", genderThreshold: 8 },
  { index: 0xc1, name: "193 Yanma", genderThreshold: 8 },
  { index: 0xc2, name: "194 Wooper", genderThreshold: 8 },
  { index: 0xc3, name: "195 Quagsire", genderThreshold: 8 },
  { index: 0xc4, name: "196 Espeon", genderThreshold: 2 },
  { index: 0xc5, name: "197 Umbreon", genderThreshold: 2 },
  { index: 0xc6, name: "198 Murkrow", genderThreshold: 8 },
  { index: 0xc7, name: "199 Slowking", genderThreshold: 8 },
  { index: 0xc8, name: "200 Misdreavus", genderThreshold: 8 },
  { index: 0xc9, name: "201 Unown", genderThreshold: -1 },
  { index: 0xca, name: "202 Wobbuffet", genderThreshold: 8 },
  { index: 0xcb, name: "203 Girafarig", genderThreshold: 8 },
  { index: 0xcc, name: "204 Pineco", genderThreshold: 8 },
  { index: 0xcd, name: "205 Forretress", genderThreshold: 8 },
  { index: 0xce, name: "206 Dunsparce", genderThreshold: 8 },
  { index: 0xcf, name: "207 Gligar", genderThreshold: 8 },
  { index: 0xd0, name: "208 Steelix", genderThreshold: 8 },
  { index: 0xd1, name: "209 Snubbull", genderThreshold: 12 },
  { index: 0xd2, name: "210 Granbull", genderThreshold: 12 },
  { index: 0xd3, name: "211 Qwilfish", genderThreshold: 8 },
  { index: 0xd4, name: "212 Scizor", genderThreshold: 8 },
  { index: 0xd5, name: "213 Shuckle", genderThreshold: 8 },
  { index: 0xd6, name: "214 Heracross", genderThreshold: 8 },
  { index: 0xd7, name: "215 Sneasel", genderThreshold: 8 },
  { index: 0xd8, name: "216 Teddiursa", genderThreshold: 8 },
  { index: 0xd9, name: "217 Ursaring", genderThreshold: 8 },
  { index: 0xda, name: "218 Slugma", genderThreshold: 8 },
  { index: 0xdb, name: "219 Magcargo", genderThreshold: 8 },
  { index: 0xdc, name: "220 Swinub", genderThreshold: 8 },
  { index: 0xdd, name: "221 Piloswine", genderThreshold: 8 },
  { index: 0xde, name: "222 Corsola", genderThreshold: 12 },
  { index: 0xdf, name: "223 Remoraid", genderThreshold: 8 },
  { index: 0xe0, name: "224 Octillery", genderThreshold: 8 },
  { index: 0xe1, name: "225 Delibird", genderThreshold: 8 },
  { index: 0xe2, name: "226 Mantine", genderThreshold: 8 },
  { index: 0xe3, name: "227 Skarmory", genderThreshold: 8 },
  { index: 0xe4, name: "228 Houndour", genderThreshold: 8 },
  { index: 0xe5, name: "229 Houndoom", genderThreshold: 8 },
  { index: 0xe6, name: "230 Kingdra", genderThreshold: 8 },
  { index: 0xe7, name: "231 Phanpy", genderThreshold: 8 },
  { index: 0xe8, name: "232 Donphan", genderThreshold: 8 },
  { index: 0xe9, name: "233 Porygon2", genderThreshold: -1 },
  { index: 0xea, name: "234 Stantler", genderThreshold: 8 },
  { index: 0xeb, name: "235 Smeargle", genderThreshold: 8 },
  { index: 0xec, name: "236 Tyrogue", genderThreshold: 0 },
  { index: 0xed, name: "237 Hitmontop", genderThreshold: 0 },
  { index: 0xee, name: "238 Smoochum", genderThreshold: 16 },
  { index: 0xef, name: "239 Elekid", genderThreshold: 4 },
  { index: 0xf0, name: "240 Magby", genderThreshold: 4 },
  { index: 0xf1, name: "241 Miltank", genderThreshold: 16 },
  { index: 0xf2, name: "242 Blissey", genderThreshold: 16 },
  { index: 0xf3, name: "243 Raikou", genderThreshold: -1 },
  { index: 0xf4, name: "244 Entei", genderThreshold: -1 },
  { index: 0xf5, name: "245 Suicune", genderThreshold: -1 },
  { index: 0xf6, name: "246 Larvitar", genderThreshold: 8 },
  { index: 0xf7, name: "247 Pupitar", genderThreshold: 8 },
  { index: 0xf8, name: "248 Tyranitar", genderThreshold: 8 },
  { index: 0xf9, name: "249 Lugia", genderThreshold: -1 },
  { index: 0xfa, name: "250 Ho-Oh", genderThreshold: -1 },
  { index: 0xfb, name: "251 Celebi", genderThreshold: -1 },
];

export const pokemons: Resource = {};

pokemonList.forEach((pokemon) => {
  pokemons[pokemon.index] = pokemon.name;
});
